### ISSUE TITLE
JobScheduler - Hangfire v1.8.x

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1004]
Quick question - Is there a plan to upgrade Hangfire to version 1.8.x (currently 1.8.2)? 

Jobscheduler is currently on 1.7.34 and the max I can only go to version 1.7.35. Due to changes in 1.8.x xpand jobscheduler will not run.

Cheers

**Comment by DannyRawlings** [comment]
Changes can be found in the link below. It now uses the Microsoft.Data.SqlClient instead of System.Data.SqlClient

https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.8.html

![2023-06-19_15h46_43](https://github.com/eXpandFramework/eXpand/assets/7148712/95068bfa-ce4f-484c-89e8-ce6501059e39)

![2023-06-19_15h46_00](https://github.com/eXpandFramework/eXpand/assets/7148712/573fb7d0-bf43-4c06-9229-c40a816fcf75)

**Comment by apobekiaris** [comment]
currently there are not many active matters so sure I can push it on the lab for some time for you test it

**Comment by apobekiaris** [comment]
is there a compatible inmemory package? do u happen to know?

**Comment by DannyRawlings** [comment]
> currently there are not many active matters so sure I can push it on the lab for some time for you test it

Thank you.. :)

**Comment by DannyRawlings** [comment]
> is there a compatible inmemory package? do u happen to know?

No, it looks like there will a version 1.7.1 released soon.

**Comment by apobekiaris** [comment]
not folowing is there or not? and which one? without an InMemory package I cannot release cause the tests cannot run

**Comment by DannyRawlings** [comment]
> not folowing is there or not? and which one? without an InMemory package I cannot release cause the tests cannot run

Sorry, latest release is 0.4.1. Requires Hangfire.Core >=1.8.0

**Comment by apobekiaris** [comment]
![image](https://github.com/eXpandFramework/eXpand/assets/159464/ea8a53e3-32bf-4a2f-a691-7273efa2d8ad)

I guess this netstanard2 support may work, I will let the tests confirm it and we will see. Alternatively we need to recomompile and republish on nuget our selves. Taking that initiative it will for sure speed up the update

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
