### ISSUE TITLE
eXpandReportsV2Win dll is missing in nuget package

### ISSUE THREAD

**Issue by Kagandaj** [eXpandFramework/eXpand#1006]
eXpandReportsV2Win dll is missing in nuget package for .net 6
is this by design because i just upgraded and noticed this

**Comment by apobekiaris** [comment]
hmm yes is not there should be the project participates in the build

**Comment by Kagandaj** [comment]
so this module will not be ported to .net 6.
where there any problems porting it before i try my
self

**Comment by apobekiaris** [comment]
> the project participates in the build

maybe I was not clear enough, I will research and publish it.

**Comment by apobekiaris** [comment]
eXpand.lab release [23.1.302.1](https://github.com/eXpandFramework/eXpand.lab/releases/23.1.302.1) includes commit that relate to this task:

* [eXpandReportsV2Win dll is missing in nuget package #1006](https://github.com/eXpandFramework/eXpand.lab/commit/8242dc007a1da7a08f655b889c1bc4bebbabd6ac)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
eXpand.lab release [23.1.502.0](https://github.com/eXpandFramework/eXpand.lab/releases/23.1.502.0) includes commit that relate to this task:

* [eXpandReportsV2Win dll is missing in nuget package #1006](https://github.com/eXpandFramework/eXpand.lab/commit/b4e6a33b69e508d1efd835d034166df5a55a2413)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
