### ISSUE TITLE
Xpand.XAF.ModelEditor.Win Crashes 

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1007]
The model editor crashes when I use it at work because we behind an internet proxy. If I connect to a standard internet connection it works fine. 

This only happens after I have selected the Model from the list

Can you change it so that it ignores this error and continues to load?

![2023-06-27_13h35_59](https://github.com/eXpandFramework/eXpand/assets/7148712/c6620787-90d2-4be4-9d60-f536ba65830d)

**Comment by DannyRawlings** [comment]
Just an update - Once it has updated itself to the latest version it seems to work ok again.

**Comment by apobekiaris** [comment]
there is a setting to load from disk, but u have to manually have to do download the files

 
![image](https://github.com/eXpandFramework/eXpand/assets/159464/e684ab4e-7d85-4e8e-855e-f715011a3e3e)

you have to use the `file://` format as far as I remember


>Just an update - Once it has updated itself to the latest version it seems to work ok again.
if files are on disk it skips download

**Comment by DannyRawlings** [comment]
Cheers, I think I am missing something tho as I don't see the ModelEditor in my list

![2023-06-27_14h30_13](https://github.com/eXpandFramework/eXpand/assets/7148712/f13c2144-88d5-427d-924d-9374bd0fc5ca)

**Comment by apobekiaris** [comment]
its the configure action in the ME list

![image](https://github.com/eXpandFramework/eXpand/assets/159464/4e489f48-5b0f-4fbe-8998-c0b73f9cc071)


actually this ME list is a XAF app

**Comment by DannyRawlings** [comment]
Got it! 👍 Cheers for your help again
