### ISSUE TITLE
Model Editor - Crashes with Jobscheduler 

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1008]
I've noticed that if I don't include the the `GlobalConfiguration.Configuration.UseMemoryStorage();` in my startup.cs the Model Editor will not load. 

I don't use the MemoryStorage() extension because it causes issues with the Hangfire dashboard, plus I also use a different Database for the hangfire tables.

![2023-06-28_16h01_36](https://github.com/eXpandFramework/eXpand/assets/7148712/e02eadbc-1951-493f-9e46-6d10f4afd780)

![2023-06-29_08h25_42](https://github.com/eXpandFramework/eXpand/assets/7148712/722a5fd1-555a-48db-9106-bf86cbc4dc94)

![2023-06-29_08h58_22](https://github.com/eXpandFramework/eXpand/assets/7148712/26b61f0d-e149-4e6e-bc87-6851ed02481e)

![2023-06-29_08h59_13](https://github.com/eXpandFramework/eXpand/assets/7148712/a9d7e46f-7512-4b09-99ec-a61e24b5462b)

Cheers 

Dan

**Comment by apobekiaris** [comment]
I think it does not worth the reources pursuing the issue, you can simply check if you in desing mode and use InMemory?

```cs
AppDomain.IsRuntime()
```

**Comment by apobekiaris** [comment]
yes InMemory is a test only layer you should never consider it in production

**Comment by DannyRawlings** [comment]
Perfect.. This worked for me.

![2023-06-29_09h23_24](https://github.com/eXpandFramework/eXpand/assets/7148712/b57d813d-4fcd-4fb7-9ce7-251787773323)

**Comment by apobekiaris** [comment]
also I want to suggest that at least for me and my work I consider bad practice to touch the Model.xafml file, modules model is perfect for everything and comes with all the benefits of a module, the front end although it has a module descenant I do not consider as such.

**Comment by DannyRawlings** [comment]
Thanks, I will take that onboard going forward :)
