### ISSUE TITLE
Hangfire Job will not create sequences without login attempt

### ISSUE THREAD

**Issue by yunits** [eXpandFramework/eXpand#1010]
Hello Mr. Bekiaris,

I found another issue that needs attention if your time allows:

[DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/12012664/DXApplication4.zip)

Steps to reproduce
1. Run Blazor Application using IIS Express in Visual Studio.
2. Login and wait for database table creation. After that, restart debugging to create neccessary Hangfire tables.
3. Create a Job. Method is for example "Import Orders Authenticated" and Cron Expression "Minutely".
4. Save and trigger to see that there are sequences generated.
6. Log off and wait one minute and see there will be new sequences.
7. Now Restart debugging and stay at login page without login. Wait for Hangfire background Task to trigger and see that the sequences that will be generated are "**0**".
8. Now, even if you try to login with wrong credentials, after one minute sequences will be generated correctly.

Conclusion: There has to be at least one login attempt, before sequences will be generated correctly.

**Comment by apobekiaris** [comment]
have u tested this on on a real server? e.g. IIS?

**Comment by yunits** [comment]
I tested this on my Windows 10 Machine running real IIS Server (not from Visual Studio).
Actually we have no Windows Server, will come soon.

I will check your link later in detail.
My Jobs are working as they should. The only thing is that there is no sequence generated, until I try to login. Even if I refresh the login page, it doesn't trigger, whatever gets triggered at login attempt.

**Comment by apobekiaris** [comment]
thnks for confirming

**Comment by derwinmhrdka** [comment]
Any updates for this issue?

**Comment by apobekiaris** [comment]
no this is going to take some time as I currently occupied, however to my understanding development can be continue on your side this a production issue which will be resolved as soon as my scheduled has a gap

**Comment by apobekiaris** [comment]
no need to mention that PR are also acceptable or if u have an idea on what is wrong here and can modify the code fast for u to test, just let me know and will push immediately

**Comment by apobekiaris** [comment]
the AdditionalObjectSpaces for all nonpersistent objectspaces should have been already populated as per 
https://github.com/eXpandFramework/Reactive.XAF/blob/42582751eb4e447a59bac05324bb741ae9f9c255/src/Modules/Reactive/RXApp.cs#L108C40-L108C40


>ession.FindObject<SequenceStorage>(myCriteria);

what it means it does not work?

why do u want to use a `Session` instead of `IObjectSpace` the module uses it but there is a reason for it. the SequenceStore is a persistent object and should be queried with objectspace, however session should also work fine.

**Comment by yunits** [comment]
I use it in XPO BusinessObject class, therefore I only have Session available.

I will get back to you after some checks, thanks for the fast response.

**Comment by apobekiaris** [comment]
>objectSpace.GetSequenceStorage() uses UnitOfWork and unitOfWork inherits from Session, therefore I thoug I could use it directly.

reasoning is simple to reuse existing code cause the module operates on an ExplicitUOW so to lock the storage for updates

```cs
var sequenceStorage = explicitUnitOfWork.GetSequenceStorage(theObject.GetType(),sequenceStorageType:sequenceStorageType);
```

however one might need to query the storage for other reasons e.g. to from tests

````cs
using var objectSpace = application.CreateObjectSpace();
	        objectSpace.GetSequenceStorage(typeof(CustomSquenceNameTestObject)).Name.ShouldBe(typeof(CustomSequenceTypeName).FullName);
```

**Comment by apobekiaris** [comment]
this does not lock the storage

```cs
 objectSpace.GetSequenceStorage
```

can be used for query though but u should not update `SequenceMember`

**Comment by yunits** [comment]
yes, I do not update SequenceMember anywhere to have no conflicts.
I will check everything and get back to you after some informations about hangfire/sequence problem. That will take some time.

**Comment by apobekiaris** [comment]
I did not have the time to research the production issue yet

**Comment by yunits** [comment]
yes, therefore I want to check if I can find any issue.
I use some extensions from you and therefore I want to dig deeper into it xD

**Comment by apobekiaris** [comment]
the case is fixed in the next minor, apologies for the delay I was extremely busy building the new XAF demo for 23.2.

**Comment by apobekiaris** [comment]
The pre-release [4.231.6.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.231.6.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator does not monitor all ObjectSpaces  #1010](https://github.com/eXpandFramework/Reactive.XAF/commit/ec68bcc0706181372b319100a8db02eee71c9d47)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.231.6</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.231.6</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by yunits** [comment]
> the case is fixed in the next minor, apologies for the delay I was extremely busy building the new XAF demo for 23.2.

I was busy too and had unfortunately no time to investigate. Thanks for your time and fix.

**Comment by yunits** [comment]
Just for information in case anyone else is wondering why the queue doesn't start without visiting the Blazor Page:

`By default, Hangfire Server instance in a web application will not be started until the first user hits your site.`
As it is for example IIS related, the solution is not to be expected from xpand.
https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html

@apobekiaris maybe you can copy&paste this link into readme somewhere to notice users about this behaviour of hangfire?

**Comment by apobekiaris** [comment]
I am not sure it deserves it, cause in the same sense we should also add info about how to make an IIS site auto start and why not for other Hangfire cases? I hope you see my point, is not related at all to the JobScheduler functionality. 

[Autostarting your (ASP.NET Core) websites on IIS](https://mallibone.com/post/iis-autostart-website#:~:text=IIS%20app%20configuration&text=Then%20go%20to%20the%20website,some%20apps%20you%20are%20developing.)

**Comment by yunits** [comment]
I got your point At least we have this links in this issue, maybe someone who needs help will find this information.
I am new to IIS/Blazor therefore it was good to know for me.

**Comment by apobekiaris** [comment]
note that JobScheduler tickets are labeled so u can target your search 

https://github.com/eXpandFramework/eXpand/issues?q=label%3AJobScheduler
