### ISSUE TITLE
EMail SmtpClient unable to select UserName when using UseDefaultCredentials False 

### ISSUE THREAD

**Issue by yunits** [eXpandFramework/eXpand#1011]
Hello, I am testing your EMail Module and found an issue or maybe I miss something.

While configuring SmtpClients there is the option "UseDefaultCredentials".
If I set it to False, I should be able to see for property UserName "Property type: Xpand.XAF.Modules.Email.IModelEmailAddress, Member of interface: Xpand.XAF.Modules.Email.IModelEmailSmtpClient" entries, same as in "From" property.

[DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/12036799/DXApplication4.zip)

![image](https://github.com/eXpandFramework/eXpand/assets/59102282/da05076e-6b09-410e-9909-3b548130ce7b)

**Comment by apobekiaris** [comment]
I am not sure what u mean, anyways u could simply look where this property is used e.g. it sets the related smtpclient prop which does not do what u said

![image](https://github.com/eXpandFramework/eXpand/assets/159464/cb0b8898-1df8-43c6-a21b-d1d4fb684d4f)

in addition this how it should work 

![image](https://github.com/eXpandFramework/eXpand/assets/159464/db091a24-b7f1-48f5-b924-38e48784c7b0)


let me know if it resolves your issues

**Comment by yunits** [comment]
I mean there are no entries in my property "UserName" if I choose UseDefaultCredentials = False.
If I search at github in your repo for "Credentials" it will show me the file "Reactive.XAF/src/Modules/Email/ModelLogic.cs"

Here we have **From**, with "DataSourceProperty(nameof(FromEmails)" and **UserName** that has no DataSourceProperty.
Could that be the reason?

```
		[Required][DataSourceProperty(nameof(FromEmails))]
		IModelEmailAddress From { get; set; }
```
```
		[Category("Credentials"), ModelBrowsable(typeof(ModelSmtpClientUseDefaultCredentialsVisibilityCalculator)), Required(typeof(ModelSmtpClientDeliveryMethodRequiredCalculator))]
		IModelEmailAddress UserName { get; set; }
```

**Comment by apobekiaris** [comment]
in the same file  u see
```cs
if (smtpClient.DeliveryMethod == SmtpDeliveryMethod.Network){
                smtpClient.Host = modelSmtpClient.Host;
                smtpClient.Port = modelSmtpClient.Port;
                smtpClient.EnableSsl = modelSmtpClient.EnableSsl;
                smtpClient.UseDefaultCredentials = modelSmtpClient.UseDefaultCredentials;
                if (!smtpClient.UseDefaultCredentials){
                    smtpClient.Credentials = new NetworkCredential(modelSmtpClient.UserName.Address,
                        modelSmtpClient.Password);
                }
            }
```

so UseDefaultCredentials is only used  SmtpDeliveryMethod.Network else it has no effect. Does this makes sense?

**Comment by yunits** [comment]
yes that makes sense and looks right.

My problem is, that the property UserName will not be filled/populated with "IModelEmailAddress" entries.
It is just empty and you cannot choose any EMail address.
And if you don't choose an address, you will get validation error.

![image](https://github.com/eXpandFramework/eXpand/assets/59102282/0e978a24-c646-4a07-83a4-4a0a96270f68)

**Comment by apobekiaris** [comment]
https://user-images.githubusercontent.com/159464/253209132-db091a24-b7f1-48f5-b924-38e48784c7b0.png

do u have entries in the EmailAddresses

**Comment by yunits** [comment]
yes.
You also see that I can choose my test address in From Property.

![image](https://github.com/eXpandFramework/eXpand/assets/59102282/6517a826-5064-4da5-b834-6b3c73dcb059)


I still think that "[DataSourceProperty(nameof(FromEmails))]" is missing above IModelEmailAddress UserName { get; set; }?

**Comment by apobekiaris** [comment]
ah now i got it apologies, anyways I will push asap,in the meantime u may try to override it with something like 

```cs
[ModelDisplayName("SmtpClient")]
	public interface IModelEmailSmtpClientEx : IModelNode {
		[DataSourceProperty("Emails")]
		[Category("Credentials"), ModelBrowsable(typeof(ModelSmtpClientUseDefaultCredentialsVisibilityCalculator)), Required(typeof(ModelSmtpClientDeliveryMethodRequiredCalculator))]
		new IModelEmailAddress UserName { get; set; }
	}
```

extend the `IModelEmailSmtpClient`

this I wrote on foot and did not test but I use similar approaches in the code so somehow near it is possible to override note the `new`

**Comment by apobekiaris** [comment]
or u can simply add it in your xafml file manuly the restriction is UI only think the code will read it even if there are no entries in the lookup

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
