### ISSUE TITLE
JobScheduler.Hangfire and EF Core 7

### ISSUE THREAD

**Issue by vassiliospallis** [eXpandFramework/eXpand#1012]
Hello, 
Is JobScheduler.Hangfire module supports EF Core 7.0?
Because I tried to install it and when started solution it seeks for the XPO libraries and gives an exception.
Thanks a lot!

**Comment by apobekiaris** [comment]
Xaf supports multiple ORM, so u can install modules on EF on XPO etc

**Comment by vassiliospallis** [comment]
Thanks a lot for your rapid answer.
My XAF project targets EF Core, I followed the instructions to install JobScheduler.Hangfire and when application started it gives an exception at startup.cs mentioning that cannot find some XPO assemblies (which is logical because an EF Core ORM doesn't include XPO libraries).
Thanks for your answer again.

**Comment by vassiliospallis** [comment]
Thanks again but I don't have this requirement (to connect to several databases).
Anyway I will search a little more to troubleshoot the issue, a big thanks for your rapid answers.

**Comment by apobekiaris** [comment]
u can use the same database/connectionstring then but two different datastores I posted the link to give the idea

**Comment by apobekiaris** [comment]
one ObjectSpaceProvider use EF and the other XPO to the same db

**Comment by vassiliospallis** [comment]
OK now I got you!
So XPO is needed indeed for the module to work and to co-exist with EF Core I have to use a workaround (2 ORMs to the same db).
A big thanks again for your elaboration.
Farewell.

**Comment by apobekiaris** [comment]
the module comes with its own Bussiness Objects that use XPO. You let it work by connecting an ObjectSpaceProvider for these types, check DX for more samples on this

**Comment by vassiliospallis** [comment]
OK now is clear.
Thanks again!
