### ISSUE TITLE
Need help downloading Xpand

### ISSUE THREAD

**Issue by CLTTris** [eXpandFramework/eXpand#1014]
https://github.com/eXpandFramework/eXpand/assets/141672485/14aa8210-fd47-460e-8669-6de9ab121d35

**Comment by apobekiaris** [comment]
we do not offer an installation see https://www.youtube.com/watch?v=LvxQ-U_0Sbg

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
