### ISSUE TITLE
Error the 'Xpand.XAF.Modules.Blazor.BlazorStartup' type is not descendant of 'DevExpress.ExpressApp.ModuleBase'

### ISSUE THREAD

**Issue by txt2203** [eXpandFramework/eXpand#1016]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
I made simple project XAF Blazor .NET6 and add Xpand.XAF.Modules.Blazor.BlazorModule 
Case 1: When running the XAF Blazor project with Xpand.XAF.Modules.Blazor.BlazorModule 
=>Error : 
DevExpress.ExpressApp.Blazor.Services.ExceptionService: Error: Handled exception occurs
System.InvalidOperationException: Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]

So I add module BlazorStartup as case 2:
Case 2: When running the XAF Blazor project with both Xpand.XAF.Modules.Blazor.BlazorModule, Xpand.XAF.Modules.Blazor.BlazorStartup => Error : 
Message:    An error with the number 1008 has occurred.
Error message: the 'Xpand.XAF.Modules.Blazor.BlazorStartup' type is not a descendant of 'DevExpress.ExpressApp.ModuleBase' (Parameter 'item')

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. Make a simple XAF Blazor .NET6 without security, no adding any Devexpress modules.
2. Add package "Xpand.XAF.Core.All" to Module project. Add package "Xpand.XAF.Web.All" to module Blazor.Server.
3. Add code to BlazorModule.cs :
+ RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup));   //case 2
+ RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Blazor.BlazorModule));  //case 1,2
[eXpressAppFramework (case 2).log](https://github.com/eXpandFramework/eXpand/files/12388459/eXpressAppFramework.case.2.log)
[eXpressAppFramework (case1).log](https://github.com/eXpandFramework/eXpand/files/12388460/eXpressAppFramework.case1.log)

**Comment by apobekiaris** [comment]
>RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup)); //case 2

this line is invalid as per the error msg 

my guess is u did not follow 

>Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]


look at these lines

https://github.com/eXpandFramework/Reactive.XAF/blob/42582751eb4e447a59bac05324bb741ae9f9c255/src/Tests/EasyTests/TestApplication/TestApplication.Blazor.Server/Startup.cs#L27-L30

u probably not need the Hangfire or the Google lines
