### ISSUE TITLE
Model Editor failed to load using Devexpress 23.1.3

### ISSUE THREAD

**Issue by novicki** [eXpandFramework/eXpand#1017]
Hello. I am using Devexpress 23.1.3 with VS2022 and I tried to install 
Xpand.Xaf.Core.All on xxx.Module project
I add the required module
RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Email.EmailModule));
After I building the solution, I try to open Model Editor
I got this error Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies cannot be loaded for execution. (0x80131058)
Model Editor failed to load. Found similar tickets. But their advice didn't help.
[XAFWithExpand2.zip](https://github.com/eXpandFramework/eXpand/files/12421378/XAFWithExpand2.zip)

**Comment by novicki** [comment]
I am trying to open a module model. What does it mean to do Xpand ME?

**Comment by apobekiaris** [comment]
see https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.XAF.ModelEditor

**Comment by novicki** [comment]
Thank you, I got it

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
