### ISSUE TITLE
ModelEditor did not open after new Version 4.231.4.1

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#1019]
Hi,

my model did not open after the new Version 4.321.4.1.
Could it be cause 4.231.4.1 is based on 23.1.5 and my project is on 23.1.4?

How can I open the model for 23.1.4?

![Screenshot 2023-09-05 194450](https://github.com/eXpandFramework/eXpand/assets/43132306/7bbc7058-7689-40fd-9262-c5beabb733df)
[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/12526620/eXpressAppFramework.log)

**Comment by apobekiaris** [comment]
I am not sure if there are incompatibilities, but I just pushed an  Xpand ME 23.1.5 version to the repo was not there before. Try it after u get notified on the release and let me know if it solves the issue

**Comment by CWolffIF** [comment]
I don´t know what you mean. But I tried again and it doesn´t work. This a little bit dramatical, cause no project opens by any employee.

**Comment by apobekiaris** [comment]
i meant I just now pushed the https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.231.5.0 does it fix the problem? Works fine with my 23.1.4 projects

**Comment by apobekiaris** [comment]
just run again the ME

**Comment by apobekiaris** [comment]
inside C:\Users\YOURUSER\AppData\Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop there should be an 4.231.5.0 folder which is the latest release is it?

**Comment by CWolffIF** [comment]
No, there is just a C:\Users\YOURUSER\AppData\Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop there should be an 4.231.4.0 folder

**Comment by apobekiaris** [comment]
it might be way easier to upgrade to 23.1.5 though as at least in my tests in an XPO empty solutions all models open without issues both in VS and Rider

**Comment by apobekiaris** [comment]
the latest Xpand ME for VS is 

![image](https://github.com/eXpandFramework/eXpand/assets/159464/b56149d5-72b6-46c7-9160-0f8e2a22eb20)

**Comment by apobekiaris** [comment]
this is what I can also verify in my local machine

1. Delete all files/folder from the C:\Users\YOURUSER\AppData\Roaming\Xpand.XAF.ModelEditor.Win
2. Create a new 23.1.4 XPO solution
3. Compile and run ME

no issues to open all models

**Comment by apobekiaris** [comment]
and got the 4.231.5.0 folder in place

**Comment by CWolffIF** [comment]
Hi,
I updated the whole project to 23.1.5 and Xpand 23.1.501. And now it loads down  4.231.5.0 and it works without an error.

**Comment by apobekiaris** [comment]
we had a happy ending then let's continue our work

**Comment by apobekiaris** [comment]
note ME has config to point to a certain release from your local disk but in my experience is easier to upgrade 

![image](https://github.com/eXpandFramework/eXpand/assets/159464/3fc26756-ba48-457a-a4c3-a4fc060f0b9e)

**Comment by CWolffIF** [comment]
What is the Field DevVersion used for?

**Comment by apobekiaris** [comment]
there is a saying like code is your friend? or something similar? :)

https://github.com/eXpandFramework/Reactive.XAF/blob/0dddcf6237e52f6e76a43fb924da7ea813eab3b4/tools/Xpand.XAF.ModelEditor/IDE/ModelEditor.Win/Xpand.XAF.ModelEditor.Module.Win/MEService.cs#L160C1-L160C1
