### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by merdiano** [eXpandFramework/eXpand#1022]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
When installing eXpandExcellImporter.Win package (23.1.503, 23.1.501, 23.1.401) it conflicts  with DevExpress.ExpressApp.CodeAnalysis 23.1.5

eXpandExcelImporter.Win 23.1.503 -> Xpand.Extensions 4.231.5 -> Microsoft.CodeAnalysis.CSharp 4.2.0 -> Microsoft.CodeAnalysis.Common (= 4.2.0) 

DevExpress.ExpressApp.CodeAnalysis 23.1.5 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).	

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. craete xaf project with devex. version 23.1.5
2. install nuget eXpandExcellImporter.Win package 23.1.503
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
package installed

**Comment by apobekiaris** [comment]
I am aware of the DevExpress.ExpressApp.CodeAnalysis problem therefore eXPand does not use it. Try remove it from your project b4 installing the nuget and let me know

**Comment by odilbek84** [comment]
I had same problem, just deleted DevExpress.ExpressApp.CodeAnalysis, no more errors. (23.1.3)

**Comment by apobekiaris** [comment]
it is also possible to keep the DevExpress.CodeAnalysis if you install 

```xml
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.7.0" />
```

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
