### ISSUE TITLE
XPand ModellEditor VS 2022 Extension

### ISSUE THREAD

**Issue by ThomasVetterling** [eXpandFramework/eXpand#1024]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
Hello dear support,
Im struggling with getting the XpandModelEditor to get running.
I just created a new 23.1 XAF solution with VS 2022.

Than I was adding the ModelMapper´Module to the platform independend Module.
Than I was compiling the whole solution and at the very end i selctede Xpand ModelEditor from the Extension Menu of VS 2022.

Now for a short period a empty window (i guess for selection of Models) gets shown, but it closes immedeately and a notification 'Parse projects' appears. Than nothing more happens. 

Can you give me a hint what i make wrong ?

Yours Thomas

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
Hi

Cannot tell at least parsing works fine on my side even for 23.2

![image](https://github.com/eXpandFramework/eXpand/assets/159464/328fef0f-d853-4023-a93b-e6e113ac2e4a)

the source is online though u can run the project your side and debug the problem

Xpand.XAF.ModelEditor.WinDesktop.csproj

**Comment by ThomasVetterling** [comment]
Thank you for your hint. It seemed that I hadn't installed all .NET SDK which were neccessary.
Now XPandModelEditor starts.

**Comment by kaman1990** [comment]
I am having the exact same issue. I get a flash on the screen and the the Parsing Notification, then nothing. Any assistance appreciated.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
