### ISSUE TITLE
Version for 23.1.6

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#1025]
Hi Tolis,

do you plan to compile agaist Devexpress 23.1.6? There are some bugfixes in Devexpress and I don´t have the know-how to compile eXpand on my own.

**Comment by apobekiaris** [comment]
I can but next weekend currently I way too busy

**Comment by CWolffIF** [comment]
Thanx, next weekend will be fine.

**Comment by CWolffIF** [comment]
Hi, I saw it. Thanx.
