### ISSUE TITLE
Xpand.XAF.Modules.ViewWizard

### ISSUE THREAD

**Issue by BurakOgutken** [eXpandFramework/eXpand#1026]
Hello,

I've added Xpand.XAF.Modules.ViewWizard to my application, but the model editor won't open. I'm pasting the error below. Additionally, the following is installed: System.Interactive.

`Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies cannot be loaded for execution. (0x80131058)`

**Comment by apobekiaris** [comment]
The wizard module was never finished.

**Comment by BurakOgutken** [comment]
Hi
First of all, thank you very much for your quick response. When is it planned to be completed, or will it never be finished?

**Comment by apobekiaris** [comment]
The package was a sponsored initiative, however the sponsor felt no need to continue so we stop it waiting for a new sponsor

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
