### ISSUE TITLE
JobScheduler.Hangfire Application Error opening Dashboard

### ISSUE THREAD

**Issue by ricardoamm** [eXpandFramework/eXpand#1028]
In development mode, when I select a Worker and open dashboard i got the following error, but the dashboard is opened in new tab.
In production, the dashboard is not opened,

The error occurred:

	Type:       JSException
	Message:    Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at D (https://localhost:5003/_framework/blazor.server.js:1:5345)
    at https://localhost:5003/_framework/blazor.server.js:1:3541
	Data:       0 entries
	Stack trace:

   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
	InnerException is null

**Comment by apobekiaris** [comment]
please post a sample and details on how to repro this

**Comment by ricardoamm** [comment]
Hi, I just select one worker from job and then click on the Dashboard button.
[record.zip](https://github.com/eXpandFramework/eXpand/files/14090574/record.zip)

**Comment by ricardoamm** [comment]
The issues seems related to invocation "JsRuntime.InvokeAsync(" instead "JsRuntime.InvokeVoidAsync("

**Comment by apobekiaris** [comment]
did you tried to upgrade the hangfire libs to a newer version to see if they resolved it?

**Comment by ricardoamm** [comment]
![image](https://github.com/eXpandFramework/eXpand/assets/26299584/327c8311-db68-4873-bdde-735be2f865f3)

System.TypeLoadException: 'Could not load type 'Hangfire.HangfireServiceCollectionExtensions' from assembly 'Hangfire.AspNetCore, Version=1.8.9.0, Culture=neutral, PublicKeyToken=null'.'

**Comment by ricardoamm** [comment]
Latest Xpand.XAF.Core.All references Hangfire 1.7.35

![image](https://github.com/eXpandFramework/eXpand/assets/26299584/39384d64-896e-4f68-aa7d-f577990e5f0b)

**Comment by ricardoamm** [comment]
I found the problem in your code on the class Xpand.XAF.Modules.JobScheduler.Hangfire.JobSchedulerService, method JobDashboard.

  return args.SelectedObjects.Cast<JobWorker>().ToObservable(ImmediateScheduler.Instance).**SelectMany**(
          job => jsRuntime?.InvokeAsync<object>("open", new object[] { $"{uri}{job.Id}", "_blank" }).AsTask());

You should use **Select** instead **SelectMany**

Could you confirm, please? It worked for me, but I prefer to reference the Nuggets.

**Comment by apobekiaris** [comment]
I recently switched the JobScheduler tests to integration tests, for testing the actual app instead of a SUT system, however yet no test for Dashboard. I will add one when my time permits for now your observation looks correct, I will update the source code.

Feel free to send a PR when ever u have any fix that was a nice catch

**Comment by apobekiaris** [comment]
I do not see how it worked for you as it does not even compile unless you posted a wronf snippet. Without testing the correct version should be

```
args.SelectedObjects.Cast<JobWorker>().ToNowObservable()
                        .SelectMany(job => Observable.FromAsync(() => jsRuntime?.InvokeVoidAsync("open", [$"{uri}{job.Id}", "_blank"]).AsTask()))
```
can u please test is fine so I can send a build?

**Comment by ricardoamm** [comment]
Should be Select instead SelectMany

**Comment by apobekiaris** [comment]
your answer beats me, can you explain why you think the Task should not be flattened?

**Comment by apobekiaris** [comment]
The `SelectMany`  is the operator that flattens the inner observable which in this case is the task. Although this task is executed on creation so it worked as you mentioned with the `Select` is not the correct approach and probably the `ToUnit` hide it from you. 

```
IObservable<IObservable<Unit>> observable = e.SelectedObjects.Cast<JobWorker>().ToNowObservable()
                        .Select(job => jsRuntime?.InvokeVoidAsync("open", [$"{uri}{job.Id}", "_blank"]).AsTask().ToObservable());
```
the `Select` will project the Task to  `IObservable<IObservable<Unit>>` where the `SelectMany` will flatten it

```
IObservable<Unit> observable = e.SelectedObjects.Cast<JobWorker>().ToNowObservable()
                        .SelectMany(job => jsRuntime?.InvokeVoidAsync("open", [$"{uri}{job.Id}", "_blank"]).AsTask().ToObservable());
```

**Comment by ricardoamm** [comment]
Ok, maybe I'm not seeing the whole concept here. I'm used to LINQ and I use SelectMany() to collapse a multidimensional sequence in a way that would otherwise require a second Select() or loop. In this case, i thought we just want to select the JobWorker Id's in a simple one-to-one projection, and foreach one create create a task.

**Comment by apobekiaris** [comment]
> I use SelectMany() to collapse a multidimensional sequence

it is LINQ and it is as you said it now else flattening and our return is a Unit not a worker. A Unit is a type we use to merge all observables into a signle subscription

```
   .Merge(manager.TriggerJobsFromAction())
                    .Merge(manager.PauseJobsFromAction())
                    .Merge(manager.ResumeJobsFromAction())
                    .Merge(manager.JobDashboard())
```
all this methods same for LINQ must have the same type in order to operate on them (Merge, Concat etc) so we use the Unit, the ToUnit method is a convenient extension that projects any type however if you not carefull it hides the whole picture from you


```
public static IObservable<Unit> ToUnit<T>(this IObservable<T> source) 
            => source.Select(_ => Unit.Default);
```

**Comment by ricardoamm** [comment]
Ok, thanks for the clarification. 
What is the expected behaviour, o new tab shoud be opened for each selected Worker?
I selected multiple Workers, but only one tab is opened.

**Comment by apobekiaris** [comment]
The pre-release [4.232.2.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.232.2.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [JobScheduler.Hangfire Application Error opening Dashboard

#1028](https://github.com/eXpandFramework/Reactive.XAF/commit/663345a48fec111b62b6a6649ddb504c3646acdc)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.232.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.232.2</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
from the RX side we expect a task for each selected object to run

```cs
jsRuntime?.InvokeVoidAsync("open", [$"{uri}{job.Id}", "_blank"]).AsTask().ToObservable()
```

**Comment by apobekiaris** [comment]
if u want to debug i suggest u verify if they open one by one so to have 2 tabs open at the end, so is it the browser that does not allow multiple popups in very close interval? then maybe a `StepInterval` operator can help and so on..

**Comment by apobekiaris** [comment]
or a `SelectManySequential` operator instead of `SelectMany` to flatten the task

**Comment by ricardoamm** [comment]
Thank you very much. 
When new nuggets will be released?

**Comment by apobekiaris** [comment]
nugets are already in the lab server, aren't they good enough at least for testing?

**Comment by ricardoamm** [comment]
sure, I need to add a new package souce to reference them?

**Comment by apobekiaris** [comment]
strange you can recompile/modify the source and you not aware of the readme? :)

![image](https://github.com/eXpandFramework/eXpand/assets/159464/e588f462-e088-4dc8-8326-264625a1608a)

did you by any chance find the time to experiement with my last suggestions? SelectManySequential + StepInterval

**Comment by ricardoamm** [comment]
I don't know how to specify the stepinterval, but the SelectManySequential seems to work, multiple tabs where open

**Comment by ricardoamm** [comment]
The browser was blocking multiple popups, so it's ok as it is.
I don't know how to specify the stepinterval, but the SelectManySequential also works.

**Comment by ricardoamm** [comment]
I'm using Hangfire because Windows Workflow Foundation is no longer supported in the new . NET 8.
What is the purpose of the JobScheduler Notification Module?

**Comment by apobekiaris** [comment]
do u mean that it does not work with SelectMany but works with the SelectManaySequential?

**Comment by ricardoamm** [comment]
work in both ways

**Comment by apobekiaris** [comment]
```cs
return e.SelectedObjects.Cast<JobWorker>().ToNowObservable()
                        .StepInterval(1.Seconds())
                        .SelectManySequential(job => jsRuntime?.InvokeVoidAsync("open", [$"{uri}{job.Id}", "_blank"]).AsTask().ToObservable());
```
you can add StepInterval just b4 the inner observable what that means is that it will wait for 1 second then it will open the page and it will wait for the task to complete (that's why we flatten) b4 moving to the next item

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
