### ISSUE TITLE
Is there any ways to get some working example which uses API like on demo example video

### ISSUE THREAD

**Issue by beneton2003** [eXpandFramework/eXpand#1032]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
Hello Apostolis! First I want to say thank you for all your work you have done for the Xpand. And the second i want to ask you if you can provide some example you showed on this video:
https://www.youtube.com/watch?v=m64GpvdwxRc

I just want to get some success example which i can use to explore how it's work in a real world. Maybe some similar example to this video will be very helpfull. Thank you again my friend!

**Comment by apobekiaris** [comment]
i cannot share a project, but I consider working example the tests for this module e.g. u can see the objects declared in the [BO folder](https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Tests/Reactive.Rest/BO) and u can review the tests to see the use those objects.  Then is a matter of spending time experiementing how the module works

**Comment by beneton2003** [comment]
I saw you have mention i an video that pagination is worked, i just want to see how it's work, maybe there is some special functions

**Comment by apobekiaris** [comment]
all the data are in memory (Non-Persistent objetcts), so u can feed them as datasource to a grid with pagination enable, is not really pagination per endpoint

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
