### ISSUE TITLE
Model Editor is not starting

### ISSUE THREAD

**Issue by beneton2003** [eXpandFramework/eXpand#1035]
Thank you guys for all your work on this project, but, i have some question, after i changed my laptop i start getting this error when i am trying to start model editor (i getting an error with built in editor as well, but in this case i am getting an error in the model xpand model editor)

Unable to create an instance of the "HRStation.Blazor.Server.HRStationBlazorApplication" type.
Reason: "Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."

can you please help me to solve this problem?
![image](https://github.com/eXpandFramework/eXpand/assets/47240176/62a65173-0c9c-4d33-8235-8a1b770d31f2)

**Comment by apobekiaris** [comment]
do u have .net7

**Comment by beneton2003** [comment]
Yes man, thank you, i think it will help, it was not very clean for me, but now everything is ok. You can also change entity framework to 6 and everything will work good! But another way is to install necessary modules manually

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
