### ISSUE TITLE
Model Editor GitHub Starting Issue

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1037]
When starting the Model Editor, I have been receiving the following error for that last couple of days. 

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/6edd9449-a42a-4eaf-b389-1df2a89b78c1)

**Comment by apobekiaris** [comment]
hmm I guess something is wrong cause I am in the process to upgrade to 23.2.3, Did you try to use the suggestion?

1. configure
![image](https://github.com/eXpandFramework/eXpand/assets/159464/91a4ea75-ef85-4b14-b948-3e8626400baf)
2. set to  https://github.com/eXpandFramework/Reactive.XAF/releases/download/4.231.6.0/Xpand.XAF.ModelEditor.WinDesktop.zip

 
![image](https://github.com/eXpandFramework/eXpand/assets/159464/a9ec3d03-4b4f-463c-9693-64cbdfdccc84)

**Comment by apobekiaris** [comment]
do not set the DownloadPrerelase unless u wanna try the 23.2.3

**Comment by beneton2003** [comment]
The same issue for me, changing the link is not solving this error
![image](https://github.com/eXpandFramework/eXpand/assets/47240176/cf41172b-57a0-42f8-b014-507a72f623ec)

**Comment by DannyRawlings** [comment]
I have also tried the usual, reinstall of the add in, updated visual studio to the latest version.

**Comment by apobekiaris** [comment]
thnks I repro the problem I am working on it

**Comment by apobekiaris** [comment]
unfortuntely i cannot provide a fix to help u directly cause it will be inlcuded in 23.2.3.xxx versions

**Comment by beneton2003** [comment]
> unfortuntely i cannot provide a fix to help u directly cause it will be inlcuded in 23.2.3.xxx versions
Thank you very much man! We do appreciate for everything you doing for the community.
Is there any information about terms when new version 23.2.3.xxx will be published?
Maybe you can give any advices how we can temporary fix it with electrical tape and soldering iron

**Comment by CWolffIF** [comment]
Hi,
I´ve got the same error. If you want to work with 23.1. you have to configure the 
![image](https://github.com/eXpandFramework/eXpand/assets/43132306/1951f014-29ec-47b9-b1ca-d805a4b8c767)

**Comment by apobekiaris** [comment]
I cannot spent time to give u exact steps but what the plugin does is download stuff from the link i posted and extract them into your Roaming profile XpandModelEditor folder. There was a bug not finiding the version in some cases as described here

https://github.com/eXpandFramework/Reactive.XAF/commit/51122111dfde76480977715f0bc64291273ae60e#diff-bce53f7a21641dca17ac31f97144ccb6b87cde5edb7dc19b00698daef6a6fd0cL167-R168

the `FirstAsync` is now `Where`  given u take the time to compile all related projects manually and replace the existing files in your Roaming folder it should work. The plugin will not attempt to redownload if the folder structure and zip files exists.

**Comment by apobekiaris** [comment]
maybe @CWolffIF can zip the full files for him cause I am not sure it will work, cause as I said it worked for you but the time u download Github had no other versions, in any case let him first tried it raw as u suggested and then he can ask back

**Comment by CWolffIF** [comment]
If you define the DevVersion (4.231.6.0) it downloads this Version from github. This Version is still there.

**Comment by beneton2003** [comment]
> If you define the DevVersion (4.231.6.0) it downloads this Version from github. This Version is still there.

Can you please give any ideas how to start it?
I just can't use neither built-in model editor nor xpand

**Comment by CWolffIF** [comment]
As I got the problem:
- Define the Version as above
- Close VS
-  kill an still opend Xpand.XAFModelEditor.Win in the Processes
 
![image](https://github.com/eXpandFramework/eXpand/assets/43132306/fd83bc78-4278-4348-93fe-e53de45e24e8)
- Start VS new and Build the project new
- Open the Modeleditor as usual

**Comment by apobekiaris** [comment]
if something went wrong due to your experiements u can always 

1. delete the `Xpand.XAF.ModelEditor.Win` from your roaming folder e.g. `C:\Users\Tolis\AppData\Roaming\`
2. Then start XpandModelEditor and when the list of models is shown execute the config button as b4

**Comment by beneton2003** [comment]
After i changed the DevVersion
![image](https://github.com/eXpandFramework/eXpand/assets/47240176/99072dec-a437-4497-b43b-842d231563c1)
i start getting new errors
![image](https://github.com/eXpandFramework/eXpand/assets/47240176/e40eca24-44c0-4dc9-85b0-2f843f31febb)

**Comment by apobekiaris** [comment]
did u tried the exact settings that `CWolffIF` suggested? they do not look the same to me

**Comment by CWolffIF** [comment]
Set the DownloadURL back to standard

**Comment by DannyRawlings** [comment]
Manually setting the version has fixed my issue for now. Thank you all for your help

**Comment by DannyRawlings** [comment]
Works perfectly now with the  latest release. Thank you
