### ISSUE TITLE
Unable to update to 4.232.1 - Xpand.Patacher needs to be >= 3.0.222

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1038]
Howdy,

I am try to update, but it is unable to due to Xpand.Patcher >= 3.0.22 being required. Nuget only has 3.0.17 available

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/098edcef-722b-4655-9a7a-81e21a1695b5)

**Comment by apobekiaris** [comment]
pushed now 

thnks

**Comment by DannyRawlings** [comment]
Thank you :)
