### ISSUE TITLE
.Net 7 Model Editor fails to load 

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1042]
Hi
I get the following error when I try open a Model from the Editor list

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/2f6a107c-27da-4374-af4a-efecf2062153)

**Comment by apobekiaris** [comment]
as I know you played around with ME config I cannot really tell more than that you have an issue with .net7. However I just publish the release with support for 6,7,8 frameworks

![image](https://github.com/eXpandFramework/eXpand/assets/159464/c8114e8a-ef9c-4523-8d75-75c96d24309e)


so update your Xpand ME plugins if you haven't arleady delete all related files from your AppData and try again. If the problem persist try to repro it with a new empty solution and post it here

**Comment by DannyRawlings** [comment]
Thank you, I'll test and let you know the result

**Comment by apobekiaris** [comment]
r u sure your Xpand ME model is clean? I mean default settings? cause I cannot repro it

![image](https://github.com/eXpandFramework/eXpand/assets/159464/5c75a7f8-7182-4743-976b-9683aa63af1f)

**Comment by apobekiaris** [comment]
hmm I did now, will update u again

**Comment by DannyRawlings** [comment]
Yep. I have even tried it on different internet connections because on the work network it doesn't like downloading updates. 

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/6f111f0e-836d-45e2-8e37-3f5e84e358a6)


https://github.com/eXpandFramework/eXpand/assets/7148712/d2611c1f-c708-4dab-8590-7ef5cf2ddb9d

**Comment by DannyRawlings** [comment]
I am now using VS to uninstall the extension. I'll then clear the app data and start again to be 100% sure

**Comment by apobekiaris** [comment]
add the missing assembly in path?? or post your sample

C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop\net6.0\4.232.2.0\

**Comment by apobekiaris** [comment]
ah i see is the same app

**Comment by DannyRawlings** [comment]
I have just tested it by create a default XAF application. Target .Net 6 first and it worked. Changed to .Net 7 and it failed 

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/4df18e40-a23e-4c78-91fe-122d2711c9bf)
[DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/13964977/DXApplication1.zip)

**Comment by apobekiaris** [comment]
I updated the Xpand ME, get the latest version and should work now and no 404

**Comment by DannyRawlings** [comment]
Thanks, it works now with the latest version. But I have to set the download url to the .Net 7 version. 

https://github.com/eXpandFramework/Reactive.XAF/releases/download/4.232.2.0/Xpand.XAF.ModelEditor.WinDesktop7.zip

**Comment by apobekiaris** [comment]
at least in my tests and with your sample app there is no prompt, maybe you try to clean up your folders again? or you can try the v8 should probably work for all
