### ISSUE TITLE
Modeleditor did not open anymore Version 4.231.6.0

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#1043]
Hi Tolis,

something changed today.
I try to open the Version 4.231.6.0, but since today it did not open anymore.

The config:
![image](https://github.com/eXpandFramework/eXpand/assets/43132306/5e043807-df8e-4b47-919d-b02a3a4df1ca)

The Error:
![image](https://github.com/eXpandFramework/eXpand/assets/43132306/77c92ab7-12fb-4a08-9ca9-07cc81bcd200)

Seems like the Version is not there anymore.

What can I do, I need this Version for 23.1.6.

**Comment by apobekiaris** [comment]
the version is here as you probably know https://github.com/eXpandFramework/Reactive.XAF/releases/download/4.231.6.0/Xpand.XAF.ModelEditor.WinDesktop.zip

what changed is that now the plugin looks for dotnet version e.g. 6,7,8

![image](https://github.com/eXpandFramework/eXpand/assets/159464/4dd1deb7-e269-4754-92da-735c5595327c)

you can get the version you need, save it in a dir, suffix it with the dotnet version e.g. 6  and use the file://c:\Xpand.XAF.ModelEditor.WinDesktop6.zip notation as the download url.

**Comment by apobekiaris** [comment]
another option is to download the source and compile the XpandVSIX of the past install it and remember to disable the VS auto update so you do not get the latest plugin version again

**Comment by CWolffIF** [comment]
I updated all to 23.2.3.x (Devexpress & eXpand) and everything works.
I think the problem occurs cause the XVSIX64 Extension updated automaticly. Is there a way the get/install an old Version?

**Comment by apobekiaris** [comment]
no there is not, the plugin is only distributed from the VS marketplace your only options are 

1. to disable the VS auto update
2. To build the source back in the version you are interested and install it manually

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
