### ISSUE TITLE
Model Editor does not open

### ISSUE THREAD

**Issue by fatemehfathollahi** [eXpandFramework/eXpand#1050]
I installed the latest version of Xpand Model Editor and installed DevExpress 23.1.6, when I want to open my Model and clock Xpand Model Editor it appears for a second and never opens I do not have any output error, I don't know what happened I reinstall depress and XVSIX64, remove roaming try to open DevExpress.ExpressApp.Design.ModelEditorServer.NetCore.v23.1.exe directly but it never runs.

also, I have this Error when I want to open my model:   Model Editor Fails to load(version (23.1.7)
this error happens without expand also

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
