### ISSUE TITLE
is it safe to deactivate the Xpand.ExpressApp.Security.Controllers.ShowNavigationItemController

### ISSUE THREAD

**Issue by muwanguzij** [eXpandFramework/eXpand#1055]
what is the purpose of this controller and is it safe to deactivate it?

**Comment by expand** [comment]
it deactivates the naviation items when 

public static bool IsRemoteClient(this ISecurityStrategyBase security){
            return security is IMiddleTierClientSecurity || security is IClientInfoProvider;
        }

**Comment by expand** [comment]
and here the git file history

![image](https://github.com/eXpandFramework/eXpand/assets/131656/5d6725ef-d114-4499-8d95-04a8179bf83e)

**Comment by muwanguzij** [comment]
OK thanks
