### ISSUE TITLE
Release for 23.2.6

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#1059]
Hi,

are you planning a Release for Devexpress 23.2.6? Cause there is a Security Bullet.

**Comment by apobekiaris** [comment]
yes

**Comment by CWolffIF** [comment]
Hi Tolis,

something went wrong. The 23.2.602 Version is not available at nuget.org. There is still 23.2.501.

**Comment by apobekiaris** [comment]
thnks I will look at it in the meantime u can also use them locally from the release https://github.com/eXpandFramework/eXpand/releases

**Comment by CWolffIF** [comment]
Thanx. I tried it locally, but I get errors in the binding/references. So I wait for nuget.org....

**Comment by CWolffIF** [comment]
Hi Tolis,
there is still something wrong:
eXpandagnostic is on Version 23.2.605
![image](https://github.com/eXpandFramework/eXpand/assets/43132306/e972dba9-a03a-4496-a915-71766917f1fa)

but eXpandwin is still on 23.2.501
![image](https://github.com/eXpandFramework/eXpand/assets/43132306/027cdc22-ca76-4f34-9862-a0f5a8d0cb09)

**Comment by apobekiaris** [comment]
I publish them manually the error was in an Azure pipe so I will not go for another build. Let me know if any problems

**Comment by CWolffIF** [comment]
Hi, it works. Thanx.....
