### ISSUE TITLE
Model Editor Error

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1061]
Morning,

I have run into another issue with the model editor.  The DevExpress ME version solves this issue by using  

`if (!ModuleHelper.IsDesignMode)`

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/b057c277-3572-4490-abfd-fffcf5eea83d)

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/f58d40f6-eba0-4bc9-a307-acd248b61a97)

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/4a3198da-abd2-4978-b67b-d65a287cec00)

Any ideas on this one?

Cheers 

Dan

**Comment by DannyRawlings** [comment]
Here is a quick example for you.. I can open it via the DevExpress ME and not eXpand ME
[DXApplication3.zip](https://github.com/user-attachments/files/15816397/DXApplication3.zip)

**Comment by apobekiaris** [comment]
fix in 24.1 release
