### ISSUE TITLE
Unable to cast object of type 'DevExpress.Xpo.DB.Helpers.MSSql2005SqlDependencyCacheRoot' to type 'DevExpress.Xpo.DB.DataCacheRoot'.

### ISSUE THREAD

**Issue by pavlovboris** [eXpandFramework/eXpand#1069]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴

Hello,

With the last version Im getting the following error:

Unable to cast object of type 'DevExpress.Xpo.DB.Helpers.MSSql2005SqlDependencyCacheRoot' to type 'DevExpress.Xpo.DB.DataCacheRoot'.

   at Xpand.Extensions.XAF.Xpo.XpoExtensions.Connection(UnitOfWork unitOfWork)
   at Xpand.Extensions.XAF.Xpo.ObjectSpaceExtensions.ObjectSpaceExtensions.Connection(IObjectSpace objectSpace)
   at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass19_0.<Connect>b__2(IObjectSpace t)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)

No issue with 4.241.3.

BR

**Comment by apobekiaris** [comment]
is this with the lab version?

**Comment by pavlovboris** [comment]
I is 4.241.3.2

**Comment by apobekiaris** [comment]
revisions mean lab, I will look at it the tenant support is to blame see #1066

**Comment by pavlovboris** [comment]
aight thank you!

**Comment by apobekiaris** [comment]
The pre-release [4.241.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.3.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: throws when cache enabled #1069](https://github.com/eXpandFramework/Reactive.XAF/commit/76c350ef8c3edef340fbdef5f2434c525e8bf7e4)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
The pre-release [4.241.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.3.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: Fails if ConnectionString has creds #1066 #1069](https://github.com/eXpandFramework/Reactive.XAF/commit/5f320dc31d4e72ff56c5f7022b75923628302a6d)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
is the fix ok with you? planning to push it public so if you have some time please test

**Comment by pavlovboris** [comment]
I keep getting the same exception;

**Comment by apobekiaris** [comment]
I was able to reproduce the case with a blank Xaf solution where I enable Xpo caching, after this patch all works fine on my side. Can you provide a solution that fails?

**Comment by apobekiaris** [comment]
I assume you are on the latest version 4.241.3.4

**Comment by pavlovboris** [comment]
yup.

**Comment by pavlovboris** [comment]
[DXApplication2.zip](https://github.com/user-attachments/files/16936135/DXApplication2.zip)

**Comment by apobekiaris** [comment]
The pre-release [4.241.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.3.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: Unable to cast object #1069](https://github.com/eXpandFramework/Reactive.XAF/commit/99eae9c71375623c5336528a0b6eb2013f97988a)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by pavlovboris** [comment]
the previous issue is fixed in 4.241.3.5, but now :

An item with the same key has already been added. Key: Password

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at DevExpress.Xpo.DB.Helpers.ConnectionStringParser.AddPart(String partName, String partValue)
   at Xpand.Extensions.XAF.Xpo.ObjectSpaceExtensions.ObjectSpaceExtensions.ConnectionString(IObjectSpace objectSpace)
   at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.SequenceGeneratorDataLayer(IObjectSpace space)
   at Xpand.Extensions.LinqExtensions.LinqExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 valueCreator, String caller)
   at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass19_0.<Connect>b__2(ValueTuple`2 t)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)

**Comment by apobekiaris** [comment]
detail me on repro steps please

**Comment by apobekiaris** [comment]
The pre-release [4.241.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.3.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: Unable to cast object fails when creds #1069](https://github.com/eXpandFramework/Reactive.XAF/commit/98c92de04b22c00c0f91ddc2edd462830875b088)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by pavlovboris** [comment]
Everything looks great now to me. Thank you for your efforts.  Efharistó para poli!
