### ISSUE TITLE
Security Modul

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#1070]
Hi,

I want to use the XAF Standard Login Window:
![image](https://github.com/user-attachments/assets/4c36802c-2656-412a-9d54-ee9436a1cdc7)

But if I comment the lines in the builder:
        builder.Security
            .UseIntegratedMode(options =>
            {
                options.RoleType = typeof(XpandPermissionPolicyRole);
                options.UserType = typeof(XpandPermissionPolicyUser);
                options.UseXpoPermissionsCaching();
                var securityCreatedHandler = options.Events.OnSecurityStrategyCreated;
                options.Events.OnSecurityStrategyCreated = (securityStrategy) =>
                {
                    securityCreatedHandler?.Invoke(securityStrategy);
                    ((SecurityStrategy)securityStrategy).AssociationPermissionsMode = AssociationPermissionsMode.ExtendedAuto;
                    ((SecurityStrategy)securityStrategy).SupportNavigationPermissionsForTypes = true;

                    **//Xpand.ExpressApp.Security.AuthenticationProviders.AuthenticationCombined authenticationCombined = new AuthenticationCombined();
                    //((SecurityStrategy)securityStrategy).Authentication = authenticationCombined;**

                    ((SecurityStrategy)securityStrategy).RolesMergingMode = RolesMergingMode.GrantedInAnyRole;
                };
                SecurityAdapterHelper.Enable(DevExpress.ExpressApp.Security.Adapters.ReloadPermissionStrategy.CacheOnFirstAccess);
            })

I got the Error:
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at Xpand.XAF.Modules.Windows.SystemActions.SystemActionsService.<>c.<WhenHotkey>b__14_0(ActionBase action)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
	InnerException is null

If I uncomment them I get the expand Login Mask.

Any Idea?

**Comment by apobekiaris** [comment]
cannot tell more than the obvious what is the System actrions of the Windows RX module. What can cause it have no idea perhaps a corrupted model? do u have any system actions in your modules?

please provide a sample so I can be certain

**Comment by TheGermanNiko** [comment]
Hi , i made a sample project to illustrate the problem and currently used modules.

[TestLogin.zip](https://github.com/user-attachments/files/17026132/TestLogin.zip)

**Comment by apobekiaris** [comment]
thnks for the sample I fixed the problem. 

Note you can avoid spending time making a sample with such many modules. For example you know from the stack that the problem was in the Xpand.XAF.Modules.Windows.WindowsModule so you could test that module only for start and if you cannot repro it you add more modules until you can. I manage to repro it with only the WindowsModule

**Comment by apobekiaris** [comment]
The pre-release [4.241.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.3.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Windows: System actions queries the model b4 is initialized #1070](https://github.com/eXpandFramework/Reactive.XAF/commit/9efe21b3eab95a53f3b4f8124cfa965e660f8549)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi,
it works with 24.1.602 and 4.241.6.
