### ISSUE TITLE
Sequence generator not working if MSSql2005SqlDependencyCacheRoot is used

### ISSUE THREAD

**Issue by pavlovboris** [eXpandFramework/eXpand#1071]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴

There are no visible errors, but the sequence generator is not generating the correct sequence and entry: 
for example, if the next number is 3, the generated number is missing the 3 and gets directly to 4, and the sequence number is not incremented at all.

Attaching a sample
[DXApplication2 (2).zip](https://github.com/user-attachments/files/17073426/DXApplication2.2.zip)

BR

**Comment by apobekiaris** [comment]
The pre-release [4.241.4.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.4.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: application.WhenProviderObjectSpaceCreated emits twice resulting in Locking exceptions #1071](https://github.com/eXpandFramework/Reactive.XAF/commit/14c61d6e55bec019da9f9fca575804623f011ec7)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by pavlovboris** [comment]
fixed, thank you.
