### ISSUE TITLE
How to configure modelviewinheritance

### ISSUE THREAD

**Issue by victorykj** [eXpandFramework/eXpand#1074]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
I have tried to reproduce the results in the documentation video couldn't.

I also copied the code in the unit tests to a real project but there was no inheritance.Its strange that the test passes.

Am upgrading from 20.2 and it worked.

**Comment by apobekiaris** [comment]
I am not sure whats the question. Apparently your first version was buggy and later the problem fixed?. I do use the module in my apps without issues
