### ISSUE TITLE
SequenceGenerator doesn't increment correctly

### ISSUE THREAD

**Issue by yunits** [eXpandFramework/eXpand#1075]
Hello,

I need some time to figure out how to sample this but I wanted to create an issue, maybe someone else can provide a sample.

Sometimes SequenceGenerator is not incrementing the sequence:
![image](https://github.com/user-attachments/assets/7142e746-c4c6-46dc-8a5c-291568d2250c)

It is a XAF Application with Win/Blazor, no MiddleTier, no Tenancy.
I am using SQL Server.
Issue occurs on Win.
After trying on Blazor it worked again as it should.

Reopening ListView etc. did not help:
![image](https://github.com/user-attachments/assets/c252ad8c-6251-472f-8699-d39e272fa5d1)

**Comment by apobekiaris** [comment]
at least myself unclear as to why this happens, unless I can repro it

**Comment by yunits** [comment]
I will test now some cases.
Could there be any conflict with different OptimisticLockingReadBehavior or different OptimisticLocking settings?

**Comment by apobekiaris** [comment]
as a side effect it can be sure

**Comment by yunits** [comment]
I turned locking on my side off but it did not help.

Will get back soon as I have any updates on this.

**Comment by yunits** [comment]
I don't know why but it happened sometimes already before:
![image](https://github.com/user-attachments/assets/cf2d021c-a362-443b-9db9-ac2888d3aa48)


it is sporadically, I can't repro it too.

**Comment by CWolffIF** [comment]
I have the save problem. I can not repro it. It happens sporadicly when many people work on the system, but simultaneous request of numbers is not the reason (the same as your example).
It seems that the new number can not be commited.

**Comment by apobekiaris** [comment]
maybe u can try detecting the exact moment it happens using a db constrain? e.g. unique index on the column and hopefully this can gives us ideas to repro it?

**Comment by yunits** [comment]
I guess I could also use my timestamp to get the exact moment but it didn't helped me to figure out what was causing this issue.
At the time when I opened this issue I was able to test a little bit and closing every View and reopening did not help. 

If I look at this line: https://github.com/eXpandFramework/Reactive.XAF/blob/4d5517f573a4182b83dc4cd5191851fc0b4f4a2c/src/Modules/SequenceGenerator/SequenceGeneratorService.cs#L266

could you change "throw" to log an exception anywhere?

@CWolffIF maybe the number can't be commited or it gets decremented.

Because we always get the last number, I guess the exception is after this line, correct? https://github.com/eXpandFramework/Reactive.XAF/blob/4d5517f573a4182b83dc4cd5191851fc0b4f4a2c/src/Modules/SequenceGenerator/SequenceGeneratorService.cs#L260

**Comment by apobekiaris** [comment]
I thinkk u could easily own the code of the module do your tests, spent your resources to find out whats the issue and report back so I can review and integrate.

I have not tried it my self so some steps maybe missing. But to me looks like you 
1. can remove the dependency to the SequenceGenerator.
2. copy-paste the only two files from the package source to your source
3. Maybe change the XPObjectType if there is an entry there for the SequenceStorage
4.  subscribe to the sevice in your module as the package does

```cs
public override void Setup(ApplicationModulesManager moduleManager){
            base.Setup(moduleManager);
            moduleManager.Connect(SequenceStorageType)
                .TakeUntilDisposed(this)
                .Subscribe();
        }
```

hopefully this suggestion is more valueable to you instead of waiting long times me to modify going blind. Let me know if there was an issue running the package like this.

**Comment by apobekiaris** [comment]
note also all problems starrted from the Tenant upgrade, b4 it worked well so you can compare the current package source (1 file) to then if you feel it will help

**Comment by apobekiaris** [comment]
added the logging in the next minor, did u by any chance have any luck?

**Comment by yunits** [comment]
I had no time to work on this project. It feels like 100 other things came up.
I'll take care of it as soon as I find time.

**Comment by apobekiaris** [comment]
The pre-release [4.241.7.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.7.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGeneratorService log all exceptions in verbose mode #1075](https://github.com/eXpandFramework/Reactive.XAF/commit/43d2a3536ac2b70c286e3b9c259d382af7f4d284)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by yunits** [comment]
just for information: I am using 4.241.7.5 and this error occured again. There is nothing in eXpressAppFramework.log

the last number at 16:36 has been generated programmatically.
All the numbers before were generated by a user in GUI.
![image](https://github.com/user-attachments/assets/5424bd05-9eef-4a76-875b-e1513c4488be)

**Comment by apobekiaris** [comment]
the link above takes u here

![image](https://github.com/user-attachments/assets/797eae01-919f-42d2-95a2-676d78e4a454)

so u need verbose in your config to see something if error

**Comment by yunits** [comment]
oh now I see it, I will change loglevel to verbose and get back with new informations.

**Comment by yunits** [comment]
```
16.12.24 16:57:45.531	Action 'SucheImVorgang' done
16.12.24 16:57:50.606	>BindingHelper.EndCurrentEdit
16.12.24 16:57:50.606		control is null: False
16.12.24 16:57:50.606		Form.ActiveForm is null: False
16.12.24 16:57:50.606	BindingHelper.EndCurrentEditCore - grid.MainView.UpdateCurrentRow
16.12.24 16:57:50.606	BindingHelper.EndCurrentEditCore - grid.MainView.UpdateCurrentRow
16.12.24 16:57:50.606	<BindingHelper.EndCurrentEdit
16.12.24 16:57:50.606	--------------------------------------------------------------------------------
							Execute action

16.12.24 16:57:50.606		Type: DevExpress.ExpressApp.Actions.SimpleAction
								ID: RechnungAusAuftrag
								Category: ObjectsCreation
								Controller.Name: JEJE.Win.Controllers.Verkauf.ovcAuftragMasterListViewWin
								Context.Name: Auftragsübersicht
								Context.IsRoot: True
								Context.SelectedObjects.Count: 1
								Context.CurrentObject: 3150c1d5-b94d-4ee6-9f53-0193cc5aef1d

16.12.24 16:57:52.073		ListView: ListView, ID:Auftrag_Auftragspositionen_ListView
16.12.24 16:57:52.073		ListView.CollectionSource: DevExpress.ExpressApp.PropertyCollectionSource
								ListView.CollectionSource.List: ProxyCollection

16.12.24 16:57:52.085		ListView: ListView, ID:Anmerkung_ListView
16.12.24 16:57:52.085		ListView.CollectionSource: DevExpress.ExpressApp.PropertyCollectionSource
								ListView.CollectionSource.List: XpoServerCollectionFlagger

JEJE.Win Error: 0 : 16.12.24 16:57:52.173	================================================================================
The error occurred:

	Type:       LockingException
	Message:    Das Objekt kann nicht bestehend bleiben. Es wurde von einem anderen Programm modifiziert oder gelöscht (bereinigt).
	Data:       0 entries
	Stack trace:

   at DevExpress.Xpo.DB.MSSqlConnectionProvider.ProcessModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.DB.DataStoreSerializedBase.ModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.DB.ConnectionProviderSql.ModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.SimpleDataLayer.ReentrancyAndThreadSafetyChecked[T](Func`1 action)
   at DevExpress.Xpo.SimpleObjectLayer.CommitChanges(Session session, ICollection fullListForDelete, ICollection completeListForSave)
   at DevExpress.Xpo.Session.FlushChanges()
   at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.GenerateSequences(ExplicitUnitOfWork explicitUnitOfWork, Object theObject, Type sequenceStorageType)
	InnerException is null

```

**Comment by yunits** [comment]
For my case I need to check if it is related to "LockModified" in some associated BusinessObject.

For example BusinessObject A generates a new sequence, but associated BusinessObject B has LockModified enabled.
I don't know if this could affect it.

I will [OptimisticLockingIgnored] every property that has a relation to sequence generator and get back with new informations in some days.

**Comment by yunits** [comment]
as I had two days without duplicates after adding [OptimisticLockingIgnored] to every property of type long that is used for sequence, I will close this issue.
If my problem appears again, I will notice.

@CWolffIF maybe you could also try to add [OptimisticLockingIgnored] and confirm if this resolves your problem. Even if you use the XAF default locking behaviour.

[OptimisticLockingIgnored]
public long MySequenceNumber {

}
..

**Comment by yunits** [comment]
this locking attribute did not help.
I will try https://supportcenter.devexpress.com/ticket/details/t1268805/sequencegenerator-for-middletier
