### ISSUE TITLE
Showing NonPersistentObject in MasterDetailMode using PopupWindowShowAction commits ObjectSpace too early in CustomizePopupWindowParams

### ISSUE THREAD

**Issue by yunits** [eXpandFramework/eXpand#1078]
Hello Apo,
I've created a sample to demonstrate my issue.
I've noticed that if I use any Reactive Module, for example SequenceGenerator, some observer does his magic and therefore my ObjectSpace gets commited in CustomizePopupWindowParams if using a ListView with MasterDetailMode.
[DXApplication2.zip](https://github.com/user-attachments/files/17960459/DXApplication2.zip)

![ezgif-7-c7e99f9e09](https://github.com/user-attachments/assets/1b632d9d-5413-4fa9-9fd5-342a555d9d17)

![stack trace](https://github.com/user-attachments/assets/feb195c2-85ce-4dd1-95a4-c917ad979c92)
![sourcecode](https://github.com/user-attachments/assets/87b9c7ec-81e2-48f1-a9f0-becd0327ecae)

**Comment by apobekiaris** [comment]
looks like I should have not change the default Xaf behaviour there, however I still not clear what exactly is the problem

**Comment by yunits** [comment]
Default xaf behavior is that my objectspace dont get committed in CustomizePopupWindowParams.

To test: don't load SequenceGenerator Modul and see that nothing gets committed in that method.

In my case I prepare objects in CustomizePopupWindowParams but dont want them to be committed before showing the popup view.

**Comment by apobekiaris** [comment]
The pre-release [4.241.7.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.241.7.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [remove EnsureNewInstanceOnNonPersistentDetailView #1078](https://github.com/eXpandFramework/Reactive.XAF/commit/b49d48f5c436ec868287db839f7fe79ae5923336)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
No packages released.
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by yunits** [comment]
fixed, thanks!
