### ISSUE TITLE
Dashboard issues in 18.1.5.x

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#133]
When migrating from 18.1.4.x I found the following changes that should be described as Breaking changes

1) Previous existing dashboards doesn't work anymore because of a non-existing proxy collection, I have to manually change XML data.
2) Coexistence with Dx dashboard, generate in my projects some issues, so I have to remove references to DX Dashboard win and web. I used to use both Dx and Xpand together ... :)
 
Also, I was using an extension method 'CreateDashboard' from the previous Xpand for emailing dashboard, that does not exist anymore.

**Comment by apobekiaris** [comment]
yes you are right I should have mentioned that Dashboard method have been removed. in fact I will add your comments now. But mayI ask why you use both dashboard modules together?

>Also, I was using an extension method 'CreateDashboard' from the previous Xpand for emailing dashboard, that does not exist anymore.

You can now follow XAF docs and override the existing services or provide new ones.

**Comment by apobekiaris** [comment]
>Previous existing dashboards doesn't work anymore because of a non-existing proxy collection, I have to manually change XML data.

However this should work at least it works in XtraDashboardTester the [MigrateDatasourceTypes method](https://github.com/expand/eXpand/blob/c40e4f571fbfd29af4321c60d7fa7cfc599a5474/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs#L101) is called for each dashboard existing or new.

I can look it further if you can provide a sample.

>Also, I was using an extension method 'CreateDashboard' from the previous Xpand for emailing dashboard, that does not exist anymore.

there are also a [set of extensions](https://github.com/expand/eXpand/blob/c40e4f571fbfd29af4321c60d7fa7cfc599a5474/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs) you might find useful and use instead of the CreateDashboard. But does not make much sense to create a Dashboard now, just override or provide a custom IXpandDashboardDataSourceFillService implementation.

**Comment by vimarx** [comment]
I missing the DashboardNavigationItem from DX Dashboard Module, that was the reason I have to use Dx Module...

**Comment by vimarx** [comment]
I'm getting Null Reference with legacy Dashboard here

![image](https://user-images.githubusercontent.com/226800/43689886-1cc98742-98d7-11e8-97d0-8401927e995b.png)

XafTypesInfo.Instance.FindTypeInfo($"{typeName}") is returning null, maybe because I'm registering a NonPersistentObjectspaceprovider also?

**Comment by apobekiaris** [comment]
can you post the datasources from the xml?

**Comment by vimarx** [comment]
another related issue while looking for the XML, this dashboard fails to retrieve dashboard calculated fields 

> <?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="es-AR">
  <Title Text="Tablero de control" />
  <DataSources>
    <ObjectDataSource ComponentName="dashboardObjectDataSource1">
      <Name>Indicador AMT</Name>
      <DataSource Type="Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection, Xpand.ExpressApp.Dashboard, Version=18.1.4.1, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958" />
      <Constructor>
        <Parameter Name="type" Type="System.String">F.Module.Cuentas.amt.IndicadorAMT</Parameter>
      </Constructor>
      <CalculatedFields>
        <CalculatedField Name="TNA PPond" Expression="Sum([SaldoCapital] * [AMT.TNA]) / Sum([SaldoCapital])" DataType="Auto" />
        <CalculatedField Name="Plazo P" Expression="Sum([SaldoCapital] * [AMT.Plazo]) / Sum([SaldoCapital])" DataType="Auto" />
      </CalculatedFields>
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Evolucion Tasas" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Measure DataMember="TNA PPond" DefaultId="DataItem0">
          <NumericFormat FormatType="Percent" />
        </Measure>
        <Dimension DataMember="Proceso.FechaReferencia" DateTimeGroupInterval="MonthYear" DefaultId="DataItem1" />
        <Measure DataMember="SaldoCapital" DefaultId="DataItem2">
          <NumericFormat FormatType="Number" Unit="Ones" IncludeGroupSeparator="true" />
        </Measure>
        <Dimension DataMember="Moneda" DefaultId="DataItem3" />
        <Measure DataMember="Plazo P" DefaultId="DataItem4">
          <NumericFormat FormatType="Number" Precision="0" Unit="Ones" />
        </Measure>
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem3" />
      </Columns>
      <Rows>
        <Row DefaultId="DataItem1" />
      </Rows>
      <Values>
        <Value DefaultId="DataItem0" />
        <Value DefaultId="DataItem4" />
        <Value DefaultId="DataItem2" />
      </Values>
    </Pivot>
    <TreeView ComponentName="treeViewDashboardItem1" Name="Periodo" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="Proceso.FechaReferencia" DefaultId="DataItem0" />
        <Dimension DataMember="Proceso.FechaReferencia" DateTimeGroupInterval="Month" DefaultId="DataItem1" />
      </DataItems>
      <FilterDimensions>
        <Dimension DefaultId="DataItem0" />
        <Dimension DefaultId="DataItem1" />
      </FilterDimensions>
    </TreeView>
    <TreeView ComponentName="treeViewDashboardItem2" Name="Sucursales" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="AMT.Sucursal.Nombre" DefaultId="DataItem0" />
      </DataItems>
      <FilterDimensions>
        <Dimension DefaultId="DataItem0" />
      </FilterDimensions>
    </TreeView>
    <Grid ComponentName="gridDashboardItem1" Name="Principales Depositantes" DataSource="dashboardObjectDataSource1">
      <InteractivityOptions MasterFilterMode="Single" />
      <DataItems>
        <Dimension DataMember="AMT.Miembros" SortOrder="Descending" TopNEnabled="true" TopNShowOthers="true" TopNCount="20" TopNMeasure="DataItem2" DefaultId="DataItem0" />
        <Dimension DataMember="Moneda" DefaultId="DataItem1" />
        <Measure DataMember="SaldoCapital" DefaultId="DataItem2">
          <NumericFormat FormatType="Number" Unit="Ones" IncludeGroupSeparator="true" />
        </Measure>
        <Measure DataMember="TNA PPond" DefaultId="DataItem3">
          <NumericFormat FormatType="Percent" />
        </Measure>
        <Measure DataMember="Plazo P" DefaultId="DataItem4">
          <NumericFormat FormatType="Number" Precision="0" Unit="Ones" />
        </Measure>
        <Measure DataMember="SaldoCapital" Name="% Total" DefaultId="DataItem5">
          <NumericFormat FormatType="Percent" />
          <Calculation>
            <PercentOfTotal />
          </Calculation>
          <WindowDefinition>
            <GridWindowDefinition />
          </WindowDefinition>
        </Measure>
      </DataItems>
      <GridColumns>
        <GridDimensionColumn Weight="132.09393346379653">
          <Dimension DefaultId="DataItem0" />
        </GridDimensionColumn>
        <GridDimensionColumn Weight="44.911937377690826">
          <Dimension DefaultId="DataItem1" />
        </GridDimensionColumn>
        <GridMeasureColumn Weight="90.704500978473618">
          <Measure DefaultId="DataItem2" />
        </GridMeasureColumn>
        <GridMeasureColumn Weight="70.450097847358151">
          <Measure DefaultId="DataItem3" />
        </GridMeasureColumn>
        <GridMeasureColumn Weight="43.150684931506873">
          <Measure DefaultId="DataItem4" />
        </GridMeasureColumn>
        <GridMeasureColumn Weight="68.688845401174191">
          <Measure DefaultId="DataItem5" />
        </GridMeasureColumn>
      </GridColumns>
      <GridOptions ColumnWidthMode="Manual" />
    </Grid>
    <ListBox ComponentName="listBoxDashboardItem1" Name="Moneda" DataSource="dashboardObjectDataSource1" ListBoxType="Radio">
      <DataItems>
        <Dimension DataMember="Moneda" DefaultId="DataItem0" />
      </DataItems>
      <FilterDimensions>
        <Dimension DefaultId="DataItem0" />
      </FilterDimensions>
    </ListBox>
    <RangeFilter ComponentName="rangeFilterDashboardItem1" Name="Plazo (dias)" ShowCaption="true" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="AMT.Plazo" DefaultId="DataItem0" />
        <Measure DataMember="SaldoCapital" DefaultId="DataItem1" />
      </DataItems>
      <Argument DefaultId="DataItem0" />
      <Series>
        <Simple SeriesType="Line">
          <Value DefaultId="DataItem1" />
        </Simple>
      </Series>
    </RangeFilter>
    <Chart ComponentName="chartDashboardItem1" Name="Evolucion Plazos y Tasas" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="Proceso.FechaReferencia" DateTimeGroupInterval="MonthYear" DefaultId="DataItem0" />
        <Measure DataMember="TNA PPond" DefaultId="DataItem1">
          <NumericFormat FormatType="Percent" />
        </Measure>
        <Measure DataMember="Plazo P" DefaultId="DataItem2">
          <NumericFormat FormatType="Number" Precision="0" Unit="Ones" />
        </Measure>
      </DataItems>
      <Arguments>
        <Argument DefaultId="DataItem0" />
      </Arguments>
      <Panes>
        <Pane Name="Panel 1">
          <Series>
            <Simple>
              <Value DefaultId="DataItem1" />
            </Simple>
            <Simple PlotOnSecondaryAxis="true">
              <Value DefaultId="DataItem2" />
            </Simple>
          </Series>
        </Pane>
      </Panes>
    </Chart>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutGroup Orientation="Vertical" Weight="72.819472616632865">
        <LayoutItem DashboardItem="pivotDashboardItem1" Weight="49.9383477188656" />
        <LayoutGroup Weight="50.0616522811344">
          <LayoutItem DashboardItem="gridDashboardItem1" Weight="50.139275766016716" />
          <LayoutItem DashboardItem="chartDashboardItem1" Weight="49.860724233983284" />
        </LayoutGroup>
      </LayoutGroup>
      <LayoutGroup Orientation="Vertical" Weight="27.180527383367139">
        <LayoutItem DashboardItem="treeViewDashboardItem2" Weight="22.071516646115906" />
        <LayoutItem DashboardItem="listBoxDashboardItem1" Weight="13.316892725030826" />
        <LayoutItem DashboardItem="rangeFilterDashboardItem1" Weight="24.290998766954377" />
        <LayoutItem DashboardItem="treeViewDashboardItem1" Weight="40.32059186189889" />
      </LayoutGroup>
    </LayoutGroup>
  </LayoutTree>
</Dashboard>


Nombre de conexión: Indicador AMT
Mensaje de error:
**Parser error at line 0, character 4: syntax error; ("TNA {FAILED HERE}PPond")**

**Comment by vimarx** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="es-AR">
  <Title Text="Tablero de control" />
  <DataSources>
    <ObjectDataSource ComponentName="dashboardObjectDataSource1">
      <Name>Indicador AMT</Name>
      <DataSource Type="Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection, Xpand.ExpressApp.Dashboard, Version=18.1.4.1, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958" />
      <Constructor>
        <Parameter Name="type" Type="System.String">F.Module.Cuentas.amt.IndicadorAMT</Parameter>
      </Constructor>
      <CalculatedFields>
        <CalculatedField Name="TNA PPond" Expression="Sum([SaldoCapital] * [AMT.TNA]) / Sum([SaldoCapital])" DataType="Auto" />
        <CalculatedField Name="Plazo P" Expression="Sum([SaldoCapital] * [AMT.Plazo]) / Sum([SaldoCapital])" DataType="Auto" />
      </CalculatedFields>
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Evolucion Tasas" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Measure DataMember="TNA PPond" DefaultId="DataItem0">
          <NumericFormat FormatType="Percent" />
        </Measure>
        <Dimension DataMember="Proceso.FechaReferencia" DateTimeGroupInterval="MonthYear" DefaultId="DataItem1" />
        <Measure DataMember="SaldoCapital" DefaultId="DataItem2">
          <NumericFormat FormatType="Number" Unit="Ones" IncludeGroupSeparator="true" />
        </Measure>
        <Dimension DataMember="Moneda" DefaultId="DataItem3" />
        <Measure DataMember="Plazo P" DefaultId="DataItem4">
          <NumericFormat FormatType="Number" Precision="0" Unit="Ones" />
        </Measure>
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem3" />
      </Columns>
      <Rows>
        <Row DefaultId="DataItem1" />
      </Rows>
      <Values>
        <Value DefaultId="DataItem0" />
        <Value DefaultId="DataItem4" />
        <Value DefaultId="DataItem2" />
      </Values>
    </Pivot>
    <TreeView ComponentName="treeViewDashboardItem1" Name="Periodo" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="Proceso.FechaReferencia" DefaultId="DataItem0" />
        <Dimension DataMember="Proceso.FechaReferencia" DateTimeGroupInterval="Month" DefaultId="DataItem1" />
      </DataItems>
      <FilterDimensions>
        <Dimension DefaultId="DataItem0" />
        <Dimension DefaultId="DataItem1" />
      </FilterDimensions>
    </TreeView>
    <TreeView ComponentName="treeViewDashboardItem2" Name="Sucursales" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="AMT.Sucursal.Nombre" DefaultId="DataItem0" />
      </DataItems>
      <FilterDimensions>
        <Dimension DefaultId="DataItem0" />
      </FilterDimensions>
    </TreeView>
    <Grid ComponentName="gridDashboardItem1" Name="Principales Depositantes" DataSource="dashboardObjectDataSource1">
      <InteractivityOptions MasterFilterMode="Single" />
      <DataItems>
        <Dimension DataMember="AMT.Miembros" SortOrder="Descending" TopNEnabled="true" TopNShowOthers="true" TopNCount="20" TopNMeasure="DataItem2" DefaultId="DataItem0" />
        <Dimension DataMember="Moneda" DefaultId="DataItem1" />
        <Measure DataMember="SaldoCapital" DefaultId="DataItem2">
          <NumericFormat FormatType="Number" Unit="Ones" IncludeGroupSeparator="true" />
        </Measure>
        <Measure DataMember="TNA PPond" DefaultId="DataItem3">
          <NumericFormat FormatType="Percent" />
        </Measure>
        <Measure DataMember="Plazo P" DefaultId="DataItem4">
          <NumericFormat FormatType="Number" Precision="0" Unit="Ones" />
        </Measure>
        <Measure DataMember="SaldoCapital" Name="% Total" DefaultId="DataItem5">
          <NumericFormat FormatType="Percent" />
          <Calculation>
            <PercentOfTotal />
          </Calculation>
          <WindowDefinition>
            <GridWindowDefinition />
          </WindowDefinition>
        </Measure>
      </DataItems>
      <GridColumns>
        <GridDimensionColumn Weight="132.09393346379653">
          <Dimension DefaultId="DataItem0" />
        </GridDimensionColumn>
        <GridDimensionColumn Weight="44.911937377690826">
          <Dimension DefaultId="DataItem1" />
        </GridDimensionColumn>
        <GridMeasureColumn Weight="90.704500978473618">
          <Measure DefaultId="DataItem2" />
        </GridMeasureColumn>
        <GridMeasureColumn Weight="70.450097847358151">
          <Measure DefaultId="DataItem3" />
        </GridMeasureColumn>
        <GridMeasureColumn Weight="43.150684931506873">
          <Measure DefaultId="DataItem4" />
        </GridMeasureColumn>
        <GridMeasureColumn Weight="68.688845401174191">
          <Measure DefaultId="DataItem5" />
        </GridMeasureColumn>
      </GridColumns>
      <GridOptions ColumnWidthMode="Manual" />
    </Grid>
    <ListBox ComponentName="listBoxDashboardItem1" Name="Moneda" DataSource="dashboardObjectDataSource1" ListBoxType="Radio">
      <DataItems>
        <Dimension DataMember="Moneda" DefaultId="DataItem0" />
      </DataItems>
      <FilterDimensions>
        <Dimension DefaultId="DataItem0" />
      </FilterDimensions>
    </ListBox>
    <RangeFilter ComponentName="rangeFilterDashboardItem1" Name="Plazo (dias)" ShowCaption="true" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="AMT.Plazo" DefaultId="DataItem0" />
        <Measure DataMember="SaldoCapital" DefaultId="DataItem1" />
      </DataItems>
      <Argument DefaultId="DataItem0" />
      <Series>
        <Simple SeriesType="Line">
          <Value DefaultId="DataItem1" />
        </Simple>
      </Series>
    </RangeFilter>
    <Chart ComponentName="chartDashboardItem1" Name="Evolucion Plazos y Tasas" DataSource="dashboardObjectDataSource1">
      <DataItems>
        <Dimension DataMember="Proceso.FechaReferencia" DateTimeGroupInterval="MonthYear" DefaultId="DataItem0" />
        <Measure DataMember="TNA PPond" DefaultId="DataItem1">
          <NumericFormat FormatType="Percent" />
        </Measure>
        <Measure DataMember="Plazo P" DefaultId="DataItem2">
          <NumericFormat FormatType="Number" Precision="0" Unit="Ones" />
        </Measure>
      </DataItems>
      <Arguments>
        <Argument DefaultId="DataItem0" />
      </Arguments>
      <Panes>
        <Pane Name="Panel 1">
          <Series>
            <Simple>
              <Value DefaultId="DataItem1" />
            </Simple>
            <Simple PlotOnSecondaryAxis="true">
              <Value DefaultId="DataItem2" />
            </Simple>
          </Series>
        </Pane>
      </Panes>
    </Chart>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutGroup Orientation="Vertical" Weight="72.819472616632865">
        <LayoutItem DashboardItem="pivotDashboardItem1" Weight="49.9383477188656" />
        <LayoutGroup Weight="50.0616522811344">
          <LayoutItem DashboardItem="gridDashboardItem1" Weight="50.139275766016716" />
          <LayoutItem DashboardItem="chartDashboardItem1" Weight="49.860724233983284" />
        </LayoutGroup>
      </LayoutGroup>
      <LayoutGroup Orientation="Vertical" Weight="27.180527383367139">
        <LayoutItem DashboardItem="treeViewDashboardItem2" Weight="22.071516646115906" />
        <LayoutItem DashboardItem="listBoxDashboardItem1" Weight="13.316892725030826" />
        <LayoutItem DashboardItem="rangeFilterDashboardItem1" Weight="24.290998766954377" />
        <LayoutItem DashboardItem="treeViewDashboardItem1" Weight="40.32059186189889" />
      </LayoutGroup>
    </LayoutGroup>
  </LayoutTree>
</Dashboard>

**Comment by apobekiaris** [comment]
post more data like stacktrace hard to tell anything like this

**Comment by vimarx** [comment]
well I can make it work by manually editing 

FROM
<DataSources>
    <ObjectDataSource ComponentName="dashboardObjectDataSource1">
      <Name>Indicador AMT</Name>
      <DataSource Type="Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection, Xpand.ExpressApp.Dashboard, Version=18.1.4.1, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958" />
      <Constructor>
        <Parameter Name="type" Type="System.String">F.Module.Cuentas.amt.IndicadorAMT</Parameter>
      </Constructor>
      <CalculatedFields>
        <CalculatedField Name="TNA PPond" Expression="Sum([SaldoCapital] * [AMT.TNA]) / Sum([SaldoCapital])" DataType="Auto" />
        <CalculatedField Name="Plazo P" Expression="Sum([SaldoCapital] * [AMT.Plazo]) / Sum([SaldoCapital])" DataType="Auto" />
      </CalculatedFields>
    </ObjectDataSource>
  </DataSources>

TO
 <DataSources>
    <ObjectDataSource ComponentName="dashboardObjectDataSource1">
      <Name>IndicadorAMT</Name>
      <DataSource Type="F.Module.Cuentas.amt.IndicadorAMT, Vimarx.F.Module, Version=18.1.6791.31664, Culture=neutral, PublicKeyToken=null" />
      <CalculatedFields>
        <CalculatedField Name="TNA PPond" Expression="Sum([SaldoCapital] * [AMT.TNA]) / Sum([SaldoCapital])" DataType="Auto" />
        <CalculatedField Name="Plazo P" Expression="Sum([SaldoCapital] * [AMT.Plazo]) / Sum([SaldoCapital])" DataType="Auto" />
      </CalculatedFields>
    </ObjectDataSource>
  </DataSources>

**Comment by apobekiaris** [comment]
your IndicatorATM what is so special? why TypesInfo cannot locate? isn't it a domain object? it should be as it is written in the xml in the first place

**Comment by vimarx** [comment]
Don't know, the only thing I found is that entityStore = 2 in TypeSInfo, and the first is the nonpersistentspaceprovider. ..

**Comment by apobekiaris** [comment]
hmmm if 
```cs
XafTypesInfo.Instance.FindTypeInfo("YourFullTypeName")==null
```
then we cannot blame the migration code, there is some issue with the solution that check should be true for all Domain objects

**Comment by vimarx** [comment]
ok, I will continue researching

**Comment by vimarx** [comment]
if I replace the typesinfo line with
DataSourceType = Type.GetType(typeName)

the problem turns to another...
IndicadorAMT has a XafDisplayname "Indicador AMT" (with an space)
so the XML  migration process is wrong (the datasource is not  replaced but duplicated) 

``` xml
  <DataSources>
    <ObjectDataSource ComponentName="dashboardObjectDataSource1">
      <Name>Indicador AMT</Name>
    </ObjectDataSource>
    <ObjectDataSource ComponentName="IndicadorAMT">
      <Name>IndicadorAMT</Name>
      <DataSource Type="F.Module.Cuentas.amt.IndicadorAMT, Vimarx.F.Module, Version=18.1.6791.33491, Culture=neutral, PublicKeyToken=null" />
    </ObjectDataSource>
  </DataSources>

```

**Comment by vimarx** [comment]
aslo calculated fields are missing ....

**Comment by apobekiaris** [comment]
>DataSourceType = Type.GetType(typeName)

this should not work does it? Type.GetType cannot locate outside of an Assembly.

>aslo calculated fields are missing ....

try detailing your problems how you create them and what is wrong. I remember testing them and working fine.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
