### ISSUE TITLE
Scripting.cs

### ISSUE THREAD

**Issue by dnasmyth** [eXpandFramework/eXpand#134]
I am upgrading an old project 17.* to 18.1 and at the same time I changed to NUGet referances. There is a new file in every project called Scripting.cs which has a program class with a Main() method. Visual Studio does not like this as it has no idea where to start running. This file seems to have to do with loading and unloading dlls. I tried deleting it but it wants it. It does not seem to be it the 17.*. It seems to be part of the CSScriptLibrary. What should be done? is this library required for something?

**Comment by apobekiaris** [comment]
https://github.com/oleg-shilo/cs-script/issues/120
