### ISSUE TITLE
Email module: Dynamic operations can only be performed in homogenous AppDomain

### ISSUE THREAD

**Issue by garung10a** [eXpandFramework/eXpand#136]
I've got the error _"Dynamic operations can only be performed in homogenous AppDomain"_ when i use Email Module follow your instruction: http://apobekiaris.blogspot.com/2013/10/how-to-send-mails-for-any-business.html. At this moment, I can bypass this error by set legacyCasModel=false in Web.Config. I don't know this way is right or wrong, or is there any better way to resolve the error?

**Comment by apobekiaris** [comment]
I am not sure that the module is to blame or what we need to do to handle this case without being able to reproduce it. The buildServer on each build runs a similar [easytest] (https://github.com/expand/eXpand/blob/18.1/Demos/Modules/Email/EmailTester.Module/FunctionalTests/Registration/Registration.ets) with success same for my dev machines.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
