### ISSUE TITLE
Move EvaluateExpressionOperator to a separate assembly

### ISSUE THREAD

**Issue by derjabkin** [eXpandFramework/eXpand#140]
EvaluateExpressionOperator uses CSScriptLibrary, which references a lot of .Net Core assemblies. When using nuget packages a lot of .net core assemblies are added to the project, which causes problems when using asp.net precompilation in CI.
My Proposal:

Move EvaluateExpressionOperator to a separate assembly and create a dedicated nuget package.
OR: Move it to PocketXaf project.

**Comment by apobekiaris** [comment]
#135
