### ISSUE TITLE
Exporting Dashboard items to stream + email

### ISSUE THREAD

**Issue by tier2framos** [eXpandFramework/eXpand#145]
Hi,

We use XAF + xpand in our application and we extend WinExportController (XAF) in order to capture all export actions from views and send by email (code below). But the problem is: it does not work in Xpand Dashboard export action (to PDF, image or Excel). Is there some class to extend to get same behavior?

`public class CloudExportController : WinExportController
{
    /// <summary>
    /// Export - overriding to send by email all exports
    /// </summary>
    /// <param name="exportTarget"></param>
    protected override void Export(ExportTarget exportTarget)
    {
        string curUser = DevExpress.ExpressApp.SecuritySystem.CurrentUserId.ToString();
        Employees thisEmployee = View.ObjectSpace.FindObject<Employees>(CriteriaOperator.Parse(string.Format("(User.Oid = '{0}')", curUser)));

        if (thisEmployee != null && thisEmployee.UserCompany != null)
        {
            string ToEmail = thisEmployee.Email;

            #region file

            ImageFormat imageFormat = null;
            MemoryStream stream = new MemoryStream();
            ContentType contentType = new ContentType();

            switch (exportTarget)
            {
                case ExportTarget.Xls:
                    //contentType.MediaType = "application/vnd.ms-excel";
                    contentType.MediaType = MediaTypeNames.Application.Octet;
                    contentType.Name = View.Caption + ".xls";

                    break;
                case ExportTarget.Xlsx:
                    //contentType.MediaType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    contentType.MediaType = MediaTypeNames.Application.Octet;
                    contentType.Name = View.Caption + ".xlsx";
                    break;
                case ExportTarget.Html:
                    contentType.MediaType = MediaTypeNames.Text.Html;
                    contentType.Name = View.Caption + ".html";
                    break;
                case ExportTarget.Mht:
                    contentType.MediaType = "message/rfc822";
                    contentType.Name = View.Caption + ".mht";
                    break;
                case ExportTarget.Pdf:
                    contentType.MediaType = MediaTypeNames.Application.Pdf;
                    contentType.Name = View.Caption + ".pdf";
                    break;
                case ExportTarget.Text:
                    contentType.MediaType = MediaTypeNames.Text.Plain;
                    contentType.Name = View.Caption + ".txt";
                    break;
                case ExportTarget.Rtf:
                    contentType.MediaType = MediaTypeNames.Application.Rtf;
                    contentType.Name = View.Caption + ".rtf";
                    break;
                case ExportTarget.Csv:
                    contentType.MediaType = "text/csv";
                    contentType.Name = View.Caption + ".csv";
                    break;
                case ExportTarget.Image:
                    contentType.MediaType = MediaTypeNames.Image.Jpeg;
                    contentType.Name = View.Caption + ".jpg";
                    imageFormat = ImageFormat.Jpeg;
                    break;
                default:
                    contentType.MediaType = MediaTypeNames.Application.Octet;
                    contentType.Name = View.Caption;
                    break;
            }

            ExportCore(exportTarget, stream, imageFormat);

            contentType.CharSet = "utf-8";
            stream.Position = 0;

            #endregion file

            #region email

            string userName = thisEmployee.UserCompany.EmailUserName;
            string password = thisEmployee.UserCompany.EmailPassword;
            MailMessage msg = new MailMessage();
            msg.To.Add(new MailAddress(ToEmail));
            msg.From = new MailAddress(userName);
            msg.Subject = "Exported File: " + View.Caption;
            msg.Body = "Do not answer this e-mail. Exported File: " + View.Caption;
            
            msg.Attachments.Add(new System.Net.Mail.Attachment(stream, contentType));
            msg.IsBodyHtml = thisEmployee.UserCompany.SMTPIsBodyHtml;
            SmtpClient client = new SmtpClient();
            client.Timeout = thisEmployee.UserCompany.SMTPTimeout;
            client.Host = thisEmployee.UserCompany.SMTPHost;
            client.Credentials = new System.Net.NetworkCredential(userName, password);
            client.Port = thisEmployee.UserCompany.SMTPPort;
            client.EnableSsl = thisEmployee.UserCompany.SMTPEnableSSL;
            client.Send(msg);

            #endregion email

        }
    }
`

thanks

Fernando

**Comment by apobekiaris** [comment]
I am not sure what I have to do to replicate the problem. Can you provide a sample?

**Comment by tier2framos** [comment]
I will explain what I want (maybe its easier way). 

I need to extend  export Xpand Dashboard action (right mouse click and export to PDF, EXCEL or Image), to export to a memory stream, and after that take this stream and send by email. At this way, export action will not open SaveAndFile dialog, and send email.

My code extended XAF export action, that uses DevExpress.ExpressApp.Win.SystemModule.WinExportController class. But I realized that Xpand Dashboard export action it is not descendant of this class

**Comment by apobekiaris** [comment]
are you after something like this?

```cs
    public class Class1:DashboardExportController {

        protected override void OnActivated() {
            base.OnActivated();
            ExportDashboardAction.Executing+=ExportDashboardActionOnExecuting;
        }

        private void ExportDashboardActionOnExecuting(object sender, CancelEventArgs e) {
            var dashboardViewer = CreateDashboardViewer();
            var data = ExportDashboardAction.SelectedItem.Data;
            var memoryStream = new MemoryStream();
            if ((string) data == "PDF") {
                dashboardViewer.ExportToPdf(memoryStream);
            }
            e.Cancel = true;
        }
    }

```

**Comment by tier2framos** [comment]
Yes, but I have tried this code and does not work. I have created as a xaf viewcontroller in module.win


` public partial class CloudXpandDashboardController : Xpand.ExpressApp.XtraDashboard.Win.Controllers.DashboardExportController
    {
        public CloudXpandDashboardController()
        {
            InitializeComponent();
            // Target required Views (via the TargetXXX properties) and create their Actions.
        }
        protected override void OnActivated()
        {
            base.OnActivated();
            // Perform various tasks depending on the target View.
            ExportDashboardAction.Executing += ExportDashboardActionOnExecuting;
        }

        private void ExportDashboardActionOnExecuting(object sender, CancelEventArgs e)
        {
            var dashboardViewer = CreateDashboardViewer();
            var data = ExportDashboardAction.SelectedItem.Data;
            var memoryStream = new MemoryStream();
            if ((string)data == "PDF")
            {
                dashboardViewer.ExportToPdf(memoryStream);
            }
            e.Cancel = true;
        }
        protected override void OnViewControlsCreated()
        {
            base.OnViewControlsCreated();
            // Access and customize the target View control.
        }
        protected override void OnDeactivated()
        {
            // Unsubscribe from previously subscribed events and release other references and resources.
            base.OnDeactivated();
        }
    }`

**Comment by apobekiaris** [comment]
now I understand sorry for the confusion, I will patch the source to fix it and will update you.

**Comment by apobekiaris** [comment]
here a possible solution with the current code base

```cs
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using DevExpress.DashboardCommon;
using DevExpress.DashboardCommon.Native;
using DevExpress.DashboardCommon.Printing;
using DevExpress.DashboardCommon.Service;
using DevExpress.DashboardExport;
using DevExpress.DashboardWin;
using DevExpress.DashboardWin.Forms.Export;
using DevExpress.DashboardWin.Native;
using DevExpress.DashboardWin.Native.Printing;
using DevExpress.DashboardWin.ServiceModel;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.Actions;
using Fasterflect;
using Xpand.ExpressApp.Dashboard.BusinessObjects;
using Xpand.ExpressApp.XtraDashboard.Win.Controllers;
using Xpand.ExpressApp.XtraDashboard.Win.PropertyEditors;

namespace XtraDashboardTester.Module.Win.Controllers {
    public class Class1:DashboardExportController {

        protected override void OnActivated() {
            base.OnActivated();
            ExportDashboardAction.Executing+=ExportDashboardActionOnExecuting;
        }

        class Viewer:DashboardViewer,IDashboardExportUIProvider {
            private readonly Action<MemoryStream> _exported;
            
            public Viewer(Action<MemoryStream> exported) {
                _exported = exported;
            }
//            bool IDashboardExportUIProvider.ShowExportForm(string name, string type, DashboardExportFormat format, IExportOptionsOwner options) {
//
//            }

//            bool IDashboardExportUIProvider.ShowPrintPreviewExportForm(string name, string type, IExportOptionsOwner options) {
//                throw new NotImplementedException();
//            }

            void IDashboardExportUIProvider.ShowSaveFileDialogAndExport(DashboardExportFormat format, IDashboardExportItem exportItem,
                IExportOptionsOwner options) {
                var opt = options.GetActual().GetOptions(format.ConvertToExportFormat(), exportItem.ExportItemType);
                opt.FormatOptions.Format = format;
                var exportService = ServiceContainer.RequestServiceStrictly<IDashboardExportService>();
                var memoryStream = new MemoryStream();
                exportService.PerformExport(memoryStream, exportItem.CreateExportInfo(opt),
                    (Hashtable) this.CallMethod("GetDashboardClientState"));
                _exported(memoryStream);
            }


        }

        protected override DashboardViewer CreateDashboardViewer(Action<MemoryStream> exported) {
            var dashboardViewer = new Viewer(exported) {
                Width = ((Form)Application.MainWindow.Template).Width,
                Height = ((Form)Application.MainWindow.Template).Height
            };
            ((Control) Frame.Template).BeginInvoke(new Action(() => dashboardViewer.Show(Application, (IDashboardDefinition) View.CurrentObject)));
            return dashboardViewer;

        }

        private void ExportDashboardActionOnExecuting(object sender, CancelEventArgs e) {
            
            
            var dashboardViewer = CreateDashboardViewer(stream => {
                var data = ExportDashboardAction.SelectedItem.Data;
                if (data == "PDF") {
                    //send mail
                }
            });
            dashboardViewer.DashboardChanged+= (o, args) => {    
                dashboardViewer.ShowExportForm(DashboardExportFormat.PDF);
            };
            
            e.Cancel = true;
        }

        private void DashboardViewerOnDashboardChanged(object sender, EventArgs e) {
            
        }
    }

    public static class DashboardExtensions {
        public static void ShowExportForm(this DashboardViewer dashboardViewer, DashboardExportFormat exportFormat) {
            dashboardViewer.CallMethod("ShowExportForm",exportFormat);
        }

    }
}

```
