### ISSUE TITLE
ORA-00942: table or view does not exist when press Save button in Persistent Assembly Info area

### ISSUE THREAD

**Issue by YARSUN** [eXpandFramework/eXpand#146]
Hello! I get a error when press Save button in WorldCreator - Persistent Class Info area.
This sql querys:
27.08.18 13:21:31.574 Executing sql 'select N0."Oid",N0."ChangedProperties",N0."TemplateInfo",N1."ChangedProperties",N1."PersistentTypeInfo",N2."ObjectType",N1."Name",N1."TemplateCode",N1."OptimisticLockField",N1."GCRecord",N1."ObjectType",N0."OptimisticLockField",N0."GCRecord" from (("CodeTemplateInfo" N0  left join "TemplateInfo" N1 on (N0."TemplateInfo" = N1."Oid"))  left join "PersistentTypeInfo" N2 on (N1."PersistentTypeInfo" = N2."Oid")) where (N0."GCRecord" is null and :p0 in (N0."TemplateInfo"))' with parameters {0e39d05a-0f47-448a-a2b8-b30c41c98591}
27.08.18 13:21:31.585 Result: rowcount = 1, total = 584, N0.{Oid,Guid} = 16, N0.{ChangedProperties,String} = 4, N0.{TemplateInfo,Guid} = 16, N1.{ChangedProperties,String} = 4, N1.{PersistentTypeInfo,Guid} = 4, N2.{ObjectType,Int32} = 4, N1.{Name,String} = 18, N1.{TemplateCode,String} = 498, N1.{OptimisticLockField,Int32} = 4, N1.{GCRecord,Int32} = 4, N1.{ObjectType,Int32} = 4, N0.{OptimisticLockField,Int32} = 4, N0.{GCRecord,Int32} = 4
27.08.18 13:21:31.588 Executing sql 'select N0."Oid",N0."ChangedProperties",N0."PersistentTypeInfo",N1."ObjectType",N0."Name",N0."TemplateCode",N0."OptimisticLockField",N0."GCRecord",N0."ObjectType" from ("TemplateInfo" N0  left join "PersistentTypeInfo" N1 on (N0."PersistentTypeInfo" = N1."Oid")) where (N0."Oid" = :p0)' with parameters {f73c9cbb-ef6e-4f57-9127-289ed29979f0}
27.08.18 13:21:31.600 Result: rowcount = 1, total = 556, N0.{Oid,Guid} = 16, N0.{ChangedProperties,String} = 4, N0.{PersistentTypeInfo,Guid} = 4, N1.{ObjectType,Int32} = 4, N0.{Name,String} = 18, N0.{TemplateCode,String} = 498, N0.{OptimisticLockField,Int32} = 4, N0.{GCRecord,Int32} = 4, N0.{ObjectType,Int32} = 4
27.08.18 13:21:31.601 Executing sql 'select * from (select N0."Oid" as F0,N1."TargetType" as F1,N1."TargetKey" as F2,N1."OptimisticLockField" as F3,N1."GCRecord" as F4,N1."ObjectType" as F5,N0."GuidId" as F6,N0."IntId" as F7,N0."DisplayName" as F8 from ("AuditedObjectWeakReference" N0  inner join "XPWeakReference" N1 on (N0."Oid" = N1."Oid")) where (N1."GCRecord" is null and (N1."TargetType" = :p0) and (N1."TargetKey" = :p1))) where RowNum <= 1' with parameters {3},{[Guid]'f73c9cbb-ef6e-4f57-9127-289ed29979f0'}
HASKI.Win.exe Error: 0 : 27.08.18 13:21:31.614	================================================================================
The error occurred:

	Type:       SchemaCorrectionNeededException
	Message:    Схема нуждается в обновлении. Обратитесь к администратору системы. Sql текст: ORA-00942: table or view does not exist
 
	Data:       0 entries
	Stack trace:

   в DevExpress.Xpo.DB.ConnectionProviderSql.SelectDataSimple(Query query, CriteriaOperatorCollection targets, Boolean includeMetadata)
   в DevExpress.Xpo.DB.ConnectionProviderSql.SelectData(Query query, CriteriaOperatorCollection targets, Boolean includeMetadata)
   в DevExpress.Xpo.DB.DataStoreBase.ProcessSelectData(SelectStatement[] selects)
   в DevExpress.Xpo.DB.DataStoreSerializedBase.SelectData(SelectStatement[] selects)
   в DevExpress.Xpo.DB.ConnectionProviderSql.SelectData(SelectStatement[] selects)
   в DevExpress.Xpo.SimpleDataLayer.ReentrancyAndThreadSafetyChecked[T](Func`1 action)
   в DevExpress.Xpo.Helpers.ObjectCollectionLoader.InternalLoadData(ObjectsQuery[] queries)
   в DevExpress.Xpo.Helpers.ObjectCollectionLoader.LoadObjects(ObjectsQuery[] queries)
   в DevExpress.Xpo.SimpleObjectLayer.LoadObjects(Session session, ObjectsQuery[] queries)
   в DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   в DevExpress.Xpo.Session.GetObjects(ObjectsQuery query)
   в DevExpress.Xpo.Session.<>c__DisplayClass3e.<FindObject>b__3c()
   в DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   в DevExpress.Xpo.Session.FindObject[ClassType](CriteriaOperator criteria)
   в DevExpress.Persistent.AuditTrail.AuditDataStore`2.CreateAuditDataStoreItem(Dictionary`2 auditedObjectWeakReferenceCache, Session session, Session auditDataItemSession, AuditDataItem auditDataItem, String currentUser)
   в DevExpress.Persistent.AuditTrail.AuditDataStore`2.Save(Session session, List`1 itemsToSave, IAuditTimestampStrategy timestampStrategy, String currentUserName)
   в DevExpress.Persistent.AuditTrail.AuditTrailService.SaveAuditDataByDefault(Session session, List`1 itemsToSave)
   в DevExpress.Persistent.AuditTrail.AuditTrailService.InternalSaveAuditData(Session session, List`1 itemsToSave)
   в DevExpress.Persistent.AuditTrail.AuditTrailService.SaveAuditData(Session session)
   в DevExpress.ExpressApp.AuditTrail.AuditTrailModule.ObjectSpace_Committed(Object sender, EventArgs e)
   в System.EventHandler.Invoke(Object sender, EventArgs e)
   в DevExpress.ExpressApp.BaseObjectSpace.OnCommitted()
   в DevExpress.ExpressApp.BaseObjectSpace.CommitChanges()
   в DevExpress.ExpressApp.Win.SystemModule.WinModificationsController.Save(SimpleActionExecuteEventArgs args)
   в DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       OracleException
			Message:    ORA-00942: table or view does not exist
			Data:       0 entries
			Stack trace:

   в System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   в System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor& rowidDescriptor, ArrayList& resultParameterOrdinals)
   в System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList& resultParameterOrdinals)
   в System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   в DevExpress.Xpo.DB.ConnectionProviderSql.<>c__DisplayClass6.<InternalGetData>b__4()
   в DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   в DevExpress.Xpo.DB.ConnectionProviderSql.SelectDataSimple(Query query, CriteriaOperatorCollection targets, Boolean includeMetadata)
			InnerException is null

--------------------------------------------------------------------------------
Error raise because XPWeakReference table not exist in HASKICREATOR sheme:
select * from 
(select N0."Oid" as F0,N1."TargetType" as F1,N1."TargetKey" as F2,N1."OptimisticLockField" as F3,N1."GCRecord" as F4,N1."ObjectType" as F5,N0."GuidId" as F6,N0."IntId" as F7,N0."DisplayName" as F8 
from ("AuditedObjectWeakReference" N0  inner join "XPWeakReference" N1 on (N0."Oid" = N1."Oid")) where (N1."GCRecord" is null and (N1."TargetType" = :p0) and (N1."TargetKey" = :p1))) where RowNum <= 1

What source of problem can be?

![db s](https://user-images.githubusercontent.com/40893033/44648015-95388a80-aa01-11e8-8a3b-83a4b731f555.jpg)
![programerror](https://user-images.githubusercontent.com/40893033/44648017-95388a80-aa01-11e8-91e6-9943a46c66fe.jpg)

**Comment by apobekiaris** [comment]
i have to get back to you tomorrow after I consult with the XAF team, it looks like an AuditTrail thing and your configuration probably is a large factor.

**Comment by apobekiaris** [comment]
did you ever had AudiTrail and WC in this solution? or is it an update thing again?

**Comment by apobekiaris** [comment]
I discussed this issue with our XPO devs and they just confirm the obvious. The XPWeakReferece is the required table if the Audit Trail Module is used. According to the callstack, it is used in the application.
The DBUpdater tool should create this table along with others. Alternatively if your WinApplication.cs contains this code and you try to debug the project the tables should be genarated also.

```cs
if(System.Diagnostics.Debugger.IsAttached) {
                e.Updater.Update();
                e.Handled = true;
            }
```

It is unclear why this error is not raised when the user just edits something. Can you try to replicate it on a sample where you can put only a small part of your domain where you use the AuditTrail and the WC ?

**Comment by apobekiaris** [comment]
after further analysis and help from the XPO guys, looks like the is a problematic part in WC. I am still researching and I will get back to you.

**Comment by YARSUN** [comment]
Hi! Thank for help! I'll try create sample in next several days.

**Comment by YARSUN** [comment]
"did you ever had AudiTrail and WC in this solution? or is it an update thing again?" - yeah we use AuditTrail module in project

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by rajkamal0610** [comment]
I want to reopen the issue. 

If we add Audit trail module in main application then the dbcreator database doesn't created any of the tables related to Audit trail.

**Comment by apobekiaris** [comment]
WC creates dynamically assemblies our of the PersistestenAssembly BO and its childs. It does not know anything about any other module, therefore it should not being affected it if Audittrail or any other module is installed. In any case you need to check the log for possible errors when generating the dynamic assembly.
