### ISSUE TITLE
Can't create Custom Attributes after update to 18.1.5.4 (XAF 18.1.5.0)

### ISSUE THREAD

**Issue by YARSUN** [eXpandFramework/eXpand#147]
Hi! After update on lattest version my project get a error when start application.

Stack:
It is impossible to check the database schema for the 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentTypeInfo' element of the 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentTypeInfo' type. Error: The operation intended for the persistent class was performed on the non-persistent class 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentAttributeInfo'.

   в DevExpress.Xpo.Metadata.XPClassInfo.AddClassToDirectlyRefTypes(Dictionary`2 targetList, XPClassInfo info, String refClassName, String refMemberName)
   в DevExpress.Xpo.Metadata.XPClassInfo.GetDirectlyRefTypes()
   в DevExpress.Xpo.Metadata.XPClassInfo.FillRefTypes(Dictionary`2 filled)
   в DevExpress.Xpo.Metadata.XPClassInfo.FillRefTypes(Dictionary`2 filled)
   в DevExpress.Xpo.Metadata.XPClassInfo.GetRefTypes()
   в DevExpress.Xpo.Metadata.XPDictionary.ExpandTypesToEnsure(XPClassInfo[] inputTypesToEnsure, IDictionary`2 alreadyEnsuredTypes)
   в DevExpress.Xpo.SimpleDataLayer.UpdateSchema(Boolean dontCreate, XPClassInfo[] types)
   в DevExpress.ExpressApp.Xpo.XPObjectSpaceProvider.DevExpress.ExpressApp.IObjectSpaceProvider.UpdateSchema()
   в DevExpress.ExpressApp.Updating.DatabaseUpdaterBase.UpdateCore(IObjectSpace updatingObjectSpace, IList`1 versionInfoList)
   в DevExpress.ExpressApp.Updating.DatabaseUpdater.Update()

Where I mistake?
![programmerror2](https://user-images.githubusercontent.com/40893033/44649385-805df600-aa05-11e8-8eec-0bb2a8ce2a55.jpg)

**Comment by apobekiaris** [comment]
also your actions are not clear I do not see how the issue subject relates to "Hi! After update on lattest version my project get a error when start application."

please explain in details and provide more info

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
