### ISSUE TITLE
ExcelImporter on web not proposing property names until the ExcelImport is changed

### ISSUE THREAD

**Issue by simonlary** [eXpandFramework/eXpand#148]
In the ExcelImporter module, the list of property names is not updated until the ExcelImport object is modified, so when you open an already existing ExcelImport, there is no property name dropdown.

**Comment by apobekiaris** [comment]
I need more details, my tests against the ExcelImporterTester worked fine.
see this screencast https://www.screencast.com/t/G8dCSju2

**Comment by simonlary** [comment]
Sorry i forgot to specify that this is in the web version.

**Comment by simonlary** [comment]
By looking more into it, it seems like it only happens when you go edit an ExcelImport object and you didn't create any ExcelImport object since the application started. So if you :

1. Start the application
2. Create and save a new ExcelImport object with some mapping
3. Stop the application
4. Start the application again
5. Go try to edit the property names of the mapping of the previously created ExcelImport object

Then there is no property name dropdown. It also happens if you create the ExcelImport object in the Updater.

I added the creation of an ExcelImport in the Updater of the sample, so if you start it and try to edit one of its property names there is no dropdown that appears.

[TestExcelImport.zip](https://github.com/eXpandFramework/eXpand/files/2329769/TestExcelImport.zip)

**Comment by apobekiaris** [comment]
thanks for the help, I fixed this issue in this [patch](https://www.dropbox.com/s/9j4jomj8jt7x9zb/eXpandFramework-18.1.5.41.exe?dl=0)

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
