### ISSUE TITLE
Dashboard loading error after BO module version update

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#152]
I can re-open a dashboard after changing version number. (even after restarting in vs)

https://www.screencast.com/t/LfxEYqYTCtab

04.09.18 18:32:27.095	================================================================================
The error occurred:

	Type:       InvalidNameException
	Message:    Esta colección ya contiene un elemento con el nombre ' IndicadorPrestamo'
	Data:       0 entries
	Stack trace:

   en DevExpress.DashboardCommon.Native.ObjectNameGenerator.CheckName(String name)
   en DevExpress.DashboardCommon.Native.ObjectTypeNameGenerator.CheckName(String name)
   en DevExpress.DashboardCommon.Native.DashboardComponentNameController`1.CheckComponentName(String name)
   en DevExpress.DashboardCommon.Native.ComponentNameControllerBase`1.OnBeforeItemAdded(Object sender, NotifyingCollectionBeforeItemAddedEventArgs`1 e)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.DataAccess.NotifyingCollection`1.BeforeAddItem(T item)
   en DevExpress.DataAccess.NotifyingCollection`1.InsertItem(Int32 index, T item)
   en System.Collections.ObjectModel.Collection`1.Add(T item)
   en Xpand.ExpressApp.Dashboard.Services.Extensions.AddNewDataSources(IDashboardDefinition dashboardDefinition, Dashboard dashboard)
   en Xpand.ExpressApp.Dashboard.Services.Extensions.GetDashboard(IDashboardDefinition dashboardDefinition)
   en Xpand.ExpressApp.Dashboard.Services.Extensions.GetDashboard(IDashboardDefinition dashboardDefinition, XafApplication application, RuleMode ruleMode, IXpandDashboardDataSourceFillService dashboardDataSourceFillService, DataSourceOptionsContainer options, Action`1 editParameters, Action modeParametersEdited)
   en Xpand.ExpressApp.XtraDashboard.Win.Templates.DashboardDesignerForm.LoadTemplate(IDashboardDefinition dashboardDefinition, XafApplication application)
   en Xpand.ExpressApp.XtraDashboard.Win.Controllers.DashboardDesignerController.DashboardEditExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by vimarx** [comment]
BTW  I'm signing assemblies

**Comment by apobekiaris** [comment]
Thanks for the screencast, I watch it carefully many times and I do not see whats different in your case. I tried to repro it in the XtraDashboardTester solution but failed. Can you help?

**Comment by vimarx** [comment]
in short
If I use strong-named assemblies and tried to open an existing dashboard with a newer version of the BO assemblies, the error appears.
In the screencast, I tried to do it faster by touching the Xml assembly version number

**Comment by vimarx** [comment]
Also, notice that the name of BO -> IndicadorPrestamo is captioned with a space as "Indicador Prestamo"
is this causing an issue?

**Comment by apobekiaris** [comment]
can you test this controller

```cs
using System;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using DevExpress.ExpressApp;
using Xpand.ExpressApp.Dashboard.BusinessObjects;
using Xpand.ExpressApp.Dashboard.Services;

namespace XtraDashboardTester.Module.Controllers {
    public class UpdateDashboardObjectDatasourceTypesController:ObjectViewController<DetailView,IDashboardDefinition> {
        protected override void OnActivated() {
            base.OnActivated();
            View.CurrentObjectChanged+=ViewOnCurrentObjectChanged;
            TestDashboradAssemblyBindings();
        }

        protected override void OnDeactivated() {
            base.OnDeactivated();
            View.CurrentObjectChanged-=ViewOnCurrentObjectChanged;
        }

        private void TestDashboradAssemblyBindings(){
            var dashboardDefinition = ((IDashboardDefinition) View.CurrentObject);
            AppDomain.CurrentDomain.AssemblyResolve += CurrentDomainOnAssemblyResolve;
            dashboardDefinition.ToDashboard();
            AppDomain.CurrentDomain.AssemblyResolve -= CurrentDomainOnAssemblyResolve;
        }

        private Assembly CurrentDomainOnAssemblyResolve(object sender, ResolveEventArgs args) {
            var value = Regex.Match(args.Name, @"\A.[^,]*").Value;
            return AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(assembly => assembly.GetName().Name == value);
        }

        private void ViewOnCurrentObjectChanged(object sender, EventArgs e) {
            TestDashboradAssemblyBindings();
        }
    }
}
```

**Comment by vimarx** [comment]
I can't find this method in my 18.1.5.4 (ported to 18.1.5.5) version, where is it defined?

dashboardDefinition.ToDashboard();

**Comment by apobekiaris** [comment]
oops sorry not available yet, try the [LoadFromXml](https://github.com/eXpandFramework/eXpand/blob/c40e4f571fbfd29af4321c60d7fa7cfc599a5474/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs#L122)

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
