### ISSUE TITLE
Disable Sequence Generator for non supported providers

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#155]
#151

**Comment by apobekiaris** [comment]
for now did you tried?

```cs
SequenceGenerator.SupportedFactories.Add(typeof(MSSqlProviderFactory),typeof(YouCustomSqlProvider));
```cs

**Comment by CWolffIF** [comment]
Hi Tolis,
I tried with 16.1.6.1
`SequenceGenerator.SupportedProviders.Clear();
SequenceGenerator.SupportedProviders.Add(typeof(MSSqlProviderFactory));`

The same Error.

**Comment by apobekiaris** [comment]
@CWolffIF sorry I missed your post, please feel free to ping me again. Also provide the connectionstring you using

**Comment by CWolffIF** [comment]
Hi Tolis,
no problem. I use MSSQL server 2017:
<add name="ConnectionString" connectionString="Integrated Security=SSPI;Pooling=false;Data Source=xxx\xxxx;Initial Catalog=xxxx" />

**Comment by apobekiaris** [comment]
@CWolffIF please subscribe to #161 as it is the same issue

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
