### ISSUE TITLE
Provide Custom SequenceObject

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#167]
Is there a way to plug my own implementation of a sequence generator into the framework? I use the ModelDifference module and the Expand Sequence Generator causes lots of locked tables in production.

Looking for a way to connect my custom type to the ModelDifference Module on app startup. Thanks!

Xpand.Persistent.BaseImpl.SequenceObject

**Comment by apobekiaris** [comment]
did you already tried the [XpandModuleBase.SequenceObjectType](https://github.com/eXpandFramework/eXpand/blob/eba2ef498788cd6ae633d9942c76a6f88268a3f8/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/SequenceGenerator.cs#L98)?

**Comment by capricciobob** [comment]
That is exactly what I was looking for. Sorry to clutter up GitHub. Is this still the correct place to ask questions? I noticed the forum was locked.

**Comment by apobekiaris** [comment]
the ModelDifference module uses the sequencegenerator to define the merging order. You can probably take that step manually and remove the sequence generator with this [patch](https://www.dropbox.com/s/pdnsnblek8om99o/eXpandFramework-18.1.6.12.exe?dl=0) and this line on your `Program.cs`

```cs
SequenceGenerator.SupportedFactories.Clear()
```

**Comment by capricciobob** [comment]
I tired setting the SequenceObjectType and the patch, but then it complains that I don't have the Xpand.BaseImpl dll. I don't use that. For now, I just comment out the Sequence lines from ModelDifferenceObject.cs

**Comment by apobekiaris** [comment]
i will try once more then and add this ticket to the BackLog 

```cs
        public override void Setup(ApplicationModulesManager moduleManager) {
            base.Setup(moduleManager);
            var modules = moduleManager.Modules.OfType<XpandModuleBase>();
            foreach (var module in modules) {
                module.InitSeqGenerator+=(sender, e) => e.Cancel = true;
            }
        }
```
To disable sequence generator add this code to one of your modules. I will add this code to the BackLog for refactoring

**Comment by capricciobob** [comment]
That eliminated the need to have BaseImpl, thank you!

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
