### ISSUE TITLE
Multidatastore and many-to-many relationships

### ISSUE THREAD

**Issue by wullumpie** [eXpandFramework/eXpand#170]
Hi Tolis,
I'm experiencing a problem with the MultiDatastore feature and the implicitly generated table to hold the keys to both tables. The application cannot find the generated table when the data tables are not in the default database. It seems that the system tries to find the generated table in the default database.
Can you tell me how to solve this problem?
Kind regards, Willem

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
