### ISSUE TITLE
Excel Importer - Save models

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#173]
Thanks Tolis ! 

Is there any way to save my import models ? I have 20 defined and do want to recreate (2hours) every time that i create a new database ? 

My initial idea was to create a model that import my 20 models. I could do a simple action to achieve this.  This was alsmost working but the file (filedata) is mandatory and we cannot set the file in the mapping. 

Any idea how to achieve this ? 

BR
ISA

**Comment by apobekiaris** [comment]
what do you mean save the models? export them? You can use the IO module for this as it can export/import configurable domain trees.

**Comment by apobekiaris** [comment]
You can export any object domain using the UI and the popup action IO/Export and then in a ModuleUpdater you can import on a new db. Similar to what FeatureCenter does to import the NorthWind db for WorldCreator.

https://github.com/eXpandFramework/eXpand/blob/18.1/Demos/FeatureCenter/FeatureCenter.Module/WorldCreator/NorthWind/WorldCreatorUpdater.cs#L26-L27

**Comment by isatahiri** [comment]
Hello,

I will try IO/Export and import. Sorry, I'm a new user and do not know all module yet. 

BR
ISA
