### ISSUE TITLE
ExcelImporter suggestion: create new fields

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#174]
It would be very useful to let the user mark fields that do not map to existing, define their types and create them automatically before importing.

**Comment by apobekiaris** [comment]
example missing

**Comment by emeyke** [comment]
Existing fields:
Person.FirstName
Person.LastName

Excel file:
FirstName
LastName
Age

Age would not map to existing fields and should be created by the importer.

By created I mean something like this:

`public static bool CreateField(XafApplication application,string viewid, IObjectSpace objectSpace, string column, string column_caption, Type oftype, Type coltype)
        {

            if (XafTypesInfo.Instance.FindTypeInfo(oftype).FindMember(column) != null)
            {
                return false;
            }
            var modelDifferenceObject = objectSpace.FindObject<ModelDifferenceObject>(new BinaryOperator("Name", application.Title));
            if (modelDifferenceObject == null) return false;
            modelDifferenceObject.ModifyModel(modelDifferenceObject, modelApplication => CreateNewMember(application, oftype, column, column_caption, coltype, modelApplication, modelDifferenceObject));
            modelDifferenceObject.Save();

            objectSpace.CommitChanges();
            return true;

        }`

**Comment by apobekiaris** [comment]
There are several attributes you can use in code to describe how the map is done.
https://github.com/eXpandFramework/eXpand/blob/18.1/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/BusinessObjects/ExcelImport.cs#L114-L128

Are they not of use for your case?

> `public static bool CreateField(XafApplication application,string viewid, IObjectSpace objectSpace, string column, string column_caption, Type oftype, Type coltype)
{

        if (XafTypesInfo.Instance.FindTypeInfo(oftype).FindMember(column) != null)
        {
            return false;
        }
        var modelDifferenceObject = objectSpace.FindObject<ModelDifferenceObject>(new BinaryOperator("Name", application.Title));
        if (modelDifferenceObject == null) return false;
        modelDifferenceObject.ModifyModel(modelDifferenceObject, modelApplication => CreateNewMember(application, oftype, column, column_caption, coltype, modelApplication, modelDifferenceObject));
        modelDifferenceObject.Save();

        objectSpace.CommitChanges();
        return true;

    }`

also it is not clear at all why your posted that snippet, how it relates to ExcelImporter.

**Comment by apobekiaris** [comment]
yes now I see, I have to research further there will be thread safe issues of course if users try the same table notification concurrently.

**Comment by emeyke** [comment]
Perhaps it makes sense to isolate "Create field" functionality as Xpand separate feature and then reuse it in importer. I use this simple implementation in all projects as it takes xaf app customizability to the next level...

**Comment by apobekiaris** [comment]
you can create fields in Xpand using either the model or WorldCreator so it already an isolated feature as I see it or whats your experience

**Comment by emeyke** [comment]
Right. It is more about exposing it in a user friendly interface especially for web only setup with minimal or no access to model editor.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
