### ISSUE TITLE
ExcelImporter suggestion: report results of import

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#175]
Show text summary of objects number created, updated per object

**Comment by apobekiaris** [comment]
please post some details is not clear what you mean

**Comment by emeyke** [comment]
I mean something simple to let the user know what actually happened during the import.
E.g.
Objects created
Person: 123
Product: 1234

Objects updated:
Store: 3
Product: 4

Actually the requests we are getting from users importing data to have this kind of report more interactive with the ability to check the records straight after importing. E.g. view the list of created and/or updated objects.
But this is getting too complex and most important is to know in general numbers.
The reason being that often the result of import differs from expectations.
E.g. some values for reference properties were mistyped and while NO reference objects were supposed to be created, some are created by (user) mistake.

Hope this helps
Evgeniy

**Comment by emeyke** [comment]
Perhaps it makes sense to isolate "Create field" functionality as Xpand separate feature and then reuse it in importer. I use this simple implementation in all projects as it takes xaf app customizability to the next level...

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
