### ISSUE TITLE
Excel Importer - New features 

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#176]
Hello,
The Excel Importer is a really nice feature and I would like to ask for new features.
Well two nice features would be.

1. parameter before import defining if non existing data from reference should be created or not. (if not so this should be considered like error)

 2. A progress bar informing the status. I imported 1.5k of records with 20 columns. It worked goot but for 45 seconds I did not know what was happening.

BR
ISA

**Comment by apobekiaris** [comment]
see #185  for your first point

**Comment by emeyke** [comment]
N1 is different from https://github.com/eXpandFramework/eXpand/issues/185
This is should probably be part controlled by import stragegy.

**Comment by apobekiaris** [comment]
hmm you are right my bad sorry

**Comment by emeyke** [comment]
However, in the update and create scenario, it is really important to have an understanding of what happened after importing large and complex files (this has been requested a lot) - https://github.com/eXpandFramework/eXpand/issues/175

**Comment by apobekiaris** [comment]
sure it relates but lets discuss #175 separately is too complex task and we need a smart solution, Feel free to update your suggestion if you have ideas.

N1 looks like #185 we can introduce a new field FailWhenNotFound perhaps?? because the `ImportStrategy` applies to the main object type and cannot be used again.

**Comment by apobekiaris** [comment]
now I got it we can introduce an `ImportStrategy` on each field similar to the main object

**Comment by emeyke** [comment]
Why not have the same strategy field for each import field?

**Comment by emeyke** [comment]
man, reading it again :)

**Comment by apobekiaris** [comment]
>Why not have the same strategy field for each import field?

i cannot follow

**Comment by emeyke** [comment]
> now I got it we can introduce an ImportStrategy on each field similar to the main object
I meant the same. You typed 10 seconds faster.

**Comment by apobekiaris** [comment]
wrong cause I already change my mind :) #175 is the first item of the new

```cs
public enum PersistentTypesImportStrategy {
        SkipEmpty,
        CreateAlways,
        UpdateOrCreate,
StillThinkingWhatCanBeHere
    }

```

**Comment by emeyke** [comment]
So why should it be different from ImportStrategy? 
SkipEmpty does is not needed - if it is empty, you always skip it.
```
public enum ImportStrategy{
        CreateAlways,
        UpdateOrCreate,
        SkipOrCreate
    }
```

**Comment by emeyke** [comment]
but it WOULD be great to define this per each reference property. By default, after mapping fields, it could be the same as main ImportStrategy

**Comment by apobekiaris** [comment]
@isatahiri suggested a failed mode which does not exist in main strategy

**Comment by emeyke** [comment]
What we had to do after importing files like this - go and check if no records were created after import, both master record and reference. When they were not meant to be and if this happened it means there was a spelling error in the import file

**Comment by apobekiaris** [comment]
these strategies sound very useful however my feeling is that your spelling work could be reduced with the use of the `Soundex` function

https://database.guide/how-the-sql-server-soundex-function-works/

**Comment by emeyke** [comment]
Well, spelling is just one scenario (and thanks for the link). 
There could be a multitude of reasons why UpdateOnly would be preferred.

**Comment by apobekiaris** [comment]
nightly build 
https://www.dropbox.com/s/uouf1bgzgwlyiiz/eXpandFramework-18.1.6.26.exe?dl=0
https://www.dropbox.com/s/6atodgc1fk729m6/Nupkg-18.1.6.26.zip?dl=0

**Comment by apobekiaris** [comment]
I am locking this one is getting too long, open new posts for each case please.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
