### ISSUE TITLE
I/O Export - Security roles

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#177]
Hello,

In accordance to the issue #173 : 
I tried the I/O Export from the tester app. 
My interess was to do a export and import. This is working well.

How can I via security role deny some user to use the functionnality. 
I try this : 
![image](https://user-images.githubusercontent.com/41955268/45785401-7463fd80-bc6c-11e8-960e-79eb99fb189f.png)

but the user still have access to it via the context menu. 

BR
ISA

**Comment by apobekiaris** [comment]
yeah you are right the action should be disabled if the role has no read permission to the SerializationConfigurationGroup.

at the moment though you can add an ActionState permission usinf the ModelAArtifact.
![image](https://user-images.githubusercontent.com/159464/45808156-cdb04900-bccd-11e8-9409-306d31697225.png)
![image](https://user-images.githubusercontent.com/159464/45808190-e456a000-bccd-11e8-9d9f-a399f48a3466.png)

The ModelArtifact module is installed from the IO module so you can try this without code from the UI. Note that eXpandFramework does not support custom permissions (like the ActionState) in the middle tier scenarion.

from the next minor I will add native support for this like

```cs
    public class Class1:ViewController<ListView> {
        protected override void OnActivated() {
            base.OnActivated();
            var bussinessObjectType = XafTypesInfo.Instance.FindBussinessObjectType(typeof(ISerializationConfigurationGroup));
            Frame.GetController<IOViewController>().IOAction.Active["Security"] =
                DataManipulationRight.CanRead(bussinessObjectType, null, null, null, ObjectSpace);
        }
    }

```

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
