### ISSUE TITLE
Error on shared web server

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#178]
Hello, 
I deployed my application in web server (external provider) in a regular iis. 
After deplyoment i have the following issue : 

`[UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Inetpub\vhosts\pme-affaires.ch\demo.pme-affaires.ch\ModelAdaptor" wurde verweigert.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +12841725
   System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) +12956069
   System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost) +82
   System.IO.Directory.CreateDirectory(String path) +33
   Xpand.Persistent.Base.ModelAdapter.InterfaceBuilder.CompileAssemblyFromSource(String source, String[] references, Boolean isDebug, String assemblyFile) in C:\expandframework\eXpand\Xpand\Xpand.Persistent\Xpand.Persistent.Base\ModelAdapter\InterfaceBuilder.cs:161
   Xpand.Persistent.Base.ModelAdapter.InterfaceBuilder.Build(IEnumerable`1 builderDatas, String assemblyFilePath) in C:\expandframework\eXpand\Xpand\Xpand.Persistent\Xpand.Persistent.Base\ModelAdapter\InterfaceBuilder.cs:123
   Xpand.Persistent.Base.General.Web.CustomizeASPxPopupController.ExtendModelInterfaces(ModelInterfaceExtenders extenders) in C:\expandframework\eXpand\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\Web\CustomizeASPxPopupController.cs:58
   DevExpress.ExpressApp.ApplicationModelManager.CreateModelApplicationCreatorProperties(IEnumerable`1 modules, IEnumerable`1 controllers, String assemblyFileAbsolutePath) +222
   DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile) +339
   DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes) +220
   DevExpress.ExpressApp.Web.WebApplication.CreateModelManager(IEnumerable`1 boModelTypes) +161
   DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters) +232
   DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security) +491
   DevExpress.ExpressApp.XafApplication.Setup() +97
   PME_Affaire.Web.Global.Session_Start(Object sender, EventArgs e) in C:\Users\isata\Documents\Source TFS\PME_Affaire\PME_Affaire.Web\Global.asax.cs:44
   System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e) +10067203
   System.Web.SessionState.SessionStateModule.CompleteAcquireState() +160
   System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) +1095
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +254
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

I use the following dlls : 
![image](https://user-images.githubusercontent.com/41955268/45903855-625c9900-bdeb-11e8-8f25-1303334ac110.png)

Can you help me please ? 

BR
ISA

**Comment by isatahiri** [comment]
Hello,

Additionnal info : 
This works in local in my computer. 

If i take away the the excel importer and other dll from expand, i can run the deployed web application. 

BR
ISA

**Comment by isatahiri** [comment]
Hello,

After some checks, i found out that the issue was due to the security related to the app_pool

Case solved.

BR
ISA

**Comment by apobekiaris** [comment]
some of the framework modules dynamically generate assemblies in the root/ModelAdaptor folder. If you did not deploy the contnents of that folder it will try to generate them again once at app startup. So you need either to give permissions or use the pre generated assemblies.
