### ISSUE TITLE
Excel Importer - Reference Property

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#179]
Hello,

I have a import model with reference property but sometimes the value is empty in the excel file. 
The property is not mandatory in my BO. 

When i try to import, it looks that the module is trying to create a record using the empty value. 

Can we consider that when the field is empty (String.IsNullOrEmpty) there is no record to check or create.

BR
ISA

**Comment by apobekiaris** [comment]
sorry I missed this one please ping me if I delay again. I think we should link this ticket to the new column strategies discussed in #176

**Comment by isatahiri** [comment]
Sorry, these days are quite busy in my side too. I saw the #176 and i agree. 

BR
ISA

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
