### ISSUE TITLE
Excel Importer - 1 solution The object you are trying to save was changed by another user. Please refresh data

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#181]
Hello,

In the excel importer, i have often the popup when i save "The object you are trying to save was changed by another user. Please refresh data"

So basically i choose a file, set the sheet, give a name, get the type, select the header row and save. 

![image](https://user-images.githubusercontent.com/41955268/45933400-20b72400-bf8c-11e8-8648-0a06f63b46a8.png)

Can you have a look please. ? 

Many thanks 
BR
ISA

**Comment by apobekiaris** [comment]
Yes I already fixed a bug which I believe is related I ll post a patched installer soon

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
