### ISSUE TITLE
ExcelImport: Empty reference values should be skipped

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#185]
Currently it would attempt to create a reference record with an empty default property.

**Comment by apobekiaris** [comment]
nightly build 
https://www.dropbox.com/s/uouf1bgzgwlyiiz/eXpandFramework-18.1.6.26.exe?dl=0
https://www.dropbox.com/s/6atodgc1fk729m6/Nupkg-18.1.6.26.zip?dl=0

**Comment by emeyke** [comment]
In this build you have SkipEmpty as an alternative to UpdateOrCreate and others.
I firmly believe that this is not an option to select, but it should be always SkipEmpty for any cell in the import file.

I would leave for both import strategies (main object and reference properties)
public enum ImportStrategy{
        CreateAlways,
        UpdateOrCreate,
        UpdateOnly
    }

And one more observation. ExcelColumnMap, ImportStrategy would only apply to reference properties.

**Comment by apobekiaris** [comment]
>I firmly believe that this is not an option to select, but it should be always SkipEmpty for any cell in the import file.

how do you null a value of an existing object?

**Comment by emeyke** [comment]
Ok maybe we are talking about different things or I don't understand the purpose here.
I suggest that if the cell in the file you are importing is empty, you do not act on it at all, it remains null in the created record. And it does not matter if it is a simple property or reference property. No?
I can understand FailIfEmpty flag which potentially be used in some case but it fallse more into validation realm rather than deailing with it at import level.

**Comment by apobekiaris** [comment]
so you update a list of `Customers` and some cell are null for the `LastName` you always end with these records never get updated. Does this sound correct to you?

**Comment by emeyke** [comment]
In my experience most update imports never attempted to nullify the values but I agree it could be needed in some cases. If this option is available it needs to be implemented in a very safe way. I could suggest that there is a separate flag at the whole ExcelImport object that is off by default. Even safer option would be to have it at the field level and it is off be default for all fields. 
What do you think?
What do others think?
After several years of assisting users with importing data (using custom own importer) it has never been an issue that nulls are updated. It would be a big issue if this was available and misused accidentally.

**Comment by Ezeckiel2517** [comment]
I have the same problem. An excel column with empty cell binded to a reference property will attemp to create a record with an empty default property.

I'm looking at the new import code and I don't think it fix the problem.
Looking at the new PersistentTypesImportStrategy, the one closer to the desired behavior is UpdateOnly.
On import, the reference property will be null because the FindObject will fail (the criteria look like "[propertyname] = null" which never work, even if an object in the database has that property to null).
When we re-import existing object with ImportStrategy.UpdateOrCreate, if my existing object has a value, it will not be set to null, which is a contradiction to PersistentTypesImportStrategy.UpdateOnly.

As for PersistentTypesImportStrategy.SkipOrCreate, I do not see any use for that.
If my excel column got a value that reference an object, why would i want it so skip the assignation if the reference object exist...

**Comment by Ezeckiel2517** [comment]
I'd suggest to change the method "ImportExtension.Imported" with the following else part :

```C#
try{
	var referenceObject = GetReferenceObject(objectSpace, importStrategy, type, keyMember, result);
	if (referenceObject != null) {
		keyMember.SetValue(referenceObject, result);
		memberInfo.SetValue(importToObject, referenceObject);
	}
	else if (importStrategy == PersistentTypesImportStrategy.UpdateOnly) {
		memberInfo.SetValue(importToObject, referenceObject);
	}
}
```

**Comment by apobekiaris** [comment]
thnks for the suggestion I ll get back to u once I review it, feel free to post more suggestions or pull requests. At the moment there are major works on the module so I am a bit overloaded sorry for this.

**Comment by Ezeckiel2517** [comment]
I'd like to contribute with pull request but unfortunately, I do not have an environment that can compile the source code, due to C# 7 spec not being well supported in VS2015

**Comment by apobekiaris** [comment]
its fine with me either way you choose.

**Comment by emeyke** [comment]
>>As for PersistentTypesImportStrategy.SkipOrCreate, I do not see any use for that.
I agree.
Tolis?

**Comment by apobekiaris** [comment]
>As for PersistentTypesImportStrategy.SkipOrCreate, I do not see any use for that.
If my excel column got a value that reference an object, why would i want it so skip the assignation if the reference object exist...

#221

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
