### ISSUE TITLE
Model View inheritance problem when using TabbedGroup

### ISSUE THREAD

**Issue by Ezeckiel2517** [eXpandFramework/eXpand#186]
Hi, we are using some business objects that inherits from a common base class.
In our detail views, we have also defined a base detail view and we want our business detail view to inherit from it. We use the MergedDifference with the 'everything' strategy.

The problem is with TabbedGroup. Tabs added in the inherited model view are not displayed.
We are using xpand 18.1.5.5 and web application.

Look at attached project for sample.
BO are MyBaseObject and MyInheritedObject.
Views are MyBaseObject_DetailView and MyInheritedObject_DetailView.
In MyInheritedObject_DetailView, we have added a tab and a property field. The layout preview look fine.
Starting the web application and browsing to the "My Inherited Object", I can see the added field input but not the tab.
[DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/2429677/DXApplication1.zip)

**Comment by Ezeckiel2517** [comment]
Forget to mention that if I right-click on the project and choose "Update Model", the tab got wiped out and is listed in UnusableNodes.xml

**Comment by apobekiaris** [comment]
thnks for the sample I will update you as soon as possible

**Comment by apobekiaris** [comment]
I update the nuggets to latest version as I do not have your version installed, although I do not recall any modification in this feature since then. The behavior was as you described (different design and runtime). However I redesigned the view as the attached screencast (rename zip to mp4) and everything worked fine. Try it and let me know please.
[2018-09-29_11-33-45.zip](https://github.com/eXpandFramework/eXpand/files/2430444/2018-09-29_11-33-45.zip)

**Comment by Ezeckiel2517** [comment]
I agree that I do see the new files tab now but looking at the resulting xml, it didn't work as I expected.

Here is a sample of the definition of view MyInheritedObject_DetailView in the xml
```xml
<TabbedGroup Id="MainTabs">
	<LayoutGroup Id="TagsGroup">
		<LayoutItem Id="Tags" />
	</LayoutGroup>
	<LayoutGroup Id="DescriptionGroup">
		<LayoutGroup Id="SizeableEditors">
			<LayoutItem Id="Oid" />
			<LayoutItem Id="Description" />
		</LayoutGroup>
	</LayoutGroup>
	<LayoutGroup Id="FilesGroup" ShowCaption="True" CaptionLocation="Top" Direction="Vertical" Index="2" Caption="Files" IsNewNode="True">
		<LayoutItem Id="Files" ViewItem="Files" Index="0" IsNewNode="True" />
	</LayoutGroup>
</TabbedGroup>
```
As we see, we need to repeat the whole layout definition of TagsGroup and DescriptionGroup.
The problem is I cannot change the MyBaseObject_DetailView of one of those group without editing back MyInheritedObject_DetailView to reflect the same changes.

What I want to achieve is having 20+ views, all of them inheriting from a single base view while having their own minor changes and allowing me the change the base view at anytime without having to re-edit all my views. I really tought that the [Model view inheritance](http://apobekiaris.blogspot.com/2013/08/model-view-inheritance-in-next.html) will allow me to do that.

**Comment by apobekiaris** [comment]
I understand what you want to achieve but changing the base will generate a totally different `Layout` which is a a special node. For its generation it follows the superposition architecture used from XAF modules. Unfortunately this process is internal in XAF and the view inheritances implementation just using it so I do not see a workaround.

https://github.com/eXpandFramework/eXpand/blob/d21ddb753915eeeca6b5f3a1e99e22ce5a8bb3c9/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/ModelMergedDifferences.cs#L80-L89

**Comment by Ezeckiel2517** [comment]
Hi Apostolis, I finally got some time to comeback at this problem and look at the ModelMergedDIfferences class you point me. First off, I must admit it is done in a very clever way. After alot of debugging, I do find out where the problem is and it is right in the code you highlight above.

The generated layer is not inserted at the proper order.
`master.InsertLayer(master.LayersCount - 1, modelApplicationBase);`

You see, by default, the application have 3 custom layers :
1-The agnostic module
2-The specific module (win or web)
3-The application

So at runtime, the last layer will be the application layer (3). Inserting the generated layer at position master.LayersCount - 1 will make this layer somewhere between the module specific layer and application layer. In fact, it need to be inserted before the module where the merge is defined. In this scenario, it must be before the agnostic module layer.

At design time, when editing the agnostic module, it do works because the last layer is the currently editing module layer and LayersCount - 1 is right before it.

I have done some manual test of changing the inserted index in the debug session and it do fix the problem. Unfortunately, I do not have a code fix to propose. Maybe you can find out better than me a proper way to determine the inserted index.

**Comment by apobekiaris** [comment]
Hi 

can you screenshot me? how about a simplistic sample to repro the case? maybe a screencast? In your sample for e.g here what I see

![image](https://user-images.githubusercontent.com/159464/49266958-e1f88b00-f460-11e8-9b81-777c01176954.png)

the layers looks fine to me.

**Comment by Ezeckiel2517** [comment]
Here is a new test solution, build on devexpress 18.1.6 and expand 18.1.604. It also contains the source code for Xpand.Persistent.Base, Xpand.Utils and Xpand.Xpo, slightly modified to be able to compile on C#5 with VS2015. [DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/2634022/DXApplication1.zip)

It is very simple test scenario. It changed only the detail views. Every layout are changed in the module agnostic layer (the lowest). The other 2 are untouched.
ClassA is a the base class. The key to demonstrate the problem is that you need to make change to the ClassA detail layout.
ClassB inherit from ClassA. Its detail view merge ClassA detail view AND make some changes to it (it add the quantity field).

At design time, ClassB layout look good.
![image](https://user-images.githubusercontent.com/15835320/49299869-c2785700-f48e-11e8-8406-e3905e2120a6.png)

At runtime, ClassB layout is missing the quantity field.
![image](https://user-images.githubusercontent.com/15835320/49299895-d15f0980-f48e-11e8-95ca-efc6e85ae155.png)

At the start of AddDifferenceLayers method, the master has 17 layers.
It is important to note that the model agnostic layer is at index 11.
![image](https://user-images.githubusercontent.com/15835320/49299939-fbb0c700-f48e-11e8-9080-721c563c8e6c.png)

At the end of AddDifferenceLayers method, the master has 21 layers.
The generated layer "ClassB_DetailView_DXApplication1Module" was inserted at index 19.
![image](https://user-images.githubusercontent.com/15835320/49300000-226efd80-f48f-11e8-92b8-5323ad2245f8.png)

ClassB detail view basically say "I want to apply those changes over the ClassA detail view". The changes are defined in the module agnostic layer. That's why the generated layer "ClassB_DetailView_DXApplication1Module" which defined the view as a copy of ClassA detail view must be place before in the hierarchy.

**Comment by apobekiaris** [comment]
you gave me no choice but to fix this immediately, patch coming, let me know how it works.

btw how come you struggle with Vs2015? Vs2017 is mature now, a wonderful environment, and free in its community version.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.23](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=277&view=results) includes commit [Model View inheritance inserts layers into wrong locations #186](https://github.com/eXpandFramework/lab/commit/22642ac14ae85331f66e9c294b52e8275f450acc),[Model View inheritance inserts layers into wrong locations #186](https://github.com/eXpandFramework/lab/commit/c1c3d560dac821f2ccf33d9e21a38953fde597e1) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by Ezeckiel2517** [comment]
Great I'll give it a try on monday.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.24](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=278&view=results) includes commit [Model View inheritance inserts layers into wrong locations #186 #263](https://github.com/eXpandFramework/lab/commit/5d32f2ed9393a06dc9c79677ebb89b5197018419) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.25](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=279&view=results) includes commit [Model View inheritance inserts layers into wrong locations #186 #263](https://github.com/eXpandFramework/lab/commit/82266e809d71cff215909548282cf88402e313be) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by Ezeckiel2517** [comment]
Hi Tolis, sorry for the delay. The changes doesn't work for me. I think the layer is still at an incorrect position as it is inserted just after the module. Just remove the "+1" when inserting the layer and it should be fine.

```C#
void AddDifferenceLayers(ModelNode node, IEnumerable<ModelMergedDifferenceInfo> mergedDifferenceses, List<ModelApplicationBase> modulesDifferences) {
            var master = (ModelApplicationBase)((ModelApplicationBase)node.Application).Master;
            foreach (var mergedDifferenceInfo in mergedDifferenceses) {
                CollectModulesDifferences(modulesDifferences, mergedDifferenceInfo, (s, application, modelMergedDifferenceInfo) => {
                    var modelApplicationBase = CreateInheritanceLayer(node, (ModelApplicationBase)application, modelMergedDifferenceInfo, master);
                    var layerIndex = FindLayerIndex(modelMergedDifferenceInfo, master);
                    master.InsertLayer(layerIndex, modelApplicationBase);
                });
            }
            master.CallMethod("EnsureNodes");
        }
```

**Comment by apobekiaris** [comment]
Hi,

I cannot follow, my patch inserts the differences right after the declaring differences.
![image](https://user-images.githubusercontent.com/159464/49533542-ee00a480-f8c7-11e8-8532-9bb6f10e14fd.png)
and you suggest to insert them before? that does not sound rational to me

**Comment by Ezeckiel2517** [comment]
For what I understand, the generated layer represent the view you merged from so it is the view before you applied the changes in the module layer. Thus it must be inserted right before, not after.

**Comment by apobekiaris** [comment]
>ClassB detail view basically say "I want to apply those changes over the ClassA detail view". The changes are defined in the module agnostic layer. That's why the generated layer "ClassB_DetailView_DXApplication1Module" which defined the view as a copy of ClassA detail view must be place before in the hierarchy.

I prepare a patch again, thnks

**Comment by Ezeckiel2517** [comment]
Works really great now.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.30](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=284&view=results) includes commit [#186 #263 #271 InvalidOperationException when Cache enabled](https://github.com/eXpandFramework/lab/commit/a2f74c8c670666bc7687f6b7edc18af44cba9126) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by Ezeckiel2517** [comment]
Hi Tolis, I've done more advanced testing and I got a problem with the designer this time.
After I configured the view merge in the module agnostics layer, I've added some customization in the module specific layer (ex. changing an editor). Doing so, the designer stop showing the view correctly.

The view in module agnostic (add quantity field and files tab over the merge view)
![image](https://user-images.githubusercontent.com/15835320/49651780-26a29a00-f9fe-11e8-9ba8-f4a05643c555.png)

The view in module specific (missing quantity and files defined in previous layer)
![image](https://user-images.githubusercontent.com/15835320/49651834-4c2fa380-f9fe-11e8-90e8-455bd21ce777.png)

It must have something to do with that part of the code, where it select "master.LayersCount" as the index.
```C#
if (layerIndex == -1)
 {
    if (!InterfaceBuilder.RuntimeMode)
        return master.LayersCount;
    throw new InvalidOperationException($"{modelMergedDifferenceInfo}");
}
```

At runtime the view are showing fine.

**Comment by apobekiaris** [comment]
hmm yes my bad I always forgot that file, myself I rarely use it. I will update the source thanks.

**Comment by apobekiaris** [comment]
Actually the lastlayer is possible to have any Id, for example XpandModelEditor uses a guid instead. That the reason why when `index==-1 and !InterfaceBuilder.RuntimeMode` it should assume the lastlayer. The problem here was a bit near as you will see in the next patch.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.31](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=285&view=results) includes commit [#186 #263 #271 InvalidOperationException when Cache enabled--UPDATE](https://github.com/eXpandFramework/lab/commit/86fd1d9e401ee1f2856b07f720da9fbb3d4a7cff) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by Ezeckiel2517** [comment]
Need to change the method UpdateNode to be able to parse layer id that contains a filename.
```C#
public override void UpdateNode(ModelNode node){
            var values = ((IList<ModelNode>)((ModelApplicationBase)node.Application).Master.GetPropertyValue("Layers"))
                .Select(_ => Regex.Replace(Regex.Replace(_.Id, "(.*assembly ')([^',]*)(.*)", "$2"), "(.*)\\\\([^\\\\]+)\\\\(.*\\.xafml)", "$2"));
            var modelLayers = string.Join(",", values);
            ((IModelApplicationLayers)node.Application).ModelLayers = modelLayers;
            UpdateNodeCore(node);
        }
```

C:\Dev\Temp\DXApplication1\DXApplication1.Module\Model.DesignedDiffs.xafml is transformed to DXApplication1.Module

**Comment by Ezeckiel2517** [comment]
As a side note, every time I opened a xafml file it now open in a modified state.
Probably because this line modify the model.
```C#
((IModelApplicationLayers)node.Application).ModelLayers = modelLayers;
```

**Comment by apobekiaris** [comment]
>Need to change the method UpdateNode to be able to parse layer id that contains a filename.

Thanks for the suggestion but I am not sure why we need this. As I said before the only case that matching might fail, is when the current model is the lastlayer. Furthermore it is hard to match the model id, it might not be always a path or located in path . So if not found it is assumed the last layer. Do you see something wrong with it?

>As a side note, every time I opened a xafml file it now open in a modified state.
Probably because this line modify the model.

In my tests I fail to repro it, always get an unmodified model.

**Comment by Ezeckiel2517** [comment]
[DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/2667845/DXApplication1.zip)
Here I have updated the sample solution to devexpress 18.2.3 and linked againsts expand 18.2.301.34.

I agree with you that the last layer can have any name (it look like a guid) and usually it is the current layer. But as you can see in those screenshot, currently there is still a problem when i open the DXApplication1.module.web model.

Here is the correct designer in DXApplciation1.Module (notice field Quantity and Files tab)
![image](https://user-images.githubusercontent.com/15835320/49805603-81503480-fd23-11e8-9104-994b059c5d45.png)

Here is an incorrect designer in DXApplication1.Module.Web (notice missing fields from previous layer)
![image](https://user-images.githubusercontent.com/15835320/49805713-cecca180-fd23-11e8-8f6d-bbd3845cced9.png)

Here is a look at the layers when I open the file DXApplication1.Module.Web\Model.DesignedDiffs.xafml
![image](https://user-images.githubusercontent.com/15835320/49805842-2f5bde80-fd24-11e8-8746-10cb0787553a.png)
Problem is the generated layers from previous module need to be moved before the layer with Id that is a path. I don't see another way to fix it.

**Comment by apobekiaris** [comment]
since XpandModelEditor does work, I consider you ok for now, I will probably rewrite this class and package it as standalone. I do not find it acceptable to release all framework like this, and this functionality needs clean and tested ideas.

**Comment by apobekiaris** [comment]
Good news, I refactored the functionality and will release a standalone nuget soon.

**Comment by apobekiaris** [comment]
the module is online please see #277

The module is unit tested and in addition I tested against all expand uses and your samples. 

Looking forward your feedback, thnks for the patient.

**Comment by apobekiaris** [comment]
note there is no lookup on model id anymore and the implantation is simple thus robust as you will probably see by your self. If you find any case that might fail I happy to unit test it as well

**Comment by Ezeckiel2517** [comment]
Great will try to look at it tomorrow before I leave to christmas vacation.

**Comment by Ezeckiel2517** [comment]
Right now, I got trouble with the new module.
Here is 2 tests I did so far:

1-Merge ClassB_DetailView with ClassA_DetailView.
Result : Runtime seems ok but the designer part is not showing the ClassA layout. It displayed the layout as if no merge was applied.

2-Cascade merge ClassC_DetailView -> ClassB_DetailView -> ClassA_DetailView
Result : Seems broken. Look like some layers are not generated anymore.

I'll look more into it after vacation, trying to post samples and screenshot.

**Comment by apobekiaris** [comment]
thnks for the help, enjoy your vacation

**Comment by Ezeckiel2517** [comment]
[ModelViewInheritanceTest.zip](https://github.com/eXpandFramework/eXpand/files/2732957/ModelViewInheritanceTest.zip)
Hi Tolis, here is a new solution to test some use case, based on DevExpress v18.2.4. It contains only the ModelViewIneritance module and its depedencies.

For the first use case, I have defined ClassA as a base business object. ClassB inherited from ClassA.
I have defined ClassA detail view as followed.
![image](https://user-images.githubusercontent.com/15835320/50772483-fc8e0300-125b-11e9-8a7c-3491605c088c.png)
Then in ClassB detail view, obviously I want to merge ClassA detail view. Unfortunately at design time, it doesn't display ClassA detail layout but it rather display the default generated layout.
![image](https://user-images.githubusercontent.com/15835320/50772638-7aeaa500-125c-11e9-803a-5285c85f6b79.png)
Looking at ClassB detail view in a higher layer (i.e. ModelViewInheritanceTest.Module.Web), the layout is displayed has expected. Also the runtime displays the desired layout.
![image](https://user-images.githubusercontent.com/15835320/50773004-85f20500-125d-11e9-9e48-77108a7f8e4f.png)

**Comment by apobekiaris** [comment]
thnks for the time but I already refactored further and cover certain special cases, so the bot will notify as soon as I finish working with it. Actually I refactored the tests to cover this case explicitly.

**Comment by apobekiaris** [comment]
[ModelViewIneritance revert base layout strategies and load from resource when design time. #290 #289 #186](https://github.com/eXpandFramework/Packages/commit/525732e3528a483882c9ab788290c24bdb6fbdd1) relates to this task. Please update your nuget packages to version 18.2.400.64 and test if it addresses the problem.
 To access the lab packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.
 If these packages are already integrated with eXpandFramework the bot will notify this issue again as soon as the release is ready.

**Comment by Ezeckiel2517** [comment]
Hi Tolis, I have made some tests on version 1.0.9 of the module. It seems better and basic scenario (described above) works now. Still sometime the designer fails to display the layout according to mergedDiff. I have to close and reopen VS to fix it.

**Comment by apobekiaris** [comment]
Hi,

at least I haven't noticed anything similar but if you can post repro instructions happy to help as always.

p.s.: I prefer to use the XpandModelEditor which is a standalone process and does not suffer from the VS designer

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
