### ISSUE TITLE
Winform - Excel Import Error when clickin in model 

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#189]
Hello,

In Winform when you click on Tools - Edit model and close it again we have a error linked to the excel importer. (please see attachment) 

Can you have a look please ? 

BR
IS
![model](https://user-images.githubusercontent.com/41955268/46264081-5aea6d80-c518-11e8-8fef-1effcf5e3a7c.png)
[Error.txt](https://github.com/eXpandFramework/eXpand/files/2432159/Error.txt)

A

**Comment by apobekiaris** [comment]
`ExcelImporter` uses the ThreadSafeDataLayer as certain features are asynchronous.

**Comment by isatahiri** [comment]
Hello,

Thanks for your answer but i'm not sure of what i should to do in order to avoid this. 

BR
ISA

**Comment by apobekiaris** [comment]
xpo has a `ThreadSafeDataLayer` that needs to be installed in Windows similar to web. For example check the `ExcelImporterTester` solution

https://github.com/eXpandFramework/eXpand/blob/18.1/Demos/Modules/ExcelImporter/ExcelImporterTester.Win/WinApplication.cs#L25

use that line in your WinApplication

**Comment by isatahiri** [comment]
Hi,

By commenting my line and adding the line of code you mentionned it is working : 
 //args.ObjectSpaceProviders.Add(new SecuredObjectSpaceProvider((SecurityStrategyComplex)Security, XPObjectSpaceProvider.GetDataStoreProvider(args.ConnectionString, args.Connection, true), false));
            args.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(XPObjectSpaceProvider.GetDataStoreProvider(args.ConnectionString, args.Connection, true), true));

What is strange is that the SecuredObjectSpaceProvider should be ThreadSafe.

BR
ISA

**Comment by apobekiaris** [comment]
>What is strange is that the SecuredObjectSpaceProvider should be ThreadSafe.

if you use this ctor you can configure it.

```cs
public SecuredObjectSpaceProvider(ISelectDataSecurityProvider selectDataSecurityProvider, IXpoDataStoreProvider dataStoreProvider, ITypesInfo typesInfo, XpoTypeInfoSource xpoTypeInfoSource, Boolean threadSafe)
```

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
