### ISSUE TITLE
Dashboard Upgrade Issue

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#192]
Upgraded from 16.2 to 18.1 and when opening a Dashboard Editor, I get this error.

The 'Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection' data type is not registered within the business model.

**Comment by apobekiaris** [comment]
It looks like the https://github.com/eXpandFramework/eXpand/blob/d21ddb753915eeeca6b5f3a1e99e22ce5a8bb3c9/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs#L101-L120 fails for some reason. I need more details to imagine the why e.g. sample xml. 
Also see #133

**Comment by capricciobob** [comment]
Somehow the XML for the dashboard replaced all my business object types with Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection type. I just edited those back to my objects and I am fine. Not sure what happened there. I think you could close this safely.

<ObjectDataSource ComponentName="dashboardObjectDataSource1">
      <Name>Candidate</Name>
      <DataSource Type="Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection, Xpand.ExpressApp.Dashboard, Version=18.1.6.1, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958" />
    </ObjectDataSource>

**Comment by apobekiaris** [comment]
Thanks for the update. 

>Somehow the XML for the dashboard replaced all my business object types with Xpand.ExpressApp.Dashboard.ParameterLessProxyCollection type

yes there was another upgrade in the past and I guess they would not respect each other. But since you are safe I spare my time.

>I think you could close this safely.

a bot closes tickets after 2 months of inactivity so no need to worry. Unless you do it explicitly for some other reason like you want to cancel them.
