### ISSUE TITLE
ModelDifference - Web Login Creates Desktop Model

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#194]
My web application is creating a ModelDifferenceObject with type Desktop. Can you point me to where that would be done so I can troubleshoot.

**Comment by capricciobob** [comment]
I think I understand why it is creating Desktop, because I am using a browser. Now the problem is if the Model exists for Desktop, when I log in it creates on for the All device type. I end up with two models. Willing to troubleshoot, just need to know where to look. Thanks as always!

**Comment by apobekiaris** [comment]
the module assigns the DeviceCategory on Init by calling the https://github.com/eXpandFramework/eXpand/blob/d21ddb753915eeeca6b5f3a1e99e22ce5a8bb3c9/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/XafApplicationExtensions.cs#L118-L122

to the `GetPlatform` method will returrn wrong results if you have mix platforms in your solution (both win-web). The `DeviceDetector` is a Xaf build-in file and can be overridden.

there is also this code that modifies the `DeviceCategory` https://github.com/eXpandFramework/eXpand/blob/a2afedc839e7e57360e2c315ee6a708bcf636732/Xpand/Xpand.ExpressApp.Modules/ModelDifference/DatabaseUpdate/DeviceCategoryUpdater.cs

**Comment by capricciobob** [comment]
I do have web and win in this solution.  Still haven't figured out where the issue is.

**Comment by apobekiaris** [comment]
what is the value of `application.GetDeviceDategory()`

**Comment by capricciobob** [comment]
GetDeviceCategory is Desktop

If I login with a model already existing for Desktop, it creates a second model for All.

**Comment by apobekiaris** [comment]
yeah that setting is correct, I tried to repro the case but fail so until you can post more details preferably a sample I am not researching further.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
