### ISSUE TITLE
ModelDifference: add platform agnostic model

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#196]
On many occasions I need to duplicate settings between win and web model. Platform agnostic model would be very handy.

**Comment by apobekiaris** [comment]
The module can work with model differences, what does an agnostic model means? 

the MDO object is associated with a `XafApplication` instance (Win or Web) however you may merge the differences as you wish from the UI.

**Comment by emeyke** [comment]
I mean that apart from win model and web model there will be a base model that applies for both (all) platforms.
E.g. I need to populate tooltips for all objects and I do not want to keep win and web in sync, rather do it in a single ModelDifferenceObject.

**Comment by vimarx** [comment]
+1 as DX shared model implementation [https://documentation.devexpress.com/eXpressAppFramework/113698/Task-Based-Help/Application-Model/How-to-Store-the-Application-Model-Differences-in-the-Database](url)

**Comment by apobekiaris** [comment]
see also #234

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
