### ISSUE TITLE
Web: when preventdataloading is enabled select all box does not work

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#199]
When PreventDataLoading options are enabled, DataAccessMode=Client
After full text search is performed, records displayed, if select all box is clicked filtered results are cleared and list view returns to empty state.

**Comment by apobekiaris** [comment]
thnks fix is on the the next nightly see #197

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
