### ISSUE TITLE
Workflow - New Objects Missing Oid

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#201]
I have a ChangedWorkflow setup. For an existing object it works wonderfully, but for a new object, I get an entry in the [ObjectChangedXpoStartWorkflowRequest] table, but the TargetObjectKey is [Guid]'00000000-0000-0000-0000-000000000000'

Because of this, my workflow does not know which object to work on. Is this the intended behavior?

Thanks.

**Comment by apobekiaris** [comment]
did you tried to init the guid?
some thing like 

```cs
BaseObject.OidInitializationMode=OidInitializationMode.AfterConstruction ??

**Comment by capricciobob** [comment]
Yes, OidInitializationMode.AfterConstruction is the setting in my Module constructor.

**Comment by apobekiaris** [comment]
I am not sure whats going on but you can init the field manually 
```cs
youobject.SetMemberValue("oid",Guid.NewGuid())
```

**Comment by capricciobob** [comment]
That worked great. Thanks.
