### ISSUE TITLE
ExcelImporter: Import fields for Reference objects

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#203]
add capability to use this kind of mapping

e.g.
Client

FirstName
LastName
Organization.Name  <- DefaultProperty
Organization.Address

This would require a dropdown ExcelColumnMap.PropertyName
that allows selecting properties of reference objects.

Makes sense?

**Comment by apobekiaris** [comment]
I am sorry I do not make sense, please elab about the Organization properties

**Comment by emeyke** [comment]
Have to think a bit more on this.
Can go to backlog

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
