### ISSUE TITLE
ExcelImporter: problem when reference object is abstract

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#204]
If ExcelColumnMap.PropertyName refers to and abstract type (e.g. Party), then Create option does not work and if the object (e.g. Party) object is not found it should be reported in Failed results.
Currently nothing is reported and objects are naturally not created.

And as a general rules: 
when an object is set UpdateOnly but not found - it needs to be reported in failed results

**Comment by apobekiaris** [comment]
>If ExcelColumnMap.PropertyName refers to and abstract type (e.g. Party), then Create option does not work 

The module prevents importing when abstract type creation is not configured. Additional BO types are added for this and the UI scaled up in the next minor.

**Comment by apobekiaris** [comment]
>when an object is set UpdateOnly but not found - it needs to be reported in failed results

sounds rational to me that if object not found while on `UpdateOnly` strategy nothing will happen. If you wish to get a a fail use `FailNotFound` strategy

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.06](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=149&view=results) includes commit [ExcelImporter does not report failures #204](https://github.com/eXpandFramework/lab/commit/132837ac8559a1603e740bc97ced3ed4384f4a8f),[Option to configure persistent types creation #204](https://github.com/eXpandFramework/lab/commit/94c8a0a2e591db8f573351350d15914ddbd6a1d9) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.17](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=196&view=results) includes commit [ExcelImporter: Option to configure persistent types creation #204 #212](https://github.com/eXpandFramework/lab/commit/c7e8030a48a6a74d0e28968fd708ce3b6b4b5951) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.19](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=221&view=results) includes commit [Option to configure persistent types creation #204 #227](https://github.com/eXpandFramework/lab/commit/61de01fbf0fc737d2481fa6fea4f9afa1f3b0c7a) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=223&view=results) includes commit [ExcelImporter: Option to configure persistent types creation #204 #212 #227](https://github.com/eXpandFramework/lab/commit/361084afa579cb44cc7245d1d1d91dd4c7ecb2d0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by emeyke** [comment]
This is still an issue.
Consider this example when DomainObject1 has a property Party (Organization or Person)

What is needed that I am able to import file like below, where the default property is contained in the abstract class (such as FullName in this example)

Test https://www.dropbox.com/sh/heggkj3gzir4gae/AAC-Qi8PoVCObt4q9sMzDINUa?dl=0

![image](https://user-images.githubusercontent.com/234025/48378956-323ec180-e6db-11e8-8608-3eea9b99ee87.png)

**Comment by apobekiaris** [comment]
from the screenshot I see that the module complains that cannot create the `Party` which is correct as it is an abstract class, did you try to assign a concrete type using the Configure action? I still cannot make much sense from you question again.

**Comment by emeyke** [comment]
The problem with selecting type is that the main reason for having abstract in this scenario is that you do not know what is being imported beforehand and it can be a mixture.
Consider example
Transaction object:
Transaction.Party
Transaction.Date

Importing file:

Date/Party
1.1.2018/Microsoft
1.1.2018/John Doe

Party.FullName is a default property and that is what importer would use to match to the Party object.
Create strategy will not work of course but definitely need an update startegy to be available for such scenarios.

Do I start to make sense? :)

**Comment by apobekiaris** [comment]
nope you do not make sense, sorry try with a sample

**Comment by emeyke** [comment]
Tolis, sample is by the link above and TestData folder contains the import file.

**Comment by apobekiaris** [comment]
I cannot download zip the solution and repost

**Comment by apobekiaris** [comment]
i run your sample created a new import and now i am on the state you screenshot before. 

**THEN I PRESS CONFIGURE** action and a new form popup where I associate a concrete type upon criteria as shown

![image](https://user-images.githubusercontent.com/159464/48470877-5691bf80-e7fb-11e8-96c6-2a8a9d82e09c.png)

then i could import with success. What do I miss as all worked fine for me.

**Comment by emeyke** [comment]
By success you mean you have the DomainObject1 records created?
I am having now success message, saving after that and not actual records created, DomainObject1 remains emprty... Please confirm you see the records showing up.

**Comment by apobekiaris** [comment]
nope i see 2 records as the message said

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
