### ISSUE TITLE
Null reference when opening DashboardView in web

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#206]
related to #183 (view.ObjectTypeInfo is null)

![image](https://user-images.githubusercontent.com/226800/46802965-4c306180-cd35-11e8-93f0-98144a801ffd.png)

**Comment by apobekiaris** [comment]
can you post a sample, in the meant time a solution that is possible to workaround can be found in #193

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
