### ISSUE TITLE
Excel Importer  - "Type d'id Passed « System.String » not compatible with the type « System.Guid »

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#212]
hello,

I do not know what i'm doing wrong but when i try to import some demo tasks, I have a error linked to the GUID of PME_User. (stack also in attachment)

I have a custom user class but what is strange is that i do not set user at all im my model import but only string and dates.
Did i miss something ? 

Please let me know if attachments are not enough.
Many thanks for you help.

In attachment : 
PME_Task ( object that i'm trying to import)
PME_Activity (PME_Task inherit from it)
PME_User --> classed mentionned in stack
+error + prtscrn of the import model.

![2018-10-17 00_20_18-13-planning-taches - pme affaires](https://user-images.githubusercontent.com/41955268/47050965-8620be00-d1a2-11e8-9b9f-eb563a39995c.png)
[Stack.txt](https://github.com/eXpandFramework/eXpand/files/2485148/Stack.txt)
[PME_Task.txt](https://github.com/eXpandFramework/eXpand/files/2485163/PME_Task.txt)
[PME_Activity.txt](https://github.com/eXpandFramework/eXpand/files/2485164/PME_Activity.txt)
[PME_User.txt](https://github.com/eXpandFramework/eXpand/files/2485165/PME_User.txt)

**Comment by apobekiaris** [comment]
Can you post your a sample xls please, also when you report it probably always useful to know the version you are on.

**Comment by isatahiri** [comment]
Hi,
Version 18.1.6.3
Here is the used file. 

Many thanks 
Isa
[13-PLANNING-Task - Copie.xlsx](https://github.com/eXpandFramework/eXpand/files/2485982/13-PLANNING-Task.-.Copie.xlsx)

**Comment by apobekiaris** [comment]
give me some time please at the moment I am scaling the module to support extra configurations. I will update u once I review this case.

**Comment by apobekiaris** [comment]
it is hard to understand what is going on without a proper sample. Please use the latest from https://dev.azure.com/eXpandDevOps/eXpandFramework/_build?definitionId=3 and provide me with a sample solution and database if the problem continues with the new version

**Comment by apobekiaris** [comment]
just click the arrow next to the `Map` action to configure the map. Let me know if you have more problems.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
