### ISSUE TITLE
Error while import data.

### ISSUE THREAD

**Issue by luizhmcarvalho** [eXpandFramework/eXpand#214]
When I import excel files the screen enter in a loop of requests (maybe to update the progressbar) and crash the application without import the records.

**Comment by apobekiaris** [comment]
do you think you can post more details on how to reproduce it? preferably a sample solution+xml data?

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
