### ISSUE TITLE
Email module attachment of nested list

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#215]
Hello,

With the email module is there any way to add attachment ? 
I have a object with a collection of Notes(description + filedata) 

Many thanks for your answer
ISA

**Comment by apobekiaris** [comment]
the module integrates the [logic rule system](http://apobekiaris.blogspot.com/search/label/Logic) with the [RazorEngine](https://github.com/Antaris/RazorEngine/). The integration is done in the [EmailRuleViewController](https://github.com/eXpandFramework/eXpand/blob/a2afedc839e7e57360e2c315ee6a708bcf636732/Xpand/Xpand.ExpressApp.Modules/Email/Logic/EmailRuleViewController.cs). Knowing this one can derive from that controller, override the `CreateEmail` method to get the `MailMessage` and add attachments. if you tried this approach and you still facing problems please describe them.
https://github.com/eXpandFramework/eXpand/blob/a2afedc839e7e57360e2c315ee6a708bcf636732/Xpand/Xpand.ExpressApp.Modules/Email/Logic/EmailRuleViewController.cs#L49-L64

**Comment by isatahiri** [comment]
Hello,

Thanks for the info. I guess in the EmailTester you did the same with the action SendEmail : 
![image](https://user-images.githubusercontent.com/41955268/47320968-59155500-d653-11e8-91ec-b0daa2dddc39.png)
I wanted to have a look as a sample but i cannot find the project of the tester. Can guide where it is please ? 

BR
ISA

**Comment by apobekiaris** [comment]
I am not sure what you ask m, isn't this screenshot from the [EmailTester solution](https://github.com/eXpandFramework/eXpand/tree/18.1/Demos/Modules/Email)

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
