### ISSUE TITLE
Model Option to configure Popup Windows WindowState 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#219]
added `IModelViewPopupWindowState.PopupWindowState`

**Comment by expand** [comment]
ttt

**Comment by expand** [comment]
ttt

**Comment by expand** [comment]
ttt

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.06](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=149&view=results) includes commit [Model option to configure Popup Windows WindowState #219](https://github.com/eXpandFramework/lab/commit/52e46df6dc59fef00bcd2c85bef63cd40cdce267),[Model option to configure Popup Windows WindowState #219](https://github.com/eXpandFramework/lab/commit/bcf3f2888b8ef3d4c3e26513db6cdc01084a9214) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.06](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=149&view=results) includes commit [Model option to configure Popup Windows WindowState #219](https://github.com/eXpandFramework/lab/commit/52e46df6dc59fef00bcd2c85bef63cd40cdce267),[Model option to configure Popup Windows WindowState #219](https://github.com/eXpandFramework/lab/commit/bcf3f2888b8ef3d4c3e26513db6cdc01084a9214) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=223&view=results) includes commit [Model option to configure Popup Windows WindowState #219](https://github.com/eXpandFramework/lab/commit/fc67a1dead367b2c55e60865b827ef0ada5613c7) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
