### ISSUE TITLE
Issues with SequenceGenerator.GenerateSequence( string sequenceName)

### ISSUE THREAD

**Issue by neo-james** [eXpandFramework/eXpand#224]
Trying to use SequenceGenerator as a service using only something like :
`
var newAutoNumber = Xpand.Persistent.Base.General.SequenceGenerator.GenerateSequence("Sequence1");
`

but failed to find any guidance to do so.

So as a result I ended up with editing WebApplication :
`
protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args) {
	args.ObjectSpaceProvider = new SecuredObjectSpaceProvider((SecurityStrategyComplex)Security,  GetDataStoreProvider(args.ConnectionString, args.Connection), 
                    true);

            if (args.ConnectionString == InMemoryDataStoreProvider.ConnectionString)
                args.ObjectSpaceProvider = new XPObjectSpaceProvider(new ConnectionStringDataStoreProvider(args.ConnectionString));
            else {
                args.ObjectSpaceProvider = this.GetEasyTestParameter("RuntimeMember")
                    ? new XpandObjectSpaceProvider(new DataStoreProvider(args.ConnectionString), Security, true)
                    : new XPObjectSpaceProvider(new ConnectionStringDataStoreProvider(args.ConnectionString));
            }
            
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));

        }
`

And in my module 
`
private void InitializeComponent() {
	...
	this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.SystemModule.XpandSystemModule));		    
}
`

and finally in my DC logic 
`
public static void AfterConstruction(ITestObject instance) {
        var newAutoNumber = Xpand.Persistent.Base.General.SequenceGenerator.GenerateSequence("CardRequest");
        instance.Seq = (ulong) newAutoNumber;
}
`

Then the SequenceGenerator yes is working and generate new number on each call and the SequenceObject table is generated in the database

But SequenceGenerator doesn't save the SequenceObject or it's value so the after closing/rerun it start from 0 again

**Comment by neo-james** [comment]
Also Initializeing it in the WebApplication.CreateDefaultObjectSpaceProvider
`
            var sequenceObjectType = typeof(Xpand.Persistent.BaseImpl.SequenceObject);
            SequenceGenerator.Initialize(args.ConnectionString, sequenceObjectType);
`

didn't solve the issue

**Comment by apobekiaris** [comment]
there this easytest with DC support @ https://github.com/eXpandFramework/eXpand/blob/18.1/Demos/Modules/SystemTester/SystemTester.Module/FunctionalTests/SequenceGenerator/SequenceGenerator.ets. It runs on each major build and does not fail at the moment.

since configuration is really important, I need to ask a sample from you to understand what is the problem.

**Comment by neo-james** [comment]
Issue will not appear using mentioned easytest as the issue is SequenceObject not saved to database.

So after restart of the application Sequence will generate from 0 again

**Comment by neo-james** [comment]
here is the sample to test
[Test1001.zip](https://github.com/eXpandFramework/eXpand/files/2499400/Test1001.zip)

**Comment by apobekiaris** [comment]
thnks for the sample I fixed the problem in 18.1.604.0

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.14](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=193&view=results) includes commit [SequenceGenerator fails when is used as a service #224](https://github.com/eXpandFramework/lab/commit/6dcaee44ba8dae55b9d9d38a3b2ad54e1d693763) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
>Also can you kindly advice : What is the minimum configuration/changes required to only use sequence feature

This is a class that can be used as a service, the framework initialize it at a specific point to workaround certain XAF behavior like password masking. Also there was a check that I removed for the SecuredObjectSpaceProvider. Not sure at this point why it was there I suspect it was a middle-tier thing. When release I will revisit this.

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=223&view=results) includes commit [SequenceGenerator fails when is used as a service #224](https://github.com/eXpandFramework/lab/commit/3f6782a920b9b82e31a064e795c9f6bb9de1c21d) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
