### ISSUE TITLE
ASPxLabelPropertyEditor not displaying value with numeric type in edit mode

### ISSUE THREAD

**Issue by Ezeckiel2517** [eXpandFramework/eXpand#225]
I'm trying to use the ASPxLabelPropertyEditor on some int property to have a readonly control.
In edit mode, the value is not displayed, I think for some reason it display the mask. Also, when I set the edit mask of my model to empty, it has no effect.

After some test, I've found a fix when adding those 2 last lines to your editor.
Because DisplayFormat and EditMask are empty for string type, I think it can be applied safely.

```CSharp
protected override WebControl CreateEditModeControlCore()
{
	var textEdit = (ASPxTextBox)base.CreateEditModeControlCore();
	textEdit.ReadOnlyStyle.Border.BorderWidth = 0;
	textEdit.ReadOnly = true;
	textEdit.DisplayFormatString = Model.DisplayFormat;
	textEdit.MaskSettings.Mask = Model.EditMask;
	return textEdit;
}
```

**Comment by apobekiaris** [comment]
thnks for this I include it in the next nightly build.

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.17](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=196&view=results) includes commit [ASPxLabelPropertyEditor not displaying value with numeric type in edit mode #225](https://github.com/eXpandFramework/lab/commit/107bc82b1bdf0d00ae427f681a17d7b0c8839903) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=223&view=results) includes commit [ASPxLabelPropertyEditor not displaying value with numeric type in edit mode #225](https://github.com/eXpandFramework/lab/commit/34a36b802201d51fbb20a4bbcba6e83dbb565619) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by Ezeckiel2517** [comment]
Tested on 18.1.603.21

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
