### ISSUE TITLE
ExcelImport: column map should not be cleared when file is added

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#230]
Often creation of map is laborious process and is supposed to be reused for subsequent uploads.
when it is reused and new file is added the existing map should stay. Ideally it is validated against the file and highlighted if there are problems. Re-mapping should be left for the user by pressing a button.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.200.04](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=237&view=results) includes commit [Validate Excel column Map against the file before import allowing different excel files for the same map #230 #231](https://github.com/eXpandFramework/lab/commit/84baf39c2b323b0802d154331d7be33f7c9b4cce) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
