### ISSUE TITLE
ExcelImporter: failure messages

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#231]
"Sequence contains no elements" - should be something like "no match found"
"Cannot convert colum value to EarthCape.Module.Core.Store" - should use BO caption

**Comment by emeyke** [comment]
Also
"Import failed in X rows out Y" is wrongly giving Y as total number of each failed fields

**Comment by apobekiaris** [comment]
>"Sequence contains no elements" - should be something like "no match found"

need more info about this where it comes from

**Comment by emeyke** [comment]
It is actually this case
https://github.com/eXpandFramework/eXpand/issues/232

**Comment by apobekiaris** [comment]
Installer lab build [18.2.200.04](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=237&view=results) includes commit [Validate Excel column Map against the file before import allowing different excel files for the same map #230 #231](https://github.com/eXpandFramework/lab/commit/84baf39c2b323b0802d154331d7be33f7c9b4cce) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
