### ISSUE TITLE
ExcelImporter: fails when DefaultProperty is calculated

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#232]
Which should work in case of Update strategy for a column
Column mapping in this case should only give UpdateOnly option.

**Comment by emeyke** [comment]
Here is what happens
![image](https://user-images.githubusercontent.com/234025/47575928-e99daf00-d94b-11e8-8a55-19db1650b8c0.png)

**Comment by apobekiaris** [comment]
I make no sense at all try elaborate a bit

**Comment by emeyke** [comment]
Actually just realized that in this case the defaultproperty is not the reason. need to debug the import and come back to this.

**Comment by apobekiaris** [comment]
btw this should also exists on the log

**Comment by apobekiaris** [comment]
Installer lab build [18.2.200.04](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=237&view=results) includes commit [ExcelImporter: fails when DefaultProperty is calculated #232](https://github.com/eXpandFramework/lab/commit/8c6be8df03379af3d538f0a8858b66bc3bf3e427) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
