### ISSUE TITLE
The use of runtime associated collection fails in workflow service

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#234]
Nighlty nugets @ https://xpandnugetserver.azurewebsites.net and nightly installers @ https://dev.azure.com/eXpandDevOps/eXpandFramework/_build?definitionId=3

It might be a good idea to [search the archived forums](http://www.expandframework.com/forum/search.html) before posting.\

Issues are autoclosed after a period of inactivity, If you are the owner consider closing them on resolve.

Hi there

We are using eXpand in a Win application and a workflow service. We have created runtime members using the win application. This works fine. We have created the following AssociatedCollection:

`<RuntimeNonPersistentMember Name="CustomTariffs" CollectionType="Persistent.Custom.CustomType002" AssociatedMember="CustomTransportRegion" 
CreatedAtDesignTime="False" AssociationName="CustomType001-CustomTariffs" IsNewNode="True" />`
The win application can use this member with no problems. 

The workflow service fails to create this runtime member. And it states that the CollectionType and or AssociatedMember are null

We did some research and found that the model that is loaded in the win application differs from the model of the service application. 

The win application loads the given xml as a OneToManyCollection member. The service however loads this xml as a RuntimeNonPersistentMember. So again: The xml is the same but it is loaded differently in memory. 

When the runtime member builder tries to create the member when starting the service, the cast of the modelMemberEx fails to the OneToManyCollection interface.

Can you help us resolve this problem? Can you give us advise to solve this? If you can't do this without a sample project we will try to create one next week.

Thanks,
Jacob

**Comment by apobekiaris** [comment]
Hi Jacob,

If not much trouble amd given the fact that there is a lot of work to support the new GitHub workflow I would appreciate a sample. It will for sure produce a fast response from me.

Thanks for the understanding

**Comment by jacobdeboer33** [comment]
Hi Tolis

I have some trouble to get this to work. I have used the workflow demo, but I think the workflow service doos not load runtime members from the model. When I create a new workflow service project, it creates a new application model. This model stays empty. How can I get this to work to test this? Or what can be the cause of my original question?  Sorry for the additional questions

Thanks,
Jacob

**Comment by apobekiaris** [comment]
still need help? I see you closed the issue

**Comment by jacobdeboer33** [comment]
Hi Tolis

I accedentily closed the issue. But I still need help. I tried to create a sample project, but eXpand doos not seem to support my situation out of the box.

We try to do all the commits that you do on our own code. We do this because we have done some customizations. One of this customizations is that we have modified the modeldiffernece module so that we can specify a fixed application name so that we can run serveral applications on the sampe application model.

We have done this for a workflow service project and a windows project. This project use the same application model.

The problem that we experiencing now is that the windows application can handle runtime collection members and the workflow service can't handle them. I tried restoring code of the modeldifference modules to earlier versions but this did not help. It seems to be related to the Xpand.Persistent.Base or Xpand.Persistent.BaseImpl projects. 

It seems that when the Application.Model property is used for the first time that it is different for the win and service application.

Can you please help me with finding the cause of this? So why doos the win application translate the xml of a modelaspect different from the service application? 

If you can provide me with some tips it would help me alot.

Thanks,
Jacob

**Comment by apobekiaris** [comment]
where u store the model? do u use Modeldifference module? how you create your members

**Comment by jacobdeboer33** [comment]
Hi Tolis

Model is stored in db. I do use the modeldiffernece module. The members are created in the win application in model designer

I tried making a sample project. Attached you will find a project containing your workflow demo. I added a custom collection member on the Issue type. This is a collection of Tasks. The member is called CustomTasks. I alse created a workflow definition that updates every issue with a subject with the value '2' It will update the subject with the count of the customtasks collection of that issue.  (workflow definition is called test5). 
This workflow fails to execute because it cannot find the customTasks collection.

I did not get this to work so that the workflow service loads the runtime members. 

So the difference between our product and this demo is that in our product the service runs in a seperate project (using the xpandworkflowapplication). Our product uses complex strategy and standard authentication. And we modified the modeldiffernece module so that different projects can use the same applicaiton model (using a fixed application name instead of the name of the running executable).

Can you get this attachment to work (the workflow definition test5). Or can you help me with my Original question using the additional info I provided?

P.s. database is included in the zip

Thanks,
Jacob
[WorkflowDemo.zip](https://github.com/eXpandFramework/eXpand/files/2535456/WorkflowDemo.zip)

**Comment by apobekiaris** [comment]
thanks for the sample, I tested and your workflow works fine for me. see my screencast.

https://www.screencast.com/t/WgDt3GXPEsm

**Comment by jacobdeboer33** [comment]
Hi Tolis

It will work in the WF designer. But it won't work using the workflow service. Please watch my attached screencast

Tanks,
Jacob
[Gravar #2.zip](https://github.com/eXpandFramework/eXpand/files/2538171/Gravar.2.zip)

**Comment by apobekiaris** [comment]
it looks lie the `ModelDifferenceModule` gets confused because the model is bound to `WorkflowDemoWindowsFormsApplication`. For now you can force loading by 

1. In you server load `WorkflowDemoWindowsFormsModule` instead of `WorkflowDemoModule` (Program.cs line 98)
1. add the next code to `WinModule.cs`
```cs
        public override void Setup(XafApplication application){
            base.Setup(application: application);
            if (application is XpandServerApplication serverApplication)
                serverApplication.SetupComplete += (sender, args) => {
                    XafTypesInfo.Instance.RegisterEntity(typeof(XPObjectType));
                    using (var objectSpace = application.CreateObjectSpace()){
                        var modelDifferenceObjects = objectSpace.GetObjectsQuery<ModelDifferenceObject>().Where(o => o.DifferenceType == DifferenceType.Model);
                        foreach (var modelDifferenceObject in modelDifferenceObjects){
                            modelDifferenceObject.GetModel((ModelApplicationBase)application.Model);
                        }
                    }
                    application.Modules.OfType<ModelDifferenceBaseModule>().First().LoadModels();
                    

                };
        }
```

**Comment by apobekiaris** [comment]
this is a temp solution and it wont be reuired from the next minor. The module will guide you by throwing exceptions.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.200.08](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=242&view=results) includes commit [ModelDifferenceModule: preconfigure loading models list on server scenarios #234](https://github.com/eXpandFramework/lab/commit/07124ac210ee8d87c6e038584068d0c3b891057b),[ModelDifferenceModule: preconfigure loading models list on server scenarios #234](https://github.com/eXpandFramework/lab/commit/ca7e0bdfdefdbfcc6af2d896b42aa0d7b9b383b5) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by jacobdeboer33** [comment]
Hi Tolis

The WorkflowDemo works with your changes. My own project however doos not. I realise that I need to research this further by myself.

Thanks for your time and effort.
Jacob

**Comment by apobekiaris** [comment]
I suggest u have the symbols loaded and check why the MDO module does not load the differences.

**Comment by apobekiaris** [comment]
feel free to ask if you have concrete questions

**Comment by jacobdeboer33** [comment]
Hi Tolis

The workflow service in our product loads the differences fine, but only runtime associated collections are interpretated differently in the service application. This results in an exception (see Original post) when starting the service. Other runtime members are working fine.

What can be the cause of this?

Thanks,
Jacob

**Comment by apobekiaris** [comment]
I do not make sense, in my tests I found that the service did not load the model at all because the model is bound to the WinApplication and not the server application. I posted a workaround already can you verify that your model is loaded from the service?
 is this line called for the model you define the members?

```cs
modelDifferenceObject.GetModel((ModelApplicationBase)application.Model);
```

**Comment by apobekiaris** [comment]
> The service application puts it in a RuntimeNonPersistentMember object

you can enable symbols and step into 

https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.Persistent/Xpand.Persistent.Base/RuntimeMembers/RuntimeMemberBuilder.cs#L35-L36

**Comment by jacobdeboer33** [comment]
Hi Tolis

When I run the Win application my code gets in the if on line 176. When I run the service the code doos not get in this if. I gets to end of this function and crashes on line 188 in the CreateCustomMembers function, because some parameters are empty.

I think this is caused by the fact that the service application puts my runtime collection members in other objects when it translates the xml. The service puts them in RuntimeNonPersistentMember objects and the win application puts them in OneToManyCollection objects. 

I'm looking for the cause of this. Why is the service putting the xml in onther objects?

Thanks,
Jacob

**Comment by apobekiaris** [comment]
I cannot understand from the info you posted however you mentioned

> We are using eXpand in a Win application and a workflow service. We have created runtime members using the win application. This works fine. We have created the following AssociatedCollection:
> 
> `<RuntimeNonPersistentMember Name="CustomTariffs" CollectionType="Persistent.Custom.CustomType002" AssociatedMember="CustomTransportRegion" CreatedAtDesignTime="False" AssociationName="CustomType001-CustomTariffs" IsNewNode="True" />`

which does not look good to me, have a look how an associated collection should look like.

https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Demos/Modules/SystemTester/SystemTester.Module/FunctionalTests/RunTimeMembers/RunTimeMembers.xafml#L15

**Comment by jacobdeboer33** [comment]
Hi Tolis

The Xml you posted is not looking the same like the xml that is generated by the sample project. So I think the problem is somewhere else. I will look into this further

Thanks,
Jacob

**Comment by jacobdeboer33** [comment]
Hi Tolis

I solved the problem adding 
`if (typeof(IModelMember).IsAssignableFrom(parameters.NodeType))
            {
                if (parameters.Values.ContainsKey("AssociatedMember"))
                    parameters.NodeType = typeof(IModelMemberOneToManyCollection);
            }`

to the ConvertXml method in XpandModuleBase. 

Do you know why this is working for you without this code in there and why it is not working for me?

Thanks,
Jacob

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
