### ISSUE TITLE
SequenceGenerator Error 

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#235]
Hi,

after Update to 18.1.604 I got an Error on starting.

27.10.18 17:07:42.023	================================================================================
27.10.18 17:07:42.026	Trace Log for iXISXRM.Win.exe is started
27.10.18 17:07:42.026	================================================================================
iXISXRM.Win.exe Error: 0 : 27.10.18 17:07:52.566	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei Xpand.Persistent.Base.General.SequenceGeneratorHelper.<Attach>b__11_0(Object sender, EventArgs args)
   bei Xpand.Persistent.Base.General.ConnectionStringHelper.OnConnectionStringUpdated()
   bei Xpand.Persistent.Base.General.ConnectionStringHelper.ConnnectionStringActions(Object sender, ObjectSpaceCreatedEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei DevExpress.ExpressApp.XafApplication.OnObjectSpaceCreated(IObjectSpace objectSpace)
   bei DevExpress.ExpressApp.XafApplication.CreateObjectSpace(Type objectType)
   bei DevExpress.ExpressApp.ModelDifferenceDbStore.Load(ModelApplicationBase model)
	InnerException is null

**Comment by CWolffIF** [comment]
Hi Tolis,

I debugged the framework. In the Project the Model and the Modeldifferences are stored in the Database. It seemed that they are not loaded. The Codeline 466 is executed in the Loadprocess (ModelDifferenceDbStore.Load(ModelApplicationBase model)), so that the Application Object is there but Application.Model is null.
The same happend in the DatabaseUpdater.

**Comment by apobekiaris** [comment]
hmmm what I wanted to know is the why the Application.Model is null, the only reason I guess is because you call it too early. Do you create any objectspace before `application.SetupComplete` event? that could cause the event to raise before  the Model was initialized. Is this a normal start of the app or you load a model?

**Comment by CWolffIF** [comment]
Hi Tolis,
I stepped through program. No, there is no objectspace created.
- Setup of the Modules: OK
- Compatibility checked: OK

It seemed that the problem occurs during the loading of the model (it seems that in ModelDifferenceDbStore.Load is an objectSpace created to load the model).
Callingstack:
- Xpand.Persistent.Base.General.SequenceGeneratorHelper.<Attach>b__11_0(Object sender, EventArgs args)
- Xpand.Persistent.Base.General.ConnectionStringHelper.OnConnectionStringUpdated()
- Xpand.Persistent.Base.General.ConnectionStringHelper.ConnnectionStringActions(Object sender, ObjectSpaceCreatedEventArgs e)
- System.EventHandler`1.Invoke(Object sender, TEventArgs e)
- DevExpress.ExpressApp.XafApplication.OnObjectSpaceCreated(IObjectSpace objectSpace)
- DevExpress.ExpressApp.XafApplication.CreateObjectSpace(Type objectType)
- DevExpress.ExpressApp.ModelDifferenceDbStore.Load(ModelApplicationBase model)
- DevExpress.ExpressApp.ApplicationModelManager.CreateLayerByStore(String id, ModelStoreBase store)
- DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
- DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes)
- DevExpress.ExpressApp.Win.WinApplication.CreateModelManager(IEnumerable`1 boModelTypes)

**Comment by apobekiaris** [comment]
put a breakpoint at 
https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/SequenceGenerator.cs#L466

is `_xpandModuleBase.Application` also null?

**Comment by apobekiaris** [comment]
bad suggestion sorry

**Comment by CWolffIF** [comment]
Hi Tolis,

thanks for your help. I hope I could help also. It was my first time to debug the framework. Straight learning curve ;-).

**Comment by apobekiaris** [comment]
Installer lab build [18.2.200.05](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=238&view=results) includes commit [SequenceGenerator initialization model flag is not possible, moved to tthe app.config #235](https://github.com/eXpandFramework/lab/commit/f85cc4cb90f0424aaebf9357db5dbec971fe3ecd) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
