### ISSUE TITLE
Dashboard problem in 18.1.7 and Xpand

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#237]
Hi, after converting to 18.1.7 I'm having the following problem with nested date fields in xpand
similar to
"The object of type "DevExpress.DataProcessing.InMemoryDataProcessor.DataVector`1[System.Object]" cannot be converted to type "DevExpress.DataProcessing.InMemoryDataProcessor.DataVector`1[System.DateTime]"."

[https://www.devexpress.com/Support/Center/Question/Details/T675017/devexpress-dataprocessing-inmemorydataprocessor-datavector-1-system-object-todevexpress](url)

Test case
[Solution4.zip](https://github.com/eXpandFramework/eXpand/files/2543827/Solution4.zip)

simple Repro video
[2018-11-02_16-08-45.zip](https://github.com/eXpandFramework/eXpand/files/2543821/2018-11-02_16-08-45.zip)

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="es-AR">
  <Title Text="Tablero de control" />
  <DataSources>
    <ObjectDataSource Name="PersistentClasses1" ComponentName="PersistentClasses1">
      <DataSource Type="Solution4.Module.PersistentClasses1, Solution4.Module, Version=1.0.6880.28834, Culture=neutral, PublicKeyToken=null" />
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Cubo 1" DataSource="PersistentClasses1">
      <DataItems>
        <Dimension DataMember="Obj2.Fecha" DefaultId="DataItem0" />
        <Measure DataMember="saldo" DefaultId="DataItem1" />
        <Measure DataMember="Oid" DefaultId="DataItem2" />
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem0" />
      </Columns>
      <Values>
        <Value DefaultId="DataItem1" />
        <Value DefaultId="DataItem2" />
      </Values>
    </Pivot>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutItem DashboardItem="pivotDashboardItem1" />
    </LayoutGroup>
  </LayoutTree>
</Dashboard>
```

**Comment by apobekiaris** [comment]
I tested against 18.2.2 but fail to repro it. Did you tried 18.2.2 is there something I missed?

![image](https://user-images.githubusercontent.com/159464/47949308-61ba3500-df49-11e8-9fd6-82383eeb087f.png)

**Comment by vimarx** [comment]
Hi Tolis, do you tried with some non-null values? because some summaries  seem to be empty

**Comment by vimarx** [comment]
for me 18.2 is not an option now

**Comment by apobekiaris** [comment]
even with data no errors
![image](https://user-images.githubusercontent.com/159464/47953160-3d2e7f00-df82-11e8-901b-754139bb1d4b.png)

(https://dev.azure.com/eXpandDevOps/eXpandFramework/_build?definitionId=11)
>for me 18.2 is not an option now

I am sorry but I do not plan a 18.1.7 build as we already branched and there is no support at the moment for multiple branches. But first we need to repro the error so can u try to repro with the latest [nightly build](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build?definitionId=11)

**Comment by vimarx** [comment]
this leads to other issues, using the same solution,

1) null reference opening nested property AFTER dropping a cube into the designer (see video)
[2018-11-03_16-46-22.zip](https://github.com/eXpandFramework/eXpand/files/2545293/2018-11-03_16-46-22.zip)

2) another issue, cannot see data in the designer when editing
[2018-11-03_16-49-17.zip](https://github.com/eXpandFramework/eXpand/files/2545295/2018-11-03_16-49-17.zip)
parameters=always or design

**Comment by apobekiaris** [comment]
Installer lab build [18.2.201.03](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=246&view=results) includes commit [Cannot open nested property after dropping a cube into the designer #237](https://github.com/eXpandFramework/lab/commit/840596fa8e4c51b37638d23b28dc70bd83f67ebe) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by vimarx** [comment]
it is working ok
