### ISSUE TITLE
SecurityTesterWin: ChooseDatabaseAtLogon permissions

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#238]
![image](https://user-images.githubusercontent.com/234025/47951384-a1444980-df68-11e8-8743-473d2b55fbbd.png)

**Comment by apobekiaris** [comment]
try to be more descriptive, this post says nothing

**Comment by emeyke** [comment]
Apologies, I run Security tester with latest release and ChooseDatabaseAtLogon enabled.

**Comment by apobekiaris** [comment]
try this fix until next minor 

```cs
        public override void Setup(XafApplication application) {
            base.Setup(application);
            application.SetupComplete += (sender, args) => {
                ((SecurityStrategy) application.Security).AnonymousAllowedTypes.Add(typeof(StringObject));
            };
        }

```

**Comment by emeyke** [comment]
Thanks, this works.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.201.03](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=246&view=results) includes commit [ChooseDatabaseAtLogon lists DBServers as protected. #238](https://github.com/eXpandFramework/lab/commit/1deaab0466963a4396165b6aee35e04e70cea2c8) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by emeyke** [comment]
18.2.201.8 fixes it
