### ISSUE TITLE
Allow XtraDashboard module together with XAF native dashboard module.

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#239]

**Comment by apobekiaris** [comment]
Installer lab build [18.2.201.03](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=246&view=results) includes commit [Allow XtraDashboard module together with XAF native dashboard module. #239](https://github.com/eXpandFramework/lab/commit/c279dee3a6c0baffa228e377fa5b14b0c27605c0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by emeyke** [comment]
Still cannot open dx dashboard with latest nightly Exception thrown: 'System.InvalidCastException' in Xpand.ExpressApp.Dashboard.dll

07.11.18 12:58:53.559		Type: DevExpress.ExpressApp.Actions.SimpleAction
								ID: ListViewShowObject
								Category: ListView
								Controller.Name: DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController
								Context.Name: Dashboard
								Context.IsRoot: True
								Context.SelectedObjects.Count: 1
								Context.CurrentObject: Dashboard

07.11.18 12:58:53.565		CurrentObject: Dashboard
07.11.18 12:58:53.572		WinApplication.CreateWindowCore.activateControllersImmediatelly: True
07.11.18 12:58:53.579		Window.activateControllersImmediately: True
07.11.18 12:58:53.581		WinWindow.activateControllersImmediately: True
07.11.18 12:58:53.591	Frame.set_Template: old value - null, new value - DevExpress.ExpressApp.Win.Templates.Ribbon.DetailRibbonFormV2
Exception thrown: 'System.InvalidCastException' in Xpand.ExpressApp.Dashboard.dll
Exception thrown: 'System.InvalidOperationException' in DevExpress.ExpressApp.v18.2.dll
Exception thrown: 'System.InvalidOperationException' in DevExpress.ExpressApp.Win.v18.2.dll
Exception thrown: 'DevExpress.ExpressApp.Actions.ActionExecutionException' in DevExpress.ExpressApp.v18.2.dll

**Comment by apobekiaris** [comment]
this stack trace does not help

**Comment by apobekiaris** [comment]
try a bit more descriptive on how to repro the case in a new posst

**Comment by expand** [comment]
although I do not see how to repro it I can see a possible patch, let me
know if it worked.

**Comment by emeyke** [comment]
there is for some reason dashboarddefinition_detailview that got assigned to dashboarddata_listview
not sure what happened, now i can get it to open but still get same error when running dashboard designer for it.

will try the patch

**Comment by emeyke** [comment]
Didnt help.
Tryed to repro on a new project. Not quite but at least the DX dashboard does not open there.
https://www.dropbox.com/s/mh3hwyzf5f3w4uf/XpandTester%20%282%29.zip?dl=0

Steps:
Create DX Dashboard
Try to open.

**Comment by apobekiaris** [comment]
download fails with the message still uploading

**Comment by emeyke** [comment]
there now

**Comment by emeyke** [comment]
Works now

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
