### ISSUE TITLE
Documentation on how to run demos

### ISSUE THREAD

**Issue by sheldmandu** [eXpandFramework/eXpand#240]
There doesn't seem to be any documentation available on how to get the demos up and running.  Would be good to have some basic documentation.

**Comment by apobekiaris** [comment]
all demos/modules project are containers for the eaytest and not to be run as standalone. It is rather easy to read the easytest to understand what is it about. For the rest the framework does the extra effort to _model it self_ as outlined in the https://github.com/eXpandFramework/eXpand/wiki/Getting-Started. I do not add functionality to the main demos, they do have easytests however and use all framework modules, so they are indicator of its state.

having say this, I of course agreed with you that I would prefer detailed docs, so as I already told you in your other post this is an OS project and contributions are welcome.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
