### ISSUE TITLE
Documentation on JobScheduler Module and Quartz

### ISSUE THREAD

**Issue by sheldmandu** [eXpandFramework/eXpand#241]
There doesn't seem to be much documentation of how to get the Quartz JobScheduler module up and running and it's really needed for anyone trying to get it going.  Using Quartz for Job Scheduling is definitely a good approach and better than writing custom activities for workflows, but it's extremely hard to get it working.

I attempted to run the Xpand.Quartz.Server.exe to start the Quartz Server after using the sql script to create the Quartz database, but keeping getting No conneciotn clould be made because the target machine active refused it 127.0.0.1:555.

It doesn't really make any sense to me why running the server would actually result in an attempt to connect to the server, so I'm rather lost, but because there's a severe lack of documentation I have no idea where to even look.

When I tried launching JobsSchedulerTester.Win.exe I just get "One or more errors occurred" when the application attempts to start.

**Comment by sheldmandu** [comment]
Hi Tolis, thanks for the reply.  I have looked at doing it the way you suggested but found that you end up missing a fair bit of higher end scheduling functionality that is already available out of the box in Quartz and you end up more or less re-inventing the wheel to a high degree.  You're definitely right in that it requires needing to learn Quartz but it does give you an enterprise level job scheduler.  To be honest job scheduling is the one thing that is really lacking in XAF that one would think every application needs at some stage.  I'll have a look at the tester and use the EasyTest configuration as that's probably what I was doing wrong.

**Comment by sheldmandu** [comment]
Hi Tolis, I tried getting EasyTest working, but when you try to start the Win app without the server already running it seems to just die because it can't connect to the remote quartz server.

**Comment by apobekiaris** [comment]
it means that the module is not designed to work without the server running.

**Comment by apobekiaris** [comment]
sounds a better idea also you can model persistent objects on the Quartz db and go persistent if u like.

**Comment by sheldmandu** [comment]
Hi @apobekiaris I had a bit more of a play with the Quartz JobScheduler implementation in Expand and done a lot more research into job scheduling options in .NET in general, especially taking your comments with regard to Quartz complexity onboard.

With regard to the current implementation of the JobScheduler in eXpand I did come across a few things that felt like bugs (e.g. I somehow ended up the trigger created twice in Quartz after making updates to the trigger schedule in the application or not being able to run the application if the quartz server is not running) and some lack of functionality due to lack of functionality in Quartz rather than something done in Expand (e.g. lack of execution logs, etc). 

The most striking thing however (like you said earlier) is the sheer complexity of quartz in terms of it's design and relationship between objects and personally I suspect this complexity and a lack of documentation to a certain degree is indeed the reason for the lack of adoption of this particular solution.

That said, I do honestly believe that any serious LoB application needs a decent job scheduler with ability to easily schedule one-off as well as recurring jobs and becomes a must once the application gets to a certain level / complexity.

With that in mind I started looking around options and considered your comment of "just make a loop" (i.e. keep it simple) but didn't think I really needed to reinvent the wheel.

After some research I found that although there's quite a considerable number of "cron" type .net solutions floating around, there are really only two that stand above the rest (as reflected by documentation, community and ultimately number of nuget installs).  The first is quartz-scheduler.net which you already used and we know the shortcomings of.  The second is Hangfire.io.  On going through the hangfire documentation (which is far better and more comprehensive than Quartz.net) it seems like a much simpler and easier solution to use without resorting to rolling your own, which doesn't make sense to me.  It also already has things like execution logging and retention built in (which is pretty important to keep track of what's actually been run).  Another benefit is rather than using remoting all communication between the clients and servers is done through the database and DB schema is actually really well designed so would be dead easy to create an XPO persistent layer over if need be also.

I don't know if you've previously looked at hangfire but might be worth a look if you want/need job scheduling in the application and quartz is too complex and an overkill.  There's obviously some things to solve (e.g. getting an Application instance inside the job), but I'm sure they're not too hard to work out.

So using Hangfire.io for job scheduling in our XAF application is the route I'm going to go and explore further as it seems like the better simpler option.

Hope this helps someone else looking to implement a job scheduler in XAF.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by bertstomphorst** [comment]
@sheldmandu thank you for your post! I'm looking for a nice solution to profide jobscheduling from our XAF application. How's your current experience with hangfire?

**Comment by isatahiri** [comment]
@sheldmandu Also looking for alternative to the stadanrd Microsoft solution. Any progress on that ? Can we participate/help somehow ?

**Comment by sheldmandu** [comment]
@isatahiri @bertstomphorst I've implemented Hangfire and it's working fantastic. I went to the trouble of implementing the full monitoring API within XAF also so it's completed managed within XAF including all dashboards and the works.  I used NonPersistent objects hydrated using the Hangire Monitoring API (plus storage API). I basically looked at what was done in the Hangfire Dashboard and how it worked and replicated in my service that's responsible for calling the hangfire APIs and returning NonPersistent DCs.

Here are some screenshots:
https://i.imgur.com/vqlwdo9.png
https://i.imgur.com/lHztDJQ.png
https://i.imgur.com/QCXHgTk.png

I'm also going to implement functionality from the Hangire Console so can provide more detailed logging of the state.

If you don't want to do all the monitoring in XAF it would be MUCH easier to implement as then it's pretty straight forward.

The main thing you need to do is create a separate project for your server application (which has combination of Web and Win modules) which can then be used by the JobServer and WorkflowServer alike.  They key there is to use XPObjectSpace instead of SecuredObjectSpace and make sure you pass the ThreadSafe flag to it.  Otherwise you'll end up with threading exceptions as the Security System in XAF cannot be used in a thread-safe manner from multiple threads even if you pass in the threadSafe flag as true to the SecuredObjectSpaceProvider at construction.

Iv'e also implemented it so that my Win application can also be a hangfire server (by instantiating the ServerApplication instance and starting a BackgroundJobServer.  Your ServerApplication needs to inherit XafApplication rather than the WinForms application so you don't get popups that won't go away.  I've done it so it's controlled in the config file whether the client acts as a JobServer.

In terms of both the JobServer and WorkflowServer I have them implemented using Topshelf.

**Comment by apobekiaris** [comment]
at least the UI looks great! It would be interested to see more details, perhaps some job code you could share? We could probably implement something similar. I like how abstract Hangfire is. My guess is that you just run your code under a hangfire context that does the notifications. So you subsbribe to them and fill your views?

**Comment by sheldmandu** [comment]
Hi @apobekiaris Sure, I'm happy to share all the code and xafml with you so you can make it into a separate standalone module as decent job scheduling is very much needed in XAF and hopefully will help with uptake of eXpand. Probably best we start a separate "feature" issue for it.

In terms of the job code it's literally just a normal method that takes simple arguments (i.e. int, string, array[int], etc) and you can do what you like in there.  It's much simpler than Quartz and much easier to get your head around.  They key is the method needs to be in a class that has a reference to XafApplication (usually passed into the constructor) so that you can create ObjectSpaces and do everything you need in the method.  Then an IoC Container is used by Hangfire to instantiate that class and pass in the XafApplication into it.

Hangfire just runs this code in it's own threads.

That's as far as the jobs themselves go.

In terms of the views for monitoring which essentially just replicate the functionality in the OWIN based Hangfire Dashboard, all I'm doing is calling the Hangfire MonitoringApi to get the objects and then populating my own Non-Persistent Objects.  This was needed due to how hangfire monitoring API returns objects vs how XAF expects them (i.e. ID in the object itself and not a key in a collection of objects).

I essentially have a HangfireMonitoringService that is responsible for talking to Hangfire MonitoringApi (and some StorageApi as that's how it's done in the Hangfire Dashboard also) and returning the non-persistent XAF ready objects.

Then there's a few controllers, some for the the non persistent object space (that essentially call the HangfireMonitoringService), some handle pagination that's built into the Hangfire Monitoring API and then a couple for BackgroundJob Actions and RecurringJob Actions respectively.

The main beauty about Hangfire is that it's considerably simpler than Quartz.  There's no jobs, triggers, data maps, calendars, etc.  You just pass your method into the BackgroundJob. The architecture is also much easier to work with in that clients store jobs to the storage and servers retrieve them and process them.  So you don't have all the issues of clients needing to communicate to some server using remoting and it also enables you to have every win client as a job server also.

**Comment by apobekiaris** [comment]
valuable info thanks I however thinking of a more standalone way losing the HangFire/XafApplication weight. I am not so sure that you really need the XAF application or typeinfo in a job or even the objectspace. What type of jobs require all application context in place? Should the jobs be more standalone? and even if you do need a module or two in a job shouldn't be easier to create them where you use them instead of supporting and be constraint from a global XAF application context?

**Comment by sheldmandu** [comment]
@apobekiaris Not quite sure what you mean by "my rstandalone way losing the HangFire/XafApplication weight".

Jobs will ultimately do whatever you need them to do, but in most cases you WILL work with data and hence will need to create at least one ObjectSpace (in the thread the job is running in).  For MOST jobs there is no avoiding working with the ObjectSpace as you need to work with data.

I guess I found it easiest to pass in the Application and in the Job itself decide what object spaces need to be created, etc.

Here's an example of what we're using Hangfire for in our application to give you an idea of why it's needed.

- Datafeed imports - Needs ObjectSpace to read definitions and to create/update objects
- Datafeed exports - Needs ObjectSpace to read the Datafeed definition and to access the data to be exported
- Rule-based Product Pricing - Needs ObjectSpace to read rule definitions and access and modify Product prices
- Automated Emails
- Web Integration
- etc

Essentially you ALWAYS need the ObjectSpace AND the ObjectSpace needs to be created in the thread the job is running in as otherwise you'll get threading exceptions as ObjectSpaces cannot be shared between threads.

**Comment by isatahiri** [comment]
Hello,

I'm not sure of what is going on regarding this case. So should we expect Workflow module with HangFire/XafApplication ? 

BR
ISA

**Comment by sheldmandu** [comment]
@isatahiri Workflow module doesn't need Hangfire.  You can easily create one with Topshelf. It's a bit hard to make it generic because you need to create an XafApplication with XPObjectSpaceProvider and based directly on XafApplication rather than on an WinFormsApplication.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by apobekiaris** [comment]
sorry for hijacking this post I try to get in contact with @bertstomphorst about #757 a gitter room invitation was sent and we wait for your respond. If you change your mind please let us know, if you still interested please join the 
https://gitter.im/xpandframework/cron-jobs

**Comment by bertstomphorst** [comment]
> sorry for hijacking this post I try to get in contact with @bertstomphorst about #757 a gitter room invitation was sent and we wait for your respond. If you change your mind please let us know, if you still interested please join the
> https://gitter.im/xpandframework/cron-jobs

Hi @apobekiaris, I've just sent you an e-mail.
