### ISSUE TITLE
WorldCreator With ThreadSafeLayer

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#244]
Hello Tolis,
When I open "XXX_Listview" two different browsers i get this error;
Exception occurring while assigning the 'XpandListView, ID: ArizaKayitFormu_ListView' view to XpandWebWindow:
Cross-thread operation detected. 'DevExpress.Xpo.UnitOfWork (1720)' is not a thread-safe object, please avoid using different threads at the same time

I tried to use ThreadSafeLayer but i cant. What Should I do ?

private static IDataLayer GetDataLayer() {
   XpoDefault.Session = null;
   string conn = ConfigurationManager.ConnectionStrings["ConnectionStringName"].ConnectionString;
   conn = XpoDefault.GetConnectionPoolString(conn);
   XPDictionary dict = new ReflectionDictionary();
   IDataStore store = XpoDefault.GetConnectionProvider(conn, AutoCreateOption.SchemaAlreadyExists);
    dict.GetDataStoreSchema(System.Reflection.Assembly.GetExecutingAssembly());
   IDataLayer dl = new ThreadSafeDataLayer(dict, store);
   return dl;
}

**Comment by skybluex3** [comment]
Hi, I attached my database configurations.
[DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/2557215/DXApplication1.zip)
I have two database , one of them standart XPO db, another one for WorldCreator Connection DB.

I defined 1 class on PersistentAssemblyInfo and i added it navigation. When i click that listview on multiple computers i get 

> "use DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true
> 
> or Devexpress.Xpo.UnitOfWork(5104) cross thread detected, please dont use threads bla bla"

**Comment by apobekiaris** [comment]
i am still confused, you send me a Win Project which you does not pass `true` for the `threadsafe` argument and you run the project on different computers? resulting in a cross-thread exception?

**Comment by apobekiaris** [comment]
It is possible to use use the ThreadSafeDatalyer in both platforms. All Tester solutions already use it for the web. ExcelImporter module for example uses it for bot win,web. 

Your post and sample does not help this case. A cross thread exception cannot spawn outside a process. Unless you provide clear instructions of your problem together with a working demo where it can be reproduced I cannot help you more.

**Comment by skybluex3** [comment]
Im using all of them devexpress-xpand modules including WorldCreator excelimporter and others. So i shouldn't use excelimporter and like that modules ?

**Comment by apobekiaris** [comment]
it does not relate to which module you use. This exception should not be raised from the framework. If it is raised, provide me exact steps to reproduce and not like before.

**Comment by skybluex3** [comment]
i catched it.
i tried this scenario;
-logged in different machines with different network on Web Application.
-I opened same listview on same time and i got
Reentrancy or cross thread operation detected. Use ThreadSafeDataLayer or find the cause of the cross thread access to the SimpleDataLayer instance from your code. To suppress this exception, set DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
