### ISSUE TITLE
High Memory usage in WinForm

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#247]
Hi, my XAf-XPand app is using 600 Mb after login (with no listview showed) and using it is easy to hit an out-of-memory exception when opening several tabs & listview 
 & reports (I'm using x86 model because of performance issues).
This issue was not noticeable some time ago (may be a year?)

After digging some time, I found this

![image](https://user-images.githubusercontent.com/226800/48377891-d578e200-e6ad-11e8-9296-324b2631e855.png)
 
[SystemTester.zip](https://github.com/eXpandFramework/eXpand/files/2573835/SystemTester.zip)
Is the RichEdit model node/Modeladaptor using a lot of memory ??

I attached SystemTester populated with a lot of BOs (just for testing model memory consumption)

Thanks

Gustavo

**Comment by apobekiaris** [comment]
from your tests it looks like it does but it you can always disable the controller if you like.

```cs
XpandModuleBase.DisableControllers(typeof(RichEditModelAdapterController));
```

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
