### ISSUE TITLE
no release for 17.1.13

### ISSUE THREAD

**Issue by faludigabor** [eXpandFramework/eXpand#252]
Hi,

How do I generate a build for **17.1.13** ? There is no such release ,please .

tx,
gabor

**Comment by apobekiaris** [comment]
Hi,

For XAF builds released while a larger version is out unfortunately you have to use the scripts in the root folder. I suggest you 

1. download https://github.com/eXpandFramework/eXpand/releases/tag/17.1.7.8 
2. Run project converter 17.1.13
1. Extract sources, modify defines.bat and run buildallcmd.bat

if u have issues feel free to post back here

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
