### ISSUE TITLE
ExcelImporter: Comlum mapping does not reset when opening different ExcelImport objects

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#253]
per subject

**Comment by emeyke** [comment]
Create new ExcelImport, add file 1, open column map
Create new ExcelImport, add file 2, open column map - map contains both files fields

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.08](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=262&view=results) includes commit [ExcelImport ColumnMap view displayes all records #253](https://github.com/eXpandFramework/lab/commit/aaa2c6d234ee3e25eb25d76b1df9b8d5d5152c8d) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
