### ISSUE TITLE
SequenceGenerator get no new number

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#254]
Hi Tolis,

in 18.2.300 the SequenceGenerator gives no new number. Stepping through the code, it seems that the Generator do not initialize correct. The "_defaultDataLayer" is null.

**Comment by apobekiaris** [comment]
the SequenceGenerator auto initialize only for (MSSQL,MYSQL,Oracle) rpoviders and while `ConfigurationManager.AppSettings["DisableSequenceGenerator"]!=true`, if does not auto initialize for those cases please provide a sample.

**Comment by CWolffIF** [comment]
Hi Tolis,

the Database is MSSQL and ConfigurationManager.AppSettings["DisableSequenceGenerator"]!=true is correct set.

It seems that the attach doesn´t work. The first line
(!xpandModuleBase.Executed<ISequenceGeneratorUser>(SequenceGeneratorHelperName))
always returns false so that the InitializeSequenceGenerator() is never executed.


public void Attach(XpandModuleBase xpandModuleBase) {
    if (!xpandModuleBase.Executed<ISequenceGeneratorUser>(SequenceGeneratorHelperName)) {
        if (SequenceObjectType == null) {
            SequenceObjectType =xpandModuleBase.LoadFromBaseImpl("Xpand.Persistent.BaseImpl.SequenceObject");
                }
                if (xpandModuleBase.RuntimeMode) {
                    _xpandModuleBase = xpandModuleBase;
                    Application.LoggedOff += ApplicationOnLoggedOff;
                    var helper = new ConnectionStringHelper();
                    helper.Attach(_xpandModuleBase);
                    helper.ConnectionStringUpdated += (sender, args) => {
                        var disable = ConfigurationManager.AppSettings["DisableSequenceGenerator"];
                        if (string.IsNullOrEmpty(disable)||!disable.Contains("true"))
                            InitializeSequenceGenerator();
                    };
                }
            }
        }

**Comment by apobekiaris** [comment]
>always returns false so that the InitializeSequenceGenerator() is never executed.

which means that is already executed.

btw why don't you explicitly initialize the SequenceGenerator using for exemplae this overload?

https://github.com/eXpandFramework/eXpand/blob/356c881b25266391420717e6d6b8e9e3534d7774/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/SequenceGenerator.cs#L311-L312

**Comment by apobekiaris** [comment]
>(!xpandModuleBase.Executed(SequenceGeneratorHelperName))
always returns false so that the InitializeSequenceGenerator() is never executed.

also can you do not have any `ISequenceGeneratorUser` module like these the XpandSystemModule or the ModelDifferenceModule. In those cases you should initialize as suggested above.

**Comment by CWolffIF** [comment]
Hi Tolis,

I´ve got the XpandSystemModule but not the ModelDifferenceModule in the project.

I tried

        protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args)
        {
            args.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(XPObjectSpaceProvider.GetDataStoreProvider(args.ConnectionString, args.Connection, true),true));
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));

            Xpand.Persistent.Base.General.SequenceGenerator.Initialize(args.ConnectionString, typeof(Xpand.Persistent.BaseImpl.SequenceObject));
        }

and it worked.

**Comment by CWolffIF** [comment]
I add both moduls XpandSystemModule and ModelDifferenceModule to the project (and deleted the explicit initalization) and it do not work.

**Comment by apobekiaris** [comment]
sorry i cannot suggest anything without being able to repro it and in my tests worked fine.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
