### ISSUE TITLE
ModelDifference updater

### ISSUE THREAD

**Issue by chulanbetra** [eXpandFramework/eXpand#261]
Hello,

I am trying to update one of my older projects that included Xpand for further use. I just updated everything to Devexpress 18.2.3 resp. 18.2.300 Xpand. Previosuly it was 17.1 version. I try to run the project on new DB and I get an exception in CombineOrderUpdater because of this line:

if (CurrentDBVersion<new Version(18,1,604,0))
                DropIndex(nameof(ModelDifferenceObject),"iCombineOrder_ModelDifferenceObject");

The problem is that somehow the objectspace that i used for this updater has null Connection so it crashes on Null Reference Exception. Any ideas how I can fix this? I am just debugging devexpress and xpand code I did not do any changes besides the 18.2.3 update and the project was working on 17.1 version without problems.

Also I have set the XafApplication.CheckCompatibilityType to ModuleInfo

**Comment by chulanbetra** [comment]
Hi
Thanks for helping me. I found a solution meanwhile. The project is using 'fork' to connect to 2 DB at the same time based on the persistent object type. When i disable this then I can run the application on clean database without problem. After the first run I can uncomment the 'fork' code and then it is working without problems with the old code too (because the tables are created already).

**Comment by apobekiaris** [comment]
Good to know, the patch is on the way, though as this call fails also for  InMemoryDataStoreProvider.ConnectionString

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
