### ISSUE TITLE
Web, Anonymous mode - Login menu does not show

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#262]
Noticed this started happening after upgrading to 18.2
Not sure what is going on and where to look. Browser console does not show anything suspicious.

Example what I am talking about:
![image](https://user-images.githubusercontent.com/234025/49274323-a4a3f580-f480-11e8-9b50-19ed60d3d3b6.png)

**Comment by apobekiaris** [comment]
I managed to repro it in SecurityTester solution after switching to New Web Style. It looks like the new style is getting more mature and does not accessing an object without read permissions. You need something like this for your anonymous role.

```cs
anonymousRole.AddObjectAccessPermission(SecuritySystem.UserType, "[Oid] = CurrentUserId()",SecurityOperations.ReadOnlyAccess);
```

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=275&view=results) includes commit [Web, Anonymous mode - Login menu does not show #262](https://github.com/eXpandFramework/lab/commit/fd6034e128557152bab355b86b1a40c2352aba25) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by emeyke** [comment]
Excellent, thanks Tolis.

**Comment by apobekiaris** [comment]
you still need to adjust permissions manually for your existing projects. The patch fixes the SecuritySystemExtensions

**Comment by emeyke** [comment]
Apologies, used AddObjectAccessPermission instead of AddObjectPermission for XpandPermissionPolicyRole

**Comment by skybluex3** [comment]
hi tolis,
in 18.2.301.27 version i can't click anymore login popup

![login](https://user-images.githubusercontent.com/23338993/49564528-f0e5ae80-f934-11e8-8a06-eefdc7321eeb.png)

**Comment by emeyke** [comment]
I didnt have time to come back to this but for me latest builds didnt resolve this either. A bit stuck on how to proceed with this.

**Comment by emeyke** [comment]
@skybluex3 did you manage to fix this?

**Comment by skybluex3** [comment]
Yeah, i restored css it has been fixed

**Comment by emeyke** [comment]
I my case didnt work due to configuration
<ActionContainer Id="Security">
        <ActionLink ActionId="MyDetails" Removed="True" />
      </ActionContainer>
Closing for now.
