### ISSUE TITLE
ModelDifference Error

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#263]
Hi Tolis,

in Version 18.2.301.23 I got on start the following error:

iXISXRM.Win.exe Error: 0 : 01.12.18 17:09:53.469	================================================================================
The error occurred:

	Type:       TypeLoadException
	Message:    Der Typ "DevExpress.Data.Extensions.IListExtentions" in der Assembly "DevExpress.Data.v18.2, Version=18.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" konnte nicht geladen werden.
	Data:       0 entries
	Stack trace:

   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.FindLayerIndex(ModelMergedDifferenceInfo modelMergedDifferenceInfo, ModelApplicationBase master)
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.<>c__DisplayClass12_0.<AddDifferenceLayers>b__0(String s, IModelApplication application, ModelMergedDifferenceInfo modelMergedDifferenceInfo) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 88.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.CollectModulesDifferences(IEnumerable`1 modulesDifferences, ModelMergedDifferenceInfo mergedDifferenceInfo, Action`3 action) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 121.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.AddDifferenceLayers(ModelNode node, IEnumerable`1 mergedDifferenceses, List`1 modulesDifferences) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 86.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.UpdateNodeCore(ModelNode node) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 47.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.UpdateNode(ModelNode node) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 51.

**Comment by CWolffIF** [comment]
Hi Tolis,
the assembly is there.

**Comment by apobekiaris** [comment]
in 18.2.301.23 indeed there is a change that uses this assembly for the #186. However as I mentioned this looks like a version conflict on your environment over a XAF assembly and not on eXpandFramework. Having say this please try downgrade to 18.2.301.21 and see if the issue remains.

**Comment by apobekiaris** [comment]
on next minor i removed the `DevExpress.Data` using so you need to upgrade and let me know.

**Comment by CWolffIF** [comment]
Hi Tolis,

I downgraded to 18.2.301.21 and everything works. Thanks.

I will try with the next minor and give you a feedback.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.24](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=278&view=results) includes commit [Model View inheritance inserts layers into wrong locations #186 #263](https://github.com/eXpandFramework/lab/commit/5d32f2ed9393a06dc9c79677ebb89b5197018419) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
btw does this code also throws in your project?

```cs
DevExpress.Data.Extensions.IListExtentions.FindIndex(new[]{1}.ToList(), i => true);
```

**Comment by CWolffIF** [comment]
Hi Tolis,

this problem lies in the ToList().

int lx=DevExpress.Data.Extensions.IListExtentions.FindIndex(new[]{1}, i => true);

is OK.

**Comment by CWolffIF** [comment]
Sorry,

using Linq;

and there is no Error.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.25](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=279&view=results) includes commit [Model View inheritance inserts layers into wrong locations #186 #263](https://github.com/eXpandFramework/lab/commit/82266e809d71cff215909548282cf88402e313be) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by CWolffIF** [comment]
Hi,

since 18.2.301.25 there is no problem.
