### ISSUE TITLE
Worldcreator Assocations

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#264]
Hi tolis,
I'm using N-N relationships and i wanna set intermediate table name.
How to use PersistentAssociationAttribute with UseAssociationNameAsIntermediateTableName parameter?

**Comment by apobekiaris** [comment]
Hi,

This is not possible with the current source, I will implement it in the next minor

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
