### ISSUE TITLE
Worldcreator anda validations web

### ISSUE THREAD

**Issue by melihyilman** [eXpandFramework/eXpand#267]
Hi Tolis,
I have suggestion for worldcreator assemblybuilder.

In this version it's selecting all code from persistent* tables. I have 300+ persistent class and attributes
and every client requesting for generating code.
I suggest when persistentassemblyinfo is saved, update generatedCode field and when application is started it should only work this query "select generatedcode from persistentassemblyinfo " and you can change it when revisionNumber is updated.

**Comment by apobekiaris** [comment]
Please provide details as to what does not work

![image](https://user-images.githubusercontent.com/159464/49398005-ca155580-f745-11e8-9264-640509e1a1cf.png)

**Comment by skybluex3** [comment]
Hmm. Does it matter with new ui?

**Comment by apobekiaris** [comment]
it shouldn't 

![image](https://user-images.githubusercontent.com/159464/49398810-25e0de00-f748-11e8-90b3-31ef0b3131d7.png)
