### ISSUE TITLE
MasterDetailController reference is null

### ISSUE THREAD

**Issue by genets** [eXpandFramework/eXpand#268]
Xpand.ExpressApp.Dashboard.Controllers.MasterDetailController.DetailViewdashboardViewItemControlCreated(Object sender, EventArgs e)
   в DevExpress.ExpressApp.Editors.ViewItem.OnControlCreated()
   в DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   в DevExpress.ExpressApp.Win.Layout.WinLayoutManager.controlItem_QueryControl(Object sender, QueryControlEventArgs e)
   в DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseQueryControl()
   в DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.EnsureControl()
   в DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseShowHide(Boolean visible)

I think `frame.GetController<NewObjectViewController>() == null`

**Comment by apobekiaris** [comment]
Hi

Thanks for reporting, probably that is the problem although not clear why is null at this point. I am looking into to it...

p.s.: It should be super easy to break on the exact line if you [use the symbols](https://github.com/eXpandFramework/eXpand/wiki/HowToDebug) and VS Break On Error.

**Comment by apobekiaris** [comment]
The Frame.GetController<T> method can return a null value if the XafApplication.OptimizedControllersCreation option is enabled. This specificity is mentioned in the [documentation](https://docs.devexpress.com/eXpressAppFramework/DevExpress.ExpressApp.Frame.GetController--1). I will use safer methods there and prepare patch.

**Comment by genets** [comment]
thank you, now OptimizedControllersCreation  = false

Failed to cast object type "Xpand.ExpressApp.XpandListView" to type "DevExpress.ExpressApp.DetailView".

    in Xpand.ExpressApp.Dashboard.Controllers.MasterDetailController.DetailViewdashboardViewItemControlCreated (Object sender, EventArgs e)
    in DevExpress.ExpressApp.Editors.ViewItem.OnControlCreated ()
    in DevExpress.ExpressApp.Editors.ViewItem.CreateControl ()

**Comment by apobekiaris** [comment]
Do you use that MasterDetail controller? can you post the model differences for this dashboard? or even better a sample?

**Comment by genets** [comment]
it is also impossible to add two identical views to dashboards

**Comment by apobekiaris** [comment]
You use the eXpandFramework `DashboardModule` which has master-detail feature which is enable by default as per 
https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.ExpressApp.Modules/Dashboard/Controllers/MasterDetailController.cs#L89-L96

I will improve this class not to autoactive when you have two views of the same type. However my guess is that you not using this feature and you need to manually disable it.
![image](https://user-images.githubusercontent.com/159464/49441391-ffb25100-f7ce-11e8-803b-af9e094f0a5b.png)

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.27](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=281&view=results) includes commit [Dashboard MasterDetailController might throw when OptimizedControllersCreation #268](https://github.com/eXpandFramework/lab/commit/79f9d30abc98ee47928cd53825ad17e3dc8fcbb9),[Dashboard MasterDetailController might throw when OptimizedControllersCreation #268](https://github.com/eXpandFramework/lab/commit/d4d5980e5f95d670c24c364cc5c22bdd91374379) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
