### ISSUE TITLE
.net 4.7.2

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#269]
Hello,

Have you tried to run eXpand agains .net 4.7.2 ? 
Any bad surprise to expect ? 

BR
ISA

**Comment by apobekiaris** [comment]
Hi,

eXpand uses 4.6.1 so later versions should be fully compatible.

**Comment by isatahiri** [comment]
Hi,

Thank you for the quick answer. I'll give a try 

BR
ISA

**Comment by isatahiri** [comment]
OK so far no surprise, I could compile and run the app without any issue (v 18.2.301.28)

BR
ISA
