### ISSUE TITLE
Ojbect Reference not set in model imageName

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#270]
Hi tolis,
I get object reference not set for every image choser property when i click for change it, i think have trouble

![untitled](https://user-images.githubusercontent.com/23338993/49592017-139db480-f981-11e8-8481-2804c06d0e8b.png)

**Comment by apobekiaris** [comment]
it works fine on an empty Xpand solution having all modules installed.
![image](https://user-images.githubusercontent.com/159464/49627265-960c8f80-f9e6-11e8-82f6-120553677c0d.png)

try to sample us.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
