### ISSUE TITLE
ModelCache

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#271]
Hi Tolis,

in 18.2.301.29 you get an Error if use the ModelCache in the second start of the application. If you delete the Model.Cache.xafml File you can start again.

The Error:

iXISXRM.Win.exe Error: 0 : 07.12.18 08:13:23.176	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    XpandLogonParameters_DetailView-XpandLogonAuthenticationStd-AuthenticationStandardLogonParameters_DetailView
	Data:       0 entries
	Stack trace:

   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.FindLayerIndex(ModelMergedDifferenceInfo modelMergedDifferenceInfo, ModelApplicationBase master) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 107.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.<>c__DisplayClass12_0.<AddDifferenceLayers>b__0(String s, IModelApplication application, ModelMergedDifferenceInfo modelMergedDifferenceInfo) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 86.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.CollectModulesDifferences(IEnumerable`1 modulesDifferences, ModelMergedDifferenceInfo mergedDifferenceInfo, Action`3 action) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 132.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.AddDifferenceLayers(ModelNode node, IEnumerable`1 mergedDifferenceses, List`1 modulesDifferences) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 84.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.UpdateNodeCore(ModelNode node) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 45.
   bei Xpand.Persistent.Base.General.MergedDifferencesUpdater.UpdateCachedNode(ModelNode node) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\ModelMergedDifferences.cs:Zeile 23.
   bei DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.RunUpdaters(ModelNode node, Boolean enableModelCache)
   bei DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.GenerateNodes(ModelNode node)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)

**Comment by apobekiaris** [comment]
thanks for reporting, working on a fix.

**Comment by apobekiaris** [comment]
see also #186

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.30](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=284&view=results) includes commit [#186 #263 #271 InvalidOperationException when Cache enabled](https://github.com/eXpandFramework/lab/commit/a2f74c8c670666bc7687f6b7edc18af44cba9126) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by CWolffIF** [comment]
Hi Tolis,

it works!

But now I have to initialize the sequencegenerator manualy. Then the Sequence work. In 18.2.301.28 this step wasn´t necessary.


        protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args)
        {
            args.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(XPObjectSpaceProvider.GetDataStoreProvider(args.ConnectionString, args.Connection, true),true));
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));

            Xpand.Persistent.Base.General.SequenceGenerator.Initialize(args.ConnectionString, typeof(Xpand.Persistent.BaseImpl.SequenceObject));
        }

**Comment by apobekiaris** [comment]
I do not see how this relates to the model, if you can guide me on how to repro it.

**Comment by CWolffIF** [comment]
I even don´t know why.
In a new project the problem doesn´t appear. The manual initialization works. I try to debug (if I got time....)
