### ISSUE TITLE
Listview is opened as popup when clicking on app logo (web version)

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#272]
If OpenDetailViewAsPopup ist set for the default navigation item, a click on the application logo opens the listview as a 

popup. Here is a short [screencast ](https://screencast-o-matic.com/watch/cFljlJrahr) demonstrating this behaviour. You can easily reproduce it by setting OpenDetailViewAsPopup to true for the ActionsObject_ListView in the model editor of the SystemTester project.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.34](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=288&view=results) includes commit [Listview is opened as popup when clicking on app logo (web version) #272](https://github.com/eXpandFramework/lab/commit/12a0511275ce849fd345f635399aaa6649c1a0a6) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by krombipils** [comment]
Works like a charm. Thank you!

**Comment by krombipils** [comment]
I think the issue is back again in 18.2.4:
I replaced `if (createdView != null && View != createdView)` with `if (createdView != null && View.Id != createdView.Id)` and it seems to be working now.

**Comment by krombipils** [comment]
I think my quick workaround does not really fix the issue. I will check again with your SystemTester demo

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by krombipils** [comment]
I think there is still/again a problem with your code: On my side the code is also executed for ListViews, therefore new ListViews also open in a Popup.

I replaced `else if (_listViewShowViewStrategy.OpenDetailViewAsPopup)` with
`else if (_listViewShowViewStrategy.OpenDetailViewAsPopup && createdView is DetailView)`
and it seems to be working fine now.
How can I repro this bug in eXpand? There are no web sample/demo projects anymore.

**Comment by krombipils** [comment]
Unfortunately I cannot re-open the issue

**Comment by apobekiaris** [comment]
thnks for the fix!

>There are no web sample/demo projects anymore.

having projects with no tests makes no sense, if eXpand is in your GAC you can use eXpand NewProject Wizard to fast create a soltion, else create a xaf empty project and install the related module.

the bot will notify u once fixed thnks again

**Comment by expand** [comment]
eXpand.lab release [19.1.602.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.4) includes commit that relate to this task:

* [inconsistent behavior of OpenDetailViewAsPopup #272](https://github.com/eXpandFramework/eXpand.lab/commit/fef0acb393f8fc67d68dfc8efd18ad1a8de69ac8)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Finally working!
