### ISSUE TITLE
after added xpand framework to XAF, error occurred after clicked on login.

### ISSUE THREAD

**Issue by CindyOw** [eXpandFramework/eXpand#273]
Hi,

Could you advice what would have been missed or how can i troubleshoot this error?

Thanks in advance.

Attached is the error message.

**Comment by CindyOw** [comment]
[error.txt](https://github.com/eXpandFramework/eXpand/files/2666263/error.txt)

**Comment by apobekiaris** [comment]
the error recorded does not involve eXpandFramework in stacktrace, can you post a sample?
