### ISSUE TITLE
EnableModelCache 

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#274]
Hi Tolis,

if I enable the Modelcache
winApplication.EnableModelCache = true;

I got the following Error in the RELEASE Version. Any idea?

2.12.18 20:55:13.749	================================================================================
12.12.18 20:55:13.751	Trace Log for iXISXRM.Win.exe is started
12.12.18 20:55:13.751	================================================================================
iXISXRM.Win.exe Error: 0 : 12.12.18 20:55:51.657	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Fehler beim Vergleichen von zwei Elementen im Array.
	Data:       0 entries
	Stack trace:

   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Comparison`1 comparison)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetChildrenForSerialization()
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.WriteToString(IModelNode modelNode, Int32 aspectIndex)
   bei DevExpress.ExpressApp.ModelCacheManager.Save(ModelApplicationBase model)
   bei DevExpress.ExpressApp.ApplicationModelManager.CreateUnchangeableLayer(ModelStoreBase[] modelDifferenceStores)
   bei DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
   bei DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   bei DevExpress.ExpressApp.Win.WinApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   bei DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters)
   bei DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.XafApplication.Setup()
   bei iXISXRM.Win.Program.Main() in C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Win\Program.cs:Zeile 101.
	----------------
	InnerException:

			Type:       DuplicateModelNodeIdException
			Message:    There is already a node with Id 'UserName'. The node: Application/Views/XpandLogonParameters_DetailView/Layout/Main/RootGroup/EditorsGroup/Editors/UserName. To avoid this error, analyze your custom code or XAFML model differences for possible duplicate nodes creation or follow the www.devexpress.com/kb=S19870 KB article, if you have several classes in different namespaces, but with the same name.
			Data:       0 entries
			Stack trace:

   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(ModelNode node)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(String id, Type type)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddClonedNode(ModelNode source, String id)
   bei DevExpress.ExpressApp.SystemModule.ConvertLayoutDiffsController.ConvertLayoutDiffs(IList`1 nodes)
   bei DevExpress.ExpressApp.SystemModule.SystemModule.<>c.<AddModelNodeValidators>b__9_0(IList`1 nodes)
   bei DevExpress.ExpressApp.Model.Core.ModelNodeInfo.UpdateNodes(IList`1 nodeLayers)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.UpdateNodeLayers(IList`1 nodeLayers, Boolean hasFirstLayer)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.PopulateMasterNodesForChildNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureMaster(ModelMultipleMasterStoreItem masterNodeItem)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.get_Master()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetMasterRecursive()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetModelValue(String name)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Boolean inThisLayer, Int32 aspectIndex)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   bei DevExpress.ExpressApp.Model.Core.SortChildNodesHelper.DoSortNodesByDefault(ModelNode node1, ModelNode node2)
   bei System.Array.FunctorComparer`1.Compare(T x, T y)
   bei System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
			InnerException is null

**Comment by apobekiaris** [comment]
Hi,

Try disabling the view inheritance updater

```cs
MergedDifferencesUpdater.Disable-true
```cs

does it make any difference, if not I have to ask for repro guidance.

**Comment by CWolffIF** [comment]
Hi,

if I disable the MergedDifferencesUpdater it works, but then there is no cache XAFML file build. It has the same effect as winApplication.EnableModelCache = false;.

**Comment by apobekiaris** [comment]
this is the same as #271 right?

**Comment by CWolffIF** [comment]
Hi Tolis,

my test was wrong. If I set
                winApplication.EnableModelCache = true;
                Xpand.Persistent.Base.General.MergedDifferencesUpdater.Disable = true;
it works and XAFML Cache file is build.

**Comment by CWolffIF** [comment]
18.2.401 no Error
