### ISSUE TITLE
ExcelImporter: System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'

### ISSUE THREAD

**Issue by CindyOw** [eXpandFramework/eXpand#275]
Hi,
I have created a simple project with ExcelImporter. I could map the columns, but when I clicked on "Import", it prompt an error - "System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'".

Could you please advice if I had missed any DLL or steps?

Below URL is the simple project which i have created. Excel filename : 'test.xlsx'
https://www.dropbox.com/s/4dh4ro2n3qavrs7/ExcelImport.zip?dl=0

Thanks in advance.

**Comment by apobekiaris** [comment]
Hi,

Thanks for the sample, give me some time please as I am overload at the moment.

**Comment by apobekiaris** [comment]
Sorry for the delay still looking at your sample, however the problem is caused from the `SecuredObjectSpaceProvider` you use. Use an `XPObjectSpaceProvider` for now until i fix it

**Comment by CindyOw** [comment]
Thanks alot for your reply, the issue is solved for now. Hope to see your fix soon.

Thanks.

**Comment by apobekiaris** [comment]
I am working on it now, just wanted to update you because due to works I was late.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.67](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=475&view=results) includes commit [DashboardModule remove security dependency #275](https://github.com/eXpandFramework/lab/commit/e799c9da79407debfd1bcbe23b3458de0e97a530),[PermissionProviderStorage throws if SecuredObjectSpaceProvider is used with ExcelImporter module #275](https://github.com/eXpandFramework/lab/commit/3c7c433a541feedba8ecf0ceda17ad18e0837e58),[DashboardModule remove security dependency #275](https://github.com/eXpandFramework/lab/commit/248e33f819b5f771bc0a5b3729fd82a5ae662928),[Excelimporter key member validation fails #275](https://github.com/eXpandFramework/lab/commit/7974912154248cf9c58000c9fbfb8ff1daf4bfee) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
