### ISSUE TITLE
Release nuget only ModelViewInheritance module 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#277]
### About

This is a low dependency module that replace the existing functionality from the eXpandFramework. It will be part of a new low dependency set of standalone modules-features. 

#### Breaking changes
The assembly and namespaces will change however the classes will remain the same and the model configurations will work as is.

**Comment by apobekiaris** [comment]
The module is released under the https://github.com/eXpandFramework/Packages repository. 

## Installation 
```ps1
Install-package DevExpress.XAF.Modules.ModelViewInheritance
```

Currently is only available through https://xpandnugetserver.azurewebsites.net/ but soon on nuget.org.

**Comment by Ezeckiel2517** [comment]
It fails to install the module

> Unable to resolve dependency 'DevExpress.ExpressApp'.

**Comment by Ezeckiel2517** [comment]
Ok I do not have that feed. Maybe it got removed when I installed the 18.2.4 hotfix.

**Comment by apobekiaris** [comment]
>18.2.4 hotfix.

the packages are for 18.2.3

**Comment by Ezeckiel2517** [comment]
I have installed the new package but i'm not sure how to configure it to work side by side with other expand module. Is this replacing the 'old' view inheritance or should they work together.

right now I have those 2 lines in my module def.

> this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.SystemModule.XpandSystemModule));
> this.RequiredModuleTypes.Add(typeof(DevExpress.XAF.Modules.ModelViewIneritance.ModelViewIneritanceModule));

and when starting the app, I get this error

> An item with the 'ModelMergedDifferences' key has already been added

**Comment by apobekiaris** [comment]
this module will replace the existing functionality which was shared in all eXpandFramework modules. Meaning that it will be installed as a required module together with your existing eXpand modules. This integration does not involve further actions from an eXpandFramework user. 

For now you can either install it in a new XAF only solution and test it, or disable old updater 

```cs
Xpand.Persistent.Base.General.MergedDifferencesUpdater.Disable=false
```

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.67](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=475&view=results) includes commit [Integrate ModelViewInheritance module #277](https://github.com/eXpandFramework/lab/commit/c63230d6db6bce928227509226608a909f438ca7) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by CWolffIF** [comment]
Hi Tolis,

in 18.2.302 I get the Error with the missing "h" again.

Error:
Unable to create an instance of the "Xpand.ExpressApp.Security.XpandSecurityModule" type.
Reason: "Die Datei oder Assembly "DevExpress.XAF.Modules.**ModelViewIneritance**, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden."
Update failed

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
