### ISSUE TITLE
Nuget for the framework

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#278]
hello Tolis,

I see that the last build is : 18.2.301.34
Any chance to get the 18.2.4 by the begining of next week ? 

Is there any plan to deploy nuget for the framework ? 
BR
ISA

**Comment by apobekiaris** [comment]
Hi,

Unfortunately there are many works and tests to pass, probably by the end, sorry about the delay. 

Until then you can always compile the source after running project converter so u can generate all assemblies.

**Comment by isatahiri** [comment]
Well i tried but it seems that is not working like it I excpected. 

I had a first error when i tried to convert the solution "Xpand.ExpressApp" : 
![image](https://user-images.githubusercontent.com/41955268/50401174-ceed8800-078c-11e9-9d3f-91fff1c56fcf.png)

Then i tried to open the solution AllModules and convertit. After the build i had this : 
![image](https://user-images.githubusercontent.com/41955268/50401212-11af6000-078d-11e9-9351-f85ee4bb2822.png)

It seems that i passed to fast to 18.2.4. Next time i'll have a look into you builds before.

Best regards and Merry Christmas
Isa

**Comment by apobekiaris** [comment]
Merry Xmas Isa,

Looks like next XAF minor has breaking changes, however I do not have the resources to pursue this case separately. I am working on integrating the DX nuget and simplifying the build scripts. In addition if you noticed there is an on going integration of the new Packages project and its modules and extensions. 

This puts me in an overload state at the moment.

Thanks for the understanding.

**Comment by isatahiri** [comment]
Hello Tolis,
Do you have any date for the 18.2.4? 

BR
Isa

**Comment by apobekiaris** [comment]
I am working on it, hope soon

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
