### ISSUE TITLE
PersistentModelDefaultAttribute

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#279]
Hi tolis,
Executing Sql 'insert into "dbo"."PersistentAttributeInfo"("Oid","Name","Owner","OptimisticLockField","GCRecord","ObjectType")values(@p0,@p1,@p2,@p3,null,@p4) insert into "dbo"."PersistentModelDefaultAttribute"("Oid","PropertyName","Value")values(@p5,@p6,@p7) insert into "dbo"."PersistentAttributeInfo"("Oid","Name","Owner","OptimisticLockField","GCRecord","ObjectType")values(@p8,@p9,@p10,@p11,null,@p12) set @r=1' with parameters '{71c4a49d-d56e-406a-a687-bf0efc16661d},{PersistentModelDefaultAttribute: DataSourceCriteria},{21dbad38-a70b-463d-984f-ec06003b8476},{0},{6},{71c4a49d-d56e-406a-a687-bf0efc16661d},{DataSourceCriteria},{KeyName = 'EGITIMDEGERLENDIRMEFORMUEVAULATIONOFTRAININGFORMEGITI...},{6f48bf7f-cba0-4868-88ec-c7658330aded},{PersistentModelDefaultAttribute: Caption},{21dbad38-a70b-463d-984f-ec06003b8476},{0},{6},{1}' exception 'System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.

Could you change size to nvarchar max on PersistentAttributeInfo  class for Name property?

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.01](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=502&view=results) includes commit [change size to nvarchar max on PersistentAttributeInfo class for Name property #279](https://github.com/eXpandFramework/lab/commit/beb0c008a9323870bb16e8ff83c9238eb6cc68ea) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS
