### ISSUE TITLE
Exception occurs while assigning the 'XpandListView, ID:Employee_ListView' view to WebWindow:  Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by CindyOw** [eXpandFramework/eXpand#280]
Hi, I am trying to use the masterdetailmode, but whenever i load the employee page, the attached error prompted. Could you advise if any setting is needed or is there any workaround to use the masterdetailmode?

Thanks in Advance.

![model_xaml](https://user-images.githubusercontent.com/45781750/50505917-26ebfd80-0ab1-11e9-83e6-9c5b4582c689.PNG)
![masterdetailmode](https://user-images.githubusercontent.com/45781750/50505918-28b5c100-0ab1-11e9-87ce-6f033813cfb5.PNG)

**Comment by CindyOw** [comment]
Hi, below is the link for a simple project.

https://www.dropbox.com/s/8y0k8qwplybt31m/ExcelImport.rar?dl=0

**Comment by apobekiaris** [comment]
I am sorry for the late response, from what I see you are using a not supported feature. The framework provides full master-detail support by using dashboard. Please run (step-by-step) this easytest as an example. 
https://github.com/eXpandFramework/eXpand/tree/18.2/Demos/Modules/Dashboard/DashboardTester.Module/FunctionalTests/MasterDetail

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
