### ISSUE TITLE
18.2.4

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#282]
There was a major bug fixed in DevEx 18.2.4. Do you know when eXpand 18.2.4 will be available? I have to get to production asap. THANKS!

**Comment by capricciobob** [comment]
Found another question on this. I am closing this one. Sorry for the duplicate!

**Comment by apobekiaris** [comment]
just a few more hours

**Comment by isatahiri** [comment]
Also wainting for this. Thanks for your contribution Tolis. It helps really a lot.
