### ISSUE TITLE
fix ModelViewInheritance module spelling

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#283]
this will result in braking changes and you need to reinstall the module if you use it as standalone

**Comment by apobekiaris** [comment]
[fix ModelViewIneritanceModule spelling #283](https://github.com/eXpandFramework/Packages/commit/84b4aa0f75d1e01e56c985dcc50ead4aa5e57319) relates to this task. Please update your nuget packages to version 18.2.400.64 and test if it addresses the problem.
 To access the lab packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.
 If these packages are already integrated with eXpandFramework the bot will notify this issue again as soon as the release is ready.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.04](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Fix ModelViewIneritance spelling #283](https://github.com/eXpandFramework/lab/commit/f97ded480e38d1a8b78411a16214bf980a98fbf3),[Fix ModelViewIneritance spelling #283](https://github.com/eXpandFramework/lab/commit/ba38a73ed6fe00962ca8f214342da2226ddf11da) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
