### ISSUE TITLE
ExcelImporter error on start

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#285]
Hi Tolis,

I upgraded to the version 18.2.401.

![image](https://user-images.githubusercontent.com/41955268/50724144-09d6b080-10e9-11e9-848a-cc182f7ab14f.png)
![image](https://user-images.githubusercontent.com/41955268/50724148-0fcc9180-10e9-11e9-8fc1-b87043331f0a.png)

When i start the project i have this message : 

/**
Exception occurs while activating the 'Xpand.ExpressApp.ExcelImporter.Win.Controllers.AutoImportController' controller:
No match for method with name OnPropertyChanged and flags Instance | NonPublic | Public | Static on type Xpand.Persistent.Base.XpandFileData.
**/

I'm probably missing something. 

Could you please help me on what is missing ? 

Before we could install the framework and chose from module file what we need easely. 
Now we have to choose from the nuget. 
If i install these  : 
![image](https://user-images.githubusercontent.com/41955268/50724188-d21c3880-10e9-11e9-8c34-d0ac94ad7cbd.png)
![image](https://user-images.githubusercontent.com/41955268/50724193-dc3e3700-10e9-11e9-8c3f-74a972d23e5a.png)
![image](https://user-images.githubusercontent.com/41955268/50724197-e2ccae80-10e9-11e9-9663-26084080141d.png)

Does that mean that everything from your framework is activated ? 

BR
ISA

**Comment by apobekiaris** [comment]
i missed the fody configuration I am fixing it

see also #284

**Comment by apobekiaris** [comment]
>I'm probably missing something.

>Could you please help me on what is missing ?

>Before we could install the framework and chose from module file what we need easely.
Now we have to choose from the nuget.
If i install these :

I am not sure what this the question here, you need to update the ExcelImporter nuget package and this will reference the dependencies. However these are just assemblies referenced and you also need to register the module you interested so I guess the ExcelImporter platform dependence modules. Now if these modules depend on other modules the registration is done internally and you may skip it.

If you need further explanation shoot

**Comment by apobekiaris** [comment]
eXpandWin, eXpandWeb, are system modules and do not install any other module, some modules require them and will install them internally

**Comment by apobekiaris** [comment]
Agnostic is a package that contains all agnostic modules however you still need to register explicitly the modules you want to use. Registration does not mean reference assemblies. Registration is done as per https://documentation.devexpress.com/eXpressAppFramework/118047/Concepts/Application-Solution-Components/Ways-to-Register-a-Module. Referencing the assemblies does nothing more than allow you to use their API if any however XAF artifacts won't be functional if you do not register the module

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.01](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=502&view=results) includes commit [XpandFileData throws cause fody internal method naming changed #285 #284](https://github.com/eXpandFramework/lab/commit/190629ef4cf07ff9e7c2704cac493db4444d9388) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by isatahiri** [comment]
Message desapeared. 
Thanks
