### ISSUE TITLE
SequenceGenerator creates gaps if connected to new middle tier app server

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#286]
**Describe the bug**

If connected to the new middle tier application server implementation, the GetNextSequence of SequenceGenerator is executed twice leading to gaps. A new sequence is generated for the _DevExpress.ExpressApp.Security.ClientServer.SecuredSessionObjectLayer_ and for the
_DevExpress.Xpo.SimpleObjectLayer_ on the server side.
I think the SequenceGenerator.CanGenerate method must be changed. The [DevExpress sample ](https://github.com/DevExpress-Examples/how-to-generate-a-sequential-number-for-a-persistent-object-within-a-database-transaction-xaf-e2829/blob/17.2.8%2B/CS/GenerateUserFriendlyId.Module/BusinessObjects/UserFriendlyIdPersistentObject.cs) explicitly checks for SecuredSessionObjectLayer:
` if(!(Session is NestedUnitOfWork)
                    && (Session.DataLayer != null)
                        && (Session.ObjectLayer is SimpleObjectLayer)
                        //OR
                        //&& !(Session.ObjectLayer is DevExpress.ExpressApp.Security.ClientServer.SecuredSessionObjectLayer)
                            && Session.IsNewObject(this)) {
                    GenerateSequence();
}`

**Comment by apobekiaris** [comment]
I am sorry it looks like I missed this one.

Looking at the `CanGenerate` method I see that there is a similar check `IsRemoteClient`

https://github.com/eXpandFramework/eXpand/blob/976fa35e4af21dfc77f22e61be7902f4f4dac1c8/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/SequenceGenerator.cs#L266

does that check fail for some reason?

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
