### ISSUE TITLE
eXpand.Search

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#287]
Hi Tolis,

is there a documentation about the eXpand.Search Modul (from the eXpand.System Modul)? I like to understand the possibilities of the Modul and the paramters to set in den Moduleditor.

In one of my projects (but only in one) I go an Error when using the Search-Button from the DetailView. But I don´t really understand the options to set.

iXISXRM.Win.exe Error: 0 : 05.01.19 14:04:15.611	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei Xpand.ExpressApp.Win.SystemModule.SearchFromDetailViewController.SearchActionOnExecute(Object sender, SimpleActionExecuteEventArgs simpleActionExecuteEventArgs) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\SearchFromDetailViewController.cs:Zeile 16.
   bei DevExpress.ExpressApp.Actions.SimpleActionExecuteEventHandler.Invoke(Object sender, SimpleActionExecuteEventArgs e)
   bei DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   bei DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by apobekiaris** [comment]
>is there a documentation about the eXpand.Search Modul (from the eXpand.System Modul)? 

I understand the importance of some basic at least documentation and examples. So at the moment I am focusing or packaging the framework in smaller nuggets where you will find what you need see the [Packages](https://github.com/eXpandFramework/Packages) project. You welcome to participate if you like.

Now digging the source on this exception first it leads to https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.ExpressApp/Xpand.ExpressApp.Win/SystemModule/SearchFromDetailViewController.cs#L16

where the only possible NullReference could be in `SearchAbleMemberInfos` which is declared in base class and assigned at 
https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/SystemModule/Search/SearchFromDetailViewController.cs#L33-L34

This line tells us the the `View.ObjectTypeInfo.FindMember` returns `null`, so you need to question if this check holds
`mode.SearchMemberMode == SearchMemberMode.Include`

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
