### ISSUE TITLE
Expand Nuget --> Toolbox editor does not contain Expand modules

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#288]
Hi,

I have question related to : 
https://github.com/eXpandFramework/eXpand/issues/285#issuecomment-451650508

I do not see the modules in the toolbox anymore.
What should i do now to see the modules in the toolbox : 
![image](https://user-images.githubusercontent.com/41955268/50725230-d13fd280-10fa-11e9-8131-a866584a1420.png)

BR
ISA

**Comment by apobekiaris** [comment]
MS is working of design time support for Nuggets however at the moment if you use nugets you are like just referencing the assemblies. I will add automating module registration as well in the future. For the toolbox and other design time features you need to use the installer.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
