### ISSUE TITLE
ModelViewInheritance fails when 1 collection in base and more than zero in subclass

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#289]
Improve unit test to cover this

**Comment by apobekiaris** [comment]
[ModelViewIneritance revert base layout strategies and load from resource when design time. #290 #289 #186](https://github.com/eXpandFramework/Packages/commit/525732e3528a483882c9ab788290c24bdb6fbdd1) relates to this task. Please update your nuget packages to version 18.2.400.64 and test if it addresses the problem.
 To access the lab packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.
 If these packages are already integrated with eXpandFramework the bot will notify this issue again as soon as the release is ready.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
