### ISSUE TITLE
Symbols are not indexed

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#293]
improve ci process to enable as per https://github.com/eXpandFramework/eXpand/wiki/HowToDebug

**Comment by apobekiaris** [comment]
done

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
