### ISSUE TITLE
ModelViewInheritance throws if BO is not exported

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#294]
add check for null

**Comment by apobekiaris** [comment]
#292

**Comment by apobekiaris** [comment]
[ModelViewInheritance throws if BO is not exported #294](https://github.com/eXpandFramework/Packages/commit/c4ea6a4f383b98d6691c638c7279e00d19bad11d) relates to this task. Please update your nuget packages to version and test if the problem is gone.
 To access the lab packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.
 If these packages are already integrated with eXpandFramework the bot will notify this issue again as soon as the release is ready.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
