### ISSUE TITLE
Please compile exe file

### ISSUE THREAD

**Issue by lekhanhky** [eXpandFramework/eXpand#295]
Please compile exe file for version 18.2.4.Tks

**Comment by apobekiaris** [comment]
no idea what this means

**Comment by zisiszaverdas** [comment]
i am guessing that its about the last 3 release that do not include the installer(eXpandFramework.exe).

Is this intended?

**Comment by apobekiaris** [comment]
nope sorry about it, as there are works on the CI somehow I missed to publish the installer

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
