### ISSUE TITLE
NullReference in ModelViewInheritance when starting application

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#296]
**Describe the bug**
Hi Tolis. 

I am getting a NullReference when staring my application using the 18.2.402 of eXpand that uses the ModelViewInheritance nuget package. 

De objectverwijzing is niet op een exemplaar van een object ingesteld.

   bij DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateViewModel(ValueTuple`3 info, IModelApplication application, ModelNode master) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:regel 83
   bij DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.<>c__DisplayClass6_0.<UpdateModel>b__1(IModelApplication application) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:regel 66
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateModel(ModelNode master, ValueTuple`3 info, IModelApplication[] modulesDifferences) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:regel 64
   bij DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateNodeCore(ModelNode node) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:regel 31
   bij DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.RunUpdaters(ModelNode node, Boolean enableModelCache)
   bij DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   bij DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   bij DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   bij DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   bij DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   bij DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   bij DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   bij DevExpress.ExpressApp.Model.Core.ModelNodeList`1.get_Item(String id)
   bij DevExpress.ExpressApp.ReportsV2.Win.ReportsWindowsFormsModuleV2.Application_SetupComplete(Object sender, EventArgs e)
   bij System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bij DevExpress.ExpressApp.XafApplication.OnSetupComplete()
   bij DevExpress.ExpressApp.Win.WinApplication.OnSetupComplete()
   bij DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bij DevExpress.ExpressApp.XafApplication.Setup()
   bij Vekrasoft.ERP.Win.Program.Main(String[] args) in C:\Source\Vekrasoft ERP\Vekrasoft.ERP\Vekrasoft.ERP.Client.Win\Program.cs:regel 44

**To Reproduce**
Start application
Exception throws before login screen (login screen uses MergedDifferences nodes

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
