### ISSUE TITLE
NullReference in SequenceGeneratorHelper.IsMySql() when starting Quartz Server

### ISSUE THREAD

**Issue by softkey87** [eXpandFramework/eXpand#298]
Hi,

After update to 18.2.403 version of eXpand, I have the following NullReference exception when starting the Quartz server. Here is the call stack:
	
Xpand.Persistent.Base.dll!Xpand.Persistent.Base.General.SequenceGeneratorHelper.IsMySql(DevExpress.ExpressApp.DC.ITypeInfo typeInfo) Line 452 + 0x18 bytes	C#
Xpand.Persistent.Base.dll!Xpand.Persistent.Base.General.SequenceGeneratorHelper.ModifySequenceObjectWhenMySqlDatalayer(DevExpress.ExpressApp.DC.ITypesInfo typesInfo) Line 438 + 0x9 bytes	C#
Xpand.Persistent.Base.dll!Xpand.Persistent.Base.General.TypesInfoExtensions.ModifySequenceObjectWhenMySqlDatalayer(DevExpress.ExpressApp.DC.ITypesInfo typesInfo) Line 43	C#
Xpand.Persistent.Base.dll!Xpand.Persistent.Base.General.XpandModuleBase.CustomizeTypesInfo Line 691	C#
Xpand.ExpressApp.dll!Xpand.ExpressApp.SystemModule.XpandSystemModule.CustomizeTypesInfo(DevExpress.ExpressApp.DC.ITypesInfo typesInfo) Line 82	C#
DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(DevExpress.ExpressApp.DC.ITypesInfo typesInfo) Line 181 + 0xe bytes	C#
DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.ApplicationModulesManager.Load(DevExpress.ExpressApp.DC.ITypesInfo typesInfo, bool loadTypesInfo) Line 274 + 0xa bytes	C#
DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.XafApplication.Setup(string applicationName, System.Collections.Generic.IList<DevExpress.ExpressApp.IObjectSpaceProvider> objectSpaceProviders, DevExpress.ExpressApp.ApplicationModulesManager modulesManager, DevExpress.ExpressApp.Security.ISecurityStrategyBase security) Line 1620 + 0x1b bytes	C#
DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.XafApplication.Setup() Line 1543 + 0x3e bytes	C#
Xpand.Persistent.Base.dll!Xpand.Persistent.Base.General.XafApplicationFactory.GetApplication Line 28	C#
Affactura.Quartz.Service.exe!Affactura.Quartz.Service.Program.Main.AnonymousMethod__0_3(Affactura.Quartz.Service.QuartzServer quartzServer) Line 50 + 0xc bytes	C#
Topshelf.dll!Topshelf.ServiceConfiguratorExtensions.WhenStarted<Affactura.Quartz.Service.QuartzServer>.AnonymousMethod__0(Affactura.Quartz.Service.QuartzServer service, Topshelf.HostControl control) + 0x2b bytes	
Topshelf.dll!Topshelf.Builders.DelegateServiceBuilder<Affactura.Quartz.Service.QuartzServer>.DelegateServiceHandle.Start(Topshelf.HostControl hostControl) + 0x5e bytes	
Topshelf.dll!Topshelf.Hosts.ConsoleRunHost.Run() + 0x20c bytes	
Topshelf.dll!Topshelf.HostFactory.Run(System.Action<Topshelf.HostConfigurators.HostConfigurator> configureCallback) + 0x48 bytes	
Affactura.Quartz.Service.exe!Affactura.Quartz.Service.Program.Main(string[] args) Line 39 + 0x52 bytes	C#

After debugging, I saw that ApplicationHelper.Instance.Application was null. I found the following commit that can be the cause of the issue:
[https://github.com/eXpandFramework/eXpand/commit/1a1a370b4d7023b20587ece9c44078941334dd7f](url)

By removing these two lines, the Quartz server is now running properly. Can you check what's wrong with these?

Thank you very much for your help!

**Comment by apobekiaris** [comment]
you change does not make sense now Xpand assemblies published in DevExpress.XAF.Modules namespace will also be deleted.

Do you have any other assemblies matching this filter?

**Comment by softkey87** [comment]
I'm sorry, I think I was not clear enough. The two lines I was reffering to are the one from the file ApplicationBuilder.cs

In this file, you added these lines:
`var application = ApplicationHelper.Instance.Application;
 ApplicationHelper.Instance.Initialize(application);`

But it seems to cause a nullreference when running the Quartz server

**Comment by apobekiaris** [comment]
forgot to label this and the bot won't notify you. But the latest nightly channels provide a fix for this issue.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.13](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [ApplicationBuilder throws when used with external application #298](https://github.com/eXpandFramework/lab/commit/4f0fbeb734bd55ea6f1daa9944a67fc50a075493) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by softkey87** [comment]
Hi Tolis, I confirm this is working properly. Thanks for all your work on eXpand
