### ISSUE TITLE
WorldCreator generated code

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#299]
Hi Tolis,
I have suggestion for worldcreator assemblybuilder.

In this version it's selecting all code from persistent* tables. I have 300+ persistent class and attributes
and every client requesting for generated code.
I suggest when persistentassemblyinfo is saved, update generatedCode field and when application is started it should only request for this query result "select generatedcode from persistentassemblyinfo " and you can change it when revisionNumber is updated.

**Comment by apobekiaris** [comment]
Hi

I will research how to we can improve performance  and update you again

**Comment by apobekiaris** [comment]
I am afraid this is not a high priority issue  and at the moment I am out of resources. Maybe its possible to further partition your domain in separate assemblies so you can work around it.

**Comment by apobekiaris** [comment]
Looking again at this case I see in the source code the `NeedsCompilation` method.

https://github.com/eXpandFramework/eXpand/blob/976fa35e4af21dfc77f22e61be7902f4f4dac1c8/Xpand/Xpand.ExpressApp.Modules/WorldCreator/System/AssemblyManager.cs#L49-L58

which is called before the GenerateCode method, I also verified that the method is never called for existing assemblyInfos.

So I am not sure where is your performance problem?

**Comment by apobekiaris** [comment]
there is only one time compilation however it will as you say query all objects every time (for each client)

this situation is improved in next minor as you suggested.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.502.01](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [WorldCreator improve load speed when many clients #299](https://github.com/eXpandFramework/lab/commit/09ae7d25df5650adee9927289ae381d5baae4d13) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by skybluex3** [comment]
hi @apobekiaris  GeneratedCode field should be nvarchar(max)

**Comment by apobekiaris** [comment]
byte?? why? is for sure non human friendly so it's hard for someone to take the db content and try to compile them for debugging purposes

**Comment by expand** [comment]
Installer lab build [18.2.501.11](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [WorldCreator GeneratedCode Db Column Size should be max #299](https://github.com/eXpandFramework/lab/commit/aff0881ebc91f7ff477cc8815b1f6e100a53a02c) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by skybluex3** [comment]
Thanks

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
