### ISSUE TITLE
Rename DevExpress.XAF.Packages namespace to Xpand.XAF

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#300]
Repository is also renamed https://github.com/eXpandFramework/XAF

**Comment by apobekiaris** [comment]
[Switch to XAF namespace #300](https://github.com/eXpandFramework/XAF/commit/6514710a30deb15bb546c4b6e67eb652a6823020) relates to this task. Please update your nuget packages to version and test if the problem is gone.
 To access the lab XAF packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

**Comment by apobekiaris** [comment]
[Switch to XAF namespace #300](https://github.com/eXpandFramework/XAF/commit/76e307ee628dba9df5296c00761e39cb1cb7c32d) relates to this task. Please update your nuget packages to version and test if the problem is gone.
 To access the lab XAF packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.13](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Update issue templates

#300](https://github.com/eXpandFramework/lab/commit/d2b24ec439fe4c57e519bb8d420bcffa595d0405),[Update issue templates

#300](https://github.com/eXpandFramework/lab/commit/8d8b156302dd753677974781005e46d8b4cfe82a),[Update issue templates

#300](https://github.com/eXpandFramework/lab/commit/bb4df11ec0c69b255345c71c6da1b3dcf0b4b92b),[Update issue templates

#300](https://github.com/eXpandFramework/lab/commit/292379f9782c1f4b54f11ed7aefdeabd58fcaa5d),[Update issue templates

Switch to XAF #300](https://github.com/eXpandFramework/lab/commit/a64df641f0079c2ae60218a7deec28cba8a1c48c),[Update issue templates

#300](https://github.com/eXpandFramework/lab/commit/f0b01bcf8e241ece2f60bfa1a901b17df5575f73),[Update issue templates

#300](https://github.com/eXpandFramework/lab/commit/c0ebf8e8f5e1460de3731d87e800bc0a40f835d5) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by isatahiri** [comment]
So this is the reason i  do not find the Devexpress.xaf.* in the Expand.DLL ?  (version 18.2.501)

They are replaced ?  If so by what because i do not find any Xpand.XAF in the Expand.DLL

![image](https://user-images.githubusercontent.com/41955268/51994455-16181880-24b1-11e9-8326-152ea1316100.png)

Many thanks
ISA

**Comment by isatahiri** [comment]
euhh actually it is wrong : in the Expand.DLL there is and Xpand.XAF.ModelViewInheritance. 

This is with what we should replace right ? 

BR
ISA

**Comment by apobekiaris** [comment]
although they should also be in th Xpand.Dll (i will chekc on this), they now belong and distributed separately as part of the eXpandFramework/XAF project. If you wish to install them separately you need to:
```ps1
Install-Package Xpand.XAF.Modules.ModelViewInheritance
```

**Comment by apobekiaris** [comment]
take a moment to go through the XAF project ReadMe files to understand what is it about 

https://github.com/eXpandFramework/XAF

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
