### ISSUE TITLE
Avoid binding to DevExpress Versioning 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#301]
**Is your feature request related to a problem? Please describe.**
It should be possible to create module that do not depend in DX Version. ModelViewinheritance is a good match as it uses core code that will not break through major versions

**Describe the solution you'd like**
1. I do not want to upgrade ModelViewInheritance again! 
1. I want to use the latest version in my old DX project without having to upgrade DX assemblies.

**Describe alternatives you've considered**
```ps1
Install-Package Xpand.VersionConverter
```
Will add msbuild targets that will patch the dxversions on each `AfterBuild`. Module consumer does not need to do any further action for having the module work with the next DX major where assembly names will change to 19.1

**Comment by apobekiaris** [comment]
[Avoid binding to DevExpress Versioning #301](https://github.com/eXpandFramework/XAF/commit/e8b5e98e57bc37b83f6ebc443925d301fed817e8) relates to this task. Please update your nuget packages to version and test if the problem is gone.
 To access the lab XAF packages you need to add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

**Comment by skybluex3** [comment]
hi, should i need install all projects? or only main module

**Comment by apobekiaris** [comment]
your question is not clear, you should use only the XAF packages you need. Not that this post is about the [XAF](https://github.com/eXpandFramework/XAF) repository which in the future will have packages that are not included in [eXpand](https://github.com/eXpandFramework/expand) repository.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by apobekiaris** [comment]
#339

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
