### ISSUE TITLE
WC and other modules

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#302]
Hi tolis,
Again me and threadSafeLayer

I did open WebApplication from different two browsers. After I clicked login buton at the same time.
And i get always that;
`

Reentrancy or cross thread operation detected. Use ThreadSafeDataLayer or find the cause of the cross thread access to the SimpleDataLayer instance from your code. To suppress this exception, set DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true
System.InvalidOperationException
Reentrancy or cross thread operation detected. Use ThreadSafeDataLayer or find the cause of the cross thread access to the SimpleDataLayer instance from your code. To suppress this exception, set DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true
   at: ManageMind.Web.Global.<>c.<InjectLog>b__8_0(Object sender, FirstChanceExceptionEventArgs e)
   at: DevExpress.Xpo.SimpleDataLayer.ReentrancyAndThreadSafetyChecked[T](Func`1 action)
   at: DevExpress.Xpo.SimpleDataLayer.OnClassInfoChanged(Object sender, ClassInfoEventArgs e)
   at: DevExpress.Xpo.Metadata.ClassInfoEventHandler.Invoke(Object sender, ClassInfoEventArgs e)
   at: DevExpress.Xpo.Metadata.XPDictionary.TriggerClassInfoChanged(XPClassInfo changedClassInfo)
   at: DevExpress.Xpo.Metadata.XPClassInfo.DropCache()
   at: DevExpress.Xpo.Metadata.ReflectionClassInfo.DropCache()
   at: DevExpress.Xpo.Metadata.ReflectionClassInfo.AddMember(XPMemberInfo newMember)
   at: DevExpress.Xpo.Metadata.XPCustomMemberInfo..ctor(XPClassInfo owner, String propertyName, Type propertyType, XPClassInfo referenceType, Boolean nonPersistent, Boolean nonPublic)
   at: Xpand.Persistent.Base.Xpo.IXPSimpleObjectExtensions.CreateCollection(XPClassInfo classInfo, String propertyName, Type elementType, String criteria, Attribute[] attributes)
   at: Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateMemberInfo(IModelMemberEx modelMemberEx, XPClassInfo xpClassInfo)
   at: Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateXpandCustomMemberInfo(IModelMemberEx modelMemberEx, XPObjectSpace objectSpace)
   at: Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateRuntimeMembers(IModelApplication model)
   at: Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.LoadModels()
   at: Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.OnUserDifferencesLoaded(Object sender, EventArgs eventArgs)
   at: System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at: DevExpress.ExpressApp.XafApplication.LoadUserDifferences()
   at: DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   at: DevExpress.ExpressApp.XafApplication.showLogonAction_OnExecute(Object sender, PopupWindowShowActionExecuteEventArgs args)
   at: DevExpress.ExpressApp.Actions.PopupWindowShowAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at: DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
   at: DevExpress.ExpressApp.Actions.PopupWindowShowAction.DoExecute(Window window)
   at: DevExpress.ExpressApp.Actions.PopupWindowShowAction.DialogController_Accepting(Object sender, DialogControllerAcceptingEventArgs e)
   at: DevExpress.ExpressApp.SystemModule.DialogController.Accept(SimpleActionExecuteEventArgs args)
   at: DevExpress.ExpressApp.SystemModule.DialogController.acceptAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   at: DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at: DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
   at: DevExpress.ExpressApp.Actions.SimpleAction.DoExecute()
   at: DevExpress.ExpressApp.Web.Templates.ActionContainers.Menu.SimpleActionMenuActionItem.ProcessAction()
   at: DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder.DevExpress.ExpressApp.Web.Templates.IXafCallbackHandler.ProcessAction(String parameter)
   at: DevExpress.ExpressApp.Web.Templates.XafCallbackManager.ProcessAction(String parameter)
   at: DevExpress.ExpressApp.Web.Templates.XafCallbackManager.callbackControl_Callback(Object source, CallbackEventArgs e)
   at: DevExpress.Web.ASPxCallback.OnCallback(CallbackEventArgs e)
   at: DevExpress.Web.ASPxCallback.RaiseCallbackEvent(String eventArgument)
   at: DevExpress.Web.ASPxWebControl.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at: System.Web.UI.Page.PrepareCallback(String callbackControlID)
   at: System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at: System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at: System.Web.UI.Page.ProcessRequest()
   at: System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   at: System.Web.UI.Page.ProcessRequest(HttpContext context)
   at: LoginPage.ProcessRequest(HttpContext context)
   at: ASP.login_aspx.ProcessRequest(HttpContext context)
   at: System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at: System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at: System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
   at: System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
   at: System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)
   at: System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
   at: System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   at: System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   at: System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
   at: System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   at: System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)

`

**Comment by apobekiaris** [comment]
posting like this does not help much, just bad quality posts that have no value whatsoever

Please try to sample me with details on what you are trying to do.

>If i use (Static) Session.Query() and if i do that request at the same time on web i got this Reentary and cross thread

this makes me understand that you use Static Session somewhere and u share it? it will result in a cross thread then. Sshare the ThreadSafeDatalayer and in each Thread create a new session with it

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
