### ISSUE TITLE
Web Dashboard: cannot open the dashboard viewer

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#303]
**Describe the bug**
Clicking on existing dashboard fails to open the viewer

**To Reproduce**
Sample:
https://www.dropbox.com/s/2jqv2o47kt88dmy/XpandTesterDash.zip?dl=0

Run win project to create new dashboard (in my case, created a simple dashboard for Domain Object1 datasource with a chart on it)
![image](https://user-images.githubusercontent.com/234025/51307353-26a7a800-1a48-11e9-84b8-43c262ff8d28.png)
Run web project and click on new dashboard.
Result: does not show and does not throw any errors.
Same result when trying to create a dashboard on the web and run the designer

**Comment by vimarx** [comment]
any news on this issue?

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
