### ISSUE TITLE
DevExpress HintPath should point to Xpand.Dll folder

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#305]
**Describe the bug**
Xpand and all assemblies which are not published in nuget should be in Xpand.dll

**Expected behavior**
The build must use the package source to download and flatten nugets in the XPand.Dll similar to the XAF project

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.13](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Support Update #305](https://github.com/eXpandFramework/lab/commit/6e9a4d37703712ee201b56ec2353f36a19f4eccc),[DevExpress HintPath should point to Xpand.Dll folder #305](https://github.com/eXpandFramework/lab/commit/6e1dcd360bfea7fce9c7f957c8c4f518caa3e8dc),[DevExpress HintPath should point to Xpand.Dll folder #305](https://github.com/eXpandFramework/lab/commit/0e1e2c5262eaa9c59df3feebeecc1244c9fb134e),[Support Update #305](https://github.com/eXpandFramework/lab/commit/bb3ffa8ae7ee32f34dbe821e662f98fa100dcb93),[DevExpress HintPath should point to Xpand.Dll folder #305](https://github.com/eXpandFramework/lab/commit/6a2ae13bb452198e8534d79ab93252d9d1eac373) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.17](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Support Update #305](https://github.com/eXpandFramework/lab/commit/b86867d3e348cd3a676c729fb351d14c0224500a) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
