### ISSUE TITLE
Clickonce deployment

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#306]
Hello Tolis,

Since some days we have some issues with clickonce : 
![image](https://user-images.githubusercontent.com/41955268/51531107-da3fdc00-1e3c-11e9-837f-6a0fce3b2927.png)

Honnestly i do not know where this comes from. 
Have you tryied to deploy a test app in clickonce since we use nuget. 
For info i'm using the version 18.2.403.0 with nuget only. 

Many thanks to let me know if you have any idea. 

BR
ISA

**Comment by isatahiri** [comment]
The app start manually from the build with the exe of course.

**Comment by apobekiaris** [comment]
have u tried to repro it with a sample? can you post the exact steps?

**Comment by apobekiaris** [comment]
if you using the latest lab nugets u might have security issues, next minor will fix them

**Comment by isatahiri** [comment]
I will check with a new app now and let you know asap. 
What is the minimum .net framework to have for expand ? still 4.5.2 ? 

BR
ISA

**Comment by apobekiaris** [comment]
nope we are 4.6.1

**Comment by isatahiri** [comment]
I did a sample without Expand and the clickonce worked. I added via nuget some modules : Workflow, statemachine and Excel Importer with dependecies and then i had the same message. I looked that we issue was around System.XML.Linq but i cannot confirm. 

So i decided to remove nugget module and go with the installer (still 18.2.403.0) The installation when well but the problem is that by tool box when i open the module does not show anymore the Expand controls. 

I created a sample project as well and i do not know what is going on.
 
I'm a bit lost so if you have any idea is welcome ? 
BR
ISA

**Comment by isatahiri** [comment]
Via the menu choose item in the Toolbox i could add the controls. And know they appear in dictionnary node.  : 
![image](https://user-images.githubusercontent.com/41955268/51552467-f65d7080-1e70-11e9-8348-6dac2bd97cd6.png)

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/Support/tree/fb19b4a6ab3606b86c0e6cb84dedec7deb9e90dd/ToolboxCreator

**Comment by isatahiri** [comment]
Hello,

I have this when i run the toolboxcreator : 
Xpand.ToolboxCreator.exe Information: 0 : WorkingDirectory=C:\Program Files (x86)\eXpandFramework\Xpand.Dll\
Xpand.ToolboxCreator.exe Information: 0 : WorkingDirectory=C:\Program Files (x86)\eXpandFramework\Xpand.Dll\
Xpand.ToolboxCreator.exe Information: 0 : WorkingDirectory=C:\Program Files (x86)\eXpandFramework\Xpand.DLL\
Xpand.ToolboxCreator.exe Information: 0 : WorkingDirectory=C:\Program Files (x86)\eXpandFramework\Xpand.DLL\
Xpand.ToolboxCreator.exe Information: 0 : WorkingDirectory=C:\Program Files (x86)\eXpandFramework\Xpand.DLL\
Xpand.ToolboxCreator.exe Information: 0 : WorkingDirectory=C:\Program Files (x86)\eXpandFramework\Xpand.DLL\

But it does not generate the tool box in VS.  But it is ok i could add them manually.

Note : By the way by using the installer and not the nuget, i could deploy in clickonce. 

BR
ISA
