### ISSUE TITLE
Please build Expand version 18.2.5

### ISSUE THREAD

**Issue by lekhanhky** [eXpandFramework/eXpand#307]
Please build Expand version 18.2.5, tks !

**Comment by apobekiaris** [comment]
is released already

**Comment by dimasrespect** [comment]
Is there any chance to see eXpand 18.2.6 in the nearest future? Thanks in advance!

**Comment by apobekiaris** [comment]
sorry about the delay feel free to ping us if somehow like now you learn about a new release before us.

**Comment by expand** [comment]
Installer lab build [18.2.501.12](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [18.2.600.0 #307](https://github.com/eXpandFramework/lab/commit/4bffe77dab2e339c36804a6569ec458d559a9aa2) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
the bot really speaks about 18.2.6 trust me on this :)

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
