### ISSUE TITLE
Object access layer

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#308]
Hi tolis,
I wanna change simple datalayer to threadSafeLayer but
Is there any way to use threadSafe layer with worldcreator and modeldifference modules?

**Comment by skybluex3** [comment]
1st question is can i set threadSafe true on creating objectspace?
2nd if i cant then can i create threadSafeLayer on CreateDefaultObjectSpaceProvider() func.
sample in attachment,

i created sessionhelper.cs and changed createDefaultObjectSpaceProvider

` protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs e) {


            e.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(new ConnectionStringDataStoreProvider(e.ConnectionString), true));
            e.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));

            var wcConnectionString = ConfigurationManager.ConnectionStrings["WorldCreatorConnectionString"];
            var wcProvider = (new Xpand.ExpressApp.WorldCreator.System.WorldCreatorObjectSpaceProvider(true, new ConnectionStringDataStoreProvider(wcConnectionString), XafTypesInfo.Instance));
            e.ObjectSpaceProviders.Add(wcProvider);

            SessionHelper.ConnectionString = e.ConnectionString;
            SessionHelper.MainSession =
                SessionHelper.GetNewUnitOfWork();
            SessionHelper.SessionWC = ((XPObjectSpace)wcProvider.CreateObjectSpace()).Session;

      

        }`

[WorldCreatorTester.zip](https://github.com/eXpandFramework/eXpand/files/2806306/WorldCreatorTester.zip)

**Comment by skybluex3** [comment]
Dictionary cannot be modified while it's being used by the ThreadSafeDataLayer. To avoid this exception, call the Session.CreateObjectTypeRecords method before using ThreadSafeDataLayer

**Comment by apobekiaris** [comment]
it looks like WC did not reset the thread safety, fixed it in next minor, also added the `MakeThreadSafe` ObjsectspaceProvider extension method. Let me know if you are ok.

**Comment by skybluex3** [comment]
Can i use this extension with runtime model members ?

**Comment by apobekiaris** [comment]
from this question is hard to tell where is the problem, be specific what you try to do

**Comment by apobekiaris** [comment]
Installer lab build [18.2.501.2](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Add MakeThreadSafe ObjectSpaceProvider extensions method #308](https://github.com/eXpandFramework/lab/commit/4182f990fb342c9a5803e43fc811469aaec03dfc) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by skybluex3** [comment]
Thanks tolis, i can use threadSafe to true for objectspace Provider. But i still cant use ThreadSafeDataLayer from sample project in SessionHelper.cs

so i tried to create new unitofWork on this way;

`public static UnitOfWork GetNewUnitOfWork() {
            return new UnitOfWork(DataLayer);
        }

        static volatile IDataLayer fDataLayer;
        static IDataLayer DataLayer {
            get {
                if (fDataLayer != null) return fDataLayer;
                lock (lockObject) {
                    if (fDataLayer == null) {
                        fDataLayer = GetDataLayer();
                    }
                }
                return fDataLayer;
            }
        }


        private static IDataLayer GetDataLayer() {
            var conn = XpoDefault.GetConnectionPoolString(ConnectionString
            );
            XPDictionary dict = new ReflectionDictionary();
            IDataStore store = XpoDefault.GetConnectionProvider(conn, AutoCreateOption.DatabaseAndSchema);
            dict.GetDataStoreSchema(System.Reflection.Assembly.GetExecutingAssembly());
            IDataLayer dl = new ThreadSafeDataLayer(dict, store);
            return dl;
        }`
but it gives me exception;
Dictionary cannot be modified while it's being used by the ThreadSafeDataLayer. To avoid this exception, call the Session.CreateObjectTypeRecords method before using ThreadSafeDataLayer. ClassInfo modified or created: 'Xpand.ExpressApp.WorldCreator.DBMapper.BusinessObjects.DBLogonObject'.

   konum: DevExpress.Xpo.ThreadSafeDataLayer.OnClassInfoChanged(Object sender, ClassInfoEventArgs e)
   konum: DevExpress.Xpo.Metadata.XPDictionary.TriggerClassInfoChanged(XPClassInfo changedClassInfo)
   konum: DevExpress.Xpo.Metadata.ReflectionDictionary.CreateClassInfo(Type classType)
   konum: DevExpress.Xpo.Metadata.ReflectionDictionary.ResolveClassInfoByType(Type classType)
   konum: DevExpress.Xpo.Metadata.ReflectionDictionary.QueryClassInfo(Type classType)
   konum: Xpand.ExpressApp.WorldCreator.System.WorldCreatorTypeInfoSource.ForceRegisterEntity(Type item) D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\WorldCreator\System\WorldCreatorTypeInfoSource.cs içinde: satır 55
   konum: Xpand.ExpressApp.WorldCreator.DBMapper.WorldCreatorDBMapperModule.Setup(ApplicationModulesManager moduleManager) D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\WorldCreator.DBMapper\Module.cs içinde: satır 22
   konum: DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()

**Comment by apobekiaris** [comment]
I am sorry without a sample cannot help much but the exception is clear 

**you modify the dictionary while in threadsafe layer**

the solution is to create the ObjectSpaceProvider in non thread safe mode then modify the dictionary then change the thread safe mode using the the extension method

**Comment by skybluex3** [comment]
Actually I tried on same project
https://github.com/eXpandFramework/eXpand/files/2806306/WorldCreatorTester.zip
Did you see  in webapplication.cs create default objectspace provider function?

**Comment by skybluex3** [comment]
Hi tolis again,
i cant check my existing project(only web). should i install Package Xpand.VersionConverter  formy all projects? and wc module compiled with 18.2.3 ?
because i got this exception
at: Xpand.ExpressApp.WorldCreator.System.WorldCreatorApplication.CheckCompatibility(XafApplication application, Func`3 func) 
   konum: DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
			----------------
			InnerException:

					Type:       FileLoadException
					Message:    'DevExpress.Xpo.v18.2, Version=18.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' cannot load file blabla. (HRESULT özel durum döndürdü: 0x80131040)
					Data:       0 entries
					Stack trace:

**Comment by skybluex3** [comment]
The association attribute cannot be used for member 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentTypeInfo.TypeAttributes' because class 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentAttributeInfo' is not persistent.

what does it mean?
