### ISSUE TITLE
XPandObjectSpaceProvider

### ISSUE THREAD

**Issue by WSB-UG** [eXpandFramework/eXpand#309]
Version 18.1.5

When I use the XPandObjectSpaceprovider always DataLockingInfo is set to locked.

_xpPandObjectSpaceProvider = New XpandObjectSpaceProvider(New MultiDataStoreProvider(args.ConnectionString), Security, false)

When I override than:

Public Class ProcessDataLockingInfoNoCheckController
    Inherits ProcessDataLockingInfoController

    Protected Overrides Sub ProcessDataLockingInfo(dataLockingInfo As DataLockingInfo, <Out> ByRef cancelAction As Boolean)
        cancelAction = False
'        MyBase.ProcessDataLockingInfo(dataLockingInfo, cancelAction)
    End Sub
End Class

It becomes totaly strange:

I can't update my changes, 
By checking the dml for update it has no Fields:

Update Anrede set where ID = 1

should be
Update Anrede Name = "Test" set where ID = 1

**Comment by apobekiaris** [comment]
so the question here is how to you use the XpandObjectSpaceProvider, happy to help if you provide a sample to repro the case.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
