### ISSUE TITLE
ClientSideSecurity=IntegratedMode - login fails

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#310]
Sample
https://www.dropbox.com/s/108xw5r6xw0b5jg/XpandTester%20%283%29.zip?dl=0
log
https://www.dropbox.com/s/2049dxiki43x7hy/xpandlog.txt?dl=0

Model.xafml in Win project contains ClientSideSecurity="IntegratedMode"
without it, application logs in normally

**Comment by apobekiaris** [comment]
while checking this case i noticed you still install the DevExpress.XAF.* assemblies. Do not use them anymore please replace with Xpand.XAF.Modules.*

**Comment by skybluex3** [comment]
what are differences between ui level and integrated mode ?

**Comment by expand** [comment]
Installer lab build [18.2.501.11](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Build-in XpandObjectSpaceProvider IntegratedMode fails #310](https://github.com/eXpandFramework/lab/commit/dcfbe28cfa0df5ae10845bd9066d09e1b0f4b797) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by emeyke** [comment]
Now i get this after loggin in

16.02.19 09:53:54.549	ExecuteNonQueryCommand: 'drop index iCombineOrder_ModelDifferenceObject on ModelDifferenceObject', silent=True
XpandTester.Win.exe Error: 0 : 16.02.19 09:53:54.672	================================================================================
The error occurred:

	Type:       SqlException
	Message:    Cannot drop the index 'ModelDifferenceObject.iCombineOrder_ModelDifferenceObject', because it does not exist or you do not have permission.
	
Same project, updated to 18.2.501.6
https://www.dropbox.com/s/xnxbjb9slyqpivp/XpandTester.zip?dl=0

**Comment by apobekiaris** [comment]
i cannot repro it 

I upgraded your solution to latest and tested fine.

**Comment by apobekiaris** [comment]
current version is 18.2.601.0

**Comment by emeyke** [comment]
So you are able to login with Admin? I am still getting it with 601

**Comment by emeyke** [comment]
log https://www.dropbox.com/s/2049dxiki43x7hy/xpandlog.txt?dl=0

**Comment by emeyke** [comment]
ok this worked on new database. will still test on existing more
