### ISSUE TITLE
Can not open Modeldesigner

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#313]
Hi,

after Update to 18.2.501 I can not open the Modeldesigner. The Error below, but 
Xpand.Persistent.BaseImpl, Xpand.Persistent.Base and the Devexpress-Equivalents are in the project and local copy.
Any idea?

29.01.19 15:18:19.897	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while initializing the 'Xpand.ExpressApp.Security.XpandSecurityModule' module: Xpand.Persistent.BaseImpl assembly not found. Please reference it in your front end project and set its Copy Local=true
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	----------------
	InnerException:

			Type:       FileNotFoundException
			Message:    Xpand.Persistent.BaseImpl assembly not found. Please reference it in your front end project and set its Copy Local=true
			Data:       0 entries
			Stack trace:

   bei Xpand.Persistent.Base.General.XpandModuleBase.LoadBaseImplAssembly() in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs:Zeile 362.
   bei Xpand.Persistent.Base.General.XpandModuleBase.get_BaseImplAssembly() in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs:Zeile 326.
   bei Xpand.ExpressApp.Security.XpandSecurityModule.Setup(ApplicationModulesManager moduleManager) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\Security\Module.cs:Zeile 64.
   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
			InnerException is null

**Comment by CWolffIF** [comment]
Hi,

I worked only with the NuGet Packages.
After installing the Version with the Installer it works. Maybe there are missing links in the NuGet Packages.

**Comment by apobekiaris** [comment]
I am not sorry why you think there is a problem here. You got an exception right?

> Xpand.Persistent.BaseImpl assembly not found. Please reference it in your front end project and set its Copy Local=true

did the problem persist after reference?

the install puts assemblies in the GAC thats how it located the BaseImpl

**Comment by CWolffIF** [comment]
Hi Tolis,

I only worked with the NuGet Packages.
- 18.2.404 everything works 
- Update to 18.2.501 the exception was thrown. I checked all references but the exception was still there.
- Install 18.2.501 with the installer (but left the NuGet Packages in the project): Everything works.

**Comment by CWolffIF** [comment]
I will try on an new machine.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
