### ISSUE TITLE
XpandLogonParameters

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#314]
Hi,

I have a problem with a difference in the release and debug version. In the debug version everything runs fine, in the release version the app did not start with an error.

I have no idea where to seek the error.

iXISXRM.Win.exe Error: 0 : 29.01.19 18:00:17.355	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Fehler beim Vergleichen von zwei Elementen im Array.
	Data:       0 entries
	Stack trace:

   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Comparison`1 comparison)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetChildrenForSerialization()
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.WriteToString(IModelNode modelNode, Int32 aspectIndex)
   bei DevExpress.ExpressApp.ModelCacheManager.Save(ModelApplicationBase model)
   bei DevExpress.ExpressApp.ApplicationModelManager.CreateUnchangeableLayer(ModelStoreBase[] modelDifferenceStores)
   bei DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
   bei DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   bei DevExpress.ExpressApp.Win.WinApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   bei DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters)
   bei DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.XafApplication.Setup()
   bei iXISXRM.Win.Program.Main() in C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Win\Program.cs:Zeile 102.
	----------------
	InnerException:

			Type:       DuplicateModelNodeIdException
			Message:    There is already a node with Id 'UserName'. The node: Application/Views/XpandLogonParameters_DetailView/Layout/Main/RootGroup/EditorsGroup/Editors/UserName. To avoid this error, analyze your custom code or XAFML model differences for possible duplicate nodes creation or follow the www.devexpress.com/kb=S19870 KB article, if you have several classes in different namespaces, but with the same name.
			Data:       0 entries
			Stack trace:

   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(ModelNode node)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(String id, Type type)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddClonedNode(ModelNode source, String id)
   bei DevExpress.ExpressApp.SystemModule.ConvertLayoutDiffsController.ConvertLayoutDiffs(IList`1 nodes)
   bei DevExpress.ExpressApp.SystemModule.SystemModule.<>c.<AddModelNodeValidators>b__9_0(IList`1 nodes)
   bei DevExpress.ExpressApp.Model.Core.ModelNodeInfo.UpdateNodes(IList`1 nodeLayers)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.UpdateNodeLayers(IList`1 nodeLayers, Boolean hasFirstLayer)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.PopulateMasterNodesForChildNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureMaster(ModelMultipleMasterStoreItem masterNodeItem)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.get_Master()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetMasterRecursive()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetModelValue(String name)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Boolean inThisLayer, Int32 aspectIndex)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   bei DevExpress.ExpressApp.Model.Core.SortChildNodesHelper.DoSortNodesByDefault(ModelNode node1, ModelNode node2)
   bei System.Array.FunctorComparer`1.Compare(T x, T y)
   bei System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
			InnerException is null

**Comment by CWolffIF** [comment]
Hi,

it seems to be a problem when generating the Cache. If I set
winApplication.EnableModelCache = false;
everything works.

**Comment by apobekiaris** [comment]
happy to help if you tell me how to repro it.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
