### ISSUE TITLE
Path to Xpand.DLL in Registry

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#316]
Hi,

after Installing eXpand and starting VS2017 the Xpand.dll can not be found. It is searched in the
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AssemblyFolders\Xpand

but the registry key is in 
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319\AssemblyFoldersEx\Xpand

If you create the 
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AssemblyFolders\Xpand
manually it works.

![registry](https://user-images.githubusercontent.com/43132306/51994387-ef59e200-24b0-11e9-86cd-a708e5c9c773.PNG)

**Comment by apobekiaris** [comment]
is this about 

https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand.Plugins/Xpand.VSIX/Wizard/ModuleManager.cs#L36

**Comment by CWolffIF** [comment]
Ah OK.

**Comment by expand** [comment]
Installer lab build [18.2.501.11](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Xpand.VSIX Wizard Xpand.Dll path is wrong #316](https://github.com/eXpandFramework/lab/commit/7a64d20a057f3261773d985ce396444073f0c0e7) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
this patch was wrong I will review this case again.

>after Installing eXpand and starting VS2017 the Xpand.dll can not be found
What do you mean by this? Who could not find the Xpand.Dll?

**Comment by apobekiaris** [comment]
actually this patch changed nothing as the installer will create keys in both AssemblyFolder and AssemblyFolderEx, so waiting until you post more details

**Comment by dimasrespect** [comment]
May be this helps:
The installer saves dll's path to:
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AssemblyFolders\Xpand`
but the ModuleManager looks for path in:
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AssemblyFoldersEx\Xpand` 
as it is changed in 7a64d20a057f3261773d985ce396444073f0c0e7 commit. I've installed Xpand first time on my PC, when I start VS, it shows following error:
![2019-02-17_17-17-37](https://user-images.githubusercontent.com/305138/52914320-02094f00-32d8-11e9-8cc3-1643421a3883.png)
I've created registry node manually and rerun VS, error disappears.

**Comment by apobekiaris** [comment]
test

**Comment by expand** [comment]
Installer lab build [18.2.600](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Revert "Xpand.VSIX Wizard Xpand.Dll path is wrong #316 #329"

This reverts commit 7a64d20a057f3261773d985ce396444073f0c0e7.](https://github.com/eXpandFramework/lab/commit/8a5cdb325a7f52e76b74acc1af7eb41f80d41afe) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
