### ISSUE TITLE
ExcelImport: app crashes if spreadsheet sheet name does not correspond to ExcelImport sheet name

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#317]
E.g. if ExcelImport.SheetName="Sheet1" and the file that is imported has a different sheet name, e.g. "Sheet".
Result: application crashes
Expected behaviour: throw error, do not attempt to import

**Comment by apobekiaris** [comment]
Installer lab build [18.2.501.4](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [ExcelImporter does not delegate exceptions to the UI and does not validate the SheetName before import #317](https://github.com/eXpandFramework/lab/commit/f7b4a3a3c0f9bda5745e7874cd558a1b36869032) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
