### ISSUE TITLE
WC & ModelDifference Module  and threadSafe

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#319]
Hi @apobekiaris 
I added modelDifferenceModule and modelDifferenceWindowsFormsModule on WorldCreatorTester project
After i open Application Settings and go to BOModel> XpandPermissionPolicyUser > OwnMembers, then i added 
Orphaned Collection type is Project (In WC assembly OneToMany) then restart the application

And try to click login button
and get the exception; Runtime members creation failed
`Dictionary cannot be modified while it's being used by the ThreadSafeDataLayer. To avoid this exception, call the Session.CreateObjectTypeRecords method before using ThreadSafeDataLayer. ClassInfo modified or created: 'Xpand.Persistent.BaseImpl.Security.XpandPermissionPolicyUser'.
`
in IXPSimpleObjectExtensions.cs / line 9

Sample is in attachment (I tried on winapplication & i changed createDefaultObjectSpaceProvider)

[WorldCreator.zip](https://github.com/eXpandFramework/eXpand/files/2827048/WorldCreator.zip)

**Comment by skybluex3** [comment]
and thats funny on callstack :)
Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder line 114
modelMemberEx.MemberInfo is null it throws nullreference :)

**Comment by skybluex3** [comment]
You can get same exception on Xpand FeatureCenter All projects with the edit WinApplication.cs to threadSafe = true
   ```
protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args) {
            args.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(new ConnectionStringDataStoreProvider(args.ConnectionString),true));
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider());
        }
```

**Comment by apobekiaris** [comment]
is there a reason you did not go for the `XpandObjectSpaceProvider`? worked in my tests

It overrides that dictionary modification check while all other locks are in place.

**Comment by skybluex3** [comment]
holy crap @apobekiaris  !

It worked! 
```
 protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs e){

            e.ObjectSpaceProviders.Add(new XpandObjectSpaceProvider(new DataStoreProvider(e.ConnectionString), Security, true));
            e.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));
        }
```

but i have another question :))

In web application devexpress has been updated new DataStoreProvider to  following code 
```
 private IXpoDataStoreProvider GetDataStoreProvider(string connectionString, System.Data.IDbConnection connection)
        {
            var application = System.Web.HttpContext.Current != null ? System.Web.HttpContext.Current.Application : null;
            IXpoDataStoreProvider dataStoreProvider;
            if (application?["DataStoreProvider"] != null)
            {
                dataStoreProvider = application["DataStoreProvider"] as IXpoDataStoreProvider;
            }
            else
            {
                dataStoreProvider = XPObjectSpaceProvider.GetDataStoreProvider(connectionString, connection, true);
                if (application != null)
                {
                    application["DataStoreProvider"] = dataStoreProvider;
                }
            }
            return dataStoreProvider;
        }
```
Will you change something ? Do i need set application DataStoreProvider ?

**Comment by apobekiaris** [comment]
the web application is setup appropriately 

https://github.com/eXpandFramework/eXpand/blob/976fa35e4af21dfc77f22e61be7902f4f4dac1c8/Demos/FeatureCenter/FeatureCenter.Web/ApplicationCode/WebApplication.cs#L82

this method just stores the dataStoreProvider in the HttpContext
.Current.Application dictionary, if you wish to improve the performance you should also do the same for the Xpand DataStore you used.

**Comment by apobekiaris** [comment]
from what I see the DataStoreProvider has build-in the caching

https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/DataStoreProvider.cs#L36-L42

can you try enable it by adding the AppSettings key `DataCache` with value `Client`

**Comment by skybluex3** [comment]
I wanna try but, i still can't open my current Web project , win application has openning but web throws exception System.IO.FileLoadException: ''DevExpress.Xpo.v18.2, Version=18.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'  cannot load file depencies.
I deleted all bin obj files and upgraded again again but same

**Comment by skybluex3** [comment]
Thanks #closed

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
