### ISSUE TITLE
Project Wizard Not Loading

### ISSUE THREAD

**Issue by tscott3** [eXpandFramework/eXpand#320]
I installed a fresh instance of expand 18.2.501 and I am unable to create a Xpand solution using the wizard. 

Here is the error message i received.

![xpandwizarderror](https://user-images.githubusercontent.com/5226304/52304082-6c74d380-2957-11e9-8669-e1a75b19e856.png)

Thanks

**Comment by apobekiaris** [comment]
it looks like the -1 Revision is causing many problems #312 #311, I will release an official to fix this. Until then feel free to use any lab build as they are versioned correctly. for example i tested this one https://dev.azure.com/expandDevOps/eXpandFramework/_build/results?buildId=786

**Comment by tscott3** [comment]
I successfully invoked the wizard using the 18.2.501.6 Lab build. Thank you.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
