### ISSUE TITLE
Cannot Open Model Editor Designer in 18.2.501

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#321]
When trying to use Xpand Model Editor
Error:
Unable to create an instance of the "Xpand.ExpressApp.SystemModule.XpandSystemModule" type.
Reason: "The type initializer for 'Xpand.ExpressApp.SystemModule.XpandSystemModule' threw an exception."

Any idea where to start ?

**Comment by apobekiaris** [comment]
Option 1: there should be a log in path
Option 2: you can enable break on error in VS  and it will break you in the exxact line so you can examine variables etc. To do this given you have the symbols in place (see https://github.com/eXpandFramework/eXpand/wiki/HowToDebug). You need also to enable Debug for the XpandModelEditor in Xpand.VSIX
![image](https://user-images.githubusercontent.com/159464/52422148-2efe7a80-2afe-11e9-9f4a-91c2fbf94428.png)

Next when you try to open the XpandModelEditor again it should disaply a messagebox stoping the application and allowing you to Debug/Attach to process XpandModelEditor. After attaching and having break on errors on you click on the messagebox so the app will continue and it will break on the exception.

**Comment by vimarx** [comment]
Sorry, it as my bad.
it was a missing flasterflect.dll, but I noticed that ModelEditor now it is launched from solution output dir, not the path specified in Xpand... Options... is that correct behavior?

Thanks

**Comment by apobekiaris** [comment]
here how it decides from where to get it

https://github.com/eXpandFramework/eXpand/blob/976fa35e4af21dfc77f22e61be7902f4f4dac1c8/Xpand.Plugins/Xpand.VSIX/ModelEditor/ModelEditorRunner.cs#L21-L34

**Comment by apobekiaris** [comment]
to debug do not forget to enable you VS/Options/Debugging/Enable source server support
