### ISSUE TITLE
File Attachment

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#323]
Hello,

Is it possible to easily customize the file attachment module. 
We would like to store attachment in  hard disk and create folder per record. 

Can this be done with the file attachment module ? 

BR
ISA

**Comment by apobekiaris** [comment]
in the Xpand FileAttachment you will find the Bo used in https://www.devexpress.com/Support/Center/Example/Details/E965/how-to-store-file-attachments-in-the-file-system-instead-of-the-database-xpo. 

However there are no configurable rules, you have to code your needs as in the example.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
