### ISSUE TITLE
Set full screen mode to dashboard inside xaf Web application

### ISSUE THREAD

**Issue by disteSp** [eXpandFramework/eXpand#324]
Hi,

I need to increase height of dashboard viewer based on client size in Xaf web application which used xpand dashboard module.
With a standard DevEx dashboard module I can do it javascript side with the following script:
`
function xafInitDashboardDesigner(s, e) {
    var designer = s;
    resizeDashboard(designer);
}
    function resizeDashboard(control) {
        control.SetHeight(window.innerHeight);
        window.onresize = function (event) {
            control.SetHeight(window.innerHeight);
        };
    }
`

Please can you show me the equivalent client side event for xpand dashboard?

Thanks

**Comment by apobekiaris** [comment]
from what I understand you use the server side component ClientSideEvents to assign javascript functions, So why can't you do the same with Xpand? Its the same Dashboard component after all. What have you tried and you fail?

**Comment by apobekiaris** [comment]
here a possible solution to your generic question :)

```cs
    public class Class1:ViewController {
        public Class1() {
            TargetViewId = DashboardDefinition.DashboardViewerDetailView;
        }

        protected override void OnViewControlsCreated() {
            base.OnViewControlsCreated();
            var asPxDashboard = ((DetailView) View).GetItems<DashboardViewEditorWeb>().First().Control;
        }
    }
```

**Comment by disteSp** [comment]
Thanks for the prompt replay. Ok with your example I get dashboard editor server side. How can I configure it in order to call a custom javascript function on client side event  load and resize?

**Comment by apobekiaris** [comment]
now I found your case https://www.devexpress.com/Support/Center/Question/Details/T715785/set-full-screen-mode-to-dashboard-inside-xaf-web-application, please mentioned such history next time.

give me some time as I am releasing 18.2.601 and I will review it again.

**Comment by apobekiaris** [comment]
in the meantime could you share why you prefer the Xpand Dashboard module instead of the native XAF Dashboard module?

**Comment by apobekiaris** [comment]
here the controller that can show the dashboard in a new view. It is included also in the next minor but you can use it /test it until then.

```cs
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.Actions;
using DevExpress.ExpressApp.Web;
using DevExpress.Persistent.Base;
using Xpand.ExpressApp.Dashboard.BusinessObjects;

namespace Xpand.ExpressApp.XtraDashboard.Web.Controllers {
    public class DisplayViewInNewTabController : ObjectViewController<DetailView, IDashboardDefinition> {
        public DisplayViewInNewTabController() {
            TargetViewId = DashboardDefinition.DashboardViewerDetailView;
            DisplayViewInNewTabControllerAction = new SimpleAction(this, "DisplayViewInNewTab", PredefinedCategory.View);
            DisplayViewInNewTabControllerAction.SetClientScript($"window.open('{WebApplication.NoHeaderPopupWindowTemplatePage}'+ window.location.hash,'_blank');", false);
            DisplayViewInNewTabControllerAction.Caption = "Show view in a separate tab";
            DisplayViewInNewTabControllerAction.Active["SupportTabs"] = WebApplication.EnableMultipleBrowserTabsSupport;
            DisplayViewInNewTabControllerAction.ImageName = "Action_Fullscreen";
        }

        public SimpleAction DisplayViewInNewTabControllerAction { get; }
    }
}
```

**Comment by disteSp** [comment]
Thanks very much for the solution you provided. 

About you answer,  when we started this xaf project Xpand module was the only option provided for dashboard designer. From what I understood now DevEx include a dashboard module  derived from Xpan module. Is it correct?  Do you suggest a migration to DevEx dashboard module?

Thanks again,

Davide

**Comment by apobekiaris** [comment]
I have recently upgraded the module to use the same architecture as the build-in one, so hopefully you can use it for long time while being able to consult the same docs. However certain features/new like this one are integrated per demand. Eventually the two modules will be merged automatically, but my schedule it too busy to predict when.

**Comment by disteSp** [comment]
Hi,

Our customers really appreciate the "show dashboard in new tab functionality". They asked us if a similar behavior could be implemented also for the single graph of the dashboard. It can be useful with tablet or smartphone. See the image attached:
![showinnewtabgraphs](https://user-images.githubusercontent.com/40351623/53239821-4e200f00-369d-11e9-9632-027f08d19029.png)

Is it a similar functionality feasible? Are charts controls part of Xpand of DevEx library?

Thanks in advice

**Comment by apobekiaris** [comment]
test

**Comment by expand** [comment]
Installer lab build [18.2.600](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Dashboard viewere add FullScreen support  #324](https://github.com/eXpandFramework/lab/commit/fd508c3ab0abc1fd12ec51e87ac69513bccdecc7) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by apobekiaris** [comment]
so to understand what you want is to use the FullScreenMode action and show the related dashboard item in a new tab? 

is this possible with the native Dashboard module?

**Comment by disteSp** [comment]
Yes I would like to add the  "show in new tab" action to all widgets of the dashboard.
I didn't find in native Dashboard module anything in official doc to enable this feature.

I think it requires to add a new action in model.

**Comment by apobekiaris** [comment]
I discussed the case with the dashboard team and they they told me that since the [Mobile-Layout](https://docs.devexpress.com/Dashboard/119662/creating-the-designer-and-viewer-applications/web-dashboard/mobile-layout) is enabled (i doubled checked) it should work by default.

what happens when you click the fullscreen actions from a mobile client while you are viewing a dashboard of course and not editing?

**Comment by apobekiaris** [comment]
in my tests It looks like defaulting to MobileLayoutMode.Always produces the desired results as it occupies the full page (including navigation). The next minor change the default layout to Always. Try it and let me know please.

**Comment by apobekiaris** [comment]
the bot will provide the downloads in a bit

**Comment by expand** [comment]
Installer lab build [18.2.600](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Dashboard MobileLayoutEnabled model option and default to Always #324](https://github.com/eXpandFramework/lab/commit/f9239d0e99f9d9302e91b97114f0b225eade9ba7) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
