### ISSUE TITLE
About XpandSessions & Sessions

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#325]
Hi Tolis,
I'm asking because i don't know how sessions works. I Have helper class example; and when i need session i get it with new one with this way;
```
  public static Xpand.Xpo.XpandUnitOfWork GetNewSession()
        {
           
            return new Xpand.Xpo.XpandUnitOfWork();
        }
```
Sometimes i checking how many active connections i have on SQL Server with this query
```

SELECT 
    DB_NAME(dbid) as DBName, 
    COUNT(dbid) as NumberOfConnections,
    loginame as LoginName
FROM
    sys.sysprocesses
WHERE 
    dbid > 0
GROUP BY 
    dbid, loginame;
```
and i creating new sessions then i checking that active connections, that connections are didn't disconnected. Should i dispose them manually? Or shouldn't i use Static sessions ?

**Comment by apobekiaris** [comment]
u should not use Session at all why don't you use `Application.CreateObjectSpace()` ?

and you should dispose the session or uow oor ospace after you use them immediately. Create session, do work, dispose session. Only the `datalayer ` has a costly construction and can be shared through static properties if in thread safe mode.

That configuration is flawless in demanding multi threading apps.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
