### ISSUE TITLE
Wrong tooltip for login action when anonymous

### ISSUE THREAD

**Issue by dimasrespect** [eXpandFramework/eXpand#326]
**Describe the bug**
When using anonymous authentication standard XAF LogOff action is used in web UI as Login action. The caption shows correctly, but the tooltip shows "Log Off". I've attached a screenshot.

**To Reproduce**
Enable anonymous authentication and run web application as anonymous user.
Click "My Account" and move mouse cursor to "Login"

**Expected behavior**
There are should be one more localizable parameter "LoginActionTooltip" an application model at "Options\Athentication\AnonymousAuthentication" that will allow us to configure the tooltip.

**Screenshots**
![2019-02-17_22-00-38](https://user-images.githubusercontent.com/305138/52917986-912b5c80-3302-11e9-8680-cbad2ef55a8e.png)

**Comment by expand** [comment]
Installer lab build [18.2.600.5](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [add tooltip parameter for login action when anonymous  #326](https://github.com/eXpandFramework/lab/commit/b3cafcb27abffed1aa01c3a20676fe6b9372d492) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
