### ISSUE TITLE
Visual Studio 2019 - Extension is not installable

### ISSUE THREAD

**Issue by uniqueitmail** [eXpandFramework/eXpand#328]
### **Visual Studio Enterprise 2019**
This Extension is not installable on any currently installed products **(WARNING)** [...]

**Visual Studio Enterprise New Integration/Upgradation**
_### **Facing Critical Problem**_
17-Feb-19 7:59:03 PM - Microsoft VSIX Installer
17-Feb-19 7:59:03 PM - -------------------------------------------
17-Feb-19 7:59:03 PM - vsixinstaller.exe version:
17-Feb-19 7:59:03 PM - 16.0.298
17-Feb-19 7:59:03 PM - -------------------------------------------
17-Feb-19 7:59:03 PM - Command line parameters:
17-Feb-19 7:59:03 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\Extended Access\eXpand 18.2.601.0\Xpand.VSIX-18.2.601.0.vsix
17-Feb-19 7:59:03 PM - -------------------------------------------
17-Feb-19 7:59:03 PM - Microsoft VSIX Installer
17-Feb-19 7:59:03 PM - -------------------------------------------
17-Feb-19 7:59:07 PM - Initializing Install...
17-Feb-19 7:59:07 PM - Extension Details...
17-Feb-19 7:59:07 PM - 	Identifier         : Xpand.VSIX.Apostolis Bekiaris.4ab62fb3-4108-4b4d-9f45-8a265487d3dc
17-Feb-19 7:59:07 PM - 	Name               : Xpand.VSIX
17-Feb-19 7:59:07 PM - 	Author             : Apostolis Bekiaris
17-Feb-19 7:59:07 PM - 	Version            : 1.0
17-Feb-19 7:59:07 PM - 	Description        : VSIX Project.
17-Feb-19 7:59:07 PM - 	Locale             : en-US
17-Feb-19 7:59:07 PM - 	MoreInfoURL        : 
17-Feb-19 7:59:07 PM - 	InstalledByMSI     : False
17-Feb-19 7:59:07 PM - 	SupportedFrameworkVersionRange : [4.5,)
17-Feb-19 7:59:07 PM - 
17-Feb-19 7:59:07 PM - 	SignatureState     : Unsigned
17-Feb-19 7:59:07 PM - 	Supported Products : 
17-Feb-19 7:59:07 PM - 		Microsoft.VisualStudio.Community
17-Feb-19 7:59:07 PM - 			Version : [14.0,15.0)
17-Feb-19 7:59:07 PM - 		Microsoft.VisualStudio.Community
17-Feb-19 7:59:07 PM - 			Version : [15.0,16.0)
17-Feb-19 7:59:07 PM - 		Microsoft.VisualStudio.Pro
17-Feb-19 7:59:07 PM - 			Version : [14.0,15.0)
17-Feb-19 7:59:07 PM - 		Microsoft.VisualStudio.Pro
17-Feb-19 7:59:07 PM - 			Version : [15.0,16.0)
17-Feb-19 7:59:07 PM - 		Microsoft.VisualStudio.Enterprise
17-Feb-19 7:59:07 PM - 			Version : [14.0,15.0)
17-Feb-19 7:59:07 PM - 		Microsoft.VisualStudio.Enterprise
17-Feb-19 7:59:07 PM - 			Version : [15.0,16.0)
17-Feb-19 7:59:07 PM - 
17-Feb-19 7:59:07 PM - 	References         : 
17-Feb-19 7:59:07 PM - 		-------------------------------------------------------
17-Feb-19 7:59:07 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
17-Feb-19 7:59:07 PM - 		Name         : Visual Studio MPF 14.0
17-Feb-19 7:59:07 PM - 		Version      : [14.0]
17-Feb-19 7:59:07 PM - 		MoreInfoURL  : 
17-Feb-19 7:59:07 PM - 		Nested       : No
17-Feb-19 7:59:07 PM - 
17-Feb-19 7:59:07 PM - 	Prerequisites      : 
17-Feb-19 7:59:07 PM - 		-------------------------------------------------------
17-Feb-19 7:59:07 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
17-Feb-19 7:59:07 PM - 		Name         : Visual Studio core editor
17-Feb-19 7:59:07 PM - 		Version      : [15.0,16.0)
17-Feb-19 7:59:07 PM - 
17-Feb-19 7:59:07 PM - Signature Details...
17-Feb-19 7:59:07 PM - 	Extension is not signed.
17-Feb-19 7:59:07 PM - 
17-Feb-19 7:59:07 PM - Searching for applicable products...
17-Feb-19 7:59:07 PM - Found installed product - Global Location
17-Feb-19 7:59:07 PM - Found installed product - ssms
17-Feb-19 7:59:07 PM - Found installed product - Visual Studio Enterprise 2019 Preview
17-Feb-19 7:59:07 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by apobekiaris** [comment]
no work done for VS 2019 yet

**Comment by uniqueitmail** [comment]
Request to upgraded as soon as possible, Visual Studio Enterprise 2019 is available Preview & April 2, 2019 Launch it.
Thanks.

**Comment by uniqueitmail** [comment]
**_Request to release Integrated New & Avoid Bugs for VS2019 worked well._**
Please sign...ASAP

**Comment by apobekiaris** [comment]
I was able to repro the case but at the moment there are works in the CI pipe and are of high priority cause without CI nothing works.

I will address the case as soon as CI is functional.

**Comment by expand** [comment]
Installer lab build [18.2.601.21](https://github.com/eXpandFramework/lab/releases/18.2.601.21) includes commit [VSIX support for VS 2019 #328](https://github.com/eXpandFramework/153812905/commit/bc5d36429258f63cad76f06c5eb8f989a6158003) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Installer lab build [18.2.601.22](https://github.com/eXpandFramework/lab/releases/18.2.601.22) includes commit [VSIX support for VS 2019 #328](https://github.com/eXpandFramework/153812905/commit/98a08a6a6f71f303e33847823530f8907cd482f0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by uniqueitmail** [comment]
**Many many**

> ###  THANKS
@apobekiaris 
&
@expand 
_For Contribution***_
