### ISSUE TITLE
Visual Studio Enterprise 2017 - Xpand not found that check

### ISSUE THREAD

**Issue by uniqueitmail** [eXpandFramework/eXpand#329]
### **Visual Studio 2017 Enterprise - **(WARNING)****
HKLM\Software\Wow6432Node\Microsoft\.NetFramework\AssemblyFoldersEx\Xpand pointsto the Xpand.DLL directory

**Expected behavior**
Xpandpoints to the Xpand.DLL directory....

**### WarningScreenshots**
![warning -2019-02-19_122334](https://user-images.githubusercontent.com/16665892/52994348-73184600-3441-11e9-8300-22639bed1f3a.png)

![check](https://user-images.githubusercontent.com/16665892/52996834-e96c7680-3448-11e9-843d-7691e272a7ec.png)

**Comment by apobekiaris** [comment]
#316

**Comment by apobekiaris** [comment]
test

**Comment by expand** [comment]
Installer lab build [18.2.600](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [Revert "Xpand.VSIX Wizard Xpand.Dll path is wrong #316 #329"

This reverts commit 7a64d20a057f3261773d985ce396444073f0c0e7.](https://github.com/eXpandFramework/lab/commit/8a5cdb325a7f52e76b74acc1af7eb41f80d41afe) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
