### ISSUE TITLE
FilterableEnumPropertyEditor Not Working

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#330]
Using systemTester, FilternameEnumPropertyEditor fails to open

**To Reproduce**
![2019-02-21_16-56-40](https://user-images.githubusercontent.com/226800/53197692-73f3d800-35f9-11e9-87f4-00dcade84a72.gif)

And also in my application Enum filter is applied ok, but fail to save editor value
![2019-02-21_17-11-10](https://user-images.githubusercontent.com/226800/53198533-60e20780-35fb-11e9-9258-9dae3f551251.gif)

**Comment by expand** [comment]
Installer lab build [18.2.600](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [FilterableEnumPropertyEditor Not Working #330](https://github.com/eXpandFramework/lab/commit/daf5773d4a3653a66b0d22a855af6aac2a05db8a) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by vimarx** [comment]
Hi Tolis, I tried to download the corresponding artifact from DevOps but faced this exception

{"$id":"1","innerException":null,"message":"TF400813: The user 'Windows Live ID\\gustavo@vimarx.com.ar' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}

**Comment by apobekiaris** [comment]
thanks for the heads up, I can also failed to download with my personal account. 

I do not see any easy work around here as from what I understand I cannot set anonymous permissions in devops. I will integrate probably Gihub lab repository for nightly releases. In the mean time your option is to build the lab repo your self or to use the nuget from https://xpandnugetserver.azurewebsites.net/

**Comment by vimarx** [comment]
Hi @apobekiaris , The Installer lab build 18.2.600 includes commit FilterableEnumPropertyEditor Not Working #330, do not solve the problem, attached failing sample solution, the drop down is filtered correct but the editor do not show anything 
[Solution3.zip](https://github.com/eXpandFramework/eXpand/files/2923540/Solution3.zip)

**Comment by vimarx** [comment]
Also in a web solution, the editor seems to be working, but it incorrectly permits an initial wrong value as shown in the following screencast
![2019-03-03_16-20-50](https://user-images.githubusercontent.com/226800/53700355-110bf900-3dd0-11e9-90ed-55790f45523b.gif)

**Comment by apobekiaris** [comment]
In the next minor the FilterbaleEnumPropertyEditor has been merged with the EnumPropertyEditor ans ASPxEnumPropertyEditor. they both default editors for enum types. I also supported an attributed based filtering like.

```cs
    [EnumFilter(nameof(FilteredStatus),EnumFilterMode.Remove, StatusColor.Blue,nameof(Switch)+"=true")]
    public class FilterableEnumPropertyEditorObject : BaseObject {
        [DataSourceProperty("InstanceStatusDataSource")]
        public StatusColor? FilteredStatus {
            get => _filteredStatus;
            set => SetPropertyValue("FilteredStatus", ref _filteredStatus, value);
        }

        [ImmediatePostData]
        public bool Switch {
            get => _switch;
            set {
```
let me know how it works.

**Comment by Paramethod** [comment]
+1 for the added criteria!

**Comment by apobekiaris** [comment]
your idea rocks Alex thanks for sharing!

**Comment by expand** [comment]
Installer lab build [18.2.601.11](https://github.com/eXpandFramework/lab/releases/18.2.601.11) includes commit [Simplify EnumPropertyEditors and support additional attribute based filtering #330](https://github.com/eXpandFramework/lab/commit/ba1667db1c86dec222007caf2ffd5ed4667881a0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Installer lab build [18.2.601.16](https://github.com/eXpandFramework/lab/releases/18.2.601.16) includes commit [EnumPropertyEditor throws on ObjectSpaceOnCommitted #330 #341](https://github.com/eXpandFramework/lab/commit/37b48276f044f91d940f3b94b9483b994ae3d0f0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Installer lab build [18.2.601.18](https://github.com/eXpandFramework/lab/releases/18.2.601.18) includes commit [EnumPropertyEditor throws on ObjectSpaceOnCommitted #330 #341](https://github.com/eXpandFramework/lab/commit/560cfc9184d3cf492f2991e7068488467cb2dc64) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
