### ISSUE TITLE
ExcelImport: ImportAction and  ImportExtension.Caption() not Localized

### ISSUE THREAD

**Issue by GannebalBarka** [eXpandFramework/eXpand#331]
Work problem:
there is no mapping of columns in the settings
Xpand.ExpressApp.ExcelImporter.Services.IsMatch compared no localized and localized values in new thread, because ValueManager not contains BOmodel

Reproduce:
you have external language, e.g. ru
you web app start in single language mode: ru

function: Xpand.ExpressApp.ExcelImporter.Controllers.ImportActionOnExecute
_step one (good work):_
line: var importParameters = ExcelImport.GetImportParameters();
run: CaptionHelper.GetMemberCaprion(<_HasLocalizedmember_>) == <_LocalizedCaprion_>
_step two (crazy work):_
line in Observable.Start async delegate
run: CaptionHelper.GetMemberCaprion(<_HasLocalizedmember_>) == <_NO_LocalizedCaprion_>

Desktop
 - OS: Windows 7
 - Browser Explorer10, Chrome
 - XAF 18.2.4, eXpand 18.2.404.0

Additional context
Referenced all XAF modules
Referenced eXpand:
- for Module 
-- external Security, Validation
-- internal (build in solution) ExcelImporter

- for Module.Web
-- external Security, Validation, Base, BaseImple
-- internal (build in solution) ExcelImporter.Web

- for Web
-- external Security, Validation, Base, BaseImple, ExpressApp, AdditionalViewControlsProvider, AdditionalViewControlsProvider.Web, Dashboard, Logic, Security.Web, Validation.Web, Web, XtraDashboard.Web, Utils, ModelViewInheritance, Xpo
-- internal (build in solution) ExcelImporter, ExcelImporter.Web

WebApplication implement of Xpand.ExpressApp.Web.XpandWebApplication

**Comment by apobekiaris** [comment]
thnks for reporting I will review and reply. 

In the meantime I am very interested in this comment:

>line in Observable.Start async delegate

so we speak about 
https://github.com/eXpandFramework/eXpand/blob/e90d395a476a0e5b3ac316c5677391523f3ac44b/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/Controllers/ExcelImportDetailViewController.cs#L110-L115

I agree that RX hides the technical, which can make the work look like crazy. However this me trying to play magician and guess what you really meant, or if there is actually a problem there.

Care to share more thoughts? Maybe there is space for improvement there.

**Comment by GannebalBarka** [comment]
I apologize, I did not express myself quite accurately.
I used a breakpoint before the function Observable.Start(async () =>{...} (step one) and inside it (step two) 
e.g. line 110: var space = Application.CreateObjectSpace(ExcelImport.GetType());
This example is described to demonstrate the wrong behavior. The error itself lies inside the import function.
Function: Xpand.ExpressApp.ExcelImporter.Services.GetImportToObject
line 68:
- importToTypeInfo.GetKeyMember() 
i see this inner call stack in source code
-- Xpand.ExpressApp.ExcelImporter.BusinessObjects.ExcelColumnMap.MemberInfo
--- Xpand.ExpressApp.ExcelImporter.BusinessObjects.ExcelColumnMap.FindMember
---- Xpand.ExpressApp.ExcelImporter.Services.ImportExtension.FindMember
----- Xpand.ExpressApp.ExcelImporter.Services.ImportExtension.IsMatch
------ CaptionHelper.GetMemberCaption(info) // Returns an invalid value (NO_LocalizedCaption).

At the moment, I decide whether to debug XAF, to understand how CaptionHalper works

**Comment by apobekiaris** [comment]
CaptionHelper has a static instance of the model thats it.

btw can you share your sample?

**Comment by GannebalBarka** [comment]
As for the import functions at the moment, I have added a function to select my own key field for the import object and reference books for attributes (necessary because the source files all have a strange format)
and is currently busy developing import hierarchical structures. hierarchy format:
- in one column by the pattern "nnn.nnn. ... .nnn"
- in two referring columns, ID and Parent

Be sure to share the development)

**Comment by GannebalBarka** [comment]
Текущий проект не могу отправить, но вот попробовать создать простой пример могу, скоро вышлю

**Comment by apobekiaris** [comment]
thnks and try to speak English :)

**Comment by GannebalBarka** [comment]
> thnks and try to speak English :)

Oh, sorry, earned :)

> I cannot send the current project, but I can try to create a simple example, I will send it out soon

**Comment by GannebalBarka** [comment]
I had an incident when creating an example of an error; (. I could easily reproduce Caption Helper's incapacity, but could not show that an error occurred (went through all the breackpoints and everything was OK). I can assume that the state described earlier is This is a rare case or my mistake. I'm sorry that I confused you (Nevertheless, I have put an example in which my revision is already there with manual adjustment of the key field, and judging by the debugging of the source code, it works! But does not save changes to the strategy Update and create

[CaptionHelperErrorSample.zip](https://github.com/eXpandFramework/eXpand/files/2900478/CaptionHelperErrorSample.zip)

**Comment by apobekiaris** [comment]
>Nevertheless, I have put an example in which my revision is already there with manual adjustment of the key field, and judging by the debugging of the source code, it works! But does not save changes to the strategy Update and create

you code should be very abstract judging from your words :). However as I said my resources are limited and I will appreciate some details on what to do with your sample and what you have changed and for what reason. No need for an essay just a basic outline please.

**Comment by GannebalBarka** [comment]
To save your time, I tested the Refresh mode and created it with the ExtselImport standard library.
Object name field Contract not updated, although I added the attribute [ExcelImportKey ("Code")] for this object

_namespace CaptionHelperErrorSample.Module.BusinessObjects
{
    [NavigationItem("Default")]
    [DefaultProperty("Name")]
    [ExcelImportKey("Code")]
    public class Contract : BaseObject
    { 
        public Contract(Session session)
            : base(session)
        {
        }
        [Size(255)]
        public string Code { get; set; }
        [Size(SizeAttribute.Unlimited)]
        public string Name { get; set; }
    }
}_

Ps
Regarding changes in source files:
- class ImportExtension
-- function GetImportToObject: Criteria of Key
-- function Import: custom Reference Key
- class ExcelImport
-- property GetKeyMember: add custom key property
- class ExcelColumnMapMemberTypeValue
-- property IsKeyMember, PropertyKeyMemberName, PropertyKeyMember
- class ExcelColumnMap
-- property IsKeyMember

Today, my working day has come to an end, until tomorrow and have a good evening)

**Comment by apobekiaris** [comment]
Thanks for the time authoring so many changes, however I noticed that you did not set the application language to Ru, once set I was able to map and import all 2 rows with success. Try it and let me know please.

![image](https://user-images.githubusercontent.com/159464/53343337-d3632800-3918-11e9-8cc4-158b9edb8078.png)

**Comment by GannebalBarka** [comment]
Unfortunately, I do not explain well, but I will always try.

Step 1:
Database is empty

Step 2:
Import - database is full

Step 3:
changing the value of one non-key field in the program

Step 3:
attempt to re-import in the "Update and create" method

Passing through the code in debug mode, I found that the changes occur correctly, but then they are not saved, although ObjectSpacw.IsModified == false after asynchronous saving
https://github.com/eXpandFramework/eXpand/blob/18.2/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/Controllers/ExcelImportDetailViewController.cs:114

P.S.
I decided to install Devekspress at home and make a branch with my own modifications to the githab

**Comment by apobekiaris** [comment]
i can reproduce the case even on Ru language, working on it as well.

>I decided to install Devekspress at home and make a branch with my own modifications to the githab
PR are welcome of course just try to be descriptive and short, if possible.

**Comment by apobekiaris** [comment]
>Passing through the code in debug mode, I found that the changes occur correctly, but then they are not saved, although ObjectSpacw.IsModified == false after asynchronous saving

this draws the attention to you bussiness object declarations which are wrong. With Xpo you need to use 

```cs
        public string Code{
            get => _code;
            set => SetPropertyValue(nameof(Code), ref _code, value);
        }
```

and not just automatic properties else IObjectSpace does not know that is modified.

**Comment by GannebalBarka** [comment]
When I checked, the ObjectSpace was changed to a string.
await ObjectSpace.WhenCommiting (). FirstAsync ();
after the line and next steps it was marked as unchanged, although nothing has changed in the database

When I can change the code and test it, I'll let you know
Thank you so much for your help.

**Comment by GannebalBarka** [comment]
Good afternoon!
I was finally able to get back to work!
Thank you, your comment about anonymous property helped me. However, I don’t quite understand why ObjectSpace at first knows that it is changed, and for asynchronous saving it forgets about changes ... But for now this does not prevent me from working)

P.S.
I almost finished the import, I hope the other day to fill it. Unfortunately, I have to develop it for version 18.2.4. Tell me how to transfer the changes to the project?

**Comment by apobekiaris** [comment]
>ObjectSpace at first knows that it is changed, and for asynchronous saving it forgets about changes

you somehow against the RX async implementation used, however I promise you it has nothing to do with async, it is a classic xpo question.

>Tell me how to transfer the changes to the project?

in english please :)

**Comment by GannebalBarka** [comment]
> in english please :)

I'll start my thought from afar:
- I have not yet shared my work on GitHub
- all the more relevant (hopefully) developments that are made in the outdated version

How do I see this for myself:
- I fork the 18.2.4 version
- making changes
- I make a commit
- I create Issues with the offer of the function and a link to my fork

I'm right?

**Comment by apobekiaris** [comment]
oh yes that can work, or even just post your commit in a related post and I could cherry pick no need to synchronize the universe every time, or feel free to discuss problems here, we will find a solution.

**Comment by GannebalBarka** [comment]
thank you very much!

**Comment by GannebalBarka** [comment]
Good day!

Recently, I have a lot of work. Because of this, the importer cannot be finished. At the moment, I have not implemented 2 more major functions. Also not yet engaged in optimization.

My question is: Can I create an example to evaluate the functionality and download it here?

Such a question arose because of the complicated interface and algorithms.

Thank!

**Comment by apobekiaris** [comment]
sure if it works I can evaluate and even integrate the ideas

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
