### ISSUE TITLE
FileDataPropertyEditor design time exception

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#332]
**Describe the bug**
System.NotImplementedException

Xpand.Persistent.Base.General.Model.VisibilityCalculators.EditorTypeVisibilityCalculator`2[[Xpand.ExpressApp.FileAttachment.Web.PropertyEditors.FileDataPropertyEditorController, Xpand.ExpressApp.FileAttachment.Web, Version=18.2.601.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958],[DevExpress.ExpressApp.Model.IModelDetailView, DevExpress.ExpressApp.v18.2, Version=18.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a]]

Xpand.Persistent.Base.General.Model.VisibilityCalculators.EditorTypeVisibilityCalculator`1.EditorType(IModelNode node)Xpand.Persistent.Base.General.Model.VisibilityCalculators.EditorTypeVisibilityCalculator`2.IsVisible(IModelNode node, String propertyName)DevExpress.ExpressApp.Model.FastModelEditorHelper.IsPropertyModelBrowsableVisible(ModelNode parentNode, String propertyName)DevExpress.ExpressApp.Win.Core.ModelEditor.ModelAttributesPropertyEditorControllerWin.CalculatePropertyVisible(ModelNode node, String propertyName)DevExpress.ExpressApp.Win.Core.ModelEditor.ModelAttributesPropertyEditorControllerWin.CollectCustomPropertyDescriptors(Object source, PropertyDescriptor propertyDescriptor, PropertyDescriptorCollection properties)DevExpress.ExpressApp.Win.Core.ModelEditor.ModelAttributesPropertyEditorControllerWin.propertyEditor_CustomPropertyDescriptors(Object sender, CustomPropertyDescriptorsEventArgs e)DevExpress.XtraVerticalGrid.PropertyGridControl.RaiseCustomPropertyDescriptors(CustomPropertyDescriptorsEventArgs e)DevExpress.XtraVerticalGrid.PropertyGridControl.DevExpress.XtraVerticalGrid.Data.IPropertyDescriptorService.GetProperties(Object source, ITypeDescriptorContext context, Attribute[] attributes)DevExpress.XtraVerticalGrid.Data.DescriptorContext.GetCachedProperties(Object source, Attribute[] attributes)

**To Reproduce**
With the ME navigate to an IFileData property while XpandFileAttachmentsWebModule is installed
**Expected behavior**
Not throw

**Comment by expand** [comment]
Installer lab build [](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [FileDataPropertyEditor design time exception #332](https://github.com/eXpandFramework/lab/commit/4deb3e7c2e42fb35067b6721188ab3ed178df719) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Installer lab build [18.2.600.20](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=18.2.600.20&view=results) includes commit [FileDataPropertyEditor design time exception #332](https://github.com/eXpandFramework/lab/commit/4deb3e7c2e42fb35067b6721188ab3ed178df719) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS
