### ISSUE TITLE
Notification and logon form

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#334]
**Describe the bug**
We have some issues reagarding the layout for the notification for (reminder) and loggon form. 
According the Devexpress, the issue comes from Xpand ExcelImporterWebModule and XpandSecurityModule modules. 
https://www.devexpress.com/Support/Center/Question/Details/T709197/reminder-notification-popup-in-web

Devexpress gave alternative but maybe we can improve somthing here. 

The postone is not visible in the reminder and the fields in loggon are smaller. 
[Ticket T709197.docx](https://github.com/eXpandFramework/eXpand/files/2915896/Ticket.T709197.docx)

**To Reproduce**
You can reproduce this in my solution : 
https://1drv.ms/f/s!Amh26IFxNEz6lNMbYslJFBZQmsa_uw

For the loggon form just start the app. 
For the reminder create appointment in calendar with reminder. 

BR
ISA

**Comment by apobekiaris** [comment]
thnks I was already informed about this case, give me some time please.

**Comment by apobekiaris** [comment]
Hi,

Both cases are resolved in the next minor, you might have to revert DevExpress support suggestions.

**Comment by expand** [comment]
Installer lab build [18.2.601.11](https://github.com/eXpandFramework/lab/releases/18.2.601.11) includes commit [XpandLayoutManager is initialized incorrectly #334](https://github.com/eXpandFramework/lab/commit/c6d8a2b829980627917854d9fd7d6f5e6c940586),[Login View items Relative size is too small #334](https://github.com/eXpandFramework/lab/commit/df81d06ce0b5e34b18f6384e3534e7089c15edbd) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by isatahiri** [comment]
Hello,

So now the LAB build are delivered only as source code ? Do we have to compile by ourself ? 

BR
ISA

**Comment by apobekiaris** [comment]
Hi,

I am sure not for long, sorry about this but CI is still in works. Feel free to post if you see inconsistencies.

**Comment by vimarx** [comment]
This issue should cover this layout problem?
![image](https://user-images.githubusercontent.com/226800/54147911-fa8a2100-4411-11e9-9628-f4e1868530ea.png)

**Comment by apobekiaris** [comment]
hmm i cannot tell, I guess the fastest way is too try the build

**Comment by isatahiri** [comment]
@vimarx  I haven't installed the last build yet ? So does it cover the layout problem that you mentionned ?

**Comment by isatahiri** [comment]
Hi the login form is OK. 
The notifications form has still a vertical scroller. 
![image](https://user-images.githubusercontent.com/41955268/54483105-9a9adc80-484e-11e9-8ae1-6abf09d476b3.png)

Is the scroll in your side too ? 

BR
ISA

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
