### ISSUE TITLE
Using SequenceGenerator with MemoryDataStoreProvider in unit testing : ExplicitBeginTransaction is not supported

### ISSUE THREAD

**Issue by neo-james** [eXpandFramework/eXpand#335]
In using the SequenceGenerator with MemoryDataStoreProvider as following :
```
	var objectSpaceProvider = new XPObjectSpaceProvider(new MemoryDataStoreProvider());
	application = new TestApplication();
	var testModule = new ModuleBase();

	testModule.AdditionalExportedTypes.Add(typeof(SequenceObject));
	testModule.AdditionalExportedTypes.Add(typeof(SequenceReleasedObject));
	application.Modules.Add(testModule);
	application.CheckCompatibilityType = CheckCompatibilityType.DatabaseSchema;
	application.DatabaseVersionMismatch += (sender, e) => {
		e.Updater.Update();
		e.Handled = true;
	};

	application.Setup("TestApplication", objectSpaceProvider);
	objectSpace = objectSpaceProvider.CreateObjectSpace();
	ApplicationHelper.Instance.Initialize(application);
	SequenceGenerator.Initialize(objectSpaceProvider.DataLayer, typeof(SequenceObject));

	//Error Here
	var seqNumber = Xpand.Persistent.Base.General.SequenceGenerator.GenerateSequence("Seq1");
```

**Comment by apobekiaris** [comment]
>ExplicitBeginTransaction is not supported

the exception message I think is very clear, the locking is done using en explicit sql server connection and will not work if the datastore server does not support such connections.

**Comment by neo-james** [comment]
> the locking is done using en explicit sql server connection and will not work if the datastore server does not support such connections.

SequenceGenerator should be able to handle such case.

Reasons:
- Unit testing using MemoryDataStoreProvider is much faster.
- MemoryDataStoreProvider is by it's nature can be created for each separate test.
 
Suggestion:
We can implement simple ExplicitUnitOfWork with required methods only for DataSet data store

**Comment by apobekiaris** [comment]
>We can implement simple ExplicitUnitOfWork with required methods only for DataSet data store

if you have something that works feel free to send a PR. From what I see the SequenceGenerator wont be enabled by default in case of the MemoryProvider, however you try to explicitly initialized.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
