### ISSUE TITLE
Win - ImmediatePostDataController : NullReferenceException occurs when adding unbound column with custom ColumnEdit

### ISSUE THREAD

**Issue by softkey87** [eXpandFramework/eXpand#336]
**Describe the bug**
A NullReferenceException occurs in ImmediatePostDataController when adding an unbound column with the property ColumnEdit assigned to a RepositoryItem at runtime (NOT by using the ModelEditor). 

**To Reproduce**
1. Create a controller that add unbound column to a GridView
2. Assign a RepositoryItem to the column's ColumnEdit property
3. Start the application and invoke the view, you'll get the NullReferenceException on line 21 of file ImmediatePostDataController:
`if (modelColumn.ImmediatePostData){`

Because the unbound column has not been created via the ModelEditor, there is no model associated with the unbound column

**Expected behavior**
If there is no model specified for the unbound column, it should not throw an exception and just return. (Should check if modelColumn is not null)

This is not a big issue for me right now has I have disabled this controller for now to solve the problem, but I wanted to report this bug

**Comment by expand** [comment]
Installer lab build [18.2.601.11](https://github.com/eXpandFramework/lab/releases/18.2.601.11) includes commit [ImmediatePostDataController throws when column has no model #336](https://github.com/eXpandFramework/lab/commit/ad1cefc1d806afbe2e67a944b3a3faac62acb74c) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
