### ISSUE TITLE
Issues with SequenceGenerator.GenerateSequence NoGeneration

### ISSUE THREAD

**Issue by brond3** [eXpandFramework/eXpand#338]
**Describe the bug**
It used to be that having the following (simplified) would be enough for a sequence to be generated and saved.  A while back something changed in the behavior of the GenerateSequence command.  

    public class ProductionRunsBO : XPCustomObject, ISupportSequenceObject
    {
        private int runNum;
        [SequenceProperty]
        public int RunNum
        {
            get
            {
                return runNum;
            }
            set
            {
                SetPropertyValue("RunNum", ref runNum, value);
            }
        }

        protected override void OnSaving()
        {
            base.OnSaving();
            if (Session.IsNewObject(this))
            {
                SequenceGenerator.GenerateSequence(this);
            }
        }
        long ISupportSequenceObject.Sequence
        {
            get { return RunNum; }
            set { RunNum = (int)value; }
        }

        string ISupportSequenceObject.Prefix
        {
            get
            {
                return "";
            }
        }
    }

**Expected behavior**
The value of ProductionRunsBO.RunNum would get set to the sequence (Used to work) 

**Desktop (please complete the following information):**
 - DevExpress 18.2.6.0
 - eXpand 18.2.601.0

**Comment by apobekiaris** [comment]
Hi,

Apologies for the delay. 

I tested your class and works fine, my guess is you do not have any eXpand module installed? or maybe you can post a sample to see whats going on.

**Comment by brond3** [comment]
I will work on creating a sample today/tomorrow.

**Comment by brond3** [comment]
[SequenceTest.zip](https://github.com/eXpandFramework/eXpand/files/2960074/SequenceTest.zip)

**Comment by apobekiaris** [comment]
Apologies for the delay, they where extensive works in the continuous integration pipeline to enhance the support experience and I was overload. They now finished.

Now about your question, already gave the hint in my previous post
> my guess is you do not have any eXpand module installed

You project although you reference assemblies in the agnostic module does not install them. These are XAF modules and they you need to add them in the `RequiredModuleTypes` collection.

SequenceGenerator is common to all modules. Meaning by installing any module u get it functional. To install for e.g the System.Win reference Xpand.ExpressApp.Win.dll in your SequenceTest.Module.Win module and add the next line in the `WinModule.Designer.cs`
```cs
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule));
```

run the project and you will get a prompt to install the `Xpand.Persistent.BaseImpl.dll` in the front end project (SequenceTet.win). BaseImpl is not a module, they following specific naming `Xpand.ExpressApp.ModuleName`, its  a lib and does not need any installation.

Now run the project again and SequenceGenerator is functional.

**Comment by brond3** [comment]
Hi, 
No problem with the delay.  I added the line as per your example and it's now giving me a runtime error.   see below. 

System.ArgumentException
  HResult=0x80070057
  Message=An error with number 1008 has occurred.
Error message: the 'Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule' type is not descendant of 'DevExpress.ExpressApp.ModuleBase'
Parameter name: item
  Source=DevExpress.ExpressApp.v18.1
  StackTrace:
   at DevExpress.ExpressApp.Utils.Guard.TypeArgumentIs(Type expectedType, Type passedType, String argumentName)
   at DevExpress.ExpressApp.ModuleTypeList.AddCore(Type item)
   at DevExpress.ExpressApp.TypeCollection.Add(Type item)
   at SequenceTest.Module.Win.SequenceTestWindowsFormsModule.InitializeComponent() in C:\Users\brond\source\repos\SequenceTest\SequenceTest.Module.Win\WinModule.Designer.cs:line 32
   at SequenceTest.Module.Win.SequenceTestWindowsFormsModule..ctor() in C:\Users\brond\source\repos\SequenceTest\SequenceTest.Module.Win\WinModule.cs:line 21
   at SequenceTest.Win.SequenceTestWindowsFormsApplication.InitializeComponent() in C:\Users\brond\source\repos\SequenceTest\SequenceTest.Win\WinApplication.Designer.cs:line 29
   at SequenceTest.Win.SequenceTestWindowsFormsApplication..ctor() in C:\Users\brond\source\repos\SequenceTest\SequenceTest.Win\WinApplication.cs:line 24
   at SequenceTest.Win.Program.Main() in C:\Users\brond\source\repos\SequenceTest\SequenceTest.Win\Program.cs:line 28

**Comment by apobekiaris** [comment]
this message means that you have a version conflict can't guess exactly which one as as you really back in time, maybe you use Xpand with a DX version that is not supposed to work? for 18.2.7 XAF version u need eXPand 18.2.70x.x similarly for your old version you use.

I attached my sample working solution however I tested with the latest Xpand Version
[SequenceTest.zip](https://github.com/eXpandFramework/eXpand/files/2989372/SequenceTest.zip)
.

**Comment by apobekiaris** [comment]
note that this is a .NET exception, not eXpand or XAF

**Comment by brond3** [comment]
I think we can close this.  I am not able to test with eXpand anymore.  I installed new version of Devexpress,  Loaded the new eXpand 18.2.70x and now nothing from eXpand will work.   I will have to assume that it works with the latest copy of eXpand.  I will wait a few updates of eXpand to try again the install process.  I suspect that something in new eXpand install process is not playing well with Visual Studio. Specifically the VSIX I suspect.

**Comment by apobekiaris** [comment]
ok but fyi VSIX offers design time integration + exra utilities and does not affect the rest of the assemblies at all. Also note that you can use the assemblies without it. Anyway when you try again feel free to post if problems.

**Comment by brond3** [comment]
I will keep trying to find what I am missing.  I can see that it works with the file you loaded.  I am obviously doing something different.  I will close it for now and reopen once I can put a clear finger on the issue that's causing the sequence to not be generated.
