### ISSUE TITLE
Null Reference in EnumProperty Editor (Lab #330)

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#341]
System.NullReferenceException
  HResult=0x80004003
  Message=Referencia a objeto no establecida como instancia de un objeto.
  Source=Xpand.ExpressApp.Win
  StackTrace:
   at Xpand.ExpressApp.Win.PropertyEditors.EnumPropertyEditor.ObjectSpaceOnCommitted(Object sender, EventArgs e) in E:\tfs\expand\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\EnumPropertyEditor.cs:line 115

The variable control is null, perhaps you should consider a null check as in OnCurrentObjectChanged?

**Comment by expand** [comment]
Installer lab build [18.2.601.16](https://github.com/eXpandFramework/lab/releases/18.2.601.16) includes commit [EnumPropertyEditor throws on ObjectSpaceOnCommitted #330 #341](https://github.com/eXpandFramework/lab/commit/37b48276f044f91d940f3b94b9483b994ae3d0f0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by apobekiaris** [comment]
build not ready yet sorry for this

**Comment by expand** [comment]
Installer lab build [18.2.601.18](https://github.com/eXpandFramework/lab/releases/18.2.601.18) includes commit [EnumPropertyEditor throws on ObjectSpaceOnCommitted #330 #341](https://github.com/eXpandFramework/lab/commit/560cfc9184d3cf492f2991e7068488467cb2dc64) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]() as a nuget package source in VS

**Comment by expand** [comment]
Installer lab build [18.2.601.22](https://github.com/eXpandFramework/lab/releases/18.2.601.22) includes commit [EnumPropertyEditor throws on ObjectSpaceOnCommitted and when Enum is a Flag #330 #341](https://github.com/eXpandFramework/153812905/commit/2b5b9d0ee41d8b7044e43caad0ca55257f715ef6) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
