### ISSUE TITLE
Xpand.VSIX not working (18.2)

### ISSUE THREAD

**Issue by volkanalkilic** [eXpandFramework/eXpand#343]
I have installed the latest version but I get this error;

![resim](https://user-images.githubusercontent.com/14903319/54178912-4edfe000-44a8-11e9-8b6e-38947dd45163.png)

**Comment by apobekiaris** [comment]
which version are you on? this should be ok in the latest nightly, see how others fix it #316

**Comment by volkanalkilic** [comment]
I fixed by changing registry path.

**Comment by odilbek84** [comment]
I have the same problem, could you explain? step by step, thank you. (teshekkur)

**Comment by volkanalkilic** [comment]
Wrong path: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AssemblyFolders\Xpand

Rigth path: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AssemblyFolders** Ex**\Xpand

![resim](https://user-images.githubusercontent.com/14903319/54306039-94e89100-45d9-11e9-9fd1-753fe0ca9337.png)

**Comment by odilbek84** [comment]
thank you so much, I did it. (cok teshakkurlar arcadash)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
