### ISSUE TITLE
InvalidCastException in Xpand EnumpropertyEditor

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#344]
**Describe the bug**
System.InvalidCastException
  HResult=0x80004002
  Message=No se puede convertir un objeto de tipo (Unable to convert an object of type)'DevExpress.XtraEditors.Repository.RepositoryItemCheckedComboBoxEdit' al tipo 'DevExpress.XtraEditors.Repository.RepositoryItemComboBox'.
  Source=Xpand.ExpressApp.Win
  StackTrace:
   **at Xpand.ExpressApp.Win.PropertyEditors.EnumPropertyEditor.SetupRepositoryItem(RepositoryItem item) in E:\tfs\expand\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\EnumPropertyEditor.cs:line 64**

**To Reproduce**
Opening a listview with several enum columns

**Expected behavior**
no error

**Comment by apobekiaris** [comment]
fix  included in latest nighlty and had to do with the Enum being a Flag

**Comment by vimarx** [comment]
Still having trouble

System.InvalidCastException
  HResult=0x80004002
  Message=No se puede convertir un objeto de tipo 'DevExpress.XtraEditors.CheckedComboBoxEdit' al tipo 'DevExpress.XtraEditors.ComboBoxEdit'.
  Source=DevExpress.ExpressApp.Win.v18.2
  StackTrace:
   at DevExpress.ExpressApp.Win.Editors.EnumPropertyEditor.get_Control() in DevExpress.ExpressApp\DevExpress.ExpressApp.Win\Editors\EnumPropertyEditor.cs:line 71
![image](https://user-images.githubusercontent.com/226800/54353800-b70efd00-4633-11e9-96ce-4f507ea14a30.png)

**Comment by apobekiaris** [comment]
I do not see how to repro the case, in my tests I marked `StatusColor` in `SystemTester` as Flag and I tested with success.

![image](https://user-images.githubusercontent.com/159464/54706050-b18b4880-4b46-11e9-8bf3-2d3f7b5d8572.png)

Can you provide sample or instructions.

**Comment by vimarx** [comment]
I think this issue is related to the IsDelayedDetailViewDataLoadingEnabled

Attached solution used
[Enumtest.zip](https://github.com/eXpandFramework/eXpand/files/2999492/Enumtest.zip)

and the repro steps (may vary...)
![2019-03-23_12-02-03](https://user-images.githubusercontent.com/226800/54867815-6dc15a80-4d63-11e9-863f-480a39e0360e.gif)

**Comment by vimarx** [comment]
some time the exception happens in other situations (the same call stack)

**Comment by vimarx** [comment]
@apobekiaris

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.2](https://github.com/eXpandFramework/lab/releases/18.2.703.2) includes commit [EnumPropertyEditor throws when flags are used #344](https://github.com/eXpandFramework/153812905/commit/7cf3b82676bbb6ad60fad73d14adf696e7c6e88b) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
