### ISSUE TITLE
VS 2017 freeze when opening toolbox in module with vsix

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#347]
Hi Tolis,

With the version 18.2.700.0 i  had severy issues : 

Installation : 

- I run : eXpandFramework-18.2.700.0.exe and it create only the folder C:\Program Files (x86)\eXpandFramework with the uninstall.exe. (no DLLs)

- So i copied the DLL manually in the installation folder : C:\Program Files (x86)\eXpandFramework\Xpand.DLL

- I run the GacInstaller.exe and the Xpand.ToolboxCreator.exe

- I run the Xpand.VSIX-18.2.700.0.vsix

After opening VS2017 Community i get a error :  #346 
When i open the module and click on ToolBox : VS2017 freezes. 

I kill the process and restart VS2017 and disable the vsix and finally click on the toolbox : OK

Many thanks for your help.

BR
ISA

**Comment by isatahiri** [comment]
Additional info : 
I have Windows 10 in french and vs 2017 Community in french. 
I'm local administrator.

**Comment by apobekiaris** [comment]
I am not sure if this problem still exists, in my machine I cannot repro it. Do you see this window populating the compnents when you first open VS after installation?

![image](https://user-images.githubusercontent.com/159464/54714071-cb358b80-4b58-11e9-8314-3b25226978ac.png)

**Comment by uniqueitmail** [comment]
I already ran it, It takes few seconds/minutes for first time run after installation complete, its depend on machine config & window populating the components. That it.

**Comment by isatahiri** [comment]
Not for me. After adding the toolbox, VS freeze and after some minutes restarts . 
I sticks loading vspackage : 
![image](https://user-images.githubusercontent.com/41955268/54787359-ce4d7c00-4c2b-11e9-87fa-87d285fa6b75.png)

And i did my machine from scratch. 

I have a VS 2017 Community in win10 pro.

**Comment by isatahiri** [comment]
fr : Chargement de la boîte à outils a partir du package 
EN : Loading toolbox from the package...

**Comment by isatahiri** [comment]
Is it due to the missing key in registry ? See #349

**Comment by apobekiaris** [comment]
nope, wait a bit please I am working on a fix

**Comment by apobekiaris** [comment]
So, in the next lab release you will find a version that should work out these toolbox problems. 

Note: You can monitor the registration status in the VS status bar this window should not be visible
![image](https://user-images.githubusercontent.com/159464/54819927-1c9f6100-4ca6-11e9-8c25-94fca52cacc1.png)

**Comment by isatahiri** [comment]
ok. I just tried with this command : 
Set-ExecutionPolicy Bypass -Scope Process -Force; iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') - Latest"
![image](https://user-images.githubusercontent.com/41955268/54821477-8f0e4200-4ca2-11e9-851a-947e42062001.png)

Did i miss something ?

**Comment by apobekiaris** [comment]
the release is not ready the bot should reply when it is.

I am not sure as i cannot translate exactly what it says but looks like  a connectivity issue the webclient fails to download the raw url. Can you try again? is the uri accesible from the browser?

**Comment by apobekiaris** [comment]
try this one https://github.com/eXpandFramework/lab/releases/tag/18.2.703.1

**Comment by apobekiaris** [comment]
the Latest flag should work now i am just installing 18.2.703.1

**Comment by expand** [comment]
Installer lab build [18.2.703.1](https://github.com/eXpandFramework/lab/releases/18.2.703.1) includes commit [VSIX-> VS Freeze when registering ToolboxItems #347](https://github.com/eXpandFramework/153812905/commit/788babc9601fb463560990c3f46d91db46ee16d3) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
well not for me : 
PS C:\WINDOWS\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') -Version '18.2.703.1'"
Downloading installation script from https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Private/Xpand/InstallXpand.ps1 into C:\Users\isata\Documents\eXpandFramework\
InstallXpand.ps1


    Répertoire : C:\Users\isata\Documents


Mode                LastWriteTime         Length Name                                                                                                                                         
----                -------------         ------ ----                                                                                                                                         
d-----       22.03.2019     13:48                eXpandFramework                                                                                                                              
Installation parameters:

Key   : SkipGac
Value : False
Name  : SkipGac


Key   : InstallationPath
Value : C:\Users\isata\Documents\eXpandFramework
Name  : InstallationPath


Key   : Version
Value : 18.2.703.1
Name  : Version


Key   : Latest
Value : False
Name  : Latest


Key   : Assets
Value : {Assemblies, Nuget, VSIX, Source}
Name  : Assets

Installing Assemblies, Nuget, VSIX, Source into C:\Users\isata\Documents\eXpandFramework.
Additional parameters: Version, Latest, Assets, InstallationPath
Downloading Sources from https://github.com/eXpandFramework/eXpand/releases/download/18.2.703.1/Xpand-Source-18.2.703.1.zip into C:\Users\isata\Documents\eXpandFramework
iex : Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:1 : 51
+ ... ess -Force; iex "$((New-Object System.Net.WebClient).DownloadString(' ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by isatahiri** [comment]
the links : https://github.com/eXpandFramework/eXpand/releases/download/18.2.703.1/Xpand-Source-18.2.703.1.zip 
is broken

**Comment by apobekiaris** [comment]
try the -latest and not the -Version i am testing the version now

**Comment by apobekiaris** [comment]
yeah the -Version flab works only for the `eXpand` repo I will update for `lab` asap

**Comment by apobekiaris** [comment]
it is now fixed as well

**Comment by isatahiri** [comment]
It does not freeze anymore. Thanks for your help Tolis !

**Comment by apobekiaris** [comment]
you welcome
