### ISSUE TITLE
Default member for {table_name} is missing 

### ISSUE THREAD

**Issue by odilbek84** [eXpandFramework/eXpand#348]
![image](https://user-images.githubusercontent.com/25136780/54423402-fea29100-46e6-11e9-8bb9-94d6531df208.png)

during the importing Excel file closed. 

what is that means this error ? 
database and excel columns format is same.

**Comment by apobekiaris** [comment]
Not having `Default Member` in your Bo is not a good practice, and will result in inconsistent even when using XAF only.
This module however queries records for e.g. the `CreateAndUpdate` strategy and for this it needs to know what member will be used. It calculates which is the Default member with this code

https://github.com/eXpandFramework/eXpand/blob/04190c2a87615388545f6978131bda3e0e61e19a/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/Services/ImportExtension.cs#L124-L127

So your solution is to assign a default member to your BO either using the `ExcelImportKeyAttribute` or using XAF attributes like `DefaultPropertyAttribute`

p.s. : checkout the XAF docs about the [defaultpropertyattribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.defaultpropertyattribute?redirectedfrom=MSDN&view=netframework-4.7.2)

**Comment by odilbek84** [comment]
thank you for your response so quick Apobekiaris
true is I'm absolutely new here and , im using DevExpress ORM Data Model Wizard and when i save model, BO is automatically creates for me, i have no idea how to add DefaultPropertyAttribute here is 
code generated could you correct me please, thank you.
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace CEM.Module.BusinessObjects.cem_brooklyn
{
    [DefaultClassOptions]
    public partial class items_all
    {
        public items_all(Session session) : base(session) { }
        public override void AfterConstruction() { base.AfterConstruction(); }
    }


}

**Comment by apobekiaris** [comment]
you can use the Model Editor
![image](https://user-images.githubusercontent.com/159464/54440517-8b7b3800-4743-11e9-9f0b-d77fabdf8f01.png)

**Comment by odilbek84** [comment]
thank you so much, you can close this question.

**Comment by brond3** [comment]
You can also use    [XafDefaultProperty("propertyname")]  before your BO if you prefer to not use the model editor.

**Comment by odilbek84** [comment]
thanks Brond3, actually i could not change with  model editor, but 

namespace CEM.Module.BusinessObjects.cem_brooklyn
{
    [DefaultClassOptions]
    [XafDefaultProperty("Item")]

    public partial class items_all
    {
        public items_all(Session session) : base(session) { }
        public override void AfterConstruction() { base.AfterConstruction(); }
    }
   

}

this worked 

thanks again for help,
 (sorry I'm not software Engineer, I like to this projects)
