### ISSUE TITLE
Installation is empty

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#349]
Hi Tolis,

the Installationfile 
eXpandFramework-18.2.601.0.exe: 57,8**MB**
eXpandFramework-18.2.602.0.exe: 96**KB**

So the installation is empty.

**Comment by apobekiaris** [comment]
Installation experience is now refactored to use powershell. Try the following one liner for lab
```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force; iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Install-Xpand.ps1'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') - Latest"
```

Omitting `-Latest` parameter will give you the official release, or you can even go for a specific version with the`-Version` parameter.

Let me know how it works for u.

**Comment by isatahiri** [comment]
Hi,

It does not work for me : 
PS C:\Users\itahiri> Set-ExecutionPolicy Bypass -Scope Process -Force; iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')"
Creating C:\Users\itahiri\Documents\eXpandFramework
Installing Assemblies, Nuget, VSIX, Source into C:\Users\itahiri\Documents\eXpandFramework.
Additional parameters: Version, Latest, Assets, InstallationPath
Finding latest Xpand version
Latest official:18.2.701.1.0
Downloading Sources from eXpand repository into C:\Users\itahiri\Documents\eXpandFramework
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:61 : 9
+         $client.DownloadFile($uri,"$InstallationPath\$zip")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Downloading Nugets from eXpand repo into C:\Users\itahiri\Documents\eXpandFramework
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:68 : 9
+         $client.DownloadFile($uri,$zip)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Expanding files into C:\Users\itahiri\Documents\eXpandFramework\Packages
Downloading assemblies from eXpand repo into C:\Users\itahiri\Documents\eXpandFramework
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:78 : 9
+         $client.DownloadFile($uri,$zip)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Expanding files into C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL
Expand-7Zip : Le fichier 'C:\Users\itahiri\Documents\eXpandFramework\Xpand-lib-18.2.701.1.0.zip' est introuvable.
Au caractère Ligne:82 : 9
+         Expand-7Zip $zip $xpandDLL
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SevenZip4PowerS...ip+ExpandWorker:ExpandWorker) [Expand-7Zip], FileNotFoundException
    + FullyQualifiedErrorId : err01,SevenZip4PowerShell.Expand7Zip
 
Remove-Item : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand-lib-18.2.701.1.0.zip », car il n'existe pas.
Au caractère Ligne:83 : 9
+         Remove-Item $zip
+         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...8.2.701.1.0.zip:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
Moving Demos
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:89 : 9
+         Get-ChildItem $xpandDLL *Tester.*|Move-Item -Destination "$de ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:92 : 13
+             Get-ChildItem $xpandDLL "*$_*"|Move-Item -Destination "$d ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Write Registry 
Exception lors de l'appel de « OpenSubKey » avec « 2 » argument(s) : « Accès au registre demandé non autorisé. »
Au caractère Ligne:96 : 9
+         $subKey = $key.OpenSubKey("SOFTWARE\Microsoft\.NETFramework\A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SecurityException
 
Impossible d’appeler une méthode dans une expression Null.
Au caractère Ligne:97 : 9
+         $subKey.CreateSubKey("Xpand").SetValue("", $xpandDLL)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
 to GAC
Set-Location : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:100 : 13
+             Set-Location "$InstallationPath\Xpand.DLL"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
Get-ChildItem : Impossible de trouver le chemin d'accès « C:\Users\itahiri\Documents\eXpandFramework\Xpand.DLL », car il n'existe pas.
Au caractère Ligne:102 : 21
+ ...      $count=(Get-ChildItem "$InstallationPath\Xpand.DLL" *.dll).Count
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...ework\Xpand.DLL:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
& : Le terme «C:\Users\itahiri\Documents\eXpandFramework\Xpand.Dll\GAcInstaller.exe» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un 
chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:105 : 15
+             & "$InstallationPath\Xpand.Dll\GAcInstaller.exe" -m Insta ...
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\itahir...AcInstaller.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Downloading VSIX from eXpand repo into C:\Users\itahiri\Documents\eXpandFramework
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « La demande a été abandonnée : La connexion a été interrompue de manière inattendue. »
Au caractère Ligne:119 : 9
+         $client.DownloadFile($uri,$vsix)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Download VSIX bootstrapper
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Une exception s'est produite lors d'une requête WebClient. »
Au caractère Ligne:121 : 9
+         $client.DownloadFile("https://github.com/Microsoft/vsixbootst ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Installing VSIX
Creating Uninstall-Xpand.ps1
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:126 : 5
+     $client.DownloadFile("https://raw.githubusercontent.com/eXpandFra ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Finished installtion in C:\Users\itahiri\Documents\eXpandFramework

PS C:\Users\itahiri>

**Comment by isatahiri** [comment]
Hi Tolis,

Something is really wrong the the script.
It just killed my dev machine.
![image](https://user-images.githubusercontent.com/41955268/54647723-eb574300-4aa3-11e9-848d-db58f3884d7a.png)

**Comment by isatahiri** [comment]
The last two last lines in green are scarry

**Comment by isatahiri** [comment]
So just a feedback on how it happened :
 - I used the script but it resulted with error : 
Set-ExecutionPolicy Bypass -Scope Process -Force; iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') "

- Then i installed xposh : Install-Module XpandPosh
- I ran the script again. It detected that it is already installed. So it started the uninstall.
- When i saw deleting registry key, i thought that it is just deleting Xpand registry key.
- And then when i saw "deleting C:\" I checked the C drive becoming slowly empty. 

How can that happen ? How can it jumt from "My Documents" to C drive directly ? 


How did that happen ? How can it jump from my document to

**Comment by isatahiri** [comment]
In the UnInstall-Xpand.ps1 : 
The last part : 
 Write-host "Removing $InstallationPath" -f Green
 [System.IO.Directory]::Delete($InstallationPath,$true)
 Write-host "$InstallationPath removed" -f Green

I the $InstallationPath is empty due to an error so it considers the c:\
You should check this part. I thing it came from this.

**Comment by apobekiaris** [comment]
wow that I should have predicted I am very ashamed, I am already disable the script and fixing it.

**Comment by apobekiaris** [comment]
My apologies again for this. Here my results:

The problem caused by a wrong release pushed to nuget.org making the script confused about which is the  official version.

In the next official the script will halt on errors so it won't continue creating the Uninstall.ps1. Furthermore before deleting the installation folder it will ask confirmation. Finally if one use the Uninstall-Xpand not from the oneliner (which is always the latest) but from the XpandPosh it will again update the script to the latest version.

I hope this was my first and last such major

**Comment by apobekiaris** [comment]
Please those that installed Xpand version 18.2.701.0 remove XpandPosh 1.3.7 for not mistaken use it.
```ps1
UnInstall-Module XpandPosh -Version 1.3.7
```

this will only remove the powershell module Xpand is still funcation

**Comment by CWolffIF** [comment]
Hi Tolis,

Version 18.2.703.0.
The RegeditKey is not created.



PS C:\WINDOWS\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') "
Downloading installation script from https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Private/Xpand/InstallXpand.ps1 into C:\Users\CWolff\Documents\eXpandFramework\InstallXpand.ps1


    Verzeichnis: C:\Users\CWolff\Documents


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       20.03.2019     15:11                eXpandFramework
Installation parameters:

Key   : SkipGac
Value : False
Name  : SkipGac


Key   : InstallationPath
Value : C:\Users\CWolff\Documents\eXpandFramework
Name  : InstallationPath


Key   : Version
Value :
Name  : Version


Key   : Latest
Value : False
Name  : Latest


Key   : Assets
Value : {Assemblies, Nuget, VSIX, Source}
Name  : Assets

Installing Assemblies, Nuget, VSIX, Source into C:\Users\CWolff\Documents\eXpandFramework.
Additional parameters: Version, Latest, Assets, InstallationPath
Finding latest Xpand version
Latest official:18.2.703
Downloading Sources from https://github.com/eXpandFramework/eXpand/releases/download/18.2.703.0/Xpand-Source-18.2.703.0.zip into C:\Users\CWolff\Documents\eXpandFramework
Downloading Nugets from https://github.com/eXpandFramework/eXpand/releases/download/18.2.703.0/Nupkg-18.2.703.0.zip into C:\Users\CWolff\Documents\eXpandFramework
Expanding files into C:\Users\CWolff\Documents\eXpandFramework\Packages
Downloading assemblies from https://github.com/eXpandFramework/eXpand/releases/download/18.2.703.0/Xpand-lib-18.2.703.0.zip into C:\Users\CWolff\Documents\eXpandFramework
Expanding files into C:\Users\CWolff\Documents\eXpandFramework\Xpand.DLL
Moving Demos
Write Registry
iex : Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In Zeile:1 Zeichen:51
+ ... ess -Force; iex "$((New-Object System.Net.WebClient).DownloadString(' ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by apobekiaris** [comment]
hi

execute this in an admin ps prompt please
```ps1
$PSVersionTable
```
whats the output?

and then execute this
```ps1
[Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry32).OpenSubKey("SOFTWARE\Microsoft\.NETFramework\AssemblyFolders", $true)
```

**Comment by apobekiaris** [comment]
yeah I can repro it, you need to run the script from an elevated prompt. I will add  a message to the script for this

**Comment by CWolffIF** [comment]
hi, what is an "elevated prompt"?

**Comment by apobekiaris** [comment]
right click on the powershell icon and chhose run as Administrator

**Comment by apobekiaris** [comment]
I fixed it, it prompts to run as admin now if you try to use it from the oneliner

**Comment by CWolffIF** [comment]
Hi Tolis,

I run as admin. But the same error, no registry key is written cause the ".NETFramework\AssemblyFolders" is not there. If I create the Folder and ran it again, than the Xpand-Key is written and there and the installation continous.

Then the GAC Installation runs and an Error with the Percentage-Bar appears:


System.Data.Common.dll
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

ForEach-Object : Das Argument für den Parameter "PercentComplete" kann nicht überprüft werden. Das 101-Argument ist
größer als der maximal zulässige Bereich von 100. Geben Sie ein Argument an, das kleiner oder gleich 100 ist, und
führen Sie dann den Befehl erneut aus.
In C:\Users\CWolff\Documents\eXpandFramework\InstallXpand.ps1:111 Zeichen:73
+ ... tallationPath\Xpand.Dll\GAcInstaller.exe" -m Install|ForEach-Object {
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ForEach-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by apobekiaris** [comment]
> is written cause the ".NETFramework\AssemblyFolders"

whats your windows version?

>Then the GAC Installation runs and an Error with the Percentage-Bar appears:

Does the installation stops at this point or continue? If stops do you use the oneliner installer ot the XpandPosh?

**Comment by CWolffIF** [comment]
Then the GAC Installation runs and an Error with the Percentage-Bar appears:

Does the installation stops at this point or continue? If stops do you use the oneliner installer ot the XpandPosh?

I use the oneliner and the Installations stops.

**Comment by apobekiaris** [comment]
>whats your windows version?

**Comment by isatahiri** [comment]
INFO : 
The error with the percentage bar is the same as mine. #350 
BR
ISA

**Comment by apobekiaris** [comment]
please try again, in my previous fix I swallow the progress bar erros however the error is on the precentage calculator. It should not disaply any red now

**Comment by isatahiri** [comment]
Hello,

No registry create in my side neither : 
I tried to create the folder manually in the regedit, uninstalled, installed but no sucess. 
![image](https://user-images.githubusercontent.com/41955268/54811494-18b11600-4c89-11e9-8e96-d423e86435de.png)

The result of $PSversiontable

PS C:\Users\isata\Documents\eXpandFramework\Xpand.DLL> $PSVersionTable

#[Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry32).OpenSubKey("SOFTWARE\Microsoft\.NETFramework\AssemblyFolders", $true)

Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17134.590                                                                                
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17134.590                                                                               
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1                                                                                      

The result of : [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry32).OpenSubKey("SOFTWARE\Microsoft\.NETFramework\AssemblyFolders", $true)
Empty : 
![image](https://user-images.githubusercontent.com/41955268/54811620-688fdd00-4c89-11e9-9bc5-d33f006ef5d8.png)

**Comment by apobekiaris** [comment]
I consider this issue now fixed, so hoping for minor damages I unpin this issue. Thanks all and apologies again.

**Comment by CWolffIF** [comment]
Hi Tolis,

works for me.
