### ISSUE TITLE
Install : ForEach-Object : Impossible de valider l'argument sur le paramètre « PercentComplete »

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#350]
Hi, 
Guring the installation, i had this : 
![image](https://user-images.githubusercontent.com/41955268/54717657-fcae5700-4b58-11e9-8644-52821efefb21.png)

Any Idea ? 
BR
ISA

**Comment by apobekiaris** [comment]
text i can translate picture nope :)

**Comment by apobekiaris** [comment]
u can copy paste your console output instead

**Comment by apobekiaris** [comment]
try the latest oneliner now it should display those errors in red but continue

**Comment by isatahiri** [comment]
Sorry for the picture :-)
"Cannot validate the argument on the parameter "Percent complete". The argument 101 is greather that the max authorized range. Specify an argument lower or equal to 100 and try again"

Well at that step it seems taht there is a counter or a foreach giving the percentage. And in somehow, the percentage is going to 101%. 

What is the "oneliner"

BR
ISA

**Comment by apobekiaris** [comment]
>What is the "oneliner"

powershell is famous for doing scripts in one line.

so u mean that the script still stops right?

**Comment by dimasrespect** [comment]
@apobekiaris May be this hepls: I have the same problem for first time installation using PS. It is also breaks after adding System.Data.Common.dll to GAC and error is the same (but in russian). I've tried to run oneliner command again, and it successfully complete for second time.

**Comment by apobekiaris** [comment]
thnks for the feedback, it completed the second time most probably cause I updated it from
https://github.com/eXpandFramework/eXpand/issues/349#issuecomment-475160294

in any case please post if problems again.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
