### ISSUE TITLE
Dashboard Designer Not Working

### ISSUE THREAD

**Issue by ramos41** [eXpandFramework/eXpand#351]
Hello,

After working in version 16.2.6, the dashboard designer stopped working after the 18.1.6 version. When I compared the XML field in the DashboardDefinition table, I saw 2 differences.

First,

In version 16.2.6, ObjectDataSource is retained in this way;

`<ObjectDataSource Name = "Opportunity" ComponentName = "dataSource1" />`

In version 18.1.6, it holds the following:

`<ObjectDataSource Name = "MT_Opportunity" ComponentName = "MT_Opportunity"> 
 <DataSource Type = "logocrm.net.Module.BusinessObjects.MT_Opportunity, logocrm.net.Module, Version = 1.54.0.0, Culture = neutral, PublicKeyToken = null" />
</ ObjectDataSource>`

Second,

The UniqueName parameter is also converted to DefaultId.

`<Value UniqueName="DataItem1" />  =>  <Value DefaultId="DataItem1" />`

What should I do about it?

Thank you,
Best Regards,
Ramos.

**Comment by apobekiaris** [comment]
Hi,

Give me some time to research this please. 
https://isc.devexpress.com/Thread/WorkplaceDetails?id=T717757

**Comment by apobekiaris** [comment]
Unfortunately is hard to tell the reason, I need the working xml with 16.2.6 and its domain to continue investigation.

**Comment by ramos41** [comment]
Hello,
Here is working in version 16.2.6 xml. 
Thank you for your interest.
Best regards.
Ramos

[sample.zip](https://github.com/eXpandFramework/eXpand/files/3001668/sample.zip)

**Comment by apobekiaris** [comment]
please upload the business objects used in this dashboard,

**Comment by ramos41** [comment]
Ok.
Thank you.

[BusinessObjects.zip](https://github.com/eXpandFramework/eXpand/files/3003204/BusinessObjects.zip)

**Comment by apobekiaris** [comment]
give me some time please I will update you once I have something

**Comment by apobekiaris** [comment]
from T727496 I see that you laredy resolve your issues, so I will not spent additional time. In any case feel free to post back if you need further assistance.

**Comment by ramos41** [comment]
Thank you Apobekiaris. I found what I was looking for.
