### ISSUE TITLE
ExcelImport : Wrong exception message when validating column mapping

### ISSUE THREAD

**Issue by Ezeckiel2517** [eXpandFramework/eXpand#352]
There is a small bug in file \ExcelImporter\Services\ImportExtension.cs, method GetImportParameters where the MemberNotFoundException report the wrong type which lead to confusion.

```csharp
public static ImportParameter[] GetImportParameters(this ExcelImport excelImport){
	return excelImport.ExcelColumnMaps.Select(map => {
		var memberInfo = excelImport.Type.GetTypeInfo().Members.FirstOrDefault(info => map.PropertyName==info.Caption());
		if (memberInfo==null)
			throw new MemberNotFoundException(excelImport.GetTypeInfo().Type, map.PropertyName);
		return new ImportParameter(){MemberInfo=memberInfo,Map=map};
	}).ToArray();
}
```

It should be

```csharp
throw new MemberNotFoundException(excelImport.Type, map.PropertyName);
```

**Comment by apobekiaris** [comment]
thanks, I ll add it in the next minor.

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.2](https://github.com/eXpandFramework/lab/releases/18.2.703.2) includes commit [ExcelImport: Wrong exception message when validating column mapping #352](https://github.com/eXpandFramework/153812905/commit/bc683d150b840430217608c37c3fa6210db60435) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.
