### ISSUE TITLE
Multi tab control in dashboard designer

### ISSUE THREAD

**Issue by disteSp** [eXpandFramework/eXpand#353]
Hi, 

I found in devEx documentation of 18.2 version that the mult tab item had been added to dashboard designer:
https://community.devexpress.com/blogs/analytics/archive/2018/09/11/DevExpress-Dashboards-Tab-Support-Windows-Web.aspx

https://documentation.devexpress.com/Dashboard/400300/Creating-Dashboards/Creating-Dashboards-on-the-Web/Designing-Dashboard-Items/Tab-Container

https://documentation.devexpress.com/Dashboard/400436/Examples/WinForms-Designer-Examples/How-to-Combine-Multiple-Dashboards-into-a-Dashboard-with-Multiple-Tab-Pages

Do you think the same functionality will be available also in Xpand designer?

Thanks

**Comment by apobekiaris** [comment]
this is a build-in Dashboard functionality and works already, what your issue exactly?

**Comment by disteSp** [comment]
It is a really good new. Now we are using the Xpand and DevEx 18.1.4 version. A customer requests us a similar functionality. So we just need to upgrade Xpand and DevEx to get the multi tab functionality without code modifications. Is it correct?

**Comment by apobekiaris** [comment]
yeah its there and there is always support if needed.

**Comment by disteSp** [comment]
Hi, I'm trying to migrato from Xpand (and DevEx) 18.1 to 18.2.7. But I found a lot of error in Web projects:
    public class DataSurfaceDashboardViewEditorWeb : DashboardViewEditorWeb
    {
        ASPxDashboardViewer _asPxDashboardViewer;
...........
 e.DashboardXml = **Definition.GetXml**(RuleMode.Runtime, **_objectSpace.CreateDashboardDataSource**, _application);

Both Definition.Xml( )  and  _objectSpace.CreateDashboardDataSource are missing and cause compiling errors.
I compared sources code of DashboardViewEditorWeb of 18.1 and 18.2, and there are many differences in code and references (i'e. using Xpand.ExpressApp.Dashboard.Filter; is no more present). Please, can  you give me some indications on it?

**Comment by apobekiaris** [comment]
the module is refactored some time ago to work with the classes of the build-in module. Those modules do not exist.

See how the [DashboardViewEditorWeb](https://github.com/eXpandFramework/eXpand/blob/18.2/Xpand/Xpand.ExpressApp.Modules/XtraDashboard.Web/PropertyEditors/DashboardViewEditorWeb.cs) is implemented now and override what u need.

**Comment by disteSp** [comment]
Ok I updated my project using the new DashboardViewEditorWeb. I only have one issue when showing the dashboard in web application. It returns the error: " : 'An error with number 1021 has occurred.
Error message: The object that has been passed belongs to another ObjectSpace..."

Debugging code I found the following functions in Xpand.ExpressApp.XtraDashboard.Web.Controllers.DashboardViewerController : 
`private void OnCustomShowNavigationItem(object sender, CustomShowNavigationItemEventArgs e){
            if (e.ActionArguments.SelectedChoiceActionItem.Data is ViewShortcut viewShortcut&&viewShortcut.ViewId==DashboardDefinition.DashboardViewerDetailView){
                var objectSpace = Application.CreateObjectSpace();
                var definition = objectSpace.GetObjectByKey<DashboardDefinition>(Guid.Parse(e.ActionArguments.SelectedChoiceActionItem.Id));
                var dashboard = definition.GetDashboard(Application, RuleMode.DesignTime,modeParametersEdited: () => EditDashboard(definition,e.ActionArguments.Action));
                if (dashboard!=null)
                    EditDashboard(definition,e.ActionArguments.Action);
                e.Handled = true;
            }
        }

        private void EditDashboard(DashboardDefinition dashboardDefinition, ActionBase actionBase){
            var modelView = (IModelDetailView) Application.Model.Views[DashboardDefinition.DashboardViewerDetailView];
            var objectSpace = Application.CreateObjectSpace();
            var detailView = Application.CreateDetailView(objectSpace, modelView, true, dashboardDefinition);
            
            Application.ShowViewStrategy.ShowView(new ShowViewParameters(detailView),new ShowViewSource(Frame,actionBase ) );
        }`
As you can see in each of the above methods there is the instruction var objectSpace = Application.CreateObjectSpace(); which cause the error for me. Dashboard definition has been retrieved from an object space in  OnCustomShowNavigationItem but it is shown using another ObjectSpace in EditDashboard method. I think that EditDashboard method should receive also the objectspace as parameter.

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.4](https://github.com/eXpandFramework/lab/releases/18.2.703.4) includes commit [DashboardViewerController uses wrong ObjectSpace #353](https://github.com/eXpandFramework/153812905/commit/4dca45847b69506af3be17ea40704604b16ad694) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by disteSp** [comment]
Thansk for the fix, I tried to install the new version with the command:
Set-ExecutionPolicy Bypass -Scope Process -Force 
$installer="Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') -Latest #-Version '18.2.703.4'"
iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));$installer"

but it seems that it installs the 18.2.703.1 version instead of 703.4. 
![XpandInstall](https://user-images.githubusercontent.com/40351623/55314002-7a336a80-5469-11e9-829f-2a55a1665d02.PNG)

**Comment by apobekiaris** [comment]
try again please I fixed the problem

**Comment by disteSp** [comment]
Now it returns the following error:
iex : Program 'nuget.exe' failed to run: The directory name is invalidAt C:\Users\davide.distefano\Documents\eXpandFramework\InstallXpand.ps1:46 char:20
+ ...  $release = & $Nuget list eXpand -Source "https://api.nuget.org/v3/in ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:3 char:1
+ iex "$((New-Object System.Net.WebClient).DownloadString('https://raw. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Invoke-Expression], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by disteSp** [comment]
![XpandInst2](https://user-images.githubusercontent.com/40351623/55319962-5aef0a00-5476-11e9-94ac-66cefd3dac36.PNG)

**Comment by apobekiaris** [comment]
hmm i do not see why this problems occured. Just before the FindVersion it downloads the Nuget in path

https://github.com/eXpandFramework/XpandPosh/blob/c85dab4152d6d3a217bd663f49ddba3fe86ffbf4/XpandPosh/Private/Xpand/InstallXpand.ps1#L38-L45

Can you try manually delete the files in the installation path and restart?

**Comment by disteSp** [comment]
Now it works. Thanks

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
