### ISSUE TITLE
MultiValueDictionary class has problems with 19.1 async loading

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#354]
it is not thread safe

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.3](https://github.com/eXpandFramework/lab/releases/18.2.703.3) includes commit [MultiValueDictionary internal HashSet is not threadsafe #354](https://github.com/eXpandFramework/153812905/commit/575710461f07aabb32205722be26049a647d6d98),[Make MultiValueDictionary to support 19.1 async loading #354](https://github.com/eXpandFramework/153812905/commit/8838df6c258be424feb46f721c7f9a1e2a983df9) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
