### ISSUE TITLE
VirtualServerModeSource for XAF Views

### ISSUE THREAD

**Issue by sheldmandu** [eXpandFramework/eXpand#355]
Currently it's extremely difficult to work with third-party APIs that require pagination if you want to surface the returned data in XAF through ListViews, etc.  There is no native pagination support in the controls.  Specific example I'm working with is Hangfire Monitoring API.

I think a good GENERIC solution would be to have the views support VirtualServerModeSource.  It is possible to create custom views based on the grid control to do it now, but it really leaves the bounds of XAF.  It would be much nicer if it were possible to just select "Virtual Server" mode as the access mode and for the view to then be wired to use the VirtualServerModeSource and enabling the developer do their own thing in terms of handing the appropriate CollectionSource events in a controller, without need to go to the trouble of creating their own UserControls, etc.

Alternative at the moment is to create NextPage, PrevPage actions to handle pagination and wire up the ObjectGetting event in the ViewController.  It's not as nice a user experience as just scrolling through records in the grid.

See https://documentation.devexpress.com/CoreLibraries/DevExpress.Data.VirtualServerModeSource.class

**Comment by apobekiaris** [comment]
thnks for the suggestion, indeed that are useful tools and know exactly what you mean as I have XAF apps that feed from web services, 

At the moment I do not have something ready to be a module unfortunately.   I can describe a possible solution though. You create an api that will notify on external input emits amd you combine them with emits from the needed XAF events such an object getting respecting some king of throttling strategy.

I cannot promise when I can release such a package I will update this post once I have something.

**Comment by sheldmandu** [comment]
Simple solution I'm using for now (which is obviously not as nice usability wise as auto-populating the grid as the user scrolls) is using a ViewController with NextPage/PrevPage actions.  The key has been not using the WindowController as suggested in all DX articles on the subject but using the ViewController as in the ViewController you have all the action event handlers and they can set common properties like CurrentPage.  Works well.  Just thought VirtualServerModeSource based ListView would be a nice generic solution for people.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by beneton2003** [comment]
Hi guys. Is there any news or some best practice about the problem described in this topic? i am trying to implement some API for my project, but API need some date range and return results only by 20 records. Is there any ways to make pagination? or maybe something new in the DE solutions?

**Comment by apobekiaris** [comment]
if u want the pagination offered from XAF component you need to persist the endpoint data, this what I do in my own apps (a hybrid strategy works pretty well in very complex applications)
