### ISSUE TITLE
ViewEditMode module as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#356]
Currently this functionality exists in ViewEditModeController which needs to be simplified. The controller lives in the Xpand.Persistent.Base.dll and will be removed from there once the nuget package released. It will however installed in all modules that use directly this functionality such as Dashboard, MasterDetail, Email, Logic. ExcelImporter.

**Comment by apobekiaris** [comment]
Lab build is out 

https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/src/Modules/Agnostic/ViewEditMode

**Comment by expand** [comment]
The DevExpress.XAF includes commit [ViewEditMode release #356](https://github.com/eXpandFramework/161949491/commit/df74308170b6e1d9a268e275ca54d93bec11c2f3) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.4](https://github.com/eXpandFramework/lab/releases/18.2.703.4) includes commit [Install ViewEditModeModule #356](https://github.com/eXpandFramework/153812905/commit/2365926922ec1277e48354387cbd22e3198a832f),[Remove ViewEditModeController #356](https://github.com/eXpandFramework/153812905/commit/a19d8ec7c95b2a7399f2f0c4cde93095894f4773) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
