### ISSUE TITLE
nullref @modeldifferencewin

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#357]
Hi tolis,

i got nullRef exception while  modeldifference opening. 
Xpand.ExpressApp.ModelDifference.Win.Controllers.ModelEditorTemplateViewController line:143

what if modelEditorPropertyEditor.Control is null then?

**Comment by apobekiaris** [comment]
apparently there reasoning for this is that there was an previous error resulted in a null Control?

if you can be more specific like how to repro this.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
