### ISSUE TITLE
DevExpress.XAF reactive modules reference System Windows assemblies

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#358]
System.Reactive may introduce this dependency due to the ObserveOn overload, it is safe to manually remove.

**Comment by expand** [comment]
The DevExpress.XAF includes commit [Remove unsued references #358](https://github.com/eXpandFramework/161949491/commit/090e66218be5b3e2323fc1b8244f030e00097657) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
