### ISSUE TITLE
Debugging does not work for the XAF.Modules packages

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#359]
**Describe the bug**
Nuget debugging as describe in [HowToDebug](https://github.com/eXpandFramework/eXpand/wiki/HowToDebug) does not work because VersionConverter does not rewrite symbols.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [Debugging does not work for the XAF.Modules packages #359](https://github.com/eXpandFramework/161949491/commit/13b56eab8c7c895add9bdd9d6aced5c350399c7e) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.4](https://github.com/eXpandFramework/lab/releases/18.2.703.4) includes commit [Update Nuget packages #359](https://github.com/eXpandFramework/153812905/commit/5fa4112ac10ea9201e6ff4e814733c4511036dbc) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
