### ISSUE TITLE
ShowNavigationItem

### ISSUE THREAD

**Issue by utwasim981** [eXpandFramework/eXpand#360]
can you advise a solution for below:

Actions with the duplicate 'ShowNavigationItem' identifier are detected in the 'XXX.Module.Win.Controllers.General.NavigationItemController' and 'Xpand.ExpressApp.Security.Controllers.ShowNavigationItemController' controllers.

**Comment by apobekiaris** [comment]
you can always disable controllers resulting in bad behaviour with a call like
``cs
XpandModuleBase.DisableControllers(typeof(Xpand.ExpressApp.Security.Controllers.ShowNavigationItemController));
```

this will probably work around the issue however a root fix is prefered. So my guess is that yours and the Xpand controller use the same base type `DevExpress.ExpressApp.SystemModule.ShowNavigationItemsController.  So to fix this modify your controller to derive from `Xpand.ExpressApp.Security.Controllers.ShowNavigationItemController` instead of  DevExpress.ExpressApp.SystemModule,ShowNavigationItemController1

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
