### ISSUE TITLE
Issue with ViewShortcutProcessor

### ISSUE THREAD

**Issue by sheldmandu** [eXpandFramework/eXpand#361]
**Describe the bug**
ViewShortcutProcessor causes an exception when trying to show a NonPersistentObject DetailView from the navigation item as shown in:
https://documentation.devexpress.com/eXpressAppFramework/113471/Task-Based-Help/Business-Model-Design/Non-Persistent-Objects/How-to-Display-a-Non-Persistent-Object-s-Detail-View-from-the-Navigation

Issues is in:
https://github.com/eXpandFramework/eXpand/blob/18.2/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/ViewShortCutProccesor.cs

You get:
Unable to cast object of type 'DevExpress.ExpressApp.NonPersistentObjectSpace' to type 'DevExpress.ExpressApp.Xpo.XPObjectSpace'.

   at Xpand.ExpressApp.ViewShortCutProccesor.GetObjectKeyCore(IObjectSpace objectSpace, Type type, String objectKeyString)
   at Xpand.ExpressApp.ViewShortCutProccesor.Proccess(CustomProcessShortcutEventArgs shortcutEventArgs)
  ....

Essentially you shouldn't be casting to XPObjectSpace as you'll get an invalid cast exception above at runtime.

**To Reproduce**
Try to show a detail view of non-persistent object from the navigation with a key set as per the DX tutorial.

**Expected behavior**
Tutorial should work as expected

If you could provide some info on how to work around the issue (i.e. disable the behaviour without upgrading to the latest version of xpand would be great.

**Comment by sheldmandu** [comment]
Also, Controller should have 2 Ls in it. Might be worth fixing at the same time.  There's actually about 5 misspelt like that in the codebase. Search for "Controler" with a single L to find them.

**Comment by sheldmandu** [comment]
I tried setting the Active to false to deactivate the controller by using another controller and doing that in OnFrameAssigned but that didn't work.

**Comment by apobekiaris** [comment]
did you tried the `ViewShortcutProccesor` detailview model attribute?

https://github.com/eXpandFramework/eXpand/blob/b5085db4d9136bcf02ae299fe71e42200b063181/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/ViewShortCutProccesor.cs#L55-L58

**Comment by sheldmandu** [comment]
@apobekiaris No, not quite sure how to use what you suggested.  What do I need to do to disable that  In any case there's definitely a bug that should be fixed.  

What does the ViewShortCutProccessor actually do?  On having a brief look it has something to do with being able to specify dynamic criteria in the ObjectKey instead of an actual, key?  That really should just be in it's own property like ObjectCriteria rather than mixed into the ObjectKey as that seems like a bit of a hack.

**Comment by apobekiaris** [comment]
yes you are right it should use a separate attribute, I will keep a not when I decouple the functionality.

What I meant before was.

![image](https://user-images.githubusercontent.com/159464/55672759-5b890580-58a7-11e9-84c7-28357f07bb32.png)

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.4](https://github.com/eXpandFramework/lab/releases/18.2.703.4) includes commit [Correct spelling #361](https://github.com/eXpandFramework/153812905/commit/d41b141c6384fe86be06d68ce1d27c50e7249c60),[ViewShortCutProccesor: remove XPO dependency #361](https://github.com/eXpandFramework/153812905/commit/7248e228f315566252679c853228967a47151438) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
