### ISSUE TITLE
AudiTrail - Cannot have various auditing levels at once.

### ISSUE THREAD

**Issue by dsikic** [eXpandFramework/eXpand#362]
**Describe the bug**
Cannot have rules in AudiTrail for descendant classes that overrule the general PersistentBase rule. For example, if general PersistentBase rule says LightWeight... then definining rules will Full auditing mode (or any other) will not work. 

**To Reproduce**
Run my sample and review screenshots. Notice that if Lightweight_mode_for_all_objects is set to Lightweight for PersistentBase. Other Rules defined upon classes which derive from PersistentBase do not have effect. For example, Audit_Customer with member age (under MembersContextGroup), set to full does nothing. The system only starts to work if the Persistentbase rule is set to full.

**My attached sample has everything implemented. Only thing is that connection string depends upon local SQL instance.**

1. Open AudiTrail demo
2. Open Model
3. Set Audit_Customer rule in AudiTrail node to AuditingMode = Full
4. Make sure the AuditTrailMembersContextGroup is set to Age
5. Try to change Age on an existing customer and it will not log as it should. 

**Expected behavior**
All classes should log Creations and basic CRUD operations in lightweight mode. Certain classes when explicitly defines as Customer is above, should log more. 

**Screenshots**
See Zip. My Sample 

**Desktop (please complete the following information):**
Tested on WinForms.

[Audit Trail issue.zip](https://github.com/eXpandFramework/eXpand/files/3053965/Audit.Trail.issue.zip)

**Additional context**
This is based upon my own expand branch but I don't believe it is too far behind you. I cannot fast forward it at the moment, it's on 18.2.5 or 6 . I also have a blank fields problem when loading XpandAuditDataItems in XAF, but they do save fine into SQL. May or may not be related.

**Comment by apobekiaris** [comment]
Thanks for the detailed report give me some time to research and I get back to you.

**Comment by apobekiaris** [comment]
For your scenario to work you have to configure the rule order. So you need to execute first the rule for all objects and after the rule for Customer to override the `AuditingMode`. So set the Index to 0 and run it.

in my tests I created a new Customer and save it. afterwards i change its birthday and saved then its age and saved. I got 2 entries as expected.

![image](https://user-images.githubusercontent.com/159464/55792199-cb2a0b00-5ac8-11e9-895c-305917f66a31.png)

for Employer which the all objects rule is applied I got only one as expected.

![image](https://user-images.githubusercontent.com/159464/55792264-f280d800-5ac8-11e9-908a-49e5b5a35b4c.png)

is this what you need?

**Comment by dsikic** [comment]
Hi Apostolis,

Thank you. I don’t believe that the property name (Age) and value changes (0 -> 1) were logged in your scenario.
Shouldn’t they have been, given that you set the auditing mode to full?

Just to confirm, you’re saying that the general PersistentBase rule should be at index 0, and lower rules (higher index) are applied afterwards to alter the behavior?
Or did I understand that backwards?

Thanks.
Denis

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by apobekiaris** [comment]
>. I don’t believe that the property name (Age) and value changes (0 -> 1) were logged in your scenario
what to do to convince you Denis? :) I sent screenshots already. 

>Shouldn’t they have been, given that you set the auditing mode to full?
do not make sense here also, yes they full audited respecting the configured member context. What do you expected to do?
>Just to confirm, you’re saying that the general PersistentBase rule should be at index 0, and lower rules (higher index) are applied afterwards to alter the behavior?
the rules are sorted by index.


ps: for the layouts on my screenshots i removed the Model.Views node differences and added this code to both Customer and Employee
```cs
private XPCollection<XpandAuditDataItemPersistent> _auditTrail;
        public XPCollection<XpandAuditDataItemPersistent> AuditTrail => _auditTrail ?? (_auditTrail = XpandAuditedObjectWeakReference.GetAuditTrail(Session, this));
```

**Comment by dsikic** [comment]
😊 In your pictures the property name was blank, so I’m guessing so were the values. 😝
[cid:image001.png@01D4EED2.699D3400]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by apobekiaris** [comment]
do these properties get filled without the Xpand AuditTrail? from what I see in the XAF code base they never assigned a value.

**Comment by dsikic** [comment]
99% sure they do in full mode.
I’ll test and reply back soon.

On Apr 10, 2019, at 11:44, Apostolis Bekiaris <notifications@github.com<mailto:notifications@github.com>> wrote:


do these properties get filled without the Xpand AuditTrail? from what I see in the XAF code base they never assigned a value.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
