### ISSUE TITLE
VersionConverter cannot resolve DevExpress assemblies 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#364]
**Describe the bug**
Projects using VersionConverter package cannot build if DevExpress is not in GAC

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [VersionConverter cannot resolve DevExpress assemblies #364](https://github.com/eXpandFramework/161949491/commit/204fbe42812bbdd2512e1071d127f3115e2d412f) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

**Comment by expand** [comment]
eXpand.lab Installer [18.2.703.5](https://github.com/eXpandFramework/lab/releases/18.2.703.5) includes commit [Update Nugets packages #364](https://github.com/eXpandFramework/153812905/commit/2af2948ee52d8a26fb8d6fafa13d26110f9591c5) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
