### ISSUE TITLE
Dependent libs are missing from nuspec

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#366]
all reactive packages need Ryder.dll

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [Dependent libs are missing from nuspec #366](https://github.com/eXpandFramework/DevExpress.XAF/commit/2e773c7d624267f1e797f9e8b640bfde50199236) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
