### ISSUE TITLE
MasterDetail as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#367]
The related controller lives in `dashboard module` and is used from Xtradashboard, ExcelImporter. 

Once the new package released the dashboard module controller will be removed and the package will be installed only to modules that using it. The same approach was used for the other [DevExpress.XAF modules](https://github.com/eXpandFramework/DevExpress.XAF)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [MasterDetail as standalone package #367](https://github.com/eXpandFramework/DevExpress.XAF/commit/acd3dc198e58d10ca3bc75966b9f5c5e10d72bbf) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [MasterDetail as standalone package #367](https://github.com/eXpandFramework/DevExpress.XAF/commit/95e4fbf1b4930edd637482e71d327fb68097e29a) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [18.2.703.6](https://github.com/eXpandFramework/eXpand.lab/releases/18.2.703.6) includes commit [Integrated MasterDetail, Autocommit, SupressConfirmation #372 #370 #367](https://github.com/eXpandFramework/eXpand.lab/commit/c01bd70b656685380016699c01183dc805568d2e) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
