### ISSUE TITLE
Executable file of eXpandFramework-18.2.703.0.exe

### ISSUE THREAD

**Issue by david0villa** [eXpandFramework/eXpand#368]
**Question**
Hi,

I am normally using executable file to install eXpandFramework. However I did not see version
eXpandFramework-18.2.7 which I am going to download Devexpress 18.2.7 too. 
Can anyone advice me how to build/install locally if executable file is not available  ?

**Comment by apobekiaris** [comment]
Hi

sorry for missing this ticket, please feel free to ping me again if I delay. 

I am not sure why you failed to find how the installation works now. It's on the release page.

http://releases.expandframework.com

![image](https://user-images.githubusercontent.com/159464/56178835-51d07200-600c-11e9-93d1-95f8abd70bfb.png)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
