### ISSUE TITLE
Incorrect case for XafApplicationExtensions.CreateCustomObjectSpaceprovider

### ISSUE THREAD

**Issue by sheldmandu** [eXpandFramework/eXpand#369]
The method should have Provider starting with a big P instead of a small p.  i.e. CreateCustomObjectSpaceProvider instead of CreateCustomObjectSpaceprovider.

**Comment by expand** [comment]
eXpand.lab release [18.2.703.6](https://github.com/eXpandFramework/eXpand.lab/releases/18.2.703.6) includes commit [Incorrect case for XafApplicationExtensions.CreateCustomObjectSpaceprovider #369](https://github.com/eXpandFramework/eXpand.lab/commit/8fe73ea8d35d0417f733eb16b195532630122787) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
