### ISSUE TITLE
AutoCommit as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#370]
The functionality is now in the controllers AutoCommitController which live in System, System.Win, System.Web. 

When the package is released the controllers will be removed and the package will be installed only in the modules that make use of it. For this case only the ExcelImporter uses the attribute.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [AutoCommit as standalone package #370](https://github.com/eXpandFramework/DevExpress.XAF/commit/0880fb15ce46d5b8c00cf5138ac70a663dd291e4) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [18.2.703.6](https://github.com/eXpandFramework/eXpand.lab/releases/18.2.703.6) includes commit [Integrated MasterDetail, Autocommit, SupressConfirmation #372 #370 #367](https://github.com/eXpandFramework/eXpand.lab/commit/c01bd70b656685380016699c01183dc805568d2e) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
