### ISSUE TITLE
SuppressConfirmation as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#372]
The functionality now lives in System, System.Win, System.Web at SupressConfirmationController. 

Once the nuget package released those controllers will be removed and the package will be installed only from the modules that using it directly as the `ExcelImporter`

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [SupressConfirmation as standalone package #372](https://github.com/eXpandFramework/DevExpress.XAF/commit/a919905722e289bdc476f8ddcc6b2932f1a0331a) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [18.2.703.6](https://github.com/eXpandFramework/eXpand.lab/releases/18.2.703.6) includes commit [Integrated MasterDetail, Autocommit, SupressConfirmation #372 #370 #367](https://github.com/eXpandFramework/eXpand.lab/commit/c01bd70b656685380016699c01183dc805568d2e) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
