### ISSUE TITLE
ModelAdapterContexts Grid

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#374]
Hi,

I have a problem ModelAdapterContexts esp. the Grid.

If I set the values in the ModelAdapterContexts\Default\Grid
PreviewLineCount = 5
OptionsView.ShowPreview = false

it has no effect for the Grids.

Setting the values in a special ListView it works but only for one value:
The "PreviewLineCount = 5" works.

The "OptionsView.ShowPreview = false" works only if I use an ListViewController with the "ApplyModel();". Before the Command the value is always "true".

**Comment by apobekiaris** [comment]
Hi,

With the SystemTester solution I failed to reproduce it. Can you post a sample?

**Comment by CWolffIF** [comment]
Hi,

I tested it with the XVideoRental. The problem lies in the standard of the OptionsView.ShowPreview. It is default "true" and if you set it to "false" it is automaticly set to "true".
1. In the running app open the Modeleditor and set (ModelAdapterContexts Grid)  OptionsView.ShowPreview=false (see Model1.png)
![Model1](https://user-images.githubusercontent.com/43132306/56454445-d2ff7000-6350-11e9-8fd4-d3c60007585f.PNG)

2. Open the Listview: The Preview is visible (that is wrong) (see Cust1.png)
![Cust1](https://user-images.githubusercontent.com/43132306/56454444-d2ff7000-6350-11e9-9d16-0d8aa8db5f54.PNG)

3. Open the ModelEditor (ModelAdapterContexts Grid)  and automaticly the OptionsView.ShowPreview=true (see Model2.png)
![Model2](https://user-images.githubusercontent.com/43132306/56454443-d2ff7000-6350-11e9-8e8b-6d181c524417.PNG)

**Comment by apobekiaris** [comment]
which view are you testing?

**Comment by CWolffIF** [comment]
I used the Customer_ListView (not the banded View)

**Comment by apobekiaris** [comment]
plans are to release a standaalone module for this functionality so I won't purse this case further

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
