### ISSUE TITLE
Issue with ApplicationHelper

### ISSUE THREAD

**Issue by sheldmandu** [eXpandFramework/eXpand#375]
Hi @apobekiaris,

In implementing the Hangfire integration I've encountered an issue with the latest version of Expand in that I get exceptions thrown when I start the Application.

The issues seems to stem from the fact that I essentially have 2 instances of an XafApplication.  One is a subclass of WinFormsApplication that actually runs and one is the ServerApplication that is inherited from XafApplication.  The reason I need 2 applications is because the BackgroundJobServer needs the ServerApplication that uses XPObjectSpace instead of the SecuredObjectSpace that's used in the WinFormsApplication.

Essentially what we get is a casting exception as your code tries to cast the ServerApplication that derives from XafApplication to WinFormsApplication which it's not a subclass of.  This happens in the NotifyIconController on line 85 because (WinApplication) ApplicationHelper.Instance.Application is called.

However on investigation the actual issue is due to how ApplicationHelper is implemented.  It appears that the Expand SystemModule essentially calls ApplicationHelper.Initialize method and what is happening is when the SystemModule is instantiated in the ServerApplication AFTER the same thing is done in the WinApplication it essentially sets the instance of the application in the ApplicationHelper to the ServerApplication instance (which derives from XafApplication).

**Comment by apobekiaris** [comment]
I am not certain to what the problem.

>I essentially have 2 instances of an XafApplication.

so my guess is that they should not live in the same AppDomain, so how do you get a casting error on instances that should not co-exist. Note that eXpandFramework support client server e.g. workflow module.

Please post details.

**Comment by sheldmandu** [comment]
Hi @apobekiaris Essentially what I'm trying to do is have each Client application being able to act as a BackgroundJobServer for processing Hangfire tasks.  This is somewhat different to having a single job server or job server installed on multiple servers, but I think can be quite effective for distributing background jobs.

The problem however is because each job runs in a separate thread, you need to have the application used by the BackgroundJobServer built in a way that is thread-safe.  Because of this you cannot use the SecuritySystem as it is NOT thread-safe (as advised by DevExpress in the Note on the Workflow Server page).  Even if you have a thread-safe data layer the SecuredObjectSpaceProvider doesn't seem to operate in a thread-safe manner.

To overcome this (which is also needed for the standalone BackgroundJobServer) I created a second application called ServerApplication which inherits XafApplication rather than WinFormsApplication.  For the standalone BackgroundJobServer this is perfectly fine as it's the only XafApplication.  In the client however I needed to use the ServerApplication for the BackgroundJobServer and the normal derivative of WinFormsApplication to run the actual UI.

As you said it seems that Expand assumes there will only be a single instance of an XafApplication in the executable and that is what's causing the problem.  Interestingly, this IS NOT a problem in Expand 17.2.7.4 but IS a problem in the latest version of Expand.

The simple fix is the add the check for _application == null in the Initialize method that was taken out in https://github.com/eXpandFramework/eXpand/commit/55a65df1427bc62fe493ca07924c7db4a1701a28#diff-09a5bb64b47d1957e5ccb277809b6d27

That said however there's of course a good possibility that something won't work as expected in the ServerApplication used in one of the background threads.

I'm not sure making the assumption that there will only ever be a single instance of an application in an executable is the right assumption to make.  Do you know if core XAF make that assumption anywhere in their code?  I've searched and looked through core XAF code and I don't see anywhere a singleton static instance being used.  The is exactly the kind of problems relying on singletons instead of using dependency injection causes.

**Comment by apobekiaris** [comment]
Your design sounds hacky and cannot moify the source to support it. The check removed for certain reasons and if you like to mofify the private class u may use reflection and do it.

fyi. about threads

xafapplication is not a thread safe class which means that you will have problems accessing share data of this class. However you can access methods that do not use state such as CreateObjectSpace. You can a Thread Safe Datalayer in a static class ctor, you expose it in a static property. Now, you use that datalayer to create the application ObjectSpaceprovider and you use the same ThreadSafe datalayer from the threads of your jobs.

This is the correct configuration, I have apps in production working with 10000 requests/sec for weeks in a row.

**Comment by sheldmandu** [comment]
I agree having a second application instance based directly on XafApplication probably isn't ideal.  That said, do you think assuming that there will only be a single instance of the XafApplication object is right?  I don't know the core XAF base well enough but from what I saw it didn't look like core XAF uses that assumption.  I mean it's not a big issue for me and I don't really need to have background jobs running on each client, but just not sure if it's the right assumption to make.

In terms of thread safety, indeed the only reason I need the application is to call CreateObjectSpace, but it's indeed good to know that it's not thread-safe.

Can you elaborate about what you mean with regard to ThreadSafeDataLayer and ObjectSpaceProvider... wouldn't passing threadSafe=true when instantiating XPObjectSpaceProvider do the the same thing so that underneath it will in turn create a ThreadSafeDataLayer?

**Comment by sheldmandu** [comment]
Are you saying that rather than passing around the application I should just pass around an ObjectSpaceProvider that I create separately and not as part of the Application?  If that's the case I presume I'm going to have issues when I have both Persistent and NonPersistent object spaces or I'll need to write something to essentially replicate how XafApplication creates ObjectSpaces in CreateObjectSpaceCore.

**Comment by apobekiaris** [comment]
hmm I will try to be understandable feel free to ask.
put somewhere your threads and your 1 WinApplication instance can access (remove parts that you do not need).

Focus on the `LazyObjectSpaceProvider`, `CreateUOW`
```cs
public static class DataLayer{
	    static DataLayer(){
	        CachedDataStoreProvider.Factory=() => new CachedDataStoreProvider(ConnectionString);
	    }

	    public static  XPObjectSpaceProvider LazyObjectSpaceProvider{
	        get{
	            if (_lazyObjectSpaceProvider == null)
	                _lazyObjectSpaceProvider = NewLazyObjectSpaceProvider();
	            return _lazyObjectSpaceProvider.Value;
	        }
	    }


	    private static Lazy<XPObjectSpaceProvider> NewLazyObjectSpaceProvider(){
	        return new Lazy<XPObjectSpaceProvider>(
	            () => new FastObjectSpaceProvider(CachedDataStoreProvider.Instance,true));
	    }

	    public static void Reset(){
	        if (_lazyObjectSpaceProvider != null){
                LazyObjectSpaceProvider.Dispose();
                _lazyDataLayer.Value.Dispose();
	        }
	        _lazyDataLayer = NewLazyDataLayer();
	        _lazyObjectSpaceProvider = null;
	        CachedDataStoreProvider.ResetDataCacheRoot();
	    }

	    [SuppressMessage("ReSharper", "NotAccessedVariable")] 
        private static Lazy<IDataLayer> _lazyDataLayer=NewLazyDataLayer();

	    private static Lazy<IDataLayer> NewLazyDataLayer(){
	        return new Lazy<IDataLayer>(() => {
	            var workingStore = CachedDataStoreProvider.Instance.CreateWorkingStore(out _);
	            var dictionary = XpoTypesInfoHelper.GetXpoTypeInfoSource().XPDictionary;

	            return new ThreadSafeDataLayer(dictionary,workingStore);
	        });
	    }

	    private static string _connectionString;
	    private static Lazy<XPObjectSpaceProvider> _lazyObjectSpaceProvider;

	    public static UnitOfWork CreateUOW(){
	        return (UnitOfWork)LazyObjectSpaceProvider.CreateObjectSpace().Session();
	    }

	    public static string ConnectionString{
	        get{
                
	            if (_connectionString != null)
	                return _connectionString;
	            string production = null;
	            if (Environment.MachineName != "APO-BEK")
	                production = "_production";
//	            if (Environment.MachineName == "APO-BEK-TESTER1")
//	                production = "_tester";
	            var connectionStringParser = new ConnectionStringParser(ConfigurationManager.ConnectionStrings[$"ConnectionString{production}"].ConnectionString);
//                connectionStringParser.AddPart("Pooling","true");
	            return connectionStringParser.GetConnectionString();
	        }
	        set => _connectionString=value;
	    }
	}
```

1. use the `CreateUOW` from your job threads 
2. use the `LazyProvider` from your winap
```cs
protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args) {
            args.ObjectSpaceProviders.Add(DataLayer.LazyObjectSpaceProvider);
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));
        }
```

now u use the same thread safe datalyer for all threads (UI and background) and u ready to go.

**Comment by apobekiaris** [comment]
the posted example uses caching which might not be appropriate for you case, but as I said this from an app in production you need to modify accordingly.

**Comment by sheldmandu** [comment]
What's wrong with just doing:
`
        protected override void CreateDefaultObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args)
        {
            args.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(args.ConnectionString, args.Connection, true));
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider(TypesInfo, null));
}
`
Note that the last argument to the XPObjectSpaceProvider is set to true for threadSafe.

**Comment by apobekiaris** [comment]
your threads must use the same Datalayer where it lives with this approach? is it easily accessible? if no u might put it on a static class and make it lazy so u sure that only one instance will ever created, so u might end with a class like I posted

**Comment by sheldmandu** [comment]
What do you mean by your threads must use the same Datalayer where it lives? and what do you mean by is it easily accessible?

in all my jobs I just have the application instance accessible and from there I just go Application.CreateObjectSpace to create the OP and then use it like I would in any controller or service to perform data manipulation.

**Comment by sheldmandu** [comment]
Oh... I think I get what you're trying to say... I don't really need to use the DataLayer directly or use a singleton and I don't really like using static variables unless necessary, I prefer to use DI where possible.  In my instance I add the application into the Autofac IoC container and all the classes that implement jobs have a constructor that takes the XafApplication instance which Autofac autowires for me.  From there I just use Application.CreateObjectSpace.

**Comment by apobekiaris** [comment]
design as u like, bottom line is that from a thread u can safely `Application.CreateObjectSpace` if datalayer is thread safe without having extra applications for each thread.

**Comment by sheldmandu** [comment]
Yes, that's what Iv'e done.  Can you please consider if it would be feasible to remove the assumption that there is only a single application instance so it's in line with the core XAF codebase. I couldn't find anywhere in the DX codebase that such an assumption is made.

**Comment by apobekiaris** [comment]
WebApplication.Instance is the first thing that comes into my mind.

each httpsession has only one instance and many threads create WeApplication.Instance.CreateObjectspace 

this is the same as I suggested.

**Comment by sheldmandu** [comment]
I don't have a WebApplication at all.  What I'm saying is I'm not sure the assumption that there is only ever a single Application in an exe is appropriate as DX don't seem to make that assumption in their code.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
