### ISSUE TITLE
Excel Importer : Excel Map columns - Error in web 

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#377]
**Describe the bug**
In web client, when i click on excel map i have a error (see attachment).
Error : (translated value)
Asynchronous operations are not allowed in this context. A page that starts an asynchronous operation must have the attribute Async set to true, and an asynchronous operation can only be started on a page before the PreRenderComplete event.

**To Reproduce**
1. Create a Excel Import record
2. Select a file
3. Select Always Create
4. Click on Excel Map amd see error

[ExcelImportError.txt](https://github.com/eXpandFramework/eXpand/files/3104867/ExcelImportError.txt)

BR
ISA

**Comment by isatahiri** [comment]
Please note that i'm using the version :18.2.704.0

**Comment by apobekiaris** [comment]
I guess that you already checked the `Page Async=True` so you might want to add this setting to your web.config.

```
  <system.web>
    <httpRuntime targetFramework="4.6.1"/>
```

let me know if this works please

**Comment by isatahiri** [comment]
Ok will check that asap and let you know. 

I see that you added "Standalone_XAF_Modules" tag. Note that i only installed the 18.2.704.0 with the powershell command. I did not install any other module. ( 
Am I missing somthing ? 

BR
ISA

**Comment by apobekiaris** [comment]
ExcelImporter uses the XAF modules and plans are to become one of them.

https://github.com/eXpandFramework/eXpand/blob/64520e8a14593d904c02c5cc4facf1f33fa0c8c2/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/ExcelImporterModule.cs#L28-L37

**Comment by isatahiri** [comment]
"ExcelImporter uses the XAF modules and plans are to become one of them" : 
That means taht i have to add "DevExpress.XAF" via nuget to make it work properly ?

**Comment by apobekiaris** [comment]
if u install ExcelImporter from nuget this is done already, it nothing more than a dependent assembly treat it like this? let the compiler tell u what it needs else nuget/msbuild are smart enough to handle dependencies.

**Comment by isatahiri** [comment]
After checking i had the same issue. 
Please see webconfig. 

Note also : This appened after upgrading, so nothing changed in my project. 
[Web.config.txt](https://github.com/eXpandFramework/eXpand/files/3124810/Web.config.txt)

I you need the project please let me know. 

BR
ISA

**Comment by apobekiaris** [comment]
config looks fine, yes please post your project

**Comment by isatahiri** [comment]
Here we go : 
https://1drv.ms/u/s!Amh26IFxNEz6lNd-z8532Xnh6lnxOw

It has been tested we Edge.
The menu is here : 
![image](https://user-images.githubusercontent.com/41955268/56862797-112f0c00-69af-11e9-8173-157f9c5cf612.png)

**Comment by apobekiaris** [comment]
![image](https://user-images.githubusercontent.com/159464/56869392-c3df8880-6a08-11e9-96d5-510d6d5066e1.png)

**Comment by isatahiri** [comment]
Its reactivated : https://1drv.ms/u/s!Amh26IFxNEz6lNd-GqO2E_B9btCzig

Sorry i thought you already took it.

Maybe this is a more price message : 

Exception occurs while assigning the'XpandListView, ID:ExcelImport_ListView' view to WebWindow: 
Impossible to start an asynchronous operation at the moment. Asynchronous operations can only be started from a manager or asynchronous module, or during certain events in the page life cycle. If this exception has been removed during the execution of a page, check that it is marked as follows: <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is not usually supported within ASP.NET request processing. Instead, the asynchronous method must return a task, and the caller must wait for it.

Translated with www.DeepL.com/Translator

**Comment by apobekiaris** [comment]
now i got it thnks

**Comment by isatahiri** [comment]
ok i'll stop sharing in 15minutes

**Comment by apobekiaris** [comment]
feel free to send me private url in my mail, its on my github profile

**Comment by apobekiaris** [comment]
but now i have it there is no need

**Comment by isatahiri** [comment]
Will you deliver 18.2.8 version and include this patch ? 
I see that in the lab you are jumping from 18.2.7 to 19.1.

**Comment by apobekiaris** [comment]
unfortunately no I do not have infrastructure to support multiple major versions at the moment, let me see whats going on with your project first

**Comment by apobekiaris** [comment]
it might be possible to projectconverter and build custom though it should work as there are no breaking changes

**Comment by isatahiri** [comment]
yep :-) No worries i'll manage to align with you avalaible versions

**Comment by apobekiaris** [comment]
>Exception occurs while assigning the'XpandListView, ID:ExcelImport_ListView' view to WebWindow:
Impossible to start an asynchronous operation at the moment. Asynchronous operations can only be started from a manager or asynchronous module, or during certain events in the page life cycle. If this exception has been removed during the execution of a page, check that it is marked as follows: **<%@ Page Async="true" %>**. This exception may also indicate an attempt to call an "async void" method, which is not usually supported within ASP.NET request processing. Instead, the asynchronous method must return a task, and the caller must wait for it.

from what i see u did not follow this message. the default.aspx declaration should be 

<%@ Page Language="C#" AutoEventWireup="true" Inherits="Default" EnableViewState="false"
    ValidateRequest="false" CodeBehind="Default.aspx.cs" Async="true" %>

this is a async module.

**Comment by apobekiaris** [comment]
I did manage to repro the exception in your project and when i used Async="true" i manage to map with no problems

**Comment by isatahiri** [comment]
so i should put that in the default.aspx ?

**Comment by apobekiaris** [comment]
yeah replace the existing declaration on top of the page

**Comment by isatahiri** [comment]
Sorry about that. 

I you have my project up, could you test it in winform and let me know if you have the same issue as declared in #379 ?

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [System.InvalidOperationException: An asynchronous operation cannot be started at this time #394 #377](https://github.com/eXpandFramework/DevExpress.XAF/commit/c529a9bf69fb55f119457a9c0f89825492a3404b) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Hi Tolis,

Here is a interesting message from DevExpress : 
https://www.devexpress.com/Support/Center/Question/Details/T749499/office-module-asp-error-on-loading-with-chrome

> > Exception occurs while assigning the'XpandListView, ID:ExcelImport_ListView' view to WebWindow:
> > Impossible to start an asynchronous operation at the moment. Asynchronous operations can only be started from a manager or asynchronous module, or during certain events in the page life cycle. If this exception has been removed during the execution of a page, check that it is marked as follows: **<%@ Page Async="true" %>**. This exception may also indicate an attempt to call an "async void" method, which is not usually supported within ASP.NET request processing. Instead, the asynchronous method must return a task, and the caller must wait for it.
> 
> from what i see u did not follow this message. the default.aspx declaration should be
> 
> <%@ Page Language="C#" AutoEventWireup="true" Inherits="Default" EnableViewState="false"
> ValidateRequest="false" CodeBehind="Default.aspx.cs" Async="true" %>
> 
> this is a async module.

I open this ticket because I have issue loading the RichEdit in the ASP (new Office module of XAF)

Any suggestion to manage this ? 

BR
ISA

**Comment by isatahiri** [comment]
Sorry this ticket is private (customer requirement) so i show you the message from DevExpress : 
![image](https://user-images.githubusercontent.com/41955268/60597618-83efa580-9dab-11e9-96c1-646dd90f9b39.png)

As my issue seems to be out of the Async topic, this is not really urgent but I think we have to take in the consideration the highlighted part.

**Comment by apobekiaris** [comment]
this requirement is hard coded and no way to avoid it at the moment. Though as I later discover it can be relaxed as it is missleading. The actual problem is somewhere else and async flag most probably not need.

so Anatol there says pretty much the same.

>Nevertheless, it appears that the issue occurs earlier and is unlikely related to asynchronous requests. Your callstack starts with the WebApplication.DisposeInstance method. By default, this method is called only in the Global.Session_End event handler. So, it appears that the user's session is unexpectedly shutdown when the user clicks

**Comment by apobekiaris** [comment]
so why don't u provide the logs the guys asked u to and see what their response first

**Comment by isatahiri** [comment]
I will go deeper into it by august as this project does not need excelimporter at the moment. pretty busy before my holidays next week :-)

I'll keep u posted when i have news.

**Comment by apobekiaris** [comment]
yeah keep me posted please, although XAF does not official support asych due to obvious reasons we have no alt here, and I am pretty sure that XAF team will be most helpful to resolve the problem.

**Comment by apobekiaris** [comment]
see #661
