### ISSUE TITLE
Excel Importer - Win - Toast notification appears twice

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#378]
Hello,

Version : 18.2.704.0
If you create a import and click on import, you'll see the toast nofication twice : 
![image](https://user-images.githubusercontent.com/41955268/56532672-82596400-6556-11e9-8c16-fa92858f2ba3.png)

BR
ISA

**Comment by isatahiri** [comment]
Just a small video if needed showing this. Nothing strange in the debugger. 

https://1drv.ms/v/s!Amh26IFxNEz6lNd7DusoUPK5pHhTTA

Can you reproduce it in your side ? 
BR
ISA

**Comment by apobekiaris** [comment]
yes the fix is on the lab however it will be available on 19.1

**Comment by expand** [comment]
eXpand.lab release [18.2.703.10](https://github.com/eXpandFramework/eXpand.lab/releases/18.2.703.10) includes commit [Excel Importer - Win - Toast notification appears twice #378](https://github.com/eXpandFramework/eXpand.lab/commit/810b7ddb6ad05132cfefeef4c1e202b570df3b13) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Hi,

I installed the  18.2.703.10 and i still have the double notification in the winform. 

BR
ISA

**Comment by apobekiaris** [comment]
i am sorry the bot was mistaken notify about a failed build and from what i see there this issue is link here.
https://github.com/eXpandFramework/eXpand.lab/releases/tag/19.1.200.1

**Comment by isatahiri** [comment]
Thanks it’s now appearing only once
