### ISSUE TITLE
Excel Importer : WIN-  Collumns mapping issue

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#379]
Hello,

The column map does not work like before.
What has been changed ? 

1 : 
Localized caption with spaces inside are not detected so we have to choose them. But this was from the beginning. 

2:
Now we cannot choose the right column in case of situation 1.

The only way is to click on cancel and choose from the main detailview of the Excel Importer 

![image](https://user-images.githubusercontent.com/41955268/56533458-f3e5e200-6557-11e9-95d5-d12f30b5b60c.png)

![image](https://user-images.githubusercontent.com/41955268/56533490-095b0c00-6558-11e9-9a24-689f058b8520.png)

BR
ISA

**Comment by apobekiaris** [comment]
I am not sure what might cause such behavior in the ExcelImporterTester solution there is such a property

https://github.com/eXpandFramework/eXpand/blob/64520e8a14593d904c02c5cc4facf1f33fa0c8c2/Demos/Modules/ExcelImporter/ExcelImporterTester.Module/BusinessObjects/Customer.cs#L31-L35

which is detracted fine, can you provide repro details please?

**Comment by apobekiaris** [comment]
post you xls please

**Comment by apobekiaris** [comment]
I was testing against 19.1 and winforms fails for 19.1 probably because of the new xaf model caching strategies the XAF team implemented. I will see firs that problem and then will test. But please post xls data

**Comment by isatahiri** [comment]
BO : LANGUE
[00-INITDATA-LANGUES.xlsx](https://github.com/eXpandFramework/eXpand/files/3125614/00-INITDATA-LANGUES.xlsx)
BO : PAYS
[01-INITDATA-PAYS.xlsx](https://github.com/eXpandFramework/eXpand/files/3125615/01-INITDATA-PAYS.xlsx)

**Comment by isatahiri** [comment]
I saw that yesterday, but as it was still in beta, did not want to generate a ticket. 
Cool if you could correct this so i'll migrate to 19.1.

BR
ISA

**Comment by apobekiaris** [comment]
give me some time please, I am working on it

**Comment by apobekiaris** [comment]
i had to disable the caching for now using the next code in your Program.cs
```cs
ModelApplicationBase.UseDefaultValuesCache = false;
```

I do not get why u sent me the language xmls as it contains only one column in english. The pays xls contains 2 localized however there are no spaces, though they display fine

![image](https://user-images.githubusercontent.com/159464/56914047-c7801780-6abb-11e9-8fc9-9aaaefaf2b6b.png)

**Comment by isatahiri** [comment]
In the zip a video shoing the error. 

Something to do the deferred deletion apparently. 

[10-INITDATA-PRESTATIONS.xlsx](https://github.com/eXpandFramework/eXpand/files/3128589/10-INITDATA-PRESTATIONS.xlsx)

Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'DevExpress.Xpo.UnitOfWork(142)'.

   à DevExpress.Xpo.Session.Connect()
   à DevExpress.Xpo.Session.get_ObjectLayer()
   à DevExpress.Xpo.Helpers.XPRefCollectionHelper.GetContentWithoutQueryIfPossible()
   à DevExpress.Xpo.XPBaseCollection.BeginLoad(Boolean force)
   à DevExpress.Xpo.XPBaseCollection.Load()
   à DevExpress.Xpo.XPBaseCollection.get_Objects()
   à DevExpress.Xpo.XPBaseCollection.get_Count()
   à System.Collections.ArrayList.InsertRange(Int32 index, ICollection c)
   à System.Collections.ArrayList.AddRange(ICollection c)
   à DevExpress.ExpressApp.Validation.ValidationTargetObjectSelector.FindAggregatedObjects(Object owner)
   à DevExpress.ExpressApp.Validation.ValidationTargetObjectSelector.GetObjectsToValidate(IObjectSpace objectSpace, Object currentObject)
   à Xpand.ExpressApp.Validation.Controllers.ActionExecuteValidationController.ActionBaseOnExecuting(Object sender, CancelEventArgs cancelEventArgs)
   à System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   à DevExpress.ExpressApp.Actions.ActionBase.OnExecuting(CancelEventArgs e)
   à DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)


[2019-04-29-20-03-35.zip](https://github.com/eXpandFramework/eXpand/files/3128615/2019-04-29-20-03-35.zip)

**Comment by isatahiri** [comment]
I do know what to say Tolis.
I restarted the app with new database (from scratch) and did not have the exception anymore.
Note that in my previous video where the error is illustrated i had also a empty database. 

I will do more tests and see if it happens again. 

But the error 1 persists. All captions localized and having spaces are not matched. This you can still test with the file 10-INITDATA-PRESTATIONS.xlsx

BR
ISA

**Comment by isatahiri** [comment]
In the windows "Maps column to Members", Actually, when i try to search the right member but with keyboard i got this error (see VS output  : 
30.04.19 00:36:32.764	'PropertyName' property editor: new value is 'Noim'
30.04.19 00:36:33.306	'PropertyName' property editor: new value is 'Noi'
30.04.19 00:36:33.490	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:34.037	'PropertyName' property editor: new value is ''
30.04.19 00:36:34.597	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:35.079	'PropertyName' property editor: new value is 'Nom d'utilisateur'
30.04.19 00:36:35.339	'PropertyName' property editor: new value is 'Nom de'
30.04.19 00:36:35.446	'PropertyName' property editor: new value is 'Nom de '
30.04.19 00:36:36.825	'PropertyName' property editor: new value is 'Nom de'
30.04.19 00:36:37.022	'PropertyName' property editor: new value is 'Nom d'utilisateur'
30.04.19 00:36:38.567	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:39.392	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:39.395	--------------------------------------------------------------------------------
							Execute action

30.04.19 00:36:39.397		Type: DevExpress.ExpressApp.Actions.SimpleAction
								ID: Save
								Category: Save
								Controller.Name: DevExpress.ExpressApp.Win.SystemModule.WinModificationsController
								Context.Name: Excel Column Map
								Context.IsRoot: True
								Context.SelectedObjects.Count: 1
								Context.CurrentObject: UserName-Nom

30.04.19 00:36:39.478	Action 'Save' done
Exception thrown: 'System.ObjectDisposedException' in DevExpress.Xpo.v18.2.dll
Exception thrown: 'System.ObjectDisposedException' in DevExpress.XtraGrid.v18.2.dll
PME_Affaire.Win.exe Error: 0 : 30.04.19 00:36:41.370	================================================================================
The error occurred:

	Type:       ObjectDisposedException
	Message:    Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'UserName-'.
	Data:       0 entries
	Stack trace:

   à DevExpress.XtraGrid.Views.Base.ColumnView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   à DevExpress.ExpressApp.Win.Editors.XafGridView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   à DevExpress.XtraGrid.Views.Base.ColumnView.OnPostRowException(ControllerRowExceptionEventArgs e)
   à DevExpress.XtraGrid.Views.Grid.GridView.DevExpress.Data.IDataControllerValidationSupport.OnPostRowException(ControllerRowExceptionEventArgs e)
   à DevExpress.Data.BaseGridController.OnPostRowException(Exception exception)
   à DevExpress.Data.CurrencyDataController.EndCurrentRowEdit(Boolean force)
   à DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRowCore(Boolean force)
   à DevExpress.XtraGrid.Views.Grid.GridView.UpdateCurrentRowCore(Boolean force)
   à DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRow()
   à DevExpress.XtraGrid.Views.Base.ColumnView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Grid.GridView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Grid.GridView.DoChangeFocusedRow(Int32 currentRowHandle, Int32 newRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Base.ColumnView.DoChangeFocusedRowInternal(Int32 newRowHandle, Boolean updateCurrentRow)
   à DevExpress.XtraGrid.Views.Base.ColumnView.set_FocusedRowHandle(Int32 value)
   à DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnMouseDown(GridHitInfo hitInfo, DXMouseEventArgs e)
   à DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   à DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   à DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   à DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   à System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   à DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null
 
In the winform it looks like this (message : cannot access to a deleted object)  : 
![image](https://user-images.githubusercontent.com/41955268/56931612-e04ef400-6ae0-11e9-8e5d-4528af682814.png)

Hope this helps. 
BR
ISA

**Comment by apobekiaris** [comment]
I tested this case however as I say there is no change in code to justify this behaviour. Anyway what I found is that the Default Column Map Regex on the ExcelImporter_DetailView 
```
( *)
``` 
is actually responsible. The regex is applied to the Excel columns to help you mapping. More specifically this regex contain a space and a start which meand replace all spaces. So removing it in this case will map automatically. In the next minor I added an extra column `ExcelColumnMapRegex` to display any replacement you might done through Regex and let you test in the UI 

below is with the default Regex on see the differences on 1,2 columns (no spaces)
![image](https://user-images.githubusercontent.com/159464/56943558-b6212480-6b28-11e9-8be8-45891d549515.png)

next one is without any regex

![image](https://user-images.githubusercontent.com/159464/56943597-e49eff80-6b28-11e9-8bf0-4e43f0ad7079.png)

In addition i noticed that you manually added a custom view as nested in the ExcelImporter_DetailView

![image](https://user-images.githubusercontent.com/159464/56943634-1748f800-6b29-11e9-8803-e198bf76a1d9.png)

just a note for this, that this view is not designed to work as nested and you might have issues.

Finally trying to keep issues seperate for better hadling so please answer me in #391

**Comment by isatahiri** [comment]
Many thanks for your research Tolis. 

Concerning you last comment : 
I manually added a custom view as nested in the ExcelImporter_DetailView because by default I do not see the mapping. For this i have to click on map function. For defining the mapping, it's ok to click on map but in order to see the result just before the import, it's very pratical to have a last look of the mapping.  (see picture below and screencast). 

![image](https://user-images.githubusercontent.com/41955268/56992092-95dd7e00-6b99-11e9-8080-ab903184ea8d.png)

https://1drv.ms/v/s!Amh26IFxNEz6lNgAPkiRXlVSWZxNGQ

In your printscreen in showing the module, the nested view is present. Note that in the tester the nestel list is also not visible.  
![image](https://user-images.githubusercontent.com/41955268/56992046-78a8af80-6b99-11e9-8cc6-1bbceba9a6ab.png)

**Comment by isatahiri** [comment]
After some testing, i finally see the grid in Auto Import. 
I do not know if you put this grid there in purpose but now that i know where it is, everythink is ok in my side. 

![image](https://user-images.githubusercontent.com/41955268/56999172-62f1b500-6bae-11e9-8777-a9e453ab1970.png)

**Comment by apobekiaris** [comment]
the reason I used I only allowed map edit through the popup is for supporting without extra code(easy support/harder to break etc.) both platforms and have a common workflow. However personally, I only use the auto-import functionality, so I am interested to know more about:
> it's very piratical to have a last look of the mapping.

why u need to see it? how is your workflow defined? Isn't it the name of the Import descriptive enough to trust it.? 

I could add a non editable grid under the Map actions with a descriptive message perhaps (for using the Map action when required)

**Comment by apobekiaris** [comment]
p.s.: the grid positioned in the AutoImport tab is a broken layout and is there by mistake

**Comment by isatahiri** [comment]
Well some suggestions : 

 - some how before clicking on "import", we need to have a last look of the mappings in order to make sure that we did not forget anything. (grid in read only would be good)
 - The import button could be in readonly if the mapping is not done. 

I do not use the auto-import functionality yet. Have not tested yet. 
In auto import, the concept is to do the mapping once and then parse a folder ? 
I works even if we are not in the Excel-Import detailview ? 

BR
ISA

**Comment by emeyke** [comment]
I agree with Isa about having the mapping grid visible is important.
It does become a bit awkward if you see a grid but need to do a mapping in a popup.
The use case for me is that person doing import, does it infrequently and need to verify each time what is about to happen and if the file is compatible (maps properly).

**Comment by apobekiaris** [comment]
so adding the only grid under the actions in readonly mode is not good option for u?

**Comment by emeyke** [comment]
It is better than just popup but gets half way there.
Original implementation was ok for me. Except that dashboard usage made it annoyingly long to load. Would prefer just grid...

**Comment by isatahiri** [comment]
well I guess that it depens on how we see things. 
For me both are ok. The important point is to see the mapping (readonly or not) before clicking on import. Having to click on "Configure" and doing this in popup is well defined action and the user know really what to do there. 

If having the mapping grid in the detail view of ExelImport will bring extra code and extra issues then please leave like it is. "It is better to not change something which is working"

BR
ISA

**Comment by emeyke** [comment]
"It is better to not change something which is working" - TRUE

**Comment by apobekiaris** [comment]
>well I guess that it depens on how we see things.
that is true, cause we have 2 different platforms and excel structure varies, sometimes the full window occupied from the popup is too much, other times is really useful.

>Original implementation was ok for me

the original implementaion evolve to the current to assure stability and to avoid different code per platform.

>made it annoyingly long to load. 
post any issue for this with details, perhaps a screencast or a sample, and most probably the logs

we will see after ExcelImporter becomes standlone and does not have to carry weight from base eXpand libs what we can do to improve.

**Comment by emeyke** [comment]
Good

**Comment by apobekiaris** [comment]
btw do u guys follow at all #380 ? do u face similar issues? if so I appreciate your feedback in new posts.

**Comment by apobekiaris** [comment]
I mentioned this here because ExcelImporter as u probaly know already integrates most of the Xpand.XAF.Modules, actually they are build for helping ExcelImporter to become one of them.

**Comment by emeyke** [comment]
Just watching at this point. Still on earlier expand build and havent had time to test the latest.

**Comment by apobekiaris** [comment]
eXpand.lab release [19.1.200.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.4) includes commit [Excel ColumnMap Regex column throws #379](https://github.com/eXpandFramework/eXpand.lab/commit/cf5eba2b515fd0816048c7b85935cb5902b2a1ed),[ExcelImport: Add Column to display the Regex replacement for easy test in the UI #379](https://github.com/eXpandFramework/eXpand.lab/commit/0ed6ce214696a9a9128ecd5de086785364614643) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](http://lab.nugetserver.expandframework.com/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
