### ISSUE TITLE
File attachment module : store files in the the server where asp application is stored.

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#381]
Hello,

Currently the E965 is working by defining a folder where to store the data. 
This folder is related to client only. How can i set a folder in the server where the ASP application is stored ? 

I want to avoid ftp path due to the sercurity. 

Any suggestion on this ? 

BR
ISA

**Comment by apobekiaris** [comment]
>How can i set a folder in the server where the ASP application is stored

I do not understand the problem

**Comment by isatahiri** [comment]
Sorry Tolis, I will give up on this. Instead I put a suggestion #382.
