### ISSUE TITLE
Document Management in a XAF APP

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#382]
Hello,

**Describe the solution you'd like**
Currently the only way to store attachment in XAF application is to use the File Attachment module of XAF in its standard. The problem is that in its standard, it is store into a blob makes the database really large. There is a way to avoid this by storing the data into a file system (E965) but as far as I know, this does not work the Web client if we want to store data in the server directly without configuring . 

Devexpress offers FileSystem Provider for many datastore already. 
Use the file Explorer to store data : 
![Untitled Diagram](https://user-images.githubusercontent.com/41955268/56589237-20940b00-65e5-11e9-8832-22407ed88c36.png)

We could imagine that in business class : 

- we add interface that implies to put a root folder and data store. 

- We add a action that show the file manager (avoid to show it directly in detail form or show in detail form but with  Delay Property Loading in order to not affect performance in detailview loading.

This would really help first me ;-) but i'm also pretty sure that other user might need it. 

BR
ISA

**Comment by isatahiri** [comment]
Of course i'm ready to make a full spec if you think that it is necessary and there is a chance to accomplish this.

**Comment by apobekiaris** [comment]
thanks for the suggestion and the time for this however at the moment I am not pursuing new modules although it may look so. I focus grow the DevExpress.XAF repo and the area you touching is too specific, and too vertical.

**Comment by apobekiaris** [comment]
though if specs are ready and you can share that would be great, maybe we already have parts ready. ExcelImporter born the same way. We now can only make assumptions out of your Generic drawing and getting into lengthy chats is counter-productive

**Comment by isatahiri** [comment]
The spec will be shared on next Monday (April 29th).

**Comment by isatahiri** [comment]
First Shot. 

Please let me know if you need more detailed specs. (process, user stories)

Frankly, I strongly think that this might be useful for many xaf users.


[Specifications - Document Management.pdf](https://github.com/eXpandFramework/eXpand/files/3118899/Specifications.-.Document.Management.pdf)

BR
ISA

**Comment by apobekiaris** [comment]
yes I need details for 2 different nature providers , I can guess the local file system but having not clear image for others. What the workflow how they integrate into context etc.

**Comment by isatahiri** [comment]
Hello,

Please find a new version. Let me know if there are still doubts  on any steps.

So the Target (similar to the new office module of XAF) : 
 - Custom Editor (FileManager) that shows documents based on selected Provider.
 - This custom editor should be usable in any class 
 - Only one provider should be select per xaf application.

[Specifications - Document Management V2.pdf](https://github.com/eXpandFramework/eXpand/files/3124771/Specifications.-.Document.Management.V2.pdf)

BR
ISA

**Comment by isatahiri** [comment]
hi Tolis,
Did you have time to look at the docs ?

**Comment by apobekiaris** [comment]
only a brief one but I do not have time to touch this subject as having a stable 19.1 is priority. I will update you again once I have something valueable to say. If you have update feel free to post them as well.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by isatahiri** [comment]
Lets see if we can simplify this somehow. I will come back to it by next month.

**Comment by apobekiaris** [comment]
sorry for closing i will adjust the bot not to close issues that I am assigned to

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
