### ISSUE TITLE
Dinamic Class and Properties

### ISSUE THREAD

**Issue by GannebalBarka** [eXpandFramework/eXpand#383]
Good day!
I have the task of creating dynamic classes, stored and computed attributes. I tried WorldCreator. The functionality meets the needs, but with one big But: it is necessary to restart the server.

**Question**
How to reset the data model of the WorldCreator to restart the server?

**Additional context**
My application Asp.Net
I studied the operation of the platform and developed a modular application architecture (similar to Expand). Now I know how it works and I think to solve my problem like this:
**Step 1**: Download the newly created Assembly via Xpand.ExpressApp.WorldCreator.System.AssemblyManager
**Step 2**: If the user wants to add properties to an existing dynamic class. They are created in the WorldCreator, but are uploaded directly to the TypesInfo.
Do new attributes indicate the need for an update? (saw something similar in the documentation)
When rebooting, everything will load WorldCreator
**Step 3 (???)**: *Update DataBase (How?)*
**Step 4**: user automatically relogin in the system

P.S.
I have already solved the problem of localization from code by creating my own attributes
Also created attributes for the configuration of bands

**Comment by apobekiaris** [comment]
> But: it is necessary to restart the server.

The XAF application model is shared and lives in a static classes shared between threads. I do not see a way to workaround this limitation at the moment.

>Do new attributes indicate the need for an update?

there is a version control for auto compilation which runs on start, if this what you ask.

https://github.com/eXpandFramework/eXpand/blob/64520e8a14593d904c02c5cc4facf1f33fa0c8c2/Xpand/Xpand.ExpressApp.Modules/WorldCreator/System/AssemblyManager.cs#L49-L58

Do new attributes indicate the need for an update?

>Persistent Assemblies have version which is raied if the objectspace midified and applied as I mentioned before.

>Update DataBase (How?)

https://github.com/eXpandFramework/eXpand/blob/64520e8a14593d904c02c5cc4facf1f33fa0c8c2/Demos/FeatureCenter/FeatureCenter.Module/WorldCreator/NorthWind/WorldCreatorUpdater.cs#L11-L33

>Step 4: user automatically relogin in the system

What this means?

**Comment by GannebalBarka** [comment]
Thanks!

>> But: it is necessary to restart the server.

> The XAF application model is shared and lives in a static classes shared between threads. I do not see a way to workaround this limitation at the moment.

I'll look for a way, maybe even have to use a dirty hack

> >Step 4: user automatically relogin in the system

> What this means?

LogOff() Redirect(...) for reauthenticate. As far as I understand, even if I find a way to reload the model without relogin, the user will not see the changes.

Thank you very much! I will try to find time to tell about the successes.

**Comment by apobekiaris** [comment]
>I'll look for a way, maybe even have to use a dirty hack 

happy to review any rational idea, remember we have a framework and we need to be as much transparent as posssible to the module consumer and we have some basic contracts like 4.6.1, **everything else is allowed**

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
