### ISSUE TITLE
CloneModelView as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#386]
The functionality now lives in 
https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/Model/CloneView.cs#L8

and is shared for all modules, once the package release it will live in the System and all modules that using it directly such as `ExcelImporter, Dashboard, ModelDifference, AuditTrail.`

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [Release CloneModelViewModule #386](https://github.com/eXpandFramework/DevExpress.XAF/commit/15b3f0b50187f2fc5ee84a3a023e9a93d4a347ac) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](http://lab.nugetserver.expandframework.com/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [CloneModelView docs #386](https://github.com/eXpandFramework/DevExpress.XAF/commit/bc6aed017b93bc6975305d55c56b94d03c5bec33) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](http://lab.nugetserver.expandframework.com/).

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
eXpand.lab release [19.1.200.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.4) includes commit [Integrate CloneModelView #386](https://github.com/eXpandFramework/eXpand.lab/commit/1a46c43fdb421d4d2bfb31d4e76b7e50563d3bf0) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](http://lab.nugetserver.expandframework.com/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
