### ISSUE TITLE
Install CloneMemberValue in system modules

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#387]
**Is your feature request related to a problem? Please describe.**
The package is not use from any eXpandFramework module, installing in system is a good fit for this functionally and is going to resolve distribution issues as it will be tested from us.

Eat your own food moto.

**Comment by expand** [comment]
eXpand.lab release [19.1.200.9](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.9) includes commit [Install CloneMemberValue in system module #387](https://github.com/eXpandFramework/eXpand.lab/commit/7ca9f737af10008ce61e88b8115e8182d13dc9f9) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
