### ISSUE TITLE
Fix SupressConfirmation spelling

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#388]

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [fix SupressConfirmation spelling #388](https://github.com/eXpandFramework/DevExpress.XAF/commit/f9fc3db70e293ef343a203107035b2aab4eedf18) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](http://lab.nugetserver.expandframework.com/).

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
