### ISSUE TITLE
Installation Issue via PowerShell

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#389]
Hello,

I had the build 18.2.7.401 (last release 18.2.7)
then i ran : 

Set-ExecutionPolicy Bypass -Scope Process -Force 
$installer="Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') -Version '19.1.200.1'"
iex "$((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/eXpandFramework/XpandPosh/master/XpandPosh/Public/Xpand/Install-Xpand.ps1'));$installer"

At the end of the removing i had this : 
![image](https://user-images.githubusercontent.com/41955268/56869808-cee4e980-6a05-11e9-9578-03ecdefeea65.png)

Please note that i had this also on last install. 
If I run the installation again, then everything seems to be ok. 

Note that i have a Windows 10 in french. 

I hope this will help.
BR
ISA

**Comment by apobekiaris** [comment]
I am not sure what the image says, however I changed the script to allow easy paste
```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  #-Version '18.2.704.0'"
```

note: while in powershell do this to help me transalte message in future.

click on the left top corner of the powershell window and then in the popup menu go to edit/select all and then press ctrl+c and paste it here.

**Comment by isatahiri** [comment]
Sorry about the untranslated content. 
Thanks for you help.

**Comment by apobekiaris** [comment]
no worries i can sure translate if you paste text instead

**Comment by apobekiaris** [comment]
the script i posted b4 had an error as it came from the lab directly. replace it with 

```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  "
```

**Comment by isatahiri** [comment]
Hi,

There is an issue with installation of 1.9.400.1 : 

`Installing Assemblies, Nuget, VSIX, Source into C:\Users\isata\Documents\eXpandFramework.
Additional parameters: Version, Latest, Assets, InstallationPath
Downloading Nuget at C:\Users\isata\Documents\eXpandFramework\nuget.exe
19.1.400.1 is a eXpand.lab version
Downloading Sources from https://github.com/eXpandFramework/eXpand.lab/releases/download/19.1.400.1/Xpand-Source-19.1.400.1.zip into C:\Users\isata\Documents\eXpandFramework
iex : Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:1 : 50
+ ... cess -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('ht ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand`
BR
ISA

**Comment by apobekiaris** [comment]
how did u got that release? is not published yet

https://github.com/eXpandFramework/eXpand.lab/releases

**Comment by isatahiri** [comment]
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  -Version '19.1.400.1'"

**Comment by isatahiri** [comment]
just with this command

**Comment by isatahiri** [comment]
![image](https://user-images.githubusercontent.com/41955268/59981001-f0c1ad80-95fd-11e9-8fd4-272fca9acc16.png)

**Comment by apobekiaris** [comment]
aha

the release is not published as I said so impossible to download it :)

**Comment by isatahiri** [comment]
ok

**Comment by isatahiri** [comment]
actually i saw it so i thought i could just get ;-)

**Comment by apobekiaris** [comment]
watch the lab releases is a better indicator
