### ISSUE TITLE
Web StringLookupPropertyEditor blocks data entry

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#390]
**Describe the bug**
Xpand.ExpressApp.Web.PropertyEditors.StringLookupPropertyEditor block new values entry if it matches partially existing values

**Expected behavior**
Should allow non existing value entry

**Screenshots**
https://www.loom.com/share/ba49e32260884a86b87bd2d39aba6aed.

**Desktop (please complete the following information):**
 Chrome

Xpand v 18.2.701.0

**Comment by apobekiaris** [comment]
so my understanding is that you want to change the DropDownStyle of the ASPxComboBox to DropDown instead and from what I see this is only possible through code at the moment as the PropertyEditor is nto adapted to the model. Use the attached file in your module for now to adapt it and then change the value.
![image](https://user-images.githubusercontent.com/159464/56909932-f98c7c00-6ab1-11e9-81ae-2f26286ea7fd.png)

[StringLookupPropertyEditor.zip](https://github.com/eXpandFramework/eXpand/files/3128202/StringLookupPropertyEditor.zip)

**Comment by apobekiaris** [comment]
eXpand.lab release [19.1.200.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.4) includes commit [ASPxComboBoxModelAdapter #390](https://github.com/eXpandFramework/eXpand.lab/commit/8c9b2723d8383c53dbfb267739050c6c36db7159) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](http://lab.nugetserver.expandframework.com/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
