### ISSUE TITLE
In the windows "Maps column to Members", Actually, when i try to search the right member but with keyboard i got this error (see VS output  :

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#391]
In the windows "Maps column to Members", Actually, when i try to search the right member but with keyboard i got this error (see VS output  : 
30.04.19 00:36:32.764	'PropertyName' property editor: new value is 'Noim'
30.04.19 00:36:33.306	'PropertyName' property editor: new value is 'Noi'
30.04.19 00:36:33.490	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:34.037	'PropertyName' property editor: new value is ''
30.04.19 00:36:34.597	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:35.079	'PropertyName' property editor: new value is 'Nom d'utilisateur'
30.04.19 00:36:35.339	'PropertyName' property editor: new value is 'Nom de'
30.04.19 00:36:35.446	'PropertyName' property editor: new value is 'Nom de '
30.04.19 00:36:36.825	'PropertyName' property editor: new value is 'Nom de'
30.04.19 00:36:37.022	'PropertyName' property editor: new value is 'Nom d'utilisateur'
30.04.19 00:36:38.567	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:39.392	'PropertyName' property editor: new value is 'Nom'
30.04.19 00:36:39.395	--------------------------------------------------------------------------------
							Execute action

30.04.19 00:36:39.397		Type: DevExpress.ExpressApp.Actions.SimpleAction
								ID: Save
								Category: Save
								Controller.Name: DevExpress.ExpressApp.Win.SystemModule.WinModificationsController
								Context.Name: Excel Column Map
								Context.IsRoot: True
								Context.SelectedObjects.Count: 1
								Context.CurrentObject: UserName-Nom

30.04.19 00:36:39.478	Action 'Save' done
Exception thrown: 'System.ObjectDisposedException' in DevExpress.Xpo.v18.2.dll
Exception thrown: 'System.ObjectDisposedException' in DevExpress.XtraGrid.v18.2.dll
PME_Affaire.Win.exe Error: 0 : 30.04.19 00:36:41.370	================================================================================
The error occurred:

	Type:       ObjectDisposedException
	Message:    Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'UserName-'.
	Data:       0 entries
	Stack trace:

   à DevExpress.XtraGrid.Views.Base.ColumnView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   à DevExpress.ExpressApp.Win.Editors.XafGridView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   à DevExpress.XtraGrid.Views.Base.ColumnView.OnPostRowException(ControllerRowExceptionEventArgs e)
   à DevExpress.XtraGrid.Views.Grid.GridView.DevExpress.Data.IDataControllerValidationSupport.OnPostRowException(ControllerRowExceptionEventArgs e)
   à DevExpress.Data.BaseGridController.OnPostRowException(Exception exception)
   à DevExpress.Data.CurrencyDataController.EndCurrentRowEdit(Boolean force)
   à DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRowCore(Boolean force)
   à DevExpress.XtraGrid.Views.Grid.GridView.UpdateCurrentRowCore(Boolean force)
   à DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRow()
   à DevExpress.XtraGrid.Views.Base.ColumnView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Grid.GridView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Grid.GridView.DoChangeFocusedRow(Int32 currentRowHandle, Int32 newRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Base.ColumnView.DoChangeFocusedRowInternal(Int32 newRowHandle, Boolean updateCurrentRow)
   à DevExpress.XtraGrid.Views.Base.ColumnView.set_FocusedRowHandle(Int32 value)
   à DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnMouseDown(GridHitInfo hitInfo, DXMouseEventArgs e)
   à DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   à DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   à DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   à DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   à System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   à DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null
 
In the winform it looks like this (message : cannot access to a deleted object)  : 
![image](https://user-images.githubusercontent.com/41955268/56931612-e04ef400-6ae0-11e9-8e5d-4528af682814.png)

Hope this helps. 
BR
ISA

_Originally posted by @isatahiri in https://github.com/eXpandFramework/eXpand/issues/379#issuecomment-487769436_

**Comment by apobekiaris** [comment]
@isatahiri let's discuss this here 

please provide a screencast as i fail to repro it myself

**Comment by isatahiri** [comment]
Please find the screencast as discussed. 

[Uploading 2019-04-30-17-49-43.zip…]()

Message : Translation : "Cannot access to a deleted object"

Impossible d'accéder à un objet supprimé. 
Nom de l'objet : 'Prénom-'.

   à DevExpress.XtraGrid.Views.Base.ColumnView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   à DevExpress.ExpressApp.Win.Editors.XafGridView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   à DevExpress.XtraGrid.Views.Base.ColumnView.OnPostRowException(ControllerRowExceptionEventArgs e)
   à DevExpress.XtraGrid.Views.Grid.GridView.DevExpress.Data.IDataControllerValidationSupport.OnPostRowException(ControllerRowExceptionEventArgs e)
   à DevExpress.Data.BaseGridController.OnPostRowException(Exception exception)
   à DevExpress.Data.CurrencyDataController.EndCurrentRowEdit(Boolean force)
   à DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRowCore(Boolean force)
   à DevExpress.XtraGrid.Views.Grid.GridView.UpdateCurrentRowCore(Boolean force)
   à DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRow()
   à DevExpress.XtraGrid.Views.Base.ColumnView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Grid.GridView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Grid.GridView.DoChangeFocusedRow(Int32 currentRowHandle, Int32 newRowHandle, Boolean raiseUpdateCurrentRow)
   à DevExpress.XtraGrid.Views.Base.ColumnView.DoChangeFocusedRowInternal(Int32 newRowHandle, Boolean updateCurrentRow)
   à DevExpress.XtraGrid.Views.Base.ColumnView.set_FocusedRowHandle(Int32 value)
   à DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnMouseDown(GridHitInfo hitInfo, DXMouseEventArgs e)
   à DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   à DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   à DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   à DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   à System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   à DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by apobekiaris** [comment]
that attachment is not valid

**Comment by isatahiri** [comment]
https://1drv.ms/u/s!Amh26IFxNEz6lNd_8Km3CyiI7hEKmA

**Comment by isatahiri** [comment]
should be better.

**Comment by isatahiri** [comment]
Did you manage to repro this in your side Tolis ?

**Comment by apobekiaris** [comment]
yes I am not sure where is the fix I am still assigned the case and will update u again, sorry for the delays

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [MasterDetail: When detailview commited reload only the changed object instead of refreshing the listview #391](https://github.com/eXpandFramework/DevExpress.XAF/commit/493b1e00ad632d0917a2e3dc2e8aa7fcd57833b8) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](http://lab.nugetserver.expandframework.com/).

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
please wait for the main build do not expirement yourself

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [MasterDetail: When detailview committed in web refresh the listview instead of reloading the changed object #391](https://github.com/eXpandFramework/DevExpress.XAF/commit/717cd001d1e998387c7e25179715d665aae8f8d4) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](http://lab.nugetserver.expandframework.com/). If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
you mean expand 19.1.201 ?

**Comment by apobekiaris** [comment]
nope the links go to the standlone module repo, you will get notified once integrated with main repo and the links will point to it and the related work

**Comment by apobekiaris** [comment]
> If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

**Comment by apobekiaris** [comment]
fyi u could try it alone by simply adding the standalone nugets to your front end project hopefuly u should be able to run now, but why to spent your time in vain? the build is baking won't be long

**Comment by isatahiri** [comment]
thanks for info.

**Comment by apobekiaris** [comment]
u welcome I will always improve the automation to boost productivity so your feedback is valuable

**Comment by expand** [comment]
eXpand.lab release [19.1.200.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.5) includes commit [ExcelImporter: Fix broken layout, display map grid in the main view and handle different the masterdetail synchronization per platform #391](https://github.com/eXpandFramework/eXpand.lab/commit/dcd21041d623b2b5e4d7d1d8a2f69599bdd71ee4),[Update Standalone nugets #394 #391](https://github.com/eXpandFramework/eXpand.lab/commit/bc1fb84affe1b0285eba429cac582ccd5d74a3da) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](http://lab.nugetserver.expandframework.com/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
this is ready for testing

**Comment by isatahiri** [comment]
Hello,

I downloaded the version 19.1.200.5 and tried. The layout is ok. 
The exceltion is still present. 
https://1drv.ms/v/s!Amh26IFxNEz6lNgIhEy-7td-Uan7ow

/////////
Cannot access a disposed object.
Object name: 'AF-'.

   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   at DevExpress.ExpressApp.Win.Editors.XafGridView.RaiseInvalidRowException(InvalidRowExceptionEventArgs ex)
   at DevExpress.XtraGrid.Views.Base.ColumnView.OnPostRowException(ControllerRowExceptionEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.DevExpress.Data.IDataControllerValidationSupport.OnPostRowException(ControllerRowExceptionEventArgs e)
   at DevExpress.Data.BaseGridController.OnPostRowException(Exception exception)
   at DevExpress.Data.CurrencyDataController.EndCurrentRowEdit(Boolean force)
   at DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRowCore(Boolean force)
   at DevExpress.XtraGrid.Views.Grid.GridView.UpdateCurrentRowCore(Boolean force)
   at DevExpress.XtraGrid.Views.Base.ColumnView.UpdateCurrentRow()
   at DevExpress.XtraGrid.Views.Base.ColumnView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   at DevExpress.XtraGrid.Views.Grid.GridView.CheckCanLeaveRow(Int32 currentRowHandle, Boolean raiseUpdateCurrentRow)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoChangeFocusedRow(Int32 currentRowHandle, Int32 newRowHandle, Boolean raiseUpdateCurrentRow)
   at DevExpress.XtraGrid.Views.Base.ColumnView.DoChangeFocusedRowInternal(Int32 newRowHandle, Boolean updateCurrentRow)
   at DevExpress.XtraGrid.Views.Base.ColumnView.set_FocusedRowHandle(Int32 value)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnMouseDown(GridHitInfo hitInfo, DXMouseEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

BR
ISA

**Comment by isatahiri** [comment]
but if i click on cancel and come back to the ExcelImporter detailview, the mapping is set correctly according to the subgrid.

**Comment by apobekiaris** [comment]
apologies my test was pretty different and my solution rational, I will try with your exact steps also,.

**Comment by apobekiaris** [comment]
I tried on your solution but cannot reproduce it, I tried with the prestation.xlx, please upload the one you used and the log

**Comment by isatahiri** [comment]
I cleaned the cache, purged all bin directories and rebuild the entire project and i do not face the issue anymore. 
So far so good. 

Thanks Tolis

**Comment by isatahiri** [comment]
You can close this one or assign it to me and I'll do it.

**Comment by apobekiaris** [comment]
I can add you as collaborator if you wish to have more control over the project, it assigns automatically to me. Also note that there is a bot https://github.com/eXpandFramework/Azure-Tasks/blob/master/Close-GitHubIssue-ForAge.yml that will close tickets based on inactivity, so we do not need to close anything ourselves, unless this the way we track our own issues.

**Comment by apobekiaris** [comment]
I keep track my work by assign-unassign my self from tickets and let the bot do the rest.

**Comment by apobekiaris** [comment]
also if you wish to commit anything please send a pull request and do not push to the repos directly, as direct commits trigger the bot scripts.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
