### ISSUE TITLE
Install eXpand with install folder in parameter

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#392]
Hello Tolis,

In our company the GPO have changed. No more executable in "My Documents" is it possible de define the installation folder of expand  when we run the install from powershell ?

BR
ISA

**Comment by apobekiaris** [comment]
move this to main repo as it concerns the installation

**Comment by apobekiaris** [comment]
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') -InstallationPath `YOURPATH`"

**Comment by apobekiaris** [comment]
```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') -InstallationPath `YOURPATH`"
```

**Comment by isatahiri** [comment]
cool thanks !
I'll try this tomorrow and let you know :-)

**Comment by apobekiaris** [comment]
try this i used wrong symbol for quote
```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') -InstallationPath 'YOURPATH'"
```

**Comment by isatahiri** [comment]
Hello,

The installation path parameter works great. 
Thanks Tolis !
