### ISSUE TITLE
System.InvalidOperationException: An asynchronous operation cannot be started at this time

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#394]
**Describe the bug**
All asynchronous/Reactive Standalone modules may throw InvalidOperationException when disposing classes.

**Solution**
Declare your Default.aspx page as Async similar to 
```xml
<%@ Page Language="C#" AutoEventWireup="true" Inherits="Default" EnableViewState="false"
    ValidateRequest="false" CodeBehind="Default.aspx.cs" Async="true"  %>
```

use the 4.6.1 Runtime in your web.config
```xml
<system.web>
    <httpRuntime targetFramework="4.6.1" />
```

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [System.InvalidOperationException: An asynchronous operation cannot be started at this time #394 #377](https://github.com/eXpandFramework/DevExpress.XAF/commit/c529a9bf69fb55f119457a9c0f89825492a3404b) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](http://lab.nugetserver.expandframework.com/). If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.200.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.5) includes commit [Update Standalone nugets #394 #391](https://github.com/eXpandFramework/eXpand.lab/commit/bc1fb84affe1b0285eba429cac582ccd5d74a3da) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](http://lab.nugetserver.expandframework.com/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by emeyke** [comment]
Applies to 18.2.7 too?

**Comment by apobekiaris** [comment]
nope

**Comment by pjeh** [comment]
This error still occurs with the latest version installed.  I have set async="true" and use 4.6.1 runtime in web.config

**Comment by apobekiaris** [comment]
this message is missleading, the problem is most probably on the actual import, as I suggested to u before, either try a simpler/different import to see if it works or post the logs here or if u want me to try out, post a sample that i Can repro it.

**Comment by pjeh** [comment]
Please see the attached sample.
[ExcelImporterError.zip](https://github.com/eXpandFramework/eXpand/files/3360907/ExcelImporterError.zip)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Web Subscription disposing throws System.InvalidOperationException: An asynchronous operation cannot be started at this time #394 #384](https://github.com/eXpandFramework/DevExpress.XAF/commit/13c2c341d43f3850b1687dfb9edef36b17da7524)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.15) includes commit that relate to this task:

* [Web Subscription disposing throws System.InvalidOperationException: An asynchronous operation cannot be started at this time #394 #384](https://github.com/eXpandFramework/eXpand.lab/commit/df3d5bd97f72786023a22cec78761c8a28bfb1aa)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by apobekiaris** [comment]
see #661
