### ISSUE TITLE
Build error when using VersionConvertor

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#395]
Hi Tolis

I recently updated the references to ModelViewInheritance nuget package and I have got the references to the VersionConvertor package. When will get the following output when building my ExpressApp Solution.

`1>------ Skipped Build: Project: Xpand.Persistent.Base, Configuration: Debug Any CPU ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: Xpand.EasyTest, Configuration: Debug x86 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: Xpand.ExpressApp.ModelArtifactState, Configuration: Debug Any CPU ------
4>------ Build started: Project: Xpand.ExpressApp.AdditionalViewControls, Configuration: Debug Any CPU ------
5>------ Build started: Project: Xpand.ExpressApp.MasterDetail, Configuration: Debug Any CPU ------
6>------ Build started: Project: Xpand.ExpressApp.Win, Configuration: Debug Any CPU ------
7>------ Skipped Build: Project: Xpand.ExpressApp.EasyTest.WebAdapter, Configuration: Debug Any CPU ------
7>Project not selected to build for this solution configuration 
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : Exception calling "ReadModule" with "2" argument(s): "Symbols were found but are not matching the assembly"
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : At C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.ps1:51 cha
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : r:5
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     [ModuleDefinition]::ReadModule($path, $readerParams).Assembly
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : SymbolsNotMatchingException
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :  
3>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\\Xpand.VersionConverter.ps1' 'C:\Source\Xpand ExpressApp\Source\Modules\Xpand.ExpressApp.ModelArtifactState\Xpand.ExpressApp.ModelArtifactState.csproj' 'C:\Source\Releases\Xpand ExpressApp\' } "" exited with code 1.
8>------ Skipped Build: Project: Xpand.Persistent.BaseImpl, Configuration: Debug Any CPU ------
8>Project not selected to build for this solution configuration 
9>------ Build started: Project: Xpand.ExpressApp.ModelDifference, Configuration: Debug Any CPU ------
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : Exception calling "ReleaseMutex" with "0" argument(s): "De synchronisatiemethode voor Object is vanuit een niet-gesynch
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : roniseerd codeblok aangeroepen."
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : At C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.ps1:194 ch
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : ar:5
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     $mtx.ReleaseMutex()
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : ApplicationException
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :  
4>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\\Xpand.VersionConverter.ps1' 'C:\Source\Xpand ExpressApp\Source\Modules\Xpand.ExpressApp.AdditionalViewControls\Xpand.ExpressApp.AdditionalViewControls.csproj' 'C:\Source\Releases\Xpand ExpressApp\' } "" exited with code 1.
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : Exception calling "ReleaseMutex" with "0" argument(s): "De synchronisatiemethode voor Object is vanuit een niet-gesynch
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : roniseerd codeblok aangeroepen."
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : At C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.ps1:194 ch
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : ar:5
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     $mtx.ReleaseMutex()
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : ApplicationException
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :  
5>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\\Xpand.VersionConverter.ps1' 'C:\Source\Xpand ExpressApp\Source\Modules\Xpand.ExpressApp.MasterDetail\Xpand.ExpressApp.MasterDetail.csproj' 'C:\Source\Releases\Xpand ExpressApp\' } "" exited with code 1.
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : Exception calling "ReleaseMutex" with "0" argument(s): "De synchronisatiemethode voor Object is vanuit een niet-gesynch
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : roniseerd codeblok aangeroepen."
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : At C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.ps1:194 ch
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : ar:5
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     $mtx.ReleaseMutex()
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : ApplicationException
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :  
6>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\\Xpand.VersionConverter.ps1' 'C:\Source\Xpand ExpressApp\Source\Core\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win.csproj' 'C:\Source\Releases\Xpand ExpressApp\' } "" exited with code 1.
10>------ Skipped Build: Project: Xpand.ExpressApp.EasyTest.WinAdapter, Configuration: Debug Any CPU ------
10>Project not selected to build for this solution configuration 
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : Exception calling "ReadModule" with "2" argument(s): "Symbols were found but are not matching the assembly"
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : At C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.ps1:51 cha
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : r:5
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     [ModuleDefinition]::ReadModule($path, $readerParams).Assembly
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : SymbolsNotMatchingException
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error :  
9>C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.17\build\\Xpand.VersionConverter.ps1' 'C:\Source\Xpand ExpressApp\Source\Modules\Xpand.ExpressApp.ModelDifference\Xpand.ExpressApp.ModelDifference.csproj' 'C:\Source\Releases\Xpand ExpressApp\' } "" exited with code 1.
========== Build: 0 succeeded, 5 failed, 89 up-to-date, 5 skipped ==========`

What can I do to solve this? 

Thanks,
Jacob

**Comment by apobekiaris** [comment]
we probably found the solution to this at #380, however is still on build servers.

**Comment by apobekiaris** [comment]
I suggest you just replace manually the VersionConverter.ps1 from #380 for now and lookout for the next official

**Comment by apobekiaris** [comment]
or if u want to spare you time a better suggestion is to switch to one parallel build in your VS/Options/Build and wait for the official without replacing anything

**Comment by jacobdeboer33** [comment]
Hi Tolis

Changing the parralel build setting did not help. Clearing powershell script did. Thanks!

Jacob
