### ISSUE TITLE
different  standalone module requirement 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#396]
I have one strange thing but maybe it is another thread.
I have refrenced Xpand 18.2.704 in my project and only the new Xpand.XAF (f.e. ViewEditMode 1.2.23). On my develop machine the program runs. If I build a release and put it on another machine, it doesn´t run. There is a reference error, cause the Xpand.XAF Version from 18.2.704 (f.e. ViewEditMode 1.2.9) are needed (Error Version dll not correct).

_Originally posted by @CWolffIF in https://github.com/eXpandFramework/eXpand/issues/380#issuecomment-490066677_

**Comment by apobekiaris** [comment]
solving such issues is usually straight forward, what happens if you add the missing assembly in your bin?

**Comment by apobekiaris** [comment]
@CWolffIF  I moved our question here

**Comment by CWolffIF** [comment]
If I replace it with the original Version from 18.2.704 it works (f.e. ViewEditMode 1.2.9).

**Comment by apobekiaris** [comment]
>There is a reference error, 

post details

**Comment by CWolffIF** [comment]
I only use 
Xpand.XAF.Modules.ModelViewInheritance
Xpand.XAF.Modules.Reactive
Xpand.XAF.Modules.ViewEditMode

The Application crashes directly (Click & Crash, no delay). 

In the log is no Error.
07.05.19 17:46:22.428	================================================================================
07.05.19 17:46:22.428	Trace Log for iXISXRM.Win.exe is started
07.05.19 17:46:22.428	================================================================================
07.05.19 17:46:22.428	System Environment
	OS Version: Microsoft Windows NT 6.2.9200.0
	.Net Framework Versions: v4.0.30319
	CLR Version: 4.0.30319.42000
	eXpressApp Version: 18.2.7.0
	eXpressApp File Version: 18.2.7.0

Application config
	Modules=
	NewVersionServer=\\DC-SQL03\IXISJH_Test_Update\
	EnableDiagnosticActions=False
	Languages=de;en;de-DE
	UserModelDiffsLocation=CurrentUserApplicationDataFolder
	ModelCacheLocation=CurrentUserApplicationDataFolder
	TraceLogLocation=CurrentUserApplicationDataFolder
	ClientSettingsProvider.ServiceUri=

07.05.19 17:46:22.443	Initialize application
=======================
07.05.19 17:46:22.443		Command line arguments: 
		C:\Program Files (x86)\ifaktor\iXISJH_Testumgebung\iXISXRM.Win.exe


In the Windows Event says
Anwendung: iXISXRM.Win.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IO.FileLoadException
   bei Xpand.ExpressApp.Security.XpandSecurityModule..ctor()
   bei iXISXRM.Win.iXISXRMWindowsFormsApplication.InitializeComponent()
   bei iXISXRM.Win.iXISXRMWindowsFormsApplication..ctor()
   bei iXISXRM.Win.Program.Main()

And the Windows AppCrash says
Version=1
EventType=CLR20r3
EventTime=132017177165692324
ReportType=2
Consent=1
ReportIdentifier=92db62a2-70df-11e9-80e1-00155d01263f
IntegratorReportIdentifier=92db62a1-70df-11e9-80e1-00155d01263f
WOW64=1
NsAppName=iXISXRM.Win.exe
Response.type=4
Sig[0].Name=Problemsignatur 01
Sig[0].Value=iXISXRM.Win.exe
Sig[1].Name=Problemsignatur 02
Sig[1].Value=18.2.7.3060
Sig[2].Name=Problemsignatur 03
Sig[2].Value=5cd10a09
Sig[3].Name=Problemsignatur 04
Sig[3].Value=iXISXRM.Win
Sig[4].Name=Problemsignatur 05
Sig[4].Value=18.2.7.3060
Sig[5].Name=Problemsignatur 06
Sig[5].Value=5cd10a09
Sig[6].Name=Problemsignatur 07
Sig[6].Value=f
Sig[7].Name=Problemsignatur 08
Sig[7].Value=129
Sig[8].Name=Problemsignatur 09
Sig[8].Value=System.IO.FileLoadException
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=6.3.9600.2.0.0.272.7
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=5861
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=5861822e1919d7c014bbb064c64908b2
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=fdca
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=fdca1fbcc5199d38e99bdacef751acf6
UI[2]=C:\Program Files (x86)\ifaktor\iXISJH_Testumgebung\iXISXRM.Win.exe
UI[3]=iXISXRM.Win funktioniert nicht mehr
UI[4]=Windows kann online nach einer Lösung für das Problem suchen.
UI[5]=Online nach einer Lösung suchen und das Programm schließen
UI[6]=Später online nach einer Lösung suchen und das Programm schließen
UI[7]=Programm schließen
LoadedModule[0]=C:\Program Files (x86)\ifaktor\iXISJH_Testumgebung\iXISXRM.Win.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\SYSTEM32\KERNEL32.dll
LoadedModule[4]=C:\Windows\SYSTEM32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\SYSTEM32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\SYSTEM32\msvcrt.dll
LoadedModule[7]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[8]=C:\Windows\SYSTEM32\RPCRT4.dll
LoadedModule[9]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[10]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[11]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\Windows\SYSTEM32\SHLWAPI.dll
LoadedModule[14]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[15]=C:\Windows\SYSTEM32\USER32.dll
LoadedModule[16]=C:\Windows\SYSTEM32\GDI32.dll
LoadedModule[17]=C:\Windows\system32\IMM32.DLL
LoadedModule[18]=C:\Windows\SYSTEM32\MSCTF.dll
LoadedModule[19]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[20]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[21]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[22]=C:\Windows\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[23]=C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\e8980cc30db74aebb06ed60c8b93c295\mscorlib.ni.dll
LoadedModule[24]=C:\Windows\SYSTEM32\ole32.dll
LoadedModule[25]=C:\Windows\system32\uxtheme.dll
LoadedModule[26]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[27]=C:\Windows\SYSTEM32\OLEAUT32.dll
LoadedModule[28]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System\4aaf5e0f4b30e54feb3ed04d28adb769\System.ni.dll
LoadedModule[29]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\bd0566bb88cdb3dff5cc707caaa994ce\System.Drawing.ni.dll
LoadedModule[30]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\0171c8501fea24221e1cc8e5b7d2f7f9\System.Windows.Forms.ni.dll
LoadedModule[31]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[32]=C:\Windows\system32\rsaenh.dll
LoadedModule[33]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[34]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\f7dc2624bbf7306afb8cff3c602a3366\System.Core.ni.dll
LoadedModule[35]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\af2c591ed4c80f42a0535bd22c952d59\System.Configuration.ni.dll
LoadedModule[36]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Data\41febda6daa4a8b00fc1dc32a86337b7\System.Data.ni.dll
LoadedModule[37]=C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[38]=C:\Windows\SYSTEM32\WS2_32.dll
LoadedModule[39]=C:\Windows\SYSTEM32\CRYPT32.dll
LoadedModule[40]=C:\Windows\SYSTEM32\NSI.dll
LoadedModule[41]=C:\Windows\SYSTEM32\MSASN1.dll
LoadedModule[42]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\ca8c74a3857ee206c1c2418876fe02b6\System.Xml.ni.dll
LoadedModule[43]=C:\Windows\SYSTEM32\shell32.dll
LoadedModule[44]=C:\Windows\SYSTEM32\SHCORE.dll
LoadedModule[45]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[46]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Deployment\5df03c3fd73dd076a9e54640084f2aab\System.Deployment.ni.dll
LoadedModule[47]=C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.19292_none_dae0bce85bc4a510\gdiplus.dll
LoadedModule[48]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[49]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=CLR20r3
AppName=iXISXRM.Win
AppPath=C:\Program Files (x86)\ifaktor\iXISJH_Testumgebung\iXISXRM.Win.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=F8CF54BEEF79D6CF729D729A9843E51B

**Comment by apobekiaris** [comment]
> If I build a release and put it on another machine

let's focus on this, what's different on this machine, can you test on a clean one? can you check your gac as it may load stuff from there, remove all xpand stuff from Gac and let them only in your bin.

**Comment by CWolffIF** [comment]
Maybe its in the ModelViewInheritance Modul, cause last Modul loaded is XpandSecurityModule  where is a dependency to.

**Comment by apobekiaris** [comment]
it works for your dev so its enviromental conlict, my understanding is that you just copy the assemblies, u did not even rebuild on the new machine

**Comment by CWolffIF** [comment]
on the new machine is no dll (DevExpress or Xpand) in the GAC. Everything is in the local bin.

**Comment by apobekiaris** [comment]
same behaviour for the patched sample? the one with the 2 agnostic and all xpand.xaf.modules?

**Comment by CWolffIF** [comment]
Just copy the the assemblies, no rebuild on the new machine. There is no development suit. A clean Windows machine.

**Comment by apobekiaris** [comment]
does your app config have binding redirects for the replaced assemblies?

**Comment by apobekiaris** [comment]
try to force loading like in your Program.cs
```cs
private Assembly CurrentDomainOnAssemblyResolve(object sender, ResolveEventArgs args){
            var setupInformation = AppDomain.CurrentDomain.SetupInformation;
            var binPath = setupInformation.PrivateBinPath??setupInformation.ApplicationBase;
            var indexOf = args.Name.IndexOf(",", StringComparison.Ordinal);
            if (indexOf > -1){
                var assemblyName = args.Name.Substring(0, indexOf);
                var path = $"{Path.Combine(binPath, assemblyName)}.dll";
                if (File.Exists(path)){
                    return Assembly.LoadFile(path);
                }
            }
            return null;
        }
```

and also subscribe to 
```cs
AppDomain.CurrentDomain.AssemblyResolve+=CurrentDomainOnAssemblyResolve;
```

**Comment by CWolffIF** [comment]
No, in the app.config there are no binding redirects. I will test with binding redirects.

**Comment by apobekiaris** [comment]
a bit of refactoring as this to the above methood which actually does not need binding redirects but was designed for different case, strongly assemblies in gac

```cs
 private Assembly CurrentDomainOnAssemblyResolve(object sender, ResolveEventArgs args){
            var setupInformation = AppDomain.CurrentDomain.SetupInformation;
            var binPath = setupInformation.PrivateBinPath??setupInformation.ApplicationBase;
            var indexOf = args.Name.IndexOf(",", StringComparison.Ordinal);
            var assemblyName = args.Name.Substring(0, indexOf);
            if (indexOf > -1){
                assemblyName=args.Name
            }
            
            var path = $"{Path.Combine(binPath, assemblyName)}.dll";
            if (File.Exists(path)){
                return Assembly.LoadFile(path);
            }
            return null;
        }
```

**Comment by apobekiaris** [comment]
oops sorry this one 

```cs
private Assembly CurrentDomainOnAssemblyResolve(object sender, ResolveEventArgs args){
            var setupInformation = AppDomain.CurrentDomain.SetupInformation;
            var binPath = setupInformation.PrivateBinPath??setupInformation.ApplicationBase;
            var indexOf = args.Name.IndexOf(",", StringComparison.Ordinal);
            var assemblyName = args.Name;
            if (indexOf > -1){
                assemblyName = args.Name.Substring(0, indexOf);
            }
            
            var path = $"{Path.Combine(binPath, assemblyName)}.dll";
            if (File.Exists(path)){
                return Assembly.LoadFile(path);
            }
            return null;
        }
``

**Comment by CWolffIF** [comment]
> 
> 
> No, in the app.config there are no binding redirects. I will test with binding redirects.

Changing app.config is not the solution.

I will try to make the changes in the program and in the app.config.

**Comment by apobekiaris** [comment]
>Changing app.config is not the solution.
in theory they both do the same,  iXISXRM.Win.exe.config changes are more strict

**Comment by apobekiaris** [comment]
> System.IO.FileLoadException

and it most probably the thing we should focus here, its a binding exception

**Comment by CWolffIF** [comment]
the
File.Exists(path) is always false, cause the path is (f.e. "resources" to much)
C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.ModelViewInheritance.resources.dll

**Comment by apobekiaris** [comment]
why u think the problem is on a resource file?

**Comment by apobekiaris** [comment]
my guess is that is safe to return null there

**Comment by CWolffIF** [comment]
All assemblynames end of ".ressources.dll"

**Comment by apobekiaris** [comment]
maybe you subscribe to late? this should be the first line

try a different approach please. In your program.cs first line
```cs
var setupInformation = AppDomain.CurrentDomain.SetupInformation;
            var binPath = setupInformation.PrivateBinPath??setupInformation.ApplicationBase;
            foreach (var file in Directory.GetFiles(binPath, "Xpand*.dll")) {
                Assembly.LoadFile(file);
            }
```

also make sure you do not have any Xpand using in the top of the file.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
