### ISSUE TITLE
AutoCommit SupressConfirmation modules missing?

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#397]
Hi Tolis

I saw in your commits that you removed the autocommit and supressconfirmation  and controllers. But you didn't add the nuget packages. Is this on purpose? Or do I need to add the packages in the application project?

Thanks,
Jacob

**Comment by jacobdeboer33** [comment]
Hi Tolis

You are right. I thougt that AutoCommit was used in several module models. But I was wrong. I will reference the packages in my application projects.

Thanks,
Jacob

**Comment by apobekiaris** [comment]
>I will reference the packages in my application projects.

if you do not use the package as standalone why u need to take any action? this should be already in your bin from the msbuild

**Comment by apobekiaris** [comment]
if u need to take such an action will only using eXPand packages please provide repro details. I do not expet users to know all the packages and have to install update them if the use the container eXpand modules.
