### ISSUE TITLE
Excel Importer: Import completed but Save button do not save imported records

### ISSUE THREAD

**Issue by vsvirtan** [eXpandFramework/eXpand#398]
I imported the Excel file using Excel Importer but and import went completed without errors. I pressed Save button but imported records are not saved.

There is no error message or anything. I'm using 18.2.704 version of Xpand Framework (and Excel Importer).

![2019-05-10_13-47-38](https://user-images.githubusercontent.com/3333010/57525978-df199480-7334-11e9-97da-c1471a50ee0c.png)

**Comment by apobekiaris** [comment]
I wouldn't recommend to try the web excel importer for 18.2 versions unless you use the latest versions from the [Standalone packages](http://xaf.expandframework.com). There were problems with all reactive modules which are resolved in 19.1 releases http://lab.releases.expandframework.com. So this might be some kind of side effect cause I just tested 19.1 and saved fine. 

Another user just reporter 18.2.701.0 works better though on my side of view suffer from the same async problems.

maybe @isatahiri can comment also on this?

**Comment by isatahiri** [comment]
Hi
Please check your data, you probably have a string long that authaurized. See #407

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
