### ISSUE TITLE
Install-Xpand fails

### ISSUE THREAD

**Issue by wullumpie** [eXpandFramework/eXpand#399]
Hi Tolis,

I've been trying to install v18.2.704.0 with Xpand-Posh but it does noet complete without error:

Installing Assemblies into C:\Users\WillemdeVries\Documents\eXpandFramework.
Additional parameters: Version, Latest, Assets, InstallationPath
Downloading Nuget at C:\Users\WillemdeVries\Documents\eXpandFramework\nuget.exe
18.2.704.0 is a eXpand version
Downloading assemblies from https://github.com/eXpandFramework/eXpand/releases/download/18.2.704.0/Xpand-lib-18.2.704.0.zip into C:\Users\WillemdeVries\Documents\eXpandFr
amework
Expanding files into C:\Users\WillemdeVries\Documents\eXpandFramework\Xpand.DLL
Moving Demos
Write Registry 
You cannot call a method on a null-valued expression.
At C:\Users\WillemdeVries\Documents\eXpandFramework\InstallXpand.ps1:111 char:9
+         $subKey.CreateSubKey("Xpand").SetValue("", $xpandDLL)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Desktop (please complete the following information):**
 - OS: Windows10 Pro
 - Browser MS Edge
 - Version Microsoft Edge 42.17134.1.0

What should i do?

**Comment by apobekiaris** [comment]
do you open powershell as Admin?

it fails to write the registry key

https://github.com/eXpandFramework/XpandPosh/blob/0dbf77050c609829bc2367189da64a995d83433c/XpandPosh/Private/Xpand/InstallXpand.ps1#L109-L111

**Comment by wullumpie** [comment]
Yes. The Powershell title says
Administrator: Windows PowerShell ISE


I tried before with the pure commandline powershell, also run as administrator. Same result.

**Comment by apobekiaris** [comment]
btw u do not need the powershell ISE for running the installer asimple powershell admin prompt is enough.

If you want however to do some scripting with powershell I highly recommend VS Code and its powershell extension. It super fast and you feel like you do c# development with breakpoints, stacktrace and most of VS goodies.

**Comment by wullumpie** [comment]
Hi Tolis,
Thank you. The AssemblyFolders did not exist as you mentioned. Thanks for your superfast response. Problem solved.

I know i could use the powershell admin prompt, but when that did not work properly i thought i could modifiy the script somehow. 

Thanks for mentioning VS Code. I will give it a try!!!

Willem
