### ISSUE TITLE
DevExpress Version 18.2.8

### ISSUE THREAD

**Issue by nurbed** [eXpandFramework/eXpand#400]
**Question**
Sorry, but I can't find the version to be installed in combination with DevExpress 18.2.8.
The eXpand 18.2.704 logically search the dx 18.2.7 dll

**Comment by apobekiaris** [comment]
at the moment we do not have the infrastructure to support multiple majors versions, 18.1.8 released after 19.1.2.

It should be easy however to recompile 18.2.7 release against 18.2.8. Just get the sources, run the 18.2.8 ProjectConverter and then the build.ps1 on the sources root.

**Comment by nurbed** [comment]
mmmm I have problems with the build process. After the project conversion to the v18.2.8, what is the version to be indicated in the file build.ps1 instead of -version "18.2.704.0"? 
If I remove the parameter, it search and try to build the 19 version...

**Comment by apobekiaris** [comment]
did you tried to set the version to 18.2.800.0 ?

**Comment by apobekiaris** [comment]
your sources on the top also reference the 19.1

```ps1
$sources=@("https://api.nuget.org/v3/index.json","https://xpandnugetserver.azurewebsites.net/nuget","C:\Program Files (x86)\DevExpress 19.1\Components\System\Components\packages")   
```

**Comment by nurbed** [comment]
I removed all the reference to the "C:\Program Files (x86)\DevExpress 19.1\Components\System\Components\packages" and replaced  "https://xpandnugetserver.azurewebsites.net/nuget" with  "C:\Program Files (x86)\DevExpress 18.2\Components\System\Components\packages"

**Comment by apobekiaris** [comment]
post the error?

**Comment by apobekiaris** [comment]
this is the correct sources for 18.2
```ps1
$sources=@("https://api.nuget.org/v3/index.json","https://xpandnugetserver.azurewebsites.net/nuget","C:\Program Files (x86)\DevExpress 18.2\Components\System\Components\packages")   
```

xpandnugetserver is needed

**Comment by nurbed** [comment]
InvokeScript :
ErrorRecord                 : Eccezione durante la chiamata di "DownloadString" con "1" argomento/i: "Errore del server remoto: (404) Non trovato."
WasThrownFromThrowStatement : True
Message                     : Eccezione durante la chiamata di "DownloadString" con "1" argomento/i: "Errore del server remoto: (404) Non trovato."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.Net.WebException: Errore del server remoto: (404) Non trovato.
                                 in System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
                                 in System.Net.WebClient.DownloadString(Uri address)
                                 in CallSite.Target(Closure , CallSite , Object , String )
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    in System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 in System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 in System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 in System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 in System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 in System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 in System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                                 in System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                                 in System.Management.Automation.CommandProcessorBase.Complete()
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
In C:\Sviluppo\eXpand\support\build\Build.ps1:24 car:5
+     InvokeScript{
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InvokeScript

InvokeScript :
MyCommand             : Get-XDxNugets
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 18
OffsetInLine          : 16
HistoryId             : 6
ScriptName            : C:\Users\bFree\Documents\WindowsPowerShell\Modules\XpandPosh\1.9.0\public\Xpand\Install-DevExpress.ps1
Line                  :     $dxNugets=(Get-DxNugets $dxVersion)

PositionMessage       : In C:\Users\bFree\Documents\WindowsPowerShell\Modules\XpandPosh\1.9.0\public\Xpand\Install-DevExpress.ps1:18 car:16
                        +     $dxNugets=(Get-DxNugets $dxVersion)
                        +                ~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Users\bFree\Documents\WindowsPowerShell\Modules\XpandPosh\1.9.0\public\Xpand
PSCommandPath         : C:\Users\bFree\Documents\WindowsPowerShell\Modules\XpandPosh\1.9.0\public\Xpand\Install-DevExpress.ps1
InvocationName        : Get-DxNugets
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :
In C:\Sviluppo\eXpand\support\build\Build.ps1:24 car:5
+     InvokeScript{
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InvokeScript

**Comment by apobekiaris** [comment]
oops now i get it 18.2.8 XAF sources are not indexed

https://github.com/eXpandFramework/DevExpress.PackageContent

the scripts index all XAF assemblies so the build can find them. 19.1.2 is the latest so they wont attempt a 18.2.7. I will see if it easy to force indexing and  will update u again

**Comment by nurbed** [comment]
![image](https://user-images.githubusercontent.com/3589082/57690619-56576d00-7642-11e9-8869-f3a31ac9de0f.png)

**Comment by apobekiaris** [comment]
as I said the problem is clear, I require additional time to prepare a 18.2.8 index if is possible

**Comment by apobekiaris** [comment]
18.2.8 is now indexed try to build you should succeed

**Comment by nurbed** [comment]
... after some test I have this error:
![image](https://user-images.githubusercontent.com/3589082/57704452-359f0f80-7662-11e9-9999-349fd433c58f.png)

**Comment by nurbed** [comment]
My fault... for testing purpose I had modified a ps file... After a revert, the version 18.2.800.0 is built
There is only a problem at line 115 of DashboardDesignerForm.cs
`private TDashboardBarButtonItem GetBarItem<TDashboardBarButtonItem>() where TDashboardBarButtonItem : DashboardBarButtonItem {`
will be
`private TDashboardBarButtonItem GetBarItem<TDashboardBarButtonItem>() where TDashboardBarButtonItem : DashboardCommandBarButtonItem {`

**Comment by apobekiaris** [comment]
so u have a build now right?

**Comment by nurbed** [comment]
yes!

**Comment by nurbed** [comment]
Sorry...
After some tests and rebuilds I have always a strange error. All the apps that I execute with eXpand fwk hang after the logon with an error 0xc0000005 Managed Debugging Assistant 'FatalExecutionEngineError' connected to a generic external native dll
Any suggestion for checking it?

**Comment by apobekiaris** [comment]
the only thing change between 18.2.7 and 18.2.8 are the XAF assemblies so I am a bit blind here. I can rebuild it on my system and check your app if you have a sample to reproduce.

**Comment by nurbed** [comment]
I'm trying with DashboardTester

**Comment by apobekiaris** [comment]
thnks i ll update u once i tested myself

**Comment by apobekiaris** [comment]
it might be a problem with missing references in the tester solution, can you try with an empty XAF solution where u will install the modules u want as ussual?

**Comment by apobekiaris** [comment]
at the moment I am on 19.1.3 release and your confirmation will boost resolution for this case.

**Comment by nurbed** [comment]
At the moment I can still do some tests to try to resolve or to have more precise information...

**Comment by nurbed** [comment]
... ok
finally I upgraded my projects to the 19.1.3 version... I have other problems now, but not in this thread :-D
