### ISSUE TITLE
19.1.3 released

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#401]
**Question**
Hi,
Could you release project for devexpress xaf 19.1.3?
Thanks

**Comment by apobekiaris** [comment]
Hi,

yes I am working on it, I mark this issue so the bot will notify u once in lab. It wont' be long after that for release though.

**Comment by expand** [comment]
eXpand.lab release [19.1.300.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.300.1) includes commit [19.1.300.0 #401](https://github.com/eXpandFramework/eXpand.lab/commit/487c0017c52cec65388fc65732fa397fef5c1b63) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
