### ISSUE TITLE
HideToolBar as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#402]
The functionality now lives in system modules in HideToolBarController spawn across the agnostic, win, web assemblies.

release a one assembly standalone package and replace the controllers.

**Comment by expand** [comment]
eXpand.lab release [19.1.301.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.1) includes commit [Install HideToolBar agnostic package #402](https://github.com/eXpandFramework/eXpand.lab/commit/eb1b81f2a42fe748ca824e4e3a7c0f6a4f7596a1) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
