### ISSUE TITLE
Editing a dashboard a second time results in an exception

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#406]
if you create a Dashboard , edit using Dashboard designer, saves it, then open dashboard designer again , an duplicate element exception raises,

	Type:       InvalidNameException
	Message:    Esta colección ya contiene un elemento con el nombre ' DashboardObjectDataSource'
	Data:       0 entries
	Stack trace:

   en DevExpress.DashboardCommon.Native.ObjectNameGenerator.CheckName(String name)
   en DevExpress.DashboardCommon.Native.ObjectTypeNameGenerator.CheckName(String name)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.DataAccess.NotifyingCollection`1.BeforeAddItem(T item)
   en DevExpress.DataAccess.NotifyingCollection`1.InsertItem(Int32 index, T item)
   en Xpand.ExpressApp.Dashboard.Services.Extensions.GetDashboard(IDashboardDefinition dashboardDefinition)
   en Xpand.ExpressApp.Dashboard.Services.Extensions.GetDashboard(IDashboardDefinition dashboardDefinition, XafApplication application, RuleMode ruleMode, IXpandDashboardDataSourceFillService dashboardDataSourceFillService, DataSourceOptionsContainer options, Action`1 editParameters, Action modeParametersEdited)
   en Xpand.ExpressApp.XtraDashboard.Win.Templates.DashboardDesignerForm.LoadTemplate(IDashboardDefinition dashboardDefinition, XafApplication application)
   en Xpand.ExpressApp.XtraDashboard.Win.Controllers.DashboardDesignerController.DashboardEditExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by apobekiaris** [comment]
Thnks fix is provide in #363 and patch is building

**Comment by vimarx** [comment]
the  DataSource is empty for new dashboards
![image](https://user-images.githubusercontent.com/226800/58022505-f3ebea00-7ae3-11e9-960a-4fce255f5dfc.png)

and also the generated XML

**Comment by apobekiaris** [comment]
I guess that you already patched the sources with my previous suggestion which was a bad one. I tested this one and works for both cases

```cs
        private static void AddNewDataSources(IDashboardDefinition dashboardDefinition, DevExpress.DashboardCommon.Dashboard dashboard){
            var dashboardTypesCount = dashboardDefinition.DashboardTypes.Count;
            if (dashboardTypesCount > 1) {
                throw new UserFriendlyException($"{dashboardDefinition.Name} contains {dashboardTypesCount} dashboard types. Only one dashboard type is supported.");
            }

            
            var wrapper = dashboardDefinition.DashboardTypes.First();
            var dataSource = new DashboardObjectDataSource{
                DataSourceType = wrapper.Type,
                Name = nameof(DashboardObjectDataSource),
                ComponentName = nameof(DashboardObjectDataSource)
            };
            if (!dashboard.DataSources.Any()) {
                dashboard.DataSources.Add(dataSource);
            }
        }

```

**Comment by expand** [comment]
eXpand.lab release [19.1.301.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.1) includes commit [Editing a dashboard a second time results in an exception #406](https://github.com/eXpandFramework/eXpand.lab/commit/e2b0db2a2508cba1a4c8cc28b81c29489db6ad82) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by rSeeFip** [comment]
and with this restriciton, how it's possible to use multiple datasources with federal datasource in Dashboard ?

**Comment by apobekiaris** [comment]
can u provide me an example of how do u want to use multiple datasources?

**Comment by rSeeFip** [comment]
1.  With 19.1 expand its necessary to selected type for Dashboard, i have many Dashboards where i use 
     only SQLDatasource  f.e. Access or different Databases. 

2. i have several Dashboards where i use more than one type, because they not associated

3. I try Federal Datasource with one type and one SQLDatasource in Designer i get items on both 
   connections in Designer, after saving and closing Designer  i can't reopen beacuse i get error that  
   already an "DashboardObjectDataSource"

   
With #363 and #406 i **must** select an type and **can only** select **one** type

**Comment by apobekiaris** [comment]
>With 19.1 expand its necessary to selected type for Dashboard, i have many Dashboards where 

i will fix this problem

>i have several Dashboards where i use more than one type, because they not associated

is this supported in the XAF native module?

**Comment by rSeeFip** [comment]
yes its supported, I've now created xaf 19.1 project with to BO's and it is possible to add both on one dashboard
![image](https://user-images.githubusercontent.com/43534405/58257508-54dc2200-7d71-11e9-9997-0e4f4c3dff20.png)

**Comment by apobekiaris** [comment]
hmm my apologies then i was under the wrong consumption, I will revert those changes asap.

**Comment by rSeeFip** [comment]
thanks a lot

**Comment by expand** [comment]
eXpand.lab release [19.1.302.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.4) includes commit [Revert "Dashboard: DisableMultiDashboardTypeController #406 #363" 0f1841fb1bbc4de50b06553f362e6bd58f0af31e.](https://github.com/eXpandFramework/eXpand.lab/commit/795ba421ad712bdac60eaefb09d7be549d81d5f9),[Revert "XtraDashboard: DashoardName is not localized #406 #363" commit 8a13613a949b63657bf3345894bdfa76b6dae339.](https://github.com/eXpandFramework/eXpand.lab/commit/0934624316ce52481b70ffa2741b902101cf90bc),[Revert "Force only one DashboardObjectDataSource #363" #406

This reverts commit f653e4d5620d3e6db30d25a5a2816eb9d4bfb597.](https://github.com/eXpandFramework/eXpand.lab/commit/79253eb2f5fba65829b67b663dbf43cd7c495ed1) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by rSeeFip** [comment]
With your fix it is still not possible to select multiple types and when trying to open an existing dashboard with multiple types in Editor the following error occurs "External DashboardName contains x dashboard tpyes. Only one dashboard is supported" out from 
Xpand.ExpressApp.XtraDashboard.Win.Controllers.DashboardDesignerController

**Comment by apobekiaris** [comment]
hmm at least on my side I can edit a dashboard select more types and they will show in the designer lookup

![image](https://user-images.githubusercontent.com/159464/58466669-c5ed5200-8142-11e9-8281-be7f52aff125.png)

![image](https://user-images.githubusercontent.com/159464/58466657-bcfc8080-8142-11e9-804c-8dbb9547d073.png)

are you sure you are in the correct version cause these reverts are done from git, haven't changed anything

**Comment by rSeeFip** [comment]
Sorry, using wrong Version

Thanks for support

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
