### ISSUE TITLE
ExcelImporter - check string size

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#407]
**Is your feature request related to a problem? Please describe.**
The ExcelImporter does not throw a exception when string data is too long.

**Describe the solution you'd like**
ExcelImporter checks if string is too long. 

In my last import, excelimporter showed the a successful message but does not import anything. 
Then i realiszed that one cell value of my data was a string of 108 chars, but in the application only 100 max was allowed. I would be great to throw a exception in failed result.

BR
ISA

**Comment by apobekiaris** [comment]
Sorry for the delay, here my results:

I fixed the non functional ValidationContexts so you can Validation rules to your objects and handle any case is not covered internally. However this will use the native XAF way to display naviation errors on Save action execution and records will not be in Failed results.

Now, some common cases, like Size, and null for keys are handled internally and will be in FailedResults.

In general FailedResults list contains conversion errors and the 2 common cases I mentioned above. All other exceptions will be dispatched to the UI.

The bot will notify you when the build is ready.

**Comment by expand** [comment]
eXpand.lab release [19.1.302.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.3) includes commit [ExcelImporter: ValidationContexts are not functional and Exceptions not dispatched to the UI #398 #407](https://github.com/eXpandFramework/eXpand.lab/commit/c55f201e06e230bfdc9f6c5df5b261eae07e524c) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
