### ISSUE TITLE
Add readme for eXpand NuGet

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#408]
ReadMe should provide an easy copy-paste installation line, and related standalone packages message

**Comment by apobekiaris** [comment]
#405

**Comment by apobekiaris** [comment]
also add .net4.6.1 dependencency

**Comment by expand** [comment]
eXpand.lab release [19.1.301.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.4) includes commit [Add readme for eXpand NuGet #408](https://github.com/eXpandFramework/eXpand.lab/commit/b8d9852dfd62eddb2fe6ec0c19be7ee48d8922b9) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
