### ISSUE TITLE
eXpandTreeListEditors missing from Nuget

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#409]
Updating nugets to 19.1.301.3 and it fails for eXpandTreeListViewWin (required for IOWin):
Unable to resolve dependency 'eXpandTreeListEditors'. Source(s) used: 'nuget.org', 'XPand nightly'

**Comment by expand** [comment]
eXpand.lab release [19.1.301.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.4) includes commit [NuGets with TreeListEditor dependencies are generated wrong #409](https://github.com/eXpandFramework/eXpand.lab/commit/d8ce63bd87b1dc0e8be98c09da3dadedaeb4630d) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
