### ISSUE TITLE
Several 19.1.301 nugets have dependencies to 18.2.704 packages in nuspec

### ISSUE THREAD

**Issue by comstyle** [eXpandFramework/eXpand#410]
Several 19.1.301 nugets have dependencies to 18.2.704 packages in nuspec

For example expandio 19.1.301 has a dependency like that:
 `<dependency id="eXpandLib" version="18.2.704" />`
Have seen that in others, maybe problem is for all.

**Comment by apobekiaris** [comment]
I guess this is a global problem I thought it was only for lab builds it is fixed there if you want to try see https://github.com/eXpandFramework/eXpand/issues/405#issuecomment-494238412

note that packagesrefrences are still not supported you should use packages.config forma if u are on nuget.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
