### ISSUE TITLE
Excel Importer - Notification Message too short

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#411]
Hi,

In my app with mysql, the field notificationMessage is a 100 char. 
According to the text set, i always have a exception because the data is too long.
DevExpress.Xpo.DB.Exceptions.SqlExecutionErrorException
  HResult=0x80131500
  Message=Exécution de SQL 'insert into `ImportNotification`(`Oid`,`AlarmTime`,`NotificationMessage`,`IsPostponed`,`OptimisticLockField`,`GCRecord`)values(?p0,?p1,?p2,?p3,?p4,null)' avec les paramètres '{ea4afa39-96b5-43a4-8689-1285151a338e},{22.05.2019 00:49:44},{Exception when importing 13B-PREMIUMSDATA-PREMIUMS.xlsx - Exécut...},{False},{0}' exception 'MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'NotificationMessage' at row 1
   à MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   à MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   à DevExpress.Xpo.DB.ConnectionProviderSql.<>c__DisplayClass109_0.<InternalExecSql>b__0()
   à DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   à DevExpress.Xpo.DB.ConnectionProviderSql.InternalExecSql(IDbCommand command)
   à DevExpress.Xpo.DB.ConnectionProviderSql.ExecSql(Query query)'
  Source=DevExpress.Data.v19.1

https://github.com/eXpandFramework/eXpand/blob/262c6277839d513332f9299184100dab8767c945/Xpand/Xpand.ExpressApp.Modules/ExcelImporter.Win/Controllers/AutoImportController.cs#L115-L120

can we adjust the size of the Notification Message to 250 char ? 

BR
ISA

**Comment by expand** [comment]
eXpand.lab release [19.1.302.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.3) includes commit [ExcelImporter: Provide a DSL/Reactive implementation on the AutoImport functionality #412 #411](https://github.com/eXpandFramework/eXpand.lab/commit/8ca18b25eb6e48e54fb60df29fb0d2517eb6834a) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
