### ISSUE TITLE
ExcelImporter - AutoImport Howto

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#412]
Hi,

Can we have some more details on the auto import works. 
I saw a File watcher in the code. Is there any frequency ? 
When i put my files in the given folder nothing happend. 
Actually when I ran the app once from vs, i saw on file was imported but the new ones are not. 

How can i trigger the parsing of the folder manually ? 

BR
ISA

**Comment by apobekiaris** [comment]
I refactor the AutoImporter and now follows the reactive style used from the StandAlone modules.

Short docs.

A signal will be created out of existing imports and mnodified that can AutoImport. Autoimport means we have at least a valid path and some other conditions like the Autoimport did not failed/stopped or already imported. The module for each import saves the file name and its creation date and compares it next time so it knows if is already imported. Dropping any file that match the `AutoImportRegex` in a watched dir will trigger an import. If an import failed the user will be notified with the Notifications module.

So foreach signal emit a directory watcher will be created and the existing data will be polled. The result then is feed to the same import method as for manual import.

**Comment by expand** [comment]
eXpand.lab release [19.1.302.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.3) includes commit [ExcelImporter: Provide a DSL/Reactive implementation on the AutoImport functionality #412 #411](https://github.com/eXpandFramework/eXpand.lab/commit/8ca18b25eb6e48e54fb60df29fb0d2517eb6834a) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Hi,

I tested with 19.1.302.5. My Excel file contains 250k lines. I splited the excel into 500 files (500 line each) 
As test, i put 3 files into the defined folder : OK
Then i deleted the Auto Imported rows in the nested collection, changed the folder and put the 500 files into it. The watcher did not parse the folder. In the log i do not see any error.

I created a new Excel Import from scratch, did the mapping and set the folder again with these 500 files. But no import. 

**The main issue is that we do not see is happening when nothing happend. I would be great to be able also to trigger it manually somehow, to see if everything is ok with the auto import.** 

BR
ISA

**Comment by apobekiaris** [comment]
>The main issue is that we do not see is happening when nothing happend. I would be great to be able also to trigger it manually somehow, to see if everything is ok with the auto import.

triggering manually makes no sense, however I agree that current UI is a blackbox. So, next minor features the Dropped files tab where you will have an entry as soon as a dropped/renamed file matches the `Regex` with `SkipReason` if any.

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/eXpand.lab/releases/tag/19.1.303.2

**Comment by isatahiri** [comment]
He dropped files helps a lot, thanks. 
When i drop multiple file (2-3) it takes only the last one.
If i drop 500 files, nothing happen. (i waited about 10 minutes and no notification and in the dropped files, no row was added) 

BR
ISA

**Comment by isatahiri** [comment]
Sorry i took time but after some minutes the system to the second file. 
I will redo some more test with large amount of files.

**Comment by isatahiri** [comment]
When i put 500 files, the last one is taken but the 499 other files are not in the dropped file table. Can you try your solution with large amount of files ? 

If not i can send a test solution. 

BR
ISA

**Comment by isatahiri** [comment]
Now when i went to the excel importer record to check Imports and dropped files and i try to close in with a save and close action, the import of other files is triggered. But the app is frozen now as it imports a really large amount of data. 

Also i discovered that the module trys also to import the tmp file which is create when we open an excel file in the dropped folder.

**Comment by isatahiri** [comment]
demo app is sent. See #428

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
