### ISSUE TITLE
Exception after opening a second time a detalview in 19.1.302

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#413]
ComprobanteVentaPago do not implement Iobjectspacelink, is a persistent object  derives from custom XPCustomObject 
How Can I Disable CloneViewController?

Thanks

 
**System.InvalidCastException**: No se puede convertir un objeto de tipo 'Vimarx.Factura.ComprobanteVentaPago' al tipo 'DevExpress.ExpressApp.IObjectSpaceLink'.
en Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueService.<>c.b__14_7(ValueTuple`2 _)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
en System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
en System.Reactive.Stubs.<>c.b__2_1(Exception ex)
en System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
en System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Subjects.Subject`1.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.IdentitySink`1.OnNext(T value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.IdentitySink`1.OnNext(T value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.HalfSerializer.ForwardOnNext[T](ISink`1 sink, T item, Int32& wip, Exception& error)
en System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnNext(TSource value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.b__1(Object sender, TEventArgs eventArgs)
en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
en DevExpress.ExpressApp.XafApplication.OnDetailViewCreated(DetailView view)
en DevExpress.ExpressApp.Win.WinApplication.OnDetailViewCreated(DetailView view)
en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading)
en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, Object obj, Boolean isRoot)
en F.Module.Vimarx.Turismo.TurismoController.PagoACuentaTurismo_Execute(Object sender, SimpleActionExecuteEventArgs e)
en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
19.1.0521.1
System.ValueTuple`3[DevExpress.ExpressApp.Model.IModelObjectView,DevExpress.ExpressApp.IObjectSpaceLink,DevExpress.ExpressApp.IObjectSpaceLink] b__14_7(System.ValueTuple`2[DevExpress.ExpressApp.DetailView,DevExpress.ExpressApp.DetailView])
en Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueService.<>c.b__14_7(ValueTuple`2 _)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
en System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
en System.Reactive.Stubs.<>c.b__2_1(Exception ex)
en System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
en System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Subjects.Subject`1.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.IdentitySink`1.OnNext(T value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.IdentitySink`1.OnNext(T value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.HalfSerializer.ForwardOnNext[T](ISink`1 sink, T item, Int32& wip, Exception& error)
en System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnNext(TSource value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.b__1(Object sender, TEventArgs eventArgs)
en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
en DevExpress.ExpressApp.XafApplication.OnDetailViewCreated(DetailView view)
en DevExpress.ExpressApp.Win.WinApplication.OnDetailViewCreated(DetailView view)
en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading)
en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, Object obj, Boolean isRoot)
en F.Module.Vimarx.Turismo.TurismoController.PagoACuentaTurismo_Execute(Object sender, SimpleActionExecuteEventArgs e)
en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by vimarx** [comment]
I', not referencing directly CloneValueService, how can I avoid using it?

**Comment by apobekiaris** [comment]
hmm there is no way to disable at the moment I will think about it. The Fastet woraround assuming that you have a custom BaseObject or if not create one and implement IObjectSpaceLink there.

**Comment by apobekiaris** [comment]
or since u have the source faster for u maybe to register the module and recompile?

https://github.com/eXpandFramework/eXpand/blob/1d300477dc10bfddddf82c102fe3cbc7853ad798/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/SystemModule/XpandSystemModule.cs#L41

**Comment by vimarx** [comment]
I'm already working on that workaround (Implement IObjectspacLink), but I do not use it for no other reason,

Now I'm facing object disposed exceptions in the same situation from a PersistentAlias used as DefaultProperty

**Comment by apobekiaris** [comment]
apparently we have a bug there I am working for it, given a solution the thing u have to do 

```ps1
Update-Package CloneMemberValue -Source https://xpandnugetserver.azurewebsites.net/nuget
```

**Comment by apobekiaris** [comment]
this should be done in your front end project so to override previous installation.

**Comment by apobekiaris** [comment]
I do not see any other way that the module is activated so to throw at that point unless there is an explicit activation.

can u verify that none of your *.xafml files have a CloneValue entry?

**Comment by vimarx** [comment]
> I do not see any other way that the module is activated so to throw at that point unless there is an explicit activation.
> 
> can u verify that none of your *.xafml files have a CloneValue entry?

It works!! removing CloneValue from .xafml was the best workaround for me.
Thanks

**Comment by apobekiaris** [comment]
hmm was that your BO or something else that I need to take care?

**Comment by apobekiaris** [comment]
for future reference here another way to disable any XAF module at your own risk of course

```cs
public TestWinApplication(){
            SetupComplete+=OnSetupComplete;
        }

        private void OnSetupComplete(object sender, EventArgs e){
            var module = Modules.FindModule(typeof(CloneMemberValueModule));
            _applicationModulesManager.Modules.Remove(module);
            module.Dispose();
        }

        protected override ApplicationModulesManager CreateApplicationModulesManager(ControllersManager controllersManager){
            _applicationModulesManager = base.CreateApplicationModulesManager(controllersManager);
            return _applicationModulesManager;
        }
```

**Comment by apobekiaris** [comment]
To finish my thoughts on this issue, the CloneMemberValue in order to clone the object need to implement IObjectSpaceLink, I removed that dependency in the next update. The bot will notify u is ready the update processes is the same I mentioned before . You do not need to update the universe just the module in your front end.

**Comment by vimarx** [comment]
> hmm was that your BO or something else that I need to take care?

Just removed all CloneValue for avoiding Clonevalueservice to activate, no Iobjectspacelink implementation nor BO modification

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [Declare module.Unload method #413](https://github.com/eXpandFramework/DevExpress.XAF/commit/2f2f89f09abc516785c4bd605eacbb93e28da0a2),[CloneMemberValue: Remove IObjectSpaceDependency #413](https://github.com/eXpandFramework/DevExpress.XAF/commit/ed8f76bf4768a285bf5e61875d8a89fce7aa0eb0) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
