### ISSUE TITLE
VersionConverter does not patch projects with PackageReference format

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#414]
**Describe the bug**
There is no indication that something went wrong, and it fails only when run since patching never occurred.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [VersionConverter does not patch projects with PackageReference format #414](https://github.com/eXpandFramework/DevExpress.XAF/commit/e59e766d7e7fc2b29ea317b20dd5c1c49e6ae51f) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Is this problem fixed? I'm using PackageReferences for the 19.1.303.0 release, but the 1.0.26 build of the VersionConverter does not work for me. ` ~\.nuget\packages\xpand.versionconverter\1.0.26\build\Xpand.VersionConverter.targets(4,9): error: Der Wert "4.7.3190.0 built by: NET472REL1LAST_C" kann nicht in den Typ "System.Version" konvertiert werden.`
This happens because VersionConverter cannot find the DevExpress dlls (they are not installed in the GAC) and instead picks the .Net Accessibility dll from the GAC.

**Comment by apobekiaris** [comment]
there were works sure and the bot linked the related commits as you see. Now there is a uniform approach for both packagereferences and packages.config. 

However apparently we need to extend the work work a bit since it can not find the DX assemblies for u. So how do you use DX so I may try to reproduce the case?

**Comment by apobekiaris** [comment]
from what I can guess there are two options which as far as I can tell they should be both covered.

1. Nuget so there is a valid HintPath
2. From a custom path so again we have a valid HintPath

so I am not clear what I have to try to repro this problem. Here is the DX version detection method

https://github.com/eXpandFramework/DevExpress.XAF/blob/e5a9449d7f32ea9d4823f3d53c9bbcf5e6bd2e79/tools/Xpand.VersionConverter/Functions.ps1#L68-L110

**Comment by krombipils** [comment]
>     1. Nuget so there is a valid HintPath

I'm using nuget, but there is no HintPath in my csproj, e.g.

```
<ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp.Win" Version="$(DevExpressVersion)" />
</ItemGroup>
```

DevExpressVersion is defined as a variable in the solution's directory.build.props

**Comment by apobekiaris** [comment]
hmm I do not recall testing this case explicitly give me some time please.

**Comment by apobekiaris** [comment]
I did not test but on a first thought it looks like you can make it work until I research by replacing the `Get-DevExpressVersion` function in your %userprofile%\.nuget\packages\Xpand.VersionConverter\1.0.26\Build\Functions.ps1 with:

```ps1
function Get-DevExpressVersion($targetPath, $referenceFilter, $projectFile) {
    [version]"19.1.3"
}
```

**Comment by krombipils** [comment]
Thank you, the workaround is working fine.
Looking forward to a real solution...

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [VersionConverter does not patch projects with PackageReference format #414](https://github.com/eXpandFramework/DevExpress.XAF/commit/976e7458194ae3e359399a25f2a706e1b6b4c543) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
