### ISSUE TITLE
VersionConvertor exception when building

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#415]
I'm getting a buil error when building our implementation of eXpand sources using the versionConvertor nuget package.

This is the build error:
`------ Build started: Project: Vekrasoft.Persistent.Base, Configuration: Debug Any CPU ------
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.ps1 : 
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : Message                     : Cannot bind argument to parameter 'Path' because it is null.
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ParameterName               : Path
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ParameterType               : System.String[]
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : TypeSpecified               : 
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ErrorId                     : ParameterArgumentValidationErrorNullNotAllowed
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : Line                        : 45
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : Offset                      : 33
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : CommandInvocation           : System.Management.Automation.InvocationInfo
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ErrorRecord                 : Cannot bind argument to parameter 'Path' because it is null.
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : WasThrownFromThrowStatement : False
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : InnerException              : 
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               Exception)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : StackTrace                  :    bij System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionCo
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               ntext funcContext, Exception exception)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFr
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               ame frame)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Inter
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               pretedFrame frame)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Inter
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               pretedFrame frame)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInv
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               oke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 vari
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               ablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object in
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               put, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               0()
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesW
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               ithThreadCheck(Action action)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Err
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               orHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object script
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               This, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               , List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, B
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               oolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Ob
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                               ject input, Object scriptThis, Object[] args)
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.Cmdlet.DoProcessRecord()
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                                  bij System.Management.Automation.CommandProcessor.ProcessRecord()
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : HelpLink                    : 
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : Source                      : System.Management.Automation
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : HResult                     : -2146233087
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : At line:1 char:5
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : + & { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionCon ...
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Xpand.VersionConverter.ps1
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :  
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.ps1 : 
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : MyCommand             : ForEach-Object
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : BoundParameters       : {}
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : UnboundArguments      : {}
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ScriptLineNumber      : 43
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : OffsetInLine          : 24
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : HistoryId             : 1
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ScriptName            : C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.Versio
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                         nConverter.ps1
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : Line                  :     $moduleDirectories|ForEach-Object{
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                         
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : PositionMessage       : At C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.Ver
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                         sionConverter.ps1:43 char:24
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                         +     $moduleDirectories|ForEach-Object{
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                         +                        ~~~~~~~~~~~~~~~
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : PSScriptRoot          : C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : PSCommandPath         : C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.Versio
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :                         nConverter.ps1
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : InvocationName        : ForEach-Object
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : PipelineLength        : 0
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : PipelinePosition      : 0
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : ExpectingInput        : False
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : CommandOrigin         : Internal
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : DisplayScriptPosition : 
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : At line:1 char:5
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : + & { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionCon ...
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Xpand.VersionConverter.ps1
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error :  
C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\\Xpand.VersionConverter.ps1' 'C:\Source\Vekrasoft ExpressApp\Source\Base\Vekrasoft.Persistent.Base\Vekrasoft.Persistent.Base.csproj' 'C:\Source\Releases\Vekrasoft ExpressApp\' } "" exited with code -1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by apobekiaris** [comment]
edit the C:\Source\Vekrasoft ERP\Vekrasoft.ERP\packages\Xpand.VersionConverter.1.0.24\build\Xpand.VersionConverter.ps1' 

and uncomment the first line VerbosePreference =continue and post the output again

**Comment by apobekiaris** [comment]
official packages are not on VersionConverter 1.0.24 am I right you use lab packages? or did you explicitly upgrade to latest?

**Comment by apobekiaris** [comment]
even if you provide verbose output I cannot tell whats the problem. it looks like the $modulesDirectories enumeration is wrong, so a better suggestion is in addition to enable the verbose flag at the top of the versionconverter.ps1 add the next after 43
https://github.com/eXpandFramework/DevExpress.XAF/blob/e59e766d7e7fc2b29ea317b20dd5c1c49e6ae51f/tools/Xpand.VersionConverter/Xpand.VersionConverter.ps1#L43


write-verbose "moduleDir=$_"

**Comment by jacobdeboer33** [comment]
Hi Tolis

I solved the problem. I added the line you suggested and saw the directory that let the script fail. It was a old directory of a old Xpand.XAF.Module.Reactive version only containing an empty lib directory. The old directory was the problem. I Removed it and the script works.

Thanks,
Jacob

**Comment by apobekiaris** [comment]
can you tell me why the script fail for the old dir? I want to handle the case on the script level

**Comment by apobekiaris** [comment]
hmm bad question it's obvious that it willfail in the next lines if an assymbly is not found I will update it accordingly.

Thanks for the feedback.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [VersionConverter fails when invalid package directories exist #415](https://github.com/eXpandFramework/DevExpress.XAF/commit/2749fd60e1a90f577637985be7e0e7bca0189d40) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.
