### ISSUE TITLE
Enum property Editor

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#416]
Xpand.ExpressApp.Win.PropertyEditors.EnumPropertyEditor.ObjectSpaceOnObjectChanged(Object sender, ObjectChangedEventArgs e) D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\EnumPropertyEditor.cs in : line 78

I dont using enum property editor but i got null ref at this line. I guess Control is null

**Comment by apobekiaris** [comment]
this is the default editor for all Enum unless you specify other wise. I ll update you on the fix again.

**Comment by expand** [comment]
eXpand.lab release [19.1.302.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.2) includes commit [Make EnumPropertyEditor non default editors and fix null reference on WinEnumpropertyEditor #416 #404](https://github.com/eXpandFramework/eXpand.lab/commit/99fb80a764328776f87dee4af36ed048a1a2539d) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
