### ISSUE TITLE
Clean-up Demos directory

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#417]
Tester solution are designed to run the Easytest and not to demo stuff, remove them they confuse people.

Furthermore remove Demos like 
1. SecurityDemo: is an overkill solution that offers the least value, we do not have anything that interacts or adds value to that demo.
2. Workflow: The consumers of the XPandWorkflow demos can use the default XAF templates
3. Remoting: Thats for dinosaurs

We aim to provide docs through the http://xaf.expandframework.com project and the main project will act as a container to them.

**Comment by apobekiaris** [comment]
see also #403

**Comment by expand** [comment]
eXpand.lab release [19.1.302.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.2) includes commit [Clean-up demos folder #417 #403](https://github.com/eXpandFramework/eXpand.lab/commit/b0df3365445442c86d16d26c57fba8812127c0d0) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
