### ISSUE TITLE
VSIX displays Version too short message 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#418]
This happens when use the eXpandFramework New Project Wizard

**Comment by expand** [comment]
eXpand.lab release [19.1.302.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.4) includes commit [VSIX displays Version too short message #418](https://github.com/eXpandFramework/eXpand.lab/commit/a191ae1d4f7eee75959400cf7a9ad71dd57bd676) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
