### ISSUE TITLE
Controlling ModelDifference objects' names

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#419]
I need the application models for win and web use different names from Application Title set in the model. E.g. Base Model (Win) and Base Model (Web). Whats the best way to do it?

Thanks,
Evgeniy

**Comment by apobekiaris** [comment]
hmm there is no way to do it on construction of the object. I added an `ModelDifferenceApplicationTitle` in the Model.Options for the next minor.

**Comment by emeyke** [comment]
Great, thanks.

**Comment by expand** [comment]
eXpand.lab release [19.1.302.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.4) includes commit [ModelDifference: Option to control Persistent Application names #419](https://github.com/eXpandFramework/eXpand.lab/commit/f9f6d6d3c77eeec672b0c97d9c82942f361c1f67) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
