### ISSUE TITLE
Installing eXpandSecurity 19.1.302 from NuGet failed

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#420]
eXpandSecurity 19.1.302 depends on Xpand.XAF.Modules.ModelViewInheritance 1.1.21.2 but that version doesn't exist.

**Comment by apobekiaris** [comment]
apologies for this, I will reasearch and upadte you. Until then I have a fast workaround. The version you posted has a Revision number which really means it comes from the lab. So if you can add our lab NugetServer to your VS nuget package source you should be able to install.

https://xpandnugetserver.azurewebsites.net/nuget

**Comment by gerritmulder** [comment]
Tolis,

The problem seems to be solved when adding the XpandLab nuget server. I see I don't have to address the problem as you already apologized for adding a package in the lab to a stable release.

Thanks,
Gerrit

**Comment by apobekiaris** [comment]
great to hear, either way the bot will update the ticket again once there is no need to have the lab server in your nuget sources
