### ISSUE TITLE
VSIX won't load in VS2019

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#422]
**Is your feature request related to a problem? Please describe.**
latest preview by default does not load plugins that do not use the new async API

**Describe the solution you'd like**
Make the plugin async

**Comment by expand** [comment]
eXpand.lab release [19.1.303.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.1) includes commit [VSIX won't load in VS2019 #422](https://github.com/eXpandFramework/eXpand.lab/commit/1c7ccdd4068a1d55ce29997c2c62021861c270d6) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
