### ISSUE TITLE
Test Installer script on Azure for each release

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#423]
Create a pipeline in the https://github.com/eXpandFramework/Azure-Tasks

**Comment by apobekiaris** [comment]
see also #421

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/Azure-Tasks#test-installer-script

**Comment by dtbagg** [comment]
I think this worked much better, but the Xpand projects were not available and VSIX did not seem to install. Problem may still be on my end.  Maybe I am not allowing unsigned or something. Part of the log file:

5/31/2019 10:03:36 AM - Initializing Install...
5/31/2019 10:03:40 AM - Extension Details...
5/31/2019 10:03:40 AM - 	Identifier         : Xpand.VSIX.eXpandFramework.4ab62fb3-4108-4b4d-9f45-8a265487d3dc
5/31/2019 10:03:40 AM - 	Name               : Xpand.VSIX
5/31/2019 10:03:40 AM - 	Author             : eXpandFramework
5/31/2019 10:03:40 AM - 	Version            : 1.0
5/31/2019 10:03:40 AM - 	Description        : VSIX Project.
5/31/2019 10:03:40 AM - 	Locale             : en-US
5/31/2019 10:03:40 AM - 	MoreInfoURL        : 
5/31/2019 10:03:40 AM - 	InstalledByMSI     : False
5/31/2019 10:03:40 AM - 	SupportedFrameworkVersionRange : [4.5,)
5/31/2019 10:03:40 AM - 
5/31/2019 10:03:40 AM - 	SignatureState     : Unsigned
5/31/2019 10:03:40 AM - 	Supported Products : 
5/31/2019 10:03:40 AM - 		Microsoft.VisualStudio.Community
5/31/2019 10:03:40 AM - 			Version : [14.0,17.0)
5/31/2019 10:03:40 AM - 		Microsoft.VisualStudio.Pro
5/31/2019 10:03:40 AM - 			Version : [14.0,17.0)
5/31/2019 10:03:40 AM - 		Microsoft.VisualStudio.Enterprise
5/31/2019 10:03:40 AM - 			Version : [15.0,17.0)

**Comment by apobekiaris** [comment]
hmm I cannot follow you what worked better?
after running the script i get the VSIX
![image](https://user-images.githubusercontent.com/159464/58714237-fb0cd500-83cc-11e9-81d3-c20111d208b6.png)

which when installed 

![image](https://user-images.githubusercontent.com/159464/58714269-0e1fa500-83cd-11e9-9fdd-b70d0e7576e2.png)

what is your VS version? although there are all versions are supported but maybe i missed something

https://github.com/eXpandFramework/eXpand/blob/6deb9088ff3ea570123234ac7e18fe462d9fcbf6/Xpand.Plugins/Xpand.VSIX/source.extension.vsixmanifest#L8-L12

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
