### ISSUE TITLE
ProgressBarViewItem as standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#425]
The existing `ProgressViewItem` now spawn in the 3 system modules. The new package should be one assembly only with support for both platforms. After release the existing package will be replaced in the system modules and in addition installed in the ExcelImporter that uses it explicitly.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commit [ProgressBarViewItem as standalone package #425](https://github.com/eXpandFramework/DevExpress.XAF/commit/25d9067cf0b86cd94777e7f7451d85ab922e9e12) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.303.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.3) includes commit [ProgressBarViewItem integration #425](https://github.com/eXpandFramework/eXpand.lab/commit/9e1f5cd12767bad178304efa284e2f34f3086ccf) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
