### ISSUE TITLE
VersionConverter fails when DevExpress is installed from Nugets

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#426]
Is this problem fixed? I'm using PackageReferences for the 19.1.303.0 release, but the 1.0.26 build of the VersionConverter does not work for me:
` ~\.nuget\packages\xpand.versionconverter\1.0.26\build\Xpand.VersionConverter.targets(4,9): error: Der Wert "4.7.3190.0 built by: NET472REL1LAST_C" kann nicht in den Typ "System.Version" konvertiert werden.`
This happens because VersionConverter cannot find the DevExpress dlls (they are not installed in the GAC) and instead picks the .Net Accessibility dll from the GAC.

_Originally posted by @krombipils in https://github.com/eXpandFramework/eXpand/issues/414#issuecomment-498578281_

**Comment by apobekiaris** [comment]
@krombipils I can repro the case however my csproj looks like amd like you posted. Any ideas how do I get your format as well?

```xml
<PackageReference Include="Devexpress.expressapp">
      <Version>19.1.3</Version>
    </PackageReference>
```

**Comment by krombipils** [comment]
I manually converted my csproj files to the new sdk-style format and used this format.

**Comment by apobekiaris** [comment]
not a bad idea at all, I will support your variable as well

**Comment by krombipils** [comment]
I just tested version 1.0.27 of the version converter and it does work if using e.g `<PackageReference Include="DevExpress.ExpressApp.ConditionalAppearance" Version="19.1.3" />` (using variables from directory.build.props is not supported yet).
But unfortunatly the ordering of the package references is important: VersionConverter always uses the first PackageReference, but this might be not a DX reference

**Comment by apobekiaris** [comment]
>directory.build.props is not supported yet)

apologies i missed this one.

>But unfortunatly the ordering of the package references is important: VersionConverter always uses the first PackageReference, but this might be not a DX reference

right I will fix this asap, thnks

**Comment by krombipils** [comment]
I just noticed, that there is also a problem, if the csproj does not contain a direct dx reference at all: `.VersionConverter.targets(4,9): error : throw "Cannot find DevExpress Version"`
The problematic project only has a indirect reference to DX by a ProjectReference to another project in the solution

**Comment by apobekiaris** [comment]
I think we should rely to `directory.build.props` for those cases as such a feature requires resources I do not currently have. A descriptive message from where the DXVersion can be read e.g  `directory.build.props` should address all related issues.

**Comment by krombipils** [comment]
Sounds like a sensible and pragmatic solution!

**Comment by apobekiaris** [comment]
to my understanding as i haven't played around with `directory.build.props` these are jsut msbuild variables and can be read as $(DXVersion) and do not need to be explicitly in  `directory.build.props` but can also be in the csproj of the module. Can you confirm my understanding?

**Comment by krombipils** [comment]
That's correct. The variables from directory.build.props are automatically imported in the projects when building the solution

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [VersionConverter: DevexpressVersion not detected when packageReferences #435 #426](https://github.com/eXpandFramework/DevExpress.XAF/commit/dc466f5ead3ea00acce5985250d12e3d438b5021)
* [VersionConverter: Add Support for custom DevExpressVersion and for howtoenable verbose messaging  #435 #426](https://github.com/eXpandFramework/DevExpress.XAF/commit/c2d4d7b1dd17eb658441f475878ccffee92587a7)
* [VersionConverter: VersionConverter: Continue patching with a warning if symbols not matched #435 #426](https://github.com/eXpandFramework/DevExpress.XAF/commit/d8f087ce592ac44ae43155bdc46acf75607ec659)
* [VersionConverter: Skips patching if at least one package is already patched  #435 #426](https://github.com/eXpandFramework/DevExpress.XAF/commit/3b902915d9bc84d865a62632ee0fc623713e7412)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [VersionConverter: Does not handle all symbol related exceptions #435 #426 #436](https://github.com/eXpandFramework/DevExpress.XAF/commit/7e68180951ca731cb51a339d57ae6f454d0fdee5)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.303.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.4) includes commit that relate to this task:

* [Update Nuget packages #435 #426](https://github.com/eXpandFramework/eXpand.lab/commit/fdbe82cb0b21b0ed3f7c64ccb1b9431012dd5cf9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Unfortunately the `<PropertyGroup><DevExpressVersion>19.1.3</DevExpressVersion></PropertyGroup> `solution is still not working for me in VersionConverter 1.0.28.
There is a `$DevExpressVersion` param in Xpand.VersionConverter.ps1, but does not seem to be used.
If a version cannot be found by `$dxVersion = Get-DevExpressVersion $targetPath $referenceFilter $projectFile ` the warning is printed and an error is thrown.

**Comment by apobekiaris** [comment]
yes you are right, looks like i missed it in the latest refactoring, added to 1.0.29

**Comment by krombipils** [comment]
Hi, just checked your [VersionConverter: Custom dxversion is not used #426 ](https://github.com/eXpandFramework/DevExpress.XAF/commit/b1df47fd01cd9073a3a06d556c9e9ebe6f0d1241) commit. The DxVersion from the msbuild variable is now used. Thank you!

Unfortunately there is another problem now: When patching `Xpand.XAF.Modules.Reactive.dll`, VersionConverter/Mono.Cecil throws an error, because it cannot find `c:\Users\andre\source\repos\XafLibs\Build\Debug\net461\DevExpress.ExpressApp.v..dll`

`c:\Users\andre\source\repos\XafLibs\Build\Debug\` is the OutputPath of my solution and in this stage of the build process it is empty.

I have no clue what's wrong.
[buildlog.txt](https://github.com/eXpandFramework/eXpand/files/3314503/buildlog.txt)

**Comment by apobekiaris** [comment]
i should probably move the patching of the output folder after the build is done. The reason that the pacthicg of the packages folder needs to be before build is done is because compiler will throw if versions not match. However after packages folder is patched you can have a build and you can patch the output folder for indirect dependencies.

In addition we may do a runtime patching before nothing is loaded, this will not be implemented in the next minor I post it for reference.

what do u think will this solve the problem?

**Comment by apobekiaris** [comment]
another reference:

>c:\Users\andre\source\repos\XafLibs\Build\Debug\net461\DevExpress.ExpressApp.v..dll

this also implies that cecil resolver can be improved to query in addition the DevExpressVersion folder, however in your case there is no DevExpressVersion folder, which might be wiser to replace the DevExpressVersion variable with a DevExpressBinFolder ??

**Comment by krombipils** [comment]
>  replace the DevExpressVersion variable with a DevExpressBinFolder
I'm not sure if I understand your suggestion: Should this DevExpressBinFolder variable point to the local nuget cache? Or to the DevExpress installation folder? I guess storing an absolute path in the solution/project does not make much sense, does it?

**Comment by apobekiaris** [comment]
>i should probably move the patching of the output folder after the build is done. The reason that the pacthicg of the packages folder needs to be before build is done is because compiler will throw if versions not match. However after packages folder is patched you can have a build and you can patch the output folder for indirect dependencies.

i think this is the change the needed my 2nd thought does not make much sense, after build Devexpress assemblies should be in targetpath

**Comment by apobekiaris** [comment]
Hi,

Forget my previous comments please, I missed that u posted a log and I was random guessing. There is no need to move the patching after build.

However looking at your log I see that patching was done with success to CloneMemberValue, CloneModelView, ModelViewInheritance and failed for the Reactive module with a really strange lookup of a version-less assembly in your target folder which is also totally strange.

I tried to use in an empty target folder like your case and patches fine.

`DevExpress.ExpressApp.v..dll`

So I want to see the Reactive assembly from your nuget, can u post it? Can you also try to clean your nuget packages folder and rebuild or even perhaps update to the latest packages? VersionConverter 1.0.29 is public now

**Comment by krombipils** [comment]
I cleaned up my nuget packages folder, updated to VersionConverter 1.0.29, but the build still fails.
I attached a very minimalistic solution which also causes the same problem. Could you please try to build this solution on your site?!
[XafLibs.zip](https://github.com/eXpandFramework/eXpand/files/3319633/XafLibs.zip)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [VersionConverter: Custom DevExpressVersion is of incorrect type #426](https://github.com/eXpandFramework/DevExpress.XAF/commit/e9602c7f4d9d2fbd54b9aeb83d6a20ec30940b28)
* [VersionConverter: DevExpress assemblies are not resolved if reference from Nuget and not in target path #426](https://github.com/eXpandFramework/DevExpress.XAF/commit/48fa05b27613ab3bce9769f83bd8fcef092201ed)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
VersionConverter is now working fine on my solutions.
Thank you!

**Comment by apobekiaris** [comment]
u welcome, your sample was the savior though.

**Comment by apobekiaris** [comment]
please update to latest official as my latest patch was incomplete.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
