### ISSUE TITLE
ViewEditMode references package from XpandLab nuget server

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#427]
stable package Xpand.XAF.Modules.ViewEditMode 1.2.32 requires unstable package Xpand.XAF.Modules.Reactive 1.2.32.1 from the lab.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Stable package dependencies shouldn't come from Xpand Nuget Server #427](https://github.com/eXpandFramework/DevExpress.XAF/commit/767a3e9e1bbc5adb2ca6cc6ab6de118f2db9509c)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
