### ISSUE TITLE
Excel Importer - dropped file folder field size

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#428]
Hello,

In the auto import, the dropped files folder is to short depending the location of the folder. 
I suggest to put it at 500. 

BR
ISA

**Comment by apobekiaris** [comment]
I do not understand give me an example and also happy to test your 1000 files over a sample app you will provide

**Comment by isatahiri** [comment]
You should have received onedrive link. In it : 
 - TEST DB
 - Project 
 - Model excel file for the mapping
 - Files to import. 

In the app, the excel import record is : 
![image](https://user-images.githubusercontent.com/41955268/59086370-d56a5900-8901-11e9-9c61-60fe43b2cd19.png)

**Comment by isatahiri** [comment]
![image](https://user-images.githubusercontent.com/41955268/59086602-8244d600-8902-11e9-9f3e-cdcd0d888066.png)

This string property should have a bigger size. I suggest 500. 

BR
ISA

**Comment by apobekiaris** [comment]
thnks I got them I will update you once I have results.

**Comment by isatahiri** [comment]
Hi,

I also saw that the clone module does not work with this object if the column mapping contains objects. 
If the object contains only primitv value, it is possible to clone. 

You can try on the project directly with the import "13D - Prämien_CH_Model.xlsx"

I have this error : 
`La référence d'objet n'est pas définie à une instance d'un objet.

   à Xpand.ExpressApp.ExcelImporter.BusinessObjects.ExcelColumnMapMemberTypeValue.OnChanged(String propertyName, Object oldValue, Object newValue)
   à DevExpress.Xpo.PersistentBase.SetPropertyValue(String propertyName, String& propertyValueHolder, String newValue)
   à Xpand.ExpressApp.ExcelImporter.BusinessObjects.ExcelColumnMapMemberTypeValue.set_Type(String value)
   à lambda_method(Closure , Object , Object )
   à DevExpress.Xpo.Metadata.ReflectionMemberInfo.DelegateFieldAccessor.SetValue(Object theObject, Object value)
   à DevExpress.Xpo.Metadata.ReflectionMemberInfo.SetValue(Object theObject, Object theValue)
   à DevExpress.Persistent.Base.Cloner.CopyMemberValue(XPMemberInfo memberInfo, IXPSimpleObject sourceObject, IXPSimpleObject targetObject)
   à DevExpress.Persistent.Base.Cloner.CloneMemberValue(IXPSimpleObject sourceObject, IXPSimpleObject targetObject, XPMemberInfo mi)
   à DevExpress.Persistent.Base.Cloner.DefaultCloneTo(IXPSimpleObject sourceObject, Type targetType)
   à DevExpress.Persistent.Base.Cloner.InternalCloneTo(IXPSimpleObject sourceObject, Type targetType)
   à DevExpress.Persistent.Base.Cloner.CloneReferenceMemberValue(IXPSimpleObject targetObject, XPMemberInfo memberInfo, IXPSimpleObject sourceObject, Type type, Boolean createNewObject)
   à DevExpress.Persistent.Base.Cloner.CopyCollection(XPMemberInfo memberInfo, IXPSimpleObject sourceObject, IXPSimpleObject targetObject, Boolean aggregated)
   à DevExpress.Persistent.Base.Cloner.CloneMemberValue(IXPSimpleObject sourceObject, IXPSimpleObject targetObject, XPMemberInfo mi)
   à DevExpress.Persistent.Base.Cloner.DefaultCloneTo(IXPSimpleObject sourceObject, Type targetType)
   à DevExpress.Persistent.Base.Cloner.InternalCloneTo(IXPSimpleObject sourceObject, Type targetType)
   à DevExpress.Persistent.Base.Cloner.CloneReferenceMemberValue(IXPSimpleObject targetObject, XPMemberInfo memberInfo, IXPSimpleObject sourceObject, Type type, Boolean createNewObject)
   à DevExpress.Persistent.Base.Cloner.CopyCollection(XPMemberInfo memberInfo, IXPSimpleObject sourceObject, IXPSimpleObject targetObject, Boolean aggregated)
   à DevExpress.Persistent.Base.Cloner.CloneMemberValue(IXPSimpleObject sourceObject, IXPSimpleObject targetObject, XPMemberInfo mi)
   à DevExpress.Persistent.Base.Cloner.DefaultCloneTo(IXPSimpleObject sourceObject, Type targetType)
   à DevExpress.Persistent.Base.Cloner.InternalCloneTo(IXPSimpleObject sourceObject, Type targetType)
   à DevExpress.Persistent.Base.Cloner.CloneTo(Object sourceObject, Type targetType)
   à DevExpress.ExpressApp.CloneObject.CloneObjectViewController.CloneObject(Object currentObject, Type targetType, IObjectSpace& targetObjectSpace, Object& clonedObj)
   à DevExpress.ExpressApp.CloneObject.CloneObjectViewController.CloneObject(SingleChoiceActionExecuteEventArgs args)
   à DevExpress.ExpressApp.CloneObject.CloneObjectViewController.CloneObjectAction_OnExecute(Object sender, SingleChoiceActionExecuteEventArgs args)
   à DevExpress.ExpressApp.Actions.SingleChoiceAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   à DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)`

**Comment by isatahiri** [comment]
Did you have the opportunity to test the auto import ? Any clue ?

**Comment by apobekiaris** [comment]
not really sorry I am preparing a large release on a new module and have to delay a few days. I will update u when I have results.

good news are that excelimporter is very close to to go standalone and version agnostic.

**Comment by isatahiri** [comment]
cool ! New module ? I'll wait.

**Comment by isatahiri** [comment]
Hi Tolis,

How is going with issues and enhancements around the ExcelImporter ? 
Did you have the opportunity to have a look ?

BR
ISA

**Comment by apobekiaris** [comment]
nope I will update u once I do I am still assigned the case

**Comment by expand** [comment]
eXpand.lab release [19.1.402.9](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.9) includes commit that relate to this task:

* [ExcelImporter: Cloning fails when localized #428](https://github.com/eXpandFramework/eXpand.lab/commit/3a5293ba0147256bbd98674ae26376d956f177a1)
* [ExcelImporter: AutoImportFrom fails with long paths #428](https://github.com/eXpandFramework/eXpand.lab/commit/716d70211aabf1ba5695aa0827acfc3de56df795)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
the problem here was that the AutoImport was sequential, so I added an ConcerrencyLimit in Model/Options.

However if you utilize parallelism you will end up with back pressure cause your DB is not optimized to handle the R/W queries and this will lead to huge disk I/O 100%. To solve it you  have to go through your db server logs find the expensive queries and index them or even create special faster objects only for use in the import. Most probably you need to do more optimization to RAM, Caching, Buffer, pages etc of your DB server.

While you optimizing your app and DB for handling such an import scenario as this one if you find ways we can improve it through code feel free to post.

Note that as I am not a MySql expert I had to install it in a RAM disk in order to be able to run it full power.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.10](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.10) includes commit that relate to this task:

* [ExcelImporter: Model Options ConcurrencyLimit #428](https://github.com/eXpandFramework/eXpand.lab/commit/8c81ace915644448f9ba999b0fc00fb56cd177ee)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
additional note from what I saw the Disk I/O issue starts when objectspace is committing so has nothing to do with any query done before. I also experiment in chunk commits without much improvement.   I guess you can simulate the problem with the module by creating 10000 objects and committing them.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.15) includes commit that relate to this task:

* [ExcelImporter: Cloning fails when localized #428](https://github.com/eXpandFramework/eXpand.lab/commit/53ced28e87a515753dfdf85cad0be77c49a8fa0d)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
