### ISSUE TITLE
ExcelImporter: Add Support for files to exclude -AutoImport

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#429]
Also i discovered that the module trys also to import the tmp file which is create when we open an excel file in the dropped folder.

_Originally posted by @isatahiri in https://github.com/eXpandFramework/eXpand/issues/412#issuecomment-499768579_

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
