### ISSUE TITLE
Upgrade all scripts to powershell core

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#430]
**Is your feature request related to a problem? Please describe.**
MS support for powershell 5 is poor moreover there is a huge improvment in performance and features.

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/XpandPwsh/issues/5

**Comment by expand** [comment]
eXpand.lab release [19.1.303.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.4) includes commit that relate to this task:

* [Upgrade scripts to powershell core #430](https://github.com/eXpandFramework/eXpand.lab/commit/451120d15df5f55c6fd8f48bec1f33787d19e6c9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
