### ISSUE TITLE
NullReference in HideToolBar

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#433]
**Describe the bug**
While Calling SetView from action for switching editor, I got the following exception

**System.InvalidOperationException: Exception occurs while assigning the 'null' view to NestedFrame:**
Referencia a objeto no establecida como instancia de un objeto. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
en Xpand.XAF.Modules.HideToolBar.HideToolBarService.<>c.b__0_2(NestedFrame frame)
en System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
en System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
en System.Reactive.Stubs.<>c.b__2_1(Exception ex)
en System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
en System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Subjects.Subject`1.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Sink`2.OnError(Exception error)
en System.Reactive.Sink`1.ForwardOnError(Exception error)
en System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.HalfSerializer.ForwardOnNext[T](ISink`1 sink, T item, Int32& wip, Exception& error)
en System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.b__1(Object sender, TEventArgs eventArgs)
en System.EventHandler.Invoke(Object sender, EventArgs e)
en DevExpress.ExpressApp.Frame.OnTemplateViewChanged()
en DevExpress.ExpressApp.Frame.SetTemplateView(View view)
en DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
--- Fin del seguimiento de la pila de la excepción interna ---
en DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
en ClasesBase.SwitchViewController.SimpleAction1_Execute(Object sender, SimpleActionExecuteEventArgs e)
en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
19.1.0607.3
Boolean SetView(DevExpress.ExpressApp.View, Boolean, DevExpress.ExpressApp.Frame, Boolean)
en DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
en ClasesBase.SwitchViewController.SimpleAction1_Execute(Object sender, SimpleActionExecuteEventArgs e)
en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
>While Calling SetView from action for switching editor, I got the following exception

can you post the code that is executed?

**Comment by vimarx** [comment]
`Dim savedView = View
        If View IsNot Nothing AndAlso Frame.SetView(Nothing, True, Nothing, False) Then
            ' Make required changes to the related Application Model nodes here.
            Dim defaultMasterDetailMode As MasterDetailMode = MasterDetailMode.ListViewOnly
            If (CType(savedView.Model, IModelListView)).MasterDetailMode = MasterDetailMode.ListViewAndDetailView Then
                CType(savedView.Model, IModelListView).MasterDetailMode = DevExpress.ExpressApp.MasterDetailMode.ListViewOnly
            Else
                CType(savedView.Model, IModelListView).MasterDetailMode = DevExpress.ExpressApp.MasterDetailMode.ListViewAndDetailView
            End If

            ' Update the saved View according to the latest model changes and assign it to the current Frame.
            savedView.LoadModel(False)
            Frame.SetView(savedView)
            'Optionally update the current object of the inner DetailView.
            'If savedView.EditView IsNot Nothing Then
            '    savedView.EditView.CurrentObject = savedView.CurrentObject
            'End If
        End If`

**Comment by apobekiaris** [comment]
are you using the `HideToolBar` module? can you disabled it as per docs if you are not using it until I fix it?

**Comment by apobekiaris** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [HideToolBar: execute only when nested frame is a ListView #433](https://github.com/eXpandFramework/DevExpress.XAF/commit/0a45d7b1e19c3fcf4f3ede6cf9d3798c0580b36e)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
