### ISSUE TITLE
Release ModelMapper StandAlone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#434]
eXpandFramework modules use the ModelAdaptor functionality to map/synchronize controls to the model.

The implementation is complex and based on controllers that are spawn across many modules, so it is very hard for users to utilize them in their own modules.

The new package should provide a very simple API for mapping/synchronizing any object to the model. Furthermore the new package should be platform agnostic and should generate only one assembly minimizing deployment cost.

As with other standalone modules once released should replace all related classes from  eXpandFramework main modules with minimum breaking change.

At the moment there is a ModelAdaptor context which is shared through all control maps. These does not make much sense and it should be moved as a child to each map.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Release ModelMapper StandAlone package #434](https://github.com/eXpandFramework/DevExpress.XAF/commit/ad1cfa53935774def71087f42cc3a0d9c3b92817)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through an module of the main eXpandFramework module, you may wait for the bot to notify you again.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
the ModelMapper is now integrated and documented at lab
https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/src/Modules/ModelMapper
https://github.com/eXpandFramework/eXpand.lab/releases/tag/19.1.402.4

**Comment by apobekiaris** [comment]
Currently the ModelMapper does not support the Visual Studio Model Editor. However you can use the `XpandModelEditor` found in the `Xpand.VSIX` package. Note that the XpandModelEditor is embedded and version agnostic so its one time only installation.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: documentation #434](https://github.com/eXpandFramework/DevExpress.XAF/commit/91b00252fbd222a8e1234561a61096d4236a7515)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.5) includes commit that relate to this task:

* [Integrate ModelMapper #434](https://github.com/eXpandFramework/eXpand.lab/commit/a6ec6f81ced9699ade32eb89d5f7acfe4a6b6820)
* [Integrate modelmapper #434](https://github.com/eXpandFramework/eXpand.lab/commit/5b84ba40b746d992c3da521cdf9379e0d7b270ff)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
