### ISSUE TITLE
Disable detailview in web

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#438]
Hi,

As a the module "HideToolBar", we should have a flag in model allowing user to chose if he wants to allow the detail view to be open in a listview. 

In web version, if we are in inline edit mode and click on the record, the detail view is open. this is very annoying. Maybe we can improve something here. 
Please let me know if it's not clear.

BR
ISA

**Comment by apobekiaris** [comment]
are you looking for something like this?

```xml
<ListView Id="Some_ListView">
  <HiddenActions>
    <ActionLink ActionId="ListViewShowObject" IsNewNode="True" />
  </HiddenActions>
</ListView>

```

**Comment by isatahiri** [comment]
Yep. This will cover the onclick action in asp too ?

**Comment by apobekiaris** [comment]
yeap is an agnostic configuration, excelimporter already uses it

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by isatahiri** [comment]
Hi,

Is this implemented somewhere ? I cannot find any option in the model for that. 

BR
ISA

**Comment by apobekiaris** [comment]
option for what I cannot follow

**Comment by isatahiri** [comment]
Sorry Tolis I did not see your answer. 
The initial demand was to implement the example E622 of devexpress in the framework : https://github.com/DevExpress-Examples/XAF_how-to-prevent-a-detailview-from-being-shown-for-a-listview-record-e622

But we can also use devexpress sample. I guess you have a lot to do already :-)

**Comment by isatahiri** [comment]
Hello ! 

I would be useful to have the option in the model to decide if we allow opening detailview or not.
We could have something like : "Open Detail View" : true/false

**Comment by apobekiaris** [comment]
please describe your need in details XAF already has many opens for handling actions, e.g. with HiddenActions model node, with conditionalappeareance, with permissions, in addition to the ModelArtifactState module from eXPandFramework

**Comment by CWolffIF** [comment]
I have an agnostic controller to allow to open an DetailView from a ListView

```
   public class ShowDetailViewFromListViewController : ViewController<ListView>, IModelExtender
    {
        public const string EnabledKeyShowDetailView = "ShowDetailViewFromListViewController";
        protected override void OnActivated()
        {
            base.OnActivated();
            ListViewProcessCurrentObjectController targetController = Frame.GetController<ListViewProcessCurrentObjectController>();
            targetController.ProcessCurrentObjectAction.Enabled[EnabledKeyShowDetailView] = ((IModelShowDetailView)View.Model).ShowDetailView;
        }
        public void ExtendModelInterfaces(DevExpress.ExpressApp.Model.ModelInterfaceExtenders extenders)
        {
            extenders.Add<IModelViews, IModelDefaultShowDetailView>();
            extenders.Add<IModelListView, IModelShowDetailView>();
        }
    }
    public interface IModelDefaultShowDetailView : IModelNode
    {
        [Category("iXIS Framework")]
        [DefaultValue(true)]
        bool DefaultShowDetailViewFromListView { get; set; }
    }
    public interface IModelShowDetailView : IModelNode
    {
        [Category("iXIS Framework")]
        [DefaultValue(true)]
        bool ShowDetailView { get; set; }
    }
    [DomainLogic(typeof(IModelShowDetailView))]
    public static class ModelShowDetailViewLogic
    {
        public static bool Get_ShowDetailView(IModelShowDetailView showDetailView)
        {
            IModelDefaultShowDetailView defaultShowDetailViewFromListView = showDetailView.Parent as IModelDefaultShowDetailView;
            if (defaultShowDetailViewFromListView != null)
            {
                return defaultShowDetailViewFromListView.DefaultShowDetailViewFromListView;
            }
            return true;
        }
    }  
```

**Comment by isatahiri** [comment]
@CWolffIF Thanks I'll use this.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
