### ISSUE TITLE
EnumEditor is not filtering in listview

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#439]
Xpand EnumEditor is not using DataSourceProperty attribute in Listview
![2019-06-12_11-19-50](https://user-images.githubusercontent.com/226800/59359535-e30a4f00-8d04-11e9-85b5-3a0529c25056.gif)

attached sample project
[Varios.zip](https://github.com/eXpandFramework/eXpand/files/3281766/Varios.zip)

**Comment by vimarx** [comment]
#404 #416

**Comment by vimarx** [comment]
@apobekiaris  any news on this issue?

Thanks

Gustavo

**Comment by expand** [comment]
eXpand.lab release [19.1.402.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.6) includes commit that relate to this task:

* [EnumPropertyEditor: DataSourceAttribute support for ListView #439](https://github.com/eXpandFramework/eXpand.lab/commit/a110324df5c4d6cc213f14633e5463c8c73f87ff)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
now in 19.1.501.0
![image](https://user-images.githubusercontent.com/226800/62432124-6b551100-b704-11e9-95e5-e81b387fef07.png)


System.InvalidCastException
  HResult=0x80004002
  Message=No se puede convertir un objeto de tipo 'DevExpress.ExpressApp.Win.Editors.RepositoryItemEnumEdit' al tipo 'DevExpress.XtraEditors.Repository.RepositoryItemCheckedComboBoxEdit'.
  Source=Xpand.ExpressApp.Win
  StackTrace:
   at Xpand.ExpressApp.Win.PropertyEditors.EnumPropertyEditor.GetItemsData(RepositoryItem repositoryItem, IMemberInfo memberInfo) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\EnumPropertyEditor.cs:line 76

**Comment by vimarx** [comment]
in a listview

**Comment by apobekiaris** [comment]
how to repro it?

**Comment by vimarx** [comment]
I will try to isolate it

Another problem with another listview, 

DisplayName ="" ???
![2019-08-04_22-17-42](https://user-images.githubusercontent.com/226800/62432404-e4a13380-b705-11e9-9ba0-d6a92617c29b.gif)

System.NullReferenceException
  HResult=0x80004003
  Message=Referencia a objeto no establecida como instancia de un objeto.
  Source=Xpand.ExpressApp.Win
  StackTrace:
   at Xpand.ExpressApp.Win.SystemModule.EnumRepositoryItemGridListEditorController.FilterRepositories(GridListEditor gridListEditor) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\EnumRepositoryItemListViewController.cs:line 26

**Comment by vimarx** [comment]
Another problem  using solution provided in first comment.
It is about the handling of invalid values when changing datasource conditions

![2019-08-04_22-25-32](https://user-images.githubusercontent.com/226800/62432568-d273c500-b706-11e9-99e3-2c91f98d0f98.gif)

**Comment by vimarx** [comment]
Another one when using the enum with the flags attribute (Change value)

![2019-08-04_22-41-01](https://user-images.githubusercontent.com/226800/62433003-ffc17280-b708-11e9-84b4-55cd3aeddc67.gif)

**Comment by expand** [comment]
eXpand.lab release [19.1.501.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.3) includes commit that relate to this task:

* [Update EnumRepositoryItemGridListEditorController #439](https://github.com/eXpandFramework/eXpand.lab/commit/a9fd90a70f1d1a4f98b037c3446fe4d1aebbf1e1)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
next minor I fixed the flags part according to your sample however u should create a valid flag declaration for testing it
```vb
<Flags()>
    Public Enum StatusColor
        None=0
        Red=1
        Green=2
        White=4
        Blue=8
    End Enum
```

**Comment by expand** [comment]
eXpand.lab release [19.1.501.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.4) includes commit that relate to this task:

* [EnumPropertyEditor: Fix problems when flags #439](https://github.com/eXpandFramework/eXpand.lab/commit/962ce61da7ffcfa5b7b5e92df8538e892ac4bc90)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
if the enum has an image they don't appear

**Comment by vimarx** [comment]
even if I change the enuproperty editor to DX, it  don't show images...


Original -non Xpand Solution

![image](https://user-images.githubusercontent.com/226800/63432281-4a283c00-c3f7-11e9-9343-0bb0ec06b7c6.png)

Xpand Sample
![image](https://user-images.githubusercontent.com/226800/63432441-89ef2380-c3f7-11e9-814a-91e0d82e0427.png)

**Comment by vimarx** [comment]
I think this may be a different issue , so I move to #521

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
