### ISSUE TITLE
Xpand.Utils en Xpand.Xpo as NuGet package targeting .NET 4.5.2 and .NET Standard 2.0

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#440]
As we also have non-XAF applications that use XPO we like to add only Xpand.Xpo and Xpand.Utils to our projects. Currently, the Xpand.Xpo and Xpand.Utils projects are added in the eXpandLib package which contains XAF packages.

Since the current XAF projects target .NET Framework and not .NET Standard like DevExpress.Xpo is, we can't use the Xpand.Xpo and the Xpand.Utils in non-XAF applications such as (ASP).NET Core projects.

We would like a solution where the Xpand.Xpo and the Xpand.Utils project (Xpand.Xpo references Xpand.Utils) are targeted at .NET Standard 2.0 and .NET 4.5.2 like DevExpress.Xpo and are available as a NuGet package. This way the projects are more future-proof and can these projects can still be referenced to current projects using those Xpand projects.

The problem that might be there when targeting .NET Standard 2.0 is the .NET Framework specific code such as System.Management, but we can work around and discuss about solutions for this.

What do you think about this?

**Comment by apobekiaris** [comment]
yes I agree its time to start releasing portable packages however I rather focus on doing it as part of the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF). 

There are already plans to release the https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/src/Extensions as source only packages e.g https://nikcodes.com/2013/10/23/packaging-source-code-with-nuget/ where each package will contain only one feature like this https://github.com/eXpandFramework/DevExpress.XAF/blob/lab/src/Extensions/Extensions/XAF/Object/GetTypeInfo.cs. If the feature has dependencies that are not portable then the package cannot be published as a .NET standard lib.

In time Xpo and utils will be puzzled from those Nuget source only packages.

So perhaps is better to hear what features of xpo and utils you find useful, so to prioritize works and thoughts

>Since the current XAF projects target .NET Framework and not .NET Standard like DevExpress.Xpo is, we can't use the Xpand.Xpo and the Xpand.Utils in non-XAF applications such as (ASP).NET Core projects.

note that this is planned to changed soon, spa is an asp.net core isn't?

**Comment by gerritmulder** [comment]
Tolis,

I understand that you only want to continue with the DevExpress.XAF project, a progressive move. 
I will look in our codebase which Xpand code we currently are using. It might take some time, because we are currently rewriting our code. Former coworkers copied the Xpand code and started to change Xpand into our company name and start editing the code, which made it a horrible mess to maintain and to read. We currently are seperating the Xpand and our code and will be able to see the differences. Then I am able to tell which functions we are currently using in our projects and might add functionalities from our code later on.

We don't use SPA yet, because it is very unstable and hasn't all the features yet. SPA is based on .NET Framework but references the ASP.NET Core libraries.

**Comment by apobekiaris** [comment]
>I understand that you only want to continue with the DevExpress.XAF project, a progressive move.

actually I plan to use them both, but the standalone packages will be documented and tested.

>We don't use SPA yet, because it is very unstable and hasn't all the features yet. SPA is based on .NET Framework but references the ASP.NET Core libraries.

true but I did soon didn't I? DX is working hard on that already

**Comment by apobekiaris** [comment]
>actually I plan to use them both, but the standalone packages will be documented and tested.

reasoning for this is, the main project will clearlt demonstrate how to create puzzles from the standlone for newcomers and for those that are lazy to create one from themselves.

**Comment by gerritmulder** [comment]
I got the answer now and I will look forward to test the source only packages and see how it will do in production. I will close the issue now.

**Comment by apobekiaris** [comment]
just for reference the source only packages althought not published are already used from the standalone packages as linked files

**Comment by apobekiaris** [comment]
now I remember why I fail migrating fasterflect the first time.

https://github.com/HelloKitty/fasterflect/issues/5

**Comment by gerritmulder** [comment]
I have noticed that and thought to create an issue on that repo, but I don't have to since you did.

**Comment by apobekiaris** [comment]
if they reject we can always publish our own signed version

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
