### ISSUE TITLE
Upgrade projects to packagereference format

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#441]
**Is your feature request related to a problem? Please describe.**
this is the future as dotnet core supports only this format

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Upgrade projects to packagereference format #441](https://github.com/eXpandFramework/DevExpress.XAF/commit/ce84a00f7a3c04cf6f1142e1369ac48abba92f9f)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
