### ISSUE TITLE
Migrate projects to SDK format

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#443]
**Is your feature request related to a problem? Please describe.**
https://www.michaeltaylorp3.net/migrating-to-sdk-project-format/

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Migrate projects to SDK format #443](https://github.com/eXpandFramework/DevExpress.XAF/commit/2bb6ec2d67a14efabbe9649d2e48c8c1329b430a)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.303.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.4) includes commit that relate to this task:

* [Migrate projects to SDK format #443](https://github.com/eXpandFramework/eXpand.lab/commit/2c061c48d9d76d77875166f90e184658acdbc6e8)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.303.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.5) includes commit that relate to this task:

* [Nuget generation update for SDK format #443](https://github.com/eXpandFramework/eXpand.lab/commit/5f213577fb6929ae2a14c20cb0d9dc9aba6e4ce2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.303.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.6) includes commit that relate to this task:

* [Nuget generation update for SDK format #443](https://github.com/eXpandFramework/eXpand.lab/commit/6f6eb49dfbebecdb5872f3192e5741d3e915d25a)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.303.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.303.7) includes commit that relate to this task:

* [Nuget generation update for SDK format #443](https://github.com/eXpandFramework/eXpand.lab/commit/c2ccbc1acac645718d6b2cfc57cd38ddd07f93ef)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
