### ISSUE TITLE
Expanding FrameExtensions functionality for Controller interfaces

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#444]
**Is your feature request related to a problem? Please describe.**
We have several stand-alone modules and one main module, similar to Xpand. We don't want the stand-alone modules to reference each other and only want them to reference the main module. Now we've got a controller in a stand-alone module that activates a custom event in another stand-alone module. Now we can not use the FrameExtensions.GetController method since they the first module can't reference the other.

**Describe the solution you'd like**
My solution was to make it possible to get those controllers implement an interface in the main project. The interface then contains an eventhandler property that is available to subscribe to. The FrameExtensions.GetController method then checks if the type is an interface and find all the controllers the interface is implemented to. The action will then be called for every controller.

What do you think about this?

**Additional context**
An example implementation.
```
// usage in controller:
Frame.GetController<ICustomFunctionController>(controller => controller.CustomEvent += (sender, args) => { })
```

**Comment by gerritmulder** [comment]
Our current implementation of this is:
```
public static void GetController<T>(this Frame frame, Action<Controller> action)
{
    if (typeof(T).IsInterface)
    {
        foreach (var controller in frame.Controllers)
            if (controller.GetType().IsAssignableFrom(typeof(T)))
                action(controller);
    }
    else
        Xpand.Persistent.Base.General.FrameExtensions.GetController(frame, typeof(T), action);
}
```

**Comment by gerritmulder** [comment]
Our current implementation is as following:
```
public static void GetController<T>(this Frame frame, Action<Controller> action)
{
    if (typeof(T).IsInterface)
    {
        foreach (var controller in frame.Controllers)
            if (controller.GetType().IsAssignableFrom(typeof(T)))
                action(controller);
     }
    else
        Xpand.Persistent.Base.General.FrameExtensions.GetController(frame, typeof(T), action);
}

// usage
Frame.GetController<ICustomFunctionController>(controller =>
{
    (controller as ICustomFunctionController).CustomEvent += (sender, args) => { };
});
```
It is not ideal to cast the controller to the interface, but it works. Maybe there would be a better solution. for this

**Comment by apobekiaris** [comment]
first nothing wronf with your code totally valid

>Xpand.Persistent.Base.General.FrameExtensions.GetController(frame, typeof(T), action);

the goal of the above method was to provide a one line solution which are easier to read as they do not occupy much space as an if statement for the case that the controller does not exist in the frame due to optimizations.

However you deal with interfaces so it should be possible to have more than one controller implementing the same interface. Therefore we deal with collections and LINQ is your friend.

try this one liner.

```cs
  Frame.GetControllers<ITestController>().ForEach(controller => controller.Hi());
```

```cs
 public class Class1:ViewController,ITestController
    {
        public void Hi(){
            
        }
    }

    public interface ITestController{
        void Hi();
    }

    public class MyClass2:ViewController{
        protected override void OnFrameAssigned(){
            base.OnFrameAssigned();
            Frame.GetControllers<ITestController>().ForEach(controller => controller.Hi());
        }
    }

    static class MEx{
        public static IEnumerable<T> GetControllers<T>(this Frame frame){
            return frame.GetControllers(typeof(T)).OfType<T>();
        }
    }
```

**Comment by gerritmulder** [comment]
That code does the job and looks like a proper solution. Thanks!

Will the extension method be implemented in some way in Xpand? This is just to know so that in planned releases we can remove our extension method and use Xpand.

**Comment by apobekiaris** [comment]
i labeled for the base, the bot will notify u once integrated
