### ISSUE TITLE
Updateing Model - Latest Version 19.1 Failed

### ISSUE THREAD

**Issue by david0villa** [eXpandFramework/eXpand#445]
**Describe the bug**
Error:
Exception occurs while the 'Xpand.ExpressApp.Security.Win.XpandSecurityWinModule' customizes TypesInfo: An error with number 1123 has occurred.
Error message: Custom persistent properties (defined in the Application Model or TypesInfo system directly) are not supported for the 'XpandPermissionPolicyRole' type.
Update failed

**To Reproduce**
1. Open Visual Studio
2. Right click on <project name>.Module.Win then click Update Module
3. Then Error coming up at Output

**Expected behavior**
Updating model successfully

**Screenshots**

**Desktop (please complete the following information):**
- Window 10 build

**Comment by apobekiaris** [comment]
can you post a sample app? whee I can repro the case?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
