### ISSUE TITLE
Error in VersionConvertor 1.0.27

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#448]
Hi Tolis

I updated some of the eXpand NuGet packages. The VersionConvertor was updated to version 1.0.27. I am getting the following error when building:

Cannot find DevExpress Version

This was working in version 1.0.26 of the VersionConvertor. What can I do to solve this or what info do you need from me to solve this bug?

Thanks,
Jacob

**Comment by apobekiaris** [comment]
try to update the versionconverter from lab current version is 1.0.28 and there are related works to this case. Let me know if u still have issues

**Comment by apobekiaris** [comment]
my bad sorry the latest is 1.0.29 but i just send it for build on the lab, u will get notified by the bot soon. If u do not want to wait u can always replace the VersionConverter.ps1, functions.ps1 from lab repo manully https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/tools/Xpand.VersionConverter

**Comment by jacobdeboer33** [comment]
Hi Tolis. Build succeeds with version 1.0.28. 

Thanks,
Jacob

**Comment by apobekiaris** [comment]
nice cause 1.0.29 can build at the moment it fails due to pending works

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [VersionConverter: version not updated to 1.0.29 #448 #436](https://github.com/eXpandFramework/DevExpress.XAF/commit/702f846430d795f4d3be49d6655e769804e54304)
* [VersionConverter: version not update to 1.0.29 #448](https://github.com/eXpandFramework/DevExpress.XAF/commit/69daa79968235ab977bc8f476ff7f2da7af638ce)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
