### ISSUE TITLE
ViewEditMode does not allow EditAction execution

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#450]
**Describe the bug**
If ViewEditMode=View in web and execute the Edit action nothing happens

**Expected behavior**
It should edit the view

**Comment by apobekiaris** [comment]
@larspl after this is fixed u can remove the workaround I provided, subscribe to this ticket to get notified

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ViewEditMode: UnLock_ViewEditoMode_When_SwitchToEditMode_Action_Executed #450](https://github.com/eXpandFramework/DevExpress.XAF/commit/08b8cb36dfa77c79e7fb2d7b2e5e053b54201fe9)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
