### ISSUE TITLE
Xpand.VersionConverter exception

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#451]
Hello, setup new version 19.1.402.0

...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverte
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error : r.ps1 : Cannot process argument transformation on parameter 'DevExpressVersion'. Can
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error : not convert value "" to type "System.Version". Error: "Version string portion was to
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error : o short or too long."
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error : At line:1 char:256
22>...\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error : + ... ...\bin\Debug\' '' ''}
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error : +                                                                    ~~
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : InvalidData: (:) [Xpand.VersionConverter.ps1], Parame 
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error :    terBindingArgumentTransformationException
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : ParameterArgumentTransformationError,Xpand.VersionCon 
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error :    verter.ps1
22>...\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error :  
22>C:\CrmExpert.XCRM\packages\Xpand.VersionConverter.1.0.30\build\Xpand.VersionConverter.targets(4,9): error MSB3073: выход из команды "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'...\packages\Xpand.VersionConverter.1.0.30\build\\Xpand.VersionConverter.ps1' '....csproj' '...\bin\Debug\' '' ''} " " с кодом -1.

**Comment by apobekiaris** [comment]
is this resolved?

**Comment by apobekiaris** [comment]
latest public version used in 19.1.402 is 1.0.32 and i see in your stack 1.0.30. How did this happen?

**Comment by genetsEvgen** [comment]
Yes, this is resolved
