### ISSUE TITLE
19.1.402 depends on System.Data.DataSetExtensions v4.0.0 that is not a NuGet package

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#453]
eXpandSystem 19.1.402 depends on System.Data.DataSetExtensions 4.0.0 which is a .NET framework assembly and not a NuGet package. When installing eXpandSystem 19.1.402 it will resolve System.Data.DataSetExtensions 4.5.0, which is a NuGet package, with a wrong version warning.

**Comment by gerritmulder** [comment]
eXpandLib seems to have this too.

**Comment by apobekiaris** [comment]
it looks like this dependency come from the migration tool, I remove it and compiles fine.

Not so sure how u get a warning though, I mean that eXpand builds use `WarnAsError` flag and apparently we have a build

**Comment by gerritmulder** [comment]
In the old .csproj formatted projects you are able to change the version of references to a project, but because we are using the new .csproj formatted projects, we can't remove a dependency from a NuGet package. I also tried installing System.Data.DataSetExtensions 4.0.0 before and after the NuGet package, but this doesn't seem to work too.

I provided a screenshot with the dependency treelist of both .csproj formats.
![Screenshot](https://user-images.githubusercontent.com/45372188/60215634-5913c780-9868-11e9-8a5e-a620c73facb4.png)

This is the solution with both projects, the System.Data.DataSetExtensions version is already 4.0.0.0, because this was added by default when creating the project and does not get overwritten by NuGet.
[Issue453.zip](https://github.com/eXpandFramework/eXpand/files/3331980/Issue453.zip)

**Comment by gerritmulder** [comment]
I want to add that version v4.0.0 from System.Data.DataSetExtensions is the latest version that comes from the .NET Framework assemblies and version v4.5.0 is availabe on NuGet, but not in the .NET Framework assemblies

**Comment by apobekiaris** [comment]
from your comments I cannot tell if removing the dependecy will resolve the issue, however I will push now a build to the lab and you let me know if its ok

**Comment by gerritmulder** [comment]
Removing v4.0.0 or adding v4.5.0 from System.Data.DataSetExtensions will resolve the build warning.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.1) includes commit that relate to this task:

* [Remove unused dependencies #453](https://github.com/eXpandFramework/eXpand.lab/commit/faafd7826fdbeb184d0653d6d50bf2c1816a05f3)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by gerritmulder** [comment]
Have tested the lab version 19.1.402.1 with following .csproj. Everything builds without warnings. Will close this issue now.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="eXpandLib" Version="19.1.402.1" />
  </ItemGroup>

</Project>
```

**Comment by expand** [comment]
eXpand.lab release [19.1.402.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.3) includes commit that relate to this task:

* [Remove unused dependencies #453](https://github.com/eXpandFramework/eXpand.lab/commit/9dbc0ad5356ffe0b0b46486a9dfa80cd813a08ad)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
I think this is not yet fixed completely, e.g. there is still a reference to DataSetExtensions 4.* in Xpand.ExpressApp.IO.csproj

**Comment by expand** [comment]
eXpand.lab release [19.1.501.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.4) includes commit that relate to this task:

* [IO: Remove unused dependency #453](https://github.com/eXpandFramework/eXpand.lab/commit/c86d03340e0910135b9510433b2c4d51fc002e92)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
19.1.501.4 is working fine. Thank you
