### ISSUE TITLE
19.1.402 VSIX Error after Installation

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#454]
Hi,

after Installation 19.1.402 the Xpand.VSIX is not correct. The Menu is there (see Screenshot) but no Menuitem works with the displayed Errormessage.
Maybe you can see something i the LogFile.
![Error](https://user-images.githubusercontent.com/43132306/60157933-25955680-97f0-11e9-88b5-35403a9ae7a8.png)

[ActivityLog.zip](https://github.com/eXpandFramework/eXpand/files/3328672/ActivityLog.zip)

**Comment by apobekiaris** [comment]
[Xpand.VSIX.zip](https://github.com/eXpandFramework/eXpand/files/3330366/Xpand.VSIX.zip)
try this one and let me know if it works for vs2017 please

**Comment by expand** [comment]
eXpand.lab release [19.1.402.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.1) includes commit that relate to this task:

* [VSIX dependecies missing for VS2017 #454](https://github.com/eXpandFramework/eXpand.lab/commit/e317c6616373c8c49ebe6acf629cdcdff7a5000b)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Hi,

The installation does not work in my side.

Downloading Sources from https://github.com/eXpandFramework/eXpand.lab/releases/download/19.1.402.1/Xpand-Source-19.1.402.1.zip into C:\Users\isata\Documents\eXpandFramework
iex : Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »
Au caractère Ligne:1 : 50
+ ... cess -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('ht ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

BR
ISA

**Comment by isatahiri** [comment]
according the the links in lab realeases  it must be 
: https://github.com/eXpandFramework/eXpand.lab/archive/19.1.402.1.zip

Am I right ?

**Comment by CWolffIF** [comment]
> 
> 
> [Xpand.VSIX.zip](https://github.com/eXpandFramework/eXpand/files/3330366/Xpand.VSIX.zip)
> try this one and let me know if it works for vs2017 please

Thanx.
It works for 2017.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.3) includes commit that relate to this task:

* [VSIX dependecies missing for VS2017 #454](https://github.com/eXpandFramework/eXpand.lab/commit/9f642a9386cd54a7728a57628f523055e2459522)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
