### ISSUE TITLE
VersionConverter can't detect XAF version from NuGet packages with new sdk-style format

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#455]
As the title says it is now not possible to use this module in a XAF 19.1 project. Can this module be updated to v19.1?

When using the IModelDetailViewViewEditMode.ViewEditMode it gives me the error: 
`The type 'ViewEditMode' is defined in an assembly that is not referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v18.2, Version=18.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'.
`

**Comment by gerritmulder** [comment]
In some projects we are using the NuGet packages from DevExpress. The versionconverter is unable to detect this and the PowerShell script fails.

**Comment by gerritmulder** [comment]
I have created a Directory.Build.props file in the solution folder looking like:
```
<Project>
  <PropertyGroup>
    <DevExpressVersion>19.1.3</DevExpressVersion>
  </PropertyGroup>
</Project>
```
Seems to work now.

**Comment by apobekiaris** [comment]
VersionCeonverter should work when devexpress is as nuget see https://github.com/eXpandFramework/eXpand/issues/426#issuecomment-505236376

if u still have problems and u wish to avoid the Directory.Build.props happy to research over detailed repro instructions

**Comment by gerritmulder** [comment]
Our projects are manually converted to the new type .csproj as this person did too: https://github.com/eXpandFramework/eXpand/issues/426#issuecomment-498601981. It would be better if we did not have the manually change the DevExpress version for the converter, but it's not a big deal.

To solve this, the script should read the .csproj and get the version. Getting from the local packages folder would cause problems because 2 solutions with different DevExpress version would give problems.

**Comment by apobekiaris** [comment]
>To solve this, the script should read the .csproj and get the version

i cannot follow this suggestion the script already reads the `DevExpressVersion` msbuild variable however since this is a a custom variable u have to manually update it.

**Comment by gerritmulder** [comment]
If im right and understand you, I think I explained it the wrong way, apologies.

I meant that the script should read the packages from the ItemGroup.PackageReference that start with DevExpress.ExpressApp or DevExpress.Persistent and get their version. If there are multiple versions, it should throw an exception.

**Comment by apobekiaris** [comment]
from what i see this is what it does
https://github.com/eXpandFramework/DevExpress.XAF/blob/f5e3a8e7f73b65f69b4600b8eba7ef2d8a42d09c/tools/Xpand.VersionConverter/Functions.ps1#L187-L193

how does this fails? can u provide a sample project that fails?

**Comment by gerritmulder** [comment]
The zip contains a .csproj which you can try to build. It requires the [DevExpress NuGet server](https://nuget.devexpress.com) to be added.

.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp" Version="19.1.4" />
    <PackageReference Include="Xpand.XAF.Modules.ViewEditMode" Version="1.2.37" />
  </ItemGroup>

</Project>
```

[Issue455Sample.zip](https://github.com/eXpandFramework/eXpand/files/3330478/Issue455Sample.zip)

**Comment by apobekiaris** [comment]
super powerfull sample! many thnks

here the fix until next minor

[Functions.zip](https://github.com/eXpandFramework/eXpand/files/3330672/Functions.zip)

**Comment by gerritmulder** [comment]
Thanks! I'll close the issue.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [VersionConverter: can't detect XAF version from NuGet packages with new sdk-style format #455](https://github.com/eXpandFramework/DevExpress.XAF/commit/477501ab4444d6dd7d07001fbf0f1409415244bc)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
