### ISSUE TITLE
 [System.Net.WebClient] does not contain a method with the name "new"

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#456]
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).Download
String('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  #-Version '
19.1.402.0' -SkipGac -InstallationPath 'C:\Xpand'"

An error occurred while calling the method, because [System.Net.WebClient] does not contain a method with the name "new".

Windows 7

**Comment by apobekiaris** [comment]
whats your powershell version?

**Comment by genetsEvgen** [comment]
2.0

**Comment by apobekiaris** [comment]
to be safe i guess u need to upgrade to 5

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
