### ISSUE TITLE
Excel Importer - Error handling very slow

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#459]
Hi,

I have the version 19.1.402.2
When i Import 6022 of data, the import process takes 2 minutes. But if there is error which affects all the rows, then it takes a very long time to generate the errors. (About 20 minutes)

Can we improve this ? 

BR
ISA

**Comment by apobekiaris** [comment]
we can add a percentage abort threshold and will take a better look why is so slow on generating errors

**Comment by isatahiri** [comment]
yes what would be great. So the user knows what it is going on.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.11](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.11) includes commit that relate to this task:

* [ExcelImporter: AbortThreshold option support #459](https://github.com/eXpandFramework/eXpand.lab/commit/494e9d8467b40ae0d64b0907fd6021f92dff9f08)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
