### ISSUE TITLE
Excel Importer - define the ExcelImportKeyAttribute in the mapping directly

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#460]
Hi,

I would be very practical if we can define the ExcelImportKeyAttribute on the fly in the mapping directly. 

Would that be easy to implement ? 
Maybe other users can give their opinion on this idea.

![image](https://user-images.githubusercontent.com/41955268/60303193-13bdcb80-9936-11e9-8ca6-d878a1955d1d.png)

**Comment by apobekiaris** [comment]
I thought also about this from time to time, thnks for the suggestion

**Comment by emeyke** [comment]
I support that

**Comment by isatahiri** [comment]
I think we have to be careful and not make it too complicated. 
Especially when the propertly is a reference itself. A limit has to be defined. It is rare that reference properties are designed as key property. So we could just show primitiv field. 
Any easy suggestions if the user chooses reference property as ExcelImportKeyAttribute ?

**Comment by apobekiaris** [comment]
a tree can do it but do we need such complexity? the end user looking at the BO domain sounds a bad idea. How often such a requirement exist? Do you have some real world examples?

**Comment by apobekiaris** [comment]
or should we attribute it to the model? isn't this an admin job?

**Comment by apobekiaris** [comment]
nah model is a bad idea this is a key for the configuration and not for the BO if it goes to the runtime

**Comment by isatahiri** [comment]
From my point of view just the default attribute. I do not think that a reference property will be a key of the class.

**Comment by apobekiaris** [comment]
agreed first version will not populate domain objects

**Comment by isatahiri** [comment]
ok for me

**Comment by expand** [comment]
eXpand.lab release [19.1.402.12](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.12) includes commit that relate to this task:

* [Excel Importer - define the ExcelImportKeyAttribute in the mapping directly #460](https://github.com/eXpandFramework/eXpand.lab/commit/2d5ccbfe492de36c711c1588969575e532f9512f)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
