### ISSUE TITLE
StateMachine

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#461]
Hi,

Is it planned to have the StateMachine as low dependency DevExpress XAF module ? 

BR
ISA

**Comment by apobekiaris** [comment]
I do not see why not? in fact there should be as many standalone module as the features presented now, not one monolithic standalone

**Comment by isatahiri** [comment]
I was wondering : what do you thing if we create a planning/roadmap so we could see an order of future modules and have an approx idea of when.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
