### ISSUE TITLE
VSIX: XpandModelEditor displays duplicate records in SDK format projects

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#462]
They work fine though

**Comment by expand** [comment]
eXpand.lab release [19.1.402.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.13) includes commit that relate to this task:

* [VSIX: Fix duplicate model records #462](https://github.com/eXpandFramework/eXpand.lab/commit/0e905899e9e82b066aa237cc20f15c53abe8a2ba)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
