### ISSUE TITLE
VSIX: Load Referenced project sources feature fails in SDK format

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#463]

**Comment by expand** [comment]
eXpand.lab release [19.1.402.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.13) includes commit that relate to this task:

* [VSIX: Load Referenced project sources feature fails in SDK format #463](https://github.com/eXpandFramework/eXpand.lab/commit/7c8158a38db6bbd27bef18c2be194f70545a6c3b)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
