### ISSUE TITLE
Create a planning/roadmap so we could see an order of future modules and have an approx idea of when.

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#464]
I was wondering : what do you think if we create a planning/roadmap so we could see an order of future modules and have an approx idea of when.

_Originally posted by @isatahiri in https://github.com/eXpandFramework/eXpand/issues/461#issuecomment-507750327_

**Comment by apobekiaris** [comment]
At the moment I am working full time to integrate the ModelMapper module. It replaces all maps scattered around the framework and makes it super easy to create additional. Until this finished I cannot touch anything newer cause as I say this a huge refactoring. So cannot keep up to any roadmap promises but I expect thing to roll smoother afterwards.

However looking the current status over a more realistic view, since the work now requires commercial type efforts (tests/docs), I am looking to introduce some kind of bounty model for those that they want to boost some work or get better support etc. Bounties will be favored from participating developers. All other framework users should follow along developers contributions.

I have't decide about the bounty thing, however as You probably noticed Microsoft is pushing towards this model see the (Sponsor button) there are dedicated services like open collective https://docs.opencollective.com/help/developers/bounties#open-collective-bounty-program. Morever GitHub has a similar product ready to release and wait for approval to see what they come up with.

Looking to hear community feedback about these plans so I pinned this one.

**Comment by apobekiaris** [comment]
in the meantime @isatahiri maybe you can help organizing this project using https://github.com/orgs/eXpandFramework/projects/1

**Comment by apobekiaris** [comment]
note we can also use gitter for fast informal chats https://gitter.im/XpandFramework/community

**Comment by isatahiri** [comment]
This was i was thinking too : https://github.com/orgs/eXpandFramework/projects/1
But we needs to coordinate first. Note that I will be aways for two weeks but after coming back, I will start it. 
Do you expect integration of the ModelMapper module to be done by end of July ?

**Comment by apobekiaris** [comment]
I already integrating ModelMapper however I cannot be certain on when will finish exactly as this functionality is everywhere

**Comment by isatahiri** [comment]
What i could suggest is : 
To Do column with module names 
![image](https://user-images.githubusercontent.com/41955268/64118075-27067080-cd97-11e9-959e-72ae3220acf9.png)

So Ideally, we should open issues for each notes and create milestones for them with due dates and versions. (approx dates of course)
The point is to have a idea of when the module will be ready in Devexpress.Xaf

With the project module of github, when we will have something in between, then moving other milestones seems manual tasks :-(

What do you think of that ? 

BR
ISA

**Comment by apobekiaris** [comment]
what is your view on how to prioritize issues? apparently cannot build everything

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
