### ISSUE TITLE
ConnectionInfoStatusMessageController: Display info also in child windows

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#466]
I like the ConnectionInfoMessage added by the ConnectionInfoStatusMessageController. Unfortunately the info is only shown in main windows. Sometimes my users send me screenshots of nested windows and I cannot see/check the ConnectionInfoMessage. Therefore I think it does make sense to display the ConnectionInfoMessage also in child windows.
Maybe you can add another option to the IModelOptionsConnectionInfoStatusMessage?

Thank you!

**Comment by apobekiaris** [comment]
thnks for the suggestion I will update u once i research it, at the moment however I am overloaded and this may take a while, so if you have a custom implementation and u in hurry feel free to send a PR.

side note: this functionality is going to be a reactive package of a broader context in the feature.

**Comment by expand** [comment]
eXpand.lab release [19.1.501.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.1) includes commit that relate to this task:

* [Model option Display connection info in child windows #466](https://github.com/eXpandFramework/eXpand.lab/commit/74bcc8b74b39e012b2d64cdf58a19fbd113ba71e)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Works like a charm. Thank you!
