### ISSUE TITLE
NavigationItem.DataSourceListView - sort items alphabetically

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#467]
Or provide an option in the model for the sort field

**Comment by expand** [comment]
eXpand.lab release [19.1.501.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.1) includes commit that relate to this task:

* [NavigationItem.DataSourceListView - sort items alphabetically #467](https://github.com/eXpandFramework/eXpand.lab/commit/642226a6f4b5ec832dc8f5822e81c3fa7f376124)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
