### ISSUE TITLE
WizardUI not working after updating to 19.1.4

### ISSUE THREAD

**Issue by Lukas-lab** [eXpandFramework/eXpand#468]
After updating an existing project from 19.1.3 to 19.1.4 i can't use the WizardUI anymore, since it returns a error message.

> Dieser Vorgang kann die Laufzeit destabilisieren.

 

>   bei CreateWindow_Patch1(XafApplication context, TemplateContext controllers, ICollection`1 createAllControllers, Boolean isMain, Boolean view, View )
>    bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInModalWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Win.WinWindow.ProcessActionCreatedView(ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
> ![image](https://user-images.githubusercontent.com/52030639/60968978-a723d300-a31e-11e9-899b-1d2debbae000.png)

 I tried to reproduce this in a new project and there i get another exception:

>  Das Objekt des Typs "System.String" kann nicht in Typ "System.Drawing.Bitmap" umgewandelt werden.   

> bei Xpand.ExpressApp.WizardUI.Win.Properties.Resources.get_wizard_image()
>    bei Xpand.ExpressApp.WizardUI.Win.Templates.WizardDetailViewForm.InitializeComponent()
>    bei Xpand.ExpressApp.WizardUI.Win.Templates.WizardDetailViewForm..ctor()
>    bei Xpand.ExpressApp.WizardUI.Win.WizardUIWindowsFormsModule.Application_CreateCustomTemplate(Object sender, CreateCustomTemplateEventArgs e)
>    bei DevExpress.ExpressApp.XafApplication.RaiseCreateCustomTemplate(CreateCustomTemplateEventArgs args)
>    bei DevExpress.ExpressApp.XafApplication.OnCreateCustomTemplate(String name)
>    bei DevExpress.ExpressApp.XafApplication.CreateTemplate(String templateContextName)
>    bei DevExpress.ExpressApp.Frame.CreateTemplate()
>    bei DevExpress.ExpressApp.Win.WinWindow..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
>    bei DevExpress.ExpressApp.Win.WinApplication.CreateWindowCore(TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
>    bei DevExpress.ExpressApp.XafApplication.CreateWindow(TemplateContext context, ICollection`1 controllers, Boolean createAllControllers, Boolean isMain, View view)
>    bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInModalWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInModalWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
>    bei DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Win.WinWindow.ProcessActionCreatedView(ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
>    bei DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
![image](https://user-images.githubusercontent.com/52030639/60969109-0386f280-a31f-11e9-95ca-27499ef77293.png)

1. Create new XAF Project with Version 19.1.4
2. Add WizardUI via the WinModul.cs
3. Create a Business Object and specify a Wizard Page
4. Start the program and try to create a new object 

Expected behavior
Wizard Page should just open

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1903
 - Visual Studio Update 16.1.6
 - XAF 19.1.4
 - eXpandFramework 19.1.4

**Additional context**
I uploaded my test application, which only shows the 2nd Bug
[expandframeworktest.zip](https://github.com/eXpandFramework/eXpand/files/3377405/expandframeworktest.zip)

**Comment by expand** [comment]
eXpand.lab release [19.1.501.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.2) includes commit that relate to this task:

* [WizardUI throws on error after 19.1.4 #468](https://github.com/eXpandFramework/eXpand.lab/commit/d8f9fa2652cb0d6fb31fa36843d2b71535df46f1)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by Lukas-lab** [comment]
it works now. Thanks a lot

**Comment by Lukas-lab** [comment]
It works now. Thanks a lot
