### ISSUE TITLE
Xpand.Source.Extensions.XAF.Model.ModelExtensions: Change from internal to public

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#470]
The ReadFromModel method from ModelExtensions seems to be usefull in my own model. Unfortunately ModelExtensions  is marked as internal. Can you please change it to public?

**Comment by apobekiaris** [comment]
unfortunately the only why this can work is when i create seperate packages for sources. At the moment these files are used from as linked files from the modules and the Tests have direct access through the InternalsVisiable attribute. Marking it as public will create conlicts which I plan to resolve by publishing smaller Xpand.Source.Extensions packages. However I could add and InternalsVisible entry for your projects if u wish not to wait. Let me know by providing your key

https://github.com/eXpandFramework/DevExpress.XAF/blob/lab/src/Extensions/Extensions/Properties/AssemblyInfo.cs#L41

or if u have a better idea feel free to suggest.

**Comment by krombipils** [comment]
>  Marking it as public will create conlicts

What conflicts are you talking about?

I think publishing Xpand.Source.Extensions is a good idea. Until then I will just copy&paste the required code into my project.
Thank you!

**Comment by apobekiaris** [comment]
module A uses the file as linked so its internal to moduleA, tests use it with the internalsvisible attribute. i do not want to reference the Source project to modules as it has many dependencies I also do not want to expose the Source api from each module so I avoid to make it public. The only way I see this getting resolved is to break the SOurces into small packages.

**Comment by krombipils** [comment]
I think this does make sense. Looking forward

**Comment by apobekiaris** [comment]
it already up in my todo as it is very useful to people that contribute that have much higer priority than simple users

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Release Xpand.Extensions, Xpand.Extensions.Cecil, Xpand.Extensions.XAF, Xpand.Extensions.XAF.Xpo, Xpand.TestsLib packages #470](https://github.com/eXpandFramework/DevExpress.XAF/commit/6b8ea608cf982240d01de9ce6c924579c1ad05c0)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
@gerritmulder please note this commit as it relates to the work you are doing, as I mentioned in the past plans are to mode functionality from Xpand.Xpo, Xpand.Utils to standalone packages as they spawn through versions. 

So the analogy I guess is clear but I will emphasize it, noting that there should be an effort to minimize dependencies .

Xpand.Utils-> Xpand.Extensions
Xpand.Xpo-> missing
Xpand.Base(only agnostic) -> Xpand.DevExpress.XAF

let me knkow your thoughts

**Comment by krombipils** [comment]
Nice job! Thank you!
