### ISSUE TITLE
ModelViewInheritance: Chained merging no longer works as before

### ISSUE THREAD

**Issue by impactjo** [eXpandFramework/eXpand#471]
Chained merging of several listviews used to work in eXpand (at least in 17.2.5) but is no longer working after upgrading an application to XAF standalone modules.

Detailed description:
I have 4 list views in the model: 
1. Connection_ListView
2. Connection_ListView_Base (generated by CloneModelView-Attribute)
3. Connection_ListView_NestedBase (generated by CloneModelView-Attribute)
4. Element_Connections_ListView

The 2nd ListView merges the differences from 1st (via MergedDifferences-Node in ModelEditor of Base Module). The 3rd ListView merges from 2nd ListView and 4th from 3rd. By the way merging here is all about column settings.

This worked flawlessly in eXpand 17.2.5 but strangely does no longer after upgrading to XAF-standalone modules.

The columns gets correctly merged until 3rd ListView but then strangely no more to the 4th ListView.
A strange thing to observe under 4th ListView's MergedDifferences-Node is, that although only one node was added manually (that one for merging 3rd LV) another node is automatically generated (for merging of 4th LV - showing up in non bold letters in ModelEditor). Column settings seem pretty much to don't get merged at all for 4th ListView.

I hope that by knowing the inner workings and changes of ModelViewInheritance-Module you can deduce what change might have caused this problem any hopefully can fix it.

**Comment by apobekiaris** [comment]
thnks for posting the module is now rewritten simplified and unit tested. Thus having a repro sample will help me add more tests to cover this case.

**Comment by impactjo** [comment]
Hi,
I have created sample project and attached it. All the interesting stuff is in the base module.  Just take at the "Element" sample business class there. If you open the model editor you can look at the Element_ListViewBase and Element_ListViewNestedBase and see that Base-LV correctly merges Element_ListView (only Street column should be shown). But ListViewNestedBase that merges from Element_ListViewBase does not merge correctly (all columns are shown).
Thanks, Johannes

Btw: Is the old expand-website and forum information really all gone? That would be real pitty. I have googled problems and found eXpand-forum entries that are no longer available. The start page  was also useful etc.

[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/3398889/Solution1.zip)

**Comment by apobekiaris** [comment]
Thnks for the sample, I ll let u know once I unit test the case. 

Yes the old site is now gone, GitHub is a superior platform supporting the old site was a big headache. Either way the plan is to rewrite and document the whole framework, so you will not miss that old data in a few months.

**Comment by impactjo** [comment]
I see the headache supporting the site. Hopefully the information on it is really no longer needed in the future. The split up of monolithic eXpand is a great thing in any case! Thanks

**Comment by apobekiaris** [comment]
I agree with u however since we are in public now and the modules will remain I do not agree that the current status can be named monolithic. All the modules right now can work as standalone with a reference to the Base lib this is exactly what XAF offers, this way you might call XAF monolithic. The new project can be named low dependency as it does not carry/share a Base lib and its dependecies.

**Comment by impactjo** [comment]
Sorry, I probably just don't know the current status. With "monolithic" I refered to those times where you added one eXpand-module and that one often referenced a bunch of others and so you had add a lot of modules that you weren't originally interested in and that usually added complexity and headaches (for me).

**Comment by apobekiaris** [comment]
no need to sorry we just discussing something, 

>With "monolithic" I refered to those times where you added one eXpand-module and that one often referenced a bunch of others and so you had add a lot of modules that you weren't originally interested in and that usually added complexity and headaches (for me).

yes this is tru for some modules. They still reference other modules however they do not register them. Meaning that there are not low dependency but the depended module do not interfere as they not registered. They are reference so to explicit consume their API but as I said their artifacts are not consumed by XAF automatically as they not registered.

Monolithic has a different meaning and was simply misused with no offense.

With the new project you should be able to puzzle what you need only. Note however that if you puzzle all then again you will end with the support cost of such an action.

**Comment by impactjo** [comment]
If there is no need to register the dependent modules anymore and so they don't interfere than this is a big win as well.

**Comment by apobekiaris** [comment]
though that is the case at least for some years now, apparently there are more issues like the ones you having but since I do not know them I cannot plan anything for them.

so please put some details for consideration as we are in the middle of a major refactor.

**Comment by impactjo** [comment]
Indeed some of my experiences are years back and I therefore have no details anymore. Those experiences at least caused me to minimize eXpand dependencies and sometimes rather not use powerful features that would have been useful (f.e. I vaguely remember that I refrained from ModelArtifactState once, as it needed to many other references/modules that somehow interfered - maybe security module or something like that - unfortunately only vague memories that might not be correct) . If the old forum would still be alive I would have looked up some of my former eXpand-Forum posts for possibly getting some old issues I experienced and thereby update my memory.

For one current application now I only use the new CloneModelView, ModelViewInheritance extensions and also some assembly references to eXpand IO where I only use ImportEngine and ExportEngine with interfaces (ISerializationConfiguration etc.) but not the included business objects, UI etc.  
With IO module I am OK so far as I don't have to use the module and just reference the assemblies. Of course it would be nicer if the basic  functionality I need, would be in assemblies that maybe wouldn't need to have a reference to DX assemblies, as I then wouldn't no longer need to update eXpand when I update to a new DX version. Or maybe it could also move in a new XAF extension.

I am really glad that I got rid of eXpand.SystemModule with the new extensions in one application. Xpand SystemModule is/was a module that I remember as doing a lot of "magic" and introtuced features and interferences I didn't appreciate. At least some of these things were discussed in the old forum.

For another client application I additionaly use Model Difference module. So for me it would be nice if it's functionality would also move in a new XAF extension (for easier DX upgrades).

So hopefully there might be something in these (vague) thoughts/memories that can be considered somehow regarding the refactorings.

**Comment by impactjo** [comment]
Addendum: As you see above it seems a real loss that the information of the old forum is gone. With the help of google cache I just looked up one former interesting conversation in a thread called "Issue with Inheriting from XpandRole" (opened by someone else) where I asked:
 "My Question is wheter this can be changed so that XpandSecurity doesn't interfere when I don't want/need to use XpandSecurity (I need to add it just because other Xpand-Modules depend on it)?"

Unfortunately I can't navigate to the second page of the discussion with the help of google cache.

Also this thread shows how helpful the forum information was when you googled problems relating to eXpand and XAF. The thread was opend in 2015 and I came there in 2018 as I searched the reason for a strange error message that seemed to come out from nowhere (that nowhere then turned out to be the security module).

**Comment by apobekiaris** [comment]
IO, ModelDifference, ModelArtifact are good s fits for standalone packages, and until then it could be doable to remove dependencies to base and system modules. This already into my plan.

The Current situation with BaseImpl and its dependecies also suffers and there is much place for improvement there, I am also planning some works for this as we move forward.

Also maybe the wayback machine can be of some help yo u instead of google cache? https://archive.org/web/

There is also a downloader available at https://github.com/hartator/wayback-machine-downloader. From what I see is possible to get a list of your issues https://web.archive.org/web/20170820072508/http://www.expandframework.com/support/forum/user/285-johannes.html

**Comment by apobekiaris** [comment]
While writing a test for this case it become apparent that there is nothing wrong with the module. I agree it might have a bit of different behavior than before but now is a well structured and tested code and most probably the behavior before will not be consistent of deeper levels. 

Now to clarify some parts:

In `Element_ListViewNestedBase` you merge the differences of `Element_ListViewBase` however the `Element_ListViewBase` has no differences except the `MergeElement_ListView` (this confused as I understand in the top of this thread) so nothing is done. If you want to merge future differences of `Element_ListViewBase` in addition to current and future differences of `Element_ListView` you could write 

```xml
<ListView Id="Element_ListViewNestedBase">
  <MergedDifferences>
    <MergedDifference Id="@a8226d80-7abd-444f-bb74-82bbc08a31b2" View="Element_ListView" IsNewNode="True" />
    <MergedDifference Id="MergeElement_ListView" Removed="True" />
    <MergedDifference Id="MergeElement_ListViewBase" View="Element_ListViewBase" IsNewNode="True" />
  </MergedDifferences>
</ListView>

```

in the snippet i removed the `MergeElement_ListView` I am not so sure if we should remove it by default though. The module correctly detected this as a difference and merged it but not take into account.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelViewInheritance: Test Chained_Cloned_listview_merging #471](https://github.com/eXpandFramework/DevExpress.XAF/commit/132221223d9101c2d546d5bf6db12c1de5d78212)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by impactjo** [comment]
The code might be more beautiful now, but from usage/feature point it seems pretty clearly less powerful and less consistent now. I will try your posted workaround  this week.
If CloneView code in "main" eXpand  is still working as before I might also fall back on main eXpand.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelViewInheritance: DeepMerge support #471](https://github.com/eXpandFramework/DevExpress.XAF/commit/86ab0933e37026fef74699182cba7a111cd4459a)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.7) includes commit that relate to this task:

* [Bump standalone packages #471 #525](https://github.com/eXpandFramework/eXpand.lab/commit/f1f96e911b6fea8a1b2e91641b7b0726614410d3)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
