### ISSUE TITLE
No way to disable MasterObject filtering

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#473]
Hi Tolis

I have a business object (ContractRule) whith a collection property (OrderRules). this property has a datasourcecriteria attribute. This attribute is intended for filtering when the user wants to connect a new order rule to the contract rule.

But when I open a detailview of the ContractRule the list with orderrules is filtered with the criteria from the datasourcecriteria attribute. This is not desired. I only want to filter the lookup views when connecting a new orderrule. 

The criteria is added by the MasterObjectViewController and the FilteredMasterObjectViewController. I can not disable this functionality.

Can you please add a way to disable this? Is this behavior intended?

Thanks,
Jacob

**Comment by apobekiaris** [comment]
Hi,

How about 
```cs
protected override void OnFrameAssigned() {
            base.OnFrameAssigned();
            Frame.GetController<FilteredMasterObjectViewController>().Active[""] = false;
        }
```

**Comment by jacobdeboer33** [comment]
Hi Tolis

Thanks for the reply. I was looking for a way to do this runtime, because one of our customers reported this to us. 

Can you please tell me what this controller doos? 

Thanks,
Jacob

**Comment by apobekiaris** [comment]
I am not sure what you asking, the snippet I posted before works at runtime. Just create a new viewcontroller and override the OnFrameAssigned method.

**Comment by apobekiaris** [comment]
in latest version the `MasterObjectDataSourceCriteriaAttribute` is used instead from these controllers, so there is behavior change

**Comment by jacobdeboer33** [comment]
Hi Tolis

This will solve my problem. 

Thanks.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.7) includes commit that relate to this task:

* [FilteredMasterObjectViewController breaks XAF lookupfiltering, replace DataSourceCriteriaAttribute with MasterObjectDataSourceCriteriaAttribute #473](https://github.com/eXpandFramework/eXpand.lab/commit/35e86e3924c2ae707aadf129b226cde2f1c5e01f)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
