### ISSUE TITLE
Quartz Server no longer exe ?

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#475]
Hello,

Can you please tell me if the Xpand Quartz Server is now only available as *.dll ?
Until 19.1.402 it was available as *.exe

Is there anything to note here?

**Comment by apobekiaris** [comment]
what is the problem exactly I fail to follow u. Why you expect a service to be distributed as a library?

**Comment by rSeeFip** [comment]
Thanks for the quick answer.
Until now i use it out of box as service, now it's a library.

I'm just want to now if it's necessary to integrate the library to own service or it comes back as
executable service

**Comment by apobekiaris** [comment]
probably a distribution mistake, you can simply build the Qartz.Server as an exe and use it. I mark the issue to fix it however it will take some time as currently I am overloaded.

**Comment by rSeeFip** [comment]
ok, thanks

**Comment by expand** [comment]
eXpand.lab release [19.1.402.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.3) includes commit that relate to this task:

* [Quartz.Server compiled as library #475](https://github.com/eXpandFramework/eXpand.lab/commit/e6f92cc237a29fc843f4013e531e54433212db30)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
