### ISSUE TITLE
Make Xpand.VSIX version agnostic

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#476]
The VSIX package depends on Devexpress version 

1. For new solution project wizard
2. For XpandModelEditor

Provide a version agnostic and and dedicated repository.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.4) includes commit that relate to this task:

* [VSIX: Version agnostic and embedded XpandModelEditor  #476](https://github.com/eXpandFramework/eXpand.lab/commit/5fab685895d27e7b1fad488f5b7a1c5fd86c435f)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.402.10](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.10) includes commit that relate to this task:

* [VSIX: Notify on XpandModelEditor errors #476](https://github.com/eXpandFramework/eXpand.lab/commit/4005e0197297412b097d4ac87429a34fb2980087)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
xpand dependencies should come from Nuget.org

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
