### ISSUE TITLE
Conversion Error in ListView with Xpand RichEdit PropertyEditor

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#478]
When i try to open an Listview with field with Xpand Richedit Property Editor,
i will get following error since 19.1.4 in Winforms Win10

Das Objekt des Typs "System.String" kann nicht in Typ "System.Drawing.Image" umgewandelt werden.

   bei Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditContainerRibbon.InitializeComponent()
   bei Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditContainerRibbon..ctor()
   bei Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditContainerBase.Create(RibbonFormStyle formStyle, XafApplication application)
   bei Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditWinPropertyEditor.CreateControlCore()
   bei DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   bei DevExpress.ExpressApp.Win.Layout.WinLayoutManager.GetControl(ViewItem viewItem, String name, Boolean forceControlCreation)
   bei DevExpress.ExpressApp.Win.Layout.WinLayoutManager.controlItem_QueryControl(Object sender, QueryControlEventArgs e)
   bei DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseQueryControl()
   bei DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.EnsureControl()
   bei DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseShowHide(Boolean visible)
   bei DevExpress.XtraLayout.BaseLayoutItem.SetVisible(Boolean lVisible)
   bei DevExpress.XtraLayout.BaseLayoutItem.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.LayoutControlItem.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.TabbedGroup.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   bei DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   bei DevExpress.XtraLayout.LayoutControlImplementor.UpdateRoot()
   bei DevExpress.XtraLayout.LayoutControlImplementor.InvalidateRootOffsetControlsAndScrolls()
   bei DevExpress.XtraLayout.LayoutControlImplementor.Invalidate()
   bei DevExpress.XtraLayout.LayoutControl.DevExpress.XtraLayout.ILayoutControl.Invalidate()
   bei DevExpress.XtraLayout.BaseLayoutItem.Invalidate()
   bei DevExpress.XtraLayout.LayoutGroup.Invalidate()
   bei DevExpress.XtraLayout.BaseLayoutItem.ComplexUpdate(Boolean shouldUpdateViewInfo, Boolean shouldResize, Boolean shouldArrangeTextSize)
   bei DevExpress.XtraLayout.LayoutItemContainer.EndUpdate()
   bei DevExpress.XtraLayout.LayoutItemContainer.EndChangeUpdate()
   bei DevExpress.XtraLayout.LayoutDesignerMethodsProvider.DevExpress.XtraLayout.ILayoutDesignerMethods.EndChangeUpdate()
   bei DevExpress.XtraLayout.LayoutControlImplementor.ProcessLookAndFeelStyleChanged()
   bei DevExpress.XtraLayout.LayoutControlImplementor.OnLookAndFeelStyleChanged(Object sender, EventArgs e)
   bei DevExpress.XtraLayout.LayoutControlImplementor.EndInitCore()
   bei DevExpress.XtraLayout.LayoutControlImplementor.set_UpdatedCount(Int32 value)
   bei DevExpress.XtraLayout.LayoutControlImplementor.EndInit()
   bei DevExpress.XtraLayout.LayoutControl.EndInit()
   bei DevExpress.ExpressApp.Win.Layout.WinLayoutManager.LayoutControls(IModelNode layoutNode, ViewItemsCollection viewItems)
   bei DevExpress.ExpressApp.CompositeView.CreateControlsCore()
   bei DevExpress.ExpressApp.View.CreateControls()
   bei DevExpress.ExpressApp.Editors.NestedFrameItem.CreateControlCore()
   bei DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   bei DevExpress.ExpressApp.CompositeView.CreateViewItemControls()
   bei DevExpress.ExpressApp.CompositeView.CreateControlsCore()
   bei DevExpress.ExpressApp.ListView.CreateControlsCore()
   bei DevExpress.ExpressApp.View.CreateControls()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.OnViewChanged()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.SetView(View view)
   bei DevExpress.ExpressApp.Win.Templates.Ribbon.DetailRibbonFormV2.DevExpress.ExpressApp.Templates.IFrameTemplate.SetView(View view)
   bei DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   bei DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)

**Comment by apobekiaris** [comment]
until fixed try the workaround in 

https://github.com/eXpandFramework/eXpand/issues/474#issuecomment-514166265

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/eXpand/issues/503

**Comment by expand** [comment]
eXpand.lab release [19.1.502.10](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.10) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/801728c32f3df8e189d68dc589af4a82b13891a5)
* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/2c6041db17458b85c36e0427d4803ef2b4da6b75)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.11](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.11) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/4e2b726fc8ef99632c38f65d8381c9de73590e35)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
