### ISSUE TITLE
Improve build performance

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#479]
modules are build sequential now for no apparent reason, furthermore thsi setup does not test versionconverter

**Comment by expand** [comment]
eXpand.lab release [19.1.402.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.13) includes commit that relate to this task:

* [Improve build performance #479](https://github.com/eXpandFramework/eXpand.lab/commit/bd7997b2353620e215d31ca14ea3d2d2a858f47f)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
