### ISSUE TITLE
VSIX empty XAF Model window in VS2019

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#480]
Suddenly (maybe after nightly windows update?) the Xaf Model Window in VS2019 appears empty(Not drawn)
VS2019 16.1.6 and 16.2
VSIx 19.1.40x
attempted uninstall and reinstall with no luck

How can I clean the registry?

Attached screencast
[2019-08-01_12-29-31.zip](https://github.com/eXpandFramework/eXpand/files/3457496/2019-08-01_12-29-31.zip)

**Comment by apobekiaris** [comment]
how did u got the VSIX? which release? try the latest. The ModelEditor now is empbedded and the options disabled and in latest removed

**Comment by vimarx** [comment]
it is ok with latest! Thanks!
