### ISSUE TITLE
Excel Import Problem - No Way to Select File to Import

### ISSUE THREAD

**Issue by dtbagg** [eXpandFramework/eXpand#481]
**Describe the bug**
I add Excel Importer and try to Upload a File. The editor seems to prevent that, only select from existing choices - there aren;t any and no New button either.  I am not sure what I am doing wrong.

**To Reproduce**
1 Just launch from Menu option.  Form does not show expected editor.

**Expected behavior**
I expect to be able to browse to a file to import.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Safari, Chrome, Edge all show same problem as in Desktop
 - Version [e.g. 22] 19.1.0.4 - I think, this is Xpand version

**Smartphone (please complete the following information):**

**Additional context**
I don't see how but it could be some step I missed. Same problem in Desktop or Web but attached shows from Windows Desktop
![importproblem](https://user-images.githubusercontent.com/51164046/62337897-76116b00-b4a4-11e9-9b6a-713b8aa45400.JPG)

**Comment by apobekiaris** [comment]
most probably u missed to install the ExcelImporterWinModule

**Comment by dtbagg** [comment]
Yes, but I can't add that it seems.  Maybe I have to remove the Import Wizard things.  See attached
![evenuniversehatesme](https://user-images.githubusercontent.com/51164046/62338184-97268b80-b4a5-11e9-861e-aede4db2bd86.JPG)

**Comment by dtbagg** [comment]
Same thing.  I added similar to web - or tried to - similar error.  I think I better start over and be sure to choose both options.
![sameerroronweb](https://user-images.githubusercontent.com/51164046/62338360-46fbf900-b4a6-11e9-9111-cbaa508f58e1.JPG)

**Comment by dtbagg** [comment]
It looks like I have 19.1.4.0 in most places but may have a 19.1.3.0 version elsewhere.  I think I may be on track to fixing it.  Sorry. How do I make this not a bug?

**Comment by apobekiaris** [comment]
no worries then, i relabel it for u

**Comment by dtbagg** [comment]
Actually it seems the problem is in the two additional xpand modules - the one for the web and one for windows.  The error above refers to DevExpress 19.1.3.0 .dll that I cant find anywhere else in the project.  When I remove Xpand the project compiles fine - so that .dll seems to be referenced only in Xpand.  Any suggestions?

**Comment by apobekiaris** [comment]
u can try to find out which to blame by loking at the stack trace, using any .NET mthod u prefer.

for e.g. the first thing that comes to my mind is to subscribe to AppDomain.CurrentDomain.AssemblyResolve and look at the stack when u have an emit for the 19.1.3 assembly

**Comment by apobekiaris** [comment]
hmm my suggestion will work for runtime problems, I missed the shots u posted before. In that case i would install the module manually. The toolbox is really a water of time VS never behave stable. Note that in next minor we drop support for the XAF model editor as well and only the XpandModelEditor can be used, though u can use the Module Designers to add XAF native modules. All Xpand modules do not provide any benefits when the module designer is used, as I said a waste of time.

so to install any module just add this call to the contrsctor of your webmodule.cs file

```cs
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Web.ExcelImporterWebModule)
```
and try to see if u run it.

**Comment by dtbagg** [comment]
I got it working by uninstalling DevExpress 19.1.4 and using 19.1.3

Thanks

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
