### ISSUE TITLE
Xpand.VSIX LoadProjects cannot index SDK formats

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#482]

**Comment by expand** [comment]
eXpand.lab release [19.1.501.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.1) includes commit that relate to this task:

* [Xpand.VSIX LoadProjects cannot index SDK formats #482](https://github.com/eXpandFramework/eXpand.lab/commit/40573d035ae281451dda16b2ed65ef9a1aa45745)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
