### ISSUE TITLE
netstandard dependencies

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#483]
What implications does netstandard support have in this commit?
Will we lose compatibility with netframework 4.6.1?
https://github.com/eXpandFramework/eXpand/commit/a88665ac40804a9ef896dbeaf98c0ca84c550196

**Comment by apobekiaris** [comment]
nope 4.6.1 can consume .netstandard

**Comment by vimarx** [comment]
So, it is enough to include netstandard.dll only?
![image](https://user-images.githubusercontent.com/226800/62434907-b2490380-b710-11e9-8d10-300cdb1cc3fa.png)

**Comment by apobekiaris** [comment]
eXpand is compile already and does not reference it directly, I do not get your point

**Comment by apobekiaris** [comment]
furthermore XAF is going there very soon I guess

**Comment by vimarx** [comment]
to compile my existing app with 19.1.5xx I had to include netstandard as a reference, because VS2019 ask me to do it, for example in my reference of Xpand.Xpo.DB.DataStore

I'm only asking to know what is the implication of such dependency

:)

**Comment by apobekiaris** [comment]
sorry if I sound strange yes it is safe to consume and Xpo is .NET Standard now, 4.6.1 should work fine as other modules consume xpo without direct references to .netstandrd

**Comment by apobekiaris** [comment]
netstandard is a specification, does not have implementation, think it like an interface. The implementation is given from the targetframework in this case the 4.6.1
