### ISSUE TITLE
IModelListViewOptionsAdvBandedView could not be found

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#484]
Hello. new version 19.1.5.  IModelListViewOptionsAdvBandedView could not be found!!!

**Comment by apobekiaris** [comment]
Hi,

cannot tell much with such short guidance, please provide repro instruction

**Comment by gerritmulder** [comment]
We have the same case with the IModelListViewOptionsGridView interface, it is being used in our code.

Both interfaces are removed in this commit: https://github.com/eXpandFramework/eXpand/commit/649190ddd939632ef2ca1a0728b3a47b497a3d1a#diff-65749f305919a28ac3550072f5c1505d without any explanation why it is removed or any code that can replace.

**Comment by apobekiaris** [comment]
the mapping is now replaced with ModelMapper apologies for the temp commit. 
Useful methods to retrieve dynamic interfaces such as the IModelListViewOptionsGridView are describe in the docs
https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/src/Modules/ModelMapper#details

if you still have issues please provide details on how u used the past dynamic model implemention

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
