### ISSUE TITLE
DevExpress NuGet references in nuspecs

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#485]
The current NuGet packages from 19.1.501 are referencing the NuGet packages from the DevExpress feed. This shouldn't be the case, because then the XAF version can't be dynamic.

Cause of the problem: https://github.com/eXpandFramework/DevExpress.XAF/blob/7abb533d51d71578f1d6348b26b473b0ab76920f/tools/Build/CreateNuspec.ps1#L80-L86

**Comment by expand** [comment]
eXpand.lab release [19.1.501.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.4) includes commit that relate to this task:

* [DevExpress NuGet references in nuspecs #485](https://github.com/eXpandFramework/eXpand.lab/commit/e01d7016f1db1ecf29ac735e96258e1816fe5a3a)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.501.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.5) includes commit that relate to this task:

* [DevExpress NuGet references in nuspecs #485](https://github.com/eXpandFramework/eXpand.lab/commit/769089a5bc4a5c345824dadf2046c69d87c13610)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.501.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.6) includes commit that relate to this task:

* [DevExpress NuGet references in nuspecs #485](https://github.com/eXpandFramework/eXpand.lab/commit/078c264da82f12998336492dcdb522fb2f9f4bf0)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
