### ISSUE TITLE
EnumRepositoryItemGridListEditorController throws NullReferenceException

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#486]
The latest (19.1.501.5) version of the EnumRepositoryItemGridListEditorController throws a NullReferenceException if the ListViews contains a nested enum reference column, e.g. Person.PreferredContactMethod.
This happens because column is null in OnViewControlsCreated
 `GridColumn column = gridListEditor.GridView.Columns[info.Name];`

info.Name is 'PreferredContactMethod' in my sample, but 'Person.PreferredContactMethod' is correct.
I slightly modified your code and use FindColumnByModel from [DevExpress](https://www.devexpress.com/Support/Center/Question/Details/T680948/how-to-get-a-grid-column-by-a-property-name-imodelcolumn-propertyname):

    protected GridColumn FindColumnByModel(GridListEditor gridListEditor, IModelColumn columnModel)
    {
        var columnWrapper = gridListEditor.FindColumn(columnModel.Id) as XafGridColumnWrapper;
        return columnWrapper?.Column;
    }

    protected override void OnViewControlsCreated()
    {
        if (View.Editor is GridListEditor gridListEditor)
        {
            _memberInfos = View.Model.Columns.Where(_ =>
                    _.Index > -1 && (_.ModelMember.MemberInfo.MemberType.IsEnum ||
                                     ReflectionExtensions.IsNullableType(_.ModelMember.MemberInfo.MemberType) &&
                                     _.ModelMember.MemberInfo.MemberType.GetGenericArguments().First().IsEnum))
                .ToArray();
            _repos = _memberInfos.Select(info =>
            {
                var gridColumn = FindColumnByModel(gridListEditor, info);
                var tuple = (column: gridColumn, repositoryItem: gridColumn.ColumnEdit,
                    info.ModelMember.MemberInfo);
                gridColumn.ColumnEdit = new RepositoryItemTextEdit();
                return tuple;
            }).ToArray();
            gridListEditor.GridView.CustomRowCellEditForEditing += GridViewOnCustomRowCellEdit;
        }
    }

**Comment by expand** [comment]
eXpand.lab release [19.1.501.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.501.7) includes commit that relate to this task:

* [EnumRepositoryItemGridListEditorController throws NullReferenceException #486](https://github.com/eXpandFramework/eXpand.lab/commit/082aa09e66a05f1a60ce710715fa5da99a01c6b2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Fixed! Thank you!
