### ISSUE TITLE
Xpand.Source.Extensions.FunctionOperators.IsAssignableFromOperator "throw an exception."

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#487]
Hello. When I open first time ListView and Edit model does not open at all

{"The type initializer \" Xpand.Source.Extensions.FunctionOperators.IsAssignableFromOperator \ "threw an exception."} System.Exception {System.TypeInitializationException}

in Xpand.XAF.Modules.ModelMapper.ModelMapperVisibilityCalculator..ctor()

DevExpress.ExpressApp.SystemModule.CustomFunctionOperatorHelper.Register(ICustomFunctionOperator customFunctionOperator)
Xpand.Source.Extensions.FunctionOperators.IsAssignableFromOperator..cctor()

The operation is invalid due to the current state of the object.

**Comment by apobekiaris** [comment]
Hi,

I cannot tell without a sampel where is the problem? maybe you already have an operator `IsAssignableFrom` and fails to register the same name?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
