### ISSUE TITLE
EditModelController throws MissingMethodException when closing ModelEditor

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#489]
When closing the ModelEditor in a running WinForms XAF app, EditModelController throws an exception:
`
No match for method with name RefreshShowViewStrategy and flags Instance | NonPublic | Public | Static on type WinForms.Win.WinFormsWindowsFormsApplication with parameter count 0 and types: .`

Of course RefreshShowViewStrategy is defined in WinApplication and if I call e.g. 
`Fasterflect.MethodExtensions.Method(typeof(DevExpress.ExpressApp.Win.WinApplication), "RefreshShowViewStrategy ");` it returns a MethodInfo

Can you repro the problem?

**Comment by apobekiaris** [comment]
yes i can tnks

**Comment by krombipils** [comment]
Any idea what's wrong? I'm not very familiar with fasterflect, but I could take a look...

**Comment by apobekiaris** [comment]
no idea that call shouldn't fail fasterflect needs no further parameters it should call any method any visibility.

**Comment by apobekiaris** [comment]
u can replace with a refelction call until is fixed

**Comment by apobekiaris** [comment]
it looks like there are two versions of fasterflect in the xpand.dll folder, it could be an issue.

**Comment by apobekiaris** [comment]
only the netstanardd version should be there

**Comment by krombipils** [comment]
According to the VS Modules window, only the Fasterflect.Netstandard.dll is loaded.
I'm running on net461. In [net-standard](https://docs.microsoft.com/de-de/dotnet/standard/net-standard) MS says:

> For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

Could this be related?

**Comment by apobekiaris** [comment]
thats a recommendation and most probably to cover their ass like doctors :). 
fasterflect is used everywhere and for this case is totally acceptable to replace it with a reflection call

**Comment by apobekiaris** [comment]
does the same call fails if u do it in your Program.cs?? experiement a bit with the Flags parameter in the callmethod. We reverently updated FasterFlect to its .NETStandard version however it was published not from the original author. It might have problems.

**Comment by genetsEvgen** [comment]
I have the same problem

No match for method with name RefreshShowViewStrategy and flags Instance | NonPublic | Public | Static on type WindowsFormsApplication with parameter count 0 and types: .

   в Fasterflect.Emitter.LookupUtils.GetMethod(CallInfo callInfo)
   в Fasterflect.Emitter.MethodInvocationEmitter.CreateDelegate()
   в Fasterflect.Emitter.BaseEmitter.GetDelegate()
   в Fasterflect.MethodExtensions.DelegateForCallMethod(Type type, Type[] genericTypes, String name, Flags bindingFlags, Type[] parameterTypes)
   в Fasterflect.MethodExtensions.CallMethod(Object obj, String name, Object[] parameters)
   в Xpand.ExpressApp.Win.EditModelController.EditModelCore()

**Comment by krombipils** [comment]
I created a new issue on [HelloKitty fasterflect](https://github.com/HelloKitty/fasterflect/issues/6)

**Comment by krombipils** [comment]
@apobekiaris: your issue from july is still not answered on HelloKitty fasterflect, therefore I think this fork is not maintained anymore.

**Comment by apobekiaris** [comment]
it is fixed the bot will notify u soon

**Comment by krombipils** [comment]
You fixed it by removing the problematic call. Nevertheless Fasterflect.Netstandard is broken and probably unmaintained. Therefore I think that eXpand should not rely on it.

I'm also using Fasterflect in my own code. After upgrade of the eXpand libs, I had compilation errors, because methods are defined in Fasterflect and Fasterflect.Netstandard. I fixed the compilation issues by removing my custom reference to Fasterflect. But now, I have to deal with the problems in Fasterflect.Netstandard.
Not sure, if it is instead possible to use aliasing with package references instead...

**Comment by expand** [comment]
eXpand.lab release [19.1.502.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.2) includes commit that relate to this task:

* [EditModelController throws MissingMethodException when closing ModelEditor #489](https://github.com/eXpandFramework/eXpand.lab/commit/6a7d8cd33ecd68baabcf608e7d4f9807db902b87)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
> Nevertheless Fasterflect.Netstandard is broken and probably unmaintained

thnks for the comments, I do not think we have a serious issue for now it may be just a bug, all frameworks have bugs. Fasterflect even unmaintained offers unmatched functionality at least to my knowledge. If you have alternative suggestions feel free to share it with us.
