### ISSUE TITLE
Excel Importer Size constrain whne un

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#491]
Hi,

I have string fields set as Size(SizeAttribute.Unlimited) and when i Import data there is an error of size constrain. If  I set for example the Size(500) then it works.

![image](https://user-images.githubusercontent.com/41955268/62579073-1996bd00-b8a3-11e9-89ed-391be4d725e8.png)

BR
ISA

**Comment by apobekiaris** [comment]
hmm confused the property is already marked Unlimited

https://github.com/eXpandFramework/eXpand/blob/6deb9088ff3ea570123234ac7e18fe462d9fcbf6/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/BusinessObjects/FailedImportResult.cs#L19-L20

**Comment by isatahiri** [comment]
No no my issue is : 
my data is set as [Size(SizeAttribute.Unlimited)] and when i try to import it is thwors a error. 

It is like when the value is set to [Size(SizeAttribute.Unlimited)] the check does not go well. 

BR
ISA

**Comment by apobekiaris** [comment]
this answer did not help me understand better

**Comment by isatahiri** [comment]
I have a class with a string property : 
private string _DescriptionDE;
        [XafDisplayName("Beschreibung"), Size(SizeAttribute.Unlimited)]
        public string DescriptionDE
        {
            get { return _DescriptionDE; }
            set { SetPropertyValue("DescriptionDE", ref _DescriptionDE, value); }
        }
when i try to import data, not matter the lengh of my data. There is a error (Size constrain).

If if change this property to : 
private string _DescriptionDE;
        [XafDisplayName("Beschreibung"), Size(500)]
        public string DescriptionDE
        {
            get { return _DescriptionDE; }
            set { SetPropertyValue("DescriptionDE", ref _DescriptionDE, value); }
        }
Then it works. 

It looks that during the import and the check of the field, the attribute Size(SizeAttribute.Unlimited) is not evaluated. Could that be ? 

BR
ISA

**Comment by apobekiaris** [comment]
nope cannot this is xpo operation and respected from the ORM. Something else is the issue maybe spaces??

**Comment by isatahiri** [comment]
i will check that and let you know. Thanks for the tips. I also saw that in db side, the unlimited is a longtext in db and the size with fixed number is a varchar.

**Comment by apobekiaris** [comment]
oh it may be some kind of error on mysql size limits u should ask DX support about it. You should be able to repro it manually
