### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by nurbed** [eXpandFramework/eXpand#492]
**Describe the bug**
After updating to the 19.1.5 version the app hang on startup with this error:
"Exception occurs while initializing the 'Xpand.ExpressApp.ModelDifference.Win.ModelDifferenceWindowsFormsModule' module: RichEditControl"

**Comment by apobekiaris** [comment]
can u try to create a sample?

**Comment by apobekiaris** [comment]
nevermind I can repro it

**Comment by expand** [comment]
eXpand.lab release [19.1.502.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.3) includes commit that relate to this task:

* [ModelDifference: throws on startup #492 if ModelMapper not found installed](https://github.com/eXpandFramework/eXpand.lab/commit/3cc56ff6cc3e8bfdcdf9ddec5e476199992334d9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by nurbed** [comment]
Yeah!!! After the update everything works!
Thanks!

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
