### ISSUE TITLE
VersionConverter throws NullReference when project doesn't have DX references

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#493]
**Description**
We have a Utils project which only references eXpandLib and doesn't reference any DevExpress references, because we only use Xpand.Utils for this project. 
This fails since 19.1.501, because the ModelMapper is added to eXpandLib, which added the VersionConverter too.
The VersionConverter doesn't recognize the DevExpress version for projects that do not have DevExpress references and throws the exception `Exception calling "Match" with "3" argument(s): "Value can not be null"`

**Solution**
The solution would be to change the script or release the Utils project as a NuGet package.

**Work-around**
Add the `<DevExpressVersion>` element to the PropertyGroup in your .csproj

**Additional information**
Problem where this occurs, the $include variable is null because the `$packageReference` and the `$dxReferences` variables are both null.
https://github.com/eXpandFramework/DevExpress.XAF/blob/319d672212f8f8f8c2524bc4046ef1a72bf08f40/tools/Xpand.VersionConverter/Functions.ps1#L220-L221

.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xpand.VersionConverter" Version="1.0.34" />
  </ItemGroup>

</Project>
```

**Comment by expand** [comment]
eXpand.lab release [19.1.502.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.4) includes commit that relate to this task:

* [Move CustomizeASPxPopupController to System.Web #493](https://github.com/eXpandFramework/eXpand.lab/commit/fb593e98ecde1b0b1fc8559e14abbaa02d090553)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.7) includes commit that relate to this task:

* [Bump standalone packages #488 #493](https://github.com/eXpandFramework/eXpand.lab/commit/9b91ce6398dea96c3463984d9f8f237f050c7fa9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.8) includes commit that relate to this task:

* [Bump standalone packages #488 #493](https://github.com/eXpandFramework/eXpand.lab/commit/d1e196aa3bd4013e687f5bc1fd47c9a8fbbef3f6)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
