### ISSUE TITLE
Model editor fails to load when XpandSystemAspNetModule is used and 2 dx version installed

### ISSUE THREAD

**Issue by Ezeckiel2517** [eXpandFramework/eXpand#494]
I just updated eXpandSystemWeb module from 19.1.402 to 19.1.502 and now the model editor fails to load because it cannot resolves to dx dll. I have dx version 18.2 and 19.1 installed on my pc. Here is a sample app to reproduce.
[DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/3476938/DXApplication1.zip)

![image](https://user-images.githubusercontent.com/15835320/62622332-22f84780-b8ec-11e9-9b0a-64467807e194.png)

**Comment by apobekiaris** [comment]
I suggest u go for the latest lab version, in addition if possible please uninstall 18.2 version for now until this will be supported. Or try the XpandModelEditor it may work better.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Fails to load when multiple DX installations #494](https://github.com/eXpandFramework/DevExpress.XAF/commit/b406df2095fdecd787d7368212cd0815c954e960)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by Ezeckiel2517** [comment]
I've connected the nuget on nightly build but I think some other package are not yet updated.
Now I got this error:
Exception occurs while initializing the 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule' module: Method not found: 'System.IObservable`1<System.Reactive.Unit> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.ToUnit(System.IObservable`1<!!0>)'.

Here is the log
[Model.DesignedDiffs.log](https://github.com/eXpandFramework/eXpand/files/3486885/Model.DesignedDiffs.log)

**Comment by apobekiaris** [comment]
it might be I will bump all versions to make sure we are on the latest, all packages should be on a revision on next notification

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Bump version #494](https://github.com/eXpandFramework/DevExpress.XAF/commit/43858986013bc478edabf21ff5d9fd4c2a2676c8)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by Ezeckiel2517** [comment]
Good it is fixed.

**Comment by Ezeckiel2517** [comment]
I just test the 19.1.503 release and the latest nightly build. Got this new error when opening web model :
![image](https://user-images.githubusercontent.com/15835320/63120766-f938c380-bf70-11e9-86bc-961b78a91b7b.png)

**Comment by apobekiaris** [comment]
this is not the same stack so I doupt is the same issue, in any case I need more details as I do not see how to reproduce it.

**Comment by krombipils** [comment]
I'm getting the same error, when trying to open Model.xafml in XVideoRental.Win
![grafik](https://user-images.githubusercontent.com/8317504/63168897-bab90c80-c035-11e9-861d-41d6abb709bc.png)

**Comment by Ezeckiel2517** [comment]
The issue is related to windows privileges. I use Win 10 with UAT activated and the "Program Files" folder is protected. Somehow a process try to generate a file in that folder and get blocked with "Access Denied". If I start Visual Studio with elevated privileges, I can open the model editor without problem.

Suggestion : generate that file in the temp folder.

**Comment by apobekiaris** [comment]
thnks!

>Suggestion : generate that file in the temp folder.

not possible as the runtime needs to find it in path so the Mapper now generates in path

https://github.com/eXpandFramework/DevExpress.XAF/blob/bd2b812f48695136d66748bc3f1c7c25a5c3a4dc/src/Modules/ModelMapper/Services/TypeMapping/PublicMembers.cs#L59

must be something else, let me know if u find it b4 me

**Comment by apobekiaris** [comment]
hmmm apparently the design time path is the program files hmmm that should be it.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Use Temp directory as design time generation path #494](https://github.com/eXpandFramework/DevExpress.XAF/commit/da36c9ce6bc73518739027ce83415761305c86fe)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
see #518 now Xpand.VSIX needs to write in program files, I guess you have to add permissions for this folder or simply start VS a admin. If you have suggestions let me know please.

**Comment by apobekiaris** [comment]
if you do not have permissions the exception will be in VS output.

**Comment by Ezeckiel2517** [comment]
I have installed the nightly 19.1.503.4 and now it ask me to install Xpand.VSIX when I open the web model editor.
![image](https://user-images.githubusercontent.com/15835320/63447140-7c429980-c409-11e9-8950-c4ac1aad15b9.png)
Is there a nighlty VSIX to install? I don't think I can use the one that ship with the latest release.

**Comment by Ezeckiel2517** [comment]
I guess it is this one I should use [https://github.com/eXpandFramework/eXpand.lab/releases](url) ?

**Comment by apobekiaris** [comment]
yes thats the latest

**Comment by Ezeckiel2517** [comment]
On the build process, it tries to copy files to C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\DataDesign. Without the permission, Visual Studio close (or crash).

Do you think you can add a user option for the output folder so we can change the location to something we have full permissions? (maybe in that option window)
![image](https://user-images.githubusercontent.com/15835320/63453459-b6666800-c416-11e9-9a72-e587f96b23b9.png)

**Comment by Ezeckiel2517** [comment]
And using Administrator mode, the designer throw error
"Could not load file or assembly 'Xpand.XAF.Modules.ModelMapper, Version=1.1.38.0". I don't understand where it comes from, version installed is 1.1.38.5.

**Comment by apobekiaris** [comment]
>"Could not load file or assembly 'Xpand.XAF.Modules.ModelMapper, Version=1.1.38.0". I don't understand where it comes from, version installed is 1.1.38.5.

search your disk and remove all modelmapper

>Do you think you can add a user option for the output folder so we can change the location to something we have full permissions? (maybe in that option window)

I will add a messagebox to check if VS is elevated however this special folder cannot be changed, VS looks at it when probing for assembly resolution

**Comment by Ezeckiel2517** [comment]
Can you try to use the AppDomain.AssemblyResolve event to manually load the assembly without copying it in program files ? (ref [https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netframework-4.7.2](url))

Sample [https://stackoverflow.com/questions/5260404/resolve-assembly-references-from-another-folder](url)
I don't know if it works from the designer.

**Comment by apobekiaris** [comment]
design time is not the runtime, attaching to the event is tricky as it maybe out of time in addition designer does not know the actual bin path.

However first I need to evaluate why is that special dir such of a problem to u? 

Note that XAF also requires admin permissions for running EasyTest

**Comment by apobekiaris** [comment]
also this event has no value as it fires when assembly is not resolved which is not the problem here, but from where it is resolved is.

**Comment by apobekiaris** [comment]
so to make it crystal clear VS looks at this `DataDesign` dir and loads the assemblies from there without attempting other probes if not needed.

**Comment by apobekiaris** [comment]
>However first I need to evaluate why is that special dir such of a problem to u?

please clarify this

**Comment by Ezeckiel2517** [comment]
I'm not against running with admin permissions. It is sometimes required, for example when debugging with IIS (not the express). It's just not in the best practice because your app can now read/write everywhere and you won't be notice of permission problem until you deploy it in your test environment.

If it was it need than ok. But even with admin I can't make the designer to work.
It still try to load the wrong dll version "Could not load file or assembly 'Xpand.XAF.Modules.ModelMapper, Version=1.1.38.0". My reference are using 1.1.38.5.

I'll try to find which dll are referencing the wrong version.

**Comment by apobekiaris** [comment]
>It's just not in the best practice because your app can now read/write everywhere

why everywhere? how about u permission only the datadesign folder? it might not even need admin permission for VS  Let me know if u try it i might even add a PS function for it to make it user friendly

>1.1.38.0

probably this version exists or your devenv.exe path and VS tries to load from there remove it or search all your disks for this version and remove it to be sure

**Comment by Ezeckiel2517** [comment]
The problem with 2 DevExpress version installed is fixed.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.4) includes commit that relate to this task:

* [VSIX: Cancel build if VS is not elevated #549 #494](https://github.com/eXpandFramework/eXpand.lab/commit/ad5625d4c7ca92edd8b35108005da3c8b99ec6fc)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
