### ISSUE TITLE
The specified conversion is not valid.

### ISSUE THREAD

**Issue by joserussi** [eXpandFramework/eXpand#495]
Hi. Install version 19.1.502. I have always used the Xpand.ExpressApp.ImportWizard.
But now when I use it this error generates me

The specified conversion is not valid.

   in Xpand.ExpressApp.ImportWizard.Win.Wizard.ExcelImportWizard.InitializeComponent () in
   D: \ a \ 1 \ s \ Xpand \ Xpand.ExpressApp.Modules \ ImportWizard.Win \ Wizard \ ExcelImportWizard.designer.cs: line 32
   
   in Xpand.ExpressApp.ImportWizard.Win.Wizard.ExcelImportWizard..ctor (XPObjectSpace objectSpace, ITypeInfo typeInfo, ExcelImportWizardStringToPropertyMap propertyValueMapper)
   in D: \ a \ 1 \ s \ Xpand \ Xpand.ExpressApp.Modules \ ImportWizard.Win \ Wizard \ ExcelImportWizard.cs: line 61
   
   in Xpand.ExpressApp.ImportWizard.Win.Controllers.ImportWizViewController.ShowWizard (IObjectSpace objectSpace)
   in D: \ a \ 1 \ s \ Xpand \ Xpand.ExpressApp.Modules \ ImportWizard.Win \ Controllers \ ImportWizViewController.cs: line 22
   
   in Xpand.ExpressApp.ImportWizard.Controllers.ImportWizViewControllerBase.ImportAction_Execute (Object sender, SimpleActionExecuteEventArgs e)
   in D: \ a \ 1 \ s \ Xpand \ Xpand.ExpressApp.Modules \ ImportWizard \ Controllers \ ImportWizViewControllerBase.cs: line 27
   in DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore (Delegate handler, ActionBaseEventArgs eventArgs)

what should I do to fix it, thanks for your support

**Comment by apobekiaris** [comment]
transfered to https://github.com/eXpandFramework/eXpand/issues

**Comment by expand** [comment]
eXpand.lab release [19.1.502.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.4) includes commit that relate to this task:

* [ImportWizard: Fails to load #495](https://github.com/eXpandFramework/eXpand.lab/commit/12eff7fbab14d563aedeb9396515dbd11bac22d5)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
