### ISSUE TITLE
Help with ChooseDatabaseAtLogon functionality

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#496]
**Question**
I wanted to set the ChooseDatabaseAtLogon functionality properly, but I'm stuck on some things.

I currently added the XpandSecurityModule in a basic application to make sure the mistake is not in our application. This isn't really working out. I have been debugging it and it turns out that when logging in, the connection string isn't set eventhough i selected a connection string from the lookup listview.

My question is: how to do it the right way?

**Additional context**
I have made a simple demo to demonstrate this. I added a SQLite database already, so you can immediately test. The username is admin and there is no password.
[XafTestApp.zip](https://github.com/eXpandFramework/eXpand/files/3478387/XafTestApp.zip)

**Comment by apobekiaris** [comment]
u need a default connection string to be used unitl login (no db is created yet) and also change thisline

```cs
e.ObjectSpaceProviders.Add(new XPObjectSpaceProvider(new ConnectionStringDataStoreProvider(ConfigurationManager.ConnectionStrings["LogonDBServerDefault"].ConnectionString)));
```
```xml
<add name="LogonDBServerDefault" connectionString="Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\mssqllocaldb;Initial Catalog=SecurityTesterEasyTesta" />    
    <add name="ConnectionString" connectionString="Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\mssqllocaldb;Initial Catalog=SecurityTestera" />
    <add name="LogonDBServerDB1" connectionString="Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\mssqllocaldb;Initial Catalog=SecurityTesterEasyTest1a" />
    <add name="LogonDBServerDB2" connectionString="Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\mssqllocaldb;Initial Catalog=SecurityTesterEasyTest2a" />
```

**Comment by gerritmulder** [comment]
Alright, thanks. Clear answer.

**Comment by apobekiaris** [comment]
forgot to mention there is a win version for this controller

**Comment by gerritmulder** [comment]
I saw, but it didn't add anything to the question, so I left that out.
