### ISSUE TITLE
Could not load file or assembly "MapperWin637007813490379672"

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#497]
I Try Open publish version

Could not load file or assembly "MapperWin637007813490379672, Version = 1.1.34.0, Culture = neutral, PublicKeyToken = null" or one of their dependencies. Cannot find the specified file.

**Comment by apobekiaris** [comment]
cannot tell much as your post does not provide any repro details. I can tell the obvious that the mapping assembly is not found, from whom? when? also I can tell you are not on the latest version

```ps1
Find-XpandPackage *ModelMapper* All

Id                            Version
--                            -------
Xpand.XAF.Modules.ModelMapper 1.1.35.1
Xpand.XAF.Modules.ModelMapper 1.1.35
```

**Comment by genetsEvgen** [comment]
In last version Xpand 
Xpand.XAF.Modules.ModelMapper 1.1.34

**Comment by apobekiaris** [comment]
you can update manually from nuget until next release. Note that versions with revision e.g. come from the lab https://xpandnugetserver.azurewebsites.net/nuget

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
