### ISSUE TITLE
Middle Tier Xpand.Excellimporter

### ISSUE THREAD

**Issue by SliimTechnologies** [eXpandFramework/eXpand#498]
Hi
i want to integrate ExcelImporter but  i get this error on stating the win project.

"Object reference not set to an instance of an object.

   à Xpand.ExpressApp.ExcelImporter.Win.Services.AutoImportService.<>c__DisplayClass2_0.<Connect>b__15(Exception exception) dans D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ExcelImporter.Win\Services\AutoImportService.cs:ligne 68
   à System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   à System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   à System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   à System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
   à System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Subjects.Subject`1.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.ThrowImmediate`1.Run(IObserver`1 observer)
   à System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   à System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   à System.Reactive.Linq.ObservableImpl.Using`2._.Run(Using`2 parent)
   à System.Reactive.Linq.ObservableImpl.Using`2.Run(_ sink)
   à System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple)
   à System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple)
   à System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   à System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   à System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
   à System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   à System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   à System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.SubscribeInner(IObservable`1 inner)
   à System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.HalfSerializer.ForwardOnNext[T](ISink`1 sink, T item, Int32& wip, Exception& error)
   à System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnNext(TSource value)
   à System.Reactive.Subjects.Subject`1.OnNext(T value)
   à System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à DevExpress.ExpressApp.XafApplication.OnSetupComplete()
   à DevExpress.ExpressApp.Win.WinApplication.OnSetupComplete()
   à DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters)
   à DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   à DevExpress.ExpressApp.Win.WinApplication.<>n__0(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   à DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()"

How can i resolve it?
Thanks

**Comment by apobekiaris** [comment]
I do not see a way that leads in such an exception, please provide a sample.

**Comment by SliimTechnologies** [comment]
let me tell you how i did before get this error, i use Middle Tiers XAf Application
1- install XpandExcelImporter from nuget version 19.1.402.
2- i insert module XpandExcelImporterWin for WinModuleapp and XpandExcelImporter in WinModule.
3- Debug my application provide this error.
If i did a mistake pls telle me or give me link to leran how integrate it in XAF application correctly.
Excuse my english iam francophone.
Thanks!

**Comment by apobekiaris** [comment]
>Excuse my english iam francophone.

if you think your post needs more details then use google to translate.

I do not think the problem exists in latest version.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
