### ISSUE TITLE
Install-Xpand function

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#499]
I try
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  #-Version '19.1.502.6' -SkipGac -InstallationPath 'YOURPATH'"

but download version 19.1.502.0

**Comment by apobekiaris** [comment]
actually the
>#-Version '19.1.502.6' -SkipGac -InstallationPath 'YOURPATH'

the # in powerhell denotes comment, so it wont execute unless u remove it.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
