### ISSUE TITLE
ScheduledWorkflowLaunchHistory very slow when large collection

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#500]
Hi Tolis

We are using the Workflow Service with Scheduled Workflows. Our customers have workflows that run almost every minute. This makes te lauch history table very large. And becuase of this editing a workflow is very slow because it seems that every record of launch history is getting edited when the schedule workflow definition is edited. This is because this collection is Aggregated. Here you can see the Association:
` [Association]

        [CollectionOperationSet(AllowAdd = false,AllowRemove = false), Aggregated]

        public XPCollection<ScheduledWorkflowLaunchHistory> LaunchHistoryItems => GetCollection<ScheduledWorkflowLaunchHistory>("LaunchHistoryItems");`

Can you please change this so it will not update every record from launch history when updating scheduled definition?

Thanks,
Jacob

**Comment by expand** [comment]
eXpand.lab release [19.1.502.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.13) includes commit that relate to this task:

* [ScheduledWorkflowLaunchHistory very slow when large collection #500](https://github.com/eXpandFramework/eXpand.lab/commit/e77be370c11a0f4a6b763d915287c220b22a7640)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
