### ISSUE TITLE
Can't open model editor in runtime

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#503]
**Can't open MDO_Detailview**
I'm using tabbed interface and Detailview Delayed initialization

it happened before.. I had to disable richedit controller, but now it was refactored...

xERP.Win.exe Error: 0 : 10.08.19 10:09:29.303	no context	================================================================================
The error occurred:

	Type:       ObjectCreatingException
	Message:    Unable to create an instance of the "Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditWinPropertyEditor" type.
Reason: "Referencia a objeto no establecida como instancia de un objeto."
	Data:       0 entries
	Stack trace:

   en DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   en DevExpress.ExpressApp.Editors.EditorsFactory.CreateViewItem(Type viewItemType, String viewItemId, Boolean checkConstructor, IModelNode modelViewItem, Type objectType, XafApplication application, IObjectSpace objectSpace)
   en DevExpress.ExpressApp.Editors.EditorsFactory.CreateDetailViewEditor(Boolean needProtectedContent, IModelMemberViewItem modelViewItem, Type objectType, XafApplication application, IObjectSpace objectSpace)
   en DevExpress.ExpressApp.Editors.EditorsFactory.CreateDetailViewEditor(Boolean needProtectedContent, IModelViewItem modelViewItem, Type objectType, XafApplication application, IObjectSpace objectSpace)
   en DevExpress.ExpressApp.ObjectView.CreateItem(IModelViewItem model)
   en Xpand.ExpressApp.XpandDetailView.CreateItem(IModelViewItem info)
   en DevExpress.ExpressApp.CompositeView.LoadModelCore()
   en DevExpress.ExpressApp.ObjectView.LoadModelCore()
   en DevExpress.ExpressApp.View.LoadModel()
   en DevExpress.ExpressApp.View.SetModel(IModelView model)
   en Xpand.ExpressApp.ViewFactory.CreateDetailView(XafApplication xafApplication, String viewId, IObjectSpace objectSpace, Object obj, Boolean isRoot, Boolean enableDelayedObjectLoading)
   en Xpand.ExpressApp.SystemModule.XpandSystemModule.ApplicationOnDetailViewCreating(Object sender, DetailViewCreatingEventArgs args)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       NullReferenceException
			Message:    Referencia a objeto no establecida como instancia de un objeto.
			Data:       0 entries
			Stack trace:

   en Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditWinPropertyEditor..ctor(Type objectType, IModelMemberViewItem model)
			InnerException is null

--------------------------------------------------------------------------------

**Comment by vimarx** [comment]
it was solved by changing the xmlcontent editor

**Comment by expand** [comment]
eXpand.lab release [19.1.502.9](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.9) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/801728c32f3df8e189d68dc589af4a82b13891a5)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.10](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.10) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/2c6041db17458b85c36e0427d4803ef2b4da6b75)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.11](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.11) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/4e2b726fc8ef99632c38f65d8381c9de73590e35)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
works ok!!
