### ISSUE TITLE
also I can't disable ModelMapper as suggested in

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#506]
also I can't disable ModelMapper as suggested in
((Xpand.XAF.Modules.ModelMapperModule) Application.Modules.FindModule(typeof(Xpand.XAF.Modules.ModelMapperModule))).Unload();

because out of memory occurs before Setup completes

_Originally posted by @vimarx in https://github.com/eXpandFramework/eXpand/issues/502#issuecomment-520168927_

**Comment by apobekiaris** [comment]
this is now implemented check package docs 
https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/src/Modules/ModelMapper#issues-debugging-troubleshooting

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
