### ISSUE TITLE
Duplicate type name within an assembly 

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#507]
Hi,

I deployed my asp into in iis 10 and when i run the web app, i have an error 

[ArgumentException: Duplicate type name within an assembly.]
   System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType) +14730529
   System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType) +63
   System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType) +162
   System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent) +204
   Xpand.Source.Extensions.XAF.ApplicationModulesManager.ApplicationModulesManagerExtensions.NewControllerType(String id) +98
   Xpand.Source.Extensions.XAF.ApplicationModulesManager.ApplicationModulesManagerExtensions.RegisterAction(ApplicationModulesManager applicationModulesManager, String id, Func`2 actionBase) +247
   Xpand.XAF.Modules.MasterDetail.MasterDetailService.RegisterActions(ApplicationModulesManager applicationModulesManager) +170
   Xpand.XAF.Modules.MasterDetail.MasterDetailService.Connect(ApplicationModulesManager applicationModulesManager, XafApplication application) +269
   Xpand.XAF.Modules.MasterDetail.MasterDetailModule.Setup(ApplicationModulesManager moduleManager) +36
   Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance) +189

[InvalidOperationException: Exception occurs while initializing the 'Xpand.XAF.Modules.MasterDetail.MasterDetailModule' module: Duplicate type name within an assembly.]
   Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance) +710
   SetupModules_Patch1(ApplicationModulesManager ) +32
   DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo) +365
   DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security) +344
   DevExpress.ExpressApp.XafApplication.Setup() +161
   PME_Affaire.Web.Global.Session_Start(Object sender, EventArgs e) in C:\Users\isata\Documents\PME Projects\PME_Affaire\PME_Affaire.Web\Global.asax.cs:46
   System.Web.SessionState.SessionStateModule.CompleteAcquireState() +364
   System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) +1226
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +625
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128

From visual studio it work good.

Does that talk to you ? 

i use the eXpand 19.1.502.8

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [MasterDetail: Production error when registering MasterDetailSave action  #507](https://github.com/eXpandFramework/DevExpress.XAF/commit/115b8b0fbce0a072fff311a8dadb859486de626c)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
