### ISSUE TITLE
Deploy Window XAF app - unsuccessfully - FileIO not found

### ISSUE THREAD

**Issue by david0villa** [eXpandFramework/eXpand#508]
**Describe the bug**
After upgrading DevExpress Version 19.1.502 - the latest version. Whenever opening the main program,the system keeps crashing with below  error message. Trying several ways to see what missed but no luck.

Problem Event Name:	CLR20r3
  Problem Signature 01:	XXXAAA.exe
  Problem Signature 02:	3.1.0.0
  Problem Signature 03:	5d50d236
  Problem Signature 04:	Xpand.ExpressApp.Validation
  Problem Signature 05:	19.1.502.0
  Problem Signature 06:	90696af8
  Problem Signature 07:	2
  Problem Signature 08:	6
  Problem Signature 09:	System.TypeInitialization
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	3081
  Additional Information 1:	54dc
  Additional Information 2:	54dc41a1bae9e8fb013d2e20d2d6446f
  Additional Information 3:	7d39
  Additional Information 4:	7d39cbd266c43554a70c44f361125821

**To Reproduce**
1- Open main program
2- System crashed

**Expected behavior**
Hope to open system any problems

**Screenshots**

**Desktop (please complete the following information):**
Window

**Comment by apobekiaris** [comment]
although i cannot directly relate your post to any opne case the 19.1.502 is buggy try a lab version after 19.1.502.11

**Comment by david0villa** [comment]
Hi,

Thank you for your prompt response. Can you please teach me how can I try with lab version ?
I used command Install-Xpand last time.

**Comment by david0villa** [comment]
Sorry, please ignore my previous comment. I have just worked out the lab version.

**Comment by david0villa** [comment]
Hi,

Tried with latest lab version 19.1.502.13 but still not work. Still did not figure out the reason. Had to roll back to version 19.1.402 in order to keep working

**Comment by apobekiaris** [comment]
unfortunately the info u provided is not enpough to guess what is the problem, though numerous problems that I consider related are now resolved. next time u try to upgrade provide at least the log

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
