### ISSUE TITLE
VSIX Model editor dont support multiple xafmls per project anymore

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#509]
**Describe the bug**
Previously it supported the following structure
![image](https://user-images.githubusercontent.com/226800/62884099-0e60e880-bd0c-11e9-8f05-72af4b74286a.png)

now VSIX model windows show only one
Image
![image](https://user-images.githubusercontent.com/226800/62884194-48ca8580-bd0c-11e9-8b98-8ca080dc8447.png)

**Comment by apobekiaris** [comment]
fixed in latest lab

**Comment by expand** [comment]
eXpand.lab release [19.1.602.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.5) includes commit that relate to this task:

* [XpandModelEditor fails to discover additional xafml files #509](https://github.com/eXpandFramework/eXpand.lab/commit/4714a7886ffed1ebac53e46a8e79448a48666b79)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
