### ISSUE TITLE
null reference in web Hyperlinkproperty editor

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#511]
atttached repro project and stack

The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandListView, ID:DomainObject1_ListView' view to XpandWebWindow:
Referencia a objeto no establecida como instancia de un objeto.
	Data:       0 entries
	Stack trace:

   en DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   en DevExpress.ExpressApp.Web.ShowViewStrategy.ShowViewInCurrentWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   en DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   en DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   en DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   en DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   en DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       NullReferenceException
			Message:    Referencia a objeto no establecida como instancia de un objeto.
			Data:       0 entries
			Stack trace:

   en Xpand.ExpressApp.Web.PropertyEditors.HyperLinkPropertyEditor.SetupHyperLink(Object editor)
   en Xpand.ExpressApp.Web.PropertyEditors.HyperLinkPropertyEditor.ReadViewModeValueCore()
   en DevExpress.ExpressApp.Web.Editors.WebPropertyEditor.ReadValueCore()
   en DevExpress.ExpressApp.Editors.PropertyEditor.ReadValue()
   en DevExpress.ExpressApp.Web.Editors.WebPropertyEditor.control_Init(Object sender, EventArgs e)
   en System.Web.UI.Control.OnInit(EventArgs e)
   en DevExpress.Web.ASPxWebControlBase.OnInit(EventArgs e)
   en DevExpress.Web.ASPxDataWebControlBase.OnInit(EventArgs e)
   en System.Web.UI.Control.InitRecursive(Control namingContainer)
   en System.Web.UI.Control.InitRecursive(Control namingContainer)
   en System.Web.UI.Control.InitRecursive(Control namingContainer)
   en System.Web.UI.Control.AddedControl(Control control, Int32 index)
   en System.Web.UI.ControlCollection.Add(Control child)
   en DevExpress.Web.Internal.ClientIDHelper.TemplateHierarchyContainer.CreateChildControls()
   en System.Web.UI.Control.EnsureChildControls()
   en DevExpress.Web.Internal.ClientIDHelper.TemplateHierarchyContainer.OnInit(EventArgs e)
   en System.Web.UI.Control.InitRecursive(Control namingContainer)
   en System.Web.UI.Control.AddedControl(Control control, Int32 index)
   en System.Web.UI.ControlCollection.Add(Control child)
   en DevExpress.Web.Internal.ClientIDHelper.AddTemplateContainerToHierarchy(Control parent, TemplateContainerBase container, String containerID)
   en DevExpress.Web.Internal.GridRenderHelper.AddTemplateToControl(Control destination, ITemplate template, GridBaseTemplateContainer templateContainer, TemplateContainerCollection collection)
   en DevExpress.Web.Rendering.GridViewRenderHelper.AddDataItemTemplateControl(Int32 visibleIndex, GridViewDataColumn column, Control templateContainer)
   en DevExpress.Web.Rendering.GridViewTableDataCell.CreateControlHierarchy()
   en DevExpress.Web.Internal.InternalTableCell.CreateChildControls()
   en System.Web.UI.Control.EnsureChildControls()
   en DevExpress.Web.Internal.InternalTableCell.DevExpress.Web.Internal.IWebControl.EnsureChildControls()
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Boolean skipContentContainers)
   en DevExpress.Web.ASPxWebControlBase.EnsureChildControlsRecursive(Control control, Boolean skipContentContainers)
   en DevExpress.Web.ASPxWebControlBase.EnsureChildControlsRecursive(Control control)
   en DevExpress.Web.ASPxWebControlBase.CreateChildControls()
   en System.Web.UI.Control.EnsureChildControls()
   en DevExpress.Web.ASPxWebControlBase.EnsureChildControls()
   en DevExpress.Web.ASPxWebControlBase.DevExpress.Web.Internal.IWebControl.EnsureChildControls()
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Predicate`1 skipControlCondition)
   en DevExpress.Web.Internal.RenderUtils.EnsureChildControlsRecursive(Control control, Boolean skipContentContainers)
   en DevExpress.Web.ASPxWebControlBase.EnsureChildControlsRecursive(Control control, Boolean skipContentContainers)
   en DevExpress.Web.ASPxWebControlBase.EnsureChildControlsRecursive(Control control)
   en DevExpress.Web.ASPxWebControlBase.CreateChildControls()
   en DevExpress.Web.ASPxWebControl.CreateChildControls()
   en System.Web.UI.Control.EnsureChildControls()
   en DevExpress.Web.ASPxWebControlBase.EnsureChildControls()
   en DevExpress.Web.ASPxDataWebControlBase.DataBindInternal()
   en DevExpress.Web.ASPxWebControl.DataBind()
   en DevExpress.ExpressApp.Web.Editors.ASPx.ASPxGridListEditor.DataBind()
   en DevExpress.ExpressApp.Web.Editors.ASPx.ASPxGridListEditor.grid_Init(Object sender, EventArgs e)
   en System.EventHandler.Invoke(Object sender, EventArgs e)
   en System.Web.UI.Control.OnInit(EventArgs e)
   en DevExpress.Web.ASPxWebControlBase.OnInit(EventArgs e)
   en DevExpress.Web.ASPxDataWebControlBase.OnInit(EventArgs e)
   en DevExpress.Web.ASPxGridBase.OnInit(EventArgs e)
   en System.Web.UI.Control.InitRecursive(Control namingContainer)
   en System.Web.UI.Control.InitRecursive(Control namingContainer)
   en System.Web.UI.Control.AddedControl(Control control, Int32 index)
   en System.Web.UI.ControlCollection.Add(Control child)
   en DevExpress.ExpressApp.Web.Controls.ViewSiteControl.view_ControlsCreated(Object sender, EventArgs e)
   en System.EventHandler.Invoke(Object sender, EventArgs e)
   en DevExpress.ExpressApp.View.OnControlsCreated()
   en Xpand.ExpressApp.XpandListView.OnControlsCreated()
   en DevExpress.ExpressApp.View.CreateControls()
   en DevExpress.ExpressApp.Web.Controls.ViewSiteControl.SetView(View view)
   en DevExpress.ExpressApp.Web.Templates.BaseXafPage.SetView(View view)
   en DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   en DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
			InnerException is null
[repro.zip](https://github.com/eXpandFramework/eXpand/files/3499591/repro.zip)

**Comment by expand** [comment]
eXpand.lab release [19.1.503.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.503.1) includes commit that relate to this task:

* [null reference in web Hyperlinkproperty editor #511](https://github.com/eXpandFramework/eXpand.lab/commit/e5afa778bc15d12080ac31347a09fae6d96e84cb)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
