### ISSUE TITLE
MissingMemberException before first load XpandCategorizedListEditor (after migration to 19.1.503.0)

### ISSUE THREAD

**Issue by NejmiRiseUp** [eXpandFramework/eXpand#512]
Hi 
after migration to 19.1.503.0 , a error occured  before first load a CategorizedListView with XpandCategorizedListEditor .

**InnerException:**

			Type:       MissingMemberException
			Message:    No match for property with name MainView and flags Instance | NonPublic | Public | Static on type DevExpress.XtraEditors.SidePanelContainer.
			Data:       0 entries
			Stack trace:

   à Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo)
   à Fasterflect.Emitter.MemberGetEmitter.CreateDelegate()
   à Fasterflect.Emitter.BaseEmitter.GetDelegate()
   à Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name, Flags bindingFlags)
   à Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name)
   à Fasterflect.PropertyExtensions.GetPropertyValue(Object obj, String name)
   à Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetViewControl(PredefinedMap predefinedMap, CompositeView view, String model)
   à Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindData(ValueTuple`3 data)
   à System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   à System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   à System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   à System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
   à System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Sink`2.OnError(Exception error)
   à System.Reactive.Sink`1.ForwardOnError(Exception error)
   à System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.IdentitySink`1.OnNext(T value)
   à System.Reactive.Subjects.Subject`1.OnNext(T value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.IdentitySink`1.OnNext(T value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   à System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   à System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
   à System.Reactive.Subjects.Subject`1.OnNext(T value)
   à System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   à System.EventHandler.Invoke(Object sender, EventArgs e)
   à DevExpress.ExpressApp.View.OnControlsCreated()
   à Xpand.ExpressApp.XpandListView.OnControlsCreated() dans D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\XpandListView.cs:ligne 35
   à DevExpress.ExpressApp.View.CreateControls()
   à DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   à DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   à DevExpress.ExpressApp.Win.Templates.ViewSiteManager.OnViewChanged()
   à DevExpress.ExpressApp.Win.Templates.ViewSiteManager.SetView(View view)
   à AcurTime.Module.Win.LightStyleMainRibbonForm1.IFrameTemplate_SetView(View view) dans e:\AcurSoft\AcurTime_4.0\AcurTime.Module.Win\LightStyleMainRibbonForm1.vb:ligne 130
   à DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   à DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)

**Comment by apobekiaris** [comment]
please provide a sample that demonstrates the problem

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by apobekiaris** [comment]
provide a sample so I can research it
