### ISSUE TITLE
help for solving "Operation could destabilize the runtime."

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#513]
Hi Tolis,
I'm finding this exception in several customer's logs, also I found a similar issue in DX, could you give me some clues for debugging this issue?

https://www.devexpress.com/Support/Center/Question/Details/T806180/operation-could-destabilize-the-runtime-how-to-debug

System.Security.VerificationException: La operación no puede desestabilizar el runtime.
en CreateNestedFrame_Patch1(XafApplication viewItem, ViewItem context, TemplateContext view, View )
en DevExpress.ExpressApp.Win.Editors.LookupEdit.CreatePopupForm()
en DevExpress.XtraEditors.PopupBaseEdit.GetPopupFormCore()
en DevExpress.XtraEditors.PopupBaseEdit.GetPopupForm()
en DevExpress.XtraEditors.PopupBaseEdit.DoShowPopup()
en DevExpress.XtraEditors.PopupContainerEdit.DoShowPopup()
en DevExpress.ExpressApp.Win.Editors.LookupEdit.DoShowPopup()
en DevExpress.XtraEditors.PopupBaseEdit.ShowPopup()
en DevExpress.XtraEditors.PopupContainerEdit.ShowPopup()
en DevExpress.XtraEditors.PopupBaseEdit.ActionShowPopup(EditorButtonObjectInfoArgs buttonInfo)
en DevExpress.XtraEditors.PopupContainerEdit.OnDefaultPressButton(EditorButtonObjectInfoArgs buttonInfo)
en DevExpress.XtraEditors.PopupBaseEdit.OnPressButton(EditorButtonObjectInfoArgs buttonInfo)
en DevExpress.XtraEditors.ButtonEdit.OnMouseDown(MouseEventArgs e)
en DevExpress.XtraEditors.PopupBaseEdit.OnMouseDown(MouseEventArgs e)
en System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
en System.Windows.Forms.Control.WndProc(Message& m)
en DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
en DevExpress.XtraEditors.TextEdit.WndProc(Message& msg)
en DevExpress.XtraEditors.PopupBaseEdit.WndProc(Message& msg)
en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
19.1.0715.10
DevExpress.ExpressApp.NestedFrame CreateNestedFrame_Patch1(DevExpress.ExpressApp.XafApplication, DevExpress.ExpressApp.Editors.ViewItem, DevExpress.ExpressApp.TemplateContext, DevExpress.ExpressApp.View)
en CreateNestedFrame_Patch1(XafApplication viewItem, ViewItem context, TemplateContext view, View )
en DevExpress.ExpressApp.Win.Editors.LookupEdit.CreatePopupForm()
en DevExpress.XtraEditors.PopupBaseEdit.GetPopupFormCore()
en DevExpress.XtraEditors.PopupBaseEdit.GetPopupForm()
en DevExpress.XtraEditors.PopupBaseEdit.DoShowPopup()
en DevExpress.XtraEditors.PopupContainerEdit.DoShowPopup()
en DevExpress.ExpressApp.Win.Editors.LookupEdit.DoShowPopup()
en DevExpress.XtraEditors.PopupBaseEdit.ShowPopup()
en DevExpress.XtraEditors.PopupContainerEdit.ShowPopup()
en DevExpress.XtraEditors.PopupBaseEdit.ActionShowPopup(EditorButtonObjectInfoArgs buttonInfo)
en DevExpress.XtraEditors.PopupContainerEdit.OnDefaultPressButton(EditorButtonObjectInfoArgs buttonInfo)
en DevExpress.XtraEditors.PopupBaseEdit.OnPressButton(EditorButtonObjectInfoArgs buttonInfo)
en DevExpress.XtraEditors.ButtonEdit.OnMouseDown(MouseEventArgs e)
en DevExpress.XtraEditors.PopupBaseEdit.OnMouseDown(MouseEventArgs e)
en System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
en System.Windows.Forms.Control.WndProc(Message& m)
en DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
en DevExpress.XtraEditors.TextEdit.WndProc(Message& msg)
en DevExpress.XtraEditors.PopupBaseEdit.WndProc(Message& msg)
en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by apobekiaris** [comment]
this method injects instructions to create for e.g. an event after the CreateNestedFrame method, unless I have a way to repro the problem I cannot suggest anything, similar approaches are used through out the framework.

**Comment by apobekiaris** [comment]
harmony is used for injecting the instruction on this method
https://github.com/pardeike/Harmony
fasterflect does a similar injection as well but not relates to this method

**Comment by apobekiaris** [comment]
#514 maybe related

**Comment by apobekiaris** [comment]
i would also recommend to go higher in the .NET framework version >=4.7.2 on the client machines that suffered if possible and report if u can still reproduce it.

**Comment by gerritmulder** [comment]
@vimarx i made that ticket and the solution i found handy was to make a custom implementation for the method that is last called, in this case LookupEdit.CreatePopupForm().
Then get the source code and find that method. Put the calls that the method in source code is making into the custom implementation so you know where it fails and usually it gives a more specific error. You can also make a unit test for that problem like we did.

**Comment by apobekiaris** [comment]
so to my understanding this is can be reproduced? can u share details on how to?

**Comment by gerritmulder** [comment]
This error isn't very specific and can occur in every possible way. In our solution it usually happens when starting up, for example we had a controller configured wrong which gave an error. The method it failed on was WinShowViewStrategyBase.CreateWindow. I looked in the source code and made a custom implementation for ShowViewStrategyBase where I created the WinWindow for the WinApplication.MainWindow manually.

Example:
```
public class ShowViewStrategy : WinShowViewStrategyBase
{
    public ShowViewStrategy(XafApplication application) : base(application) { }

    protected override WinWindow CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, bool isMain)
    {
        if (isMain)
        {
            // For accessing the ControllersManager in your application
            // public new ControllersManager ControllersManager => base.ControllersManager;
            var controllers = (Application as ICustomApplication).ControllersManager
                .CreateControllers(typeof(Controller), Application.Model, parameters.CreatedView);
            for (int i = controllers.Count - 1; i >= 0; i--)
                if (typeof(DialogController).IsAssignableFrom(controllers[i].GetType()))
                    controllers.RemoveAt(i);

            if (parameters.Controllers != null)
                controllers.AddRange(parameters.Controllers);

            foreach (var controller in controllers)
                controller.Application = Application;

            return new WinWindow(Application, TemplateContext.ApplicationWindow, controllers, isMain, true);
        }
        else
            return base.CreateWindow(parameters, showViewSource, isMain);
    }

    protected override UIType GetUIType() => UIType.TabbedMDI;
}
```

Although when trying to mime the error in a clean XAF application, I get the error directly without having to use a custom implementation. 
For this error it's just a case of collecting solutions like above and make proper unit tests of them, this helps you catch these errors easier. Code in big business applications isn't usually the cleanest, so you can't prevent these errors.

**Comment by apobekiaris** [comment]
thnks for the update but still hard to understand what to blame

>Although when trying to mime the error in a clean XAF application

can u post this sample?

**Comment by gerritmulder** [comment]
I'd say, not sure tho, that it's not Xpand causing the error.
The sample is just a clean application with the code above, so it doesn't do anything.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
