### ISSUE TITLE
eXpandWin nuget package has wrong dependencies

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#515]
eXpandWin nuget package has wrong dependencies, see attached image, e.g. IO.Win is wrong. Should be eXpandIOWin
![grafik](https://user-images.githubusercontent.com/8317504/63161241-e29d7580-c01f-11e9-91f6-744637c36719.png)

**Comment by apobekiaris** [comment]
I am not sure how you got this, the VS Nuget Package Manager does not report such dependencies.

![image](https://user-images.githubusercontent.com/159464/63165698-da036a00-c034-11e9-8f25-5b20c65f6665.png)

**Comment by krombipils** [comment]
Your screenshot shows the wrong package. I tried to download eXpandWin, not eXpandSystemWin.

**Comment by expand** [comment]
eXpand.lab release [19.1.503.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.503.3) includes commit that relate to this task:

* [Nuget platform package containers dependencies are wrong #515](https://github.com/eXpandFramework/eXpand.lab/commit/b70fc088602bfde2647a431c91b3276059f369f4)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Fixed. Thank you!
