### ISSUE TITLE
ModelMapper module pollutes the user model with ColumnSummaryItem nodes.

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#516]
I attached a screencast demonstrating the issue in XVideoRental:
[Aufnahme #40.zip](https://github.com/eXpandFramework/eXpand/files/3509257/Aufnahme.40.zip)

ApplyModelCore() of DevExpress.ExpressApp.Editors.ColumnWrapperModelSynchronizer creates ColumnSummaryItem for all columns, as soon as a listview is opened. This pollutes the model with useless nodes. The SummaryItems seems to be created by the ModelMapper module.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Do_Not_Map_Properties_Marked_With_DesignerSerialization_Hidden #516](https://github.com/eXpandFramework/DevExpress.XAF/commit/086b5027d8f078ffd8612c44c90f9628a812e57d)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Fixed. Thank you!
