### ISSUE TITLE
How to Get Started Excel Importer

### ISSUE THREAD

**Issue by dwlandry** [eXpandFramework/eXpand#517]
Can you please provide a quick walk-through on what I need to do to get started with Excel Importer?  I am using XAF Winforms and I'm not sure what I need to do to include this in my project.  Do I use Nuget to add ExcelImporter to Project.Module, then use Nuget to add ExcelImporter.Win to Project.WinModule?  I notice that this adds a bunch of dependencies.
I'm not sure what to do after this? 

Thank you for taking the time to help guide me in the right direction.

**Comment by dwlandry** [comment]
Ok. Sure enough as soon as I post this I get it figured out. Here is what I did:

- Add ExcelImporter.Win to Project.WinModule.

- Received compile error stating to add reference to Xpand.Persistent.BaseImpl to your front end project and set its Copy Local=true.  So I added this reference to Project.Win and voila!  It works!

**Comment by apobekiaris** [comment]
yeah anything you know about XAF applies here, in addition most the registration of the platform agnostic module if exists is optional if there is a platform dependent module. The platform dependent will register the agnostic. For the rest there will be guidance as you proceed e.g. the BaseImpl case.

In any case feel free to post on anything.
