### ISSUE TITLE
VS ModelEditor: Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.ToUnit not found in 19.1.503.3

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#518]
The VS ModelEditor does not work (again) after I updated to 19.1.503.3. 

    Exception occurs while initializing the 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule' module: Methode nicht gefunden: "System.IObservable`1<System.Reactive.Unit> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.ToUnit(System.IObservable`1<!!0>)

VS also added a Binding Redirect for Xpand.XAF.Modules.Reactive to fix issues between 1.2.46.4 and 1.2.46.1

**Comment by apobekiaris** [comment]
i cannot tell how to repro it? from which version u upgrade?

**Comment by krombipils** [comment]
I upgraded from 19.1.503.1.
Could you please try to repro it with the modified XVideoRental project. I replaced some dll references with PackageReference to eXpand 19.1.503.3. When I try to open Model.DesignedDiffs.xafml of Module.Win, I get the MissingMethodException
[XVideoRental.zip](https://github.com/eXpandFramework/eXpand/files/3516220/XVideoRental.zip)

**Comment by apobekiaris** [comment]
I reproduced the issue and update the CI process with guard code to avoid it the same mistake in the future.

in addition I worked on the ModelMapper dependency issue. The problem actually is that VS gets confused on the location of the assemblies when design time as reflection is used to load them and not direct references. For this reason from next minor the `Xpand.VSIX` installation will be mandatory, the module will check and throw if not. The plugin will detect if ModelMapper is installed and will copy all files to a special directory which VS probes for assemblies.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: CheckXpandVSIXInstalled #518](https://github.com/eXpandFramework/DevExpress.XAF/commit/602a5e534719b29872c3b22bb01cf5733bdf1a1e)
* [Bump unchanged reactive modules version when reactive module changed #518](https://github.com/eXpandFramework/DevExpress.XAF/commit/57266a61d0394f43598107710b6b050a706f6f88)
* [Guard DevExpress build version #518](https://github.com/eXpandFramework/DevExpress.XAF/commit/2288bf7a7797434f927074eb88d9287440d305f2)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.503.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.503.4) includes commit that relate to this task:

* [VSIX: Copy to CommonExtensions\DataDesign directory on build when ModelMapper #518](https://github.com/eXpandFramework/eXpand.lab/commit/8d98dcd4e76025535775f31c8e4a87d409441cab)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
ModelEditor seems to be working fine now. Thank you!
