### ISSUE TITLE
Error starting production web site with xpand 19.1.503.0

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#519]
Access denied error when starting a website (under non-admin account), deployed with xcopy (no GAC install)
after adding explicit permission to user folder (not required in the previous version) a copy of netstandard.dll appears on c:\users\<username>\appdata\temp\

================================================================================
The error occurred:

	Type:       TypeInitializationException
	Message:    Se produjo una excepción en el inicializador de tipo de 'Xpand.Persistent.Base.General.XpandModuleBase'.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   en PresolicitudWebAspApplication..ctor()
   en Global.Session_Start(Object sender, EventArgs e)
   en System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
   en System.Web.SessionState.SessionStateModule.CompleteAcquireState()
   en System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   en System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       UnauthorizedAccessException
			Message:    **Acceso denegado a la ruta de acceso 'C:\Users\web\AppData'**.
			Data:       0 entries
			Stack trace:

   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   en System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   en System.IO.Directory.CreateDirectory(String path)
   en Xpand.Persistent.Base.General.XpandModuleBase..cctor()
			InnerException is null

**Comment by apobekiaris** [comment]
netstandard is now stored at `$@"{Path.GetTempPath()}\\netstandard"` you can add it there manually to avoid modifying the permissions

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
