### ISSUE TITLE
Breaking change: TreeList editor raises an exception when the default is set to server mode

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#520]
attached solution fails with "not supported exception" , the previous version worked properly

steps
1- try with a non-xpand solution with treelisteditor and default server mode option set to on -> OK
2 - Add xpand win treeeditor module -> exception

[Solution4.zip](https://github.com/eXpandFramework/eXpand/files/3529818/Solution4.zip)

**Comment by expand** [comment]
eXpand.lab release [19.1.602.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.5) includes commit that relate to this task:

* [TreeList editor raises an exception when the default is set to server mode #520](https://github.com/eXpandFramework/eXpand.lab/commit/d222ebb530752db3a0e297c69fb84a451b734b1a)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
