### ISSUE TITLE
19.1.503.x do not honor Editor setting

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#521]
from #439  I want to switch back to original Dx EnumProperty Editor which works OK in the same non-Xpand Solution

(original editor)
![image](https://user-images.githubusercontent.com/226800/63511845-a99a5080-c4b8-11e9-9537-a5c83ff028ab.png)

Xpand solution with same editor setting
![image](https://user-images.githubusercontent.com/226800/63511882-be76e400-c4b8-11e9-8cba-3ab0a954b499.png)

The model editor shows editor changed but the editor seem to not change (not showing images)

**Comment by expand** [comment]
eXpand.lab release [19.1.602.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.4) includes commit that relate to this task:

* [EnumRepositoryItemGridListEditorController should be activated only for the XpandEnumPropertyEditor #521](https://github.com/eXpandFramework/eXpand.lab/commit/89d093391c4e382ab54a4b05747d82b70ce1f17d)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
