### ISSUE TITLE
Error in Reactive

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#522]
After starting my project with 19.1.503.4 I got the Error

23.08.19 17:04:58.989	================================================================================
23.08.19 17:04:58.992	Trace Log for iXISXRM.Win.exe is started
23.08.19 17:04:58.993	================================================================================
iXISXRM.Win.exe Error: 0 : 23.08.19 17:05:16.563	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Mindestens ein Fehler ist aufgetreten.
	Data:       0 entries
	Stack trace:

   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei DevExpress.ExpressApp.Win.WinApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.XafApplication.Setup()
   bei iXISXRM.Win.Program.Main() in C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\Program.cs:Zeile 102.
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Exception occurs while initializing the 'Xpand.ExpressApp.XtraDashboard.Win.DashboardWindowsFormsModule' module: Sequence contains no elements.
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBasePatch.cs:Zeile 28.
   bei SetupModules_Patch2(ApplicationModulesManager )
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.Win.WinApplication.<>n__0(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
			----------------
			InnerException:

					Type:       InvalidOperationException
					Message:    Sequence contains no elements.
					Data:       0 entries
					Stack trace:

**Comment by apobekiaris** [comment]
the stack includes the Reactive module but also includes the DevExpress, what I meant is that these are notification points and do not relate to the actual error. Unfortunately the stack does not provide any clues to guess what is the problem.

**Comment by apobekiaris** [comment]
try to reference the attached assemmbly instead and let me knkow what the stack now?

[Xpand.XAF.Modules.Reactive.zip](https://github.com/eXpandFramework/eXpand/files/3535174/Xpand.XAF.Modules.Reactive.zip)

**Comment by apobekiaris** [comment]
in fact to not change anything just put it in path and execute your  iXISXRM.Win.exe without vs build

**Comment by CWolffIF** [comment]
23.08.19 17:42:06.090	================================================================================
23.08.19 17:42:06.092	Trace Log for iXISXRM.Win.exe is started
23.08.19 17:42:06.092	================================================================================
23.08.19 17:42:06.094	System Environment
	OS Version: Microsoft Windows NT 6.2.9200.0
	.Net Framework Versions: v4.0.30319
	CLR Version: 4.0.30319.42000
	eXpressApp Version: 19.1.5.0
	eXpressApp File Version: 19.1.5.0

Application config
	Modules=
	NewVersionServer=
	EnableDiagnosticActions=False
	Languages=de;en
	UserModelDiffsLocation=CurrentUserApplicationDataFolder
	ModelCacheLocation=CurrentUserApplicationDataFolder
	TraceLogLocation=CurrentUserApplicationDataFolder
	DpiAwareness=PerMonitorV2
	EnableWindowsFormsHighDpiAutoResizing=True
	ClientSettingsProvider.ServiceUri=

23.08.19 17:42:06.122	Initialize application
=======================
23.08.19 17:42:06.122		Command line arguments: 
		C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\iXISXRM.Win.exe
23.08.19 17:42:06.177	Resolve the 'Xpand.XAF.Modules.Reactive, Version=1.2.46.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958' assembly

**Comment by apobekiaris** [comment]
there is no stack here

**Comment by CWolffIF** [comment]
It just´s ends

**Comment by apobekiaris** [comment]
hmm i am confused the app started?

**Comment by CWolffIF** [comment]
No it did not start. I called the EXE in the debug Directory.

**Comment by apobekiaris** [comment]
no idea what to blame them, most probably is not the reactive module, happy to debug it on a sample or full app if u can send in private if u wish

**Comment by apobekiaris** [comment]
also try the verbose logging and post the log

**Comment by apobekiaris** [comment]
>Resolve the 'Xpand.XAF.Modules.Reactive, Version=1.2.46.0

where did this came from? the version should be 1.2.46.5

**Comment by CWolffIF** [comment]
Where did the 1.2.46.5 come from. With Nuget I get the 1.2.46.0.

**Comment by apobekiaris** [comment]
[bin.zip](https://github.com/eXpandFramework/eXpand/files/3535362/bin.zip)
try this and post yout log previously failed to resolve

**Comment by apobekiaris** [comment]
```ps1
Find-XpandPackage *react* Lab

Id                         Version
--                         -------
Xpand.XAF.Modules.Reactive 1.2.46.5
```

also if u could point which package has wrong dependcies?

**Comment by CWolffIF** [comment]
iXISXRM.Win.exe Error: 0 : 23.08.19 18:52:54.205	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Mindestens ein Fehler ist aufgetreten.
	Data:       0 entries
	Stack trace:

   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei DevExpress.ExpressApp.Win.WinApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.XafApplication.Setup()
   bei iXISXRM.Win.Program.Main() in C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\Program.cs:Zeile 102.
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Exception occurs while initializing the 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule' module: Methode nicht gefunden: "System.IObservable`1<!!0> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.Tracer(System.IObservable`1<!!0>, Boolean)".
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
   bei SetupModules_Patch1(ApplicationModulesManager )
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.Win.WinApplication.<>n__0(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
			----------------
			InnerException:

					Type:       MissingMethodException
					Message:    Methode nicht gefunden: "System.IObservable`1<!!0> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.Tracer(System.IObservable`1<!!0>, Boolean)".
					Data:       0 entries
					Stack trace:

   bei Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueService.Connect(ApplicationModulesManager modulesManager, XafApplication application)
   bei Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule.Setup(ApplicationModulesManager moduleManager) in D:\a\1\s\src\Modules\CloneMemberValue\Module.cs:Zeile 15.
   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
					InnerException is null

**Comment by apobekiaris** [comment]
this exception probably occurs because of the version problem please go though the packages in Nuget Manger console and check which one reports dependency to reactive 1.2.46.0

**Comment by CWolffIF** [comment]
All Xpand.XAF Modules I got throu Nuget got another number

	Xpand.XAF.Modules.CloneMemberValue, Version=1.2.46.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.CloneMemberValue.dll
	Xpand.XAF.Modules.CloneMemberValue, Version=1.2.46.2, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.CloneMemberValue\v4.0_1.2.46.2__c52ffed5d5ff0958\Xpand.XAF.Modules.CloneMemberValue.dll
	Xpand.XAF.Modules.CloneModelView, Version=0.0.29.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.CloneModelView.dll
	Xpand.XAF.Modules.CloneModelView, Version=0.0.29.2, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.CloneModelView\v4.0_0.0.29.2__c52ffed5d5ff0958\Xpand.XAF.Modules.CloneModelView.dll
	Xpand.XAF.Modules.HideToolBar, Version=0.0.22.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.HideToolBar.dll
	Xpand.XAF.Modules.HideToolBar, Version=0.0.22.2, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.HideToolBar\v4.0_0.0.22.2__c52ffed5d5ff0958\Xpand.XAF.Modules.HideToolBar.dll
	Xpand.XAF.Modules.ModelMapper, Version=1.1.38.5, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ModelMapper\v4.0_1.1.38.5__c52ffed5d5ff0958\Xpand.XAF.Modules.ModelMapper.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.37.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.37.2, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ModelViewInheritance\v4.0_1.1.37.2__c52ffed5d5ff0958\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.ProgressBarViewItem, Version=0.0.16.2, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ProgressBarViewItem\v4.0_0.0.16.2__c52ffed5d5ff0958\Xpand.XAF.Modules.ProgressBarViewItem.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.46.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.46.5, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.Reactive\v4.0_1.2.46.5__c52ffed5d5ff0958\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.46.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXIS\iXISXRM\iXISXRM.Win\bin\Debug\Xpand.XAF.Modules.ViewEditMode.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.46.2, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ViewEditMode\v4.0_1.2.46.2__c52ffed5d5ff0958\Xpand.XAF.Modules.ViewEditMode.dll

**Comment by apobekiaris** [comment]
the versions in your gac is the latest, I am not sure where/how the other assemblies came from.

the nugetserver versions look fine to me
![image](https://user-images.githubusercontent.com/159464/63611542-bfa52f80-c5e4-11e9-80a1-25f69e0769fd.png)

**Comment by CWolffIF** [comment]
You are right. The Version Conflict was the problem. Now it starts. Thanx.
