### ISSUE TITLE
Duplicate item is shown in enum editor

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#523]
This Enum produces the following wrong behavior
Public Enum NoFilterEnum
        <ImageName("BO_Task")> Option1
        Option2
    End Enum

![2019-08-26_15-50-15](https://user-images.githubusercontent.com/226800/63715032-59edb900-c819-11e9-86ba-1d33d0fa6beb.gif)

Public Enum NoFilterEnum
        <ImageName("BO_Task")> Option1
        Option2
    End Enum

**Comment by apobekiaris** [comment]
please provide a sample to avoid losing time in vain

**Comment by apobekiaris** [comment]
i cannot reproduce the case with the latest lab version and your sample, please check again and let me know

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
