### ISSUE TITLE
eXpand win app has runtime dependency on DevExpress.ExpressApp.Web

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#524]
A FileNotFoundException for DevExpress.ExpressApp.Web.v19.1 is thrown on startup of a eXpand winforms app.
You can easily reproduce this problem in XVideoRental demo, if you remove DevExpress.ExpressApp.Web from the GAC.
Where does this dependency come from? Bug is somehow triggered by XpandModuleBase.GetDeclaredControllerTypesCore
[stacktrace.txt](https://github.com/eXpandFramework/eXpand/files/3545140/stacktrace.txt)

**Comment by apobekiaris** [comment]
I can repro it, could be loaded by mistake from a standalone module cannot tell which one without investigating. I ll update u again once fixed.

**Comment by gerritmulder** [comment]
I believe I have mentioned this earlier, but the "agnostic" Xpand projects aren't really agnostic. They're made agnostic because both Win and Web dependencies are added.

As you see here the "agnostic project" has non-agnostic XAF dependencies: https://github.com/eXpandFramework/eXpand/blob/f57a4845c4e0868bfff4b5e27a6e0864e06e11bb/Xpand/Xpand.Persistent/Xpand.Persistent.Base/Xpand.Persistent.Base.csproj#L35-L36

We have that error too in our buildserver if we remove our DevExpress.ExpressApp.Web dependency while we don't have a web project. This is because the Xpand agnostic project is looking for that assembly, but can't find it. For this reason we have to add the web assembly to our project.

**Comment by apobekiaris** [comment]
yes sure I remember however without yet researching the issue I want to add that .NET is lazy loading the only when a type is used it will be loaded. You can see the same approach in DevExpress.Utils assembly which references web assemblies. In any case when when is clear how the web is loaded we will provide a fix.

**Comment by gerritmulder** [comment]
I wonder how it will lazy load the DevExpress.ExpressApp.Web assembly in a Xaf WinForms only project if it's not available?

**Comment by apobekiaris** [comment]
it won't there should be no call to a web type in such case

**Comment by krombipils** [comment]
Are you still working on this?
In the `XpandModuleBase.GetDeclaredControllerTypesCore` you have some checks for the platform, e.g  `if (!this.Executed("GetDeclaredWebControllerTypes", ModuleType.Web))` but there is no such a check for the `WebDashboardRefreshController`.
Is this the cause of the issue?

**Comment by apobekiaris** [comment]
apologies yes its an open case and still assigned, however other works have priority. If u have a fix let me know please else I ll update u once I research it

**Comment by krombipils** [comment]
Actually I don't really understand what's going on. The `GetDeclaredControllerTypesCore` e.g. has a check `if (!Executed("GetDeclaredWebControllerTypes", ModuleType.Web)){...}` and the web types should only be loaded if the Platform is web. But according to the debugger, the types are always loaded. I'm not sure whether this happens due to some compiler optimizations?!
If I replace the array in the if block with a getter, DevExpress.ExpressApp.Web is not loaded anymore/ not FileNotFoundException is thrown in GetDeclaredControllerTypesCores.

    protected IEnumerable<Type> WebTypes
    {
        get
        {
            var webTypes = new[]
            {
                typeof(NavigationContainerWebController), typeof(ActionsClientScriptController),
                typeof(ActionsClientConfirmationController),
                typeof(SyntaxHighlightController)
            };
            return webTypes;
        }
    }

But then the FileNotFoundException is thrown later when SetupModules is called.
Somehow the lazy loading of non-agnostic types in Xpand.Persistent.Base seems to be broken.

**Comment by apobekiaris** [comment]
even if I fix the loading from the `GetDeclaredControllerTypesCore` there is this call 

https://github.com/eXpandFramework/eXpand/blob/2518300e8e660014bc6f0b4ad2feb7e0628c192b/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/XpandModuleBase.cs#L425

The call is done to quick register all types so they can be consumed from other modules. I will remove it and probably we have a few exceptions because of this. If you take the time to report them I will provide manual registrations where needed.

**Comment by apobekiaris** [comment]
unfortunately further research revealed that it is not possible to avoid this load, the Base assembly architecture suffers. In the Base there are model interfaces and when XAF constructs the model loads the all types. 

Web/Win dependencies need to be separate packages and installed to their respective platform.

I am leaving this case open

**Comment by krombipils** [comment]
> Web/Win dependencies need to be separate packages 
If I understand you right, your plan is to split the Xpand.Persistent.Base.dll into a platform-agnostic dll and win/web-specific dlls. Right?

**Comment by gerritmulder** [comment]
> > Web/Win dependencies need to be separate packages
> > If I understand you right, your plan is to split the Xpand.Persistent.Base.dll into a platform-agnostic dll and win/web-specific dlls. Right?

Tolis, said one dll and dll will decide if web or win is loaded. 

> yes sure I remember however without yet researching the issue I want to add that .NET is lazy loading the only when a type is used it will be loaded. You can see the same approach in DevExpress.Utils assembly which references web assemblies. In any case when when is clear how the web is loaded we will provide a fix.

**Comment by apobekiaris** [comment]
i do not plan to split the base, but to create standalone package out of the platform specific implementations found in base. Then install these packages to the related modules. 

I am not sure what your 2nd quote implies so cannot asnwer much yes .net is lazy loading but as soon as someone does assembly.GetTypes() in the base everything is loaded. This action is done from XAF where we do not have much control.

**Comment by apobekiaris** [comment]
>Tolis, said one dll and dll will decide if web or win is loaded.

this approach is used in some standalone standalone packages for e.g 
https://github.com/eXpandFramework/DevExpress.XAF/blob/lab/src/Modules/ProgressBarViewItem/ProgressBarViewItemBase.cs#L30-L53

as u see types are loaded on Init using reflection and depending on the platform, so even an assembly.GetTypes() will not load unwanted assemblies

**Comment by apobekiaris** [comment]
for now, it is not a big problem having to distribute a additional assemblies even if they are for a different platform. XAF already depends to a lot of assemblies a few more won't make much difference. This the feeling I have.

**Comment by gerritmulder** [comment]
Persistent.Base uses the actual DevExpress.ExpressApp.Web dependency. It will build, but won't run. The ProgressBarViewItem uses reflection and not the DLL, which will work.

**Comment by gerritmulder** [comment]
Another case where Xpand causes problems is when making a Win or Web release. When building my Win project, it will take only the Win and Agnostic projects. None of those have a Web reference ofcourse. So when putting the zip with my WinApplication on a customer's pc (without Web references ofcouse, since it's a Win application), Persistent.Base will throw an exception.

So either use reflection so there are no Web dependencies or split them up. First is a nice approach, but at least be sure it works.

**Comment by gerritmulder** [comment]
> 
> 
> for now, it is not a big problem having to distribute a additional assemblies even if they are for a different platform. XAF already depends to a lot of assemblies a few more won't make much difference. This the feeling I have.

As many people use Xpand, I don't think it's professional to have unnessary files in a release.

These DLL's come with DevExpress.ExpressApp.Web with a total size of 85,2 mb .
DevExpress.ExpressApp.Web.v19.1.dll
DevExpress.Web.ASPxHtmlEditor.v19.1.dll
DevExpress.Web.ASPxPivotGrid.v19.1.dll
DevExpress.Web.ASPxSpellChecker.v19.1.dll
DevExpress.Web.ASPxThemes.v19.1.dll
DevExpress.Web.ASPxTreeList.v19.1.dll
DevExpress.Web.Resources.v19.1.dll
DevExpress.Web.v19.1.dll

**Comment by apobekiaris** [comment]
the case only affects the distribution so it remain open until works are finished.

**Comment by apobekiaris** [comment]
#626  probably relates to this case

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
