### ISSUE TITLE
How do install Expand Visual Studio 2019 ?

### ISSUE THREAD

**Issue by mcaltindal33** [eXpandFramework/eXpand#526]
Hi I can't find it now when presenting an installation file. Unfortunately the xpand.dll does not load with the component installer. Is my DevExpress Version 18.2.10, so I couldn't install it. I think about it I fell into a lower case as a beginner rookie :(

**Comment by apobekiaris** [comment]
did u try the powershelll installer?

![image](https://user-images.githubusercontent.com/159464/63982366-dbb83d80-caca-11e9-826f-3166c1bf83ce.png)

**Comment by mcaltindal33** [comment]
Yeah, I tried. However, my version of DevExpress is 18.2.10. incoming file 19.1.503
![2019-08-30](https://user-images.githubusercontent.com/39138827/63983103-ede7ab00-cacd-11e9-83cb-599cc88479b1.png)

**Comment by apobekiaris** [comment]
from what i saw the latest is https://github.com/eXpandFramework/eXpand/releases/tag/18.2.704.0 there isn't one for 18.2.10 as it released while a newer version is already out.

you can get the version u want with the installer if u remove the bracket from the command 

```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  -Version '18.2.704.0'"
```

**Comment by mcaltindal33** [comment]
Installation is complete. However, I can't create an XAF Project right now. I'm getting an error. I think I need to update DevExpress or I need to install the old version.

In the meantime, thank you very much for your help.

**Comment by apobekiaris** [comment]
u need 18.2.7

**Comment by mcaltindal33** [comment]
Or you need to manually rebuild the project from source 18.2.10 manually.

**Comment by apobekiaris** [comment]
yes thats also an option
