### ISSUE TITLE
Tree List View web example

### ISSUE THREAD

**Issue by socrates-rivera** [eXpandFramework/eXpand#527]
Hello.
Please indicate location of an example illustrating the use of a web Tree List View control.
I use C# in visual studio.
Thanks in advance,
Regards
Socrates A Rivera R

**Comment by apobekiaris** [comment]
there is no examples of this module and from what I see it is not so rich in features, makes me wonder why u interested in this module specific?

Depending on your installation reference the Xpand.ExpressApp.TreeListEditors.Web.dll and add this line to the ctor of your module
```cs
RequiredModuleTypes.Add(typeof(XpandTreeListEditorsAspNetModule));
```

after that the module and its agnostic mart are installed.

**Comment by socrates-rivera** [comment]
Hello:
Thank for your answer.
I have to show a grid, but the first column has a father/son relationship (and have to show it as a tree).
I have the dll and is referenced.
I am sorry. I do not understand. What is “the ctor of your module”? Is it constructor?
Thank you very much in advance.
Regards,
Socrates A rivera R

**Comment by apobekiaris** [comment]
yes the ctor means constructor

**Comment by socrates-rivera** [comment]
Hello:
Thank you for your answer.
I am sorry. Are these instructions for C# web in visual studio?
Thank you very much in advance.
Regards,
Socrates A Rivera R

**Comment by socrates-rivera** [comment]
Hello Apostolis:
Thank you very much for your answer.
I am pretty novice in these matters.
Can somebody provide advice much more oriented to my case?
Thank you very much in advance.
Regards,
Sócrates A Rivera R

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
