### ISSUE TITLE
More Details about Xpand Quartz JobScheduler module

### ISSUE THREAD

**Issue by OulaAlshiekh** [eXpandFramework/eXpand#528]
Ihave read the documentation in the url http://apobekiaris.blogspot.com/2011/04/xaf-quartz-jobscheduler-module.html

        but details are not explained and it is the only source for this topic

        can you help me more about that topic
        and provide me with currently  working Examples
        i have never found an example in the feature center as mentioned in the blog

**Comment by apobekiaris** [comment]
see #241

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
