### ISSUE TITLE
Convert project

### ISSUE THREAD

**Issue by sabo961** [eXpandFramework/eXpand#529]
I have to convert existing project to 19.1.5. Before, it worked automatically when I installed new version. How to do it now?

**Comment by apobekiaris** [comment]
you can use XAF projectconverter as usual and in aditional from powershell you can use 

```
Start-XpandProjectConverter
```

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
