### ISSUE TITLE
inner Exception is by closing Scheduler Detail View

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#530]
After Update to 19.1.503 when i open and close scheduler detail view by closing i get following issue

Type:       InvalidCastException
	Message:    Das Objekt des Typs "ModelDevExpressXtraScheduler_SchedulerControl" kann nicht in Typ "Xpand.ExpressApp.Scheduler.Model.IModelListViewSchedulerEx" umgewandelt werden.
	Data:       0 entries
	Stack trace:

   bei Xpand.ExpressApp.Scheduler.Model.SchedulerModelAdapterControllerBase.SchedulerListEditorOnResourceDataSourceCreating(Object sender, ResourceDataSourceCreatingEventArgs e)
   bei DevExpress.ExpressApp.Scheduler.SchedulerListEditorBase.OnResourceDataSourceCreating(ResourceDataSourceCreatingEventArgs e)
   bei DevExpress.ExpressApp.Scheduler.SchedulerListEditorBase.CreateResourcesDataSource()
   bei DevExpress.ExpressApp.Scheduler.Win.SchedulerListEditor.TryRefreshResourcesDataSource()
   bei DevExpress.ExpressApp.Scheduler.Win.SchedulerDetailViewController.View_Closing(Object sender, EventArgs e)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.View.Close(Boolean checkCanClose)
   bei DevExpress.ExpressApp.Win.WinWindow.ProcessFormClosing()
   bei DevExpress.ExpressApp.Win.WinWindow.DoOnFormClosing(CancelEventArgs e)
   bei DevExpress.ExpressApp.Win.WinWindow.Form_Closing(Object sender, CancelEventArgs e)
   bei System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   bei System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   bei System.Windows.Forms.Form.WmClose(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   bei DevExpress.XtraBars.Ribbon.RibbonForm.WndProc(Message& msg)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

**Comment by rSeeFip** [comment]
If i try to open locally ModelEditor from DevExpress i get access issue with following text

error CS1567: Fehler beim Generieren der Win32-Ressource: Zugriff verweigert 
warning CS1610: Die temporäre Datei 'c:\Program Files (x86)\DevExpress 19.1\Components\Tools\eXpressAppFramework\Model Editor\CSC1572542B29A744878BEDE761EDC5E38B.TMP', die für die Win32-Standardressource verwendet wird, kann nicht gelöscht werden -- Das System kann die angegebene Datei nicht finden. 

   bei Xpand.XAF.Modules.ModelMapper.Services.TypeMapping.TypeMappingService.Compile(IEnumerable`1 references, String code)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count)
   bei System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count)
   bei System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Subjects.Subject`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Aggregate`1._.OnCompleted()
   bei System.Reactive.Sink`1.ForwardOnCompleted()
   bei System.Reactive.TailRecursiveSink`1.Drain()
   bei System.Reactive.TailRecursiveSink`1.Recurse()
   bei System.Reactive.Sink`1.ForwardOnCompleted()
   bei System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler)
   bei System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   bei System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   bei System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   bei System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
   bei System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   bei System.Reactive.Linq.ObservableImpl.Switch`1._.OnNext(IObservable`1 value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei DevExpress.ExpressApp.ApplicationModelManager.CreateModelApplicationCreatorProperties(IEnumerable`1 modules, IEnumerable`1 controllers, String assemblyFileAbsolutePath)
   bei DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateApplicationModelCore(ApplicationModulesManager modulesManager, IEnumerable`1 localizerTypes, IEnumerable`1 aspects, ModelStoreBase modelDifferencesStore, ModelStoreBase userDifferencesStore)
   bei DevExpress.ExpressApp.ModelEditor.MainClass.StandaloneModelEditorModelLoader.LoadModel(String targetFileName, String modelDifferencesStorePath, String deviceSpecificDifferencesStoreName, String assembliesPath)
   bei DevExpress.ExpressApp.ModelEditor.MainClass.controller_CustomLoadModel(Object sender, CustomLoadModelEventArgs e)

**Comment by rSeeFip** [comment]
issue in english:

object of type "ModelDevExpressXtraScheduler_SchedulerControl" cannot converted to type of "Xpand.ExpressApp.Scheduler.Model.IModelListViewSchedulerEx"

**Comment by apobekiaris** [comment]
I am not sure how to repro this case, I tested against XVIdeoRental wchich features a full schudeler and does not throw. Can you please post a sample?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
