### ISSUE TITLE
Error when MasterDetailMode is ListViewAndDetailView

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#531]
Hello,

after upgrading to 19.1.503.0 when i try to open or close an View in Win, where MasterDetailMode is ListViewAndDetailView,
this error Popup.
After this error i try to open this View again and it works without error until
next restart of Apllication.

No match for property with name MainView and flags Instance | NonPublic | Public | Static on type DevExpress.XtraEditors.SidePanelContainer.

   bei Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo)
   bei Fasterflect.Emitter.MemberGetEmitter.CreateDelegate()
   bei Fasterflect.Emitter.BaseEmitter.GetDelegate()
   bei Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name, Flags bindingFlags)
   bei Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name)
   bei Fasterflect.PropertyExtensions.GetPropertyValue(Object obj, String name)
   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetViewControl(PredefinedMap predefinedMap, CompositeView view, String model)
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindData(ValueTuple`3 data)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   bei System.Reactive.ExceptionHelpers.Throw(Exception exception)
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.IdentitySink`1.OnNext(T value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.IdentitySink`1.OnNext(T value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.View.OnControlsCreated()
   bei Xpand.ExpressApp.XpandListView.OnControlsCreated()
   bei DevExpress.ExpressApp.View.CreateControls()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.OnViewChanged()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.SetView(View view)
   bei DevExpress.ExpressApp.Win.Templates.Ribbon.DetailRibbonFormV2.DevExpress.ExpressApp.Templates.IFrameTemplate.SetView(View view)
   bei DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   bei DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)

**Comment by apobekiaris** [comment]
unfortunately there is no easy resolution to this 

same as #506

**Comment by rSeeFip** [comment]
i'm closing this issue for me now by using
  xaf CategorizedListEditor and not Expand CategorizedListEditor 

for first it's ok. all of #506 not works

**Comment by apobekiaris** [comment]
although I see that ModelMapper is involved I fail to reproduce it. If you can post a sample happy to debug it further.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
