### ISSUE TITLE
Email Module 

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#532]
Hi

XAF Application use with PermissionPolicyUser/Role how can implement Email Module 

XpandFramework work on SecuritySystemUser/Role

Kindly Help me to Use it

**Comment by apobekiaris** [comment]
I can offer support over your problems once you post details about it. Now I do not see where is the problem

**Comment by cevious** [comment]
Thanks
I have implemented latest XAF Security system PermissionPilicyRole & PermissionPolicyUser in my application 

Entire expandframework security system work on  SecuritySystemUser & SecuritySystemRole how do I add module in my application.

Can you help me.

**Comment by melihyilman** [comment]
https://lmgtfy.com/?q=devexpress+xaf+how+to+change+user+type&iie=1

**Comment by cevious** [comment]
hi

Try to undefrstand. My application  Written & dependent with latest XAF Security system. We cann't changes. some custome securoty implemented.

Email Module Dependencies on Xpand Logic Module, Xpand Security Module.

**Comment by apobekiaris** [comment]
>We cann't changes. some custome securoty implemented.

what is the problem?

 eXpand does not use any fixed schema rather it takes it from the front end

**Comment by cevious** [comment]
We can change but some of the custom feature made us in latest XAF Security system

For new user is easy to implement but existing user difficult to change. Who have already custom things.

So it is difficult to change but you should do this.

Any feature plan? Some of the feature really want use. But?


Thanks & Regards

Hemant
Sent from my iPhone

On 12-Sep-2019, at 1:51 AM, Apostolis Bekiaris <notifications@github.com<mailto:notifications@github.com>> wrote:


We cann't changes. some custome securoty implemented.

what is the problem?

eXpand does not use any fixed schema rather it takes it from the front end

**Comment by apobekiaris** [comment]
as I said eXpand should work with any XAF security object, if u have a problem provide a sample to reproduce it.

**Comment by cevious** [comment]
Right, Should work on all, I inspect code
XapandSecurity
XapandLogic
ScecurityExtansion written based on old structure and hardly inplemented on class level SecuritySystemUser/Role

I am very much intrested to use Logic/Security/Excel Import Module but today I can’t due so much dependencies.

I am try to change but some custom security create hardle. So I can’t

Current XAF Security implement lot of feature in default I.e navigation, propertylever security and lots more.


Thanks & Regards

Hemant
Sent from my iPhone

On 12-Sep-2019, at 8:40 AM, Apostolis Bekiaris <notifications@github.com<mailto:notifications@github.com>> wrote:


as I said eXpand should work with any XAF security object, if u have a problem provide a sample to reproduce it.

**Comment by cevious** [comment]
Thanks

I ma tryied to use email module with user registration option but I use XpandLogonParameter but no option is comming

I have enable Option (Registration) from module editor. But no clue.

You can check with EmailTester

**Comment by apobekiaris** [comment]
try these steps:

1. Install Xpand.VSIX
1. Use VS New Project Wizard and create a new Xpand solution
![image](https://user-images.githubusercontent.com/159464/65441001-4e021080-de32-11e9-9e23-b5c5a1b885ba.png)
2. Create a new Win Solution wit Standard Authentication. This will automatically register the XpandSecurity
3. Modify the model to enable Registration
```xml
<Application Title="Solution256">
  <Options>
    <LayoutManagerOptions RequiredFieldMark="*" />
    <Registration Enabled="True" />
  </Options>
</Application>
```
4. Run the application
![image](https://user-images.githubusercontent.com/159464/65441210-afc27a80-de32-11e9-9621-56748b76497a.png)

**Comment by cevious** [comment]
I have my ownPermissionPolcy User/Role and want to use it. How can I use it

Thanks & Regards

Hemant
Sent from my iPhone

On 23-Sep-2019, at 9:18 PM, Apostolis Bekiaris <notifications@github.com<mailto:notifications@github.com>> wrote:


try these steps:

  1.  Install Xpand.VSIX
  2.  Use VS New Project Wizard and create a new Xpand solution
[image]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F159464%2F65441001-4e021080-de32-11e9-9e23-b5c5a1b885ba.png&data=02%7C01%7C%7C6bae8a288b354dc43d5c08d7403d71ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637048504955149752&sdata=yy3awjuf5EaSrDlGnzmpaqgnTJm7k%2FpJXBUnk0eZrZU%3D&reserved=0>
  3.  Create a new Win Solution wit Standard Authentication. This will automatically register the XpandSecurity
  4.  Modify the model to enable Registration

<Application Title="Solution256">
  <Options>
    <LayoutManagerOptions RequiredFieldMark="*" />
    <Registration Enabled="True" />
  </Options>
</Application>

  1.  Run the application
[image]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F159464%2F65441210-afc27a80-de32-11e9-9621-56748b76497a.png&data=02%7C01%7C%7C6bae8a288b354dc43d5c08d7403d71ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637048504955159760&sdata=M9HBp3OhULHOgsQ%2B%2FbpE67JWI7%2B2zcLl6Mvs6z8fYCU%3D&reserved=0>

**Comment by apobekiaris** [comment]
the steps i described before will generate the next code in your WinApplication.Designer.cs
```cs
this.securityStrategyComplex1.RoleType = typeof(Xpand.Persistent.BaseImpl.Security.XpandPermissionPolicyRole);
            this.securityStrategyComplex1.UserType = typeof(Xpand.Persistent.BaseImpl.Security.XpandPermissionPolicyUser);
```
change it as per your custom types

**Comment by cevious** [comment]
Hi 

I have identified issue.
1.) Fresh application it running fine (Registration)
2.) My Existing application showing error find enclosed trace log
[Tracelog.txt](https://github.com/eXpandFramework/eXpand/files/3645845/Tracelog.txt)
3.)Try to fix (I have disbale module "ModelViewInheritanceModule")  Now My application excuted but registration feature not working

Can you help me

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
