### ISSUE TITLE
Help resolving "Could not load file or assembly 'Fasterflect.Netstandard"

### ISSUE THREAD

**Issue by rblinton** [eXpandFramework/eXpand#533]
I'm having trouble with Xpand.ExpandApp.ViewVariants 

1. Installed eXpandViewVariants (v19.1.503) via nuget
2. Added this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule)); to WinModule.Designer.cs
3. Build and attempted to open Model.DesignedDiffs designer
4. Recieved Error: "Could not load file or assembly 'Fasterflect.Netstandard, Version=1.0.9.0..." in designer
5. Installed Fasterflect.Netstandard (v1.0.9) via nuget
6. Buld and attempt to open Model.DesignedDiff and received the same error as above

Can you please assist in solving this error?

**Comment by apobekiaris** [comment]
I see, apparently there is a problem with the nuspec generation, we use a recombiled version of FasterFlect, Until fixed u can find it here https://github.com/eXpandFramework/eXpand/tree/master/Support/_third_party_assemblies

**Comment by rblinton** [comment]
Thank you for the quick reply. I've uninstalled the FastFlect using nuget and added a reference to the recompiled .dll
I now receive the error:
"Exception occurs while initializing the 'Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule' module: The type initializer for 'Xpand.Persistent.Base.General.ApplicationModulesManagerExtensions'"

![eXpand View Variant Error](https://user-images.githubusercontent.com/8559250/64739141-7727b600-d4ae-11e9-8605-d6f45fb0516c.png)
I have attached a screenshot of the error with stack trace

**Comment by rgrove71** [comment]
Thanks for posting this. I uninstalled eXpand after having this issue yesterday afternoon after the install. I'd like to try some of the modules like this one. Do they all have this issue? Or did I just pick the wrong one to start with. I'll probably play around with it this weekend since I don't have time to troubleshoot something like this during the workday ATM.

**Comment by apobekiaris** [comment]
hmm apologies reading your screenshot again i noticed that the 0Harmony.dll is missing u can find it in the same place.

this is a distribution problem apparently all nugets do not include those libs so if they are needed it will throw or just download them and put them in path

**Comment by apobekiaris** [comment]
see #556 #557

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
