### ISSUE TITLE
Generated Assembly issue in World Creator (web UI)

### ISSUE THREAD

**Issue by JakeLogan2019** [eXpandFramework/eXpand#536]
When generated this code in Persistent Assembly Info screen...

using System;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using Xpand.Persistent.Base.PersistentMetaData;
using Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos;
using System.Linq;
[assembly: System.Reflection.AssemblyVersionAttribute("19.1.5030.13")]
namespace TestAssembly1{public class DynamicTestAssembly1Module:DevExpress.ExpressApp.ModuleBase{}}
namespace TestAssembly1{
using System;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using Xpand.Persistent.Base.PersistentMetaData;
using Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos;

using System.Linq;

  public class TestClass1:Xpand.Xpo.XpandCustomObject{
    public TestClass1(Session session):base(session){}
    public override void AfterConstruction() {
        base.AfterConstruction();
    }

    protected override void OnSaving() {
        base.OnSaving();
    }

    protected override void OnChanged(string propertyName, object oldValue, object newValue) {
        base.OnChanged(propertyName,oldValue, newValue);
    }

      string _FullName;
    [DevExpress.Xpo.SizeAttribute(255)]
[DevExpress.Persistent.Base.VisibleInLookupListViewAttribute(true)]
[DevExpress.Xpo.PersistentAttribute(@"FullName")]
[DevExpress.Persistent.Validation.RuleRequiredFieldAttribute(@"VK1234",@"Save", TargetCriteria=null)]
[DevExpress.Xpo.PersistentAliasAttribute(@"Full Name")]
[DevExpress.Persistent.Base.VisibleInListViewAttribute(true)]
[DevExpress.Persistent.Base.VisibleInDetailViewAttribute(true)]
    public string FullName{
      get{
        return _FullName;
      }
      set{
        SetPropertyValue("FullName", ref _FullName, value);
      }
    }
}
}

I get this Compile Error

================================================================================
The error occurred:

   Type: FileLoadException
   Message: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)
   Data: 0 entries
   Stack trace:

at System.RuntimeTypeHandle.GetAssembly(RuntimeType type)
at System.RuntimeType.GetRuntimeAssembly()
at System.Reflection.Emit.DynamicMethod.PerformSecurityCheck(Type owner, StackCrawlMark& stackMark, Boolean skipVisibility)
at System.Reflection.Emit.DynamicMethod..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
at Fasterflect.Emitter.BaseEmitter.CreateDynamicMethod(String name, Type targetType, Type returnType, Type[] paramTypes)
at Fasterflect.Emitter.MemberGetEmitter.CreateDynamicMethod()
at Fasterflect.Emitter.BaseEmitter.GetDelegate()
at Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name, Flags bindingFlags)
at Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name)
at Fasterflect.PropertyExtensions.GetPropertyValue(Object obj, String name)
at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
at SetupModules_Patch1(ApplicationModulesManager )
at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
at Xpand.ExpressApp.WorldCreator.CodeProvider.Validation.AssemblyValidator.TypesInfoValidation(String assemblyFile, TypesInfo typesInfo) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\WorldCreator\CodeProvider\Validation\AssemblyValidator.cs:line 47
at Xpand.ExpressApp.WorldCreator.CodeProvider.Validation.AssemblyValidator.ValidateCore(String assemblyPath) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\WorldCreator\CodeProvider\Validation\AssemblyValidator.cs:line 29
   InnerException is null

--------------------------------------------------------------------------------
Loaded assemblies
   Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null, Location=InMemory Module
   AppDomainToolkit, Version=1.0.4.1, Culture=neutral, PublicKeyToken=f2fc7ab5180cf5c4, Location=D:\_dev\Solution1\Solution1.Web\bin\AppDomainToolkit.dll
   be6063f447fc44378885ee5980354198, Version=19.1.5030.12, Culture=neutral, PublicKeyToken=null, Location=D:\_dev\Solution1\Solution1.Web\be6063f447fc44378885ee5980354198.Xpand
   DevExpress.Data.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.Data.v19.1\v4.0_19.1.5.0__b88d1754d700e49a\DevExpress.Data.v19.1.dll
   DevExpress.ExpressApp.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.ExpressApp.v19.1\v4.0_19.1.5.0__b88d1754d700e49a\DevExpress.ExpressApp.v19.1.dll
   DevExpress.ExpressApp.Xpo.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.ExpressApp.Xpo.v19.1\v4.0_19.1.5.0__b88d1754d700e49a\DevExpress.ExpressApp.Xpo.v19.1.dll
   DevExpress.Images.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.Images.v19.1\v4.0_19.1.5.0__b88d1754d700e49a\DevExpress.Images.v19.1.dll
   DevExpress.Utils.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.Utils.v19.1\v4.0_19.1.5.0__b88d1754d700e49a\DevExpress.Utils.v19.1.dll
   DevExpress.Xpo.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.Xpo.v19.1\v4.0_19.1.5.0__b88d1754d700e49a\DevExpress.Xpo.v19.1.dll
   Fasterflect.Netstandard, Version=1.0.9.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=D:\_dev\Solution1\Solution1.Web\bin\Fasterflect.Netstandard.dll
   Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Utilities.v4.0\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Utilities.v4.0.dll
   mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
   netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll
   System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
   System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll
   System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
   System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
   System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
   System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Design\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Design.dll
   System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
   System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
   System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll
   System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll
   System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
   System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll
   System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll
   System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.RegularExpressions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.RegularExpressions.dll
   System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll
   System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
   System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
   WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll
   Xpand.ExpressApp.WorldCreator, Version=19.1.503.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=D:\_dev\Solution1\Solution1.Web\bin\Xpand.ExpressApp.WorldCreator.dll
   Xpand.Xpo, Version=19.1.503.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=D:\_dev\Solution1\Solution1.Web\bin\Xpand.Xpo.dll
================================================================================

Solution1.zip was submitted in bug 535.

**Comment by JakeLogan2019** [comment]
Just FYI for all 3 bugs I used VS 2017 all latest updates loaded.

**Comment by JakeLogan2019** [comment]
![image](https://user-images.githubusercontent.com/55221746/64751966-f091c980-d4eb-11e9-8634-92970a482d31.png)

Hope this also helps I tried setting up version to 1.0

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
