### ISSUE TITLE
SourceLink not working?

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#537]
I'm trying to debug ModelMapper version 1.1.38.5 from https://xpandnugetserver.azurewebsites.net/nuget/ The package contains a pdb file but no sources and SourceLink does not seem to work?! I tried to use the source files from https://github.com/eXpandFramework/DevExpress.XAF, but VS complains about differences between the pdb/dll and the source file (for PredefinedMapService.cs). Am I doing something wrong?

**Comment by krombipils** [comment]
Thank you. The sources are now found, after I enabled source server support again in VS (I think eXpand was using source link in the past?!).
Unfortunately while debugging ModelMapper sources, the code lines do not match the call stack in the debugger. Setting COMPLUS_ZapDisable = 1 did not worked for me, therefore I compiled my own version of ModelMapper.

**Comment by apobekiaris** [comment]
>I think eXpand was using source link in the past?!)

yeah before sourcelink become official we borrow the idea from sourcelink

>COMPLUS_ZapDisable = 1

this only disables the optimizations u should be able to step in without it

if u try it again please use the Get-SymbolsSurces and see where the ModelMapper is indexed to. Hard to believe that this package is not indexed while other other cause its the same process

**Comment by krombipils** [comment]
I think you got me wrong: It is now possible to step into, but the debugger does not stop on the exact line numbers. Get-SymbolSources returns e.g. https://raw.githubusercontent.com/eXpandFramework/DevExpress.XAF/lab/src/extensions/extensions/xaf/xafapplication/GetPlatform.cs. I think this is correct.

**Comment by apobekiaris** [comment]
aha makes sense as the lab header is not moved, I should index against a specific commit and not the head 

thnks!

**Comment by krombipils** [comment]
I guess this does make sense

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Index the source against a specific commit and not the head #537](https://github.com/eXpandFramework/DevExpress.XAF/commit/a10483ec9ec6da378eb341ad370918e42aa883cf)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.8) includes commit that relate to this task:

* [Index the source against a specific commit and not the head #537](https://github.com/eXpandFramework/eXpand.lab/commit/5181e53ea58a85eee4343523068ed6a36549432e)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Indexing a specific commit is working now. Thank you!
