### ISSUE TITLE
New Periodic View Refresh

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#538]
as per the existing `RefreshObjectViewController` included in the source

**Comment by apobekiaris** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [RefrshView release #538](https://github.com/eXpandFramework/DevExpress.XAF/commit/82d38e0d30a64d1b844faf86f3708a4ddc3f7f17)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.15) includes commit that relate to this task:

* [Integrate RefreshViewModule #538](https://github.com/eXpandFramework/eXpand.lab/commit/56daabd669b5c9e1c62406059ab6676c225e8ef2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
