### ISSUE TITLE
New Logger Module

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#539]
Reactive Extensions used for designing the standalone modules as a higher level language demands higher level logging tools. Without them it is not certain what the code does.

Existing extensions can be instrumented with a .Trace() call at the end of the pipeline. The logger will log all RX actions (Subscribe, OnNext, OnComplete, Dispose)  per module per application. Futhermore it will act as a server where other clients can connect and monitor the running pipes.

**Comment by apobekiaris** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ReactiveLogger release #539](https://github.com/eXpandFramework/DevExpress.XAF/commit/f6aa0f6f05abb971179147435ba6302085ba0e64)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.15) includes commit that relate to this task:

* [Integrate reactive.logger #539](https://github.com/eXpandFramework/eXpand.lab/commit/535c6cd26002bf746427a8a61abdc896eb6fe649)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
