### ISSUE TITLE
New OneVIew Module

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#540]
THe module should hide the mainform and show a model configured view with the option to configure the model and nothing else, like toolbars staus,navigation. Simple tools powered from XAF like the client of the  #539

**Comment by apobekiaris** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [OneView release #540](https://github.com/eXpandFramework/DevExpress.XAF/commit/d51e9c2f7aae43637fff65a99b24b9f765a9e399)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
