### ISSUE TITLE
New GridListEditor module

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#541]
The module will host features related to the win GridListEditor. Rules for each feature you want to enable should be added from the model. For start there is a need to remember the `TopRowIndex` for example when you stream data into a view like the client of #539

**Comment by apobekiaris** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [GridListEditor release #541](https://github.com/eXpandFramework/DevExpress.XAF/commit/5d4b29e03bf37c3f4a7f9303a7e394e471c71186)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.15) includes commit that relate to this task:

* [integrate GridListEditor module #541](https://github.com/eXpandFramework/eXpand.lab/commit/8574febe3f69ba80d15b4c1065139e7e6b941b74)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
