### ISSUE TITLE
NuGet error: Package is not compatible with framework version, does not support any target frameworks

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#545]
[Issue545.csproj.txt](https://github.com/eXpandFramework/eXpand/files/3620018/Issue545.csproj.txt)

When adding a 19.1.602 project, the following error is given:
```
error NU1202: Package eXpandSystem 19.1.602 is not compatible with net461 (.NETFramework,Version=v4.6.1).
Package eXpandSystem 19.1.602 does not support any target frameworks.
```
eXpandLib seems be the only package to not have this.

csproj I tested with:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="eXpandSystem" Version="19.1.602.0" />
  </ItemGroup>

</Project>
```

**Comment by apobekiaris** [comment]
yes i see the problem, though i missed it before, maybe my clocal sources conflict somehow. I am working on it

**Comment by apobekiaris** [comment]
I am not sure why it happens because I cannot repro it anymore, after `Clear-NugetCache` the problem stopped. I can create a new empty XAF solution and install the eXpandSystem package. Can you try it?

**Comment by gerritmulder** [comment]
I just tested this on the buildserver, issue is there too. We can't use this version in our projects until there is a fix or an easy workaround.

**Comment by apobekiaris** [comment]
did you clean the nuget cache in your buildserver?

**Comment by gerritmulder** [comment]
Yes, I did

**Comment by apobekiaris** [comment]
tried on another machine fresh install DX works also

**Comment by gerritmulder** [comment]
I'll try to find the error later, if I have found the problem I'll report it.

**Comment by apobekiaris** [comment]
feel free to ping me on the chat while u doing it

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [lab-Pipeline uses wrong artifacts #525 #545](https://github.com/eXpandFramework/DevExpress.XAF/commit/dcef4205f25e366f55a6f0bee4cad00daab3eaa6)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
