### ISSUE TITLE
ExcelImporter map detailview disabled after key member exists validation error

### ISSUE THREAD

**Issue by Kelbethor** [eXpandFramework/eXpand#547]
Hi, I'm quite a noob to xaf and totally to xpand.
On mapping excel to member I get ""KeyMemberExists" must be set to true." validation error and after that the screen doesnt work: Changing column at listview does nothing. 
Closing and reopening get the window totally disabled even clicking "reset" mappings option  for that import, other imports and new imports created. 
Window gets enabled again once the application is restarted.
Checked and member object has key on it.
I supose It's because the member to be mapped is a relation to other object and the key is string instead of oid. Could it be?

Using xaf 19.1.6.0 and xpand 19.1.602.0

**Comment by apobekiaris** [comment]
it shouldn't behave so strange in any case, so if u provide sample and test data and instructions on how to repro it I will provide a fix for such cases.

Now the validation is here
https://github.com/eXpandFramework/eXpand/blob/da838e97b3685b0c3c117ac9bb9e97c1250afbaa/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/BusinessObjects/ExcelColumnMap.cs#L90-L99

note the `!IsPersistentBO`

**Comment by Kelbethor** [comment]
Attached the business objects and a sample import file.

[547BusinessObjectsExcelImporter.zip](https://github.com/eXpandFramework/eXpand/files/3638531/547BusinessObjectsExcelImporter.zip)

**Comment by apobekiaris** [comment]
apologies for the delay I am now in this case however the reason i asked for a sample with data is to minimize the time spent as my resources are really limited. So please 

1. Install the Xpand.VSIX VS addon
1. using the VS New Project Wizard create a new Xpand Project And install the ExcelImporter there
2. Paste your objects in the new solution and remove all properties that do not related to this case
3. Provide a screenshot of the final configuration before the error or even better a screencast

Thanks.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
