### ISSUE TITLE
UnauthorizedAccessException - Visual studio restarts

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#549]
hello,

Since i migrated to the 19.600.2 i have this issue : 
This issue is taken from the evnetviewer because VS 19 restarts before running the app.

****This is a very serious issue as i cannot run my dev apps anymore.**** 

Might it be linked to the #519 ? If so i'm not sure to understand what 
"netstandard is now stored at $@"{Path.GetTempPath()}\\netstandard" you can add it there manually to avoid modifying the permissions" means. 

Application : devenv.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.UnauthorizedAccessException
   à System.IO.__Error.WinIOError(Int32, System.String)
   à System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   à System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   à System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   à System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   à System.IO.File.InternalWriteAllText(System.String, System.String, System.Text.Encoding, Boolean)
   à System.IO.File.WriteAllText(System.String, System.String)
   à Xpand.VSIX.Services.ModelMapperService+<>c__DisplayClass2_0.<BuildEventsOnOnBuildDone>b__7()
   à System.Reactive.Linq.ObservableImpl.Finally`1+_[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Dispose(Boolean)
   à System.Reactive.Sink`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Dispose()
   à System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   à System.Reactive.SafeObserver`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Dispose(Boolean)
   à System.Reactive.SafeObserver`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Dispose()
   à System.Reactive.AnonymousSafeObserver`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnCompleted()
   à System.Reactive.Sink`2[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnCompleted()
   à System.Reactive.TailRecursiveSink`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Done()
   à System.Reactive.TailRecursiveSink`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Drain()
   à System.Reactive.ConcatSink`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnCompleted()
   à System.Reactive.Sink`2[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnCompleted()
   à System.Reactive.Linq.ObservableImpl.SelectMany`2+ObservableSelector+_+InnerObserver[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnCompleted()
   à System.Reactive.TailRecursiveSink`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Done()
   à System.Reactive.TailRecursiveSink`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Drain()
   à System.Reactive.Linq.ObservableImpl.OnErrorResumeNext`1+_[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnError(System.Exception)
   à System.Reactive.Subjects.AsyncSubject`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnError(System.Exception)
   à System.Reactive.Linq.QueryLanguage+<>c__189`1[[System.Reactive.Unit, System.Reactive, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].<ToAsync>b__189_1(System.ValueTuple`2<System.Func`1<System.Reactive.Unit>,System.Reactive.Subjects.AsyncSubject`1<System.Reactive.Unit>>)
   à System.Reactive.Concurrency.Scheduler+<>c__75`1[[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ScheduleAction>b__75_0(System.Reactive.Concurrency.IScheduler, System.ValueTuple`2<System.Action`1<System.ValueTuple`2<System.__Canon,System.__Canon>>,System.ValueTuple`2<System.__Canon,System.__Canon>>)
   à System.Reactive.Concurrency.UserWorkItem`1[[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run()
   à System.Reactive.Concurrency.DefaultScheduler+<>c__5`1[[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Schedule>b__5_0(System.Object)
   à System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl+<>c.<QueueUserWorkItem>b__3_0(System.Object)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by apobekiaris** [comment]
nope #519 is a runtime exception and yours is not, u relate to #494 in short VS must run as admin, newer version will messabox if not and not crashing VS

**Comment by expand** [comment]
eXpand.lab release [19.1.602.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.1) includes commit that relate to this task:

* [VSIX: Cancel build if VS is not elevated #549 #494](https://github.com/eXpandFramework/eXpand.lab/commit/ad5625d4c7ca92edd8b35108005da3c8b99ec6fc)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
