### ISSUE TITLE
18.2.10 - How to Compile

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#550]
**Question**
I need to use DevEx 18.2.10, but the NuGet for eXpand only goes through 18.2.7. I used to build the source locally, but it appears that process has changed. What is the quickest way to get eXpand built against 18.2.10? Thanks!!

**Comment by apobekiaris** [comment]
1. downlload the source
2. Run 18.2.10 project converter 
3. Modify the Build.ps1 both version and sources

**Comment by capricciobob** [comment]
I pulled master and ran the project converter. In Xpand\Xpand.Xpo\DB\SchemaColumnSizeUpdater.cs line 25 AsyncLockHelper does not exist. That must be new after 18.2.

When I switch to the 18.2 branch and run the project converter, the build.ps1 gives two errors. 

1. Get-Feed : The term 'Get-Feed' is not recognized as the name of a cmdlet, function, script file, or operable program.
2. The term 'D:\NewGithub\eXpand\support\build\go.ps1' is not recognized as the name of a cmdlet, function, script..... that file is not in the source.

**Comment by apobekiaris** [comment]
>I pulled master 

checkout the 18.2.7 tag and run the 18.2.10 projectconverter there

**Comment by capricciobob** [comment]
![Error](https://user-images.githubusercontent.com/889492/65617113-363da000-df8a-11e9-9ed8-28bfbbe3fb5a.PNG)

**Comment by apobekiaris** [comment]
replace the Get-Feed -DX call with 

C:\Program Files (x86)\DevExpress 18.2\Components\System\Components\packages\

**Comment by capricciobob** [comment]
The support folder is empty so the new error is The term 'D:\eXpand-18.2.704.0\support\build\go.ps1' is not recognized as the name of a cmdlet

**Comment by apobekiaris** [comment]
staring from 19.1 Support is not a git SubModule anymore and will be download with the Sources as a normal folder. For past versions the submodule is loacated at https://github.com/eXpandFramework/Support download and put it in the Support folder in the root

**Comment by apobekiaris** [comment]
u should run ProjectConverter there as well

**Comment by capricciobob** [comment]
I'm just giving up for now. Sorry to waste your time. Here is the latest error.

 Errors: Package 'devexpress.document.processor 18.2.7' is not found in the following primary
                 source(s): 'C:\Users\rober\.nuget\packages\,https://api.nuget.org/v3/index.json,https://xpandnugetserv
                 er.azurewebsites.net/nuget,C:\Program Files (x86)\DevExpress
                 18.2\Components\System\Components\Packages'. Please verify all your online package sources are
                 available (OR) package id, version are specified correctly.

**Comment by apobekiaris** [comment]
havinf 18.2.7 in the GAC i remove all DX nuget from the build.ps1 located in Support/Build folder and was able to build. If 18.2.10 has no XAF breaking changes u should be able to build elese u have to open the breaking project and fix it manually 

[Build.zip](https://github.com/eXpandFramework/eXpand/files/3655104/Build.zip)

**Comment by apobekiaris** [comment]
unfortunately we have no instrastructure to support builds like 18.2.10 which is released outdated after a newer XAF version is out.

**Comment by apobekiaris** [comment]
if there are breaking changes u can look how it was fixed in a newer version of the file using git File history
