### ISSUE TITLE
MiddelTier throws ModelMapper required error

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#551]
Xpand 19.1.602.5 installed via 
pwsh Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  -Version '19.1.602.5' #-SkipGac -InstallationPath 'YOURPATH'"

and project created via XPand 19.1 solution wizard.

When running application server it gets:

System.NullReferenceException: '_xafWinAssembly check that ModelMapperModule is added to the RequiredModuleTypes collection'

repro project: https://www.dropbox.com/s/xzpkn1pamaj57f4/xpandTest191.Win.zip?dl=0

**Comment by krombipils** [comment]
I think this is related to my [issue](https://github.com/eXpandFramework/eXpand/issues/542): If you add the ModelMapper module, another exception is thrown

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Platform detection fails when MiddleTier #542 #551](https://github.com/eXpandFramework/DevExpress.XAF/commit/b20744c2d680f3693357415d34a21ae4c66271d9)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
