### ISSUE TITLE
Move the ViewEditMode Module reference to System Module

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#552]
Hi Tolis

Can you please move the ViewEditMode nuget reference from the ExelImporter module to the System module? This will add the reference in our product without doing this manually or adding the ExcelImporter module. The ViewEditMode reference is now only made in the ExcelImporter Module.

Thanks,
Jacob

**Comment by apobekiaris** [comment]
I do not understand where is the problem

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
