### ISSUE TITLE
Excel Importer - Dependencies

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#554]
Hi,

In one of my project, i need only ExcelImporter. 
In Module, module.win and module.web i have only the ExcelImporter dll in reference. 
But in Web and Win i have all of these. 

Does ExcelImporter use all of these ? 
![image](https://user-images.githubusercontent.com/41955268/65728601-bdd6fc00-e0bb-11e9-8fcc-7ef15e5af088.png)

**Comment by apobekiaris** [comment]
some of the references come from the system module which ExcelImproter depends on currently. In future version this depency will be removed. All other like Dashboard, Validation AutoCommit, MasterDetail, Reactive, ViewEditMode, SuppressConfirmation are used directly from the module.

**Comment by isatahiri** [comment]
OK thanks.

**Comment by apobekiaris** [comment]
if u use nuget packagereference they will be hidden as per nuget strategy

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
