### ISSUE TITLE
RePublish FasterFlect

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#556]
FasterFlect now lives in both eXpand and DevExpress.XAF repos and in many cases if you need the assembly you have to download the source and extract it. Nuget is a better solution than this process

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Switch to FasterFlect.Xpand #556](https://github.com/eXpandFramework/DevExpress.XAF/commit/52a78f6775205b5bb85f2652732345833aaaba14)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.8) includes commit that relate to this task:

* [Switch to FasterFlect.Xpand #556](https://github.com/eXpandFramework/eXpand.lab/commit/0b48e66dfc42ff77a0d7a22a327abaa6491dd54e)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
I think FasterFlect.Xpand is not yet published on your LAB NugetServer, is it?

**Comment by krombipils** [comment]
Just found it on the official nuget.org feed...

**Comment by krombipils** [comment]
Your [fasterflect repository](https://github.com/eXpandFramework/fasterflect) is not marked as a fork buunguyen/fasterflect. Was this done on purpose?

**Comment by apobekiaris** [comment]
there is no reason to fork an unmaintained project, this is now our responsibility, do u see anything wrong with this desicion?

**Comment by krombipils** [comment]
No, I think it is ok. But I like the idea of a fork, to see the relationship between the origin fasterflect and your repo.

**Comment by apobekiaris** [comment]
sure credits are to the authors of this great library as so copy rights are preserved in code wiki plus past commits from the original authors

**Comment by apobekiaris** [comment]
having the users go to the original unmainted wiki and issues only brings problems in my opinion as there will find no help there

**Comment by krombipils** [comment]
Everything is fine for me!

**Comment by apobekiaris** [comment]
great happy to clarify any decisions feel free to ask

**Comment by krombipils** [comment]
Could you please add the pdb to the fasterflect.xpand nuget package?

**Comment by krombipils** [comment]
The ugly CallMethod [bug](https://github.com/HelloKitty/fasterflect/issues/6) (see [issue 489](https://github.com/eXpandFramework/eXpand/issues/489) fasterflect.netstandard is also fixed in fasterflect.xpand

**Comment by apobekiaris** [comment]
>The ugly CallMethod bug (see issue 489 fasterflect.netstandard is also fixed in fasterflect.xpand

I am a bit confused here do u mean that this bug does not occur in our fork which is a fork of the original repeo and not the HelloKitty repo?  

>Could you please add the pdb to the fasterflect.xpand nuget package?

SourceLInk should be supported did u tried ?

https://github.com/eXpandFramework/Fasterflect/blob/7806f90e91bd57d2be601b08843a4dfc14a9ea79/Fasterflect/Fasterflect.csproj#L25-L28

**Comment by krombipils** [comment]
> that this bug does not occur in our fork 

Exactly! The implementation was changed in the HelloKitty fork (without any comment) and the change caused the issue. The CallMethod impl in the original repo/your fork seems to be fine.
 

> SourceLInk should be supported

Yeah, but I still need the pdbs for sourcelink to work?! See [SourceLink#package-pdb-in-nupkg](https://github.com/ctaggart/SourceLink#package-pdb-in-nupkg)

**Comment by apobekiaris** [comment]
I am checking it now, just note that our build uses portable pdb

**Comment by apobekiaris** [comment]
after I spent some time triying to make sourcelink to work, I decide to fall back to our [Update-Symbols](https://github.com/eXpandFramework/XpandPwsh/wiki/Update-Symbols). Latest version is indexed and tested

**Comment by expand** [comment]
eXpand.lab release [19.1.602.12](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.12) includes commit that relate to this task:

* [Update FasterFlect #556](https://github.com/eXpandFramework/eXpand.lab/commit/c454eb39da5962cb94a9b174616b9e78a0fafebb)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Update FasterFlect #556](https://github.com/eXpandFramework/DevExpress.XAF/commit/42f0720f61039807497251f946fd3f6b1bcc294c)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
