### ISSUE TITLE
Replace binary 3rd dependencies 

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#557]
There are still dependencies ()Harmony, ConcurrentCollections, ObservableCollections that will lead to the same problems as in  #556 , replace with Nuget packages

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Replace binary 3rd dependencies #557](https://github.com/eXpandFramework/DevExpress.XAF/commit/92e60d859de920bbb2449933b4947d365150567d)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.9](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.9) includes commit that relate to this task:

* [Replace binary 3rd dependencies #557](https://github.com/eXpandFramework/eXpand.lab/commit/d8932a8ab646024eb2222b07535a72d2cc491091)
* [Replace binary 3rd dependencies #557](https://github.com/eXpandFramework/eXpand.lab/commit/acc0cc9eacc84d2a4bceefa377043194804d7286)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
