### ISSUE TITLE
Expand 19.1.602.9: VersionConverter fails with 'Failed to resolve Xpand.XAF.Modules.Reactive.Extensions.ObservableTraceStrategy'

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#558]
Hi,
I just tried to upgrade to 19.1.602.9, but VersionConverter fails on build with 'Failed to resolve Xpand.XAF.Modules.Reactive.Extensions.ObservableTraceStrategy'

Maybe this is related to my old [issue](https://github.com/eXpandFramework/eXpand/issues/518)?
Do you have to bump versions of the Xpand.XAF modules again?

**Comment by apobekiaris** [comment]
602.9 uses the lab standalone and 602.10 the official from nuget where all versions are bumped for safety. However they both consume the packages as u do and they do not fail. First thought is that the difference between you and the Azure builds is that the later environment is always clean (VM machine). SO can u try clean your nuget cache?

I do not have more suggestions at the moment I need more data.

**Comment by krombipils** [comment]
After updating to 602.10, the issue is gone (without cleaning nuget caches).
Should I try to repro it again in 602.9?

But there is now another [issue](https://github.com/eXpandFramework/eXpand/issues/559) on nuget restore

**Comment by apobekiaris** [comment]
do not spent your time in vain it is already noted however no automation is possible for this case at the moment as we do not have a clear picture.

**Comment by krombipils** [comment]
So I can/should close the issue for now?

**Comment by apobekiaris** [comment]
yes u can the `ObservableTraceStrategy` its a shared enum to all packages that depend on the Reactive. It is used from the Reactive logger. For now this info is noted, although there is code to pump all version once the reactive change something got overlooked. Anyway for safety at the moment all versions pumped again when official

**Comment by krombipils** [comment]
Thank you for the explanation. You changed/restructured quite a lot of the eXpand codebase and it is not always easy to understand what's going on.

**Comment by apobekiaris** [comment]
this is the reason I try to elab once I can, but bottom line the CI does and will continue to handle anything related to release. Most of the packages depend on the Reactive package which is like a base, in the future there will be extra dependcies to packages born from #470 but the only common package will always be the Reactive. Addition to it like Reactive.Win, Reactive.Logger etc are standalone packages. The dependecies are visible in each package ReadMe.md and its generation as  everything is automated
