### ISSUE TITLE
Expand-Button in LayoutControlGroup

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#560]
Hi,

how can I set the Expand Button in a LayoutControlGroup (in the Model)?
In 19.1.402 I could set a special Modeladaptor to a LayoutGroup, f.e.
LayoutGroup Id="Item1" ModelAdapter="LayoutControlGroupLeftExpand"

**Comment by apobekiaris** [comment]
looks like I missed this one please post your existing model configuration for reference

**Comment by CWolffIF** [comment]
After opening the Model in the Designer all positions are deleted.
But here is an reference from the old project
`  <ModelAdapterContexts>
    <ModelAdapters Id="Default">
      <OptionsGridView Id="GridView">
        <OptionsView ColumnAutoWidth="False" ShowPreview="" />
      </OptionsGridView>
      <LayoutControlGroup Id="LayoutControlGroupLeftExpand" Expanded="True" ExpandOnDoubleClick="True" ExpandButtonVisible="True" ExpandButtonMode="Normal" HeaderButtonsLocation="Default" TextLocation="Left" IsNewNode="True">
        <ModelAdapters IsNewNode="True">
          <LayoutControlGroupModelAdapter Id="Default" ModelAdapter="LayoutControlGroupLeftExpand" Index="0" IsNewNode="True" />
        </ModelAdapters>
      </LayoutControlGroup>
      <LayoutControlGroup Id="LayoutControlGroupTopExpand" ExpandButtonVisible="True" Enabled="" Expanded="True" ExpandButtonMode="Normal" ExpandOnDoubleClick="True" HeaderButtonsLocation="Default" TextLocation="Top" IsNewNode="True">
        <ModelAdapters IsNewNode="True">
          <LayoutControlGroupModelAdapter Id="Default" ModelAdapter="LayoutControlGroup" Index="0" IsNewNode="True" />
        </ModelAdapters>
      </LayoutControlGroup>
    </ModelAdapters>
  </ModelAdapterContexts>`

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Added LayoutGroupControl support #560](https://github.com/eXpandFramework/DevExpress.XAF/commit/3ca8d3076f0b6194e679ed531bfa5a3545e275a1)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
at the moment Map contexts are not implemented see the workaround at #548

you will get updated again once the package integrated with the main packages

**Comment by expand** [comment]
eXpand.lab release [19.1.602.14](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.14) includes commit that relate to this task:

* [ModelMapper: Added LayoutGroupControl support #560](https://github.com/eXpandFramework/eXpand.lab/commit/183f96e4f2abff744c55814a206c6b39ada40967)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Superb, it works.
