### ISSUE TITLE
ProvidedAssociation Bug/Error

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#561]
Hi

I have use ProvidedAssociation in my Module. This is working fine with Administrator rights. But I login from user throw exception. 

Last three days to investigate how exception come on user. When I disable ProvidedAssociationController then user login successfull

Find enclosed exception log and sample solution

I ahve associatied Customer & User by ProvidedAssociation
[Email.txt](https://github.com/eXpandFramework/eXpand/files/3680747/Email.txt)

Kindly Rename Sample Solution Email.txt to Email.rar

[log.txt](https://github.com/eXpandFramework/eXpand/files/3680705/log.txt)

**Comment by apobekiaris** [comment]
The stack trace you posted does not include Xpand as so is hard to even guess whats going on. Further more ProvidedAssociated operates before the TypesInfo is constructed and has nothing to do with permissions. 

To investigate further I have to ask for a sample that the problem is reproducible

**Comment by cevious** [comment]
right in trace log noting related to providedassociation. So  I have investigate from last three days one by one controller nad also i investigate providedassociasioncontroller but no exception.

But when I exclue from project or remove ProvidedAssociation attribute from project then show exception when login from user

Problem is i have used providedassotion attribute in project 50 to 60 time but now we implemeing security then i face problem.

I think probably problem with XAF dynamic member

i have attached sample solution in previous post. kindly check

**Comment by apobekiaris** [comment]
hmm yes i missed your attachment apologies however it is very hard to fix it to compile as especially the Module.Win has a great number of references that are unused and they result in failing when compile. Please create an empty solution install only the packages u used and paste your code.

or modify the attached EmailTester solution which has Security installed 
[Email.zip](https://github.com/eXpandFramework/eXpand/files/3681543/Email.zip)

**Comment by cevious** [comment]
[Email.txt](https://github.com/eXpandFramework/eXpand/files/3681636/Email.txt)
rename .txt to .rar
FInd enclosed Latest sample remove refrences only security & system

**Comment by apobekiaris** [comment]
I can repro the issue now thanks

**Comment by cevious** [comment]
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by expand** [comment]
eXpand.lab release [19.1.602.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.13) includes commit that relate to this task:

* [ProvidedAssociationAttribute: AssociatedMemberInfo is null #561](https://github.com/eXpandFramework/eXpand.lab/commit/7d4d9356c54316158413c9c0f08d075d911b13d3)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by cevious** [comment]
Issue rectified by add refresh

[ProvidedAssociationsController.txt](https://github.com/eXpandFramework/eXpand/files/3692902/ProvidedAssociationsController.txt)

Add in ProvidedAssociationController=>CreateMemberInfo Method

typesInfo.RefreshInfo(typeToCreateOn);
typesInfo.RefreshInfo(memberInfo.Owner.ClassType);

Also You can use My ProvidedAssociatioController with more Feature

**Comment by apobekiaris** [comment]
>Issue rectified by add refresh

this was my solution also, did it not work?

**Comment by cevious** [comment]
Yes it is working on User right

I am using expand from since long.

Now you can rectified this code by minor change or add latest version of ProvidedAssociation you can add to your eXpand nugetServer

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by apobekiaris** [comment]
yes I will review and update u again 

thanks a lot

**Comment by apobekiaris** [comment]
thnks for the suggested changes again, to my understanding you only provided Browsable support to the existing implementation. However there is a dedicated attribute to this and I do not see the reason to pollute the current implementation. Thinking similar on may merge all XAF attributes into one??

**Comment by cevious** [comment]
Two changes done
1.) browsable false on anothet side
2.) doesn’t required to define  association name

Thanks & Regards

Hemant
Sent from my iPhone

On 06-Oct-2019, at 11:31 AM, Apostolis Bekiaris <notifications@github.com<mailto:notifications@github.com>> wrote:


thnks for the suggested changes again, to my understanding you only provided Browsable support to the existing implementation. However there is a dedicated attribute to this and I do not see the reason to pollute the current implementation. Thinking similar on may merge all XAF attributes into one??

**Comment by apobekiaris** [comment]
>2.) doesn’t required to define  association name

so how does it know where to relate in case of muplite associations?

**Comment by apobekiaris** [comment]
cause I remember there was sucvh a feature at some point but we drop it but cannot remember why
