### ISSUE TITLE
EnumRepositoryItemGridListEditorController: RepositoryItemEnumEdit does not contain the localized values

### ISSUE THREAD

**Issue by esparagis** [eXpandFramework/eXpand#562]
Since 19.1.5 in the ListViews, enum editors ignores the localized values.

For a not editable ListView I found a solution by removing the ```gridColumn.ColumnEdit = new RepositoryItemTextEdit();``` in the GetData method:

```        
private (GridColumn column, RepositoryItem repositoryItem, IMemberInfo MemberInfo)[] GetData(GridListEditor gridListEditor) {
            var columns = View.Model.Columns.Where(MemberTypeIsEnum).ToArray();
            return columns.Select(info => {
                var gridColumn = FindColumnByModel(gridListEditor, info);
                if (gridColumn != null) {
                    var tuple = (column: gridColumn, repositoryItem: gridColumn.ColumnEdit,
                        info.ModelMember.MemberInfo);
                    // gridColumn.ColumnEdit = new RepositoryItemTextEdit(); // removed
                    return tuple;
                }
                return default;
            })
                .Where(_ => _ != default)
                .ToArray();
        }
```
![InkedCapture2_LI](https://user-images.githubusercontent.com/16288692/66041470-9c926780-e522-11e9-91c7-607502c55131.jpg)

But when the ListView is editable the editor displays not localized values.

![Capture](https://user-images.githubusercontent.com/16288692/66040570-7ec40300-e520-11e9-952c-ca5b52ceacc8.PNG)

From what I have seen, the problem is inside the GridViewOnCustomRowCellEdit event handler where the repository items are generated using the 
```var values =EnumsNET.NonGeneric.NonGenericEnums.GetValues(data.memberInfo.MemberType).ToArray();```

I tried to solve the issue by using an EnumDescriptor according to this https://docs.devexpress.com/eXpressAppFramework/DevExpress.ExpressApp.Utils.EnumDescriptor

Unfortunately I haven't found a way to solve it.

**Comment by apobekiaris** [comment]
possible dublicate of #521 can u try the related lab build or if u cannot upgrade u can disable the existing controller and get the patched from the lab
https://github.com/eXpandFramework/eXpand.lab/blob/89d093391c4e382ab54a4b05747d82b70ce1f17d/Xpand/Xpand.ExpressApp/Xpand.ExpressApp.Win/SystemModule/EnumRepositoryItemListViewController.cs

**Comment by apobekiaris** [comment]
if u still cannot resolve using my suggestion provide sample app and data to research it further

**Comment by esparagis** [comment]
I checked the patched controller from lab and works fine.
Thank you
