### ISSUE TITLE
DrillDown by SQLQuery/Procedure

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#563]
Hi

I am using XAF since 2008 for my org application. THis is greate technalogy ever made for developement made easy.

One Idea/Requirement in mind and also will be great  addon on XAF
DrillDown LIstView/TreeView/PivotGrid from complex SQL/Procedure on RunTime something like Business Intelligence (BI)

XAF Listview run on Generated Model View. I have made report by coding on nonpersistent class but everything in coding.  But problem is whenever you change in SQL/Procedure you need to rewrite class and build again.

Proposed Solution
1.) Generate Model like LINQCollection or any other wayout. Or Generate class from SQL/Procedure and update view model and link with ProcessListViewController

Thanks

**Comment by apobekiaris** [comment]
did u tried to utilize Dynamic classes out of WorldCreator?

**Comment by cevious** [comment]
I have tried worldcreater but I have to create class on runtime. But requirement is to generate class directly from sql/procedure with data polulated with query and if any parameter dynamic popup window for parameter

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by apobekiaris** [comment]
At the moment the road map is to support and do not enhance with complex functionality existing modules of this repo and gradually create standalone full tested packages in the DevExpress.XAF repository out of them. There any complex implementation makes sense as without the tests/docs there is no way to further develop anything that lasts and we will spent our time in vain.

>Or Generate class from SQL/Procedure and update view model and link with ProcessListViewController

After WC is such a package I could touch it again.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
