### ISSUE TITLE
The collection with type='Pager' already exists.

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#564]
Hello,

I migrated from the 19.1.602.1 to the 19.1.602.13. 
Since that when i run the app from VS 2019 i have the following error in ASP : 
![image](https://user-images.githubusercontent.com/41955268/66165683-94771c80-e635-11e9-9b48-b0044c5672a4.png)

And the page editors are frozen. 
Does that talk to you  ?

BR
ISA

**Comment by isatahiri** [comment]
the detail : 
Unchecked runtime.lastError: The message port closed before a response was received.
VM455:6 Uncaught ReferenceError: ASPxClientRoundPanel is not defined
    at eval (eval at _aspxRunStartupScriptsCore (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_46,1_32,1_48,1_9-6g_tj:6666), <anonymous>:6:20)
    at _aspxRunStartupScriptsCore (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_46,1_32,1_48,1_9-6g_tj:6666)
    at _aspxRunStartupScripts (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_46,1_32,1_48,1_9-6g_tj:6639)
    at Object.ASPx.FinalizeScriptProcessing (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_46,1_32,1_48,1_9-6g_tj:6633)
    at Object.ASPx.OnScriptLoadCallback (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_46,1_32,1_48,1_9-6g_tj:6710)
    at HTMLScriptElement.eval (eval at _aspxProcessScripts (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_46,1_32,1_48,1_9-6g_tj:6596), <anonymous>:3:6)

**Comment by isatahiri** [comment]
I opened a ticket at DX support too : [T820548](https://www.devexpress.com/Support/Center/Question/Details/T820548/xaf-error-in-asp-the-collection-with-type-pager-already-exists) because it looks a DX issue. Please let me know if it is in your side.

**Comment by apobekiaris** [comment]
Without repro sample unfortunately I cannot

**Comment by isatahiri** [comment]
Well I delete all generated dll's run again i do not have the error.

**Comment by apobekiaris** [comment]
whats a generated dll?

**Comment by isatahiri** [comment]
I will investigate and let you know

**Comment by isatahiri** [comment]
in my project i run a batch file which deletes all the generated files. Often i used to have something clean and if needed make it lighter for sharing the project  :
c:
cd "C:\Users\isata\Documents\PME Projects\PME_Affaire\PME_Affaire.Module\"
rmdir  Bin /s /q
mkdir Bin 
rmdir  obj /s /q
mkdir obj 

cd "C:\Users\isata\Documents\PME Projects\PME_Affaire\PME_Affaire.Module.Web\"
rmdir  Bin /s /q
mkdir Bin 
rmdir  obj /s /q
mkdir obj 

cd "C:\Users\isata\Documents\PME Projects\PME_Affaire\PME_Affaire.Module.Win\"
rmdir  Bin /s /q
mkdir Bin 
rmdir  obj /s /q
mkdir obj 

cd "C:\Users\isata\Documents\PME Projects\PME_Affaire\PME_Affaire.Web\"
rmdir  Bin /s /q
mkdir Bin 
rmdir  obj /s /q
mkdir obj 

cd "C:\Users\isata\Documents\PME Projects\PME_Affaire\PME_Affaire.Win\"
rmdir  Bin /s /q
mkdir Bin 
rmdir  obj /s /q
mkdir obj 

cd "C:\Users\isata\Documents\PME Projects\PME_Affaire\SnapModule\"
rmdir  Bin /s /q
mkdir Bin 
rmdir  obj /s /q
mkdir obj 

pause

**Comment by isatahiri** [comment]
After running this it works

**Comment by apobekiaris** [comment]
so it is now fixed or what?

**Comment by isatahiri** [comment]
Well yes but i always have delete generated files in VS. That's new. But at least it works

**Comment by isatahiri** [comment]
What does the code : -915408701 means ? 

ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenDetailViewCreated(166): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.DetailViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenDetailViewCreated(166): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.DetailViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
ReactiveModule Information: -915408701 : XafApplicationRXExtensions.WhenListViewCreated(183): OnNext((PME_Affaire.Web.PME_AffaireAspNetApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))
04.10.19 00:14:34.881	cswlmy4rllhbjwf2p32sqa11	Action 'New' done

**Comment by apobekiaris** [comment]
provide more info how this log is generated

**Comment by isatahiri** [comment]
I do not have more. I can send you the project... 
![image](https://user-images.githubusercontent.com/41955268/66168463-98a73800-e63d-11e9-9c1f-dcc9b96d618e.png)

**Comment by isatahiri** [comment]
Actually yes it was at the very beginning. 
My default.aspx starts with : 
<%@ Page Language="C#" AutoEventWireup="true" Inherits="Default" EnableViewState="false" ValidateRequest="false" CodeBehind="Default.aspx.cs" Async="true" %>

[Trace.txt](https://github.com/eXpandFramework/eXpand/files/3688307/Trace.txt)
. Again a asynchronous issue :

**Comment by isatahiri** [comment]
I think i saw in one ticket that i should remove the system.reactive and use only Xpand.XAF.Modules.Reactive. Right ?

**Comment by apobekiaris** [comment]
the number is unsuable info just a hashcode
https://github.com/eXpandFramework/DevExpress.XAF/blob/b8536326589269000a9d5fd98ca907e3265bc134/src/Modules/Reactive/Extensions/TraceExtensions.cs#L140

the async=true is not a requirement anymore

>Type:       InvalidOperationException
	Message:    Impossible de démarrer une opération asynchrone pour le moment. Les opérations asynchrones peuvent être démarrées uniquement depuis un gestionnaire ou un module asynchrone, ou lors de certains événements du cycle de vie de la page. Si cette exception a été levée durant l'exécution d'une page, vérifiez que celle-ci est marquée de la façon suivante : <%@ Page Async="true" %>. Cette exception peut aussi indiquer une tentative d'appeler une méthode « async void », qui n'est pas généralement pris en charge au sein de traitement d'une demande ASP.NET. À la place, la méthode asynchrone doit retourner une tâche, et l'appelant doit l'attendre.
	Data:       0 entries
	Stack trace:

this is a missleading message without debugging cannot say much

**Comment by apobekiaris** [comment]
System.Reactive throws like IEnumerable so it is not possible to tell from the stack what happen before. I have deveoped a logger for this purpose

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger

**Comment by isatahiri** [comment]
I just sent you a link by email to my project.

**Comment by isatahiri** [comment]
I will use the Reactive.Logger asap. Sorry i did not see it.

**Comment by isatahiri** [comment]
Please let me know if you can download it so i remove the link.

**Comment by apobekiaris** [comment]
got it

**Comment by apobekiaris** [comment]
I can repro the problem however I did not found a solution as I did not debug further. What I did is removed ALL 3rd party refrences and code and the problem continue. If I was u I will continue removing stuff until I find the cause of the error. If you need my remove all copy of your solution let me know

**Comment by apobekiaris** [comment]
note that the log is clear og eny exceptions

**Comment by apobekiaris** [comment]
i also recommend u switch to nuget packagesreference format cause I found many dependecies that are not used and nuget can successfully remove this support weight

**Comment by isatahiri** [comment]
> If I was u I will continue removing stuff until I find the cause of the error.
What do you mean ? Do you suspect that the issue is not coming from the Framework ?
You can keep the last solution and remove old copies as it is moving fast. 

> note that the log is clear og eny exceptions
I'm not sure what it means

> Using nuget packagereference instead
Last time i tried i had many version depedencies issue so i gave up. Maybe i should try again

**Comment by apobekiaris** [comment]
I will try to be more clear. I remove all Xpand references and also all other references except Devexpress and then run the web app and got the same exception, so I assume it is something else. I also checked the log when references removed and no exception found there

Continuing to remove parts of your solution will most probably get to the root of the problem.

**Comment by apobekiaris** [comment]
and as this solution is not so large I would start the opposite way, that is from a blank empty solution where I would paste the BO objects (commenting a few attributes or even better rewriting them dynamically so I could repeat this operation in the future if necessary). Then paste the few controllers and run without 3rd part libs and finally start to register the 3rd part modules. This way (having a clear/decoupled system you will be able to track down any problem fast at any time without even understand the root u will be able to blame something. It is a common way to resolve problems. Automatically generated coded does not help as it is time consuming to remove it, if u see Xpand does not use designers nowhere, it registers controllers. modules etc in code so by commenting them out I am able to track the problem if I do not understand it.

**Comment by isatahiri** [comment]
I did remove all references, empty the unused Nuget Packages one by one. And the error was still there. So I had a solution consuming only devexpress assemblies and the error was still there. 
Then by curiosity i tried in a seconf browser and it worked. So i deleted cash from Chrome and now it works. 

At the end i do not know that causes this. I will add Expand and see. By the way, when do you expect the Excel Module as standalone ?

**Comment by apobekiaris** [comment]
tried some time ago but there are many dependecies to system which need to carefully packaged out so I cannot estimate

**Comment by isatahiri** [comment]
OK thanks for the info Tolis !

**Comment by isatahiri** [comment]
OK, i could not find the source of the error but I really suspect that all dependencies as you said we causing this. 

Now i would like to use ExcelImporter in one of my project without installing Expand via PowerShell. From nuget would that be enough ? 
![image](https://user-images.githubusercontent.com/41955268/66487656-04115f80-eaad-11e9-89aa-e3528f4b33c3.png)

**Comment by apobekiaris** [comment]
of course

**Comment by isatahiri** [comment]
so i add then, manually add the module in each module classes.  Nothing else for Excel Importer is needed as the nuget will bring its own dependencies ?  Sorry for dummy questions ! Better ask than do mistakes :-)

**Comment by apobekiaris** [comment]
yes feel free to ask, nuget have all the dependencies u need, using the packagerefrence format all dependecies for the excelimporter will be handled as one unless u excplicity install packages

**Comment by isatahiri** [comment]
Great ! Thanks Tolis !

**Comment by isatahiri** [comment]
I tried but now it take the new version. Is it too early 604 ? 
![image](https://user-images.githubusercontent.com/41955268/66490521-961b6700-eab1-11e9-933f-62647bc14f64.png)

**Comment by isatahiri** [comment]
stack : 
Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'DevExpress 19.1 Local', 'Microsoft Visual Studio Offline Packages'.

**Comment by apobekiaris** [comment]
no 604 is online does the same problem exists on an empty xaf solution

**Comment by isatahiri** [comment]
![image](https://user-images.githubusercontent.com/41955268/66491363-e646f900-eab2-11e9-875c-b2e6d004167d.png)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Remove akarnokd.reactive_extensions #564 #571](https://github.com/eXpandFramework/DevExpress.XAF/commit/f07e3e40e1eb8f03338b228037ac20a399dc97fc)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
just for info, it seems that different version of MonoCecil are used in excelimporter. Nugets proposes to consolidate : 
![image](https://user-images.githubusercontent.com/41955268/66505390-91fc4300-eacb-11e9-82b1-4e18698cfb4f.png)

**Comment by isatahiri** [comment]
After installing, on the first run, i had the same issue as last time. But after clearing the cash on chrome. it worked. 

On more think : the Expand.Persistent.baseimpl is set to copy local = true in my module.web but it is not being copyied in the release folder the the web module.  I have to copy it manually. 

Beside this its working fine again :-)

**Comment by apobekiaris** [comment]
>On more think : the Expand.Persistent.baseimpl is set to copy local = true 

this is enviromental issue on your side u can however add a post-build event to copy on each build

**Comment by expand** [comment]
eXpand.lab release [19.1.604.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.604.2) includes commit that relate to this task:

* [Bump Mono.Cecil to 0.11.0 #564](https://github.com/eXpandFramework/eXpand.lab/commit/6cc40c9052d568ebeda67c1926790d1a018634ac)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
see #661
