### ISSUE TITLE
ExcelImport Module

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#567]
Issue.
Excel Sheet selection doesnot working. Import Workbook all sheet and merge to single

Required Help
2.) I have import SIngle Class data and working fine 
3.) How can i import multi Associciation/Object data

Any documentation/help/Sample for ExcelImport

**Comment by apobekiaris** [comment]
in an 1-M association we first import the 1 part. The module will match it against the Map you have declared using either keys either from the UI (KeyMaps tab) or u can use the ExcelImportKeyAttribute in code. 

example Gender->Customer we first import the Gender and then the Customer. When in customer and we create the ExcelMap that matches the Excel Columns with the Customer Type properties we can define a key for the Gender type which is different from the db key. For this the next method is used which does the lookup as I mentioned before

https://github.com/eXpandFramework/eXpand/blob/da838e97b3685b0c3c117ac9bb9e97c1250afbaa/Xpand/Xpand.ExpressApp.Modules/ExcelImporter/Services/ImportExtension.cs#L133-L139

**Comment by apobekiaris** [comment]
>Excel Sheet selection doesnot working. Import Workbook all sheet and merge to single

I fail to understand u, please provide screenshot and sample solution with data if u think is required

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
