### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#568]
In [Reactive.Logger.Hub readme](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub) the module is named `typeof(Xpand.XAF.Modules.Reactive.Logger.HubModule)` but actually it is `typeof(Xpand.XAF.Modules.Reactive.Logger.Hub.ReactiveLoggerHubModule)`

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Minor documentation issue #568](https://github.com/eXpandFramework/DevExpress.XAF/commit/d58d7c1926e57dc519dfd95f2ead881750a43a94)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
One reference is fixed, but there is still `RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Reactive.Logger.HubModule));` in the docu

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
