### ISSUE TITLE
Reactive.Logger.Hub transmit messages on realtime

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#570]
right now messages are buffer until logon and then starts transmission, reasoning is that the messages are stored to the local db which is valid only after logon. However cases like #542 need real time transmission

**Comment by rSeeFip** [comment]
Thru Update from 602 to 603 I've  following issue after login, can this concern to the #542 
but its on standard Win App

Der Typ "DevExpress.Utils.Extensions.UtilsExtensions" in der Assembly "DevExpress.Utils.v19.1, Version=19.1.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" konnte nicht geladen werden.

   bei Xpand.XAF.Modules.Reactive.Logger.ModelReactiveModuleLogger.ReactiveLogger(IModelReactiveModules reactiveModules)
   bei Xpand.XAF.Modules.Reactive.Logger.ModelReactiveModuleLogger.<>c.<ReactiveLogger>b__0_0(IModelReactiveModules modules)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   bei System.Reactive.ExceptionHelpers.Throw(Exception exception)
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Do`1.Actions._.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   bei System.Reactive.ObserverBase`1.OnNext(T value)
   bei Xpand.XAF.Modules.Reactive.Extensions.TraceExtensions.<>c__DisplayClass6_1`1.<Trace>b__2(TSource v)
   bei System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei DevExpress.ExpressApp.XafApplication.OnLoggedOn(LogonEventArgs args)
   bei DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   bei DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)

**Comment by apobekiaris** [comment]
it is now building on lab can u please update and let me know 19.1.603.1

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
