### ISSUE TITLE
Static analysis checks against version patching

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#572]
It should be possible to enumerate all 18.2.7 types/methods used from Standalone packages and check them on each build against latest DX version to avoid cases like   #571

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Run tests against latest #572](https://github.com/eXpandFramework/DevExpress.XAF/commit/a472702267806cf8bbd6bce549440c137d03c08f)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Generate compatibility matrix #572](https://github.com/eXpandFramework/DevExpress.XAF/commit/db9488ac844147d195bc1d0d254520c086fe1ad6)
* [Run tests against the latest minor of each Major version for the last 3 years #572](https://github.com/eXpandFramework/DevExpress.XAF/commit/f94f36b83d26c8245287741e8558abd890b65b46)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/DevExpress.XAF#compatibility-matrix
