### ISSUE TITLE
19.1.604 Upgrade - reactive_extensions

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#574]
When I try to update the NuGet References to 19.1.604 I get the following error.

Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'DevExpress 18.1 Local', 'DevExpress 18.2 Local', 'DevExpress 19.1 Local', 'DevExpress 19.2 Local'.

**Comment by apobekiaris** [comment]
it is broken will publish tomorrow but 604.1 on lab should work

**Comment by capricciobob** [comment]
Thank you very much!
