### ISSUE TITLE
19.1.604 - CloneMemberValueModule

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#575]
I know the current NuGet release is broken. Is this error related?

Running win project after upgrading to 19.1.604

DevExpress.ExpressApp.DC.ObjectCreatingException: 'Unable to create an instance of the "Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule" type.
Reason: "The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception."'

Inner Exceptions:
TypeInitializationException: The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception.

FileNotFoundException: Could not load file or assembly '0Harmony, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958' or one of its dependencies. The system cannot find the file specified.

**Comment by apobekiaris** [comment]
nope does not look relatedthats a dependency of the Xpand.XAF.Module.Reactive package located in the Xpand.Patcher. From what  I see the nuget is valid

![image](https://user-images.githubusercontent.com/159464/66532413-fd6c0200-eb17-11e9-9d39-10332b44f47c.png)

do u have a way to repro it?

**Comment by apobekiaris** [comment]
is the assembly in your bin?

**Comment by capricciobob** [comment]
The 0Harmony assembly is not being copied to the bin. When I place it there manually, I can debug.

**Comment by apobekiaris** [comment]
can u provide a sample so I can debug further? just install some modules that u in an empty xaf app and see if it works

**Comment by capricciobob** [comment]
I created a blank XAF app and used NuGet to add one module, Xpand.XAF.Modules.CloneMemberValue. It will not build. See attached.
[Fuzion.zip](https://github.com/eXpandFramework/eXpand/files/3713410/Fuzion.zip)

**Comment by capricciobob** [comment]
Interesting, when I closed the solution and reopened, it let me build. The 0Harmony is in the bin. There must be a reference issue in my project. I will keep digging.

**Comment by capricciobob** [comment]
I opened the new .csproj in text editor and copied the reference line and all is good now.

<Reference Include="0Harmony, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, processorArchitecture=MSIL">
      <HintPath>..\packages\Xpand.Patcher.1.0.1\lib\net461\0Harmony.dll</HintPath>
    </Reference>
