### ISSUE TITLE
Visual Studio 2019 Upgrade

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#576]
I started using VS 2019 with an existing project. I get the following error. How to resolve?

Exception occurs while initializing the 'Xpand.XAF.Modules.ModelMapper.ModelMapperModule' module: ModelMapper requires Xpand.VSIX which is not installed in VS 16

**Comment by apobekiaris** [comment]
How about following the message to the letter? :)
Xpand.VSIX is avaiable at https://github.com/eXpandFramework/eXpand/releases

**Comment by apobekiaris** [comment]
all its feature expect the Xpand New Project wizard are version agnostic so u do not need to update the package often

**Comment by capricciobob** [comment]
Found it! I had installed it right after I upgraded to 2019. I ran the installer again and it worked, thanks.
