### ISSUE TITLE
Posh Installer

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#579]
I am running the install command as suggested at this link since the MSI installers are gone. https://github.com/eXpandFramework/XpandPwsh/wiki/Install-Xpand

Getting the error in this screenshot.
![posh](https://user-images.githubusercontent.com/889492/66599634-b4489c00-eb71-11e9-9019-8a09ce96b7cc.PNG)

**Comment by apobekiaris** [comment]
it looks like u use a very old version of XpanPosh which does not even exists anymore
trye uninstall it and install the XpandPwsh instead

```ps`
Uninstall-Module XpandPosh
Install-Module XpandPwsh
```

**Comment by capricciobob** [comment]
PS C:\WINDOWS\system32> Install-Module XpandPwsh

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PackageManagement\Install-Package : The following commands are already available on this system:'Clear-NugetCache,Clear
-ProjectDirectories,ConvertTo-Object,ConvertTo-PackageObject,Disable-ExecutionPolicy,Find-XpandPackage,Get-CallerPrefer
ence,Get-ChocoPackage,Get-DevExpressVersion,Get-DotnetCoreVersion,Get-DxNugets,Get-GitLastSha,Get-MsBuildPath,Get-NUget
PackageMetadataVersion,Get-NugetPath,Get-PackageFeed,Get-PackageSourceLocations,Get-RelativePath,Get-XmlContent,Get-Xpa
ndPackages,Get-XpandPath,Get-XpandVersion,Install-Chocolatey,Install-Devexpress,Install-SubModule,Install-Xpand,Invoke-
Parallel,Invoke-Retry,New-Command,Publish-NugetPackage,Remove-ProjectNuget,Set-VsoVariable,Uninstall-ProjectAllPackages
,UnInstall-Xpand,UnPublish-NugetPackage,Update-AssemblyInfo,Update-AssemblyInfoVersion,Update-HintPath,Update-NugetPack
age,Update-ProjectPackage,Update-ProjectTargetFramework,Update-Symbols,Use-NugetAssembly,Checkpoint-GitHubIssue,Close-G
ithubIssue,Get-Distinct,Get-GitHubCommitIssue,Get-GitHubMilestone,Get-GitHubRelease,Get-GitHubRepositoryTag,Get-NugetPa
ckage,Get-NugetPackageSearchMetadata,New-GithubReleaseNotes,New-GithubReleaseNotesTemplate,Publish-GitHubRelease,Update
-GitHubIssue,Update-NugetProjectVersion'. This module 'XpandPwsh' may override the existing commands. If you still
want to install this module 'XpandPwsh', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage

**Comment by capricciobob** [comment]
Is -AllowClobber okay to set as suggested in the error?

**Comment by capricciobob** [comment]
Got further this time..... 
![install2](https://user-images.githubusercontent.com/889492/66601774-acd7c180-eb76-11e9-8484-26fce9a5a081.PNG)

**Comment by capricciobob** [comment]
Needed the 19.1.603.0   the .0 at the end.

**Comment by apobekiaris** [comment]
-AllowClobber is not ok u have mu;lti version in your system confirm by

```ps1
Get-Module *xpand* -listavailable
```
