### ISSUE TITLE
Couldn't install eXpandImportWizard.

### ISSUE THREAD

**Issue by XAFxpand** [eXpandFramework/eXpand#580]

**Comment by XAFxpand** [comment]
I got a following error message when I tried to install eXpandImportWizard (19.1.604)  from Manage NuGet Packages on VS2015 project(xaf v19.1.15). I tried to install all xpand v19.1.50x but all failed with the same error.  I tried to upgrade from v18.1.4.1.  Please advise.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package **'Fasterflect.Xpand 2.0.6'.** You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by apobekiaris** [comment]
604 is broken will update asap #571

**Comment by XAFxpand** [comment]
Thanks for the update for 19.1.605 but I got the same error as followings.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Fasterflect.Xpand 2.0.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by apobekiaris** [comment]
452 is not supported update to 461

**Comment by apobekiaris** [comment]
sorry i miss this before

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
