### ISSUE TITLE
Excel Importer : WEB - InvalidOperationException

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#581]
Hello,

I'm on the 19.1.604.3 and the excel importer in ASP does not work. 

[Trace.txt](https://github.com/eXpandFramework/eXpand/files/3719548/Trace.txt)

`The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandListView, ID:TraceEvent_ListView' view to WebWindow:
Impossible de démarrer une opération asynchrone pour le moment. Les opérations asynchrones peuvent être démarrées uniquement depuis un gestionnaire ou un module asynchrone, ou lors de certains événements du cycle de vie de la page. Si cette exception a été levée durant l'exécution d'une page, vérifiez que celle-ci est marquée de la façon suivante : <%@ Page Async="true" %>. Cette exception peut aussi indiquer une tentative d'appeler une méthode « async void », qui n'est pas généralement pris en charge au sein de traitement d'une demande ASP.NET. À la place, la méthode asynchrone doit retourner une tâche, et l'appelant doit l'attendre.
	Data:       0 entries
	Stack trace:

   à DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   à DevExpress.ExpressApp.Web.ShowViewStrategy.ShowViewInCurrentWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   à DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   à DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   à DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   à DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   à DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   à DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)`

**Comment by isatahiri** [comment]
I confirm that it works well on winform

**Comment by isatahiri** [comment]
Note also that we should replace this message as the import is already committing into the database : 
![image](https://user-images.githubusercontent.com/41955268/66685231-26a5a300-ec7c-11e9-8dc2-bc07d5caa240.png)

**Comment by apobekiaris** [comment]
I can repro it

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveLoggerService RefreshViewDataSource fails the web #581 #543 #565](https://github.com/eXpandFramework/DevExpress.XAF/commit/8b976e7ef674a254909c7461b2b73f73042226f8)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.1) includes commit that relate to this task:

* [Bump standalone packages #565 #581](https://github.com/eXpandFramework/eXpand.lab/commit/3c88dcad436b49c202b4559b883f9ce27a8997e1)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
