### ISSUE TITLE
Invalid cast when XpoExpressionMemberInfo from Runtime members

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#582]
T821232

**Comment by expand** [comment]
eXpand.lab release [19.1.605.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.1) includes commit that relate to this task:

* [Invalid cast when XpoExpressionMemberInfo from Runtime members #582](https://github.com/eXpandFramework/eXpand.lab/commit/b02624fbac4555688b3604afb97ecbaa6d7b30bf)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
