### ISSUE TITLE
Reactive.Logger set logging off

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#583]
Hi,

the Reactive.Logger Module is needed because of refrences (f.e. dashboard).
How can I set the logging off?
In the Model I set everything to "Off", but
- TraceEvents is still written
- ..RXLogger.log is still written

![Logger](https://user-images.githubusercontent.com/43132306/66704970-64103c00-ed21-11e9-98eb-1abb5c23387a.PNG)

**Comment by apobekiaris** [comment]
until i research the case did you already tried to disable the module as per docs?

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger#issues-debugging-troubleshooting

**Comment by CWolffIF** [comment]
Yes,
if I
Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.Reactive.Logger.ReactiveLoggerModule))
my App didn´t start because the refrences has requierence.

**Comment by apobekiaris** [comment]
i am not sure what u mean? references have nothing to do with not loading the module. References remain but the module won't load

**Comment by apobekiaris** [comment]
this functionality should work at least per this test

https://github.com/eXpandFramework/DevExpress.XAF/blob/6540487be9f16a55908ee87d68f3d82465271967/src/Tests/Reactive/XafApplicationTests.cs#L123-L129

**Comment by CWolffIF** [comment]
Hi,
maybe I´m in the wrong place with the unload.
Where to place the command?

**Comment by CWolffIF** [comment]
I got the Error


			Type:       CannotRemoveModule
			Message:    Cannot remove the "ReactiveLoggerModule" module, there are dependent modules:   XpandSystemModule
  DashboardModule
  iXISXRMModule
  DashboardWindowsFormsModule
  XpandSystemWindowsFormsModule
  MasterDetailWindowsModule
  XpandChartWinModule
  XpandTreeListEditorsWinModule
  XpandPivotGridWinModule
  iXISXRMWindowsFormsModule

**Comment by apobekiaris** [comment]
a bit strange I thought it the other way around XpandSystemModule has logger installed not the opposite. I let you know once I research those case, at the moment I do not have more suggestions

**Comment by CWolffIF** [comment]
On my project (Win) there is no problem with the Security. TaceEvent allways written. But I think that it is good to init as AnonymousAllowedType.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveModule unload as per docs #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/0c5a47b039955473d20c272a0da6ffe67666f4f2)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.3) includes commit that relate to this task:

* [Bump standalone packages #583 #585 #587](https://github.com/eXpandFramework/eXpand.lab/commit/947a263942a42af2ff6096d7c1b09ffb2eac6860)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Tested with 19.1.605.4
All settings are "Off" but TraceEvent is still written. Also the RXLogger.log File.

**Comment by CWolffIF** [comment]
Tested with 19.1.605.4 and 
Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.Reactive.Logger.ReactiveLoggerModule));

App didn´t start. Error seee Screenshot.

![Logger](https://user-images.githubusercontent.com/43132306/66753083-3e0aa900-ee93-11e9-8507-fc97734ef5e1.png)

**Comment by krombipils** [comment]
I get a different (InvalidCast) exception, when trying to unload the ReactiveLoggerModule in 605.4. I unloaded the ReactiveLoggerModule in the constructor of my agnostic module (in a winforms app)

**Comment by CWolffIF** [comment]
If I try to unload the ReactiveLoggerModule in then constructor of my agnostic module (win) I got the same error as described above. (InvalidOperationException).
But before I cleared the NugetCaches and Clear-Projectdirectories (bin, obj) I got the InvalidCast like you.

**Comment by apobekiaris** [comment]
wait for the next minor please i have fixed this one.

General note :

although u can unload a module the api is still used
unload does not guarantee that the app will start it will break where the api is used and I will not pursue bug fixes like this unless its a special case like this one. I will pursue fixing the root problem of course

for e.g u cannot unload Reactive its api is used everywhere

**Comment by CWolffIF** [comment]
OK, super Tolis. I wait for the fix and then test it.

**Comment by apobekiaris** [comment]
or to say it better u can unload reactive but it will break where the API is used and I will not pursue such fixes.

**Comment by apobekiaris** [comment]
I hope it makes sense there are open cases to that Logger does not obey the model rules, and this is the problem and not unloading all modules

**Comment by CWolffIF** [comment]
If the logical conditions rule, I do not want to unload the module.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Invalid Cast when unloading LoggerModule or ReactiveLogger #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/e2ab079f88420dfa3501549aaf366930f1e0f7c6)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.5) includes commit that relate to this task:

* [Bump standalone packages
 1. Invalid Cast when unloading LoggerModule or ReactiveLogger #583](https://github.com/eXpandFramework/eXpand.lab/commit/3355add9011fc47a27a83291387016399c52fc67)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Exception is gone in 605.5, but Tracing is still active/log file is generated/TraceEvents are stored, although ReactiveLoggerModule is unloaded

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveLogger: Do_Not_Trace_If_TraceSources_Level_Off #588 #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/996b7a7454cbdf516066d0c3df894e1184864ade)
* [ReactiveLogger: Fix File IOException on RXLogger.log #588 #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/59cf652096ebee9add61e7adc2bd2747fd2652a9)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.6) includes commit that relate to this task:

* [Bump standalone packages
 1. ReactiveLogger: Do_Not_Trace_If_TraceSources_Level_Off #588 #587 #583
1. ReactiveLogger: Fix File IOException on RXLogger.log #588 #587 #583](https://github.com/eXpandFramework/eXpand.lab/commit/b44eef6c180e5b1662b5b0323e2f675302570adf)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
19.1.605.7 it works
