### ISSUE TITLE
Show nested list in listview

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#584]
Hello,

I have a object "Parent" with aggregated collection inside "Children".
In a listview, i would like to show the parents with the Childrens under.

Can i do that with the framework because as far as know XAF does not provide this funcitonnality. 

Thanks for your help
ISA

**Comment by apobekiaris** [comment]
how about 

http://masterdetail.expandframework.com

**Comment by isatahiri** [comment]
Not really, this dashoard shows the children, parent by parent. I was more looking for a kind of brandlayout, with on line the parent and brands nested listview. 

Something like this (WIN/ASP) : 
![image](https://user-images.githubusercontent.com/41955268/66707754-1eb23580-ed46-11e9-8651-325c1b9fe6b4.png)

**Comment by apobekiaris** [comment]
I see 2 attributes in the listview model that may help

The native XAF DataRowMode and from Xpand web the PreviewDetailView

**Comment by isatahiri** [comment]
We definitely learn everyday ! 
Thanks Tolis !
