### ISSUE TITLE
Expand.Extensions could not be found

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#585]
Hi Tolis,

I tried to install the new version, but Xpand.Extensions could not be found, f.e. as reference  in Reactive Module.

![Extensions](https://user-images.githubusercontent.com/43132306/66712386-4b913780-ed9c-11e9-8ac5-0e3d1c795578.PNG)

**Comment by apobekiaris** [comment]
did u find a solution? I just tested against a new XAF Solution where I installe the reactive module and worked

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Xpand.Extensions not published #585](https://github.com/eXpandFramework/DevExpress.XAF/commit/2ec4912eb795cd97e0896e654b38aa62d57ec341)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Xpand.Extensions not published #585](https://github.com/eXpandFramework/DevExpress.XAF/commit/38238a245b8f839eff06e03543860830c08691f8)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi Tolis,

I tried, but now I get the error in ReactiveLoggerService,cs

System.IO.FileNotFoundException: "Die Datei oder Assembly "DevExpress.ExpressApp.v18.2, Version=18.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden."

**Comment by CWolffIF** [comment]
In 
`    public static class ReactiveLoggerService{
        
        
        private static readonly Subject<ITraceEvent> SavedTraceEventSubject=new Subject<ITraceEvent>();

        public static IObservable<ITraceEvent> ListenerEvents{ get; private set; }

        public static IObservable<ITraceEvent> SavedTraceEvent{ get; }=SavedTraceEventSubject;
        internal static IObservable<Unit> Connect(this ReactiveLoggerModule reactiveLoggerModule){

            var application = reactiveLoggerModule.Application;
            if (application == null){
                return Observable.Empty<Unit>();
            }

            var listener = new ReactiveTraceListener(application.Title);
            ListenerEvents = listener.EventTrace.Publish().RefCount();
            
            return application.BufferUntilCompatibilityChecked(ListenerEvents.Select(_ => _))
                .SaveEvent(application)
                .ToUnit()
                .Merge(ListenerEvents.RefreshViewDataSource(application))
                .Merge(application.RegisterListener(listener),Scheduler.Immediate)
                .ToUnit();
        }`

**Comment by apobekiaris** [comment]
it looks like the assembly is not getting patched can you try to clean your nuget cache and bin ?

**Comment by CWolffIF** [comment]
Cleared everything and downloaded all new. Same error.

**Comment by CWolffIF** [comment]
Try to update to 19.1.605.3

**Comment by expand** [comment]
eXpand.lab release [19.1.605.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.3) includes commit that relate to this task:

* [Bump standalone packages #583 #585 #587](https://github.com/eXpandFramework/eXpand.lab/commit/947a263942a42af2ff6096d7c1b09ffb2eac6860)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
i can confirm issues with the latest packages working on them

**Comment by CWolffIF** [comment]
I can not confirm.
- Deinstalled everything.
- Clear all caches
- Install 19.1.605.3
=> same error

**Comment by apobekiaris** [comment]
these are new packages and from what I see VersionConverter is not intalled for them,

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Add VersionConverter to Xpand.Extensions #585](https://github.com/eXpandFramework/DevExpress.XAF/commit/0be2e6b3fc0fc4d0a7c676beff4be206ca56f989)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.4) includes commit that relate to this task:

* [Bump standalone packages #585](https://github.com/eXpandFramework/eXpand.lab/commit/d28c128e8f74f2e86566f5031e54f541634ca85f)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
19.1.605.4 runs with no error.
