### ISSUE TITLE
Reactive Logger 

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#587]
Xpand.XAF.Reactive Logger error : Object prohibitaed by security rule

Xpand Version : 19.1.605.2

![image](https://user-images.githubusercontent.com/163586/66714445-9a5ac380-edd4-11e9-820a-1fd9b47f67f4.png)

Application Not running. Any stable relaese which can i use on my production enviroment.

**Comment by apobekiaris** [comment]
until fix u can simply fix it by adding permission for your roles to this object

**Comment by apobekiaris** [comment]
here the resolution that is missed in the source code

https://docs.devexpress.com/eXpressAppFramework/DevExpress.ExpressApp.Security.SecurityStrategy.AnonymousAllowedTypes

adding TraceEvent there solves the problem

**Comment by cevious** [comment]
how do I add TraceEvent.  

Before login throw error

**Comment by apobekiaris** [comment]
follow my last comment what is not clear? docs have an example

**Comment by cevious** [comment]
I have tried to unload but show error
Any wayout resolve issue or any old stable release which can downgrade

Cannot remove the "ReactiveModule" module, there are dependent modules:   ReactiveLoggerModule
  ModelMapperModule
  XpandTreeListEditorsWinModule
  IOWinModule
  CloneMemberValueModule
  HideToolBarModule
  ProgressBarViewItemModule
  RefreshViewModule
  XpandSystemModule
  GridListEditorModule
  XpandSystemWindowsFormsModule
  MasterDetailModule
  AutoCommitModule
  ViewEditModeModule
  SuppressConfirmationModule
  ExcelImporterModule
  ExcelImporterWinModule
  CoreAppWindowsFormAdditionalModule
  eFusionWindowsFormsModule


   at DevExpress.ExpressApp.ModuleList.OnRemove(Int32 index, Object value)
   at System.Collections.CollectionBase.System.Collections.IList.Remove(Object value)
   at DevExpress.ExpressApp.Utils.BindingListBase`1.Remove(T item)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.<>c__DisplayClass4_0.<Unload>b__0(ApplicationModulesManager _) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 16
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Sink`1.ForwardOnError(Exception error)
   at System.Reactive.Sink`1.ForwardOnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 25
   at SetupModules_Patch1(ApplicationModulesManager )
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by apobekiaris** [comment]
thnks for reporting this I am aware 

My suggestion however was different
```
((SecurityStrategy)Security).AnonymousAllowedTypes.Add(typeof(TraceEvent));
```

**Comment by apobekiaris** [comment]
#583

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveModule unload as per docs #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/0c5a47b039955473d20c272a0da6ffe67666f4f2)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.3) includes commit that relate to this task:

* [Bump standalone packages #583 #585 #587](https://github.com/eXpandFramework/eXpand.lab/commit/947a263942a42af2ff6096d7c1b09ffb2eac6860)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by cevious** [comment]
Version : 19.1.502.4
Latest Version Error 

Exception occurs while initializing the 'Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule' module: Sequence contains no elements.

   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 41
   at SetupModules_Patch1(ApplicationModulesManager )
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by apobekiaris** [comment]
>Version : 19.1.502.4
Latest Version Error

not sure what this means? 19.1.502.4 is not the latest version for sure

**Comment by cevious** [comment]
sorry

19.1.605.4

My Suggessation
static option for every module for load & unload rather use unload

**Comment by apobekiaris** [comment]
thnks for the suggestion however the problem should be addresses on the abstract level else u go arounnd supporting the unload for each package which is a nightmare. 

Now again I fail to understand how this exception it thrown

**Comment by cevious** [comment]
I think you have unload recusively from all dependent module in latest code.

**Comment by apobekiaris** [comment]
i added a test to describe the previous problem as u can see in `ReactiveModule unload as per docs #587 #583` link i posted above. Apparently I miss somthing however if not match trouble try to describe a way to reproduce it.  and post the full log I need to know where this comes from and why not logged properly

**Comment by apobekiaris** [comment]
note that I can install and run 605.4 SystemWin on an empty XAF solution

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveLogger: Fix File IOException on RXLogger.log #588 #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/59cf652096ebee9add61e7adc2bd2747fd2652a9)
* [ReactiveLogger: Do_Not_Trace_If_TraceSources_Level_Off #588 #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/996b7a7454cbdf516066d0c3df894e1184864ade)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.6) includes commit that relate to this task:

* [Bump standalone packages
 1. ReactiveLogger: Do_Not_Trace_If_TraceSources_Level_Off #588 #587 #583
1. ReactiveLogger: Fix File IOException on RXLogger.log #588 #587 #583](https://github.com/eXpandFramework/eXpand.lab/commit/b44eef6c180e5b1662b5b0323e2f675302570adf)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
> thnks for reporting this I am aware
> 
> My suggestion however was different
> 
> ```
> ((SecurityStrategy)Security).AnonymousAllowedTypes.Add(typeof(TraceEvent));
> ```

My suggestion was incorrect as the Logger module does not persist TraceEvent before Login. After Login the Security permissions used for each type. I also tried the similar static [AdditionalSecuredTyoes](https://docs.devexpress.com/eXpressAppFramework/113366/concepts/security-system/security-system-overview#restrict-non-persistent-types-access) but this applied as it looks only to non persistent objects. Finanly I implemented a custom functionality the `SecuredTypesAttribute` where you can use to exclude any type.

TraceEvent is marked with the new `SecuredTypeAttribute` in the next minor

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Reactive: SecuredTypeAttrbute excludes Type from Security operations #587](https://github.com/eXpandFramework/DevExpress.XAF/commit/018286409124f107a4f8268d1844cbe2dc69dfae)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Reactive: NonSecuredTypeAttrbute excludes Type from Security operations #587](https://github.com/eXpandFramework/DevExpress.XAF/commit/5e037ee140e04770b3ef838254a4c7a7e3fd145d)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.7) includes commit that relate to this task:

* [Bump standalone packages
 1. Reactive: NonSecuredTypeAttrbute excludes Type from Security operations #587
1. Reactive: SecuredTypeAttrbute excludes Type from Security operations #587](https://github.com/eXpandFramework/eXpand.lab/commit/8059bbfd109afa12076060b537654d4ea062275b)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Now in 19.1.605.7 I go the error when I try to open the model (updating model always fails)

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

   bei Xpand.Extensions.XAF.XafApplication.XafApplicationExtensions.AddNonSecuredType(XafApplication application, Type[] objectTypes) in D:\a\1\s\src\Extensions\Xpand.Extensions.XAF\XafApplication\AddAdditionalSecuredTypes.cs:Zeile 10.
   bei System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Reactive: Design time NullReference on AddNonSecuredTypes #587](https://github.com/eXpandFramework/DevExpress.XAF/commit/64ba8ff2f8c6e31e10919e3ff1f9f6e741466859)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Top. It builds/updates and opens in the Modeleditor again.
Later I will test if the "Off" Setting of the Logger works.

How can I prevent that the file RXLogger.log is created?

**Comment by apobekiaris** [comment]
>How can I prevent that the file RXLogger.log is created?

if oFf should not write to it,  does it still write?

**Comment by CWolffIF** [comment]
When all settings are of
- the table TraceEvent is empty
- the file RXLogger.log (is created) but nothing is written

OK, superb.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.8) includes commit that relate to this task:

* [Bump standalone packages
 1. Reactive: Design time NullReference on AddNonSecuredTypes #587](https://github.com/eXpandFramework/eXpand.lab/commit/6205b5d280ef598ebb5525e79f1c2d2c60444311)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
