### ISSUE TITLE
InvalidOperationException:'XpandListView, ID:MDO_ListView' view to XpandWebWindow:

### ISSUE THREAD

**Issue by larspl** [eXpandFramework/eXpand#589]
**Question**
Xpand Version Nuget 19.1.605.2 
 
i get the following Error when i try to open the Application Settings View ( default Xpand View for Application settings. ) 

what can i do to solve this issue? 

**
> Unable to cast object of type 'System.String' to type 'System.Collections.Generic.List`1[System.String]'.

**

**System**
System.Web 
XAF WebApp
XAF App that use DC
DX 19.1.6

**Additional context**
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandListView, ID:MDO_ListView' view to XpandWebWindow:
Unable to cast object of type 'System.String' to type 'System.Collections.Generic.List`1[System.String]'.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   at DevExpress.ExpressApp.Web.ShowViewStrategy.ShowViewInCurrentWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       InvalidCastException
			Message:    Unable to cast object of type 'System.String' to type 'System.Collections.Generic.List`1[System.String]'.
			Data:       0 entries
			Stack trace:

   at setter(Object , Object )
   at Fasterflect.FieldExtensions.SetFieldValue(Object obj, String name, Object value)
   at Xpand.ExpressApp.Web.PropertyEditors.ASPxStringPropertyEditor.CreateEditModeControlCore() in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\PropertyEditors\StringPropertyEditor.cs:line 17
   at DevExpress.ExpressApp.Web.Editors.WebPropertyEditor.CreateControlCore()

**Comment by apobekiaris** [comment]
try removing the Xpand.ExpressApp.Web.PropertyEditors.ASPxStringPropertyEditor

**Comment by larspl** [comment]
its not possible todo that in model.xaml

the ViewID: MDO_ListView is found in 

**Navigation:** 
  <Item Id="MDO_ListView" Caption="Application Settings" />

**and point to**

 <Class Name="Xpand.ExpressApp.ModelDifference.DataStore.BaseObjects.ModelDifferenceObject" Caption="Application Settings" />

this class i can't remove.

**Comment by apobekiaris** [comment]
I did not mean to remove the model nodes just assign another PropertyEditor and not the one that throws

**Comment by apobekiaris** [comment]
the ASPxStringPropertyEditor  is market as default for strings change it and use the DevExpress.ExpressApp.Web.Editors.ASPx.ASPxStringPropertyEditor

**Comment by larspl** [comment]
should i do this in code? or in Model.xaml?

**Comment by apobekiaris** [comment]
I am not sure what u ask, so choose any way u prefer the effect is the same

**Comment by larspl** [comment]
> the ASPxStringPropertyEditor is market as default for strings change it and use the DevExpress.ExpressApp.Web.Editors.ASPx.ASPxStringPropertyEditor

this is your hint to me. 
i ask you where i should assign this PropertyEditor from a class inside of:
**Xpand.ExpressApp.ModelDifference.DataStore.BaseObjects.ModelDifferenceObject** 

please explain your idea to a parttime XAF Developer. thanks

**Comment by apobekiaris** [comment]
yes apologies u said u have 2 options as u said so I understand that u aware of them

so start with the model for start and change your application/Viewitems/System.String/EditorType attribute

**Comment by larspl** [comment]
Hi Tolis, 

i have some Problems when i try to open the DX ModelEditor.

the error with 'Fasterflect, in 
Xpand.Persistent.Base.General.XpandModuleBase'

is back.  i use 19.1.605.6 

what can i do? any fast help is welcome and appreciated! 

> 
> 
>    at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
>    at DevExpress.Persistent.Base.ReflectionHelper.CreateObject(Type objectType, Object[] args)
>    at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
>    at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
>    at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.ReInit()
> ----------InnerException----------
> The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception.
> ----------StackTrace----------
>    at Xpand.Persistent.Base.General.XpandModuleBase..ctor()
>    at Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule..ctor()
>    at pnc.dgv.cdb.Web.CdbAspNetApplication.InitializeComponent() in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\WebApplication.cs:line 237
>    at pnc.dgv.cdb.Web.CdbAspNetApplication..ctor() in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\WebApplication.cs:line 148
>    at Create_CdbAspNetApplication()
>    at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
> ----------InnerException----------
> Could not load file or assembly 'Fasterflect, Version=0.0.0.0, Culture=neutral, PublicKeyToken=38d18473284c1ca7' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
> ----------StackTrace----------
>    at Xpand.Persistent.Base.General.XpandModuleBase..cctor()

**Comment by apobekiaris** [comment]
I tested against an empty XAF solution where I failed to repro any of these issues. If you can provide a sample happy to debug..

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
