### ISSUE TITLE
XpandVersionConverter: Process cannot access file.

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#591]
Hi Tolis,

We have a buildserver where the VersionConverter keeps failing on this line: https://github.com/eXpandFramework/DevExpress.XAF/blob/master/tools/Xpand.VersionConverter/Functions.ps1#L325

A second build works on my pc, but not on the buildserver since a buildserver does only one build. I get the error the second time when I delete all the Xpand.XAF.Modules packages in my .nuget/packages folder. 

This is what calls the Update-Version: https://github.com/eXpandFramework/DevExpress.XAF/blob/master/tools/Xpand.VersionConverter/Xpand.VersionConverter.ps1#L83

Do you have any idea what the problem might be?

Thanks,
Gerrit

**Comment by gerritmulder** [comment]
Logfile: [6.txt](https://github.com/eXpandFramework/eXpand/files/3725015/6.txt)

**Comment by apobekiaris** [comment]
sorry not a clue Xpand builds are scripts and a retry is super easy, I remember that the problem started at the time Xpo ported to netstandard and affects both repos

**Comment by ncryptn** [comment]
Will close it now. If it appears in later versions too I will reopen it if I found the problem.

**Comment by gerritmulder** [comment]
Will see if it is in later version and reopen it if I found the problem. For now closed and will stay on 503. Thanks for your time.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [VersionConverter: Resolved assemblies are not getting disposed #591](https://github.com/eXpandFramework/DevExpress.XAF/commit/e418fceb5f112f93a344d89cc2e52aef58e3f15b)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [VersionConverter: Resolved assemblies are not getting disposed #591](https://github.com/eXpandFramework/DevExpress.XAF/commit/17ae411aba82341b4e777f53ccd1079fa573c30e)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
