### ISSUE TITLE
Add DevExpress dependencies to Nuget

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#594]
install the Reactive.Logger to a project without ConditionalAppearance and it will throw if not in GAC.

**Comment by apobekiaris** [comment]
Issue is prioritized as it contains one of the following labels ***sponsor***, **installation**, **contribution**, **nuget**, **breakingchange**, **ReproSample**, **Deployment**

**Comment by apobekiaris** [comment]
this is not possible as nuget validation won't allow installation because packages are spawn through XAF versions

**Comment by expand** [comment]
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
