### ISSUE TITLE
Xpand.Extensions old Reference

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#595]
Hi Tolis,

if I try to open the model (Win) in VS I got the error with missing Xpand.Extensions.

But Xpand.Extensions, Version=0.0.3.1 is installed and referenced.

Xpand.XAF.Modules.ModelMapper Version=1.1.55.2

20.10.19 14:13:27.363	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while initializing the 'Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule' module: Der Typeninitialisierer für "Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService" hat eine Ausnahme verursacht.
	Data:       0 entries
	Stack trace:

   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModulesPatch(ApplicationModulesManager __instance)
   bei SetupModules_Patch1(ApplicationModulesManager )
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	----------------
	InnerException:

			Type:       TypeInitializationException
			Message:    Der Typeninitialisierer für "Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService" hat eine Ausnahme verursacht.
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Extend(ApplicationModulesManager modulesManager, PredefinedMap map, Action`1 configure)
   bei Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule.Setup(ApplicationModulesManager moduleManager)
   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
			----------------
			InnerException:

					Type:       FileNotFoundException
					Message:    Die Datei oder Assembly "Xpand.Extensions, Version=0.0.3.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
					Data:       0 entries
					Stack trace:

   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetAssembly(Assembly[] assemblies, String name, Boolean partialMatch)
   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Init()
   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService..cctor()
					InnerException is null

**Comment by CWolffIF** [comment]
If I went back to 
Xpand.Extensions, Version=0.0.3.0 and Xpand.Extensions.XAF, Version=0.0.3.0 (only this to modules)
it works.

**Comment by apobekiaris** [comment]
from this info cannot guess match, provided a sample happy to research further

**Comment by CWolffIF** [comment]
Went back to Version 0.0.3.0 compiled, cleared-directories and the updated to 0.0.3.1. Everything works now.
