### ISSUE TITLE
eXpand adds "Group" to group captions

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#596]
See the attached screenshot: ![group](https://user-images.githubusercontent.com/8317504/67189387-6a23ae00-f3ee-11e9-9f82-ac91150cc50a.png)

The "Group" in "AssignmentHistoryCollection_Group" is somehow added by eXpand. If XpandSystemWindowsFormsModule is not installed, everything is fine. Maybe this is again related to ModelMapper?

I attached a simple demo project, but I guess you can easily repro it in all solutions, if eXpandWin is installed and at least one group exists in the layout (and the group caption is not explicitly set).

[Solution8.zip](https://github.com/eXpandFramework/eXpand/files/3749771/Solution8.zip)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: IModelLayoutGroup Caption is incorrect  #596](https://github.com/eXpandFramework/DevExpress.XAF/commit/3f2de563a7bdf1f0b5e0d2465479e21aa21021ec)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Fixed. Thank you!

**Comment by expand** [comment]
eXpand.lab release [19.1.701.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.4) includes commit that relate to this task:

* [Bump standalone packages

1. CloneModelView: Keep ModelNodeGenerators #601
1. ModelMapper: IModelLayoutGroup Caption is incorrect  #596](https://github.com/eXpandFramework/eXpand.lab/commit/a0148d801f29ae112adfdb2d281fabb87f1773a1)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.701.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.8) includes commit that relate to this task:

* [Bump standalone packages #606

1. CloneModelView: Keep ModelNodeGenerators #601
1. ModelMapper: IModelLayoutGroup Caption is incorrect  #596](https://github.com/eXpandFramework/eXpand.lab/commit/a7fe51aca9d529a41382d4c91149c5e9a83164a2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
