### ISSUE TITLE
VersionControl without manual download libs

### ISSUE THREAD

**Issue by GannebalBarka** [eXpandFramework/eXpand#599]
Hi!
**Is your feature request related to a problem? Please describe.**
My organization use proxy without internet connection (blocked all binary files).
VersionControl need downloaded 2 files nuget and mono.ceil
in this line
https://github.com/eXpandFramework/DevExpress.XAF/blob/95f2f87729b82893cf23fdc5d8057234ee58b500/tools/Xpand.VersionConverter/Functions.ps1#L82
https://github.com/eXpandFramework/DevExpress.XAF/blob/95f2f87729b82893cf23fdc5d8057234ee58b500/tools/Xpand.VersionConverter/Functions.ps1#L101

I'm not single developer. I'm single developer have access to downloadable packages and many executable binary types(i.e. authorized of security service)
I make new package version include this binary files and push in local package mirror (sonatype nexus)
I think this is bad practice.

**Describe alternatives you've considered**
1. Add Mono.Cecil to VersionControl PackageReference
2. Create build script for VersionControl nuget. This script pre pack command. Script get VersionControl MonoCecil version and write to tools/Xpand.VersionConverter/Functions.ps1 variable or write in *.target file
3. remove dowload functions
https://github.com/eXpandFramework/DevExpress.XAF/blob/95f2f87729b82893cf23fdc5d8057234ee58b500/tools/Xpand.VersionConverter/Functions.ps1#L82
https://github.com/eXpandFramework/DevExpress.XAF/blob/95f2f87729b82893cf23fdc5d8057234ee58b500/tools/Xpand.VersionConverter/Functions.ps1#L101

**Additional context**
This architecture:
- provides usages single version mono.cecil in packages and scripts. 
- provides default logic for download package (i.e. mono.cecil). 
- whithout downloded nuget.exe version

Thanks for your work

**Comment by apobekiaris** [comment]
It sounds rational suggestion on your part, however have you thought that it introduces an additional dependency (Mono.Cecil) with its support cost to ALL packages? with the current architecture there is no cost added to consumer project, I could modify the scripts however to get the files from an Enviromental Variable and if not set fallback to the url

does that solves your issue?

**Comment by GannebalBarka** [comment]
> It sounds rational suggestion on your part, however have you thought that it introduces an additional dependency (Mono.Cecil) with its support cost to ALL packages?
Isn’t the same thing happening now? Just not noticeable to the developer. If you add the dependency explicitly, then nothing will change. The assembly will take place as before. The number of downloaded versions of Mono.Cecil will be equal to 1, as now. This dependence will be added automatically to all projects - this is fully consistent with the nuget ideology.
Am I just trying to understand what are you trying to achieve with this feature? (suddenly this is best practice)

>  I could modify the scripts however to get the files from an Enviromental Variable and if not set fallback to the url
I think yes. Then add the package name as an option to the problem description.

But this will not solve the problem of the obvious appearance of such a dependence in the project.(Although I don’t think anyone will notice :D )

**Comment by apobekiaris** [comment]
so let's discuss this desicion a bit. The Mono.Cecil version A is used from VersionConverter inside the packages directory and never moved to the outputpath. Changing the architecture  and add it as a Dependecncy to all packages, would mean that others that use it as a dependency have to deal with nuget version conflicts which is not a straightforward think as  you describe it in your example, especially for larger frameworks with many packages like this one. Now lets say that you wish to update the VersionConverter Mono.Cecil version again Nuget/MsBuild will most propbably warn u about version conflicts and prompt u to take action which means support cost for u.

Another option is to add the Mono.Cecil not as a dependency but as an artifact so it is downloaded with the .nupkg and used as needed from there without the need of any consumer action

**Comment by apobekiaris** [comment]
>(Although I don’t think anyone will notice :D )

I am pretty sure that I will notice it as I maintain a universe of packages

**Comment by GannebalBarka** [comment]
Fine! let's do it!
I have a suggestion. What if you just look for the desired mono.cesil package in the current packages path? 
Manual for developer (without manual download):
To download the package of the desired version and there are no version conflicts: create *.csproj with the desired mono.cecil and connect it to the projects this way:
1. `<ProjectReference Include="..\ProjectA\ProjectA.csproj">`
2. `      <Project>{b402782f-de0a-41fa-b364-60612a786fb2}</Project>`
3. `      <Name>ProjectA</Name>`
4. `      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>`
5. `</ProjectReference>`

**Comment by apobekiaris** [comment]
u nail it! 

looks like it can address everything transparently thnks

**Comment by apobekiaris** [comment]
it not total clear however, why add the ProjectA as ProjectReference ?

**Comment by GannebalBarka** [comment]
Always happy to help!

**Comment by apobekiaris** [comment]
adding ProjectA as projectrefernce I understand that will be displayed in the Solution Explorer??

**Comment by GannebalBarka** [comment]
usage example.
A task:
- you need to specify the build order without connecting the project as a dependency and without copying such a dependency into the output directory (our case)

how it works:
- project A contains a nugget
- project B connects project A only for assembly (ReferenceOutputAssembly = false)
- when assembling project B:
- Project A side starts
- Project A nougat downloads
- going to project A
- Project B is going to (starting the version converter)

P.S. the nugget in project A can be specified with ReferenceOutputAssembly = false that it will download it, but will not copy it to the output directory of project A

I relied on information from an article https://blogs.msdn.microsoft.com/kirillosenkov/2015/04/04/how-to-have-a-project-reference-without-referencing-the-actual-binary/

 we use a rider and we don’t have a window as a visual studio "Assembly Order". This article says that it is out of date

**Comment by GannebalBarka** [comment]
Rider mark reference dotted picture
![InRider](https://user-images.githubusercontent.com/26537238/67452930-46ef3d80-f63e-11e9-8d0c-a30e562128b1.png)
VS permanent mark for buid dependancy
![InVS2017](https://user-images.githubusercontent.com/26537238/67452932-46ef3d80-f63e-11e9-91d5-ab0c7921618a.png)

**Comment by apobekiaris** [comment]
what I understand is that you can use the `ReferenceOutputAssembly` attribute to add another csproj in context however at the moment that you modify the current.csproj with a ProjectReference this is shown in VS solution explorer is this right?

**Comment by apobekiaris** [comment]
however thinking this again we can distribute the assemblies with nuget and do not reference them e.g. if you use another extension than .dll, probably this idea is better simpler magic

**Comment by apobekiaris** [comment]
i am not sure exactly how to do it though I just guested let me know your feedback

**Comment by GannebalBarka** [comment]
> what I understand is that you can use the ReferenceOutputAssembly attribute to add another csproj in context however at the moment that you modify the current.csproj with a ProjectReference this is shown in VS solution explorer is this right?

Yes, the visual studio adds the project depending and shows in the assembly order

> however thinking this again we can distribute the assemblies with nuget and do not reference them e.g. if you use another extension than .dll, probably this idea is better simpler magic

I hope this will work well. To check how it works, I cleaned the Nuget repository:
- cmd `nuget locals all -clear`
- remove ./packages/ folder of my solution

**Comment by apobekiaris** [comment]
or u can do with XpandPwsh

```ps1
Clear-NugetCache XpandPackages
```

that the easy part :)

**Comment by GannebalBarka** [comment]
I create sample project for demonstaration manual download nuget
I mark #TODO changes in ../packages/Xpand.VersionControl.1.0.35/build/Functions.ps1
*changes are not optimal and only demonstrate the approach
[TestNuget.zip](https://github.com/eXpandFramework/eXpand/files/3765826/TestNuget.zip)

**Comment by GannebalBarka** [comment]
> Clear-NugetCache XpandPackages

thnks

**Comment by apobekiaris** [comment]
> I create sample project for demonstaration manual download nuget
> I mark #TODO changes in ../packages/Xpand.VersionControl.1.0.35/build/Functions.ps1
> *changes are not optimal and only demonstrate the approach
> [TestNuget.zip](https://github.com/eXpandFramework/eXpand/files/3765826/TestNuget.zip)

yes i get the idea but do u think that everyone that uses Xpand.VersionConverter we should add one more project into every solution ?

**Comment by GannebalBarka** [comment]
No, this is a solution for people like me. so that there is no background loading of the nugget. everything will be transparent.
At the same time, your option also works

**Comment by apobekiaris** [comment]
happy to accept a PR if you interested to contribute on somthing like this though
https://stackoverflow.com/questions/30037974/how-can-i-use-a-nuget-package-to-distribute-an-executable

sounds it should work fine, you put the mono.cecil.dll in the content and when you need it (OnBuild) you move it to the packages folder for further use.

**Comment by GannebalBarka** [comment]
this approach has disadvantages:
- if you change the mono.cecil version, we will have to create a new nuget
- update nuget in all projects of all solutions
- the "content" folder copies its contents to the project, and not to the packages folder(../packages/Xpand.VersionControl.1.0.35/buils/mono.cecil.10.0.34/lib/net40/). That is, I will have to write a command that will understand which version of the converter is currently used and copy mono to the desired package

I suggested a version that:
- maximizes the use of existing nuget
- does not require creating your own nuget packages to solve this problem
- does not require scripting
- allows you to use search and replace by project for migration to a new version of mono
- forces the developer to create such a project in all solutions

P.S. comparing these solutions, I had one interesting idea and tomorrow I will try to implement it ;)

**Comment by GannebalBarka** [comment]
I came up with a solution. I think not very good, but witty
build project and look in the folder
[TestNuget.zip](https://github.com/eXpandFramework/eXpand/files/3767564/TestNuget.zip)

**Comment by apobekiaris** [comment]
I did not checked your sample yet but Ii feels we over engineering here. The Xpand.VersionConverter package already distributes *.ps1 files in the packages folder. The same way it can distributes the Mono.Cecil.sll

where do u see a problem?

**Comment by GannebalBarka** [comment]
I don’t think it makes sense to create a separate package with mono. It’s easier to turn it inside the converter right away.
Anyway, the converter requires a certain version of mono

P.S. latest test project downloads standard mono package

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [VersionConverter: Distribute Mono.Cecil instead of download #599](https://github.com/eXpandFramework/DevExpress.XAF/commit/f97bc1c841d00670a24e50776a4d2c8b25b7004c)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
