### ISSUE TITLE
Xpand.VSIX error after 19.1.701.0 install

### ISSUE THREAD

**Issue by GillesBrice** [eXpandFramework/eXpand#600]
Hello,

After I install the 19.1.701.0 version of eXpand, I get an error when I open Visual Studio with the Xpand.VSIX.
I have the 19.1.7 version of DevExpress, the 19.1.701.0 version of eXpand, I got the error both in Vusual Studio Community 2017 and 2019.

Here the screenshot message :
![2019-10-22_09-52-58](https://user-images.githubusercontent.com/14292185/67261463-cf8ca300-f4b1-11e9-86e1-c30fb5d4921e.png)

And here the error into the ActivityLog :
`<entry>
    <record>560</record>
    <time>2019/10/22 05:42:22.882</time>
    <type>Error</type>
    <source>Xpand.VSIX.VSPackage.VSPackage</source>
    <description>bindings:Text Editor::Alt+T&#x000D;&#x000A;System.ArgumentException: La ressource demand&#x00E9;e est introuvable&#x00A0;: &apos;6001&apos;.&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.CommonIDE.ResourceLoader.TryEachApplicableNamespace[T](String resourceName, GetResourceDelegate`1 getResource)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.CommonIDE.ResourceLoader.GetString(String resourceName, Int32 lcid)&#x000D;&#x000A;   &#x00E0; EnvDTE.Command.set_Bindings(Object pVar)&#x000D;&#x000A;   &#x00E0; Xpand.VSIX.Commands.VSCommand.BindCommand(DteCommand dteCommand) dans D:\a\1\s\Xpand.Plugins\Xpand.VSIX\Commands\VSCommand.cs:ligne 23</description>
  </entry>`

**Comment by apobekiaris** [comment]
I cannot tell why this is thrown, can u try to open the Xpand.VSIX and run it after u configure it as

![image](https://user-images.githubusercontent.com/159464/67269061-9e669f80-f4be-11e9-9386-13569e868fb4.png)

We can try to option the message so it is not shown but the exception won't be fixed this way. Also do you run VS as admin?

**Comment by GillesBrice** [comment]
I configure the Xpand.VSIX and run it after but what I have to do next (it just open a new Visual Studio window) ?

**Comment by apobekiaris** [comment]
yes does it run without errors? 

breakpoint at D:\a\1\s\Xpand.Plugins\Xpand.VSIX\Commands\VSCommand.cs:ligne 23

does it throw?

**Comment by apobekiaris** [comment]
if u remove the Command Line Arguments u can run it against the actual visual studio instance which is problematic but with them it runs against the experimental so u may won't be able to repro the problem

**Comment by apobekiaris** [comment]
I added the `ShowErrorsInMessageBox` which can be found in the General tab of the Plugin options

**Comment by expand** [comment]
eXpand.lab release [19.1.701.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.2) includes commit that relate to this task:

* [VSIX: ShowErrorsInMessageBox option #600](https://github.com/eXpandFramework/eXpand.lab/commit/1399e89ea80225db8459743dd783c8d5300406d2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by GillesBrice** [comment]
Thank you, with the release 19.1.701.2, I don't have the problem anymore.
