### ISSUE TITLE
Combination of CloneModelView and ModelMergedDifferences attributes does not work

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#601]
Here is a simple demo combining CloneModelView and ModelMergedDifferences attributes on a Business Object.

![cloned](https://user-images.githubusercontent.com/8317504/67369698-c8c96300-f579-11e9-8d6e-81fc54373ce0.jpg)

No MergedDifferences node is generated in TestBO_Cloned_DetailView and therefore no inheritance is applied. If I add the MergedDifferences manually to the xafml, everything is fine.

[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/3760869/Solution1.zip)

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [CloneModelView: Keep ModelNodeGenerators #601](https://github.com/eXpandFramework/DevExpress.XAF/commit/91a2ee369a24aeed6e1640245e5972dc57ada8ce)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Really would like to test the new version, but I think you have to bump eXpand versions again?! The dependencies/versioning probs are somehow/sometimes a pain in the ass

**Comment by apobekiaris** [comment]
yeah the update is still a bit manual but I am working to automate this bumping as well

**Comment by expand** [comment]
eXpand.lab release [19.1.701.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.4) includes commit that relate to this task:

* [Bump standalone packages

1. CloneModelView: Keep ModelNodeGenerators #601
1. ModelMapper: IModelLayoutGroup Caption is incorrect  #596](https://github.com/eXpandFramework/eXpand.lab/commit/a0148d801f29ae112adfdb2d281fabb87f1773a1)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.701.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.8) includes commit that relate to this task:

* [Bump standalone packages #606

1. CloneModelView: Keep ModelNodeGenerators #601
1. ModelMapper: IModelLayoutGroup Caption is incorrect  #596](https://github.com/eXpandFramework/eXpand.lab/commit/a7fe51aca9d529a41382d4c91149c5e9a83164a2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Thank you, but with the new version it is now no longer possible to use ModelViewInheritance if view is cloned in model editor. I attached my modified sample project.
Instead of using the atributes I added this to my model.designeddiffs.xafml:

    <DetailView Id="TestBO_Cloned_DetailView" ClassName="Solution1.Module.BusinessObjects.TestBO" IsNewNode="True">
      <MergedDifferences IsNewNode="True">
        <MergedDifference Id="@2f13170e-008a-4661-9058-57a940a38362" View="TestBO_DetailView" IsNewNode="True" />
      </MergedDifferences>
    </DetailView>
Now an exception is thrown on startup:
![grafik](https://user-images.githubusercontent.com/8317504/67750684-fdcd2e00-fa2f-11e9-8baf-8e4ff229ed78.png)
[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/3782438/Solution1.zip)

**Comment by krombipils** [comment]
Latest lab nuget version 1.0.14.4 does not contain this patch/commit.

**Comment by apobekiaris** [comment]
for start plan is to publish releases in the DevExpress.XAF repo containing the only the changed nupkg files.

**Comment by expand** [comment]
eXpand.lab release [19.2.300.16](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.16) includes commit that relate to this task:

* [Bump standalone packages
 1. CloneModelView: Create new views instead of Cloning #601 #611](https://github.com/eXpandFramework/eXpand.lab/commit/7f1ebaf5943cea3e0a0907e60c38abd391f88154)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
