### ISSUE TITLE
Error on compilation after uprade to 19.1.701.2

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#604]
Hi Tolis,

After doing a update via Nuget solution center to the version 19.1.701.2, i have a error on build. 

Somehow, the powershell code, is trying to get the dll in the release folder that are not here.
I actuall do a clean brefore build.

Exception lors de l'appel de «Write» avec «1» argument(s): «Le fichier 
1>  
1>                                'C:\Users\isata\Documents\PME 
1>  
1>                                Projects\PME_Affaire\PME_Affaire.Module\bin\Release\Xpand.XAF.Modules.Reactive.dll' est 
1>  
1>                                introuvable.»

Please see attachment. 
[Output.txt](https://github.com/eXpandFramework/eXpand/files/3771836/Output.txt)
[Error.txt](https://github.com/eXpandFramework/eXpand/files/3771837/Error.txt)

**Comment by apobekiaris** [comment]
you tried to clean-up the cache?

```ps1
Clear-NugetCache
```
```

**Comment by apobekiaris** [comment]
else

verbose  messaging by adding <PropertyGroup><VersionConverterVerbose>Continue</VersionConverterVerbose>. to your csproj

and repost

**Comment by apobekiaris** [comment]
by adding 
```xml
<PropertyGroup><VersionConverterVerbose>Continue</VersionConverterVerbose>.
```

**Comment by isatahiri** [comment]
Clear-NugetCache does not change anything
I added to the module csproj but no change.

**Comment by isatahiri** [comment]
i copied the reactive dll manually from package to the realease folder (just this file) and now it worked

**Comment by isatahiri** [comment]
I did the update because i had this error when doing right click on references --> add Expand 
![image](https://user-images.githubusercontent.com/41955268/67569931-7f6f4400-f730-11e9-9b86-1360ebeca110.png)
 and still having the same issue with new version.

BR
ISA

**Comment by krombipils** [comment]
> i copied the reactive dll manually from package to the realease folder

I just noticed the same problem/solution after upgrading to 605.11 on my build server

**Comment by apobekiaris** [comment]
it looks like the vsix activates features that need the Xpand installer at the moment the only fix is to create the directory.

**Comment by isatahiri** [comment]
Thanks It is working now

**Comment by expand** [comment]
eXpand.lab release [19.1.701.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.8) includes commit that relate to this task:

* [VSIX: Remove Xpand.DLL UI message #604](https://github.com/eXpandFramework/eXpand.lab/commit/5cec5e186867bd1d09c5c1f93bdd371fe1eedbba)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
