### ISSUE TITLE
Can't open ModelEditor by Release over 19.1.503

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#605]
Hello,

i'm testing with 19.1.60x and with 19.2.701  i can build an start the application without issues.
but its not possible to open Model Editor

I got everytime issue :

Type:       InvalidOperationException
	Message:    The method can be called only for an instance that was created with the XpoTypeInfoSource(TypesInfo typesInfo) constructor.
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.CheckDictionary()
   bei DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.Reset()
   bei DevExpress.ExpressApp.DC.TypesInfo.Reset()
   bei DevExpress.ExpressApp.DC.TypesInfo.HardReset()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	InnerException is null

with 19.1.503 it works, i've Just update Xpand and Devexpress

one time issue was Rective or depency can'T found, but i've checked and after next restart of VS XPOTypeInfoSource issue comes again

**Comment by apobekiaris** [comment]
is there a log next to the model?

**Comment by rSeeFip** [comment]
This Description is out of Model log.
Sorry, but this is my problem. I find nothing

**Comment by apobekiaris** [comment]
from this description I can only tell the is a mix in XPO Dictionaries, who create or use them is not known.

**Comment by rSeeFip** [comment]
after upgrade to 19.2.301 i can open model editor successfully in Module, in Module.Win and Win i get
issue #609 in ModelEditor and on starting too

**Comment by rSeeFip** [comment]
After i'm now succesfully can create new Project #614 i've got error by trying to open Model Editor.

What i've done.
Create new Expand based Projekt
[Solution2.zip](https://github.com/eXpandFramework/eXpand/files/3792304/Solution2.zip)

I selected all Modules in XAF, same in Expand. Change Target net-Framework from 4.5 to 4.6.1 and
build Project.

Now i trying to open Model Editor and get following issue

![image](https://user-images.githubusercontent.com/43534405/67921513-4dcf0080-fba8-11e9-8d06-17c3160902e8.png)

**Comment by rSeeFip** [comment]
When i try to open it with Devexpress Standalone ModellEditor i got following Message

Der Typeninitialisierer für "Xpand.Persistent.Base.General.XpandModuleBase" hat eine Ausnahme verursacht.

   bei Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   bei Xpand.ExpressApp.Security.XpandSecurityModule..ctor()
   bei Solution2.Win.Solution2WindowsFormsApplication.InitializeComponent() in C:\Workspaces\Testbereich\Solution2\Solution2\Solution2.Win\WinApplication.Designer.cs:Zeile 66.
   bei Solution2.Win.Solution2WindowsFormsApplication..ctor() in C:\Workspaces\Testbereich\Solution2\Solution2\Solution2.Win\WinApplication.cs:Zeile 30.
   bei Create_Solution2WindowsFormsApplication()
   bei DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)

**Comment by apobekiaris** [comment]
I can open the models in your solution with both ModelEditors with no error although I am not sure we are on the same version as I had to set the Specific Version to False in order to compile.

Is there any log in path (both model,bin)

**Comment by rSeeFip** [comment]
[Model.log](https://github.com/eXpandFramework/eXpand/files/3792392/Model.log)
[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/3792399/eXpressAppFramework.log)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
