### ISSUE TITLE
VSIX can no load in 19.1.701.4

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#606]
Hi,

in 19.1.701.4 the installation suceeded but starting VS (VS 2017) I get the error
![error](https://user-images.githubusercontent.com/43132306/67622071-b3bd3000-f816-11e9-8db8-96cab773d3e0.PNG)

and all functions in the Xpand Menu do not work.

Hereby is the ActivityLog.xml

[ActivityLog.zip](https://github.com/eXpandFramework/eXpand/files/3774986/ActivityLog.zip)

**Comment by CWolffIF** [comment]
I went back to 19.1.701.0 and the VSIX installed and the extensions loads.

**Comment by CWolffIF** [comment]
Tested it with 19.1.701.5: The same error.

**Comment by expand** [comment]
eXpand.lab release [19.1.701.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.6) includes commit that relate to this task:

* [VSIX: Restore VSSDK 15 #606](https://github.com/eXpandFramework/eXpand.lab/commit/b12b8e03ae805ba43cb6855f56b292e741002aad)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi Tolis,

no same Error-Message. Here is the ActivityLog.XML with some hints to Xpand.
Hope it helps.

[ActivityLog.zip](https://github.com/eXpandFramework/eXpand/files/3775668/ActivityLog.zip)

**Comment by expand** [comment]
eXpand.lab release [19.1.701.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.7) includes commit that relate to this task:

* [VSIX: Restore ToolsVersion #606](https://github.com/eXpandFramework/eXpand.lab/commit/2c3c2d6f5dbf4db2504bca30a1c67a089b73b1d6)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
I cleared the MEF Cache and installed 19.1.701.7: Same error-message.

[ActivityLog.zip](https://github.com/eXpandFramework/eXpand/files/3775720/ActivityLog.zip)

**Comment by apobekiaris** [comment]
I hope next one is the lucky one.

**Comment by expand** [comment]
eXpand.lab release [19.1.701.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.701.8) includes commit that relate to this task:

* [Bump standalone packages #606

1. CloneModelView: Keep ModelNodeGenerators #601
1. ModelMapper: IModelLayoutGroup Caption is incorrect  #596](https://github.com/eXpandFramework/eXpand.lab/commit/a7fe51aca9d529a41382d4c91149c5e9a83164a2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
That´s the lucky one.
Thanx Tolis.
