### ISSUE TITLE
Change MasterDetailView in Code: Error in LogicRuleEvaluator

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#607]
Hi,

I try to change the MasterDetailView setting of a ListView in Code (like the example from Devexpress).
My Code in the Controller:
            if (View is ListView myView)
            {
                try
                {
                    BeginUpdate();
                    if (Frame.SetView(null, true, null, false))
                    {
                        if (e.SelectedChoiceActionItem.Id == "None")
                        {
                            myView.Model.MasterDetailMode = MasterDetailMode.ListViewOnly;
                        }
                        else if (e.SelectedChoiceActionItem.Id == "Vertical")
                        {
                            myView.Model.MasterDetailMode = MasterDetailMode.ListViewAndDetailView;
                            myView.Model.SplitLayout.Direction = FlowDirection.Vertical;
.....

In the line
Frame.SetView(null, true, null, false)

I got the error
iXISXRM.Win.exe Error: 0 : 26.10.19 19:36:00.994	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei Xpand.ExpressApp.Logic.LogicRuleEvaluator.ViewOnCurrentObjectChanged(Object sender, EventArgs eventArgs) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\Logic\LogicRuleEvaluator.cs:Zeile 56.
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.View.OnCurrentObjectChanged()
   bei DevExpress.ExpressApp.ObjectView.OnCurrentObjectChanged()
   bei DevExpress.ExpressApp.ListView.DoOnListEditorFocusedObjectChanged()
   bei DevExpress.ExpressApp.ListView.listEditor_FocusedObjectChanged(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.Editors.ListEditor.RaiseFocusedObjectChanged()

If I look at line 56
            IsNew = _frame.View.ObjectSpace.IsNewObject(_frame.View.CurrentObject);
I think the _frame is null.

How to avoid?

**Comment by apobekiaris** [comment]
until fixed I guess u need to disable the controller

**Comment by apobekiaris** [comment]
I added a check to avoid throwing however it looks like a side effect of your state and it might throw again later. In any case let me know

**Comment by expand** [comment]
eXpand.lab release [19.2.300.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.13) includes commit that relate to this task:

* [LogicRuleEvaluator throws NullRefrence #607](https://github.com/eXpandFramework/eXpand.lab/commit/fe99a5be2cdacdd5bddafaeb00e2f98e04c9aa7a)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
