### ISSUE TITLE
LayoutControlGroup only works on first opening

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#608]
I´ve got a LayoutControlGroup Setting for expandbutton.
On first opening it works
![ControlGroup1](https://user-images.githubusercontent.com/43132306/67638421-7de67d00-f8e4-11e9-8590-4d0c1ec7d798.PNG)

Then I close the view and open it again
![ControlGroup2](https://user-images.githubusercontent.com/43132306/67638426-8939a880-f8e4-11e9-93c1-60951cdc704a.PNG)

If I look in the Model (at runtime) the settings are still there
![SettingsControlGroup](https://user-images.githubusercontent.com/43132306/67638432-9b1b4b80-f8e4-11e9-9fe7-027087d5d8d0.PNG)

but they don´t work in the view and all other views with expandbuttons the buttons (and the expand feature by doubleclick) are also lost.

There is no error message.

Version 19.1.701.8

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Test Bind_Subsequent_Views #608](https://github.com/eXpandFramework/DevExpress.XAF/commit/bced870139000e49f1eef9e878cf4f1e1a830eb6)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
in addition to adding this test, I also tested manually and couldn't repro the case.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
