### ISSUE TITLE
Cannot start 19.2.300.9 win app

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#609]
with every win solution I tried
Exception while starting :

27.10.19 23:21:19.313	Customize TypesInfo
Solutionenum.Win.exe Error: 0 : 27.10.19 23:21:33.107	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Se han producido uno o varios errores.
	Data:       0 entries
	Stack trace:

   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   en DevExpress.ExpressApp.Win.WinApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   en DevExpress.ExpressApp.XafApplication.Setup()
   en Solutionenum.Win.Program.Main(String[] arguments) en C:\tfs\Varios\Solutionenum.Win\Program.vb:línea 48
	----------------
	InnerException:

			Type:       CompilerErrorException
			Message:    Cannot compile the generated code. Please inspect the generated code via this exception's SourceCode property. The following errors occurred: 
(29853, 14): 'ModelDevExpressXtraEditors_TileItemViewInfo' no implementa el miembro de interfaz 'IModelDevExpressXtraEditors_TileItemViewInfo.Layers'. 'DevExpress.ExpressApp.Model.Core.ModelNode.Layers' no puede implementar un miembro de interfaz porque no es público.

			Data:       0 entries
			Stack trace:

   en DevExpress.ExpressApp.Utils.CodeGeneration.CSCodeCompiler.RaiseCompilerException(String sourceCode, CompilerResults compilerResults)
   en Compile_Patch1(CSCodeCompiler sourceCode, String references, String[] assemblyFile, String )
   en DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.CompileModelAssembly(ICollection`1 customInterfacesToGenerate, ClassDescriptionCollection classDescriptions, CustomLogics customLogics, ModelInterfaceExtenders interfaceExtenders, String assemblyFileAbsolutePath)
   en DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.Get(ICollection`1 customInterfacesToGenerate, ClassDescriptionCollection classDescriptions, CustomLogics customLogics, ModelInterfaceExtenders interfaceExtenders, String assemblyFileAbsolutePath)
   en DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.GetModelAssembly(ModelApplicationCreatorProperties properties)
   en DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.CreateCreatorInfo(ModelApplicationCreator modelApplicationCreator)
   en DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.get_CreatorInfo()
   en DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.AddValidator[T](IModelNodeValidator`1 validator)
   en DevExpress.ExpressApp.SystemModule.SystemModule.AddModelNodeValidators(IModelNodeValidatorRegistrator validatorRegistrator)
   en DevExpress.ExpressApp.ApplicationModelManager.SetupModelApplicationCreator(ModelApplicationCreator creator, IEnumerable`1 modules, IEnumerable`1 aspects)
   en DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
   en DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   en DevExpress.ExpressApp.Win.WinApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   en DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters)
   en DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   en DevExpress.ExpressApp.Win.WinApplication.<>n__0(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   en DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
			InnerException is null

**Comment by apobekiaris** [comment]
Looks like a caching issue, did u try an empty solution?

**Comment by apobekiaris** [comment]
outdated model assembly is what I meant I guess with some system clean it will work

**Comment by vimarx** [comment]
deleted bin/obj and temp with no luck

**Comment by vimarx** [comment]
also the "add xpand "  ,show empty list

**Comment by vimarx** [comment]
sample solution
[Varios.zip](https://github.com/eXpandFramework/eXpand/files/3776932/Varios.zip)

**Comment by krombipils** [comment]
Same issue here with 19.2.300.9.
I also cleaned up everything before.

**Comment by rSeeFip** [comment]
Same issue here with 19.2.300.9
i cleaned up and not found some similar item in model.xafml

**Comment by krombipils** [comment]
As I quick workaround I added this to my win module:
`TypeMappingService.ReservedPropertyTypes.Add(typeof(TileItemViewInfo));
`

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Add missiong base properties/methods to ReservedPropertyNames #609](https://github.com/eXpandFramework/DevExpress.XAF/commit/7ccd0b4f5a262fca8646e86791eb93ddd6f39e81)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by rSeeFip** [comment]
I've same issue with Modelmapper 1.1.58.4 from nuget labs.

Unable to create an instance of the "ModelApplicationCreatorInfo" type.
Reason: "Die Datei oder Assembly "DevExpress.ExpressApp.v19.1, Version=19.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden."

Of course,because i have no 19.1 on system

the type ModelApplicationCreatorInfo is ModelApplicationCreatorInfoBase in 19.2 ExpressApp

**Comment by rSeeFip** [comment]
with 19.2.300.11 application starts without workaround but model editor in Win show issue:

Type:       ArgumentNullException
	Message:    Der Wert darf nicht NULL sein.
Parametername: designerHost.RootComponent
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.GetComponentFromDesigner[ComponentType](ProjectItem projectItem, ITypesInfo typesInfo)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.GetXafApplicationByDesigner(Project project)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	InnerException is null


   

fresh build bin,obj was cleared.

ModelEditor shows Model in Module , but not in Module.Win or Win

**Comment by apobekiaris** [comment]
can u post a sample? this stack says nothing

**Comment by rSeeFip** [comment]
i've tried since 300.9 but by creation of new Expand Project i get empty module list and after closing this empty list VS crash

**Comment by rSeeFip** [comment]
issue from Visual studio 
![image](https://user-images.githubusercontent.com/43534405/67861383-6b588780-fb20-11e9-96bc-278bc0062b39.png)

**Comment by apobekiaris** [comment]
did u try to run VS as admin?

**Comment by rSeeFip** [comment]
only as admin

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
