### ISSUE TITLE
How work IO module

### ISSUE THREAD

**Issue by genetsEvgen** [eXpandFramework/eXpand#610]
How to work with the IO module

"This module was designed to help move objects graphs in the form of XML out of XAF and again in, using the same domain schema. Below you see the objects generation Graph"

**Comment by apobekiaris** [comment]
your post makes no sense please provide detail description of your problem/question

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
