### ISSUE TITLE
null reference opening xtradashboard designer in 19.2.300.10/11

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#613]
it happens when trying to edit a dashboard 
![image](https://user-images.githubusercontent.com/226800/67800407-f6c11280-fa65-11e9-9834-2b9e5761a2db.png)

29.10.19 16:06:46.367	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Referencia a objeto no establecida como instancia de un objeto.
	Data:       0 entries
	Stack trace:

   en Xpand.ExpressApp.XtraDashboard.Win.Templates.DashboardDesignerForm.UpdateActionState()
   en System.EventHandler.Invoke(Object sender, EventArgs e)
   en DevExpress.DashboardWin.Native.History.RaiseChanged()
   en DevExpress.DashboardWin.DashboardDesigner.OnDashboardEndInitialize(Object sender, EventArgs e)
   en DevExpress.DashboardWin.ServiceModel.DashboardLoadingService.OnDashboardEndInitialize()
   en DevExpress.DashboardWin.DashboardViewer.OnHandleCreated(EventArgs e)
   en System.Windows.Forms.Control.WmCreate(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.UserControl.WndProc(Message& m)
   en DevExpress.XtraEditors.XtraUserControl.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

================================================================================

**Comment by expand** [comment]
eXpand.lab release [19.2.300.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.13) includes commit that relate to this task:

* [XtraDashboard: NullRefrence when opening designer #613](https://github.com/eXpandFramework/eXpand.lab/commit/64f938fd02071919cda76ca704c25ca1464bf380)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
NullReference I could repro however I was able to modify and save a dashboard with no erors

**Comment by vimarx** [comment]
Close #613

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
