### ISSUE TITLE
i've tried since 300.9 but by creation of new Expand Project i get empty module list and after closing this empty list VS crash

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#614]
i've tried since 300.9 but by creation of new Expand Project i get empty module list and after closing this empty list VS crash

_Originally posted by @rSeeFip in https://github.com/eXpandFramework/eXpand/issues/609#issuecomment-547898550_

this affects probably only the New Solution Wizard

**Comment by apobekiaris** [comment]
or wait for the fix of https://github.com/eXpandFramework/eXpand/issues/609#issuecomment-546771108

**Comment by rSeeFip** [comment]
yes, will be the best. Thanks for quick response

**Comment by expand** [comment]
eXpand.lab release [19.2.300.12](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.12) includes commit that relate to this task:

* [VSIX: Xpand Solution Wizard is empty #614 #609](https://github.com/eXpandFramework/eXpand.lab/commit/b38c46c252c13155f68863e0942e3f6d932631b2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by rSeeFip** [comment]
ok, i'Ve updated to 19.2.300.12 creating of new Project works now for me too. 

I selected all Modules in XAF, same in Expand. Change Target net-Framework from 4.5 to 4.6.1 and
build Project.

No i try to open Model Editor and get following issue

![image](https://user-images.githubusercontent.com/43534405/67921102-e95f7180-fba6-11e9-9d30-d720e2ae244a.png)

**Comment by rSeeFip** [comment]
[Solution2.zip](https://github.com/eXpandFramework/eXpand/files/3792295/Solution2.zip)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
