### ISSUE TITLE
Add delayed option for RuntimeMembers

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#615]
Hi Tolis,

Feature request for making model setting for runtime members to make them delayed. If we do have members with type System.Drawing.Image, we prefer them delayed. Can this be added? I'm also able to make a PR to add it myself, if you tell me which project.

**Comment by apobekiaris** [comment]
I am  not sure how trivial is it, my guess is u have to create another Type similar to the XpandCollectionMemberInfo and work out the types until u get to the model. Then you have to actually create the type using the logic found in the Xpand.Persistent.Base.RuntimeMembers namespace

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
