### ISSUE TITLE
19.2 - ModelDifference Web Project Error

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#618]
When I launch the web app in 19.2 I get following error.

DevExpress.ExpressApp.DC.ObjectCreatingException: 'Unable to create an instance of the "Xpand.ExpressApp.ModelDifference.ModelDifferenceModule" type.
Reason: "An error with number 1008 has occurred.
Error message: the 'Xpand.XAF.Modules.ModelViewInheritance.ModelViewInheritanceModule' type is not descendant of 'DevExpress.ExpressApp.ModuleBase'
Parameter name: item"'

**Comment by capricciobob** [comment]
It looks like NuGet added the lines in the picture and they all have this error.

See image.
![nugetadd](https://user-images.githubusercontent.com/889492/68048128-54e43480-fcb6-11e9-95aa-68ea2470ed97.PNG)

**Comment by apobekiaris** [comment]
Nuget does nto modify the source code, it looks like the VersionConverter did not run. try in powershell

```ps1
Clear-NugetCache XpandPackages
```

and rebuild

**Comment by capricciobob** [comment]
Worked like a charm, thanks.
