### ISSUE TITLE
CloneModelView Reference to 19.2.3

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#620]
Hi Tolis,

I got an Error on Xpand.XAF.Modules.CloneModelView, Version=1.0.15.3
There is a reference to 
Die Datei oder Assembly "DevExpress.ExpressApp.v19.2, Version=19.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

I´m using 19.1.701.8

**Comment by apobekiaris** [comment]
did u tried to clear the Nuget Cache?
```ps1
Clear-NugetCache XpandPackages
```

**Comment by CWolffIF** [comment]
Yes, cleared all and installed new.
Same Error.

**Comment by apobekiaris** [comment]
I can install the CloneModelView package in a new 17.1 XAF empty solution and run it fine on my side. Does that works for u?

**Comment by CWolffIF** [comment]
It doesn´t work with 19.1.701.8

**Comment by apobekiaris** [comment]
The Lab Server does not contain past packages any more so I cannot understand how u even manage to compile since u cleared your cache it all packages should go missing. You need to either downgrade to official packages from 19.1.701 or upgrade to latest lab

**Comment by CWolffIF** [comment]
In our company we have a Backup Nuget Server. So I can went back to the last runing setting.

**Comment by apobekiaris** [comment]
this however does not remove the xpand packages but restore them in a previous state that is probably the reason it fails.

**Comment by apobekiaris** [comment]
you can try removing the *DoNotDelete directories found in your Nuget path

**Comment by apobekiaris** [comment]
after that build again do u see the Indexing assemblyName messages in your output from VersionConverter?

**Comment by CWolffIF** [comment]
Yes, when I delete the *DoNotDelete directories it is Indexing.


I went back to the versions
Xpand.Collections" version="1.0.1"
Xpand.Extensions" version="0.0.6.2" 
Xpand.Extensions.Reactive" version="0.0.1.2" 
Xpand.Extensions.XAF" version="0.0.6.2" 
Xpand.Extensions.XAF.Xpo" version="0.0.6.2" 
Xpand.Patcher" version="1.0.1" 
Xpand.VersionConverter" version="1.0.36" 
Xpand.XAF.Modules.AutoCommit" version="1.0.16.2" 
Xpand.XAF.Modules.CloneMemberValue" version="1.2.64.2" 
Xpand.XAF.Modules.CloneModelView" version="1.0.14.2" 
Xpand.XAF.Modules.GridListEditor" version="0.0.18.2" 
Xpand.XAF.Modules.HideToolBar" version="1.0.15.2" 
Xpand.XAF.Modules.MasterDetail" version="1.0.15.2" 
Xpand.XAF.Modules.ModelMapper" version="1.1.58.2" 
Xpand.XAF.Modules.ModelViewInheritance" version="1.1.54.2" 
Xpand.XAF.Modules.ProgressBarViewItem" version="1.0.15.2" 
Xpand.XAF.Modules.Reactive" version="1.2.67.2" 
Xpand.XAF.Modules.Reactive.Logger" version="0.0.20.2" 
Xpand.XAF.Modules.Reactive.Win" version="0.0.18.2" 
Xpand.XAF.Modules.RefreshView" version="0.0.18.2" 
Xpand.XAF.Modules.SuppressConfirmation" version="1.0.15.2" 
Xpand.XAF.Modules.ViewEditMode" version="1.2.64.2" 

That was the last setting that worked.

It compiles, but updating the Model (only Win Model) I got the Error
Exception occurs while initializing the 'Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule' module: Methode nicht gefunden: "System.Collections.Generic.IEnumerable`1<!!0> EnumsNET.Enums.GetValues()".

**Comment by apobekiaris** [comment]
so cleaniing fixes the original problem and this a new one? 

>updating the Model (only Win Model) 

what this mean exactly?

**Comment by apobekiaris** [comment]
I cannot tell whats happening there so let's postpone this until u update version

**Comment by CWolffIF** [comment]
Went back to 19.1.701.0.
The project compiles and it starts without error. I try now the update to 19.1.701.8.

**Comment by CWolffIF** [comment]
Update 19.1.701.8 worked.

**Comment by apobekiaris** [comment]
if u get a lot of these consider switching to a local nuget storage
