### ISSUE TITLE
Uninstall VSIX

### ISSUE THREAD

**Issue by guitelnx** [eXpandFramework/eXpand#621]
How do you uninstall VSIX?
Since I installed it, the visual studio is closed when compiling

**Comment by guitelnx** [comment]
ready OK

**Comment by apobekiaris** [comment]
it probably closes because of is not elevated, run it as admin

if u cannnot uninstall it through VS/Extensions/Manage menu then u can force remove it like
```ps1
 "Local", "Roaming" | ForEach-Object {
            Get-ChildItem "$env:USERPROFILE\AppData\$_\Microsoft\VisualStudio" Xpand.VSIX.pkgdef -Recurse | ForEach-Object {
                $directory = [System.IO.Path]::GetFullPath("$($_.DirectoryName)")
                Write-Host "Found in $directory" -f Green
                Get-ChildItem $directory -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
            }
        }
```

Note: That any module that depends on the ModelMapper package requires the VSIX installed

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
