### ISSUE TITLE
CloneModelView does not work in 19.2.3, because VersionConverter does not patch references from attributes

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#623]
CloneModelView module 1.0.15.1 is compiled against DevExpress 19.1.7. VersionConverter correctly patches the references to 19.2.3.
But the `[HarmonyPatch(typeof(ModelViewsNodesGenerator))]` attribute on `ModelViewsNodesGeneratorPatch` generates an hard-coded reference to 19.1.7 which is currently not patched.
This is not directly related to the HarmonyPatchAttribute, but happens on all attributes (accepting a type as parameter).

**Comment by apobekiaris** [comment]
this case is already address I am unassigned

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
