### ISSUE TITLE
GridViewOptions/MasterDetail not work 

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#625]
With Upgrade to 19.2.301.1 GridViewOptions not work not in ListView and either not in
ModelMapper -> MapperContext -> ModelMapperAttribute

It's not only MasterDetail, each configuraition in GridViewOptions has no effect

There is no error, when i  set ReactiveLogger for ModelMapperModule to All nothing happens in LOG

**Comment by rSeeFip** [comment]
With 19.2.402.0 It works, when nox xafml in Application Folder.

Something is changed, to192.301 i able to leave the model.xamlf in 
Application Folder. 
The Appliaction used it only when i erased model on Databse within Application.
Now the XAF.Modules not Work when Model.xamlf in Applixation Folder

**Comment by apobekiaris** [comment]
The framework has tests that for the masterdetail that do not fail, I am afraid without providing repro details I cannot research further

https://github.com/eXpandFramework/DevExpress.XAF/blob/master/src/Tests/MasterDetail/MasterDetailTests.cs

**Comment by rSeeFip** [comment]
It works when i remove the xafml from application Folder, so its ok
