### ISSUE TITLE
Error on udpating framework

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#627]
Hello,

I have installed the ExcelImporter in a new project. After the installation, i had may updates. 
I updated everything except : the Xpand.XAF.Modules.GridListEditor and Xpand.XAF.Modules.Reactive.Logger tries to install : runtime.win-arm64.runtime.native.System.Data.SqlClient.sni and in my project it fails. 

Did i miss something here ? 

Error on update : 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'runtime.win-arm64.runtime.native.System.Data.SqlClient.sni 4.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

BR
ISA

**Comment by apobekiaris** [comment]
which version is this u are trying? I cannot tell how u end up installing SqlClient runtime

**Comment by isatahiri** [comment]
![image](https://user-images.githubusercontent.com/41955268/68722339-71854400-05b5-11ea-88a2-c2102f7c53a9.png)

**Comment by isatahiri** [comment]
I do not know either. This is the first time i got this.

**Comment by apobekiaris** [comment]
I am in the process of integrating https://fsprojects.github.io/Paket/paket-install.html which is a Nuget alternative and will help us deal with them. As I still not finished I need to look those packages again. Do not use the lab builds for the moment

**Comment by isatahiri** [comment]
ok i'll remove them and use the release

**Comment by isatahiri** [comment]
I tried to install the version 19.2.301.3 but i got an exception : 
Exception thrown: 'System.IO.FileNotFoundException' in Brokero.Master.Module.dll
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Brokero.Master.Module.dll
Impossible de charger le fichier ou l'assembly 'Xpand.Persistent.Base, Version=19.2.301.3, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958' ou une de ses dépendances. Le fichier spécifié est introuvable.


How to reporduce : 
Install the excelimporter (eXpandExcelImporter in module project, eXpandExcelImporter.Win in module.win project and eXpandExcelImporter.Web in module.webproject)

Add in module :  this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.ExcelImporterModule));
add in module.win : 
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Win.ExcelImporterWinModule));
add in module.web : 
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Web.ExcelImporterWebModule));

**Comment by isatahiri** [comment]
Previously we did not need to install anything else if we wanted to use ExcelImporter. Has something changed ?

**Comment by isatahiri** [comment]
After this i downgrades to the 19.2.301.2 but same mistake. By the way the process now is very fast but many things seems to be missing copared to last versions. 
Before when we installed the ExcelImporter, we had the eXpandLib, eXapndsecurity. Not anymore. This this part of the update ?

**Comment by isatahiri** [comment]
by the way the removal process is now more difficult, we have to remove (nia nuget) manually stuff by respecting dependencies. Before, when removing excelimporter, all dependencies were removed automatically.

**Comment by expand** [comment]
eXpand.lab release [19.2.301.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.301.4) includes commit that relate to this task:

* [Incorrect Nuspec generation #627](https://github.com/eXpandFramework/eXpand.lab/commit/52f7b200cee881afafb24fcbf00778519d07dcca)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Ok everything seems to be present. Now i have an another issue.
In the issue one of my class is mentionned but if i exclude this class from the project then it take another class. So does not seem to be related to my class. 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\PropertyChanged.Fody.2.6.1\build\..\netclassicweaver\PropertyChanged.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 186
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 109
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Could not inject EventInvoker method on type 'Brokero.Master.Module.BO.Settings.PME_ExcelSplitter'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on Brokero.Master.Module.BO.Settings.PME_ExcelSplitter.
Type:
Fody.WeavingException
StackTrace:
   at ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType) in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:line 84
   at ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType) in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:line 28
   at ModuleWeaver.FindMethodsForNodes() in C:\projects\propertychanged\PropertyChanged.Fody\MethodFinder.cs:line 237
   at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 18
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
Source:
PropertyChanged.Fody
TargetSite:
Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)	Brokero.Master.Module

**Comment by expand** [comment]
eXpand.lab release [19.2.301.5](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.301.5) includes commit that relate to this task:

* [eXpandLib nuget missing dependencies #627](https://github.com/eXpandFramework/eXpand.lab/commit/1358530031e77b18049f42d1ae7f438d71154bf4)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.301.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.301.6) includes commit that relate to this task:

* [eXpandLib nuget missing dependencies #627](https://github.com/eXpandFramework/eXpand.lab/commit/67f4ab0b568b460e7230745a2a15e7dd78c1d69b)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
I just updated in 19.2.301.6 and still issues.
I did a cleanup of the solution and a rebuild.
Should I try to remove the framework and re-add from scratch? 
 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\PropertyChanged.Fody.2.6.1\build\..\netclassicweaver\PropertyChanged.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 186
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 109
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Could not inject EventInvoker method on type 'Brokero.Master.Module.BO.Settings.PME_ExcelSplitter'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on Brokero.Master.Module.BO.Settings.PME_ExcelSplitter.
Type:
Fody.WeavingException
StackTrace:
   at ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType) in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:line 84
   at ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType) in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:line 28
   at ModuleWeaver.FindMethodsForNodes() in C:\projects\propertychanged\PropertyChanged.Fody\MethodFinder.cs:line 237
   at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 18
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
Source:
PropertyChanged.Fody
TargetSite:
Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)	Brokero.Master.Module

**Comment by isatahiri** [comment]
Did a reinstall but  not change. The issue is still the same.

**Comment by apobekiaris** [comment]
do u have fody packages installed in your solution? remove them? maybe they come from a bad release these are design time only packages and should not be distributed

**Comment by itahirikba** [comment]
I have a Foody and PropertyChanged.Foody installed. By default i cannot because Expand dependst on it. By forcing the uninstall, then it works and the project starts. 

By the way, this is a new VS solution and again the Xpand.Persistent.BaseImpl is in my reference with copy local = true but it does not copy it. I have to install eXpandLib package in the Win and Web as standalone.

**Comment by isatahiri** [comment]
I have a Foody and PropertyChanged.Foody installed. By default i cannot because Expand dependst on it. By forcing the uninstall, then it works and the project starts.

By the way, this is a new VS solution and again the Xpand.Persistent.BaseImpl is in my reference with copy local = true but it does not copy it. I have to install eXpandLib package in the Win and Web as standalone.

**Comment by isatahiri** [comment]
There is also a dependency missing with ExcelImporter : 
Exception occurs while assigning the 'XpandListView, ID:ExcelImport_ListView' view to WinWindow:
Impossible de charger le fichier ou l'assembly 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' ou une de ses dépendances. Le fichier spécifié est introuvable.

**Comment by apobekiaris** [comment]
>By the way, this is a new VS solution and again the Xpand.Persistent.BaseImpl is in my reference with copy local = true but it does not copy it. I have to install eXpandLib package in the Win and Web as standalone.

NugetManager can install packages to multiple projects in the solution this was the case always, I am not sure what u wanted to happen or how u did this operation other times

![image](https://user-images.githubusercontent.com/159464/69198465-7447e200-0b3d-11ea-8596-9475df494a37.png)

**Comment by apobekiaris** [comment]
>Exception occurs while assigning the 'XpandListView, ID:ExcelImport_ListView' view to WinWindow:
Impossible de charger le fichier ou l'assembly 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' ou une de ses dépendances. Le fichier spécifié est introuvable.

this a bit strange as the SharpZipLib is a dependency to ExcelDatareader package

```ps1
Get-NugetPackageDependencies ExcelDataReader

Id                  Include Exclude VersionRange
--                  ------- ------- ------------
SharpZipLib         {}      {}      [0.86.0, )
NETStandard.Library {}      {}      [1.6.1, )
System.Data.Common  {}      {}      [4.3.0, )
```

can u repro it on an empty XAF solution? if yes please post the sample and let me know how to repro it.

**Comment by apobekiaris** [comment]
in an empty solution neither Fody or SharpZipLib problems should occured once packages installed.

**Comment by isatahiri** [comment]
I do not know what is going on.  Now with the version 19.2.301.6 i cannot even install it. 

![image](https://user-images.githubusercontent.com/41955268/69281046-dc530280-0be7-11ea-96d0-6054e995ed96.png)

Here is my project : 
[Brokero.Master.zip](https://github.com/eXpandFramework/eXpand/files/3871575/Brokero.Master.zip)

**Comment by apobekiaris** [comment]
I did not check the project yet but this message looks to me VS nuget related, check your VS/Options/Nuget/PackageSources and remove the missing source as it was left there from another installation

**Comment by isatahiri** [comment]
It seems so. I'll do some research...

**Comment by isatahiri** [comment]
Ok i could install the 19.2.301.7 after some cleanup. But still have one dependency missing : SharpZipLib
I installed it manually on version 1.2 and it goes.
