### ISSUE TITLE
Fixed Row Heigths On Listview

### ISSUE THREAD

**Issue by melihyilman** [eXpandFramework/eXpand#628]
Hi Tolis ,
I have issue with listviews. I can't set Fixed Row Heigths.
I tried with controller on XpandMainDemo 

` public partial class ViewController1 : ViewController<ListView> {
        public ViewController1() {
            InitializeComponent();
        }

        protected override void OnViewControlsCreated() {
            base.OnViewControlsCreated();
            ASPxGridListEditor listEditor = ((ListView)View).Editor as ASPxGridListEditor;
            if (listEditor != null)
                listEditor.Grid.HtmlRowCreated += (s, e) => { e.Row.Height = Unit.Pixel(15); };
        }

    }`
but it didn't changed. I guess it's about xpandListview, it changes by row cell values length.
![image](https://user-images.githubusercontent.com/23338993/68738621-d6618e00-05f7-11ea-9376-b72060cbb54a.png)
i asked before devexpress. but it didn't work with Xpand
https://www.devexpress.com/Support/Center/Question/Details/T830147/xaf-web-gridview-row-fixed-height

**Comment by melihyilman** [comment]
Do you have any idea to fix it @apobekiaris

**Comment by apobekiaris** [comment]
without spending time on this, nope I do not.

**Comment by melihyilman** [comment]
kk. I hope you have some time for this :)

**Comment by apobekiaris** [comment]
i am sorry at the moment I am overloaded

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
