### ISSUE TITLE
ExpandFramework and VB.NET

### ISSUE THREAD

**Issue by dlraschka** [eXpandFramework/eXpand#629]
**Question**
I was trying to convert my projects from an older version of expandframework to the new github version. My projects are in VB.NET and I am getting this error with the xpand.versionconverter.ps1

Severity	Code	Description	Project	File	Line	Suppression State
Error		﻿The 'using' keyword is not supported in this version of the language.	

I noticed that both the functions.ps1 and xpand.VersionConverter.ps1 are written in c#

Is VB.NET XAF projects no longer supported or do you have these .ps1 files in vb.net 

Thanks in advance 			

**Additional context**

**Comment by apobekiaris** [comment]
try this https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-5-1

**Comment by dlraschka** [comment]
Thank you very much that did the trick.
