### ISSUE TITLE
VersionConverter - Devexpress version issue

### ISSUE THREAD

**Issue by dlraschka** [eXpandFramework/eXpand#630]
**Question**
I am having issues with a project that I updated to the latest version of expandframework.
The application will not run because its expecting Devexpress.ExpressApp Version 19.1
I combed through the entire project and made sure everything had the latest expandframework version and also made sure xpand.VersionChecker was also enabled on all projects.

I do not have this issue on a new project only this older project.

Can you please point me in the right direction of where to look as to why its 

**Additional context**
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in AMS.Win.exe

Additional information: Could not load file or assembly 'DevExpress.ExpressApp.v19.1, Version=19.1.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The system cannot find the file specified.

**Comment by apobekiaris** [comment]
Which version u upgraded?

**Comment by dlraschka** [comment]
I upgraded from 14.2.7

**Comment by dlraschka** [comment]
I am currently on version 15.1.10 of devexpress XAF

**Comment by apobekiaris** [comment]
I make no sense of your state u said u updated to the latest version of eXpand versioned 19.1.xxx ?? but you use XAF 15.1?? for 19.1 version u need same timed XAF that is 19.1.xxx

**Comment by dlraschka** [comment]
I guess I miss understood, because I thought it didn't matter anymore what version of Devexpress XAF I had. I have version 15.1.10 of Devexpress components. 
I created a new project and it seems to work fine with the 19.1 version of your expandframework.
So your saying that I can not use 19.1 version of your expandframework with version 15.1.10 of devexpress XAF?

**Comment by apobekiaris** [comment]
there are 2 repos ths one and the https://github.com/eXpandFramework/DevExpress.XAF so this one is bound to DX versions however the newer is not as per https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.VersionConverter

**Comment by apobekiaris** [comment]
all packages released from https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules can work with past versions, however we only tests them against the last 3 years so latest test is on 18.2.10 although some packages may work for even older version but we do not have test. 

A compatibility matrix should be released soon
https://github.com/eXpandFramework/DevExpress.XAF#compatibility-matrix

**Comment by dlraschka** [comment]
All of the expandframework packages for my Visual Studio 2015 VB.NET projects  I installed through Nuget. All packages were from http://xaf.expandframework.com and are version 19.1.701
 All my projects use Devexpress version 15.1.10 .

I had an existing project that was using 14.2.7 of the expandframework from before you went to github. I upgraded that one using Nuget to update Expandframework packages to 19.1.701
 
After the updating I get an error asking for devexpress components to be 19.1.701 that I shown you above

in contrast

I create a brand new project in Visual Studio 2015 using the Devexpress 15.1.10 XAF wizard and then use nuget to install the expandframework.  The project compiles and runs and there are no errors

I was wondering what file in the project or what package in the upgraded project is requesting the devexpress components to be 19.1.701 , I checked everything between both projects and I can not determine what needs to be updated on the older project. 

That is what I was after. A new project does not show any errors using Devexpress 15.1.10 yet the updated project does. I figured its something not installed or something needs to be updated.

**Comment by apobekiaris** [comment]
> All packages were from http://xaf.expandframework.com and are version 19.1.701

packages in devexpress.xaf repo are not versioned like this 19.1.xxxx see for yourself https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules#platform-agnostic-modules-list

only the main framework packages are versioned like this and since you use the 19.1.7xxx versions u need XAF 19.1.7. 

>I was wondering what file in the project or what package in the upgraded project is requesting the devexpress components to be 19.1.701 , I checked everything between both projects and I can not determine what needs to be updated on the older project.

All packages named like Xpand.ExpressApp.xxx require XAF 19.1.7 if they are on the 19.1.7.xxx range. Packages named as Xpand.XAF.Modules.xxx can work with any DX version.

**Comment by dlraschka** [comment]
Any chance you still have copies of your framework for DX version 15.1.10 and 15.1.15?

**Comment by apobekiaris** [comment]
u need to get the source for the latest 15.1.xx published
https://github.com/eXpandFramework/eXpand/releases/tag/15.1.8.2

run projectconverter on it and build it using the scripts on the root

**Comment by dlraschka** [comment]
thank you so much!

**Comment by dlraschka** [comment]
I apologize in advance if this troublesome
For the life of me I could not find any instructions on how to build using the scripts or which script to use. I assume I need to run an elevated command prompt and do buildall.cmd .  
I downloaded all the files https://github.com/eXpandFramework/eXpand/releases/tag/15.1.8.2
I assumed I would be working with the Xpand-Source-15.1.8.2.zip as it was the only file that had xpand.dll and also support source. 

The first thing was that in the xpand.dll folder it was missing GACInstaller.exe, I found the source and solution in the support folder. I open the solution in Visual studio 2015 and build the solution and it created the GACINstalller.exe in the xpand.dll folder

Then I used DX project converter on all solutions.

I then started the elevated command prompt and issued the builldall.cmd
it erases gacinstaller.exe after it finishes and there are several errors
I will attach the msbuild.log and the gacinstaller.log and below past the output from the command prompt

**Comment by dlraschka** [comment]
andFramework>
Pending references:
Number of assemblies uninstalled = 0
Number of failures = 0

Press any key to continue . . .
Build Target
  All packages listed in packages.config are already installed.
  FixReferences -> S:\Expand\Xpand-Source-15.1.8.2\Xpand.DLL\FixReferences.exe
S:\Expand\Xpand-Source-15.1.8.2\Xpand.build(109,5): warning MSB3202: The projec
t file "Support\VersionChanger\VersionChanger.sln" was not found.
  All packages listed in packages.config are already installed.
  Xpand.Utils -> S:\Expand\Xpand-Source-15.1.8.2\Xpand.DLL\Xpand.Utils.dll
  All packages listed in packages.config are already installed.
  Xpand.Xpo -> S:\Expand\Xpand-Source-15.1.8.2\Xpand.DLL\Xpand.Xpo.dll
  All packages listed in packages.config are already installed.
General\Controllers\CollectionsEditModeController.cs(33,17): warning CS0618: 'D
evExpress.ExpressApp.Web.ShowViewStrategy.CollectionsEditMode' is obsolete: 'In
 ASP.NET applications, use 'IModelOptionsWeb.CollectionsEditMode' instead. In W
inForms applications, this property is not used anymore.' [S:\Expand\Xpand-Sour
ce-15.1.8.2\Xpand\Xpand.Persistent\Xpand.Persistent.Base\Xpand.Persistent.Base.
csproj]
Validation\FromIPropertyValueValidator\RuleFromIPropertyValueValidator.cs(22,67
): error CS1729: 'DevExpress.Persistent.Base.SimpleValueManager<string>' does n
ot contain a constructor that takes 0 arguments [S:\Expand\Xpand-Source-15.1.8.
2\Xpand\Xpand.Persistent\Xpand.Persistent.Base\Xpand.Persistent.Base.csproj]
Validation\FromIPropertyValueValidator\RuleFromIPropertyValueValidator.cs(31,67
): error CS1729: 'DevExpress.Persistent.Base.SimpleValueManager<string>' does n
ot contain a constructor that takes 0 arguments [S:\Expand\Xpand-Source-15.1.8.
2\Xpand\Xpand.Persistent\Xpand.Persistent.Base\Xpand.Persistent.Base.csproj]
  All packages listed in packages.config are already installed.
PropertyEditors\ComboBoxItemsBuilder.cs(23,66): error CS0308: The non-generic t
ype 'Xpand.Persistent.Base.General.Model.VisibilityCalculators.EditorTypeVisibi
lityCalculator' cannot be used with type arguments [S:\Expand\Xpand-Source-15.1
.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.ExpressApp.csproj]
SystemModule\Appearance\AppearanceController.cs(170,22): error CS0012: The type
 'DevExpress.ExpressApp.Model.IModelNode' is defined in an assembly that is not
 referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.1,
 Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expan
d\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.ExpressAp
p.csproj]
SystemModule\XpandSystemModule.cs(23,49): error CS0234: The type or namespace n
ame 'Actions' does not exist in the namespace 'Xpand.Persistent.Base.General.Co
ntrollers' (are you missing an assembly reference?) [S:\Expand\Xpand-Source-15.
1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.ExpressApp.csproj]
SystemModule\XpandSystemModule.cs(35,25): error CS0012: The type 'DevExpress.Ex
pressApp.ModuleBase' is defined in an assembly that is not referenced. You must
 add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=14.1.5.0, Cu
lture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-Source-15.1.8
.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.ExpressApp.csproj]
SystemModule\XpandSystemModule.cs(35,25): error CS0012: The type 'DevExpress.Ex
pressApp.Model.Core.IModelNodeUpdater`1<T0>' is defined in an assembly that is
not referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14
.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Ex
pand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.Expres
sApp.csproj]
SystemModule\XpandSystemModule.cs(35,25): error CS0012: The type 'DevExpress.Ex
pressApp.Updating.IModelXmlConverter' is defined in an assembly that is not ref
erenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Ver
sion=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xp
and-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\Xpand.ExpressApp.cs
proj]
SystemModule\XpandSystemModule.cs(35,133): error CS0246: The type or namespace
name 'IModifyModelActionUser' could not be found (are you missing a using direc
tive or an assembly reference?) [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.Ex
pressApp\Xpand.ExpressApp\Xpand.ExpressApp.csproj]
  All packages listed in packages.config are already installed.
ListEditors\GridListEditors\ColumnView\Model\ColumnViewModelAdapterController.c
s(23,27): error CS0012: The type 'DevExpress.ExpressApp.ViewController' is defi
ned in an assembly that is not referenced. You must add a reference to assembly
 'DevExpress.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToke
n=b88d1754d700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xp
and.ExpressApp.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(21,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelNode' is defined in an assembl
y that is not referenced. You must add a reference to assembly 'DevExpress.Expr
essApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49
a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Wi
n\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(30,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelColumn' is defined in an assem
bly that is not referenced. You must add a reference to assembly 'DevExpress.Ex
pressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e
49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.
Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(30,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelMemberViewItem' is defined in
an assembly that is not referenced. You must add a reference to assembly 'DevEx
press.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1
754d700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.Exp
ressApp.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(30,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelCommonMemberViewItem' is defin
ed in an assembly that is not referenced. You must add a reference to assembly
'DevExpress.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken
=b88d1754d700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpa
nd.ExpressApp.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(30,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelToolTip' is defined in an asse
mbly that is not referenced. You must add a reference to assembly 'DevExpress.E
xpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700
e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp
.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(51,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelListView' is defined in an ass
embly that is not referenced. You must add a reference to assembly 'DevExpress.
ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d70
0e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressAp
p.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(51,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelObjectView' is defined in an a
ssembly that is not referenced. You must add a reference to assembly 'DevExpres
s.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d
700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.Express
App.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(51,22): error CS0
012: The type 'DevExpress.ExpressApp.Model.IModelView' is defined in an assembl
y that is not referenced. You must add a reference to assembly 'DevExpress.Expr
essApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49
a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Wi
n\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(58,56): error CS0
308: The non-generic type 'Xpand.Persistent.Base.General.Model.VisibilityCalcul
ators.EditorTypeVisibilityCalculator' cannot be used with type arguments [S:\Ex
pand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.Ex
pressApp.Win.csproj]
ListEditors\GridListEditors\AdvBandedView\Model\Interfaces.cs(80,18): error CS0
012: The type 'DevExpress.ExpressApp.Model.ModelNodesGeneratorBase' is defined
in an assembly that is not referenced. You must add a reference to assembly 'De
vExpress.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b8
8d1754d700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.
ExpressApp.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\ColumnView\Model\Synchronizers.cs(75,27): error CS0
012: The type 'DevExpress.ExpressApp.Model.ModelSynchronizer`2<T0,T1>' is defin
ed in an assembly that is not referenced. You must add a reference to assembly
'DevExpress.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken
=b88d1754d700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpa
nd.ExpressApp.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\ColumnView\Model\Synchronizers.cs(171,18): error CS
0012: The type 'DevExpress.ExpressApp.Model.ModelSynchronizer' is defined in an
 assembly that is not referenced. You must add a reference to assembly 'DevExpr
ess.ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d175
4d700e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.Expre
ssApp.Win\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\GridView\Model\Interfaces.cs(7,18): error CS0012: T
he type 'DevExpress.ExpressApp.Model.IModelIsVisible' is defined in an assembly
 that is not referenced. You must add a reference to assembly 'DevExpress.Expre
ssApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a
'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win
\Xpand.ExpressApp.Win.csproj]
ListEditors\GridListEditors\LayoutView\Model\Interfaces.cs(33,53): error CS0308
: The non-generic type 'Xpand.Persistent.Base.General.Model.VisibilityCalculato
rs.EditorTypeVisibilityCalculator' cannot be used with type arguments [S:\Expan
d\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.Expre
ssApp.Win.csproj]
PropertyEditors\RichEdit\RichEditWinPropertyEditor.cs(193,103): error CS0246: T
he type or namespace name 'IPropertyEditor' could not be found (are you missing
 a using directive or an assembly reference?) [S:\Expand\Xpand-Source-15.1.8.2\
Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win.csproj]
PropertyEditors\DurationPropertyEditor.cs(19,61): error CS0308: The non-generic
 type 'Xpand.Persistent.Base.General.Model.VisibilityCalculators.EditorTypeVisi
bilityCalculator' cannot be used with type arguments [S:\Expand\Xpand-Source-15
.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win.csproj]
Editors\ActionButtonDetailItem.cs(10,18): error CS0012: The type 'DevExpress.Ex
pressApp.Editors.ViewItem' is defined in an assembly that is not referenced. Yo
u must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=14.1.5
.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-Source-
15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win.cspro
j]
PropertyEditors\StringPropertyEditors\LabelControlPropertyEditor.cs(20,58): err
or CS0308: The non-generic type 'Xpand.Persistent.Base.General.Model.Visibility
Calculators.EditorTypeVisibilityCalculator' cannot be used with type arguments
[S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xp
and.ExpressApp.Win.csproj]
PropertyEditors\StringPropertyEditors\LabelControlPropertyEditor.cs(46,18): err
or CS0012: The type 'DevExpress.ExpressApp.IModelExtender' is defined in an ass
embly that is not referenced. You must add a reference to assembly 'DevExpress.
ExpressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d70
0e49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressAp
p.Win\Xpand.ExpressApp.Win.csproj]
SystemModule\AutoExpandNewRowController.cs(23,18): error CS0012: The type 'DevE
xpress.ExpressApp.ViewController`1<T0>' is defined in an assembly that is not r
eferenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.1, V
ersion=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\
Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.Express
App.Win.csproj]
SystemModule\LayoutControlGroupModelAdapterController.cs(72,77): error CS0246:
The type or namespace name 'IModelModelAdapterLink' could not be found (are you
 missing a using directive or an assembly reference?) [S:\Expand\Xpand-Source-1
5.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win.csproj
]
SystemModule\XpandSystemWindowsFormsModule.cs(28,25): error CS0012: The type 'D
evExpress.ExpressApp.ModuleBase' is defined in an assembly that is not referenc
ed. You must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=
14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-S
ource-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpand.ExpressApp.Win
.csproj]
SystemModule\XpandSystemWindowsFormsModule.cs(28,25): error CS0012: The type 'D
evExpress.ExpressApp.Model.Core.IModelNodeUpdater`1<T0>' is defined in an assem
bly that is not referenced. You must add a reference to assembly 'DevExpress.Ex
pressApp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e
49a'. [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.
Win\Xpand.ExpressApp.Win.csproj]
SystemModule\XpandSystemWindowsFormsModule.cs(28,25): error CS0012: The type 'D
evExpress.ExpressApp.Updating.IModelXmlConverter' is defined in an assembly tha
t is not referenced. You must add a reference to assembly 'DevExpress.ExpressAp
p.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [
S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\Xpa
nd.ExpressApp.Win.csproj]
  All packages listed in packages.config are already installed.
ListEditors\EditableTabEnabledListEditor\Model.cs(12,69): error CS0308: The non
-generic type 'Xpand.Persistent.Base.General.Model.VisibilityCalculators.Editor
TypeVisibilityCalculator' cannot be used with type arguments [S:\Expand\Xpand-S
ource-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web
.csproj]
ListEditors\TwoDimensionListEditor\Model.cs(12,63): error CS0308: The non-gener
ic type 'Xpand.Persistent.Base.General.Model.VisibilityCalculators.EditorTypeVi
sibilityCalculator' cannot be used with type arguments [S:\Expand\Xpand-Source-
15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.cspro
j]
Editors\ActionButtonDetailItem.cs(9,18): error CS0012: The type 'DevExpress.Exp
ressApp.Editors.ViewItem' is defined in an assembly that is not referenced. You
 must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=14.1.5.
0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-Source-1
5.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.csproj
]
ListEditors\Model\GridViewModelAdapterController.cs(14,18): error CS0012: The t
ype 'DevExpress.ExpressApp.ViewController' is defined in an assembly that is no
t referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.1
, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expa
nd\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.Expr
essApp.Web.csproj]
ListEditors\Model\Interfaces.cs(6,18): error CS0012: The type 'DevExpress.Expre
ssApp.Model.IModelIsVisible' is defined in an assembly that is not referenced.
You must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=14.1
.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-Sourc
e-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.csp
roj]
ListEditors\Model\Synchronizers.cs(8,18): error CS0012: The type 'DevExpress.Ex
pressApp.Model.ModelSynchronizer' is defined in an assembly that is not referen
ced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version
=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-
Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.We
b.csproj]
ListEditors\Model\Synchronizers.cs(20,18): error CS0012: The type 'DevExpress.E
xpressApp.Model.ModelSynchronizer`2<T0,T1>' is defined in an assembly that is n
ot referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.
1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Exp
and\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.Exp
ressApp.Web.csproj]
PropertyEditors\StringPropertyEditor.cs(11,132): error CS0246: The type or name
space name 'IPropertyEditor' could not be found (are you missing a using direct
ive or an assembly reference?) [S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.Exp
ressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.csproj]
SystemModule\PessimisticLockingViewController.cs(6,18): error CS0012: The type
'DevExpress.ExpressApp.ViewController`1<T0>' is defined in an assembly that is
not referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14
.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Ex
pand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.Ex
pressApp.Web.csproj]
SystemModule\WebToolTipsController.cs(10,18): error CS0012: The type 'DevExpres
s.ExpressApp.IModelExtender' is defined in an assembly that is not referenced.
You must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=14.1
.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-Sourc
e-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.csp
roj]
SystemModule\XpandSystemAspNetModule.cs(26,25): error CS0012: The type 'DevExpr
ess.ExpressApp.ModuleBase' is defined in an assembly that is not referenced. Yo
u must add a reference to assembly 'DevExpress.ExpressApp.v14.1, Version=14.1.5
.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Expand\Xpand-Source-
15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.ExpressApp.Web.cspro
j]
SystemModule\XpandSystemAspNetModule.cs(26,25): error CS0012: The type 'DevExpr
ess.ExpressApp.Model.Core.IModelNodeUpdater`1<T0>' is defined in an assembly th
at is not referenced. You must add a reference to assembly 'DevExpress.ExpressA
pp.v14.1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'.
[S:\Expand\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xp
and.ExpressApp.Web.csproj]
SystemModule\XpandSystemAspNetModule.cs(26,25): error CS0012: The type 'DevExpr
ess.ExpressApp.Updating.IModelXmlConverter' is defined in an assembly that is n
ot referenced. You must add a reference to assembly 'DevExpress.ExpressApp.v14.
1, Version=14.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'. [S:\Exp
and\Xpand-Source-15.1.8.2\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Xpand.Exp
ressApp.Web.csproj]
Installing assemblies to GAC...
'".\Xpand.DLL\GACInstaller.exe"' is not recognized as an internal or external co
mmand,
operable program or batch file.
Installing Toolbox Items...
Building Xpand.ToolboxCreator...
Done Xpand.ToolboxCreator
Xpand.ToolBoxCreator.exe Information: 0 : 0 eXpand Assemblies found
Installing and refreshing visual studio templates
Support\Xpand.DesignExperience\vs_templates\cs\XpandFullSolutioncs.v15.1.zip
1 File(s) copied
Support\Xpand.DesignExperience\vs_templates\vb\XpandFullSolutionvb.v15.1.zip
1 File(s) copied
Press any key to continue . . .

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE>

**Comment by dlraschka** [comment]
GACInstaller.exe Information: 0 : Xpand.Utils
    DateTime=2019-11-21T20:29:07.7168262Z
GACInstaller.exe Information: 0 : Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.


Assembly: Xpand.Utils, Version=12.2.8.9, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, processorArchitecture=MSIL
Reference not found:
              SCHEME: <UNINSTALL_KEY>  ID: <eXpandFramework>  DESCRIPTION : <eXpandFramework>  
Pending references:

Assembly: Xpand.Utils, Version=14.1.5.3, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, processorArchitecture=MSIL
Reference not found:
              SCHEME: <UNINSTALL_KEY>  ID: <eXpandFramework>  DESCRIPTION : <eXpandFramework>  
Pending references:
Number of assemblies uninstalled = 0 
Number of failures = 0

    DateTime=2019-11-21T20:29:07.7168262Z
GACInstaller.exe Information: 0 : Xpand.Xpo
    DateTime=2019-11-21T20:29:09.9665670Z
GACInstaller.exe Information: 0 : Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.


Assembly: Xpand.Xpo, Version=12.2.8.9, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, processorArchitecture=MSIL
Reference not found:
              SCHEME: <UNINSTALL_KEY>  ID: <eXpandFramework>  DESCRIPTION : <eXpandFramework>  
Pending references:

Assembly: Xpand.Xpo, Version=13.2.7.3, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, processorArchitecture=MSIL
Reference not found:
              SCHEME: <UNINSTALL_KEY>  ID: <eXpandFramework>  DESCRIPTION : <eXpandFramework>  
Pending references:

Assembly: Xpand.Xpo, Version=14.1.5.3, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, processorArchitecture=MSIL
Reference not found:
              SCHEME: <UNINSTALL_KEY>  ID: <eXpandFramework>  DESCRIPTION : <eXpandFramework>  
Pending references:
Number of assemblies uninstalled = 0 
Number of failures = 0

    DateTime=2019-11-21T20:29:09.9821902Z

**Comment by apobekiaris** [comment]
i do not know hwat the problem but the most obsious thing we see here is that there are multiple version ranges 13.2, 12.2,14.1, U can only have one eXpand version range in your GAC

**Comment by dlraschka** [comment]
I assume those were form past versions of expandframework installation . 
I used gacutil and cleaned them all out.
I was able to build 
Thanks for your help
