### ISSUE TITLE
Dashboard FIlter Removed from Module Model.xafml

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#631]
Whenever I update my Module model.xafml, it removes the Filter node that I get from expand to filter dashboard views. I must be missing some reference in my Module project?

![DashboardFilterDis](https://user-images.githubusercontent.com/889492/69285716-92562680-0bbf-11ea-8e42-7e7167e89c07.PNG)

**Comment by apobekiaris** [comment]
do u see the differences in the ME? does this feature only fails when update the model?

**Comment by capricciobob** [comment]
As long as I manaually put the text in the xafml file, the functionality works great. I just have to remember everytime I save my model, it gets rid of the needed language.

**Comment by capricciobob** [comment]
I'm not using all the modules in this project. Here is my Module.Designer.cs

this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ModelDifference.ModelDifferenceModule));
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Security.XpandSecurityModule));
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule));
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Workflow.XpandWorkFlowModule));

Maybe I am missing a module?

**Comment by apobekiaris** [comment]
since this is a Dashboard case shoulnd' u have that module as well?

**Comment by capricciobob** [comment]
It looks like the missing one was....
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.SystemModule.XpandSystemModule));
