### ISSUE TITLE
Can not open Win.Modul.Model 19.1.701

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#633]
Got the error

Methode nicht gefunden: "System.Collections.Generic.IEnumerable`1<!!0> EnumsNET.Enums.GetValues()".

   bei Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule.Setup(ApplicationModulesManager moduleManager)
   bei Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:Zeile 39.

I think maybe there is a wrong reference. Any idea?

**Comment by CWolffIF** [comment]
Hi,

I solved. The Problem was in an existing Project.
- Deinstalled all components including Xpand.XAF
- Cleared all Caches
- Reinstalled 19.1.701.8 and all dependencies
- Then I got an Error from VersionConverter (1.0.36): "Der Wert "4.8.3752.0 built by: NET48REL1" kann nicht in den Typ "System.Version" konvertiert werden."
- Deinstalled VersionConverter
- Build the Project
- Installed VersionConverter 1.0.36
- Build the Project. The "indexing...." run
- Updated all Model

=> The Win.Modul.Model opens.

I think the "indexing....." that the VersionConverter does was the problem. How can I force it?

**Comment by apobekiaris** [comment]
Indexing... happens after patching if not patching no indexing so what I mean is that for some reason the indexing was skipped initially and after cleaning your cache it restarted. Do u have multiple Dx versions on the same machine? possibly the same packages patched everytime u work on each version? If such a case consider moving your nuget cache to a dedicated folder per project

**Comment by CWolffIF** [comment]
No I do not have multiple DX Versions.

After cleaning cache I can not build the project anymore. No "indexing...."

Error:
1>------ Erstellen gestartet: Projekt: iXISFramework.Module, Konfiguration: Debug Any CPU ------
1>  WARNUNG: Der Wert "4.8.3752.0 built by: NET48REL1" kann nicht in den Typ "System.Version" konvertiert werden. Fehler: 
1>  "Die Eingabezeichenfolge hat das falsche Format."
1>  
1>  Edit C:\DevProjects\iXISJH\iXISFramework.Module\iXISFramework.Module.csproj and enable verbose messaging by adding 
1>  <PropertyGroup><VersionConverterVerbose>Continue</VersionConverterVerbose>. Rebuild the project and send the output to 
1>  support.
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error : Check output warning message
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error : In C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Functions.ps1:264 Zeichen:5
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error : +     throw "Check output warning message"
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : OperationStopped: (Check output warning message:String) [], RuntimeException
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : Check output warning message
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error :  
1>C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\Xpand.VersionConverter.targets(4,9): error MSB3073: Der Befehl "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\DevProjects\NuGetPackages\Xpand.VersionConverter.1.0.36\build\\Xpand.VersionConverter.ps1' 'C:\DevProjects\iXISJH\iXISFramework.Module\iXISFramework.Module.csproj' 'C:\DevProjects\iXISJH\iXISFramework.Module\bin\Debug\' '' ''} " " wurde mit dem Code 1 beendet.
========== Erstellen: 0 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========

**Comment by apobekiaris** [comment]
it looks like it fails to detect the DXVersion, can u try to force it?

```xml
<Project>
 <PropertyGroup>
   <DevExpressVersion>19.2.3</DevExpressVersion>
 </PropertyGroup>
</Project>
```

**Comment by CWolffIF** [comment]
I think the VersionConverter patches the Nugets and I use the nugets from many projects. If I deinstall the VersionConverter it runs.

**Comment by apobekiaris** [comment]
then my suggestion is still on, for the patched projects 

https://stackoverflow.com/questions/4092759/is-it-possible-to-change-the-location-of-packages-for-nuget

**Comment by CWolffIF** [comment]
OK that works.
I can build the model and project and everything works in debug mode. But in release mode I got the error

iXISXRM.Win.exe Error: 0 : 25.11.19 19:56:10.170	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Mindestens ein Fehler ist aufgetreten.
	Data:       0 entries
	Stack trace:

   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei DevExpress.ExpressApp.Win.WinApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.XafApplication.Setup()
   bei iXISXRM.Win.Program.Main()
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Fehler beim Vergleichen von zwei Elementen im Array.
			Data:       0 entries
			Stack trace:

   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Comparison`1 comparison)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetChildrenForSerialization()
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNodes(XmlElement xmlNode, ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.SerializeNode(ModelNode modelNode, Int32 aspectIndex, XmlDocument document)
   bei DevExpress.ExpressApp.Model.ModelXmlWriter.WriteToString(IModelNode modelNode, Int32 aspectIndex)
   bei DevExpress.ExpressApp.ModelCacheManager.Save(ModelApplicationBase model)
   bei DevExpress.ExpressApp.ApplicationModelManager.CreateUnchangeableLayer(ModelStoreBase[] modelDifferenceStores, Boolean cacheApplicationModelDifferences, ModelStoreBase applicationModelDifferenceStore)
   bei DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
   bei DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   bei DevExpress.ExpressApp.Win.WinApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   bei DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters)
   bei DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.Win.WinApplication.<>n__0(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
			----------------
			InnerException:

					Type:       DuplicateModelNodeIdException
					Message:    There is already a node with Id 'UserName'. The node: Application/Views/XpandLogonParameters_DetailView/Layout/Main/RootGroup/EditorsGroup/Editors/UserName. To avoid this error, analyze your custom code or XAFML model differences for possible duplicate nodes creation or follow the www.devexpress.com/kb=S19870 KB article, if you have several classes in different namespaces, but with the same name.
					Data:       0 entries
					Stack trace:

   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(ModelNode node)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(String id, Type type)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.AddClonedNode(ModelNode source, String id)
   bei DevExpress.ExpressApp.SystemModule.ConvertLayoutDiffsController.ConvertLayoutDiffs(IList`1 nodes)
   bei DevExpress.ExpressApp.SystemModule.SystemModule.<>c.<AddModelNodeValidators>b__9_0(IList`1 nodes)
   bei DevExpress.ExpressApp.Model.Core.ModelNodeInfo.UpdateNodes(IList`1 nodeLayers)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.UpdateNodeLayers(IList`1 nodeLayers, Boolean hasFirstLayer)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.PopulateMasterNodesForChildNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.EnsureMaster(ModelMultipleMasterStoreItem masterNodeItem)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.get_Master()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetMasterRecursive()
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetModelValue(String name)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Boolean inThisLayer, Int32 aspectIndex)
   bei DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   bei DevExpress.ExpressApp.Model.Core.SortChildNodesHelper.DoSortNodesByDefault(ModelNode node1, ModelNode node2)
   bei System.Array.FunctorComparer`1.Compare(T x, T y)
   bei System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
					InnerException is null


Any idea?

**Comment by apobekiaris** [comment]
>Type:       DuplicateModelNodeIdException
				Message:    There is already a node with Id 'UserName'. The node: Application/Views/XpandLogonParameters_DetailView/Layout/Main/RootGroup/EditorsGroup/Editors/UserName. To avoid this error, analyze your custom code or XAFML model differences for possible duplicate nodes creation or follow the www.devexpress.com/kb=S19870 KB article, if you have several classes in different namespaces, but with the same name.
				Data:       0 entries
				Stack trace:

Sounds aversion conflict u have multiple same assemblies with different versiosns, also no idea how u manage to have secusss in debug but not in release. Focus on it what the difference. The packages do not take into account Debug,or Release configurations

**Comment by CWolffIF** [comment]
I compared both logs. Both use the same modules and assemblies.
I will try to go back to 19.1.701.

**Comment by CWolffIF** [comment]
I stayed at 19.1.701.8 and found out that the ModelCache (generating the cache file) is the problem.
So I set
winApplication.EnableModelCache = false;
and the release works.
I do not keep on searching, waiting for the 19.2. release and test it again.
