### ISSUE TITLE
RELEASE 19.2.4

### ISSUE THREAD

**Issue by ghost** [eXpandFramework/eXpand#634]
When version 19.2.4 is going to be released

**Comment by apobekiaris** [comment]
I am working on it, when the framework builds are green, you can click the `watch releases` button to get notified

**Comment by apobekiaris** [comment]
more details on the current status. There are are huge delays due to the way the CI pipelines are structured. Previously the test report time could take up to 40 min. As you can understand in some cases where the tests fail on azure only and not locally having such reports times made it impossible to find a way to resolve the problem. 

So we know habe 1.5 min report time which gives me the power to resolve any remote case in reasonable times.

Apologies to all for the delays however as a maintainer this is 1st priority and not releasing a framework that do not even the tests pass and then run around fixing small or big cases from users.

**Comment by apobekiaris** [comment]
further details: 
for having a stable framework I switched to https://fsprojects.github.io/Paket/ which us a Nuget alternative that allows finer dependency control. In addition to the 2 EasyTested XafApplicationss (win/web) which consume our own packages and tested on each build I manage to minimize version issues. This work is ready for the DevExpress.XAF repo only but the main will follow later.

As my test report time is now only 1.5min (not have time for a bite) I am working to resolve further remote only issues like dead locks.

As long as the builds are green with stable/fast pipelines we can have a healthy framework with short support times and new implementations else you can imagine the alternative.

**Comment by apobekiaris** [comment]
19.2.402.0 is now out thanks for the understanding. 

Don't miss the new published Compatibility matrix
https://github.com/eXpandFramework/DevExpress.XAF#compatibility-matrix

![image](https://user-images.githubusercontent.com/159464/70401256-84b1f500-1a37-11ea-8b83-54e467fd5321.png)

**Comment by txt2203** [comment]
After upgrade to 19.2.402.0, build with error : "The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &.....' '' ''} " " exited with code 1."
It happended at line 4 of Xpand.VersionConverter.targets.
how to fix ? I run VS2017 in Admin.
Truong.

**Comment by isatahiri** [comment]
I got the same error : 
Error		+     throw "Check output warning message"	Brokero.Master.Module			
Error		Au caractère C:\Users\isata\Documents\PME	Brokero.Master.Module			
Error		+ CategoryInfo          : OperationStopped: (Check output warning message:String) [], RuntimeException	Brokero.Master.Module			
Error		+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~	Brokero.Master.Module			
Error		Check output warning message	Brokero.Master.Module			
Error			Brokero.Master.Module			
Error		+ FullyQualifiedErrorId : Check output warning message	Brokero.Master.Module			
Error		Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.ps1:99 : 5	Brokero.Master.Module			
Error		The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\\Xpand.VersionConverter.ps1' 'C:\Users\isata\Documents\PME Projects\Brokero.Master\Brokero.Master.Module\Brokero.Master.Module.csproj' 'C:\Users\isata\Documents\PME Projects\Brokero.Master\Brokero.Master.Module\bin\Release\' '' ''} " " exited with code 1.	Brokero.Master.Module

**Comment by isatahiri** [comment]
I wont' build so unable to use it. Any idea Tolis ?

**Comment by apobekiaris** [comment]
i would start by cleanign the nuget cache, if the problem persists posts the actual message from your VS output window

>"Check output warning message"

**Comment by isatahiri** [comment]
Did cleaning cache. 
the full stack : 
 Exception:
1>  ----------
1>  ForEach-Object : Le terme «ConvertTo-FramedText» n'est pas reconnu comme nom d'applet de commande, fonction, fichier 
1>  de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le 
1>  chemin d'accès est correct et réessayez.
1>  Au caractère C:\Users\isata\Documents\PME 
1>  Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Write-HostFormatted.ps1:70 : 21
1>  +             $Object|ForEach-Object{
1>  +                     ~~~~~~~~~~~~~~~
1>      + CategoryInfo          : ObjectNotFound: (ConvertTo-FramedText:String) [ForEach-Object], CommandNotFoundException
1>      + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.ForEachObjectCommand
1>   
1>  ----------------
1>  InvokcationInfo:
1>  ----------------
1>  
1>  
1>  MyCommand             : ForEach-Object
1>  BoundParameters       : {}
1>  UnboundArguments      : {}
1>  ScriptLineNumber      : 70
1>  OffsetInLine          : 21
1>  HistoryId             : 1
1>  ScriptName            : C:\Users\isata\Documents\PME 
1>                          Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Write-HostFormatted.ps1
1>  Line                  :             $Object|ForEach-Object{
1>                          
1>  PositionMessage       : Au caractère C:\Users\isata\Documents\PME 
1>                          Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Write-HostFormatted.ps1:70 
1>                          : 21
1>                          +             $Object|ForEach-Object{
1>                          +                     ~~~~~~~~~~~~~~~
1>  PSScriptRoot          : C:\Users\isata\Documents\PME 
1>                          Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build
1>  PSCommandPath         : C:\Users\isata\Documents\PME 
1>                          Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Write-HostFormatted.ps1
1>  InvocationName        : ForEach-Object
1>  PipelineLength        : 0
1>  PipelinePosition      : 0
1>  ExpectingInput        : False
1>  CommandOrigin         : Internal
1>  DisplayScriptPosition : 
1>  
1>  AVERTISSEMENT : 
1>  
1>  Edit C:\Users\isata\Documents\PME Projects\Brokero.Master\Brokero.Master.Module\Brokero.Master.Module.csproj and enable
1>   verbose messaging by adding <PropertyGroup><VersionConverterVerbose>Continue</VersionConverterVerbose>. Rebuild the 
1>  project and send the output to support.
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error : Check output warning message
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error : Au caractère C:\Users\isata\Documents\PME 
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error : Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.ps1:99 : 5
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error : +     throw "Check output warning message"
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error : +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error :     + CategoryInfo          : OperationStopped: (Check output warning message:String) [], RuntimeException
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error :     + FullyQualifiedErrorId : Check output warning message
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error :  
1>C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'C:\Users\isata\Documents\PME Projects\Brokero.Master\packages\Xpand.VersionConverter.1.1.7\build\\Xpand.VersionConverter.ps1' 'C:\Users\isata\Documents\PME Projects\Brokero.Master\Brokero.Master.Module\Brokero.Master.Module.csproj' 'C:\Users\isata\Documents\PME Projects\Brokero.Master\Brokero.Master.Module\bin\Debug\' '' ''} " " exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by isatahiri** [comment]
it looks like its looking for something that does not find

**Comment by isatahiri** [comment]
1> ForEach-Object : Le terme «ConvertTo-FramedText» n'est pas reconnu comme nom d'applet de commande, fonction, fichier
1> de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le

what is "ConvertTo-FramedText" ?

**Comment by apobekiaris** [comment]
hmm yes let me look the source as this is very strange the ssme VersionCOnverter runs on Azure downloading source from github so nothing comes from my local machine so somethingf is forgotten

**Comment by apobekiaris** [comment]
i see the difference apparently is that your machine does not have the XpandPwsh PS module installed. This is a bug of course but for now u can in a PS admin prompt

```ps1
Install-Module XpandPwsh
```

**Comment by isatahiri** [comment]
much better Thanks ! 
Still got my fody exception. 
1>MSBUILD : error : Fody: Could not inject EventInvoker method on type 'Brokero.Master.Module.BO.Settings.PME_ExcelSplitter'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on Brokero.Master.Module.BO.Settings.PME_ExcelSplitter.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Removed them and it builds without error.

**Comment by apobekiaris** [comment]
At some point u got that package in your project perhaps from an eXpand wrong package dependency, this dependency should not be there please remove it Fody is a design time only package and should not be install without our packages. If this happend report again please

**Comment by isatahiri** [comment]
Still not a planning for the ExcelImporter as standalone ?

**Comment by isatahiri** [comment]
somthing is wrong in the nuget tolis. When I install ExcelImporter in the module it installs the web dll: 
![image](https://user-images.githubusercontent.com/41955268/70485252-b33ed700-1aee-11ea-89be-29be97a2e6a6.png)

**Comment by apobekiaris** [comment]
if u watch this repo I am sure that u agree with me with the way that I prioritize the tasks. So I am now finishing the current CI works that regard build/testing/distribution having those tools in a good shape it is very easy to write catchy modules like ExcelImporter in XAF. Not having a good CI and support you spent your time in vain attempting to support vertical makert modules.

**Comment by isatahiri** [comment]
well i guess you're right. I'm just thinnking that managing these modules in separate module might be easier to support. ExpandFramework is huge and i'm pretty sure that issues would less if it is splitted in smaller modules. But of course that theorical.

**Comment by apobekiaris** [comment]
this really means 2 CI lines to support right? each one with its own problems? sounds like I need to employ people which is also actually ion my plans :)

**Comment by isatahiri** [comment]
Well i was more imagining in the futur that DevExpress.XAF will be covering what ExpandFramework covers currently but by small modules. And people using ExpandFramework will have to migrate. 

At the end, in some point we have to migrate in order to follow. If DevExpress.XAF covers what ExpandFramework is currently offering in a better and more modulable way I do not see any incovenience.  But again that is only my point of view.

**Comment by isatahiri** [comment]
We can easily open a issue as suvey and invite main users or contributors to vote on it.

**Comment by apobekiaris** [comment]
Well, XAF team has its own mindset and level of implementation, I do not see this happening, small stuff yes we steal ideas from each other

**Comment by apobekiaris** [comment]
vote on what?

**Comment by apobekiaris** [comment]
>Still not a planning for the ExcelImporter as standalone ?

it may look that I can do magic due to the experience I have but maturing a module needs time and mine is split around. The best thing I can do is to offer dedicated services if someone really needs something now. Check my new 50% discount tier (before the last one) in my sponsors page and decide if this shared model can work for you.

https://github.com/sponsors/apobekiaris

**Comment by isatahiri** [comment]
> https://github.com/sponsors/apobekiaris

OK lets discuss this tomorrow ! it's kinda interesting for me.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
