### ISSUE TITLE
Cloned View Variant does not reset view settings

### ISSUE THREAD

**Issue by melihco** [eXpandFramework/eXpand#635]
Hi there,
If the user cloned a view on the listview, the cloned view variant does not reset the view settings. Because ResetViewSettingsController makes its own button enabled false. So, the user can not reset changes on the cloned view variant. But, if the view is a root view, the user can reset changes in view.

Do you have any suggestions to reset view changes on a cloned view which is not a root one?

I've been cloning view variant like ;

`private IModelListView CloneView(string id, string viewCaption)
        {
            var modelApplicationBase = (ModelApplicationBase)Application.Model;
            var clonedViewResetEnabled = ((IModelListViewViewClonable)View.Model).ClonedViewResetEnabled;
            if (clonedViewResetEnabled)
            {
                var modelListView = (IModelListView)(((ModelNode)View.Model).Clone(id));
                modelListView.Caption = viewCaption;
                SynchronizeModel(Frame, id);
                var viewXml = modelListView.Xml();
                var clonedViewsStorage = ((IModelApplicationViewVariants)Application.Model).ViewVariants.Storage ?? viewXml;
                var clonedViewStorageLayer = modelApplicationBase.CreatorInstance.CreateModelApplication();
                clonedViewStorageLayer.Id = id;
                new ModelXmlReader().ReadFromString(clonedViewStorageLayer, "", clonedViewsStorage);
                new ModelXmlReader().ReadFromString(clonedViewStorageLayer, "", string.Format("<Application><Views>{0}</Views></Application>", viewXml));
                ((IModelApplicationViewVariants)Application.Model).ViewVariants.Storage = clonedViewStorageLayer.Xml;
                modelListView.Remove();
                modelApplicationBase.AddLayerBeforeLast(clonedViewStorageLayer);
                return (IModelListView)Application.Model.Views[id];
            }
            return (IModelListView)(((ModelNode)View.Model).Clone(id));
        }`

Best Regards, Melih.

**Comment by apobekiaris** [comment]
i do not have specific to your case but u can thin it like this XAF reads the model to create views, you can modify the model and instruct xaf to refresh the view, if its a nested view u need to it for the parent

**Comment by melihco** [comment]
Hi again, 

As ı understand, the root listviews keep their own properties in the model. But, the clone listviews keep their properties in a table whose name is X1_ModelDifferenceAspect. So, ResetViewSetting is not enabled for clone listviews. Because, if a user reset view settings for a Clone ListView, it's going to remove that listview property. So, the listview knows nothing about which is columns as default.

Best Regards, Melih.

**Comment by melihco** [comment]
Are there any suggestions to return the view?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
