### ISSUE TITLE
eXpand for XAF version 16.1.17 ? It exists?

### ISSUE THREAD

**Issue by FernandoARamos** [eXpandFramework/eXpand#637]
I have XAF at version 16.1.17, but I didn´t find this version at Expand. How can I find this? Or compile a version compatible?

Tks

Fernando

**Comment by apobekiaris** [comment]
We do release for past minors released while a newer version is already out. You need to get the latest for 16.1.xxx from the releases pages and use the scripts on the root to build it from scratch

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
