### ISSUE TITLE
Adittionalviewcontrols on detailviews  issue 

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#638]
Additional view controls don't update on property changes in detail views

**To Reproduce**
1. Update feature center app to 19.1 
2. Run app and go to additional view controls/conditional view controls with positioning
3. Change name to more than 20 characters
4. No effect
5.controls appear only if you leave the view and return.

This behavior appeared after upgrading from 17.2 to 19.1

**Comment by apobekiaris** [comment]
to speed up resolution please provide a sample, note that the Featurecenter app is not supported anymore and has been removed in recent source code

**Comment by sam105kelly** [comment]
[FeatureCenter.zip](https://github.com/eXpandFramework/eXpand/files/3932316/FeatureCenter.zip)
Version 19.1

**Comment by sam105kelly** [comment]
I see in model editor the when creating the execution context group ,the ObjectspaceObjectChanged does not exist in higher versions of xpand

**Comment by apobekiaris** [comment]
this context was removed cause it too risky to use because of the large number of invocations and will most probably lead to problems,

**Comment by sam105kelly** [comment]
Is there any way I can add it in my code without modifying expand assemblies?

**Comment by apobekiaris** [comment]
from a quick look, there is no direct way  due to the nature of this feature, however patching can be used for such cases and expand has applied patching successfully using the Xpand.Patcher packages.

**Comment by sam105kelly** [comment]
OK thanks very much

**Comment by sam105kelly** [comment]
Could you please point me to the last version that contained this feature

**Comment by apobekiaris** [comment]
the last commit containing the ObjectspaceObjectChanged  is the https://github.com/eXpandFramework/eXpand/commit/1ea2630243c0b72813db68929013cdf898a69b3e

**Comment by apobekiaris** [comment]
u can look the date of the commit and browse the release to find one at that time
