### ISSUE TITLE
How to map collection properties

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#639]
i have a setup like this.
my class
<code>
 public class NavigationOptions
    {
        public NavigationOptions()
        {
            DashboardViewOptions = new  DashboardViewOptionsConfiguration ();
        }
        public string View2
        { get; set; }

         public DashboardViewOptionsConfiguration DashboardViewOptions
        { get; set; }
       
    }
    public class DashboardViewOptionsConfiguration
    {
        public DashboardViewOptionsConfiguration()
        { ListViewFilters = new ListViewFilterConfigurations(); }
       public ListViewFilterConfigurations ListViewFilters
        { get;  }
    }

    public class ListViewFilterConfigurations: List<ListViewFilterConfiguration>
    {
  

    }

    public class ListViewFilterConfiguration
    {
        public string View
        { get; set; }

        public string Criteria { get; set; }

    }

</code>
when i use
<code>
 NavigationOptions navigationOptions = new NavigationOptions();
  m2.BindTo(navigationOptions);
</code>
every thing works fine except ListViewFilterConfiguration objects are not added to the collection
 How do you create collection properties?
     

**Additional context**

**Comment by apobekiaris** [comment]
no idea what you mean? is this a question about this framework?

**Comment by sam105kelly** [comment]
Its about xpand.xaf.modelmapper module

**Comment by apobekiaris** [comment]
the module only works with metadata the collection items are object instances, this means that feel free to extend further as per your case. Targetting an abstract solution for this case sounded very costly for me when I was writing the module.

**Comment by sam105kelly** [comment]
Thanks for the clarification.

**Comment by sam105kelly** [comment]
Would you please give an example on how to map a class with one collection property?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
