### ISSUE TITLE
DBUpdater crash after Update to 19.2.402.0

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#642]
After Upgrade to 19.2.402.0 DBUpdater Crash
![image](https://user-images.githubusercontent.com/43534405/70497691-3c1c3980-1b14-11ea-9509-a3fe96497a0a.png)

**Comment by apobekiaris** [comment]
does it work in an empty xaf project where the crashed module is registered?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
