### ISSUE TITLE
VersionConverter: The term 'ConvertTo-FramedText' is not recognized

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#643]
When building with 19.2.402 I am getting the following error: 

[test.csproj.txt](https://github.com/eXpandFramework/eXpand/files/3944130/test.csproj.txt)

**Comment by apobekiaris** [comment]
see https://github.com/eXpandFramework/eXpand/issues/634#issuecomment-563501602

**Comment by gerritmulder** [comment]
I don't really those kind of workarounds, I'll wait for an update then.
