### ISSUE TITLE
Need built assemblies of 19.1.6 with updated standalone modules

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#644]
Is it possible to get built assemblies of version 19.1.6 with standalone assemblies updated to the latest assemblies. I am asking this because I work offline

**Comment by apobekiaris** [comment]
it may if there are no breaking changes

**Comment by sam105kelly** [comment]
Is it possible to use versionconverter to patch expand modules to 19.1,
Am thinking I download expand version 19.2.401 and patch it to 19.1.6

**Comment by apobekiaris** [comment]
yes it should be possible and I plan to move to this direction in the future for now you can experiment your self similar to what is done from our TestPipeline
https://github.com/eXpandFramework/DevExpress.XAF/blob/b8c09ac34fd4c38ea123aae96404e4a58adc75e8/tools/Build/TestPipeline.ps1#L75-L79
```ps1
    Get-ChildItem $updates *.dll | ForEach-Object {
        Write-HostFormatted "DevExpress Version Patching $($_.BaseName) $($dxVersion)" -Section
        Switch-ReferencesVersion $_.FullName $dxVersion DevExpress* $snk $allAssemblies
        UpdateVersion $_ $monoPath $allAssemblies
    }
```

the Testpipeline for example download assemblies from an Azure blob and patches them to work with the existent. This is done to spare all the time consume from the BuildPipeline. The technique is applied to DX and Xpand References.

**Comment by sam105kelly** [comment]
Thanks, I will get back to you after testing it out

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
