### ISSUE TITLE
How Can I Open Dashboard From Navigation Items?

### ISSUE THREAD

**Issue by ramos41** [eXpandFramework/eXpand#645]
Hello,

I have many dashboards and I want to show these boards on the navigation items and I did it! But I have a problem. I am getting an error when I clicked the dashboard on the navigation Item. I didn't fix this. How can I do that? I am sending a sample project. You can add a new dashboard and make a test. By the way our version number is 18.2.7

Thank you.

You can download the sample project here : https://gofile.io/?c=VEO3EL

**Comment by apobekiaris** [comment]
does this work with the latest?

**Comment by ramos41** [comment]
Yes, It is working. But we can't upgrade our version to the latest for now. Is there a way to do this in 18.1.6?

**Comment by apobekiaris** [comment]
Frankly the problem here is resources and nothing else. At the moment I have many open cases and this works with the latest thus is not a priority.

**Comment by ramos41** [comment]
Thank you.
