### ISSUE TITLE
Trying to Install Xpand in Clean Azure VM

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#646]
After installing Xpsh in a new Azure VM machine, when trying to install Xpand (Install-Xpand cmd), I receive the following error

![image](https://user-images.githubusercontent.com/226800/71328092-f1c19200-24ef-11ea-96cf-5ae4c5e05779.png)

**Comment by vimarx** [comment]
it works if I use the -version option

**Comment by apobekiaris** [comment]
there is a dedicated pipeline testing the installer https://dev.azure.com/eXpandDevOps/eXpandFramework/_build?definitionId=43., However it is disconnected at the moment due to the recent CI works. I will see to it, thanks

**Comment by apobekiaris** [comment]
actually it looks like this issue most probably related to your network try open the firewall

**Comment by apobekiaris** [comment]
>it works if I use the -version option

oops I guess this was not it if you already installed. I get back to u once enab;e the pipeline

**Comment by apobekiaris** [comment]
the pipeline is now green https://dev.azure.com/eXpandDevOps/eXpandFramework/_build?definitionId=43&_a=summary

added also a badge to monitor its status at the releases page 

![image](https://user-images.githubusercontent.com/159464/71476518-1bc7cc80-27ee-11ea-9bca-0da1f95c4c33.png)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
