### ISSUE TITLE
ScheduledWorkflow only processing the first LaunchScheduleItems collection item?

### ISSUE THREAD

**Issue by jacargentina** [eXpandFramework/eXpand#647]
**Question**
I'm. trying to define more than one `LaunchScheduleItems` but current code simply ignores all items which are not the first

**Additional context**
<img width="479" alt="Captura de Pantalla 2019-12-27 a la(s) 14 11 49" src="https://user-images.githubusercontent.com/517228/71525928-dae5bb80-28b2-11ea-95eb-ef3a5b1fbaac.png">

Current code

<img width="997" alt="Captura de Pantalla 2019-12-27 a la(s) 14 13 45" src="https://user-images.githubusercontent.com/517228/71525979-24cea180-28b3-11ea-8195-5b2b46d6da51.png">

**Comment by apobekiaris** [comment]
it looks like a logic problem however at the moment I am overloaded so it will take some time until I reach this case.  However PR are acceptable and totally possible from your side judging from the question.

**Comment by jacargentina** [comment]
@apobekiaris thanks for your fast response

BTW, I'm also a little overloaded for a PT and also I've my own classes (which I've copy pasted some time ago); what I've just written after you've confirmed, is this (hope this helps)

```csharp
 protected override bool NeedToStartWorkflow(IObjectSpace objectSpace, ScheduledWorkflow workflow)
        {
            var needStart = false;
            foreach (var schedule in workflow.LaunchScheduleItems)
            {
                switch (schedule.StartMode)
                {
                    case StartMode.OneTime:
                        if (NeedToStartOneTime(workflow, schedule))
                            needStart = true;
                        break;
                    case StartMode.Min:
                        if (NeedToStartMin(workflow, schedule))
                            needStart = true;
                        break;
                    case StartMode.Daily:
                        if (NeedToStartDaily(workflow, schedule))
                            needStart = true;
                        break;
                    case StartMode.Weekly:
                        if (WeeklyDayMatch(schedule))
                        {
                            if (workflow.LaunchScheduleItems.Count > 0 && NeedToStartWeekly(workflow, schedule))
                                needStart = true;
                        }
                        break;
                }
            }
            return needStart;
        }
```

**Comment by apobekiaris** [comment]
thnks for the patch I will update the source when I review this case.

**Comment by apobekiaris** [comment]
Issue is prioritized as it contains one of the following labels ***sponsor***, **installation**, **contribution**, **nuget**, **breakingchange**, **ReproSample**, **Deployment**

**Comment by expand** [comment]
eXpand.lab release [19.2.502.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.502.3) includes commit that relate to this task:

* [ScheduledWorkflow only processing the first LaunchScheduleItems collection item? #647](https://github.com/eXpandFramework/eXpand.lab/commit/0f7ad7f2616fcd7d594bcf183940c06de11e6e03)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
