### ISSUE TITLE
eXpandLib 19.2.501 problem

### ISSUE THREAD

**Issue by nurbed** [eXpandFramework/eXpand#650]
**Describe the bug**
After the update to the 19.2.501 version of the library I have an error due to absence of the  Xpand.Persistent.Base.dll file

**To Reproduce**
Update DevExpress to the 19.2.5 version
Update eXpandLib to the 19.2.501 version
Compile

**Screenshots**

*Version 19.2.403 with Xpand.Persistent.Base.dll file*
![image](https://user-images.githubusercontent.com/3589082/71679090-0a9b3480-2d87-11ea-858d-76c5d18d33aa.png)

*Version 19.2.501 without Xpand.Persistent.Base.dll file*
![image](https://user-images.githubusercontent.com/3589082/71679142-2b638a00-2d87-11ea-9541-269b9d145d6d.png)

**Comment by isatahiri** [comment]
The last lab version works. Try it

**Comment by nurbed** [comment]
Ok, with the version 19.2.501.5 the app compile...
but when I try to open the module.cs file, the designer hangs with the error: "Unable to create an instance of the "Xpand.ExpressApp.Security.XpandSecurityModule" type.
Reason: "The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception.""

**Comment by apobekiaris** [comment]
what is the exception?

**Comment by nurbed** [comment]
After the uptate to the version 19.2.502.0 everything works...
