### ISSUE TITLE
Not showing Module_eXpandFramework v19.2 XAF Solution Wizard --Not work

### ISSUE THREAD

**Issue by uniqueitmail** [eXpandFramework/eXpand#651]
**VS 2019 16.0.4**
Using DevExpress 19.2.5 but not showing module add since eXpand Wizard -time.
Please see attached~

**Blank --Add Module--**
Please solved the issue....
![Not showing --Module](https://user-images.githubusercontent.com/16665892/71736818-4532c900-2e7c-11ea-9eef-2a855fe2bd3f.png)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
