### ISSUE TITLE
File not Found in Build Script for Devexpress.XAF

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#653]
Hello.

when i try to build Devexpress.XAF Modules i'm firstly run the go.ps1

But since actual Release i got File not found error the script should use path 

C:\Program Files (x86)\DevExpress 19.2\Components\System\Components\packages

but it use only C:\Program  and says path not found

![image](https://user-images.githubusercontent.com/43534405/71886996-7d1c6380-313d-11ea-80b5-c8a9a2e68755.png)

**Comment by apobekiaris** [comment]
hmm i am not sure if go.ps1 works with no problems can you try 

```ps1
& .\tools\Build\BuildPipeline.ps1 -CustomVersion $DXVersion -dxapifeed $env:localDXFeed -branch "master"
```

**Comment by apobekiaris** [comment]
the script i posted is used from AzureDevOps so it works for sure

**Comment by rSeeFip** [comment]
I tried but i get another file not found exception

![image](https://user-images.githubusercontent.com/43534405/71892903-819b4900-314a-11ea-92a9-ae258008d9a2.png)

**Comment by apobekiaris** [comment]
hmm the exception is clear a `System` assembly is missing, When I run in my system

```ps1
Get-XAFLatestMinors

Major  Minor  Build  Revision
-----  -----  -----  --------
19     2      5      0
19     1      8      0
18     2      11     0
```

The pipeline definition is loaded at the same folder BuildPipeline.yml and the Compatibity Matrix is green for 18.2.11 https://github.com/eXpandFramework/DevExpress.XAF#compatibility-matrix. The project does not use loca dependecies, they all come from Nuget.

Unfortunately i cannot tell why it fails in your system. Try adding the missing assembly to the GAC

**Comment by apobekiaris** [comment]
what the version of XpandPwsh module?

```ps1
get-module Xpandpwsh -ListAvailable


    Directory: C:\Work\eXpandFramework\XpandPwsh

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.192.35   XpandPwsh                           Desk      {New-GithubReleaseNotesTemplate, Close-GithubIssue, Update-NugetProjectVersion, Find-XpandNugetPackage…}
```

**Comment by apobekiaris** [comment]
try uninstall all version of XpandPwsh from your system and then run the build script

```ps1
uninstall-module XpandPwsh -AllVersions
```

**Comment by rSeeFip** [comment]
always miss System.ComponentModel.Annotations  
![image](https://user-images.githubusercontent.com/43534405/71900762-bb764a80-315e-11ea-8785-fb69dbae7800.png)

I've installed it manually from nuget get in the Modules Extensions Project, but not helps.

**Comment by rSeeFip** [comment]
actual installed XpandPwsh
![image](https://user-images.githubusercontent.com/43534405/71900892-009a7c80-315f-11ea-98a6-6da4559fef8a.png)

**Comment by apobekiaris** [comment]
first the latest version of XpandPwsh is 

```ps1
find-module xpandpwsh

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.192.35             XpandPwsh                           PSGallery            Various functions working with DevExpres…
```

and you use .14

maybe there is

**Comment by rSeeFip** [comment]
I've uninstall all and then run go.ps1 

so thru go.ps1 old version get installed

**Comment by apobekiaris** [comment]
ok i got what is happening now you unde powershell but this is designed to run over powershell.core so 

``ps1
dotnet tool install --global PowerShell
pwsh
& .\BuildPipeline.ps1
```

**Comment by rSeeFip** [comment]
for note

i've uninstall XpandPwsh, manually install Version 1.192.35 sucessfully,
after running go.ps1 i got two versions 1.192.35 and 1.92.14

**Comment by apobekiaris** [comment]
.14 is correct version as it is installed with the latest source u can upgrade if u wish though by installing the latest XpandPwsh first and then running the build

**Comment by apobekiaris** [comment]
it is not required to update to latest

**Comment by rSeeFip** [comment]
i 've testet with .35 and .14 and both. Not work.
With using of go.ps1 i get always folder C:\Program not exists, sure it calls C:\Program Files...
by using of 
.\tools\Build\BuildPipeline.ps1 -CustomVersion $DXVersion -dxapifeed $env:localDXFeed -branch "master"

i got issue "miss System.ComponentModel.Annotations 4.2" which when i google is a steady problem 
in gac i have System.ComponentModel.Annotations 4.8

All what i have change from last sucessfully build 2 weeks ago id installing devexpress 19.2.5 and
expand , no windows updates or something else

this why i'am surprised how can this happen

**Comment by rSeeFip** [comment]
i've checked backup clone from production system last month ago their was too

 System.ComponentModel.Annotations 4.8

in GAC, so it could not be to changing module from 4,2 to 4,8

**Comment by apobekiaris** [comment]
it seems that u do not understand what I said in https://github.com/eXpandFramework/eXpand/issues/653#issuecomment-571606278

the Annotations problem is because you run the script from powershell.exe and not from pwsh.exe.
pwsh.exe is the powershell.core version which u have to install in your system in order to run the scripts. Once install you Start/Run --> pwsh.exe and in the command prompt you run the scripts.

**Comment by apobekiaris** [comment]
all other suggestions about GAC etc. are not valid

**Comment by rSeeFip** [comment]
i understand i use pwsh.exe
![image](https://user-images.githubusercontent.com/43534405/72052989-75d49180-32c6-11ea-85b5-a7e862230c38.png)

**Comment by apobekiaris** [comment]
check how is done in azure 

https://github.com/eXpandFramework/DevExpress.XAF/blob/ab6e69f927ac369530c4ca58f2075c656ee3d039/tools/Build/BuildPipeline.yml#L32-L46

copy paste the lines and explicity declare all parameters

**Comment by apobekiaris** [comment]
the error u get says that the DX package source is not found which means that u either do not have DX installed or u installed it in a non default path

**Comment by rSeeFip** [comment]
No, thats what i've checked in first topic in this chat, folder and files exists
![image](https://user-images.githubusercontent.com/43534405/72053736-e62fe280-32c7-11ea-80ac-3c59c44096cd.png)

**Comment by apobekiaris** [comment]
did you tried to use your DX feed instead of your local folder as a source?
e.g. https://nuget.devexpress.com/88luCgoeuPFT....

**Comment by rSeeFip** [comment]
ok, i used as package Source my DX feed, it's little better .
it found Web.Themes and Scheduler.Web  libs but crash by finding Charts lib and further
![image](https://user-images.githubusercontent.com/43534405/72055580-5d1aaa80-32cb-11ea-81d7-2f20096d8bfd.png)



so i'm not able to solve this, i must wait for next expand.lab build

**Comment by apobekiaris** [comment]
still is on local source somehow try the following search and replace the C:\Program files... with your nuget feed to all paket.dependencies and paket.lock files found in the repo source

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/1a259535cad5d9df1bc6eb6df1e7e6fd48c13c03)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/764666de79495032e7f598f8581f663ef72626fc)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by dsikic** [comment]
Use your DX nuget feed not @apobekiaris 's URL from above. Example: 
![packages](https://user-images.githubusercontent.com/25459554/73274686-f5fa6280-41b3-11ea-9745-61f5461e0ecd.png)

**Comment by dsikic** [comment]
More specifically in packet.lock where it says remote: C:\Program change to remote: <your DX nuget feed ending with /api>

**Comment by dsikic** [comment]
@apobekiaris Please change packet.lock line to end with / and wrap with. 
Like so:

https://github.com/eXpandFramework/eXpand/commit/18c20136af577e31a7d6a13a34d241eec5ad189e

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
