### ISSUE TITLE
ModelMapper  & WC Module

### ISSUE THREAD

**Issue by melihyilman** [eXpandFramework/eXpand#656]
Hi,
To realize issue steps:
Devexpress:19.2.5 & xpand ps . 19.2.502.0
*Add new class&object to WorldCreator module name doesn't matter . for example XXX
*Go to model and select XXX_DetailView and change something on Layout. Save Layout changes.
* Open XXX_ListView and press new button 

You'll see this

`The object reference is not set to an instance of an object.

   at:Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindToModel(IModelNodeDisabled modelNodeDisabled, Object instance)
   at:Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindTo(ValueTuple`3 data)
   at:Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.<>c.<BindLayoutGroupControl>b__5_3(ValueTuple`3 tuple)
   at:System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   at:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at:System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at:System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at:System.Reactive.Sink`1.ForwardOnError(Exception error)
   at:System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   at:System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   at:System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at:System.Reactive.ObserverBase`1.OnError(Exception error)
   at:System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at:System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   at:System.Reactive.Sink`2.OnError(Exception error)
   at:System.Reactive.Sink`1.ForwardOnError(Exception error)
   at:System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
   at:System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at:System.Reactive.ObserverBase`1.OnNext(T value)
   at:Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass8_1`1.<Trace>b__2(TSource v)
   at:System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at:System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at:System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   at:System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at:System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at:System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at:System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
   at:System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at:System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at:System.Reactive.Subjects.Subject`1.OnNext(T value)
   at:System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at:DevExpress.ExpressApp.Layout.LayoutManager.OnCustomizeAppearance(CustomizeAppearanceEventArgs args)
   at:DevExpress.ExpressApp.Win.Layout.WinLayoutManager.LayoutControls(IModelNode layoutNode, ViewItemsCollection viewItems)
   at:DevExpress.ExpressApp.View.CreateControls()
   at:DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   at:DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   at:DevExpress.ExpressApp.Win.Templates.ViewSiteManager.OnViewChanged()
   at:DevExpress.ExpressApp.Win.Templates.Bars.DetailFormV2.DevExpress.ExpressApp.Templates.IFrameTemplate.SetView(View view)
   at:DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   at:DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)`

**Comment by apobekiaris** [comment]
sounds related to #653

**Comment by melihyilman** [comment]
@apobekiaris 
i deleted all %reactive% modules from project. But still it's creating :/ how do i disable Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService?
![image](https://user-images.githubusercontent.com/23338993/72070400-8c94db80-32fa-11ea-9903-4c5cdc2c07ae.png)

**Comment by apobekiaris** [comment]
the assemblies cannot be removed you may try unload them as per docs
https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper#issues-debugging-troubleshooting

**Comment by melihyilman** [comment]
i guess it ModelDifference depended this.

`Exception occurs while initializing the 'Xpand.ExpressApp.ModelDifference.Win.ModelDifferenceWindowsFormsModule' module: ModelMapperModule not installed

   konum: Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
   konum: SetupModules_Patch1(ApplicationModulesManager )
   konum: DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   konum: DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   konum: DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   konum: System.Threading.Tasks.Task.Execute()`

**Comment by apobekiaris** [comment]
hmm the message implies that ModelMapper was not unload

**Comment by melihyilman** [comment]
i tried with constructor and SetupComplette. They give me same result
  `Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.ModelMapper.ModelMapperModule));`
So if i use modeldifference tmodule hen it cant unloaded?

**Comment by apobekiaris** [comment]
#640 is about a similar case where i provided a workaround, also coonsider using the latest version .502

**Comment by melihyilman** [comment]
i installed 502 version yesterday. Do you mean lab builds?

**Comment by apobekiaris** [comment]
>Devexpress:19.2.5 & xpand 19.2.501.0

http://releases.expandframework.com/

**Comment by melihyilman** [comment]
opss. Sorry for that.
![image](https://user-images.githubusercontent.com/23338993/72072928-f499f080-32ff-11ea-9632-c98d33a0e406.png)

**Comment by apobekiaris** [comment]
ok then follow #640 the case is the same and in addition #653 patch once is out it will workround it hopefully

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/1a259535cad5d9df1bc6eb6df1e7e6fd48c13c03)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/764666de79495032e7f598f8581f663ef72626fc)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by melihyilman** [comment]
> The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:
> 
> * [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/1a259535cad5d9df1bc6eb6df1e7e6fd48c13c03)
> 
> Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).
> 
> If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.
> 
> Thanks a lot for your contribution.

Did the version number is correct?

**Comment by apobekiaris** [comment]
yes https://github.com/eXpandFramework/eXpand.lab/releases/tag/19.2.502.1 includes this fix. Do u still having issues? if yes provide a sample

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
