### ISSUE TITLE
19.2.502 contains references to lab versions of stand alone modules

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#657]
Hi Tolis

I'm trying to use the new eXpand version, but it seems to have references to lab version of the stand alone nuget modules. This makes building impossible

Thanks,
Jacob

**Comment by apobekiaris** [comment]
Hi,

please be specific which references and also note that the build is possible at least on a clean VM like the ones used in Azure DevOps

**Comment by jacobdeboer33** [comment]
Hi Tolis

Here's a copy of the errors I'm getting:
Error	NU1102	Unable to find package Xpand.XAF.Modules.ModelViewInheritance with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ModelMapper with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneModelView with version (>= 2.192.27.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.GridListEditor with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneMemberValue with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ProgressBarViewItem with version (>= 2.192.28.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.RefreshView with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneModelView with version (>= 2.192.27.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ModelViewInheritance with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneMemberValue with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneModelView with version (>= 2.192.27.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.HideToolBar with version (>= 2.192.28.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ProgressBarViewItem with version (>= 2.192.28.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.Reactive.Logger with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ModelViewInheritance with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ModelMapper with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneMemberValue with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.CloneModelView with version (>= 2.192.27.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.HideToolBar with version (>= 2.192.28.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.ProgressBarViewItem with version (>= 2.192.28.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.Reactive.Logger with version (>= 2.192.4.2)
Error	NU1102	Unable to find package Xpand.XAF.Modules.RefreshView with version (>= 2.192.4.2)
etc....

Maybe you have the lab source added?

Thanks,
Jacob

**Comment by gerritmulder** [comment]
If I just search in this repository for 2.192.4.2 I get plenty of nuspecs containing versions not available on the main NuGet package source.
https://github.com/eXpandFramework/eXpand/search?p=2&q=2.192.4.2&unscoped_q=2.192.4.2

**Comment by apobekiaris** [comment]
thnks for the input, I will check it, can u also tell me what is the problem using the lab nuget server temporarly to continue your work?

**Comment by gerritmulder** [comment]
Since the lab version has usually more problems for us then the release version we prefer to just stay on the previous version until there is a new release.

**Comment by apobekiaris** [comment]
fair enough thnks again

**Comment by gerritmulder** [comment]
thank you too for your service

**Comment by jacobdeboer33** [comment]
Hi Tolis

Thanks alot! You're the greatest! (by far)

Thanks,
Jacob

**Comment by apobekiaris** [comment]
Issue is prioritized as it contains one of the following labels ***sponsor***, **installation**, **contribution**, **nuget**, **breakingchange**, **ReproSample**, **Deployment**

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Add CheckVersion build task #657](https://github.com/eXpandFramework/DevExpress.XAF/commit/6d6d1ffe1c300885cac0596d84926ac0301c9910)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.502.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.502.2) includes commit that relate to this task:

* [add CheckStandalonePackageVersions build task #657](https://github.com/eXpandFramework/eXpand.lab/commit/ffd848f22f894f65c9abafec595464b19b8931ae)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
