### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by moodmosaic** [eXpandFramework/eXpand#658]
**Question**
Any plans to have the standalone packages target .NET Standard?

**Comment by apobekiaris** [comment]
Hi

As you know XAF already has many modules ported. However XAF Blazor is still on CTP and has long way to go. Therefore it a bit early for us to consider porting however for sure will follow.

**Comment by expand** [comment]
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
