### ISSUE TITLE
IsCollapsibleGroup Error in LayoutControlGroupModelAdapterController

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#659]
I got an Error if I use the IsCollapsibleGroup Layout Option from Devexpress in Version 19.2.5.
The there is the error in the Xpand LayoutControlGroupModelAdapterController.

To reproduce:
- The the Option in the Modeleditor (IsCollapsibleGroup)
- Expand or Collapse the Group

iXISXRM.Win.exe Error: 0 : 16.01.20 07:07:53.718	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei Xpand.ExpressApp.Win.SystemModule.LayoutControlGroupController.OnGroupExpandChanged(Object sender, LayoutGroupEventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\LayoutControlGroupModelAdapterController.cs:Zeile 23.
   bei DevExpress.XtraLayout.LayoutControl.DevExpress.XtraLayout.ILayoutControl.RaiseGroupExpandChanged(LayoutGroupEventArgs e)
   bei DevExpress.XtraLayout.LayoutGroup.set_Expanded(Boolean value)
   bei DevExpress.ExpressApp.Win.Layout.XafLayoutControlGroup.set_Expanded(Boolean value)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.DoInvertGroupExpanded(LayoutGroup group)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.ProcessGroupActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.PerformOwnersActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.BaseLayoutItemHandler.PerformControlActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.PerformControlActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.PerformChildHandlerActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.PerformControlActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.OnMouseDown(MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.OnMouseDown(Object sender, MouseEventArgs e)
   bei DevExpress.XtraLayout.LayoutControl.OnMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ContainerControl.WndProc(Message& m)
   bei DevExpress.XtraLayout.LayoutControl.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

**Comment by apobekiaris** [comment]
the error points to 

https://github.com/eXpandFramework/eXpand/blob/f916916dcf045b5317c48a8d7740fdc169f86fe4/Xpand/Xpand.ExpressApp/Xpand.ExpressApp.Win/SystemModule/LayoutControlGroupModelAdapterController.cs#L23

which means that the ModelMapper node was not found, post the modeldifference for this group node please

**Comment by CWolffIF** [comment]
You are Right. The Node is Not there. Must I add these nodes manualy?

**Comment by apobekiaris** [comment]
first we need to find out what so special about this node and is not extended

**Comment by CWolffIF** [comment]
The modenode (Module.Win) was not there, but the View was modiefied in the existing project. I Reset differences for the view and modelnode was visible in the modeleditor. So everything works.

How can i update an existing model (Module.Win) with out setting back all differences?

**Comment by CWolffIF** [comment]
Sorry

**Comment by apobekiaris** [comment]
show me the model as I requested before for the node that fails

**Comment by CWolffIF** [comment]
I found out something strange. When I start app and look in model everything looks fine and the it works for the first time I opened the DetailView.
see Nodes1
![Nodes1](https://user-images.githubusercontent.com/43132306/72549873-d5680980-3891-11ea-9243-9144561847ec.PNG)


In the second opening the model is changed and the modeladapter nodes are deleted.
see Nodes2


![Nodes2](https://user-images.githubusercontent.com/43132306/72550035-28da5780-3892-11ea-83f3-1200d70cb262.PNG)


Here is the diff 
    <DetailView Id="AccountingVoucher_DetailView">
      <Layout>
        <LayoutGroup Id="Main">
          <LayoutGroup Id="Autoc3896482-ddd9-449c-8468-0c826f4fdf8f" RelativeSize="93.066666666666663">
            <LayoutGroup Id="SimpleEditors" RelativeSize="30.266666666666666">
              <TabbedGroup Id="Item3">
                <LayoutGroup Id="AccountingVoucher">
                  <LayoutGroup Id="AccountingVoucher_col1" RelativeSize="48.898678414096914">
                    <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
                  </LayoutGroup>
                  <LayoutGroup Id="AccountingVoucher_col2" RelativeSize="51.101321585903086">
                    <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
                  </LayoutGroup>
                  <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
                </LayoutGroup>
                <LayoutGroup Id="Item4">
                  <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
                </LayoutGroup>
              </TabbedGroup>
              <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
            </LayoutGroup>
            <TabbedGroup Id="Item2" RelativeSize="69.733333333333334">
              <LayoutGroup Id="AccountingVoucherPositions">
                <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
              </LayoutGroup>
              <LayoutGroup Id="AccountingInformation">
                <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
              </LayoutGroup>
              <LayoutGroup Id="AccountingJournals">
                <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
              </LayoutGroup>
            </TabbedGroup>
            <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Removed="True" />
          </LayoutGroup>
          <SplitterItem Id="SplitterItem1" RelativeSize="1.6" />
          <LayoutGroup Id="Item1" RelativeSize="5.333333333333333" IsGroupCollapsed="True">
            <DevExpressXtraLayout_LayoutControlGroup Id="LayoutControlGroup" Expanded="True" Removed="True" />
          </LayoutGroup>
        </LayoutGroup>
      </Layout>
    </DetailView>

**Comment by apobekiaris** [comment]
I suggest u disable the problematic controller and I will see to it when my time allows it.

**Comment by CWolffIF** [comment]
Hi Tolis,

what is the problematic Controller for the modelmapper?

**Comment by apobekiaris** [comment]
this case most probably relates to the removed nodex and throws in the LayoutControlGroupModelAdapterController so I guess disabling the controller it will let u work until is fixed.

**Comment by CWolffIF** [comment]
Sorry for the question. How to disable? I can´t find the controller in the model.

**Comment by apobekiaris** [comment]
use this class in your project

```cs
    public class MyClass:LayoutControlGroupController {
        protected override void OnActivated() {
            
        }
    }

```

**Comment by CWolffIF** [comment]
Sorry but this doesn´t work. In the DetailView there is a SplitterItem and so model changed everytime you move the spiltter and on the next opening i got an error (see below).
I think this is same error like #652 cause there is also a splitter.

17.01.20 09:50:52.655	================================================================================
17.01.20 09:50:52.657	Trace Log for iXISXRM.Win.exe is started
17.01.20 09:50:52.658	================================================================================
iXISXRM.Win.exe Error: 0 : 17.01.20 09:52:58.225	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandDetailView, ID:AccountingVoucher_DetailView' view to XpandWinWindow:
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInInspector(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInNewWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewFromCommonView(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   bei DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   bei DevExpress.ExpressApp.Win.WinWindow.ProcessActionCreatedView(ActionBaseEventArgs e)
   bei DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   bei DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   bei DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       NullReferenceException
			Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindToModel(IModelNodeDisabled modelNodeDisabled, Object instance) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 159.
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindTo(ValueTuple`3 data) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 125.
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.<>c.<BindLayoutGroupControl>b__5_3(ValueTuple`3 tuple) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 95.
   bei System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs:Zeile 38.

**Comment by apobekiaris** [comment]
#652 should be address in the latest lab release, did u try it?

**Comment by apobekiaris** [comment]
i still want to know if u are in the latest lab version, if not the https://github.com/eXpandFramework/eXpand/issues/640#issuecomment-567425195 code should stop binding if the model is null

**Comment by apobekiaris** [comment]
use that code before xafapplication instance is created

**Comment by CWolffIF** [comment]
I´m on Version 19.2.502.1, ModelMapper 2.192.4.5

#652 
The same error as before.

**Comment by apobekiaris** [comment]
what about the code from https://github.com/eXpandFramework/eXpand/issues/640#issuecomment-567425195 according to your stack trace that code is verified from the other users there that works

**Comment by CWolffIF** [comment]
I tried
`            Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.ControlBind.Subscribe(parameter =>
            {
                parameter.Handled = parameter.Model == null;
            });

            iXISXRMWindowsFormsApplication winApplication = new iXISXRMWindowsFormsApplication();`

This worked in #659, but not in #652.

**Comment by apobekiaris** [comment]
this should work

 install packages Xpand.Patcher, Xpand.Fasterflect and b4 xafapp creation 

```cs
var harmony = new Harmony(typeof(DoNotMapTests).Namespace);
            var bindToModelMethod = typeof(ModelBindingService).Method("BindToModel",Flags.StaticAnyVisibility);
            var methodInfo = typeof(ModelBindingServicePatch).Method("BindToModel",Flags.StaticAnyVisibility);
            harmony.Patch(bindToModelMethod, new HarmonyMethod(methodInfo));

    public static class ModelBindingServicePatch{
        public static bool BindToModel(IModelNodeDisabled modelNodeDisabled, object instance){
            return modelNodeDisabled != null;
        }

    }

```

**Comment by CWolffIF** [comment]
This worked in #659, but not in #652.

**Comment by apobekiaris** [comment]
Issue is prioritized as it contains one of the following labels ***sponsor***, **installation**, **contribution**, **nuget**, **breakingchange**, **ReproSample**, **Deployment**

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Binding thorws null reference when GroupNodes are removed #659](https://github.com/eXpandFramework/DevExpress.XAF/commit/0a4aeff51ba2caa507275f993905ae5341fab6f3)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the [Xpand.XAF.Modules](https://github.com/eXpandFramework/DevExpress.XAF) directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi Tolis,

I´m on 19.2.502.2 and Modelmapper 2.201.0.2 but it doesn´t work.

The error disapeared only opening the view with lost nodes.

Same error behaviour:
- On the first opening the Collapse of the LayoutGroup works. But with this action the DetailView is modified and Nodes are disabled
- On the second opening I got the error on collapsing or expanding the group


iXISXRM.Win.exe Error: 0 : 19.01.20 09:57:17.903	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei Xpand.ExpressApp.Win.SystemModule.LayoutControlGroupController.OnGroupExpandChanged(Object sender, LayoutGroupEventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\LayoutControlGroupModelAdapterController.cs:Zeile 23.
   bei DevExpress.XtraLayout.LayoutControl.DevExpress.XtraLayout.ILayoutControl.RaiseGroupExpandChanged(LayoutGroupEventArgs e)
   bei DevExpress.XtraLayout.LayoutGroup.set_Expanded(Boolean value)
   bei DevExpress.ExpressApp.Win.Layout.XafLayoutControlGroup.set_Expanded(Boolean value)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.DoInvertGroupExpanded(LayoutGroup group)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.ProcessGroupActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.PerformOwnersActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.BaseLayoutItemHandler.PerformControlActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutGroupHandler.PerformControlActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.PerformChildHandlerActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.PerformControlActions(EventType eventType, MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.OnMouseDown(MouseEventArgs e)
   bei DevExpress.XtraLayout.Handlers.LayoutControlHandler.OnMouseDown(Object sender, MouseEventArgs e)
   bei DevExpress.XtraLayout.LayoutControl.OnMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ContainerControl.WndProc(Message& m)
   bei DevExpress.XtraLayout.LayoutControl.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

**Comment by apobekiaris** [comment]
Please check your bin that the ModelMapper assembly there is 2.201.0.2 because the latest version of Xpand uses the 2.201.0.1 version and u need to explictlu install it until is updated.

```ps1
Get-XpandNugetPackageDependencies eXpandSystemWin -Source Xpand

Id                               Include Exclude VersionRange
--                               ------- ------- ------------
AutoMapper                       {}      {}      [3.3.1, )
eXpandLib                        {}      {}      [19.2.502.2, )
eXpandSystem                     {}      {}      [19.2.502.2, )
System.Resources.Extensions      {}      {}      [4.6.0, )
Xpand.XAF.Modules.GridListEditor {}      {}      [2.201.0.1, )
Xpand.XAF.Modules.ModelMapper    {}      {}      [2.201.0.1, )
```

attaching my sample that works fine following the steps you suggested.
[Solution91.zip](https://github.com/eXpandFramework/eXpand/files/4082759/Solution91.zip)

**Comment by apobekiaris** [comment]
in my sample u will find a Customer dderiving from Person where i modified the Layout add a spittler remove some nodes. This action resulted in the excception u mentioned at start which was fixed. Now I open the detailview contract the Person group close the app and restart. No exception

**Comment by CWolffIF** [comment]
You are right. I modified the solution91 with my test and no error #659 or #652 appears.

But in my real-solution the errors appear (#659 and #652) in categorized listview (which I use often) and in colapsible layoutgroup. Any ideas?
[Solution91new.zip](https://github.com/eXpandFramework/eXpand/files/4082869/Solution91new.zip)

**Comment by apobekiaris** [comment]
let's continue testing of #652 at the dedicated thread, I consider this one resolved, let me know if u still have problems.

**Comment by expand** [comment]
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
