### ISSUE TITLE
bump versions to x.201.xxx

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#660]
versions minor should reflect the current year/semester

**Comment by apobekiaris** [comment]
Issue is prioritized as it contains one of the following labels *sponsor*, installation, contribution, nuget, breakingchange, ReproSample, Deployment

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [bump versions to x.201.xxx #660](https://github.com/eXpandFramework/DevExpress.XAF/commit/24890720b4e28db0585d8778cd47a1b690db3e48)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
