### ISSUE TITLE
Is it possible to use model deference module with remote  idatastore via wcf.

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#665]
Is it possible to use model deference module with remote  idatastore via wcf. I have setup a new solution and it works fine but does not allow opening models

**Comment by apobekiaris** [comment]
details please

**Comment by melihyilman** [comment]
i guess @sam105kelly  wants to use WCF. Security system throws some exceptions if roles aren't specified.
You should grant anonymous acess for model.  https://www.devexpress.com/Support/Center/Question/Details/T847685/how-can-use-modeldifferencedbstore-in-wcf

Func<IDataServerSecurity> dataServerSecurityProvider = () =>
{
    SecurityStrategyComplex security = new SecurityStrategyComplex(typeof(PermissionPolicyUser), typeof(PermissionPolicyRole), new AuthenticationStandard());
    security.SupportNavigationPermissionsForTypes = false;
    security.RegisterXPOAdapterProviders();
    security.AnonymousAllowedTypes.Add(typeof(ModelDifference));
    security.AnonymousAllowedTypes.Add(typeof(ModelDifferenceAspect));
    return security;
};

**Comment by sam105kelly** [comment]
Thanks very Much
