### ISSUE TITLE
References loaded twice when opening model editor or updating model

### ISSUE THREAD

**Issue by Kelbethor** [eXpandFramework/eXpand#666]
Hi, I'm adding XAF modules (lab nuget) to an existing dx windows application (19.2.5), first I add all agnostic (xpand & xaf) references to agnostic module and win (xpand & xaf) references to winmodule and winapplication. Change my winApplication class to inherit from Xpand.ExpressApp.Win.XpandWinApplication, everything builds fine, add modules using the designers in agnostic and winmodule modules. Again compile.
then I update models, agnostic is fine, winmodule is fine but winapplication model update fails. Opening application designer or model editor fails too.

Updater fails with: An item with the 'ModelProgressBarViewItem' key has already been added ('Xpand.XAF.Modules.ProgressBarViewItem.IModelProgressBarViewItem', 'Xpand.XAF.Modules.ProgressBarViewItem.IModelProgressBarViewItem')

Application designer: System.ComponentModel.Design.Serialization.CodeDomSerializerException: 'Xpand.XAF.Modules.Reactive.Logger.ReactiveLoggerModule' type not found.

Sorry I supose this has been asked a million times.

What am I missing?

**Comment by apobekiaris** [comment]
Hi,

I am not sure what u doing without a sample however from your post, I want to mention that there is no need to explicitly add Xpand.XAF.Modules since u use the Xpand.ExpressApp, though I doupt this the problem.  You can also try the XpandModelEditor instead maybe the behaviour differs. In any case you can probaably create a sample easy. just remove all code from your app and leave only the module installation.

**Comment by apobekiaris** [comment]
a few ore thoughts:
1. You need to have XPand.VSIX package when working with Xpand.ExpressApp modules that depend on Xpand.XAF.Modules.ModelMapper (most packages have it as dependency)
2. .NET will load doubles if the version is different or if it locates them in different places
3. Try to clean assemblies listed at VSPATH\CommonExtensions\DataDesign\ModelMapperFiles.txt. This work should be done from XPand.VSIX on each build and most probably related to this case

**Comment by Kelbethor** [comment]
That was why! I had installed xpand on the system and using nuget references at the same time. Uninstall-Xpand and cleaned did it.
