### ISSUE TITLE
Xpand VSIX empty Model List

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#676]
attached screencast, which info/log do you need to for debug?
[modellistempty.zip](https://github.com/eXpandFramework/eXpand/files/4209830/modellistempty.zip)
espected.

**Comment by apobekiaris** [comment]
is tthat a sample u can share?

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by vimarx** [comment]
it happens with every solution in my dev pc

**Comment by apobekiaris** [comment]
I guess u used the latest build? if yes the #636  may affect u. Can you try the VSIX from the previous than 19.2.601.2

**Comment by apobekiaris** [comment]
only the VSIX

**Comment by vimarx** [comment]
reinstalled previous version and problem continues (xaf model list is not painted...)

![image](https://user-images.githubusercontent.com/226800/74606792-01a1c080-50b2-11ea-8004-3d1ef501cde1.png)

**Comment by apobekiaris** [comment]
the transparency thing is VS problem u can configure it to avoid it google for it. e.g. https://developercommunity.visualstudio.com/content/problem/638322/vs-2019-regression-transparent-toolwindowpane-with.html

**Comment by vimarx** [comment]
Solved! thanks!

**Comment by apobekiaris** [comment]
is it solved? i am confused? u fallback to previous and worked but does it work with the latest?

**Comment by vimarx** [comment]
solved , it was a VS issue, not Xpand's.
I applied the solution you suggested in https://developercommunity.visualstudio.com/content/problem/638322/vs-2019-regression-transparent-toolwindowpane-with.html

**Comment by vimarx** [comment]
it also work ok in 19.2.601.2
