### ISSUE TITLE
Can't get eXpand emails working

### ISSUE THREAD

**Issue by scrawny-5** [eXpandFramework/eXpand#679]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
Just as a follow-on from #677, I decided to bite the bullet and upgrade the project's DX framework to 19.2.6 to coincide with the Nuget package. After installing the package (as admin and signing the PS1 files), it appeared to also need a project upgrade to .Net framework 4.7.2 otherwise the compiler was complaining about having to remap assemblies in the app.config file (which I didn't want to do). Eventually, I was able to compile the Module project and the eXpand Email module appeared in the model as expected. I couldn't compile the web project initially as it was missing references to 0Harmony.dll (similar to #575) and a more recent version of System.ValueTuple.

Anyway, I was able to configure the emailer via the Model as per the wiki and initially I just created a basic rule to email when a certain business object was created. No matter how I approached it (reconfiguring the rule, templates, various context groups), there was still no email in my inbox. I checked the firewall for the SMTP logs but there is nothing. I also checked the usual XAF logs but there is no mention of xpand or an email. Does the eXpandEmail module write to a log? Are there any other ways I can troubleshoot where this is failing? The EmailOperationPermissionPolicyData table is empty at the moment. Does this require an entry or does it allow-all when there are no specific permissions?

**Comment by apobekiaris** [comment]
the module is super simple it just integrates the Logic module (Ruling engine)
http://apobekiaris.blogspot.com/search/label/Logic

so it has only one controller where u can easily disable override the FrameAssigned copy the source code into your project and find exactly how it works and do your custom logging if u need to.

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/eXpand/blob/master/Xpand/Xpand.ExpressApp.Modules/Email/Logic/EmailRuleViewController.cs

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
