### ISSUE TITLE
Please publish the step-by-step instructions for updating the solution to the new version of eXpand Framework

### ISSUE THREAD

**Issue by laceratione** [eXpandFramework/eXpand#686]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
We are currently having difficulty updating to new versions of eXpand Framework. The update is performed in the following sequence:

1. Uninstall DevExpress old version
2. Install the new version of DevExpress 19.2.6
3. Launch in Visual Studio 'Extention -> DevExpress -> ProjectConverter -> ProjectConvert v19.2...'
4. We execute the Expand Framework install script
`_Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source') #-Version '19.2.602.0' -SkipGac -InstallationPath 'c:\solution'"`
5. In PowerShell we install
`Install-Module XpandPwsh`
6. In PowerShell we execute Cmdlet
`Start-XpandProjectConverter -version '19.2.602.0' -Path 'C:\Solution' -ProjectType 'csproj' -SkipInstall`

**Comment by apobekiaris** [comment]
the installer needs nothing extra it will uninstall the current version if found first and will continue. I do not get where is the problem

the extra step of `Start-XpandProjectConverter` is optional in case u face problems. However I would recommend switching to Nugets are the dotnet core times are here and they do not support the GAC

the XpandPwsh is only requeired if u want to use the Start-XpandProjectConverter

**Comment by laceratione** [comment]
I asked that because I thought that I did something wrong and this is why i get [this problem ](https://github.com/eXpandFramework/eXpand/issues/684).

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
