### ISSUE TITLE
Validation error: Combination of the following properties must be unique: Persistent Application, Difference Type, Combine Order. 

### ISSUE THREAD

**Issue by nwpratt** [eXpandFramework/eXpand#687]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Website is creating two records in the ModelDifferenceObject with the same values for the properties listed in the validation error message. Should the validation include the Device Category?
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. Expand zip file
2. Click on the "Application Settings" navigation item.
3. Expand the Difference Type: User rows
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
The validation message should not be shown.
𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
none

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

04. Installation

For all other issues the posting time is respected.
[expandModelDifTest.zip](https://github.com/eXpandFramework/eXpand/files/4313829/expandModelDifTest.zip)

**Comment by apobekiaris** [comment]
If I understand u correctly u want to add an additional check against the Device?

**Comment by nwpratt** [comment]
I don’t know if the validation error is correct. Did I forget to add something when I setup the project?

Thank you,
Niel

**Comment by apobekiaris** [comment]
the validation is correct its a xaf validation rule which i may remove from the model but some feature that depends on it will missbehave. However u can simply assign a differnt combine order for each of your models and the validation will pass

**Comment by vimarx** [comment]
is it necessary to Initialize  sequence generator for proper auto-numbering of combine order?

**Comment by nwpratt** [comment]
I will add the additional field for the validation.
I have been reading your blog http://apobekiaris.blogspot.com/search/label/ModelDifference to work with the module.
Where should I go to get the newest information?

Thank you!!
Niel

**Comment by apobekiaris** [comment]
@vimarx  actually we had this feature in the past however due to bad performance it was removed. But   sure it can be used if performance is not an issue.

**Comment by apobekiaris** [comment]
@nwpratt the module is really old same the blog post u read unfortunately these are no docs at the moment.

**Comment by nwpratt** [comment]
I just wanted to make sure I was looking that the correct link. Thanks

**Comment by apobekiaris** [comment]
all related blog posts are labeled 

http://apobekiaris.blogspot.com/search/label/ModelDifference

**Comment by nwpratt** [comment]
Here is the commit link where the SequenceGenerator was removed.
https://github.com/eXpandFramework/eXpand.lab/commit/82c34e6a098f465a146e0948375386276c10b79d

In the example file it looks like the Combine Order field is not updating.

**Comment by apobekiaris** [comment]
I do not understand what example is this? furthermore I do not see the point of discussing it further. Don't u think is a bad idea to add such a heavy and with so many constrains dependency (seqgenerator) just for the same of combining models? most of the users never combine the models. So if you do not want to combine the models u safe to loosen the validation

**Comment by apobekiaris** [comment]
also maybe u can succefully apply the positioncolumn implementation to this case

https://github.com/eXpandFramework/eXpand/blob/01a65994c310251669d463246e4d4388b76d781d/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/SystemModule/PositionInListViewController.cs#L18-L25

**Comment by nwpratt** [comment]
Thank you
