### ISSUE TITLE
ModelDifference detailview gets modified on load

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#690]
opening the detailview the objectspace gets modified due to lazy model intialization

**Comment by expand** [comment]
eXpand.lab release [19.2.602.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.602.4) includes commit that relate to this task:

* [ModelDifference detailview gets modified on load #690](https://github.com/eXpandFramework/eXpand.lab/commit/50420eed327f4388b993f1f19a65ae261da240e7)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
