### ISSUE TITLE
The ModelDifference Ribbon is missing actions

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#691]
this only happens if the Mdi tabbed and the last open view is the MDO_DetailView. It can be treated with the Model_DetailView Serializable attribute

**Comment by expand** [comment]
eXpand.lab release [19.2.602.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.602.4) includes commit that relate to this task:

* [The ModelDifference Ribbon is missing actions #691](https://github.com/eXpandFramework/eXpand.lab/commit/ba3d8e43a166ee0d7a2df3d3296b3583302614cf)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
