### ISSUE TITLE
can't open web model in win app in 19.2.602.5 and in 19.2.701.1

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#692]
Do I HAVE to override that METHOD?

9.03.20 14:31:07.929	no context	Customize TypesInfo
29.03.20 14:31:07.993	no context	FirstChanceException event raised in VxERP.Win.exe: The ModelEditor requires a valid ModelAssembly. Override the VxERPAspNetApplication GetModelAssemblyFilePath to provide a valid filename e.g.
//Win
Path.Combine(Path.GetTempPath(),$"{GetType().Name}{ModelAssemblyFileName}")

//Web
GetType().GetField("sharedModelManager", BindingFlags.NonPublic|BindingFlags.FlattenHierarchy|BindingFlags.Static)?.GetValue(this) == null
                ? Path.Combine(Path.GetTempPath(), $"{GetType().Name}{ModelAssemblyFileName}") : null                    
    en Xpand.Persistent.Base.ModelDifference.ModelBuilder.BuildModel(XafApplication application, String configFileName, XpandApplicationModulesManager applicationModulesManager)
29.03.20 14:31:07.994	no context	FirstChanceException event raised in VxERP.Win.exe: Se han producido uno o varios errores.    en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
29.03.20 14:31:07.994	no context	FirstChanceException event raised in VxERP.Win.exe: Se han producido uno o varios errores.    en DevExpress.ExpressApp.Actions.ActionBase.OnHandleException(Exception e)
VxERP.Win.exe Error: 0 : 29.03.20 14:31:08.006	no context	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Se han producido uno o varios errores.
	Data:       0 entries
	Stack trace:

   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Utils.Helpers.Retry.Do(Action action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(Boolean tryToUseCurrentTypesInfo, Action`1 action)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModelCore(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModel(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.OnCurrentObjectChanged()
   en DevExpress.ExpressApp.Editors.ViewItem.set_CurrentObject(Object value)
   en DevExpress.ExpressApp.ObjectView.InitializeItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.AddItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.LoadModelCore()
   en DevExpress.ExpressApp.View.LoadModel()
   en DevExpress.ExpressApp.View.SetModel(IModelView model)
   en Xpand.ExpressApp.ViewFactory.CreateDetailView(XafApplication xafApplication, String viewId, IObjectSpace objectSpace, Object obj, Boolean isRoot, Boolean enableDelayedObjectLoading)
   en Xpand.ExpressApp.SystemModule.XpandSystemModule.ApplicationOnDetailViewCreating(Object sender, DetailViewCreatingEventArgs args)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       FileNotFoundException
			Message:    The ModelEditor requires a valid ModelAssembly. Override the VxERPAspNetApplication GetModelAssemblyFilePath to provide a valid filename e.g.
//Win
Path.Combine(Path.GetTempPath(),$"{GetType().Name}{ModelAssemblyFileName}")

//Web
GetType().GetField("sharedModelManager", BindingFlags.NonPublic|BindingFlags.FlattenHierarchy|BindingFlags.Static)?.GetValue(this) == null
                ? Path.Combine(Path.GetTempPath(), $"{GetType().Name}{ModelAssemblyFileName}") : null                    

			Data:       0 entries
			Stack trace:

   en Xpand.Persistent.Base.ModelDifference.ModelBuilder.BuildModel(XafApplication application, String configFileName, XpandApplicationModulesManager applicationModulesManager)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModelCore(Boolean rebuild)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(XafApplication xafApplication, Action`1 action)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.<>c__DisplayClass12_0.<

**Comment by apobekiaris** [comment]
what is not clear in this message?

>The ModelEditor requires a valid ModelAssembly. Override the VxERPAspNetApplication GetModelAssemblyFilePath to provide a valid filename e.g.
>//Win
Path.Combine(Path.GetTempPath(),$"{GetType().Name}{ModelAssemblyFileName}")

>//Web
GetType().GetField("sharedModelManager", BindingFlags.NonPublic|BindingFlags.FlattenHierarchy|BindingFlags.Static)?.GetValue(this) == null
? Path.Combine(Path.GetTempPath(), $"{GetType().Name}{ModelAssemblyFileName}") : null

please do not post so long stacks it makes the thread hard to read, edit your post and trim the junk

**Comment by vimarx** [comment]
my doubt is if it is mandatory because then it would be a breaking change?

**Comment by apobekiaris** [comment]
yes it is mandatory your previous workaround although it may looked it worked it still let XAF to produce assemblies. Is there a problem about this solution?

**Comment by vimarx** [comment]
no, it's fine, I will try it.

**Comment by vimarx** [comment]
Could anyone make it work on production web sites?
I have trouble generating web model assembly ....

**Comment by apobekiaris** [comment]
what kind of problem? and why u need to generate the assembly in the production web site ? the assembly is needed from the win modeleditor when only u want to open a web assembly

**Comment by vimarx** [comment]
sorry, I couldn't get generated the web model assembly in my win app (please discard what I said about web site).
It is a release compiled. 
The temp path has only the win assembly model, but no web model.
I don't know how to force web assembly model dll generation

**Comment by emeyke** [comment]
You would have to run the web app, as far as I understand, to have web model assembly generated.

**Comment by vimarx** [comment]
and copy it to the win path?? mmm
BTW, in my web site, no Modelassembly is generated,

**Comment by vimarx** [comment]
> You would have to run the web app, as far as I understand, to have web model assembly generated.

do you successfully opened it in that way?

**Comment by emeyke** [comment]
For now i have opened it from the win app running on the same machine as the web app since both model assembly paths are the same.

**Comment by vimarx** [comment]
but if you can't get or copy it, you can't use win app as a standalone solution? (as before)

**Comment by emeyke** [comment]
I am just getting to distribution bit and plan to have the web model assembly generated in the pipeline during easy test and include it with the installer..

**Comment by vimarx** [comment]
Now I remember!, if I use a temp path for web model assembly, it works, but only the first time, if you log off or open it again, it fails with an  access
-denied exception because it tries to regenerate the assemblies

**Comment by vimarx** [comment]
I don't know why the web tries to regenerate the model  assembly

**Comment by apobekiaris** [comment]
@vimarx do u use the recommended snippet for web or your own?

**Comment by vimarx** [comment]
Hi, I had to modify it because, in my understanding, I need the generated model assembly for the win app in order to modify its model.
Also, I had to check if the modelassembly file exists (if yes, then return nothing), because in my implementation, it tries to generate it several times, failing after the first successfully generation with access-denied file exception

**Comment by apobekiaris** [comment]
here how it is designed to work 

1. u run the web app with the exact recommend snippet and the web assembly is generated in temp. The snippet has logic not to regenerate twice for the same app instance but to regenerate on next app start. Below is the snippet expanded and commented to explain my words
```
        protected override string GetModelAssemblyFilePath(){
            //check if sharedModelManager fields has value which means that the app has started so return null if this happened
            if (GetType().GetField("sharedModelManager", BindingFlags.NonPublic | BindingFlags.FlattenHierarchy | BindingFlags.Static)?.GetValue(this) == null)
                return Path.Combine(Path.GetTempPath(), $"{GetType().Name}{ModelAssemblyFileName}");
            else
                return null;
        }
```
2. you copy the web bin file into the win files location

Does this fail?
