### ISSUE TITLE
Ambiguous match on logon view with language

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#693]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
I have it in the past you fixed it, but now is back.
I got before logon view opens an "ambiguous match found issue"

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
It happens again by reactive select onNext by XAFLayoutControl

![image](https://user-images.githubusercontent.com/43534405/78668183-83f07900-78da-11ea-97ed-1c07ded9989b.png)

[StackTrace.txt](https://github.com/eXpandFramework/eXpand/files/4444123/StackTrace.txt)

![image](https://user-images.githubusercontent.com/43534405/78668367-d893f400-78da-11ea-8151-cdc460b83efd.png)

**Comment by apobekiaris** [comment]
how u can tell it is about the XafLayoutControl? at least the info u posted does not verify it? Also is not clear at all how to repro it, furthermore details like which was the previous working version can help a lot

**Comment by apobekiaris** [comment]
and the past ticket

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
