### ISSUE TITLE
NullReference in ModelDifference

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#694]
Hi Tolis

I'm getting the following nullreference exception after (re)opening a object of a specific type.

De objectverwijzing is niet op een exemplaar van een object ingesteld.

   bij Xpand.ExpressApp.ModelDifference.Win.Controllers.ModelEditorTemplateViewController.<OnFrameAssigned>b__7_1(Object sender, DetailViewCreatingEventArgs args)
   bij System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bij DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   bij DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   bij DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, Object obj, View sourceView)
   bij DevExpress.ExpressApp.SystemModule.NewObjectViewController.CreateNewObject(Type newObjectType, IObjectSpace objectSpaceForNewObject, SingleChoiceActionExecuteEventArgs args)
   bij DevExpress.ExpressApp.Win.SystemModule.WinNewObjectViewController.New(SingleChoiceActionExecuteEventArgs args)
   bij DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

We are using version 19.2.602 of Xpand.

Thanks,
Jacob

**Comment by apobekiaris** [comment]
should be fixed in 19.2.603, try to upgrade please

ModelEditorTemplateViewController #683

**Comment by apobekiaris** [comment]
please also note that there are works on this area until two weeks ago 

https://github.com/eXpandFramework/eXpand.lab/commits/93ef1591b82b5a1caab58d87d3c4e7c3c5b832e0/Xpand/Xpand.ExpressApp.Modules/ModelDifference.Win/Controllers/ModelEditorTemplateViewController.cs

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
