### ISSUE TITLE
New SequenceGenerator standalone package

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#696]
This one of the most common needs in a XAF solution and although eXpandFramework has a build-in implementation it is not tested nor documented and has many unrelated dependencies.

A new [standalone package](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules) that can work with all XAF versions, has a UI and  is tested on each build and documented is required.

**Credits:** To the company that already [sponsored](https://github.com/sponsors/apobekiaris) this module implementation

**Comment by apobekiaris** [comment]
When released the package will also distributed with the Xpand.SystemModule and the existing SequenceGenerator implementation that is not shared to all packages will be removed. The new package will not have support for released sequences.

**Comment by expand** [comment]
The pre-release [2.201.3.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.3.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: Tests #696](https://github.com/eXpandFramework/DevExpress.XAF/commit/9c9738337ea5abfde05d7ca2fa8426a9c71e4228)
* [SequenceGenetor: module release #696](https://github.com/eXpandFramework/DevExpress.XAF/commit/e73e82134fae1a7a312b0eb13b9bd002eeb2be08)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.201.14.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)

 1. [Xpand.Extensions.Reactive v.2.201.14.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)

 1. [Xpand.Extensions.XAF v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)

 1. [Xpand.Extensions.XAF.Xpo v.2.201.13.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)

 1. [Xpand.VersionConverter v.2.201.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.VersionConverter)

 1. [Xpand.XAF.Core.All v.2.201.27.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.ModelEditor v.1.201.5](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.XAF.ModelEditor)

 1. [Xpand.XAF.Modules.AutoCommit v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)

 1. [Xpand.XAF.Modules.CloneMemberValue v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)

 1. [Xpand.XAF.Modules.CloneModelView v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)

 1. [Xpand.XAF.Modules.GridListEditor v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)

 1. [Xpand.XAF.Modules.HideToolBar v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)

 1. [Xpand.XAF.Modules.LookupCascade v.2.201.4.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)

 1. [Xpand.XAF.Modules.MasterDetail v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)

 1. [Xpand.XAF.Modules.ModelMapper v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)

 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)

 1. [Xpand.XAF.Modules.OneView v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)

 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)

 1. [Xpand.XAF.Modules.Reactive v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)

 1. [Xpand.XAF.Modules.Reactive.Logger v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)

 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)

 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)

 1. [Xpand.XAF.Modules.Reactive.Win v.2.201.14.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)

 1. [Xpand.XAF.Modules.RefreshView v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)

 1. [Xpand.XAF.Modules.SequenceGenerator v.2.201.0](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)

 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)

 1. [Xpand.XAF.Modules.ViewEditMode v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)

 1. [Xpand.XAF.Web.All v.2.201.27.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Win.All v.2.201.27.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)


</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
![hfvTo7UsCI](https://user-images.githubusercontent.com/159464/80309035-f918e500-87da-11ea-8f52-7799457213cf.gif)

**Comment by expand** [comment]
The pre-release [2.201.3.2](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.3.2) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: documentation #696](https://github.com/eXpandFramework/DevExpress.XAF/commit/01a7c3d9969ce8e4b12bb7bcf68b95f5bb250fb7)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.XAF.Core.All v.2.201.27.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Modules.AutoCommit v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)

 1. [Xpand.XAF.Modules.CloneMemberValue v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)

 1. [Xpand.XAF.Modules.GridListEditor v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)

 1. [Xpand.XAF.Modules.HideToolBar v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)

 1. [Xpand.XAF.Modules.LookupCascade v.2.201.4.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)

 1. [Xpand.XAF.Modules.MasterDetail v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)

 1. [Xpand.XAF.Modules.ModelMapper v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)

 1. [Xpand.XAF.Modules.OneView v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)

 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)

 1. [Xpand.XAF.Modules.Reactive v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)

 1. [Xpand.XAF.Modules.Reactive.Logger v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)

 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)

 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)

 1. [Xpand.XAF.Modules.Reactive.Win v.2.201.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)

 1. [Xpand.XAF.Modules.RefreshView v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)

 1. [Xpand.XAF.Modules.SequenceGenerator v.2.201.0.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)

 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)

 1. [Xpand.XAF.Modules.ViewEditMode v.2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)

 1. [Xpand.XAF.Web.All v.2.201.27.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Win.All v.2.201.27.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)


</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.702.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.702.2) includes commit that relate to this task:

* [SequenceGenerator: Remove old implementation #696](https://github.com/eXpandFramework/eXpand.lab/commit/f870623ce3ca331fbaa7b2db22623dc168f5ec49)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.702.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.702.4) includes commit that relate to this task:

* [SequenceGenerator: register standalone package in System module #696](https://github.com/eXpandFramework/eXpand.lab/commit/07c02319e31759ce5e7b62a84842b79bfea900ac)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
