### ISSUE TITLE
NU1701: Package 'Xpand.Patcher 1.0.1' was restored using '.NETFramework,Version=v4.6.1...

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#697]
Hi,

I'm trying to use latest Xpand.Xaf.Core.All package (2.201.27, from nuget.org) in a project targeting netstandard2.0. Unfortunately package restore fails with NU1701: Package 'Xpand.Patcher 1.0.1' was restored using '.NETFramework,Version=v4.6.1...
This happens because Xpand.Extensions.XAF has a dependency on Xpand.Patcher and this package still targets net461. Any workarounds?

Thank you!

**Comment by apobekiaris** [comment]
Hi

Hmm but Xpand.Extensions.XAF is also depend on 461 so what you trying to do there?

**Comment by apobekiaris** [comment]
only Xpand.Extensions, Xpand.Extensions.Reactive, Xpand.Extensions.Mono.Cecil are netstandard2 assemblies so using the container package in a netstandard lib does not make much sense to me, you can same easy depend directly

**Comment by krombipils** [comment]
Oh, of course you are right...
I guess I was too optimistic about netstandard/net core support. Sorry for bothering you

**Comment by apobekiaris** [comment]
yeah there is no support yet
