### ISSUE TITLE
XPO Change Type

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#698]
Hi

I am facing new issue in XPO. I want change objectType, any xpand xpo extension to help me out.

Example:
Class User{
UserName
Mobile
}
Class Employee:User
{
EMPNo
}

User : Albert,997282883
Employee : Dennis, 7839293902, EMP001

I want to Change Object Type of User to Employee. In DB base class maintain ObjectType. if I change ObjectType No then Its work but how do i change by XPO code.

Thanks

**Comment by apobekiaris** [comment]
Hi,

this case is document in XAF docs

```
public class Updater : ModuleUpdater {
    // ...
    public override void UpdateDatabaseBeforeUpdateSchema() {
        base.UpdateDatabaseBeforeUpdateSchema();
        if (CurrentDBVersion < new Version("1.1.0.0") 
            && CurrentDBVersion > new Version("0.0.0.0")) {
            RenameTable("Department", "Division");
            UpdateXPObjectType(
                "MySolution.Module.Department", "MySolution.Module.Division", "MySolution.Module");
        }
    }
    // ...
```

https://docs.devexpress.com/eXpressAppFramework/113254/task-based-help/business-model-design/express-persistent-objects-xpo/how-to-handle-renamings-and-deletions-of-business-classes-and-their-properties#renameclass

**Comment by cevious** [comment]
Thank for quick response

I want to convert some transaction from User to Employee.


Thanks & Regards

Hemant
Sent from my iPhone

On 01-May-2020, at 12:47 PM, Apostolis Bekiaris <notifications@github.com> wrote:

﻿

Hi,

this case is document in XAF docs

public class Updater : ModuleUpdater {
    // ...
    public override void UpdateDatabaseBeforeUpdateSchema() {
        base.UpdateDatabaseBeforeUpdateSchema();
        if (CurrentDBVersion < new Version("1.1.0.0")
            && CurrentDBVersion > new Version("0.0.0.0")) {
            RenameTable("Department", "Division");
            UpdateXPObjectType(
                "MySolution.Module.Department", "MySolution.Module.Division", "MySolution.Module");
        }
    }
    // ...


https://docs.devexpress.com/eXpressAppFramework/113254/task-based-help/business-model-design/express-persistent-objects-xpo/how-to-handle-renamings-and-deletions-of-business-classes-and-their-properties#renameclass<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.devexpress.com%2FeXpressAppFramework%2F113254%2Ftask-based-help%2Fbusiness-model-design%2Fexpress-persistent-objects-xpo%2Fhow-to-handle-renamings-and-deletions-of-business-classes-and-their-properties%23renameclass&data=02%7C01%7C%7C58d215f459354ea9464b08d7ed9fb8b3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637239142556608545&sdata=wHH4S1fz81K%2BLdWXf5Qa4Hn0TIfOaRZxxO3GP99vO2c%3D&reserved=0>

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
