### ISSUE TITLE
Cannot open model editor in win app (using 20.1.301.0)

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#699]
Log follows (attached simple repro case)

01.05.20 23:44:01.466	Customize TypesInfo
Exception thrown: 'System.MissingFieldException' in Fasterflect.dll
Exception thrown: 'System.AggregateException' in Xpand.Utils.dll
Exception thrown: 'DevExpress.ExpressApp.Actions.ActionExecutionException' in DevExpress.ExpressApp.v20.1.dll
Solution14.Win.exe Error: 0 : 01.05.20 23:44:01.520	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Se han producido uno o varios errores.
	Data:       0 entries
	Stack trace:

   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Utils.Helpers.Retry.Do(Action action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(Boolean tryToUseCurrentTypesInfo, Action`1 action)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModelCore(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModel(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.OnCurrentObjectChanged()
   en DevExpress.ExpressApp.Editors.ViewItem.set_CurrentObject(Object value)
   en DevExpress.ExpressApp.ObjectView.InitializeItem(ViewItem item)
   en DevExpress.ExpressApp.DetailView.InitializeItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.AddItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.AddItem(IModelViewItem info)
   en DevExpress.ExpressApp.CompositeView.LoadModelCore()
   en DevExpress.ExpressApp.ObjectView.LoadModelCore()
   en DevExpress.ExpressApp.View.LoadModel()
   en DevExpress.ExpressApp.View.SetModel(IModelView model)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.SimpleActionExecuteEventHandler.Invoke(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			**Type:       MissingFieldException
			Message:    No match for field with name fileModelAssembly and flags Instance | NonPublic | Public | Static on type DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.
			Data:       0 entries
			Stack trace:
[Solution14.zip](https://github.com/eXpandFramework/eXpand/files/4566971/Solution14.zip)
**

   en Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo)
   en Fasterflect.Emitter.MemberSetEmitter.CreateDelegate()
   en Fasterflect.Emitter.BaseEmitter.GetDelegate()
   en Fasterflect.FieldExtensions.DelegateForSetFieldValue(Type type, String name, Flags bindingFlags)
   en Fasterflect.FieldExtensions.DelegateForSetFieldValue(Type type, String name)
   en Fasterflect.FieldExtensions.SetFieldValue(Object obj, String name, Object value)
   en Xpand.Persistent.Base.ModelDifference.ModelBuilder.BuildModel(XafApplication application, String configFileName, XpandApplicationModulesManager applicationModulesManager)
   en Xpand.Persistent.Base.ModelDifference.ModelBuilder.Build(Boolean rebuild)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModelCore(Boolean rebuild)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(XafApplication xafApplication, Action`1 action)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.<>c__DisplayClass12_0.<GetMasterModel>b__0()
   en Xpand.Utils.Helpers.Retry.<>c__DisplayClass0_0.<Do>b__0()
   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
			InnerException is null

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by expand** [comment]
eXpand.lab release [20.1.300.0](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.300.0) includes commit that relate to this task:

* [ModelDifference: 20.1 breaking change #699](https://github.com/eXpandFramework/eXpand.lab/commit/889e03b6c86f157aa9b6498cb36f9a8c9fb94561)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
Solved!! Thanks
