### ISSUE TITLE
Exception while opening app with a role model AND additiona models file (in 20.1.30x)

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#700]
If I create a role model (as shown below) and a additional model exist in project, and exception occurs at startup (attached project)

05.05.20 12:13:16.267	Resolve the 'Microsoft.Data.SqlClient' assembly
05.05.20 12:13:16.304	Resolve the 'System.Data.SqlClient' assembly
05.05.20 12:13:16.337	--------------------------------------------------------------------------------
							Logon successful

05.05.20 12:13:16.386	--------------------------------------------------------------------------------
							ModelDifference -- Adding Layers to application model 

05.05.20 12:13:16.397	--------------------------------------------------------------------------------
							ModelDifference -- Loaded: False

05.05.20 12:13:16.403	--------------------------------------------------------------------------------
							ModelDifference -- CreateResourceModels

05.05.20 12:13:16.415	--------------------------------------------------------------------------------
							ModelDifference -- Layers added to application model

05.05.20 12:13:16.422	--------------------------------------------------------------------------------
							ModelDifference -- Application model saved to the database

05.05.20 12:13:16.444	--------------------------------------------------------------------------------
							Logon failed

05.05.20 12:13:16.446	master.LastLayer
Nombre del parámetro: Solution15WindowsFormsModule,Solution15.Module.Win.MDO_stub.xafml
Solution15.Win.exe Error: 0 : 05.05.20 12:13:16.456	================================================================================
The error occurred:

	Type:       ArgumentException
	Message:    master.LastLayer
Nombre del parámetro: Solution15WindowsFormsModule,Solution15.Module.Win.MDO_stub.xafml
	Data:       0 entries
	Stack trace:

   en Xpand.ExpressApp.ModelDifference.DataStore.BaseObjects.ModelDifferenceObject.GetModel(ModelApplicationBase master)
   en Xpand.ExpressApp.ModelDifference.DictionaryStores.XpoUserModelDictionaryDifferenceStore.Load()
   en Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.LoadModels()
   en Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.OnUserDifferencesLoaded(Object sender, EventArgs eventArgs)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.ExpressApp.XafApplication.LoadUserDifferences()
   en DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   en DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
	InnerException is null

![2020-05-05_12-11-18](https://user-images.githubusercontent.com/226800/81083938-96ef6c80-8ecb-11ea-8881-5fb90a8ba1fc.gif)

![image](https://user-images.githubusercontent.com/226800/81084193-efbf0500-8ecb-11ea-809e-15527f30f43d.png)
[Solution15.zip](https://github.com/eXpandFramework/eXpand/files/4581807/Solution15.zip)

**Comment by vimarx** [comment]
Also noticed this in the startup log

							UpdateDB

05.05.20 12:13:15.890	Resolve the 'Microsoft.Data.SqlClient' assembly
05.05.20 12:13:15.914	Resolve the 'System.Data.SqlClient' assembly
05.05.20 12:13:15.993	Resolve the 'Microsoft.Data.SqlClient' assembly
05.05.20 12:13:16.021	Resolve the 'System.Data.SqlClient' assembly
05.05.20 12:13:16.051		ConnectionString: Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\mssqllocaldb;Initial Catalog=Solution15;XpoDataStorePool=True;
05.05.20 12:13:16.052	ExecuteNonQueryCommand: 'drop index iCombineOrder_ModelDifferenceObject on ModelDifferenceObject', silent=True
Solution15.Win.exe Error: 0 : 05.05.20 12:13:16.087	================================================================================
The error occurred:

	Type:       SqlException
	Message:    Cannot drop the index 'ModelDifferenceObject.iCombineOrder_ModelDifferenceObject', because it does not exist or you do not have permission.
	Data:       6 entries
			'HelpLink.ProdName'		'Microsoft SQL Server'
			'HelpLink.ProdVer'		'13.00.4259'
			'HelpLink.EvtSrc'		'MSSQLServer'
			'HelpLink.EvtID'		'3701'
			'HelpLink.BaseHelpUrl'		'http://go.microsoft.com/fwlink'
			'HelpLink.LinkId'		'20476'
	Stack trace:

   en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   en DevExpress.ExpressApp.Updating.ModuleUpdater.ExecuteNonQueryCommand(String commandText, Boolean silent)
	InnerException is null

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by vimarx** [comment]
Any idea of why is happening this?  it happens with copies of existing and previously working customers production databases

**Comment by apobekiaris** [comment]
no idea have to research it it onmy todo possibly today

**Comment by apobekiaris** [comment]
the Xpand.XAF.Modules.Reactive module when app starts merges all embedded models found and this operation did not account the ModelDifference specialties. So  corrected the issue by providing a config regex: The next snippet describes what I just said in case you need it 

```cs 
        private static IObservable<Unit> MergedExtraEmbededModels(this ApplicationModulesManager manager) =>
            manager.WhereApplication().ToObservable()
                .SelectMany(application => application.WhenCreateCustomUserModelDifferenceStore()
                    .Do(_ => {
                        var models = _.application.Modules.SelectMany(m => m.EmbeddedModels().Select(tuple => (id: $"{m.Name},{tuple.id}", tuple.model)))
                            .Where(_ => {
                                var pattern = ConfigurationManager.AppSettings["EmbeddedModels"]??@"(\.MDO)|(\.RDO)";
                                return !Regex.IsMatch(_.id, pattern, RegexOptions.Singleline);
                            })
                            .ToArray();
                        foreach (var model in models){
                            _.e.AddExtraDiffStore(model.id, new StringModelStore(model.model));
                        }

                        if (models.Any()){
                            _.e.AddExtraDiffStore("After Setup", new ModelStoreBase.EmptyModelStore());
                        }
                    })).ToUnit();
```

updating to the next minor should fix this problem

**Comment by expand** [comment]
The pre-release [2.201.5.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.5.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Reactive: Embedded Model mergings fails with modeldifference #700](https://github.com/eXpandFramework/DevExpress.XAF/commit/2379d87b2246dc37557839158361d499e6870ae5)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)

 1. [Xpand.Extensions.Mono.Cecil v.2.201.28.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)

 1. [Xpand.Extensions.Office.Cloud v.2.201.28](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)

 1. [Xpand.Extensions.Office.Cloud.Microsoft v.2.201.28](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Microsoft)

 1. [Xpand.Extensions.Reactive v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)

 1. [Xpand.Extensions.XAF v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)

 1. [Xpand.Extensions.XAF.Xpo v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)

 1. [Xpand.XAF.Core.All v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Modules.AutoCommit v.2.201.29.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)

 1. [Xpand.XAF.Modules.CloneMemberValue v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)

 1. [Xpand.XAF.Modules.CloneModelView v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)

 1. [Xpand.XAF.Modules.GridListEditor v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)

 1. [Xpand.XAF.Modules.HideToolBar v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)

 1. [Xpand.XAF.Modules.LookupCascade v.2.201.31.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)

 1. [Xpand.XAF.Modules.MasterDetail v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)

 1. [Xpand.XAF.Modules.ModelMapper v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)

 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)

 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.201.0](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)

 1. [Xpand.XAF.Modules.OneView v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)

 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)

 1. [Xpand.XAF.Modules.Reactive v.2.201.29.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)

 1. [Xpand.XAF.Modules.Reactive.Logger v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)

 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)

 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)

 1. [Xpand.XAF.Modules.Reactive.Win v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)

 1. [Xpand.XAF.Modules.RefreshView v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)

 1. [Xpand.XAF.Modules.SequenceGenerator v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)

 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)

 1. [Xpand.XAF.Modules.ViewEditMode v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)

 1. [Xpand.XAF.Web.All v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Win.All v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)


</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [20.1.302.1](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.302.1) includes commit that relate to this task:

* [Bump Standalone packages #700](https://github.com/eXpandFramework/eXpand.lab/commit/ef5d7ce9d2c289335f270bbe22200810bdf665bc)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
solved
