### ISSUE TITLE
Office365 Todo integration

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#701]
The package will synchronize between `ITask` and Office365 Todo lists. More details in the package documentation once released.  This package will not be distributed with the main framework but only as standalone from the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository.

---
**Credits** to [Brokero](https://www.brokero.ch/de/startseite/) for [sponsoring](https://github.com/sponsors/apobekiaris) a larger cloud office implementation which helped to give birth to the `Xpand.XAF.Modules.Office.Microsoft.Todo` package.

**Comment by expand** [comment]
The pre-release [2.201.5.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.5.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Office.Microsoft.Todo: release + tests #701](https://github.com/eXpandFramework/DevExpress.XAF/commit/1614a7c8e496857ed2ef05652a9a023b079a8563)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)

 1. [Xpand.Extensions.Mono.Cecil v.2.201.28.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)

 1. [Xpand.Extensions.Office.Cloud v.2.201.28](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)

 1. [Xpand.Extensions.Office.Cloud.Microsoft v.2.201.28](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Microsoft)

 1. [Xpand.Extensions.Reactive v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)

 1. [Xpand.Extensions.XAF v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)

 1. [Xpand.Extensions.XAF.Xpo v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)

 1. [Xpand.XAF.Core.All v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Modules.AutoCommit v.2.201.29.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)

 1. [Xpand.XAF.Modules.CloneMemberValue v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)

 1. [Xpand.XAF.Modules.CloneModelView v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)

 1. [Xpand.XAF.Modules.GridListEditor v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)

 1. [Xpand.XAF.Modules.HideToolBar v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)

 1. [Xpand.XAF.Modules.LookupCascade v.2.201.31.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)

 1. [Xpand.XAF.Modules.MasterDetail v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)

 1. [Xpand.XAF.Modules.ModelMapper v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)

 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)

 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.201.0](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)

 1. [Xpand.XAF.Modules.OneView v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)

 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)

 1. [Xpand.XAF.Modules.Reactive v.2.201.29.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)

 1. [Xpand.XAF.Modules.Reactive.Logger v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)

 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)

 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)

 1. [Xpand.XAF.Modules.Reactive.Win v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)

 1. [Xpand.XAF.Modules.RefreshView v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)

 1. [Xpand.XAF.Modules.SequenceGenerator v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)

 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)

 1. [Xpand.XAF.Modules.ViewEditMode v.2.201.29.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)

 1. [Xpand.XAF.Web.All v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

 1. [Xpand.XAF.Win.All v.2.201.29.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)


</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The pre-release [2.201.10.6](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.10.6) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Replace Xpand.Extensions.Office.Cloud.Microsoft with Xpand.XAF.Modules.Office.CLoud.Microsoft #701](https://github.com/eXpandFramework/DevExpress.XAF/commit/f559d630af02cd7863ed3e2f5a83760caa3ed059)
* [Microsoft.Todo: Web intergration #701](https://github.com/eXpandFramework/DevExpress.XAF/commit/8881f27a63cc11e0487ad5c82f913fc6c132bddc)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.201.34.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Office.Cloud v.2.201.34.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.201.35.11](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.201.35.10](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.XAF.Core.All v.2.201.34.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.201.37.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.201.34](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.201.6.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.201.6.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.201.35.12](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.201.35.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.201.35.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.201.35.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.201.35.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.201.1.9](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Web.All v.2.201.34.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.201.34.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
![OTHr7A9GUm](https://user-images.githubusercontent.com/159464/87254701-0ade6000-c48d-11ea-9934-83003901feb2.gif)

**Comment by expand** [comment]
The pre-release [2.201.12.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.12.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Office.Cloud.Microsoft.Todo: documentation #701](https://github.com/eXpandFramework/DevExpress.XAF/commit/fce02a4954d684a70ef90d5a21fc9a8a9fba8792)
* [Office.Cloud.Microsoft.Todo: EasyTest #701](https://github.com/eXpandFramework/DevExpress.XAF/commit/46e103e9794366c1f08f9b8e17eac91e7220df3b)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.39.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.35](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.39.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.36.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.36.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.42.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.41.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.10](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.11.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.11.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.40.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.40.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.6.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.0](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.36.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.36.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
