### ISSUE TITLE
Can't open XAF Application Designer because XpandModuleBase tries to access Visual Studio-Folder

### ISSUE THREAD

**Issue by impactjo** [eXpandFramework/eXpand#704]
After Upgrading an project to V20.3 I get the following error when try to open the XAF Application Designer:

!System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\netstandard.dll' is denied."

The reason for this is that XpandModuleBase tries in its static constructor to write the netstandard.dll to AppDomain.CurrentDomain.ApplicationPath(). In the context of the designer this is the VisualStudio-Folder and if you work with a non-admin user the access is denied and loading of the application designer fails.

If this module really has to do this in it's static constructor then at least it shouldn't do it if it's running within a Visual Studio designer.

Thanks.

**Comment by apobekiaris** [comment]
the assembly is required for generating the model, so you have four options  one is to start VS as admin , two is to copy the file there manually so it will be used, three is to give permissions to that folder, four is to use the Xpand.ModelEditor instead.

Also ME operations if ModelMapper is used require access to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\DataDesign\  and for this u have only two options, to start VS as admin or to give permissions to that folder

**Comment by expand** [comment]
eXpand.lab release [20.1.302.2](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.302.2) includes commit that relate to this task:

* [Improve .NetStandard design time failure message #704](https://github.com/eXpandFramework/eXpand.lab/commit/562e469eeb6c0f7654bd0100e83d1e19b8e141ac)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by impactjo** [comment]
Thanks for the information. I used ModelDifferenceModule which itself obviously also uses ModelMapper (among other dependencies). I was finally able to move the application to native ModelDifferenceDbStore which solved this and other issues for me.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
