### ISSUE TITLE
Can't open web model using win in 20.1.302.x

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#705]
while trying to open web model.. no exception is logged..

![2020-05-11_19-43-20](https://user-images.githubusercontent.com/226800/81686235-cd2e6e00-942e-11ea-9cde-84f0c70da0e4.png)

**Comment by vimarx** [comment]
listview async loading is disabled

**Comment by apobekiaris** [comment]
i do not make much sense out of your post, elab on repro steps or provide a sample

**Comment by expand** [comment]
eXpand.lab release [20.1.302.4](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.302.4) includes commit that relate to this task:

* [ModelDifference: Disable Async loading for all MDO detailviews #705](https://github.com/eXpandFramework/eXpand.lab/commit/bc71ab74a30d8be9e9a7e09618fb5dd056bb4d5a)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
although I couldn't repro it I noticed that if AsyncLoading is enabled for the view, it throws. However this is a special module that reconstructs the XafApplication on the background and such operations in addition to DelayView loading (see https://github.com/eXpandFramework/eXpand/issues/669#issuecomment-588580789) are not supported. So Now it is disabled by default and my sample works fine
[Solution2.zip](https://github.com/eXpandFramework/eXpand/files/4622610/Solution2.zip)

If this solution does not cover you and  you post more details  I will revisit for now I am unassigned.

**Comment by vimarx** [comment]
solved!
Thanks!
