### ISSUE TITLE
Xpand VSIX Error

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#706]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Xpand VSIX
Patching ME for version 20.1.3
System.NotImplementedException: Non implémenté (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at Xpand.VSIX.ModelEditor.GridHelper.<>c.<GetFileSystemWatchers>b__9_0(Project project) in D:\a\1\s\Xpand.Plugins\Xpand.VSIX\ModelEditor\GridHelper.cs:line 97
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xpand.VSIX.ModelEditor.GridHelper.GetFileSystemWatchers() in D:\a\1\s\Xpand.Plugins\Xpand.VSIX\ModelEditor\GridHelper.cs:line 96
   at Xpand.VSIX.ModelEditor.GridHelper.EventsSolutionEventsOnOpened() in D:\a\1\s\Xpand.Plugins\Xpand.VSIX\ModelEditor\GridHelper.cs:line 87
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. Pin the XAF Solution Model List in VS

𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
![image](https://user-images.githubusercontent.com/41955268/82053433-a5a10500-96bd-11ea-9756-10941571148b.png)

**Comment by isatahiri** [comment]
This might be related to the error received at startup of VS : 
![image](https://user-images.githubusercontent.com/41955268/82053611-ea2ca080-96bd-11ea-896b-63fac12b3a54.png)

**Comment by apobekiaris** [comment]
the message box just say u do not have installed the packages so they cannot be found from the Xpand New project wizard and if u want to use the wizard u should configure the registry key. The message box can be disabled from the Tools/Options/Xpand/General/Show Errors in MessageBox


I also used a pinned list which I control it with ctrl+shit+alt+m

>at EnvDTE.Project.get_FullName()

This says that the Project.FullName for at least one project in your solution something is very special and VS fails to get its fullname, My guess is that is a one time exception if it persists can u cloning your solution and open it while removing all projects until u find which one to blame?

From the screenshot I do not see an models listsed so u may also need to disable the Tools\Options\Enviroment\Optimize Rendering fro screens with different pixel densities

**Comment by isatahiri** [comment]
> From the screenshot I do not see an models listsed so u may also need to disable the Tools\Options\Enviroment\Optimize Rendering fro screens with different pixel densities

This seems to resolve the rendering issue.

**Comment by apobekiaris** [comment]
maybe an uloaded project can cause the other exception?

**Comment by isatahiri** [comment]
Maybe. I will check because i have unloaded projects too.

**Comment by CWolffIF** [comment]
Hi,

if you use VS 2019 you had to uncheck the rendering for pixel optimization in the options dialog and restart. If it is checked the window is empty. I had the same problem with the view in the tab.

![1](https://user-images.githubusercontent.com/43132306/82058074-8b1e5a00-96c4-11ea-9118-e2dcad357b09.PNG)

**Comment by isatahiri** [comment]
Hi,

yeah it seems that this solved my issue. I did not know about this... Discovering everyday...

Thanks for your help

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
