### ISSUE TITLE
NullReference IChooseFromListCollectionEditor

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#707]
Hi,

I got the error in 20.1.302.4.

![Unbenannt1](https://user-images.githubusercontent.com/43132306/82237696-587b9800-9936-11ea-9ecd-cff4f44fad35.PNG)

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
Hi

Until I provide a better fix use this call in the Setup method of your agnostic module

```cs
XafTypesInfo.Instance.LoadTypes(typeof(XpandModuleBase).Assembly)
```

**Comment by apobekiaris** [comment]
with the next minor u can remove this workaround, let me know how it works please.

**Comment by expand** [comment]
eXpand.lab release [20.1.302.7](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.302.7) includes commit that relate to this task:

* [Persistent.Base regular type not loaded #707](https://github.com/eXpandFramework/eXpand.lab/commit/86aa63e5032a08b89cc564a30f1d8ca6e649a3ce)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Thanx, it is solved.

**Comment by expand** [comment]
eXpand.lab release [20.1.303.1](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.303.1) includes commit that relate to this task:

* [Resolve assemblies from path when loading Persistent.Base regular types #707](https://github.com/eXpandFramework/eXpand.lab/commit/83d3eb4bf7fc95340cb91b29efee48a1129b65fb)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [20.1.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.400.0) includes commit that relate to this task:

* [Resolve assemblies from path when loading Persistent.Base regular types #707](https://github.com/eXpandFramework/eXpand.lab/commit/e21bfb9a77a87605e559813ee455a32d02dc9343)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.
