### ISSUE TITLE
Error on updating model for projects / exception thrown in ME

### ISSUE THREAD

**Issue by neuropseudolonicher** [eXpandFramework/eXpand#714]
The following exception is currently thrown when we perform "Update model on all projects" in Visual Studio:

Exception occurs while the 'Xpand.Persistent.Base.General.Controllers.CustomAttibutesController' customizes TypesInfo: Object reference not set to an instance of an object.
Update failed

A colleague of the mine faces the same error when trying to open the ME from within our application:

![image](https://user-images.githubusercontent.com/60786066/83740855-b529c300-a657-11ea-8da9-0ed3b57350d4.png)

Among other changes, we also migrated from eXpand / Devexpress v. 19.2.7 to the latest version of both frameworks.
Thus, it is unclear to us if the error is related to the migration of the framework or if it is caused by a modification we did in our implementation. If it is the latter, how can find out more information about the root cause of the problem?

Thank you in advance for your support!

**Comment by apobekiaris** [comment]
I am confused a related however design time problem was addressed at https://github.com/eXpandFramework/eXpand/issues/707 where i posted a temp workaround. But the user confirm that the next minor fixed the problem. You mentioned `Update Model on all project` which is a designtime command however your screenshot is from runtime.

**Comment by neuropseudolonicher** [comment]
Yes, we faced the problem in both of design and runtime.
It seems the workaround works for both of them.

Thanks for your help and immediate reply!

**Comment by apobekiaris** [comment]
the workaround is not a solution rather as it loads all types win,web resulting in problems later e.g. huge win installation. if u post a runtime sample happy to research it
