### ISSUE TITLE
Anonymous Login and Open a View from a Link

### ISSUE THREAD

**Issue by ThomasVetterling** [eXpandFramework/eXpand#716]
Hello dear eXpand-Team,

im using the 'Anonymous'-Logon Feature of expand in my Application.
That is working perfectly.

Now a customer wanted to send links to a detailview to a businessobject by mail
to a colleage like

"http://localhost:2064/Order_DetailView/321f6fe0-7716-4605-b95a-c3361331600d/?mode=View"

but that is not working as the application logged us into the security-system with 'Anonymous' automatically but the Anonymous-Role has not enough rigths to view the 'order'-business object.

One solution would be that the Anonymous-Role wouldbe given all read rights to all businessobjects, but than i wouldn't need an anonymous user.

Can someone give me ahint how to work with Anonymous Logon and userfriendly urls at the same time?

Yours Thomas

**Comment by apobekiaris** [comment]
Hi,

at the moment I do not have resources to research such integration, though the XAF SC guys may help u if u explain to them how the anonymous works and what u want to do

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
