### ISSUE TITLE
Error in ModelEditor when trying to add calculated field on chart view

### ISSUE THREAD

**Issue by neuropseudolonicher** [eXpandFramework/eXpand#717]
Trying to add a Calculated Field in ModelEditor results in an exception "ModelDevExpressXtraCharts_ChartCalculatedField can't convert to type
Devexpress.Charts.Native.IChartCalculatedField".

We have been in contact with DevExpress regarding this, they were able to reproduce and asked  us to get in contact with you.

For further details, please see 
https://supportcenter.devexpress.com/ticket/details/t896106/error-in-modeleditor-when-trying-to-add-calculated-field-on-chart-view

**Comment by apobekiaris** [comment]
thnks for reporting, according to this screenshot 

![image](https://user-images.githubusercontent.com/159464/84387468-b466d300-abfb-11ea-9e0c-ab2ac36310f9.png)

my understanding is that u tried to use the ModelMapper Chart mapping to add calculated fields. However although ModelMapper can map any type, some cases like this one, may need additional logic. I am going to add this suggestion to the future improvements list as the case does not justifies prioritization.

https://github.com/eXpandFramework/DevExpress.XAF/blob/master/src/Modules/ModelMapper/Readme.md#possible-future-improvements

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
