### ISSUE TITLE
Unable to open the model in the XAF Model editor. Exception on the inti type for Xpand.Persistent.Base.General.XpandModuleBase'

### ISSUE THREAD

**Issue by FlorentMaillot** [eXpandFramework/eXpand#726]
Hello. 
I've got an error when i want to open the Model in the XAF model editor. I reinstalled Xpand, rebuild my solution and can't find a way to open it. 

Here is the message i've got : 

**One or more errors were encountered while loading the designer. The errors are listed below. Fixing some of the errors may require code or model changes.
Unable to create an instance of the "Xpand.ExpressApp.Dashboard.DashboardModule" type.**
**Reason: "Une exception a été levée par l'initialiseur de type pour 'Xpand.Persistent.Base.General.XpandModuleBase'."**
`à DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   à DevExpress.ExpressApp.ModuleBase.CreateModule(Type moduleType, ModelStoreBase diffsStore)
   à DevExpress.ExpressApp.Core.ModuleFactory.ModuleFactoryWithResourcesDiffsStore.CreateModule(Type moduleType)
   à DevExpress.ExpressApp.ApplicationModulesManager.AddModule(Type moduleType, Boolean loadModuleDiffs)
   à DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   à DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   à DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   à DevExpress.ExpressApp.Design.ModelEditor.EditorPane.ReInit()
----------InnerException----------
Une exception a été levée par l'initialiseur de type pour 'Xpand.Persistent.Base.General.XpandModuleBase'.
----------StackTrace----------
   à Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   à Xpand.ExpressApp.Dashboard.DashboardModule..ctor()
   à Create_DashboardModule()
   à DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
----------InnerException----------
Impossible de charger le type 'Mono.Cecil.DefaultReflectionImporter' à partir de l'assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'.
----------StackTrace----------
   à MonoMod.Utils.MMReflectionImporter..ctor(ModuleDefinition module)
   à MonoMod.Utils.MMReflectionImporter._Provider.GetReflectionImporter(ModuleDefinition module)
   à Mono.Cecil.ModuleDefinition.CreateModule(String name, ModuleParameters parameters)
   à HarmonyLib.HarmonySharedState.CreateModule()
   à HarmonyLib.HarmonySharedState.GetState()
   à HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   à HarmonyLib.PatchProcessor.Patch()
   à HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   à Xpand.Persistent.Base.General.XpandModuleBase..cctor()`

I supposed to have a problem with the Mono.Cecil version, installed on my PC is the 0.11.2.0 version. 
I'm on the eXpand 20.1.401.0 version. 

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
In my case just rebuild solution and open the module.Model or Module.win.Model

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

**Comment by apobekiaris** [comment]
>In my case just rebuild solution and open the module.Model or Module.win.Model

which solution is this? please provide a sample with detailed instructions

**Comment by FlorentMaillot** [comment]
I think there's something wrong with my workstation installation/config (My coworkers don't have this problem).
I've got this problem on a production code, i'll try to reproduce it on a sample.

**Comment by FlorentMaillot** [comment]
Hello. 

My error message is talking about a Mono.Cecil.dll in the 0.10.0.0 Version. 
eXpand 20.1.401.0 is using the 0.11.2.0 version.. 
I think there is an error when trying to find the Mono.Cecil dll installed on the computer in eXpand, i've got Xamarin installed on my worstation, which i think was problematic.
I uninstalled the Xamarin's extension in visual studio and the problem is solved (i remembered that Mono was also used in Xamarain..)

**Comment by apobekiaris** [comment]
not a clue how they relate without a repro sample, however all good for now

**Comment by FlorentMaillot** [comment]
[DashBoardTest.zip](https://github.com/eXpandFramework/eXpand/files/4896959/DashBoardTest.zip)

You're right. 
Attached you'll find my sample. 
As it is mentionned in the error message it seems to have a problem with the DashBoardModule. 
To reproduce, try to add Xamarin extensions (using the VS installation manager). 
The sample is a Devex Xaf application with the Xpand DashBoardModule.
I cannot open the Xaf Model Editor when i have the Xamarin's extension installed in visual studio and the DashBoard module. 
Thank you for your assistance.
