### ISSUE TITLE
NetCore Support

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#727]
I've been testing NetCore 3.0 migration and it seems that the XpandModuleBase includes modules that use the Systen.Web.UI.Control from System.Web which is now legacy in NetCore.

Is there a way around this or any news on how the move to standard2.0 is going?

**Comment by apobekiaris** [comment]
no at the moment there is no support

**Comment by DSCmattb** [comment]
What in XpandModuleBase uses System.Web?

This is the error that comes out

_TypeLoadException: Could not load type 'System.Web.UI.Control' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'._

**Comment by apobekiaris** [comment]
![image](https://user-images.githubusercontent.com/159464/87042052-ca1be800-c1fb-11ea-863f-244807c30273.png)

**Comment by DSCmattb** [comment]
Isn't Xpand.Persistent.Base platform agnostic?

**Comment by apobekiaris** [comment]
not to the net targetframework

**Comment by DSCmattb** [comment]
Do you know what would inherit System.Web.UI.Control from a Win Application?

**Comment by DSCmattb** [comment]
Oh, I found it. Seems to step from InterfaceBuilderData, PropertyEditorControlAdapterController and UnitValueConverter

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
