### ISSUE TITLE
Can't use model editor when using modelartifactstate

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#732]
1. Create new expand application using expand wizard in visual studio
2.include modelartifactstate module
3.build ,and run,then open Edit model.
4.Try adding new controller state rule. And you get errors.

**Comment by sam105kelly** [comment]
Even if you use expand model editor you get errors

**Comment by sam105kelly** [comment]
Using 20.1.4

**Comment by apobekiaris** [comment]
does the XpandModelEditor works?

**Comment by sam105kelly** [comment]
No it does not work.
Follow the same procedure. And go controller state rules,add a rule and you get multiple errors.

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by expand** [comment]
eXpand.lab release [20.1.602.3](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.602.3) includes commit that relate to this task:

* [LoadAssemblyRegularTypes should be a Runtime only call #732](https://github.com/eXpandFramework/eXpand.lab/commit/8022f7c5361ab5a9a71bfa254598918d4e1bc56f)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by sam105kelly** [comment]
Thanks,I will try this tomorrow

**Comment by sam105kelly** [comment]
It is still showing errors,
Follow the same procedure

**Comment by apobekiaris** [comment]
t is not reproducible at least I am able to run the both the Xpand and the XAF ModelEditor in the attached solution without issues,

[Solution57.zip](https://github.com/eXpandFramework/eXpand/files/5033177/Solution57.zip)

**Comment by sam105kelly** [comment]
Let me check,Problem could be coming from a combination of modules.
Am using all expand modules except world creator.I will prepare a sample

**Comment by sam105kelly** [comment]
![Uploading CSIms.Primary.jpg…]()

**Comment by sam105kelly** [comment]
Open file as rar. I had problems uploading on a mobile device

**Comment by sam105kelly** [comment]
[CSIms.Primary.zip](https://github.com/eXpandFramework/eXpand/files/5039423/CSIms.Primary.zip)

**Comment by sam105kelly** [comment]
Also another error shows up at startup With this lab release about harmony failing to patch but application continues to logon screen and starts

**Comment by apobekiaris** [comment]
such solutions on the reference format are not recommended and I plan to remove them and release only as nuget packages. Said so although I can repro your problem I will not pursue it because if you install `only` the eXpandWin package in your solution and register the modules u want everything works fine.

**Comment by sam105kelly** [comment]
[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/5076547/Solution1.zip)
sample sdk style project
same issue

**Comment by sam105kelly** [comment]
[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/5076547/Solution1.zip)
sample sdk style project
same issue

**Comment by apobekiaris** [comment]
the bot may notify this case multiple times I ll let u know when works are finished

**Comment by expand** [comment]
The pre-release [2.201.14.3](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.14.3) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Add Mono.Cecil dependecy to Xpand.Patcher #732](https://github.com/eXpandFramework/DevExpress.XAF/commit/e938c492731cec3b95bccb8ce87aa3344323f7e1)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.43.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.38.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.40.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.38.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.46.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.5.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.1.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.45.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.16.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.15.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.15.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.44.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.10.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.6.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.38.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.38.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [20.1.700.1](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.700.1) includes commit that relate to this task:

* [Bump Standalone packages #732](https://github.com/eXpandFramework/eXpand.lab/commit/fc13a5117e9a40ddb5980605ad263872b35a6719)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [20.1.700.3](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.700.3) includes commit that relate to this task:

* [Revert LoadAssemblyRegularTypes should be a Runtime only call #732](https://github.com/eXpandFramework/eXpand.lab/commit/b4f99ee3817489515376435c7c289a9d883d9a79)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [20.1.700.4](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.700.4) includes commit that relate to this task:

* [User friendly message refering issue 753 #732](https://github.com/eXpandFramework/eXpand.lab/commit/53d583489740f8a33147fc33c69357e266bd37c4)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
XpandModelEditor works fine with this build please let me know

**Comment by sam105kelly** [comment]
still not working?
did the sdk poject work for you

**Comment by apobekiaris** [comment]
>still not working?

what this means? provide details yes your project works fine with the XpandModelEditor on my side

**Comment by sam105kelly** [comment]
works fine but when i add master detail module and excel importer module the same issue comes back

**Comment by apobekiaris** [comment]
i am not sure what this means, according to your project these modules are already added.

```cs
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.AdditionalViewControlsProvider.AdditionalViewControlsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.AdditionalViewControlsProvider.Win.AdditionalViewControlsProviderWindowsFormsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.AuditTrail.XpandAuditTrailModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Chart.Win.XpandChartWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Dashboard.DashboardModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Email.EmailModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.ExcelImporterModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Win.ExcelImporterWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.FileAttachment.XpandFileAttachmentsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ImportWizard.ImportWizardModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ImportWizard.Win.ImportWizardWindowsFormsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.IO.IOModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.IO.Win.IOWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.JobScheduler.Jobs.JobSchedulerJobsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.JobScheduler.JobSchedulerModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Logic.LogicModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.MasterDetail.MasterDetailModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.MasterDetail.Win.MasterDetailWindowsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ModelArtifactState.ModelArtifactStateModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ModelDifference.ModelDifferenceModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ModelDifference.Win.ModelDifferenceWindowsFormsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.PivotChart.Win.XpandPivotChartWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.PivotChart.XpandPivotChartModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.PivotGrid.Win.XpandPivotGridWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Reports.XpandReportsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ReportsV2.Win.ReportsV2WinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Scheduler.Win.XpandSchedulerWindowsFormsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Scheduler.XpandSchedulerModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Security.Win.XpandSecurityWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Security.XpandSecurityModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.StateMachine.XpandStateMachineModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.TreeListEditors.Win.XpandTreeListEditorsWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.TreeListEditors.XpandTreeListEditorsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Validation.Win.XpandValidationWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Validation.XpandValidationModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.SystemModule.XpandSystemModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.WizardUI.Win.WizardUIWindowsFormsModule));
            //RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Workflow.XpandWorkFlowModule));
            //RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.WorldCreator.DBMapper.WorldCreatorDBMapperModule));
            //RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.WorldCreator.Win.WorldCreatorWinModule));
            //RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.WorldCreator.WorldCreatorModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.XtraDashboard.Win.DashboardWindowsFormsModule));
```

1. what exactly is the issue? 
2. do u use the 20.1.700.4 build which is compiled for XAF 20.1.7?

**Comment by sam105kelly** [comment]
let me investigate,i dont know why my project is still throwing.

**Comment by sam105kelly** [comment]
yes i upgraded

**Comment by apobekiaris** [comment]
>my project is still throwing.

what is the exception u only referring to errors in this post, I have no clue what is the actual exception

**Comment by sam105kelly** [comment]
Object reference not set to an instance of an object.

   at System.Object.GetType()
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelAttributesPropertyEditorControllerWin.CreateDataSourcePropertyRepositoryItem(IEnumerable valuesList, ModelNode modelNode, String propertyName, Type elementType)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelAttributesPropertyEditorControllerWin.FillRepositoryItem(RepositoryItem repositoryItem, ModelNode modelNode, String propertyName)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelAttributesPropertyEditorControllerWin.propertyEditor_CustomFillRepositoryItem(Object sender, CustomFillRepositoryItemEventArgs e)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.AttributesPropertyGrid.OnCustomFillRepositoryItem(RepositoryItem& result, String propertyName)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.AttributesPropertyGrid.CreateDefaultRowEdit(RowProperties p)

**Comment by apobekiaris** [comment]
this method is called only at runtime and not at designtime, so apparently we are not speaking the same language. What steps exactly lead to this exception

**Comment by apobekiaris** [comment]
apologies now I can repro it

**Comment by expand** [comment]
eXpand.lab release [20.1.701.0](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.701.0) includes commit that relate to this task:

* [ModelArtifactState: New ControllerStateRule throws #732](https://github.com/eXpandFramework/eXpand.lab/commit/b07da2e26f0c99a915681d7d808868fe4e6ee6a3)
* [User friendly message refering issue 753 #732](https://github.com/eXpandFramework/eXpand.lab/commit/9e67417e9f7253d617fd15bbde8ae761e166d0da)
* [Bump Standalone packages #732](https://github.com/eXpandFramework/eXpand.lab/commit/8e7cd0c1c49944c855c68a70f5b0ef44769e582b)
* [Revert LoadAssemblyRegularTypes should be a Runtime only call #732](https://github.com/eXpandFramework/eXpand.lab/commit/dd9e251805362bdaa72c0f8d2d517449e75da790)
* [LoadAssemblyRegularTypes should be a Runtime only call #732](https://github.com/eXpandFramework/eXpand.lab/commit/f817c789ec83676d64ee173574da102c141f7fad)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
there is a versioning issue please try the next minor you won't be notified again, let me know how it works now

**Comment by sam105kelly** [comment]
works fine thanks

**Comment by expand** [comment]
eXpand.lab release [20.1.703.1](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.703.1) includes commit that relate to this task:

* [ModelArtifactState: New ControllerStateRule throws #732](https://github.com/eXpandFramework/eXpand.lab/commit/4215d294486bf03ce39cdb44a1c98ecf3299c9a9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.
