### ISSUE TITLE
ModelMapper with 2 apps

### ISSUE THREAD

**Issue by melihyilman** [eXpandFramework/eXpand#734]
Hi tolis,
I have issue with modelmapper module, the proplem is i have two application (ribbon mdi,sdi..). That two app cant run at the same time because of modelmapper create dll for it.
Basicly two application in same folder cant run at the same time.

Log : 
`error CS0016: 'c:\Projects\Development\ManageMind\ManageMind.Win\bin\Debug\ModelMapperAssemblyWin.dll' Could not write to output file -- 'This operation cannot access the file because the file is used by another process. '

   at: Xpand.XAF.Modules.ModelMapper.Services.TypeMapping.TypeMappingService.Compile(IEnumerable`1 references, String code)
   at: System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   at: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at: System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at: System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   at: System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   at: System.Reactive.Sink`2.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count)
   at: System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at: System.Reactive.ObserverBase`1.OnError(Exception error)
   at: System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count)
   at: System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Subjects.Subject`1.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Sink`1.ForwardOnError(Exception error)
   at: System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)
   at: System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at: System.Reactive.ObserverBase`1.OnNext(T value)
   at: Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass13_1`1.<Trace>b__2(TSource v)
   at: System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at: System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at: System.Reactive.Linq.ObservableImpl.Aggregate`1._.OnCompleted()
   at: System.Reactive.Sink`1.ForwardOnCompleted()
   at: System.Reactive.TailRecursiveSink`1.Drain()
   at: System.Reactive.TailRecursiveSink`1.Recurse()
   at: System.Reactive.Sink`1.ForwardOnCompleted()
   at: System.Reactive.Sink`1.ForwardOnCompleted()
   at: System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler)
   at: System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at: System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at: System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at: System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
   at: System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at: System.Reactive.Linq.ObservableImpl.Switch`1._.OnNext(IObservable`1 value)
   at: System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at: System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at: System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
   at: System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value)
   at: System.Reactive.Subjects.Subject`1.OnNext(T value)
   at: Xpand.XAF.Modules.Reactive.ReactiveModule.ExtendModelInterfaces(ModelInterfaceExtenders extenders)
   at: DevExpress.ExpressApp.ApplicationModelManager.CreateModelApplicationCreatorProperties(ITypesInfo typesInfo, IEnumerable`1 modules, IEnumerable`1 controllers, String assemblyFileAbsolutePath)
   at: DevExpress.ExpressApp.ApplicationModelManager.Setup(ITypesInfo typesInfo, IEnumerable`1 boModelTypes, IEnumerable`1 modules, IEnumerable`1 controllers, IEnumerable`1 applicationLocalizerTypes, IEnumerable`1 applicationAspects, ModelStoreBase applicationModelDifferenceStore, String modelAssemblyFile)
   at: DevExpress.ExpressApp.XafApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   at: DevExpress.ExpressApp.Win.WinApplication.CreateModelManager(IEnumerable`1 boModelTypes)
   at: DevExpress.ExpressApp.XafApplication.Setup(ExpressApplicationSetupParameters parameters)
   at: DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at: DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   at: System.Threading.Tasks.Task.Execute()`

Same issue did fix this before on Model with adding to config modelAssemblyPath
    <add key="UserModelDiffsLocation" value="CurrentUserApplicationDataFolder" />

So can you use UserModelDiffsLocation on config?

**Comment by apobekiaris** [comment]
can you repro it in an empty xaf solution where only ModelMapper is installed?

**Comment by apobekiaris** [comment]
there are tests that do not fail and verify that a new ModelMapper assembly wont be created if it exists, so please provide exact repro steps to spare my resources

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
