### ISSUE TITLE
Error updating model: Exception occurs while the 'Xpand.Persistent.Base.General.Controllers.CustomAttibutesController' customizes TypesInfo: NRE

### ISSUE THREAD

**Issue by Vbacna** [eXpandFramework/eXpand#735]
Hello, Tolis

I have a problem starting to use eXpand. Having installed eXpand and used JobsSchedulerModule, I now fail to update models in my project, and cannot open model for the Web project in model editor:

Exception occurs while the 'Xpand.Persistent.Base.General.Controllers.CustomAttibutesController' customizes TypesInfo: Object reference not set.

Details:
в DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)
   в DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   в DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(XafApplication application, String configFileName, String assembliesPath)
   в DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   в DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   в DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
----------InnerException----------
Ссылка на объект не указывает на экземпляр объекта. (NullReferenceException)
----------StackTrace----------
   в Xpand.Persistent.Base.General.Controllers.CustomAttibutesController.HandleCustomAttribute(IMemberInfo memberInfo, ITypesInfo typesInfo)
   в Xpand.Persistent.Base.General.Controllers.CustomAttibutesController.CustomizeTypesInfo(ITypesInfo typesInfo)
   в DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)

However,
'My.Module' base (agnostic) module, which is using JobsSchedulerModule works,
'My.Module.Wev' also opens the model,
but 'My.Web' application fails

Also, the 'My.Web' model is opened in eXpand model without problems.

Can you suggest anything to solve the problem?

**Comment by apobekiaris** [comment]
without a sample i cannot guess why it fails, in the meantime maybe this solution workaround it https://github.com/eXpandFramework/eXpand/issues/707#issuecomment-630321315

**Comment by apobekiaris** [comment]
this is fixed in next minor

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
