### ISSUE TITLE
XAF Model Editor throws Exception due to eXpand

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#738]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Opening the model I get the following issue:

The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception.

It seems to be within the following line:

this.importWizardModule1 = new Xpand.ExpressApp.ImportWizard.ImportWizardModule();

This is inside the InitializeComponent on the WinApp

**Comment by apobekiaris** [comment]
does the XpandModelEditor works? also see the workaroound posted here https://github.com/eXpandFramework/eXpand/issues/724#issuecomment-659985778

**Comment by DSCmattb** [comment]
If the model editor opens via the Model List mine simply opens a transparent window.

**Comment by apobekiaris** [comment]
this can be fixed by unchecking the VS/Tools/Options/Enviroment/General/Optimize Rendering

**Comment by DSCmattb** [comment]
That opens now, but it throws a different error.

We're running .net sdk project style which puts the output location as the following: \bin\Local\net462\win-x64 as per the identifier and target platform but the model editor is expecting it to be in the output path bin\Local\ but VS seems to do something different now after we moved to .net sdk project.

**Comment by apobekiaris** [comment]
do u really use that identifier functionality? it can also be disabled

**Comment by DSCmattb** [comment]
We do, regardless I would have expected it to pick it up.
As well as that it would still go to \bin\Local\net462 without the identifier which would mean that it would still throw errors. Its expecting the .exe to bin in \bin\Local which is naturally won't be due to the new way them seem to build the project in the new style

**Comment by apobekiaris** [comment]
yes true it should pickup I just tried to provide an immediate solution

**Comment by apobekiaris** [comment]
this is also addressed already let me know if not

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
