### ISSUE TITLE
Optimistic Locking occurs to other objects when Pessimistic Locking is added

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#741]
Can confirm the new version addresses this issue.

However a separate issue has started. When adding the attributes to class A that inherits XPCustomObject it works fine and works as expected. However when modifying object B that inherits XPLiteObject we now get the application tracking changes to the object and asking for merging. on save as per the following image from DX.

https://docs.devexpress.com/eXpressAppFramework/images/concurrencymerge117396.png

This wasn't a problem previously and I have confirmed that removing the attribute on Object A stops this from happening.

Object A and B are linked 1-1 but the objects being attempted do not have data in the relations.

_Originally posted by @DSCmattb in https://github.com/eXpandFramework/eXpand/issues/655#issuecomment-665435598_

**Comment by apobekiaris** [comment]
I can say that I do not recall any changes that can result in behavior change to this feature. To resaerch the case resources are required and repro sample

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
