### ISSUE TITLE
Powershell Install doesn't respect spaces in path for VSIX install

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#742]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
If you were to install into the following path C:\Example Folder when the powershell script starts the install of the VSIX it simply calls the location of the VSIX without quotations which then throws errors about the path.

**Comment by apobekiaris** [comment]
post the console output

**Comment by apobekiaris** [comment]
also the script is again public just in case some one want to fix it

https://github.com/eXpandFramework/XpandPwsh/blob/master/XpandPwsh/Private/Xpand/InstallXpand.ps1

you just download and run and let me know the fix or send a PR

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
