### ISSUE TITLE
Modules.Office.Cloud.Microsoft -> ClientId & ClientSecret not visible in model

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#745]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
After installing Xpand.XAF.WEB.All and adding office module, i still do not see the ClientID and ClientSecret. 
This test are done in a empty project. 
![image](https://user-images.githubusercontent.com/41955268/89329445-1ccbb100-d68f-11ea-93f1-f2e10a54a5bd.png)
[Solution2.zip](https://github.com/eXpandFramework/eXpand/files/5023793/Solution2.zip)

**Comment by isatahiri** [comment]
in your code, I see that these two propertie are decorate with : 
[ModelBrowsable(typeof(DesignerOnlyCalculator))]

What is this ? Might be the issue ?

**Comment by apobekiaris** [comment]
u r right the DesignerOnlyCalculator which does not work with the XpandModelEditor. Unitl I fix it u can define the property in your xaffml file or by code, it just that the property is invisible in ME it should work fine other ways

**Comment by isatahiri** [comment]
Thanks for the info.

**Comment by apobekiaris** [comment]
this is already fixed

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
