### ISSUE TITLE
Xpand Patcher 2.0.23 needed. 2.0.15 on nuget.org

### ISSUE THREAD

**Issue by n1LWeb** [eXpandFramework/eXpand#748]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
The newest nuget Packages need Xpand.Patcher 2.0.23 bit only 2.0.15 is on nuget. Failed deploy?
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
install Nuget package eXpandIO
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
Install
𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
German Message
Es wird versucht, Abhängigkeiten für das Paket "Xpand.Extensions.XAF.2.202.43" mit dem DependencyBehavior "Lowest" aufzulösen.
Die Version von "Xpand.Patcher", die mit 'Xpand.Extensions.XAF 2.202.43 Einschränkung: Xpand.Patcher (>= 2.0.23)' kompatibel ist, wurde nicht gefunden.
Verstrichene Zeit: 00:00:00.2417200

Matches
05. Installation
06. ShowStopper
07. Nuget

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
thnks for the the heads up, the package was only available through our lab server, I have now publish it

```ps1
Find-NugetPackage xpand.patcher

Id                       Version
--                       -------
Xpand.Patcher            2.0.23
```
