### ISSUE TITLE
LookupCascade - horizotal scroll bar or wrap

### ISSUE THREAD

**Issue by itahirikba** [eXpandFramework/eXpand#755]
Hello,
I see that in the LookupCascade, this is no way to make the lookup larger or have scroll bar. 
Maybe we can add scroll bar or wrap or extend the with somehow. 

![image](https://user-images.githubusercontent.com/57799686/91443502-b859d700-e873-11ea-882a-9ebffb6a5371.png)

**Comment by apobekiaris** [comment]
You can achieve it decoratively using [ModelMapper](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper) with which u can configure the ComboBox control visible rows , please check the ModelMapper wiki 2,3 sections that refer on how to configure propertyeditors. In this case u should deal with the RepositoryItemCombo and ASPxComboBox

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
