### ISSUE TITLE
How to fix error during Install-Xpand from Powershell for Version 20.1.602.0

### ISSUE THREAD

**Issue by stefanushalim** [eXpandFramework/eXpand#756]
Hi there, i try to install eXpand using below command in Powershell.

`>Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  -Version '20.1.602.0' -SkipGac`

but I got the following error.

**Additional parameters: Version, Latest, Assets, InstallationPath
20.1.602.0.0 is a eXpand version
Cannot convert value "20.1.602.0.0" to type "System.Version". Error: "Version string portion was too short or too
long."**

I noticed that there is additional .0 added on the version but if I put:

`>Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  -Version '20.1.602' -SkipGac`

Version returned correct but I got new error: 404 not found,

**Additional parameters: Version, Latest, Assets, InstallationPath
20.1.602.0 is a eXpand version
Downloading Sources from https://github.com/eXpandFramework/eXpand/releases/download/20.1.602/Xpand-Source-20.1.602.zip into C:\eXpandFramework
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."**

Could you please help on how to fix this issue?

**Comment by apobekiaris** [comment]
I do not not recommend to use the installer anymore and is going obsolete as per #746. Moving towards to .NetCore the GAC makes no sense and having all assemblies in a global dir only leads to problems. You can try the same approach demoed at https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules but if u want to use the main framework packages  u should use the related container packages which are the eXpandWin, eXpandWeb, eXpandAgnostic

**Comment by apobekiaris** [comment]
if u for some reason u still want to make the installer work, you can try fix it your self as the script is public and can be download and run locally https://github.com/eXpandFramework/XpandPwsh/tree/master/XpandPwsh/Private/Xpand

**Comment by neuropseudolonicher** [comment]
Modifying InstallXpand.ps1 by adding 
_$release = $Version_ in ln. 63 
and adding the line 
_InstallXpand -Version 'xx.x.xxx' -SkipGac_ (where xx.x.xxx reflects the version requested)
 to call InstallXpand() function at the end of the script did it for me.
Script was started then locally from a powershell with elevated privileges.

**Comment by apobekiaris** [comment]
please post the modified script or even better send a PR either wasy u prefer

**Comment by neuropseudolonicher** [comment]
Attached my version of the script to initialize eXpand installation as described above
[InstallXpand.zip](https://github.com/eXpandFramework/eXpand/files/5154674/InstallXpand.zip)

**Comment by apobekiaris** [comment]
in line 162 u have 

```ps1
InstallXpand -Version '20.1.602' -SkipGac
```

what is the meaning of such a call, it does not look good to me

**Comment by neuropseudolonicher** [comment]
This line calls function InstallXpand() if you start the script from a local PS, as described in my comment of August 31, 11:14

**Comment by apobekiaris** [comment]
i modified the public version can u try and let me know

**Comment by apobekiaris** [comment]
note installed is depreciated going forward from 20.1.602.4

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
