### ISSUE TITLE
Model Difference Question 

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#758]
I'm using the Model Difference Module in a Win app and now I need to implement a Web counterpart, but I do not need to enable per-user model difference.
How can  I disable user model differences only for the web app?

Thanks

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
it should be possible but what problem you trying to workaround by this?

**Comment by vimarx** [comment]
My scenario involves about a thousand potential users, and I don't need too many user models

**Comment by apobekiaris** [comment]
ok give me some time to research it

**Comment by apobekiaris** [comment]
on a first thought what is the problem on storing 1000 models? did u face performance issues? u still have to persist user model differences somehow e.g listview layout. or you do not? or u want to fallback to default storage?

**Comment by apobekiaris** [comment]
although I do not see a problem having the user store in place, a call like the following can disabled it.

``cs
WebApplication.Instance.Setup();
            application.CreateCustomUserModelDifferenceStore += (o, args) => {
                args.Store = null;
                args.Handled = false;
            };
            WebApplication.Instance.Start();
```
