### ISSUE TITLE
20.1.701.1 Can not build model

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#762]
Hi Tolis,

after Update to 20.1.701.1 (from 20.1.401.0) I got the error

------- Updating model differences: Project: C:\DevProjects\iXISIF\iXISXRM.Module\iXISXRM.Module.csproj
Error:
Unable to create an instance of the "Xpand.ExpressApp.SystemModule.XpandSystemModule" type.
Reason: "Der Typeninitialisierer für "Xpand.Persistent.Base.General.XpandModuleBase" hat eine Ausnahme verursacht."
Update failed

I added the module by
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.SystemModule.XpandSystemModule));

**Comment by apobekiaris** [comment]
Hi,

Please post the log located next to the model in the failing project dir

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by CWolffIF** [comment]
Hi, there is no log next to the model.

**Comment by CWolffIF** [comment]
But if I try to open the module in VS directly i got the message. The Xpand.Xpo.dll could not be found.


bei DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   bei DevExpress.ExpressApp.ModuleBase.CreateModule(Type moduleType, ModelStoreBase diffsStore)
   bei DevExpress.ExpressApp.Core.ModuleFactory.ModuleFactoryWithResourcesDiffsStore.CreateModule(Type moduleType)
   bei DevExpress.ExpressApp.ApplicationModulesManager.AddModule(Type moduleType, Boolean loadModuleDiffs)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
----------InnerException----------
Der Typeninitialisierer für "Xpand.Persistent.Base.General.XpandModuleBase" hat eine Ausnahme verursacht.
----------StackTrace----------
   bei Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   bei Xpand.ExpressApp.SystemModule.XpandSystemModule..ctor()
   bei Create_XpandSystemModule()
   bei DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
----------InnerException----------
Die Datei "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Xpand.Xpo.dll" konnte nicht gefunden werden.
----------StackTrace----------
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   bei Xpand.Persistent.Base.General.XpandModuleBase.AssemblyResolver.Resolve(AssemblyNameReference name)
   bei Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   bei Mono.Cecil.TypeReference.Resolve()
   bei Xpand.Extensions.Mono.Cecil.MonoCecilExtensions.<BaseClasses>d__0.MoveNext()
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Xpand.Extensions.Mono.Cecil.MonoCecilExtensions.IsSubclassOf(TypeDefinition childTypeDef, TypeDefinition parentTypeDef)
   bei Xpand.Persistent.Base.General.XpandModuleBase.<>c__DisplayClass99_0.<LoadAssemblyRegularTypes>b__1(TypeDefinition definition)
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei Xpand.Persistent.Base.General.XpandModuleBase.LoadAssemblyRegularTypes()
   bei Xpand.Persistent.Base.General.XpandModuleBase..cctor()

**Comment by CWolffIF** [comment]
Full Log.
[Model.DesignedDiffs.log](https://github.com/eXpandFramework/eXpand/files/5172948/Model.DesignedDiffs.log)

**Comment by apobekiaris** [comment]
i will try to skip this method when devenv is used, my guess is that XpandModelEditor works fine?

**Comment by apobekiaris** [comment]
note  that .netcore base editor is standalone and does not suffer anymore from these issues, pretty much behave like the XpandModelEditor

**Comment by CWolffIF** [comment]
Yes your XpandModelEditor works fine. But if you try to update the model in (rightclick in devenv) you got the same error.

**Comment by apobekiaris** [comment]
update model will use VS to open the model and VS behavior is somewhat problematic no need to mention that. Personally I never use it nor the Update model action. In any case let me know how the next minor behaves.

**Comment by expand** [comment]
eXpand.lab release [20.1.701.2](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.701.2) includes commit that relate to this task:

* [Skip LoadAssemblyRegularTypes when ME devenv is used #762](https://github.com/eXpandFramework/eXpand.lab/commit/38421b9b610de5f3abed4778966b2400e95fbc43)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi Tolis. Thanx. It is solved.

**Comment by expand** [comment]
eXpand.lab release [20.1.703.1](https://github.com/eXpandFramework/eXpand.lab/releases/20.1.703.1) includes commit that relate to this task:

* [Skip LoadAssemblyRegularTypes when ME devenv is used #762](https://github.com/eXpandFramework/eXpand.lab/commit/31673cca10c2002be579e567d76d8f7230c5af08)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.

Thanks a lot for your contribution.
