### ISSUE TITLE
Error updating nuget-Packages from 20.1.4 to 20.1.7

### ISSUE THREAD

**Issue by neuropseudolonicher** [eXpandFramework/eXpand#763]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Attached is a sample project, I have originally provided this as a sample for #754 using eXpand 20.1.401

We have no changed Reference from eXpand-Installation to use nuget, which basically worked fine. 
When we try to update this project to use version 20.1.701, the update fails with the followwing error message:

_Attempting to gather dependency information for multiple packages with respect to project 'exPsample.Win', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 16,26 sec
Attempting to resolve dependencies for multiple packages.
Unable to resolve dependencies. 'Xpand.Patcher 2.0.23' is not compatible with 'eXpandLib 20.1.701 constraint: Xpand.Patcher (>= 2.0.24)', 
'Xpand.Extensions.XAF 2.202.46 constraint: Xpand.Patcher (>= 2.0.24)', 
'Xpand.XAF.Modules.CloneModelView 2.202.46 constraint: Xpand.Patcher (>= 2.0.24)', 
'Xpand.XAF.Modules.Reactive 2.202.46 constraint: Xpand.Patcher (>= 2.0.24)', 
'Xpand.XAF.Modules.Reactive.Logger 2.202.46 constraint: Xpand.Patcher (>= 2.0.24)'.
Time Elapsed: 00:00:09.9807579
========== Finished ==========_

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. Open project in Visual Studio
2. Start Package Manager Console
3. Type Update-Package eXpandLib
4. Error message is being written to console

𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
![image](https://user-images.githubusercontent.com/60786066/92230094-c8dd0380-eeaa-11ea-9c03-1dba03ceaf4c.png)

**Sample**
[exPsample_nuget.zip](https://github.com/eXpandFramework/eXpand/files/5174276/exPsample_nuget.zip)

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by neuropseudolonicher** [comment]
[exPsample_nuget.zip](https://github.com/eXpandFramework/eXpand/files/5174289/exPsample_nuget.zip)

**Comment by apobekiaris** [comment]
the Xpand.Patcher 2.0.24 was available only in lab servers I just publish it on nuget, let me know if it resolved the case.

https://www.nuget.org/packages/Xpand.Patcher/

still indexing though try a bit later

**Comment by neuropseudolonicher** [comment]
Yes, it's solved.

Thanks for your immediate help :-)
