### ISSUE TITLE
VSIX New Solution Error

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#771]
Trying to create a new solution with 20.1.701 and get this error.

![image](https://user-images.githubusercontent.com/889492/92947017-71e4aa80-f425-11ea-858b-6616d2ba143f.png)

**Comment by apobekiaris** [comment]
the Xpand installer is depreciated nuget is the only distribution channel now. As so the VSIX wizard is removed so I guess u have not updated your VSIX yet.

nuget provides the modules installation script as similar to https://www.youtube.com/watch?v=LvxQ-U_0Sbg&feature=youtu.be

Note that going forward I only offer support for samples using Nuget and not direct references. The Nugets contain logic that shouldn't be skipped.

**Comment by capricciobob** [comment]
Thank you!
