### ISSUE TITLE
CompatibilityException when using worldcreator + MasterDetailModule

### ISSUE THREAD

**Issue by Johnkag** [eXpandFramework/eXpand#772]
use this combination
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.WorldCreator.DBMapper.WorldCreatorDBMapperModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.WorldCreator.Win.WorldCreatorWinModule));
            RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.MasterDetail.Win.MasterDetailWindowsModule));

you get 

System.InvalidOperationException
  HResult=0x80131509
  Message=Exception occurs while initializing the 'Xpand.ExpressApp.WorldCreator.WorldCreatorModule' module: An error with number 1111 has occurred.
Error message: The database version is greater than the application version. The application needs to be updated. Please contact your system administrator or download a new version.
Additional information: the local version 2.202.46.0 of module 'MasterDetailModule' is smaller than version 20.1.701.2 in the database.
  Source=Xpand.XAF.Modules.Reactive
  StackTrace:
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 80
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModulesPatch(ApplicationModulesManager __instance) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 47
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)

Inner Exception 1:
CompatibilityException: An error with number 1111 has occurred.
Error message: The database version is greater than the application version. The application needs to be updated. Please contact your system administrator or download a new version.
Additional information: the local version 2.202.46.0 of module 'MasterDetailModule' is smaller than version 20.1.701.2 in the database.

**Comment by Johnkag** [comment]
added           Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.MasterDetail.MasterDetailModule));
but still throws

**Comment by apobekiaris** [comment]
sample is required

**Comment by apobekiaris** [comment]
also note that v2.202.46.0 belongs to the https://github.com/eXpandFramework/DevExpress.XAF repository and  v20.1.701.2  to this one

**Comment by Johnkag** [comment]
[Win.zip](https://github.com/eXpandFramework/eXpand/files/5214372/Win.zip)

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by Johnkag** [comment]
i think its because modules from the two repositories have the same name "MasterDetailModule"

**Comment by apobekiaris** [comment]
the standalone packages can be unloaded, instructions available in each module wiki

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail#issues-debugging-troubleshooting

**Comment by Johnkag** [comment]
still throws even if unloaded

**Comment by Johnkag** [comment]
still throws after            Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.MasterDetail.MasterDetailModule));

**Comment by apobekiaris** [comment]
Sorry without further research I cannot help you more. The unload feature is tested on each build and it should work. However although you prioritized with the sample, there are pending cases with [higher priority](https://github.com/eXpandFramework/eXpand/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3APriority) at the moment. Once i research the case I let u know. 

Consider boosting the case priority as per [my support tiers](https://github.com/sponsors/apobekiaris) and please let me know if you solve it your self not to consume my resources in vain.

**Comment by apobekiaris** [comment]
did u resolve the case?

**Comment by Johnkag** [comment]
renamed expand master detail module
