### ISSUE TITLE
FileNotFound exception with new project

### ISSUE THREAD

**Issue by mbogaerts** [eXpandFramework/eXpand#773]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Could not find file 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Xpand.Xpo.dll'.
File not found exception when creating new 20.1 project, added expand via the nuget packages
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
File not found exception when creating new 20.1 project, added expand via the nuget packages𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
looks related to #762 however I cannot guess as your post is missing details

**Comment by apobekiaris** [comment]
there is a related fix in the next minor if u haven't resolve this already

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
