### ISSUE TITLE
Exception when try to open dashboard designer on a client machine

### ISSUE THREAD

**Issue by GillesBrice** [eXpandFramework/eXpand#780]
Hello,

I got an exception when try to open dashboard designer on a client machine. I don't have this error when I open the dashboard on my developper's machine (on visual studio or with the .exe)

Here the exception :
 `Stack trace:

   à Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindToModel(IModelNodeDisabled modelNodeDisabled, Object instance)
   à Xpand.ExpressApp.XtraDashboard.Win.Controllers.DashboardDesignerApplyModelController.OnDashboardDesignerOpening(Object sender, DashboardDesignerOpeningEventArgs e)
   à Xpand.ExpressApp.Dashboard.Controllers.DashboardDesignerController.OnDashboardDesignerOpening(DashboardDesignerOpeningEventArgs e)
   à Xpand.ExpressApp.XtraDashboard.Win.Controllers.DashboardDesignerController.DashboardEditExecute(Object sender, SimpleActionExecuteEventArgs e)
   à DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   à DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
InnerException is null`

On the client machine, in the Model, I see that the DesignerSettings node of the DashboardModule isn't created.
![devenv_9yBh0gYoZo](https://user-images.githubusercontent.com/14292185/94529401-bdcb8800-024a-11eb-9788-da18a7ee37f6.png)

How can I do to solve this problem please ? A dll missing ?

**Comment by apobekiaris** [comment]
you can start by searching the issues for ModelBindingService there are several cases with several work arounds e.g. #659. 

If you still require support in order to add the case in the prioritization queue I need a repro sample. 

To boost case resolution consider subscribing to one of my tiers  https://github.com/sponsors/apobekiaris

**Comment by apobekiaris** [comment]
Also I want to add that since in one enviroment it works fine and in other not, it should be a case of missing assemblies. It should be also possible to attach a debugger and try to get more info on whats missing by placing the disctrubted pdb files in path.

**Comment by apobekiaris** [comment]
>or with the .exe

put all xpand assemblies from your bin and DX assemblies from the GAC in client folder, Does it solve it? If yes do the same gradully until u find the missing assembly

**Comment by GillesBrice** [comment]
Hello,

I find the problem, my projects' configurations was in x86 for the Release configuration and in Any CPU for the Debug.
I put Any CPU for the Release configuration and I don't have the exception anymore.
