### ISSUE TITLE
How to use SequenceGenerator?

### ISSUE THREAD

**Issue by stefanushalim** [eXpandFramework/eXpand#781]
I have register the Xpand.XAF.Modules.SequenceGeneratorModule 
but don't know how to make it works.

Could you provide a sample on how to use this module?

𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
A clear and concise description

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
there is a detailed wiki for it

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
