### ISSUE TITLE
VS2019, creating new solution: The vstemplate file references the wizard class 'Xpand.VSIX.Wizard.SolutionWizard', which does not exist in the assembly 'Xpand.VSIX, Version=20.1.704.0

### ISSUE THREAD

**Issue by Wojtekxor2** [eXpandFramework/eXpand#788]
Hi,

I have installed Xpand.VSIX-20.1.704.0.vsix for VS2019. When I wantes to create new expend solution I got that error: 

The vstemplate file references the wizard class 'Xpand.VSIX.Wizard.SolutionWizard', which does not exist in the assembly 'Xpand.VSIX, Version=20.1.704.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958'.

What to do with that?

**Comment by apobekiaris** [comment]
I am not sure in which exact version this was depreciated but the New-ProjectWizard and the powershell installed are now depreciated. The nuget is the distributionu have to use and contains all data to make you life easy 

see this related video in a this wiki https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules#modules-list

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
