### ISSUE TITLE
Microsoft cloud calendar in direction

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#789]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
In the **IN** direction, the local event is always null. Does that mean I have to request it in the db on the fly ? 
If so, the Id of the event is store in the CloudOfficeObject table i guess. 

![image](https://user-images.githubusercontent.com/41955268/96255650-94835980-0fb7-11eb-90df-7e451fb25500.png)

![image](https://user-images.githubusercontent.com/41955268/96255131-b3352080-0fb6-11eb-9073-6321dc9d1a77.png)

**Comment by apobekiaris** [comment]
if you `e.handled=true` means that u override the default map which will create an object for the `Insert` case  like 

```cs
 if (args.Instance.mapAction == MapAction.Insert&&synchronizationType.IsCreate()){
                                    localEvent = (IEvent)objectSpace.CreateObject(newCloudEventType);
                                    objectSpace.CommitChanges();
                                    objectSpace.NewCloudObject(localEvent, args.Instance.cloud).Wait();
                                    localEvent.Update( args);
                                }
                                else if (args.Instance.mapAction == MapAction.Update&&synchronizationType.IsUpdate()){
                                    localEvent.Update( args);
                                }
``

it use the Model for the  `newCloudEventType`  which by looking a bit up in the call chain is retrieved from 

```cs
var newCloudEventType = _.frame.View.Model.Application.Calendar().NewCloudEvent.TypeInfo.Type;
```

https://github.com/eXpandFramework/DevExpress.XAF/blob/fc426d7b646bf18a98dadee1a91c5605e4314203/src/Modules/Office.Cloud.Microsoft.Calendar/CalendarService.cs#L197-L202

https://user-images.githubusercontent.com/159464/93871666-ac78fd80-fcd7-11ea-9db6-1279678557ae.png

**Comment by apobekiaris** [comment]
>an I have to request it in the db on the fly ?

so yes an object must be created since does not exist locally either from u or from the default map

**Comment by isatahiri** [comment]
I'll handle only update in this case. Seems to work. Thanks. I'm still having " SessionStore is not available.". 
I do not know how to repro it. So until then, I guess we cannot do much. 
 
The error occurred:

	Type:       InvalidOperationException
	Message:    SessionStore is not available.
	Data:       0 entries
	Stack trace:

   à DevExpress.ExpressApp.Web.ASPSessionValueManagerBase.SetValue(String key, Object value)
   à DevExpress.ExpressApp.Web.ASPSessionValueManager`1.set_Value(ValueType value)
   à DevExpress.ExpressApp.Model.Core.ModelNodeValuesCache.get_ModelValuesCache()
   à DevExpress.ExpressApp.Model.Core.ModelNodeValuesCache.GetValue(ModelNode modelNode, String name, Func`2 getValueMethod)
   à DevExpress.ExpressApp.Model.Core.ModelNode.GetDefaultValueCore(ModelValueInfo info, String name)
   à DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[ValueType](IModelValue`1 modelValue, String name, Int32 aspectIndex)
   à DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Boolean inThisLayer, Int32 aspectIndex)
   à DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   à ModelCalendarItem.get_ObjectView()
   à Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar.CalendarService.<>c__DisplayClass27_0.<Authorize>b__4(IModelCalendarItem item) dans D:\a\1\s\src\Modules\Office.Cloud.Microsoft.Calendar\CalendarService.cs:ligne 116
   à System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   à Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar.CalendarService.<>c.<Authorize>b__27_2(ValueTuple`3 t) dans D:\a\1\s\src\Modules\Office.Cloud.Microsoft.Calendar\CalendarService.cs:ligne 114
   à System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) dans /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:ligne 39
	InnerException is null

**Comment by apobekiaris** [comment]
>SessionStore is not availabl

means that u access non-thread safe data stored in the HttpSession which is not available. from the screenshot u posted I cannot see clear, if you cannot find it ping me tomorrow on skype and I can remote to you

**Comment by isatahiri** [comment]
Ok Thanks

**Comment by isatahiri** [comment]
So after commenting all my customization, I still have the issue
When looking at the stack, i checked the line 114-116 of the CalendarService and there you are accessing to the model : 
![image](https://user-images.githubusercontent.com/41955268/96333428-2fd50700-106a-11eb-9528-287a5b3ce5ea.png)

**Comment by isatahiri** [comment]
Method  in [CalendarService](src/Modules/Office.Cloud.Microsoft.Calendar/CalendarService.cs)

    static IObservable<(Frame frame, GraphServiceClient client, global::Microsoft.Graph.Calendar calendar, IModelCalendarItem calerdarItem)> Authorize(this  IObservable<Frame> source) 
            => source
	            .AuthorizeMS()
                .EnsureCalendar()
                .Publish().RefCount()
                .WhenNotDefault(t => t.frame.Application)
                .Do(tuple => ClientSubject.OnNext((tuple.frame,tuple.client)))
                .Select(t => (t.frame, t.client, t.calendar,
                    t.frame.Application.Model.ToReactiveModule<IModelReactiveModuleOffice>().Office.Microsoft()
                        .Calendar().Items.First(item => item.ObjectView==t.frame.View.Model)))
                .TraceMicrosoftCalendarModule(_ => _.frame.View.Id);

**Comment by expand** [comment]
The pre-release [2.201.19.3](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.19.3) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Cloud Office: Emit for all matching model rules #789](https://github.com/eXpandFramework/DevExpress.XAF/commit/aee0a92db18147238a4d031a2a8db5635b7fcf78)
* [Synchronize threads on authorization #789](https://github.com/eXpandFramework/DevExpress.XAF/commit/f07b3105e3ac242614b4cb9ea739c675b69808e6)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions.Office.Cloud v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Office.Cloud.Google.Blazor v.2.202.0.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor)
 1. [Xpand.XAF.Core.All v.2.202.43.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.61.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.59.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.20.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.2.202.10.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.17.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.60.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.31.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.30.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.Office.DocumentStyleManager v.2.202.7.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.DocumentStyleManager)
 1. [Xpand.XAF.Modules.OneView v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.30.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.59.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.59.7](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.59.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.25.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.21.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.43.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.43.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The pre-release [2.201.20.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.20.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Cloud Office: Emit for all matching model rules #789](https://github.com/eXpandFramework/DevExpress.XAF/commit/4ee79dfa58927718b37c1899e6d2b3f2bd0fc138)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.59](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.54](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Office.Cloud.Google.Blazor v.2.202.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor)
 1. [Xpand.Extensions.Reactive v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.56](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.44](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.62](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.21](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.2.202.11](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.18](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.61](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.32](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.31](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.Office.DocumentStyleManager v.2.202.8](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.DocumentStyleManager)
 1. [Xpand.XAF.Modules.OneView v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.31](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.61](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.60](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.26](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.22](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.44](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.44](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Passing to blazor... So closing this issue created for asp.net app.
