### ISSUE TITLE
ModelAssembly.dll always regenerates when using expand master detail module 

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#791]
I have noticed that the model assembly is always regenerated when I Add 
Xpand.ExpressApp.MasterDetailModule.

While developer machines are fast,client machines are relatively slow and this can mean an extra  15-40 seconds at start up.
 
If you removed the module, startup is a lot faster.

**Comment by sam105kelly** [comment]
It is regenerated on subsequent runs even in release mode

**Comment by apobekiaris** [comment]
#785 although it will not treat specifically any case related to MasterDetail aims to improve performance please subscribe to it to get notified once released

**Comment by sam105kelly** [comment]
Already subscribed.
Also I would like to clarify that this is the modelassembly.dll and not the model mapper assembly.

**Comment by apobekiaris** [comment]
but xaf provides all means to stop modelassembly regeneration and use it from the path, so only compile it once

**Comment by apobekiaris** [comment]
and as far as I remember this is the default behavior so it shouldn't update the modelassembly if no debugger is attached, have u research on it or have additional feedback?

**Comment by sam105kelly** [comment]
If you remove expand master detail module. The assembly is not regenerated.
But that's a very useful module.
I will inform you if I find out the cause

**Comment by apobekiaris** [comment]
my guess is that it relates to ModelMapper as it is a dependency  to the system win module

https://github.com/eXpandFramework/eXpand/blob/master/Xpand/Xpand.ExpressApp.Modules/MasterDetail.Win/MasterDetailWindowsModule.cs#L13

so it will be really valuable to know when exactly xaf generates again the ModelAssembly cause xpand does not delete it. 

As you understand this case requires resources and is not clear what to blame so unless there is an active subscription I am afraid I cannot prioritize it.

**Comment by apobekiaris** [comment]
also the XAF model lazy loads so in theory it should not be affected by the size of the model at least when the model already exists in an assembly and not compiled each time

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
