### ISSUE TITLE
Sequence Generator parallel transaction

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#794]
Hi,

with Version 20.1.802.0 I got an error in an existing project with the sequence generator.

I had an persistent class that got i sequenced number by the sequence generator. The object has validation rules (the name should not by empyt).

**No error:**
I create a new object, save  and there is no validation error => the sequence is set

**Error**
I create a new object, save and there is a validation error. I correct the validation, save (2nd time) and the application is lost in everlasting loop (till the log burst the hard disk)

This is the error log
	Type:       InvalidOperationException
	Message:    SqlConnection unterstützt keine parallelen Transaktionen.
	Data:       0 entries
	Stack trace:

   bei System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   bei System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   bei System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   bei System.Data.Common.DbConnection.System.Data.IDbConnection.BeginTransaction()
   bei DevExpress.Xpo.DB.ConnectionProviderSql.ConnectionBeginTransaction(Object il)
   bei DevExpress.Xpo.DB.ConnectionProviderSql.BeginTransactionCore(Object il)
   bei DevExpress.Xpo.DB.ConnectionProviderSql.DoInternal(String command, Object args)
   bei DevExpress.Xpo.DB.ConnectionProviderSql.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.DB.DataStoreForkBase.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.Helpers.BaseDataLayer.Do(String command, Object args)
   bei DevExpress.Xpo.Helpers.BaseDataLayer.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.Helpers.DataLayerWrapperS18452.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.SimpleObjectLayer.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.Session.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.ExplicitUnitOfWork.<BeginTransaction>b__8_0()
   bei DevExpress.Xpo.Logger.LogManager.Log(String category, LogHandlerVoid handler, MessageHandler`1 createMessageHandler, ExceptionHandler exceptionHandler)
   bei DevExpress.Xpo.ExplicitUnitOfWork.BeginTransaction()
   bei DevExpress.Xpo.ExplicitUnitOfWork.BeginFlushChanges()
   bei DevExpress.Xpo.Session.FlushChanges()
   bei Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.GenerateSequences(ExplicitUnitOfWork explicitUnitOfWork, Object theObject, Type sequenceStorageType) in D:\a\1\s\src\Modules\SequenceGenerator\SequenceGeneratorService.cs:Zeile 244.
   bei Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass27_0.<GenerateSequences>b__0() in D:\a\1\s\src\Modules\SequenceGenerator\SequenceGeneratorService.cs:Zeile 224.
   bei System.Reactive.Linq.ObservableImpl.Defer`1._.Run() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Defer.cs:Zeile 38.
	InnerException is null

--------------------------------------------------------------------------------
Loaded assemblies
.......
================================================================================

Ausnahme ausgelöst: "System.InvalidOperationException" in System.Data.dll
Ausnahme ausgelöst: "System.InvalidOperationException" in DevExpress.Data.v20.1.dll
Ausnahme ausgelöst: "System.InvalidOperationException" in DevExpress.Data.v20.1.dll
Ausnahme ausgelöst: "System.InvalidOperationException" in DevExpress.Xpo.v20.1.dll
Ausnahme ausgelöst: "System.InvalidOperationException" in Xpand.XAF.Modules.SequenceGenerator.dll
iXISXRM.Win.exe Error: 0 : 30.10.20 15:34:13.028	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    SqlConnection unterstützt keine parallelen Transaktionen.
	Data:       0 entries
	Stack trace:

   bei System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   bei System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   bei System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   bei System.Data.Common.DbConnection.System.Data.IDbConnection.BeginTransaction()
   bei DevExpress.Xpo.DB.ConnectionProviderSql.ConnectionBeginTransaction(Object il)
   bei DevExpress.Xpo.DB.ConnectionProviderSql.BeginTransactionCore(Object il)
   bei DevExpress.Xpo.DB.ConnectionProviderSql.DoInternal(String command, Object args)
   bei DevExpress.Xpo.DB.ConnectionProviderSql.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.DB.DataStoreForkBase.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.Helpers.BaseDataLayer.Do(String command, Object args)
   bei DevExpress.Xpo.Helpers.BaseDataLayer.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.Helpers.DataLayerWrapperS18452.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.SimpleObjectLayer.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.Session.DevExpress.Xpo.Helpers.ICommandChannel.Do(String command, Object args)
   bei DevExpress.Xpo.ExplicitUnitOfWork.<BeginTransaction>b__8_0()
   bei DevExpress.Xpo.Logger.LogManager.Log(String category, LogHandlerVoid handler, MessageHandler`1 createMessageHandler, ExceptionHandler exceptionHandler)
   bei DevExpress.Xpo.ExplicitUnitOfWork.BeginTransaction()
   bei DevExpress.Xpo.ExplicitUnitOfWork.BeginFlushChanges()
   bei DevExpress.Xpo.Session.FlushChanges()
   bei Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.GenerateSequences(ExplicitUnitOfWork explicitUnitOfWork, Object theObject, Type sequenceStorageType) in D:\a\1\s\src\Modules\SequenceGenerator\SequenceGeneratorService.cs:Zeile 244.
   bei Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass27_0.<GenerateSequences>b__0() in D:\a\1\s\src\Modules\SequenceGenerator\SequenceGeneratorService.cs:Zeile 224.
   bei System.Reactive.Linq.ObservableImpl.Defer`1._.Run() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Defer.cs:Zeile 38.
	InnerException is null

**Comment by CWolffIF** [comment]
Hi Tolis,

here is a sample.
![Sequence](https://user-images.githubusercontent.com/43132306/97774597-7beb7580-1b59-11eb-8d53-363355a04e5b.gif)
[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/5468761/Solution1.zip)

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by CWolffIF** [comment]
Hi Tolis,
sorry, but now it´s getting urgent. What can I do to support you?

**Comment by xblazor** [comment]
the fix is already included in sources however the build did not pass yet
[Generate_Sequence_When_Error_Inside_transaction #794](https://github.com/eXpandFramework/DevExpress.XAF/commit/3fa5f30527f27eea76f4b842abe340fe62000769)
, if u want to support me extra and buy a few hours priority choose a better tier with hrs and get my skype from my profile or mail so we can track the works in private. For this case I do not think u need extra support though once th build pass u will have it

**Comment by apobekiaris** [comment]
the fix is already included in sources however the build did not pass yet
[Generate_Sequence_When_Error_Inside_transaction #794](https://github.com/eXpandFramework/DevExpress.XAF/commit/3fa5f30527f27eea76f4b842abe340fe62000769)
, if u want to support me extra and buy a few hours priority choose a better tier with hrs and get my skype from my profile or mail so we can track the works in private. For this case I do not think u need extra support though once th build pass u will have it

**Comment by CWolffIF** [comment]
Thanx for the reply. At first step I think we go to the next tier.

**Comment by apobekiaris** [comment]
how i usually work with tiers is that interested party buy hrs and we consume when needed, so it kind of stashing the hrs until u need them with an expiration of 1 month as subriptions are month based.

**Comment by apobekiaris** [comment]
or of course what other u have in mind, just ask and we can find a solution I am can do attitude

**Comment by apobekiaris** [comment]
SequenceGenerator v2.202.60.4 in the lab is ready for testing

**Comment by expand** [comment]
eXpand.lab release [20.2.302.2](https://github.com/eXpandFramework/eXpand.lab/releases/20.2.302.2) includes commit that relate to this task:

* [Bump Standalone package version #794](https://github.com/eXpandFramework/eXpand.lab/commit/b711bf9ded41ae9f08faac1f1dd51cce6a931ee4)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.
