### ISSUE TITLE
Visual Studio hangs on opening Model Editor with Dashboard module

### ISSUE THREAD

**Issue by nurbed** [eXpandFramework/eXpand#799]
After many attemps to find the problem in my main project, I created a new project from scratch an I found the problem...
- I created a new XAF Solution (20.1.8, winform only, xpo only, all the defaults module installed)
- I added the eXpand Dashboard module (20.1.802)
After the first build, I opened the model editor and... Visual Studio hangs
I tried looking for some error codes but without success. Debugging from another VS instance also didn't give me info...

**Comment by apobekiaris** [comment]
please see this case which is still open unfortunately but maybe some advice there helps

**Comment by apobekiaris** [comment]
#790

**Comment by nurbed** [comment]
Ops, sorry... I searched for "dashboard" among the issues but I didn't find anything.
So, I found the problem by adding the dashboard module. I tried a little bit of everything to circumscribe it (VS in admin mode, with or without the expand extension enabled, with and without the installation of the other expand modules)

**Comment by apobekiaris** [comment]
however XpandModelEditor works as the other user reports, does not for u?

**Comment by nurbed** [comment]
I tried to debug the VS instance of the "small" project instead that of the main, and the Exception throwed is

System.NullReferenceException  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace: <Cannot evaluate the exception stack trace>
in the xpand reactive dll

the XpandModelEditor works...

**Comment by apobekiaris** [comment]
the exception says nothing it most probably some side effect

**Comment by nurbed** [comment]
I try to look for some more information

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
