### ISSUE TITLE
Mono Cecil 0.11.3

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#805]
Hi,

after Update to eXpand 20.2.304 and compiling, I got the error that XpandSecurityModule needs MonoCecil 0.11.3. But with the expand package MonoCecil 0.11.2 is installed.

Update MonoCecil to 0.11.3 as Nuget solves the problem.

Maybe it is a simple correction in the rferences.

![image](https://user-images.githubusercontent.com/43132306/99149941-76317c00-2691-11eb-8c77-0828aa2a872d.png)

**Comment by apobekiaris** [comment]
true with .NET5 there were many works on the dependencies and I missed this one, its on my todo though to automate it :)

**Comment by apobekiaris** [comment]
eXpand.lab release [20.2.302.6](https://github.com/eXpandFramework/eXpand.lab/releases/20.2.302.6) includes commit that relate to this task:

* [Mono Cecil 0.11.3 #805](https://github.com/eXpandFramework/eXpand.lab/commit/a0bca9f1abbed00ba6e8614750e8cb2f7a0e17df)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.
