### ISSUE TITLE
PositionInListView

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#806]
Hi,

updating the Model in my agnostic project I got thr error:

------- Updating model differences: Project: C:\DevProjects\iXISIF\iXISXRM.Module\iXISXRM.Module.csproj
Error:
Exception occurs while initializing the 'Xpand.XAF.Modules.PositionInListview.PositionInListViewModule' module: Unable to create an instance of the "MoveObjectUpActionViewController" type.
Reason: "Der angegebene Schlüssel war nicht im Wörterbuch angegeben."
Update failed

**Comment by CWolffIF** [comment]
After I cleared the caches and build all new the error changed to:
------- Updating model differences: Project: C:\DevProjects\iXISIF\iXISXRM.Module\iXISXRM.Module.csproj
Error:
Die Datei oder Assembly "ActionsAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Update failed

I know nothing about an "ActionsAssembly" and the program runs. Any idea?

**Comment by CWolffIF** [comment]
Sorry, wrong message above. The error is still the same 'Xpand.XAF.Modules.PositionInListview.PositionInListViewModule' module: Unable to create an instance of the "MoveObjectUpActionViewController" type.


   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
----------InnerException----------
Unable to create an instance of the "MoveObjectUpActionViewController" type.
Reason: "Der angegebene Schlüssel war nicht im Wörterbuch angegeben."
----------StackTrace----------
   bei DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   bei DevExpress.ExpressApp.Controller.Create(Type controllerType)
   bei Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.<>c__DisplayClass86_0`2.<RegisterAction>b__0(IObserver`1 observer)
   bei System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer)
   bei System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   bei System.Reactive.ExceptionHelpers.Throw(Exception exception)
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   bei System.Reactive.ObserverBase`1.OnError(Exception error)
   bei Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass15_1`1.<Trace>b__3(Exception e)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error)
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   bei System.Reactive.ObserverBase`1.OnError(Exception error)
   bei Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass15_1`1.<Trace>b__3(Exception e)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Subjects.Subject`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   bei System.Reactive.ObserverBase`1.OnError(Exception error)
   bei Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass15_1`1.<Trace>b__3(Exception e)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   bei System.Reactive.ObserverBase`1.Fail(Exception error)
   bei System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   bei System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.SubscribeInner(IObservable`1 inner)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler)
   bei System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.<>c.<Run>b__3_0(IScheduler innerScheduler, _ this)
   bei System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   bei System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   bei System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   bei System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   bei System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
   bei System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   bei System.Reactive.Producer`2.Subscribe(IObserver`1 observer)
   bei System.ObservableExtensions.Subscribe[T](IObservable`1 source)
   bei Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.Subscribe[T](IObservable`1 source, ModuleBase moduleBase)
   bei Xpand.XAF.Modules.PositionInListview.PositionInListViewModule.Setup(ApplicationModulesManager moduleManager)
   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
----------InnerException----------
Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
----------StackTrace----------
   bei System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   bei Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.Notify(Controller controller)
   bei MoveObjectUpActionViewController..ctor()
   bei Create_MoveObjectUpActionViewController()
   bei DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)

**Comment by apobekiaris** [comment]
without a repro sample I can only suggest to unload the PositionInListView as per module wiki

**Comment by CWolffIF** [comment]
Sorry but the
Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.PositionInListview.PositionInListViewModule));
did not work. Same error in converted projects. I did not use the "PositionInListviewModule" in the projects.

**Comment by apobekiaris** [comment]
Create a new empty xaf solution, add to the RequiredTypesCollection the Xpand module that u use and when u repro it post the solution, worth a try I think
