### ISSUE TITLE
Security 20.1 in 20.2.304

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#807]
Hi,
building my project with 20.2.304.0 and test it on an empty system it did not start and I got the error in fuslogvw

*** Protokolleintrag für Assembly-Binder  (15.11.2020 @ 12:34:47) ***

Fehler bei diesem Vorgang.
Ergebnis der Bindung: hr = 0x80070002. Das System kann die angegebene Datei nicht finden.

Der Assemblymanager wurde geladen aus:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Als EXE-Datei ausgeführt.  C:\DevProjects\iXISIF\iXISXRM.Win\bin\Release\iXISXRM.Win.exe
--- Ein detailliertes Fehlerprotokoll folgt. 

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = DevExpress.ExpressApp.Security.v20.1
 (Partial)
WRN: Für eine Assembly wurden partielle Bindungsinformationen bereitgestellt:
WRN: Assemblyname: DevExpress.ExpressApp.Security.v20.1 | Domänen-ID: 1
WRN: Eine partielle Bindung tritt auf, wenn nur ein Teil des Assemblyanzeigenamens bereitgestellt wird.
WRN: Dies führt möglicherweise dazu, dass die Sammelmappe eine falsche Assembly lädt.
WRN: Geben Sie die Textidentität der Assembly mit allen Einzelheiten an. 
WRN: Dazu gehören der einfache Name, die Version und Kultur und das öffentliche Schlüsseltoken.
WRN: Weitere Informationen und allgemeine Lösungen für dieses Problem finden Sie im Whitepaper unter "http://go.microsoft.com/fwlink/?LinkId=109270".
LOG: Appbase = file:///C:/DevProjects/iXISIF/iXISXRM.Win/bin/Release/
LOG: Ursprünglicher PrivatePath = NULL
LOG: DynamicBase = NULL
LOG: CacheBase = NULL
LOG: AppName = iXISXRM.Win.exe
Aufruf von Assembly : (Unknown).
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\DevProjects\iXISIF\iXISXRM.Win\bin\Release\iXISXRM.Win.exe.Config
LOG: Die Hostkonfigurationsdatei wird verwendet: 
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config wird verwendet.
LOG: Die Richtlinie wird derzeit nicht auf den Verweis angewendet (private, benutzerdefinierte, teilweise oder pfadbasierte Assemblybindung)
LOG: Download von neuem URL file:///C:/DevProjects/iXISIF/iXISXRM.Win/bin/Release/DevExpress.ExpressApp.Security.v20.1.DLL.
LOG: Download von neuem URL file:///C:/DevProjects/iXISIF/iXISXRM.Win/bin/Release/DevExpress.ExpressApp.Security.v20.1/DevExpress.ExpressApp.Security.v20.1.DLL.
LOG: Download von neuem URL file:///C:/DevProjects/iXISIF/iXISXRM.Win/bin/Release/DevExpress.ExpressApp.Security.v20.1.EXE.
LOG: Download von neuem URL file:///C:/DevProjects/iXISIF/iXISXRM.Win/bin/Release/DevExpress.ExpressApp.Security.v20.1/DevExpress.ExpressApp.Security.v20.1.EXE.
LOG: Fehler bei allen Such-URLs.

**Comment by apobekiaris** [comment]
i understand there is a problem but this stack does not help much, 

>DevExpress.ExpressApp.Security.v20.1

how to tell why this happens? possible multiple assemlies in path? cache clean up?

what is needed is a repro sample as i suggested b4

**Comment by CWolffIF** [comment]
I addressed it to Devexpress

**Comment by vimarx** [comment]
may be related to #800  ?

**Comment by vimarx** [comment]
@CWolffIF  any news on this issue? I cannot migrate to 20.2.3 because of open issues, and one of those is about 20.1 assemblies been mixed with 20.2

**Comment by apobekiaris** [comment]
I am not researching the case as I do not have a way to repro it. The exception complains about a version conflict so I would try to see if there is one and where. So maybe the `Get-ReferenceConfict` powershell command in your bin can tell us more about the Security assembly?

**Comment by CWolffIF** [comment]
@vimarx : I can not repro it with a new empty solution. 2 of my converted projects do have this behaviour, but the applications do run. An we go with the projects in live production.

I addressed it to devexpress and they say that there is maybe an error in updateconversion. But I do not believe so. I will try to research it with Get-ReferenceConflict like Tolis said if I got a little bit more time.

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/XpandPwsh/wiki/Get-ReferenceConflict

**Comment by vimarx** [comment]
> @vimarx : I can not repro it with a new empty solution. 2 of my converted projects do have this behaviour, but the applications do run. An we go with the projects in live production.
> 
> I addressed it to devexpress and they say that there is maybe an error in updateconversion. But I do not believe so. I will try to research it with Get-ReferenceConflict like Tolis said if I got a little bit more time.

@CWolffIF  are they running in production without problem? web or win?

**Comment by CWolffIF** [comment]
@vimarx in production without problem. Both projects are win.

**Comment by vimarx** [comment]
thanks, @CWolffIF , my pending issues are web-related, because of version mix in web #800 , I will try again with @apobekiaris  suggestion as soon as my work day ends.

**Comment by CWolffIF** [comment]
I´ve done the Get-ReferenceConflict, but there seems to be no conflict with any 20.1 Version.

```
PS C:\WINDOWS\system32> get-referenceconflict -path "C:\DevProjects\iXISIF\iXISXRM.Win\bin\Debug"

Key                                             Conflicts
---                                             ---------
mscorlib                                        {{ Assembly = 0Harmony, Version=2.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Reference = mscorlib, Version=4…
Mono.Cecil                                      {{ Assembly = 0Harmony, Version=2.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Reference = Mono.Cecil, Version…
System.Core                                     {{ Assembly = 0Harmony, Version=2.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Reference = System.Core, Versio…
System                                          {{ Assembly = 0Harmony, Version=2.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Reference = System, Version=4.0…
System.Drawing                                  {{ Assembly = AForge.Imaging, Version=2.2.5.0, Culture=neutral, PublicKeyToken=ba8ddea9676ca48b, Reference = System.Drawin…
System.Data                                     {{ Assembly = AutoMapper.Net4, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005, Reference = System.Data,…
System.Xml                                      {{ Assembly = Common.Logging, Version=2.1.2.0, Culture=neutral, PublicKeyToken=af08829b84f0328e, Reference = System.Xml, V…
System.Security                                 {{ Assembly = DevExpress.Docs.v20.2, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Reference = Syste…
System.Web                                      {{ Assembly = DevExpress.ExpressApp.Web.v20.2, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Referen…
System.Net.Http                                 {{ Assembly = DevExpress.Xpo.v20.2, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, Reference = System…
Microsoft.CodeAnalysis                          {{ Assembly = DevExpress.XtraReports.v20.2.CodeCompletion, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e…
Microsoft.CodeAnalysis.CSharp                   {{ Assembly = DevExpress.XtraReports.v20.2.CodeCompletion, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e…
System.Collections.Immutable                    {{ Assembly = DevExpress.XtraReports.v20.2.CodeCompletion, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e…
Newtonsoft.Json                                 {{ Assembly = Google.Apis.Auth, Version=1.49.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab, Reference = Newtonsoft…
System.Memory                                   {{ Assembly = Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad, Reference = System.Memory,…
System.Buffers                                  {{ Assembly = Grpc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad, Reference = System.Buffers, Ve…
System.DirectoryServices                        {{ Assembly = iXISXRM.Module, Version=20.2.3.1007, Culture=neutral, PublicKeyToken=null, Reference = System.DirectoryServi…
System.Threading.Tasks.Extensions               {{ Assembly = MagicOnion, Version=2.6.3.0, Culture=neutral, PublicKeyToken=7bf5b512f16761c0, Reference = System.Threading.…
System.Runtime.CompilerServices.Unsafe          {{ Assembly = MagicOnion, Version=2.6.3.0, Culture=neutral, PublicKeyToken=7bf5b512f16761c0, Reference = System.Runtime.Co…
System.IdentityModel                            {{ Assembly = Microsoft.Exchange.WebServices.Auth, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Ref…
System.ValueTuple                               {{ Assembly = Microsoft.Graph.Core, Version=1.22.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Reference = System…
Microsoft.IdentityModel.Tokens                  {{ Assembly = Microsoft.IdentityModel.JsonWebTokens, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Re…
Microsoft.IdentityModel.Protocols               {{ Assembly = Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad…
System.IdentityModel.Tokens.Jwt                 {{ Assembly = Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad…
Microsoft.IdentityModel.Protocols.OpenIdConnect {{ Assembly = Microsoft.Owin.Security.OpenIdConnect, Version=4.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Re…
Common.Logging                                  {{ Assembly = Quartz, Version=2.2.4.400, Culture=neutral, PublicKeyToken=f6b8c98a402cc8a4, Reference = Common.Logging, Ver…
System.Reactive                                 {{ Assembly = reactive-extensions, Version=0.0.27.0, Culture=neutral, PublicKeyToken=81fee42a89ec3c71, Reference = System.…
```

**Comment by apobekiaris** [comment]
hmm try this call

```ps1
Get-ChildItem *.dll|Get-AssemblyReference|sls 20.1
```

**Comment by apobekiaris** [comment]
```ps1
Get-ChildItem $path *.dll|Get-AssemblyReference|sls 20.1
```

**Comment by CWolffIF** [comment]
Got errors

```
PS C:\WINDOWS\system32> Get-ChildItem "C:\DevProjects\iXISIF\iXISXRM.Win\bin\debug" *.dll|Get-AssemblyReference|sls 20.1
Exception calling "ReadAssembly" with "2" argument(s): "Format of the executable (.exe) or library (.dll) is invalid."
At C:\Users\CWolff\Documents\PowerShell\Modules\XpandPwsh\1.202.46.4\public\DotNet\Read-AssemblyDefinition.ps1:23 char:9
+         [Mono.Cecil.AssemblyDefinition]::ReadAssembly($Path,$p)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : BadImageFormatException

You cannot call a method on a null-valued expression.
At C:\Users\CWolff\Documents\PowerShell\Modules\XpandPwsh\1.202.46.4\public\DotNet\Get-AssemblyReference.ps1:21 char:13
+             [PSCustomObject]@{
+             ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CWolff\Documents\PowerShell\Modules\XpandPwsh\1.202.46.4\public\DotNet\Get-AssemblyReference.ps1:55 char:9
+         $assembly.dispose()
+         ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "ReadAssembly" with "2" argument(s): "Format of the executable (.exe) or library (.dll) is invalid."
At C:\Users\CWolff\Documents\PowerShell\Modules\XpandPwsh\1.202.46.4\public\DotNet\Read-AssemblyDefinition.ps1:23 char:9
+         [Mono.Cecil.AssemblyDefinition]::ReadAssembly($Path,$p)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : BadImageFormatException

You cannot call a method on a null-valued expression.
At C:\Users\CWolff\Documents\PowerShell\Modules\XpandPwsh\1.202.46.4\public\DotNet\Get-AssemblyReference.ps1:21 char:13
+             [PSCustomObject]@{
+             ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CWolff\Documents\PowerShell\Modules\XpandPwsh\1.202.46.4\public\DotNet\Get-AssemblyReference.ps1:55 char:9
+         $assembly.dispose()
+         ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by apobekiaris** [comment]
yeah maybe u have some native dll also there, I assume you already search your files especial the config for 20.1
