### ISSUE TITLE
VS Crash When Xpand.VSIX is enabled

### ISSUE THREAD

**Issue by mbogaerts** [eXpandFramework/eXpand#812]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
When Xpand.VSIX is enable frequent crashes occur in VS 2019. (latest version of both VSIX and VS)
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲 (lastest crash)
1. Open Xpand Settings > Load Referenced Projects -> Search Selected
2. Crash!
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
from this data i cannot suggest much however it is super easy to load the one VSIX project (Xpand/Xpand.Plugins/Xpand.Plugins.csproj) in VS hit F5 and see if u can repro it with the debugger attached.

**Comment by mbogaerts** [comment]
I know…

VS just exits just thrown it in so maybe you had a quick fix for me :-).
it seems to be an access violation of some kind  as the eventviewer tells me…
not enough info to share and to get serious here.

[cid:image002.jpg@01D6C1DB.0D0C3230]

**Comment by apobekiaris** [comment]
u missed the image, and I already had a look and on my side works fine, not have similar reports also. Anyway running the project debugger will most probably crash on the line

**Comment by mbogaerts** [comment]
I’ll keep you posted if I find anything

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
