### ISSUE TITLE
How can I debug this?

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#816]
From time to time, I found this exception in production environment (web app), any help to debug it?

System.ArgumentException: Nombre de tipo duplicado en un ensamblado.
en System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
en System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
en System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
en System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent)
en Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.NewControllerType[T](String id) en D:\a\1\s\src\Modules\Reactive\Services\Actions\RegisterAction.cs:línea 170
en Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.RegisterAction[TController,TAction](ApplicationModulesManager applicationModulesManager, String id, Func`2 actionBase) en D:\a\1\s\src\Modules\Reactive\Services\Actions\RegisterAction.cs:línea 147
en Xpand.XAF.Modules.PositionInListview.SwapPositionInListViewService.<>c__DisplayClass4_0.b__0(String actionnId) en D:\a\1\s\src\Modules\PositionInListview\SwapPositionInListViewService.cs:línea 33
en System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)
WEB
Void CheckTypeNameConflict(System.String, System.Type)
en System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
en System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
en System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
en System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent)
en Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.NewControllerType[T](String id) en D:\a\1\s\src\Modules\Reactive\Services\Actions\RegisterAction.cs:línea 170
en Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.RegisterAction[TController,TAction](ApplicationModulesManager applicationModulesManager, String id, Func`2 actionBase) en D:\a\1\s\src\Modules\Reactive\Services\Actions\RegisterAction.cs:línea 147
en Xpand.XAF.Modules.PositionInListview.SwapPositionInListViewService.<>c__DisplayClass4_0.b__0(String actionnId) en D:\a\1\s\src\Modules\PositionInListview\SwapPositionInListViewService.cs:línea 33
en System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)

**Comment by apobekiaris** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
replace this assembly and let me know the results

[Xpand.XAF.Modules.Reactive.zip](https://github.com/eXpandFramework/eXpand/files/5628246/Xpand.XAF.Modules.Reactive.zip)

**Comment by apobekiaris** [comment]
to use it in dev u need to replace the files under C:\Users\User\.nuget\packages\xpand.xaf.modules.reactive\4.202.0\lib\netstandard2.0\

**Comment by vimarx** [comment]
Thanks Tolis, the issue is in seen in production, may I replace directly in the bin directory?

**Comment by apobekiaris** [comment]
yes assuming u use the same version

**Comment by apobekiaris** [comment]
this a quick test until a build is out

**Comment by vimarx** [comment]
not possible
The error occurred:

	Type:       MissingMethodException
	Message:    Método no encontrado: 'System.IObservable`1<System.ValueTuple`2<!!0,DevExpress.ExpressApp.IObjectSpace>> Xpand.XAF.Modules.Reactive.Services.ObjectSpaceExtensions.NewObject(DevExpress.ExpressApp.XafApplication, Boolean)'.
	Data:       0 entries
	Stack trace:

   en Xpand.XAF.Modules.PositionInListview.PositionInListViewService.<>c.<PositionNewObjects>b__6_0(XafApplication application)
   en System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value)
	InnerException is null

**Comment by apobekiaris** [comment]
sorry u have to wait for the build

**Comment by vimarx** [comment]
may be related to #817 ?

**Comment by apobekiaris** [comment]
nope if may be possible two different threads to access that code causing this behaviour a simple lock will tell us

**Comment by apobekiaris** [comment]
I did not update u here but the problem should be fixed right?

**Comment by vimarx** [comment]
I don't see it in the latest production logs, so we can close it for now
