### ISSUE TITLE
NullReferenceException in authenticate

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#817]
I have this issue in production in a web app, it is difficult to catch in a debug environment.

Objectspace is not Null , login parameters also aren't null,
How can I go deeper? 

this issue is not new (a couple of months at least), and it is making me crazy...
Thanks.

**System.NullReferenceException**: Referencia a objeto no establecida como instancia de un objeto.
en DevExpress.ExpressApp.Security.AuthenticationStandard.Authenticate(IObjectSpace objectSpace)
en ClasesBase.AuthenticationStandardApp.Authenticate(IObjectSpace objectSpace)
en DevExpress.ExpressApp.Security.SecurityStrategyBase.Logon(IObjectSpace objectSpace)
en DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
en DevExpress.ExpressApp.XafApplication.showLogonAction_OnExecute(Object sender, PopupWindowShowActionExecuteEventArgs args)
en DevExpress.ExpressApp.Actions.PopupWindowShowAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
WEB
System.Object Authenticate(DevExpress.ExpressApp.IObjectSpace)
en DevExpress.ExpressApp.Security.AuthenticationStandard.Authenticate(IObjectSpace objectSpace)
en ClasesBase.AuthenticationStandardApp.Authenticate(IObjectSpace objectSpace)
en DevExpress.ExpressApp.Security.SecurityStrategyBase.Logon(IObjectSpace objectSpace)
en DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
en DevExpress.ExpressApp.XafApplication.showLogonAction_OnExecute(Object sender, PopupWindowShowActionExecuteEventArgs args)
en DevExpress.ExpressApp.Actions.PopupWindowShowAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
do u use the MS Office packages?

**Comment by vimarx** [comment]
not direct, may be some lost reference?

**Comment by apobekiaris** [comment]
if not then I would try to gather more info by overriding the XafApplication CreateLogonObjectSpace which is the one that returns a null objectspace

```
		protected virtual IObjectSpace CreateLogonObjectSpace(Type objectType) {
			CheckCompatibility();
			IObjectSpace objectSpace = null;
			IObjectSpaceProvider objectSpaceProvider = GetObjectSpaceProvider(objectType);
			INonsecuredObjectSpaceProvider nonsecuredObjectSpaceProvider = objectSpaceProvider as INonsecuredObjectSpaceProvider;
			if(nonsecuredObjectSpaceProvider != null) {
				objectSpace = nonsecuredObjectSpaceProvider.CreateNonsecuredObjectSpace();
			}
			else {
				objectSpace = objectSpaceProvider?.CreateObjectSpace();
			}
			return objectSpace;
		}
```

**Comment by vimarx** [comment]
> do u use the MS Office packages?

Xpand Office or DX office?

**Comment by apobekiaris** [comment]
looking again at the GetObjectSpaceProvider method we see that is a Type location failure problem which tell us that something is wrong with our boot so i would verify that by check the type.Assembly,Location and AssemblyQualiedName

**Comment by apobekiaris** [comment]
i meant the Xpand MS packages

**Comment by apobekiaris** [comment]
so to clear my thoughs overrider the CreateLogonObjectSpace and when objectspace is null return the type.Assembly.Location, type.AssemblyQualiedName etc.

**Comment by apobekiaris** [comment]
and by return i really mean trace them in the log :)

**Comment by vimarx** [comment]
Thank @apobekiaris for your help, still monitoring logs for this problem.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
