### ISSUE TITLE
cant create XpandLogonParameters object

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#818]
This started returning null in 20.2

IObjectSpace os = Application.CreateObjectSpace();
XpandLogonParameters p = os.CreateObject<XpandLogonParameters>();

**Comment by apobekiaris** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by emeyke** [comment]
Here is the sample project.
Test action in Test Controller (in Win) demonstrates the issue.
https://www.dropbox.com/s/byfuvsn3tgzyi7z/XpandTestSolution.zip?dl=0

**Comment by apobekiaris** [comment]
>IObjectSpace os = Application.CreateObjectSpace();

avoid this overload in general and try to use this

```cs
IObjectSpace os = Application.CreateObjectSpace(typeof(XpandLogonParameters));
```

does it work?

**Comment by emeyke** [comment]
It works! 
Thanks,
Evgeniy
