### ISSUE TITLE
Typo in the ReadMe.txt of the Xpand.XAF.Web.All package

### ISSUE THREAD

**Issue by janhulsebosch** [eXpandFramework/eXpand#820]
RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.MasterDetail.MasterDetail**Mode**));

MasterDetail**Mode** should be MasterDetail**Module**

**Comment by apobekiaris** [comment]
the fixing commit is not yet published

https://github.com/eXpandFramework/DevExpress.XAF/commit/9a05de261c4f79da273559074f64117c7cdf1faa

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
