### ISSUE TITLE
Excel Importer Win - Cross Threaded Operation Detected

### ISSUE THREAD

**Issue by ndamgaard** [eXpandFramework/eXpand#824]
This has happened with all recent versions of the eXpandWin eXpanExcelImporter.Win and happened again today on a clean install on a new test project using version 20.2.402. Everything installs and compiles fine. When I attempt the import operation I get the following Cross Threaded Operation Detected error. The Excel spreadsheet contains about 8000 rows.

![SNAG-0001 2020-12-28 7 00 06 AM MX60PC](https://user-images.githubusercontent.com/210170/103216377-83ba6280-48db-11eb-99a7-5971bea99f5f.png)

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/eXpand/issues/337#issuecomment-470054856

**Comment by ndamgaard** [comment]
Thank you very much.

Niels

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
