### ISSUE TITLE
Could not load type 'DevExpress.ExpressApp.Utils.StringObject' from assembly 'DevExpress.ExpressApp.Xpo.v20.2, Version=20.2.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'.

### ISSUE THREAD

**Issue by cuongpv88** [eXpandFramework/eXpand#828]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
A clear and concise description

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
you can resolve such exceptions by making sure the complaint assembly is in the bin directory and you do not have conflicting binding redirects in your config.

I am interested to know your setup, do you have a sample?

**Comment by cuongpv88** [comment]
Thanks, i have solved the problem. How to use it for xaf blazor?

**Comment by apobekiaris** [comment]
use what for blazor?

**Comment by cuongpv88** [comment]
I want to use ExcelImporter & JobScheduler in Blazor

**Comment by apobekiaris** [comment]
JoScheduler will be available soon once this wiki is not empty I will announce in https://www.linkedin.com/groups/8984465/ or wait for the next release.

ExcelImporter supports WebForms, WinForms only for the moment.

**Comment by cuongpv88** [comment]
> JoScheduler sẽ có sẵn sớm một khi wiki này không phải là sản phẩm nào tôi sẽ [công bố trong https://www.linkedin.com/groups/8984465/ hoặc](https://www.linkedin.com/groups/8984465/) chờ đợi cho việc phát hành tiếp theo.
> 
> ExcelImporter hỗ trợ WebForms, WinForms chỉ cho thời điểm này.

Thanks

**Comment by apobekiaris** [comment]
The DevExpress.XAF repository modules that do not have a wiki are not consider released 

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/JobScheduler.Hangfire

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
