### ISSUE TITLE
Blazor Upload Module --> Bad requests

### ISSUE THREAD

**Issue by itahirikba** [eXpandFramework/eXpand#830]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
when i drag and drop the files, i have a error 400 bad request
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
take the sample project, create a expense and drag and drop files. See error with F12 in the browser. 

https://user-images.githubusercontent.com/57799686/104301766-4dc6d200-54c8-11eb-9d00-ec73a8e75e72.mp4

[Solution7.zip](https://github.com/eXpandFramework/eXpand/files/5801305/Solution7.zip)

**Comment by apobekiaris** [comment]
please replace your front end project dependecies with:

```xml
<PackageReference Include="DevExpress.ExpressApp.Core.All" Version="20.2.4" />
    <PackageReference Include="DevExpress.ExpressApp.Blazor.All" Version="20.2.4" />
    <PackageReference Include="Xpand.XAF.Web.All" Version="4.202.48" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.1" />
```

**Comment by apobekiaris** [comment]
prefer the container packages instead, unless you know what you are doing

**Comment by isatahiri** [comment]
thanks --> Works now
