### ISSUE TITLE
Xpand.XAF.Modules.JobScheduler.Hangfire.JobSchedulerModule

### ISSUE THREAD

**Issue by ndamgaard** [eXpandFramework/eXpand#831]
When triggering a scheduled event from my XAF application the default constructor in the following code is called and not the one that initializes the Blazor Application variable. I'm not clear on what I have done wrong.

using BlazorHangTest1.Module.BusinessObjects;
using DevExpress.ExpressApp.Blazor;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Xpand.Extensions.XAF.Xpo.ObjectSpaceExtensions;
using Xpand.XAF.Modules.JobScheduler.Hangfire;

namespace BlazorHangTest1.Module.Blazor
{
    [JobProvider]
    public class Import
    {
        public BlazorApplication Application { get; }
        public Import() { }
        public Import(BlazorApplication application)
        {
            Application = application;
        }

        public async Task DoSomething()
        {
            var objectSpace = Application.CreateObjectSpace();
            var order = objectSpace.CreateObject<Order>();

            order.OrderId = Convert.ToInt32(new Random(1000));

            await objectSpace.CommitChangesAsync();
        }

        //// [JobProvider("Customize-Name")]
        //public async Task DailyOrders()
        //{
        //    using var objectSpace = Application.CreateObjectSpace();
        //    for (int i = 0; i < 10; i++)
        //    {
        //        var order = objectSpace.CreateObject<Order>();
        //        order.OrderID = i;
        //    }
        //    await objectSpace.CommitChangesAsync();
        //}
    }
}

**Comment by apobekiaris** [comment]
What you posted is correct I cannot guess what else is missing in your solution, I suggest you download the explore TestBlazorApplication found at https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Tests/EasyTests/TestApplication/TestApplication.Blazor.Server

**Comment by apobekiaris** [comment]
Do u use the Trigger action? The default Cron Expression is set to yearly if I remember correctly meaning that the method will execute after one year. The default constructor is called immediately but the actually initialization is bound to the Cron Expression

**Comment by ndamgaard** [comment]
Yes. I have triggered it. But thank you and I will explore the test code.

**Comment by apobekiaris** [comment]
the testapplication consumes the nugets so u only have to compile the blazor project and nothing else. It configured to run in memory without DB, the video and the EasyTests run there. Additional unit tests are avalable at https://github.com/eXpandFramework/DevExpress.XAF/blob/master/src/Tests/JobScheduler.Hangfire/JobSchedulerTests.cs  

for e.g have a look at [Inject_BlazorApplication_In_JobType_Ctor](https://github.com/eXpandFramework/DevExpress.XAF/blob/master/src/Tests/JobScheduler.Hangfire/JobSchedulerTests.cs#L50-L65)

**Comment by ndamgaard** [comment]
I struggled with this all day and now I'm cross eyed.

If someone that really knows what they are doing could make a simple example XAF Blazor application, and share the source code, with this working it would sure be appreciated.

Thank you

**Comment by apobekiaris** [comment]
> but neither the stock or Xpand model editors will load.

unfortunately this means nothing, it a common error to people with not much experience not to detailed them selves. 

As more detailed as you are you increase the chances of getting an answer here. e.g. screenshot, logs, screencast etc.

**Comment by ndamgaard** [comment]
Noted. 

This is my first experience with free, open source software. It's fantastic for learning but not the best for production. I'll figure it out in time.

Thanks.

**Comment by apobekiaris** [comment]
also the this case looks resolved and u r not the author, so better idea is your author your own issues

**Comment by ndamgaard** [comment]
Here is the error I get when I try to use the built in XAF model editor:

Exception occurs while initializing the 'Xpand.XAF.Modules.Blazor.BlazorModule' module: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

And I get the following error when I try to load the Xpand model editor by double clicking on the Module List.

![SNAG-0000 1-13-2021 7 42 18 AM WKS-S0144](https://user-images.githubusercontent.com/210170/104459854-f0d42600-5572-11eb-897c-8a6ba6b84ed9.png)

**Comment by apobekiaris** [comment]
does the Blazor.Module model open? the front end project model is not supported currently

**Comment by ndamgaard** [comment]
Yes. The Blazor.Module loads with both module editors. I have installed Xpand.XAF.Web.All v4.202.48 in the .Server and .Blazor modules but not in the .Module

**Comment by apobekiaris** [comment]
in general it is best practice to create modules, meaning that the front end project is not a module and cannot be reused. Modifying the front end project model cannot be reused. The Blazor.Module model is reusable.

**Comment by ndamgaard** [comment]
Just to clarify do you mean I should not be installing Xpand nuget packages(or any other nuget packages) in the front end Blazor project? That's good to know. Thank you.

**Comment by apobekiaris** [comment]
no i did not say that, even if you u install in a module the dependecies are transitive so you will always have the front end project model not working 

at least until XpandModelEditor supports it.

**Comment by ndamgaard** [comment]
ok. I see what you were getting at

**Comment by apobekiaris** [comment]
also it should be possible to use the front end model as well if you create an extra module only for Xpand model configuration and add it to the front end project only from the configuration file dynamically.

This way all other mmodules know nothing about Xpand and any Xpand related problems are isolated only to that extra modules.

**Comment by ndamgaard** [comment]
Do you have an example anywhere that shows the best way to do that? It sounds like a great idea to me.

**Comment by apobekiaris** [comment]
nope I do not but it how XAF/.NET works nothing more nothing Xpand related

**Comment by apobekiaris** [comment]
the only advantage i see using the front end model though is the lazy modification, meaning after compile. However XAF also offers other means for that even at runtime without the need to restart the app as with Model.xafml

**Comment by ndamgaard** [comment]
Sounds good. I think I know what you mean.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
