### ISSUE TITLE
Could not load assembly 'System.ComponentModel.Annotations, Version=4.2.0.0..

### ISSUE THREAD

**Issue by maltedbarley** [eXpandFramework/eXpand#835]
Am using Devexpress.XAF and the ImportWizard module (source). Updated to latest DevExpress 20.2.4.0 and lifted the target framework to v4.8. Updated all expand related code as well. While having no build errors VS throws an exception on 
Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule telling me it can't find 
System.ComponentModel.Annotations Version=4.2.0.0 when running the application.

All projects are set to "auto-generate binding redirects" but there's no bindingRedirect in app.config for System.ComponentModel.Annotations.

Any ideas?

**Comment by apobekiaris** [comment]
is this assembly in your bin? is this runtime or design time?

**Comment by maltedbarley** [comment]
The dll is not in the application bin but both System.ComponentModel.Annotations and System.ComponentModel.DataAnnotations is in the GAC (v4.8). If I manually add System.ComponentModel.Annotations.dll to the application (the 4.4.1 version, which is .net 4.6 I believe) it throws another exception:

_Exception occurs while initializing the 'Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule' module: Attempt by method 'EnumsNET.EnumCache'2<TUnderlying,TUnderlyingOperations>.AsString(!0, EnumsNET.EnumFormat)' to access method 'EnumsNET.AttributeCollection.Get<System.ComponentModel.DataAnnotations.DisplayAttribute>()' failed._

(EnumsNET is also updated and should work.) The problem occurs when I try to start the application = runtime.

**Comment by apobekiaris** [comment]
post a sample please, I cannot tell

**Comment by maltedbarley** [comment]
An application sample or a sample from the log file?
Since I updated from .net 4.5 to 4.8 my first thoughts was that maybe there's some problem using 4.8 as the target framework together with eXpand fw.

**Comment by apobekiaris** [comment]
was it working b4? Xpand packages at least the main framework  >=net461 compatibility.

**Comment by maltedbarley** [comment]
Hi. It was working before with no problems. 
I have got passed the above problem (by downgrading the target framework, etc) but now face a similar issue with HarmonyLib getting referenced in two different versions somehow. The problem is probably due to the fact that the expand-lib zip is no longer distributed and because of that I have used the nuget packages for expand. These packages seems to have messed up the applications references (for DX references as well). Note that I use the source code for ImportWizard, and not the precompiled modules. 
I am not fully clear on the updating path for the framework when using this setup. It worked fine when the expand-lib was available for download.

**Comment by apobekiaris** [comment]
what do u find expandlib is not available ?

```ps1
find-nugetpackage eXpandlib

Id        Version
--        -------
eXpandLib 20.2.403
```

**Comment by maltedbarley** [comment]
I mean the xpand-lib zip file containing all dll's.

**Comment by apobekiaris** [comment]
we only support nuget currently, cause dependencies are hard to manage by your self and do not see the reason why you should even attempt it. I spent the majority of my time to support the nugets avoiding them u need to spent a lot of time as well

**Comment by apobekiaris** [comment]
having all dll in a zip also makes no sense and cannot work, cause there are packages for net461,net472,netstandard2.0,netstandard2.1, netcore3.1,net5.0 and blazor which they all have dependecies build specific for their frameworks.

Nugets are the solution to it and widely accepted.

**Comment by maltedbarley** [comment]
Sure, I use nuget packages all the time in other applications, but I got some weird errors in this Devex-application. And not to mention some of the packages downloads and messes with a lot of Devexpress packages as well that I already manage through the Devex Updater tool.

**Comment by maltedbarley** [comment]
However, I am troubleshooting/recreating the issue with a new application in order to have a bit cleaner testing ground.

**Comment by apobekiaris** [comment]
>I spent the majority of my time to support the nugets avoiding them u need to spent a lot of time as well

I feel your pain but cannot do much more, the projects are on Azure and their yml pipelines exist in the source and used to build. Therefore you could rebuild and modify all project in a fork of your own, at least in theory. 

I never attempt to build the DX sources although I have the sources and I am very experienced to it. I try to find a way to use them as they are published. They work for thousands I can sure make them work for me, same stands true for the Xpand nugets

**Comment by maltedbarley** [comment]
I don´t actually build the DX sources, only the expand ImportWizard source. I will probably find out what the problem is, just wanted to see if I could get any pointers or ideas. Otherwise it's ok to close the ticket.

**Comment by apobekiaris** [comment]
The pre-release [2.201.26.1](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/2.201.26.1) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: Blazor support #835](https://github.com/eXpandFramework/Reactive.XAF/commit/62cbf3159795cbe986d3e3c2ecdad8d9707bc005)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/tests'>Xpand.TestsLib.Net461 v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade'>Xpand.XAF.Modules.LookupCascade v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft'>Xpand.XAF.Modules.Office.Cloud.Microsoft v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.202.49.2</a></br> <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.202.49.2</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
