### ISSUE TITLE
Building source XVideoRental getting error

### ISSUE THREAD

**Issue by rajkamal0610** [eXpandFramework/eXpand#836]
while build XVideoRental project [source code v20.2.3] in VS2019, i got the below error 

The command "dotnet paket restore" exited with code 1.

Kindly help to build the source

**Comment by apobekiaris** [comment]
navigate to the XvideoRental directory and call the command again with the verbose param, it will tell u what is missing

 ```cs
dotnet paket restore -v
```

**Comment by apobekiaris** [comment]
note that u cannot build only the XVideoRental u should be all source instead

**Comment by rajkamal0610** [comment]
Hi,

i ran dotnet restore command, am getting error. for your reference i place the file.

Devexpress 20.2 installed folder as same as in the paket.dependencies

![Error](https://user-images.githubusercontent.com/8022900/105356503-8037a400-5c19-11eb-9dea-89d23990bd5d.jpg)

**Comment by apobekiaris** [comment]
the message is clear i think, u need to install xaf in the default dir or change the nuget paket sources

https://github.com/eXpandFramework/eXpand/blob/29714623d50f40b5e6e03271e6cf48d2686bb8a1/paket.dependencies#L1

**Comment by apobekiaris** [comment]
to buld xpand u do not required to install XAF u can also use your private dx nuget feed instead of c:\program...

**Comment by apobekiaris** [comment]
prefer installation however if u do not have experience in paket, if u change the paket.dependencies then paket will resolve again all packages and that might conflict cause new version fo the dependecies might be out

**Comment by rajkamal0610** [comment]
Hi,

Thanks for your guidance.

Devexpress installed in default directory only. Somehow packet dependencies not using the directory for downloading. But i changed the path to nuget private api url for restoring devexpress. Now it's working fine.


Thanks and Regards

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
