### ISSUE TITLE
Objectchangeworkflows throw for new objects

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#839]
1. Create a new object change workflow for    objectx and include getobjectbykey activity in your definition.
2. Set it to execute on the client and set active to true
3. Create new objectx and save.
4. You get an error.

Reason.
The workflow is invoked before the commit operation is completed. Meaning the object does not exist yet in the database. Using get objectbykey will throw.

Possible solutions.
1. Prevent invoking for new objects
2. Invoke after new object committed
3. Have some other way of passing new object to workflow.

**Comment by apobekiaris** [comment]
𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

please help me to label this case.

**Comment by apobekiaris** [comment]
is it a showstopper? it might be but if not spending 2-3 and manage to successfully reproduce it I do not know if it a problem of your configuration or about covid.

I am pretty sure u understand my point, such posts make my work look bad, you want help, your have to provide help as well any way u can.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
