### ISSUE TITLE
How to prevent regeneration of modelassembly?

### ISSUE THREAD

**Issue by james1o4timothy** [eXpandFramework/eXpand#842]
Hello,I am new to expand framework.
I created a new project added expand win all nugets.Then removed world creator modules from required module list.
Application runs but I noticed that modelassembly.DLL is always created even on subsequent runs in release mode.
Is this the expected behavior of expand or there is something wrong on my side?

**Comment by apobekiaris** [comment]
check the front end project once u use designers by default they register modules to the front end application, i recomend u never touch designers, they take initiatives that are hidden

**Comment by james1o4timothy** [comment]
I  manually registered the expand assemblies to my module project. They don't exist in the frontend project.
You labeled it world creator but I removed world creator modules and am not using them anywhere.
Just create a new project. Add expandWin nugets.I removed world creator because I don't plan to use it.

**Comment by apobekiaris** [comment]
hmm no expand does/should not mess up the default XAF behaviour, please provide a sample to be examined

**Comment by james1o4timothy** [comment]
[Sample.zip](https://github.com/eXpandFramework/eXpand/files/5914331/Sample.zip)

**Comment by apobekiaris** [comment]
prioritizing as:

09. ReproSample

note: researching this can take a while to users without active subscription

**Comment by apobekiaris** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by james1o4timothy** [comment]
Researched this issue and traced it to
Expand masterdetailmodule.
Checked the implementation and there is nothing wrong.The issue exists in earlier versions of expand.(went as far back as 18.2.7) they are just a little bit faster.avoiding the module prevents regeneration.With today's PCs apps will still start in less than 50 seconds with regeneration of the assembly. So I am closing the issue
