### ISSUE TITLE
Connect world creator to wcf datastoreservice instead of directdb

### ISSUE THREAD

**Issue by james1o4timothy** [eXpandFramework/eXpand#845]
Can I connect World creator on the client to a wcf DataStoreService instead of a direct database connection.

**Comment by apobekiaris** [comment]
In the past I had it working for WCF, however I cannot tell if now is possible as many have changed from all parts DX, Xpand, .NET. having stashed a few hours from my sposnors page https://github.com/sponsors/apobekiaris, I could research and provide a solution that fits your project needs,

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
