### ISSUE TITLE
SequenceGenerator not working after upgrading DX / eXpand

### ISSUE THREAD

**Issue by AndreasMock1** [eXpandFramework/eXpand#849]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
We have upgraded our solution from DX / eXpand 20.1.4 to use DX 20.2.5 respectively eXpand 20.2.503.
After the update, the sequence for the BOs being configured to use SequenceGenerator is not working anymore. 
Since the update requires change eXpand referencing to Nugets and we have to change this in our project, too, I have gone through the installation steps described in the Wiki, but with no success.

What can we do to find the reason it is not working anymore to fix it?

**Comment by apobekiaris** [comment]
> the sequence for the BOs being configured to use SequenceGenerator is not working anymore

what exactly does not work? try to be as descriptive as possible in the future? 

1. Did you looked at the log? is there an error when u save the object.
2. Can you try to reproduce it in a sample app? 

Note that the SequenceGenerator video found in its wiki page is also EasyTest for each build. I would start from that to make sure that in an empty app the video scenarion works.

**Comment by apobekiaris** [comment]
Or if you can sample me happy to research it

**Comment by AndreasMock1** [comment]
In a clean sample app it is working, in the migrated solution it seems that SequenceGenerator is not being triggered at all, according to the stack trace.

Attached both of the stack traces, one from the source version using version 20.1.4 before migration and the other using version 20.2.5 after migration happened.

[callstack_sequencegenerator_not_working_20_2_5.txt](https://github.com/eXpandFramework/eXpand/files/6008021/callstack_sequencegenerator_not_working_20_2_5.txt)
[callstack_sequencegenerator_working_20_1_4.txt](https://github.com/eXpandFramework/eXpand/files/6008022/callstack_sequencegenerator_working_20_1_4.txt)

**Comment by apobekiaris** [comment]
please post the loaded XAF modules as listed in your log

**Comment by apobekiaris** [comment]
some additional info for you to consider by looking at the source code. The SequenceGenerator supports only 

https://github.com/eXpandFramework/Reactive.XAF/blob/master/src/Modules/SequenceGenerator/SequenceGeneratorService.cs#L213
```cs
 public static IList<Type> SupportedDataStoreTypes { get; } = new List<Type>(){typeof(MSSqlConnectionProvider), typeof(BaseOracleConnectionProvider), typeof(MySqlConnectionProvider)};
```
passing this check the module should trace it self as per this method

https://github.com/eXpandFramework/Reactive.XAF/blob/a3d800c866a085fbc2c90c3241031e620899d2dd/src/Modules/SequenceGenerator/SequenceGeneratorService.cs#L215-L222

```cs
        private static IObservable<object> GenerateSequences(this IObservable<IObjectSpace> source, IDataLayer dataLayer,Type sequenceStorageType=null) 
            => source.WhenSupported().SelectMany(space => Observable.Defer(() => space.GetObjectForSave(dataLayer).SelectMany(e => e.GenerateSequences(sequenceStorageType))
                        .TakeUntil(space.WhenCommitted().Select(objectSpace => objectSpace)))
                    .RepeatWhen(observable => observable.Where(o => !space.IsDisposed).Do(o => {}))
                )
                .Select(o => o)
                .Do(SequenceSubject)
                .TraceSequenceGeneratorModule();
```

for tracing you require to install the Xpand.XAF.Modules.Reactive.Logger module, you can virify it works in your empty solution by looking the TraceEvent BO and then do the same for your main app.

**Comment by AndreasMock1** [comment]
Here the list from "Loaded Modules" view in application model:


Name	Version	Assembly Name
SystemModule	20.2.5.0	DevExpress.ExpressApp.v20.2
AuditTrailModule	20.2.5.0	DevExpress.ExpressApp.AuditTrail.v20.2
BusinessClassLibraryCustomizationModule	20.2.5.0	DevExpress.ExpressApp.Objects.v20.2
ChartModule	20.2.5.0	DevExpress.ExpressApp.Chart.v20.2
CloneObjectModule	20.2.5.0	DevExpress.ExpressApp.CloneObject.v20.2
ConditionalAppearanceModule	20.2.5.0	DevExpress.ExpressApp.ConditionalAppearance.v20.2
ValidationModule	20.2.5.0	DevExpress.ExpressApp.Validation.v20.2
KpiModule	20.2.5.0	DevExpress.ExpressApp.Kpi.v20.2
PivotChartModuleBase	20.2.5.0	DevExpress.ExpressAp.PivotChart.v20.2
PivotGridModule	20.2.5.0	DevExpress.ExpressApp.PivotGrid.v20.2
ReportsModuleV2	20.2.5.0	DevExpress.ExpressApp.ReportsV2.v20.2
ScriptRecorderModuleBase	20.2.5.0	DevExpress.ExpressApp.ScriptRecorder.v20.2
StateMachineModule	20.2.5.0	DevExpress.ExpressApp.StateMachine.v20.2
TreeListEditorsModuleBase	20.2.5.0	DevExpress.ExpressApp.TreeListEditors.v20.2
ViewVariantsModule	20.2.5.0	DevExpress.ExpressApp.ViewVariantsModule.v20.2
WorkflowModule	20.2.5.0	DevExpress.ExpressApp.Workflow.v20.2
FileAttachmentsWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.FileAttachment.Win.v20.2
HtmlPropertyEditorWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.HtmlPropertyEditor.Win.v20.2
SecurityXpoModule	20.2.5.0	DevExpress.ExpressApp.Security.Xpo.v20.2
SecurityModule	20.2.5.0	DevExpress.ExpressApp.Security.v20.2
SystemWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Win.v20.2
WorkflowWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Workflow.Win.v20.2
ReactiveModule	4.202.51.0	Xpand.XAF.Modules.Reactive
ModelViewInheritanceModule	4.202.51.0	Xpand.XAF.Modules.ModelViewInheritance
XpandSecurityModule	20.2.503.0	Xpand.ExpressApp.Security
LogicModule	20.2.503.0	Xpand.ExpressApp.Logic
MasterDetailModule	20.2.503.0	Xpand.ExpressApp.MasterDetail
MapViewModule	20.2.503.0	Xpand.ExpressApp.MapView
XpandViewVariantsModule	20.2.503.0	Xpand.ExpressApp.ViewVariants
CloneModelViewModule	4.202.51.0	Xpand.XAF.Modules.CloneModelView
ModelDifferenceModule	20.2.503.0	Xpand.ExpressApp.ModelDifference
XpandValidationModule	20.2.503.0	Xpand.ExpressApp.Validation
ModelArtifactStateModule	20.2.503.0	Xpand.ExpressApp.ModelArtifactState
XpandPivotChartModule	20.2.503.0	Xpand.ExpressApp.PivotChart
ViewEditModeModule	4.202.51.0	Xpand.XAF.Modules.ViewEditMode
ReactiveLoggerModule	4.202.51.0	Xpand.XAF.Modules.Reactive.Logger
DashboardModule	20.2.503.0	Xpand.ExpressApp.Dashboard
XpandReportsModule	20.2.503.0	Xpand.ExpressApp.Reports
SchedulerModuleBase	20.2.5.0	DevExpress.ExpressApp.Scheduler.v20.2
XpandSchedulerModule	20.2.503.0	Xpand.ExpressApp.Scheduler
XpandStateMachineModule	20.2.503.0	Xpand.ExpressApp.StateMachine
XpandTreeListEditorsModule	20.2.503.0	Xpand.ExpressApp.TreeListEditors
CloneMemberValueModule	4.202.51.0	Xpand.XAF.Modules.CloneMemberValue
HideToolBarModule	4.202.51.0	Xpand.XAF.Modules.HideToolBar
ProgressBarViewItemModule	4.202.51.0	Xpand.XAF.Modules.ProgressBarViewItem
RefreshViewModule	4.202.51.0	Xpand.XAF.Modules.RefreshView
PositionInListViewModule	4.202.51.0	Xpand.XAF.Modules.PositionInListView
SequenceGeneratorModule	4.202.51.0	Xpand.XAF.Modules.SequenceGenerator
ViewItemValueModule	4.202.51.0	Xpand.XAF.Modules.ViewItemValue
XpandSystemModule	20.2.503.0	Xpand.ExpressApp
AdditionalViewControlsModule	20.2.503.0	Xpand.ExpressApp.AdditionalViewControlsProvider
IOModule	20.2.503.0	Xpand.ExpressApp.IO
JobSchedulerModule	20.2.503.0	Xpand.ExpressApp.JobScheduler
JobSchedulerJobsModule	20.2.503.0	Xpand.ExpressApp.JobScheduler.Jobs
XpandWorkFlowModule	20.2.503.0	Xpand.ExpressApp.Workflow
XpandAuditTrailModule	20.2.503.0	Xpand.ExpressApp.AuditTrail
EmailModule	20.2.503.0	Xpand.ExpressApp.Email
XpandFileAttachmentsModule	20.2.503.0	Xpand.ExpressApp.FileAttachment
ImportWizardModule	20.2.503.0	Xpand.ExpressApp.ImportWizard
AutoCommitModule	4.202.51.0	Xpand.XAF.Modules.AutoCommit
SEE_4_UModule	1.0.7720.19346	SEE_4_U.Module
ChartWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Chart.Win.v20.2
PivotChartWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.PivotChart.Win.v20.2
PivotGridWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.PivotGrid.Win.v20.2
ReportsWindowsFormsModuleV2	20.2.5.0	DevExpress.ExpressApp.ReportsV2.Win.v20.2
ScriptRecorderWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.ScriptRecorder.Win.v20.2
TreeListEditorsWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.TreeListEditors.Win.v20.2
ValidationWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Validation.Win.v20.2
AdditionalViewControlsProviderWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.AdditionalViewControlsProvider.Win
ModelMapperModule	4.202.51.0	Xpand.XAF.Modules.ModelMapper
XpandChartWinModule	20.2.503.0	Xpand.ExpressApp.Chart.Win
ImportWizardWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.ImportWizard.Win
XpandTreeListEditorsWinModule	20.2.503.0	Xpand.ExpressApp.TreeListEditors.Win
IOWinModule	20.2.503.0	Xpand.ExpressApp.IO.Win
GridListEditorModule	4.202.51.0	Xpand.XAF.Modules.GridListEditor
XpandSystemWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.Win
MasterDetailWindowsModule	20.2.503.0	Xpand.ExpressApp.MasterDetail.Win
XpandSecurityWinModule	20.2.503.0	Xpand.ExpressApp.Security.Win
ModelDifferenceWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.ModelDifference.Win
XpandPivotChartWinModule	20.2.503.0	Xpand.ExpressApp.PivotChart.Win
XpandPivotGridWinModule	20.2.503.0	Xpand.ExpressApp.PivotGrid.Win
ReportsModule	20.2.5.0	DevExpress.ExpressApp.Reports.v20.2
ReportsWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Reports.Win.v20.2
XpandReportsWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.Reports.Win
SchedulerWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Scheduler.Win.v20.2
XpandSchedulerWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.Scheduler.Win
XpandValidationWinModule	20.2.503.0	Xpand.ExpressApp.Validation.Win
WizardUIWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.WizardUI.Win
DashboardWindowsFormsModule	20.2.503.0	Xpand.ExpressApp.XtraDashboard.Win
MasterDetailModule	4.202.51.0	Xpand.XAF.Modules.MasterDetail
GoogleModule	4.202.51.0	Xpand.XAF.Modules.Office.Cloud.Google
GoogleCalendarModule	4.202.51.0	Xpand.XAF.Modules.Office.Cloud.Google.Calendar
GoogleTasksModule	4.202.51.0	Xpand.XAF.Modules.Office.Cloud.Google.Tasks
MicrosoftModule	4.202.51.0	Xpand.XAF.Modules.Office.Cloud.Microsoft
MicrosoftCalendarModule	4.202.51.0	Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar
MicrosoftTodoModule	4.202.51.0	Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo
OfficeModule	20.2.5.0	DevExpress.ExpressApp.Office.v20.2
SuppressConfirmationModule	4.202.51.0	Xpand.XAF.Modules.SuppressConfirmation
DocumentStyleManagerModule	4.202.51.0	Xpand.XAF.Modules.Office.DocumentStyleManager
OneViewModule	4.202.51.0	Xpand.XAF.Modules.OneView
ViewWizardModule	4.202.51.0	Xpand.XAF.Modules.ViewWizard
SEE_4_UWindowsFormsModule	1.0.7720.19352	SEE_4_U.Module.Win
OfficeWindowsFormsModule	20.2.5.0	DevExpress.ExpressApp.Office.Win.v20.2

**Comment by AndreasMock1** [comment]
I have also created a new repo in our organization's github containing the problematic solution

**Comment by apobekiaris** [comment]
cool I will review the problem there then, thnks

**Comment by apobekiaris** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
please create an issue guiding me on how to compile and reproduce the case in your organization repo
