### ISSUE TITLE
How to open the editor from the terminal?

### ISSUE THREAD

**Issue by thomasmoors** [eXpandFramework/eXpand#850]
At the moment I get a lot of exceptions after installing `Xpand.XAF.ModelEditor` from NuGet. Is there a way to just use the model editor from cli or something as the package is installed at `C:\Users\thomas\.nuget\packages\xpand.xaf.modeleditor\1.201.6\build`

**Comment by apobekiaris** [comment]
the nuget package unfortunately aims to help Rider users or those advanced that want to do it without VS. If you are not one of the consider the Xpand.VSIX VS plaugin, the Xpand.ModelEditor is embeded no need to do anything

![image](https://user-images.githubusercontent.com/159464/108701879-304a4680-7511-11eb-99a9-155fc563df83.png)


check the releases page to get the Xpand.VSIX package

**Comment by apobekiaris** [comment]
but if you are one of them consider putting all Xpand assemblies from all nuget packages in the same folder and have DX installed in the Gac.

**Comment by thomasmoors** [comment]
But I do intent to use it with Rider :)

**Comment by apobekiaris** [comment]
>but if you are one of them consider putting all Xpand assemblies from all nuget packages in the same folder and have DX installed in the Gac.

Failing the first suggestion, u can compile the Reactive.XAF repository using the scripts on the root and the XpandModelEditor will be in the bin folder. Unfortunately distribution is a bit uncomplete the editor should work however having all dependecies in place. So to achieve as a Rider (advanced) user my instructions should help. You wish me to test and make sure it works for you or even improve the disctibution so all your team can use it effortless consider one of my subscriptions https://github.com/sponsors/apobekiaris

**Comment by apobekiaris** [comment]
what VSIX does mre is that copies the same Xpand.ModelEditor used for Rider in the bin folder of your project where all dependecis already exist, sonsider that also an option for make it work for u

**Comment by thomasmoors** [comment]
Yes I just tried the distributed nuget version, but now I will build the application myself. I will let you know if that fixes it. For now it has dependencies that have hard references to not-included assemblies. I think that might be room for improvement?

**Comment by apobekiaris** [comment]
i have no idea what even the problem yet, but the ME does not use anything extra than XAF so having it in a folder that all xaf assemblies are along with your assemblies should work fine

**Comment by apobekiaris** [comment]
what ME does is loads xaf assemblies and your assemblies along with their dependecies Xpand or other dependecncies, to resolve everything safely u just need them in the same folder

**Comment by apobekiaris** [comment]
and that folder must be your bin cause u constanly update your assemblies, or have a script on post build event that copies everything to a global dir should work fine also

**Comment by thomasmoors** [comment]
Things that go wrong:

When downloading the ME from nuget you instantly get a lot of exceptions. There is no ModelEditor.bat because of this.
When cloning this repo yourself there are hard path and dll references that are not present on the machine, so they have to be changed around. Even after fixing this the code still breaks during runtime.

**Comment by apobekiaris** [comment]
Rider & VS support is now improved using native IDE plugins, read more in the [wiki](https://github.com/eXpandFramework/Reactive.XAF/edit/master/tools/Xpand.XAF.ModelEditor/Readme.md)

![Xpand XAF ModelEditor Win](https://user-images.githubusercontent.com/159464/134785037-e40fe22e-a9c6-4ee5-9f4a-70101f318f7d.gif)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
