### ISSUE TITLE
Access managment

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#853]
𝗜𝘀 𝘆𝗼𝘂𝗿 𝗳𝗲𝗮𝘁𝘂𝗿𝗲 𝗿𝗲𝗾𝘂𝗲𝘀𝘁 𝗿𝗲𝗹𝗮𝘁𝗲𝗱 𝘁𝗼 𝗮 𝗽𝗿𝗼𝗯𝗹𝗲𝗺? 𝗣𝗹𝗲𝗮𝘀𝗲 𝗱𝗲𝘀𝗰𝗿𝗶𝗯𝗲.
We often would like to know who is connected to a XAF application.
We often ask users to logout from the app and if they do not, it would be nice to force a signout. 

𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝘀𝗼𝗹𝘂𝘁𝗶𝗼𝗻 𝘆𝗼𝘂'𝗱 𝗹𝗶𝗸𝗲
- The solution must show a list view of who (permissionpoliucyuser) is connected and from what device : Desktop or mobile. Maybe the ip address.
- From that list view, an admin can force signout. 

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
how u imagine the logout? how about a iis restart? will sure log out them all :)

**Comment by isatahiri** [comment]
How about : https://stackoverflow.com/questions/41629691/how-to-sign-out-other-user-in-asp-net-core-identity/42389162

**Comment by apobekiaris** [comment]
cannot answer if this applicable without researching it deep, there should be other ways to do xafApplication.LogOff() using SignalR or Magic.Onion the tasks is not as easy as it sounds though.

**Comment by isatahiri** [comment]
I did ask DX in order to see. 
Let's wait the answer.
https://supportcenter.devexpress.com/ticket/details/t978442/xaf-blazor-access-management
