### ISSUE TITLE
installing Xpand framework

### ISSUE THREAD

**Issue by hmarzouk** [eXpandFramework/eXpand#855]
Hi Dears,
I want to install Xpand framework 20.2.504.0,  after installing xpandpwsh, so I tried 

Install-Xpand -Version 20.2.504.0 

didn't work with "The Nuget.org is the only ditribution channel starting from v20.1.602.4". i searched on nuget but couldn't find the Xpand.ExpressApp. libraries.  how can i install the 20.2. as the previous versions 

Thanks in advance,
Hesham

**Comment by apobekiaris** [comment]
where did u searched the message says u need to use nuget

https://www.nuget.org/packages?q=expandframework

**Comment by apobekiaris** [comment]
use the container packages eXPandAgnostic, eXpandWin,eXpandWeb

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
