### ISSUE TITLE
Cant use xpand standalone modules at the moment

### ISSUE THREAD

**Issue by ThomasVetterling** [eXpandFramework/eXpand#860]
Hello dear developers,

I was trying to use xpand with a fresh DX 20.2.6 project.
I followed the instructions which were given at

https://www.youtube.com/watch?v=LvxQ-U_0Sbg

and 

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules....

Now I have 2 questions:
a) I have had to add **Microsoft.Graph.Beta** and **akarnokd.reactive_extensions** by hand before I could add '_Xpand.XAF.Core.All_'
That is ok for me, but why such things can happen?

b) When I try to start the project, or try to open the Model-Editor I get error.

"System.ArgumentException: "Ein Fehler mit der Nummer 1008 ist aufgetreten.
Fehler Nachricht: Der 'Xpand.ExpressApp.AdditionalViewControlsProvider.AdditionalViewControlsModule' Typ ist nicht Nachfolger von 'DevExpress.ExpressApp.ModuleBase'.
Parametername: item"

So it seems that something is wrong with my configuration.

Do you have any advice, how to solve that problem?

Yours Thomas

**Comment by apobekiaris** [comment]
AdditionalViewControlsModule belong to the eXpandAgnostic container package and not to Xpand.XAF.Core.All I am guessing u over do it with the registration and I suggest to register only the package u intent to use and not the universe. We have unit/easytests for all packages in the Xpand.XAF.Modules.* namespace however the old framework is not tested and certain configuration may need additional work to start.

**Comment by ThomasVetterling** [comment]
Thank you for your quick answer.
Do I understand correctly that i should either use 'eXpand...' nuget Packages or Xpand.XAF...All nuget packages and not both at the same time?

I have tried to just use the  eXpand... -Packages now. But there now seems to be a 'problem' with 'Mono.Cecil'-DLL which can not be loaded during 'Program-Start'.

Is there any way to find out which module uses Mono.Cecil to solve that problem perhaps with an 'assembly redirection'?

Yours Thomas

**Comment by apobekiaris** [comment]
>Do I understand correctly that i should either use 'eXpand...' nuget Packages or Xpand.XAF...All nuget packages and not both at the same time?

Not correct, there are two reprositories this one and the Reactive one. This repro packages have the `eXpand`  prefix the reactive the `Xpand.XAF.Modules`. The eXpand packages already use some of the reactive packages but not all. In general these are nuget packages u may use them as u wish, however the container packages are more comfortable and tested from the EasyTest solution.

>I have tried to just use the eXpand... -Packages now. But there now seems to be a 'problem' with 'Mono.Cecil'-DLL which can not be loaded during 'Program-Start'.

The process must be as straightforward as in the video at least this what I experience so might u not using the packagereference format but the legay packages.config?

>Is there any way to find out which module uses Mono.Cecil to solve that problem perhaps with an 'assembly redirection'?

the problem can be resolved installing the missing package to the project that complains. You can also use the XpandPwsh `Get-ReerenceConflict` cmdlet to work out your conficts but i do not think is required here

https://github.com/eXpandFramework/XpandPwsh/wiki/Get-ReferenceConflict

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
