### ISSUE TITLE
DevExpress XAF Blazor with Xpand JobScheduler Hangfire Module

### ISSUE THREAD

**Issue by ramilcatalandomingo** [eXpandFramework/eXpand#861]
Hello Apostolis,

Apologies for a newbie post so I went ahead and made a video recording instead.  I hope this helps explain my issue.

https://drive.google.com/file/d/1WxWVq9bxgWnYgzmkM88rlkc2qLwfP7Gy/view?usp=sharing

Thank you for your help.

**Comment by apobekiaris** [comment]
so what happens when u add the Mono.Cecil package?

Also move the JoScheduler registration to the Blazor.Module project instead, and I would expect to see a bunch of guidance exceptions about attributes u have to mark the front end project.

**Comment by ramilcatalandomingo** [comment]
I got this after adding the Xpand.Extensions.Mono.Cecil and moving the Xpand.XAF.Modules.JobScheduler.Hangfire to the Module.Blazor project.

![hangfire](https://user-images.githubusercontent.com/31090302/113686208-983ba180-96f9-11eb-803c-9d2f395a859d.PNG)

**Comment by apobekiaris** [comment]
>and I would expect to see a bunch of guidance exceptions about attributes u have to mark the front end project.

isn't the exception instructions clear for u?

**Comment by ramilcatalandomingo** [comment]
I think I figured it out. Thank you for your help @apobekiaris I appreciate your response to my post.  Your modules are awesome.
