### ISSUE TITLE
Exception when trying to load a model from version 17 on version 20.2

### ISSUE THREAD

**Issue by GECFDISD** [eXpandFramework/eXpand#862]
I'm trying to migrate an old app and while we try to open the model in VS is generating an app crash without any details.

It was opening in previous version (17)

If we open it using the model Tools on VS 2017/2019 this an error is thrown

Message in console is:
XpandModelEditorAppConfigPath enviromental variable is not set
Patching Xpand.XAF.ModelEditor for version 20.2.6
Starting C:\Users\XXX\Documents\dev\XXX\Application\APP\APP\APP.Module.Web\bin\Debug\Xpand.XAF.ModelEditor.exe with arguments  False

Error Message in Xpan Dialog is :

Exception occurs while initializing the 'Xpand.XAF.Modules.ModelViewInheritance.ModelViewInheritanceModule' module: The type initializer for 'Xpand.XAF.Modules.ModelViewInheritance.ModelViewInheritanceService' threw an exception.

If you have any idea how to overcome this issue please let me know.

**Comment by apobekiaris** [comment]
>Exception occurs while initializing the 'Xpand.XAF.Modules.ModelViewInheritance.ModelViewInheritanceModule' module: The type initializer for 'Xpand.XAF.Modules.ModelViewInheritance.ModelViewInheritanceService' threw an exception.

this is thrown when some dependency missing, but does not provide enough info, I would try debugging the XpandModelEditor process as to determine what might be wrong.

Also if you need my help to migrate painless consider my sponsors s page

https://github.com/sponsors/apobekiaris
