### ISSUE TITLE
Sequence Generator - Postgresql

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#863]
I'm evaluating postgresql. According to limitations of sequence storage Postgresql does not work. 
After doing some test I confirm that that sequence number is not set. 
Have you tried to run your unit tests agains postgresql ?

**Comment by apobekiaris** [comment]
>Have you tried to run your unit tests agains postgresql ?

nope I only testing against sql server, however according to https://www.postgresql.org/docs/9.4/explicit-locking.html it might work, not sure 100% u might need to ask DX if https://supportcenter.devexpress.com/ticket/details/e2829/how-to-generate-a-sequential-number-for-a-persistent-object-within-a-database/ works with postgresql.

You probably need to configure the module by adding the the PostResSQlProvider to thje `SequenceGenaratorService.SupportedDataStoreTypes` 

https://github.com/eXpandFramework/Reactive.XAF/blob/3768944fcfc322bc1c629513841e54d6694796c5/src/Modules/SequenceGenerator/SequenceGeneratorService.cs#L213

**Comment by isatahiri** [comment]
yep adding the datastore was the solution ! 
`Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.SupportedDataStoreTypes.Add(typeof(PostgreSqlConnectionProvider));
            RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorModule));`
