### ISSUE TITLE
On New Project Creation eXpand App Wizard is not visible

### ISSUE THREAD

**Issue by nitrixHub** [eXpandFramework/eXpand#864]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
On New Project Creation eXpand App Wizard is not visible, 

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
On VS 2019 CE
1. Install DevExpress 20.2
2. Install the Library from Xpand.VSIX-20.2.504.0.vsix
3. Open VS
4. New Project

𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
eXpand Framework Application wizard available for new projects.

𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀

![image](https://user-images.githubusercontent.com/82302343/114293261-531ec300-9a9d-11eb-8d4e-d085cb8f5a27.png)

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀

05. Installation

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
we do not provide wizard support anymore since we switched to nuget packages

https://www.youtube.com/watch?v=LvxQ-U_0Sbg

**Comment by ugurozyildiz** [comment]
Hello, add nuget package problem. Can you help me?

![NugetXpandProblem](https://user-images.githubusercontent.com/60185974/114874634-2a802b80-9e05-11eb-8fba-aae40f56bad6.jpg)

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'DevExpress 20.2 Local', 'Microsoft Visual Studio Offline Packages'.

**Comment by ugurozyildiz** [comment]
> nuget paketlerine geçtiğimizden beri artık sihirbaz desteği sağlamıyoruz
> 
> https://www.youtube.com/watch?v=LvxQ-U_0Sbg

Hello, can you share if there is a more detailed video other than this video?

**Comment by apobekiaris** [comment]
use the packagereference format instead of packages.config

![image](https://user-images.githubusercontent.com/159464/114905332-835dbd00-9e21-11eb-817d-9db03ed38cd9.png)

**Comment by ugurozyildiz** [comment]
> package.config yerine packagereference biçimini kullanın
> 
> ![görüntü](https://user-images.githubusercontent.com/159464/114905332-835dbd00-9e21-11eb-817d-9db03ed38cd9.png)

thank you so much

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
