### ISSUE TITLE
port all eXpand agnostic packages to netstandard2.0

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#867]

**Comment by isatahiri** [comment]
is this linked to the #844 ?

**Comment by apobekiaris** [comment]
not really however in the next minor tests/easytests are now on .net5.0 so I consider the packages fully compatible to anything >=net461

**Comment by apobekiaris** [comment]
eXpand.lab release [20.2.601.1](https://github.com/eXpandFramework/eXpand.lab/releases/20.2.601.1) includes commit that relate to this task:

* [port all eXpand agnostic packages to netstandard2.0 #867](https://github.com/eXpandFramework/eXpand.lab/commit/4dab2370723e4412dd1503ba4001842cdc8d8345)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
