### ISSUE TITLE
Dashboard without localized Fields

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#868]
Hi Tolis,

after Updating form 20.2.602 to 20.2.701 in Dashboards the localized Fieldnames are not shown. The miracle is that some are shown and other not.

In the Screenshot:
the red are not shown
the blue are shown

![Screenshot 2021-05-03 171357](https://user-images.githubusercontent.com/43132306/116895018-05781f00-ac33-11eb-8219-ba586749a5a6.png)

**Comment by CWolffIF** [comment]
Also I use the "Data View Service".
So in 20.2.602 the refrenced and/or not used attriutes are not shown. See the same Screenshot from 20.2.602 here as above in 20.2.701.

![Screenshot 2021-05-03 174217](https://user-images.githubusercontent.com/43132306/116898788-19258480-ac37-11eb-9b71-076f79240dbb.png)

**Comment by apobekiaris** [comment]
I do not recall anything related this is build-in xaf functionality and we have no custom code to it. Can you sample me?

**Comment by CWolffIF** [comment]
OK. I asked this at Devexpress.

**Comment by CWolffIF** [comment]
Devexpress got the Error
