### ISSUE TITLE
Xpand

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#869]
Hi,

I'm using XpandObjectSpaceProvider with threadsafe parameter = true.
But now I'm fighting in my web app with some "Reentrancy or cross-thread operation detected. ..." exceptions, so  I found in  "https://github.com/eXpandFramework/eXpand/blob/9bd90234886b9ff6f47ba5cdced6cd59bebb3be7/Xpand/Xpand.Xpo/DB/DataStoreManager.cs"  some simpledatalayer  references.

I understand that simpledatalayer datastores are still created.
Is this true? is this a limitation?

Thanks

**Comment by apobekiaris** [comment]
>I'm using XpandObjectSpaceProvider with threadsafe parameter = true.

what is the reason for it? what u try to support that needs this class

**Comment by apobekiaris** [comment]
I want to say that this an old implementation and XAF currently supports it natively using seperate ObjectSpaceProviders with different DataStores of course.

However, I understand that u want to keep your working so as unfortunately cannot recall why this SimpleLayer is created there nor does make sense I can modify the code to use a ThreadSafeLayer `always` when Web. Hopefully it will fix your problems 

Let me know in any case

**Comment by vimarx** [comment]
But If I like to use 2 different  ObjectSpaceProviders, do I have to redo all the datastore stuff?

This will be fine, -- -> "However, I understand that u want to keep your working so as unfortunately cannot recall why this SimpleLayer is created there nor does make sense I **can modify the code to use a ThreadSafeLayer always when Web**. Hopefully it will fix your problems" 
Thanks!

**Comment by vimarx** [comment]
Thanks, will try in upcoming 21.1.3 version (hope soon)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
