### ISSUE TITLE
Overhead is too much and with conflict in 'ApplicationSettingsBase'

### ISSUE THREAD

**Issue by neo-james** [eXpandFramework/eXpand#872]
Just needed the  "XpandNavigationItemAttribute" in a WinForms Xaf and thus resulted to I need to include the following :

    Xpand.ExpressApp.dll
    Xpand.Extensions.dll
    Xpand.Extensions.Mono.Cecil.dll
    Xpand.Extensions.Reactive.dll
    Xpand.Extensions.XAF.dll
    Xpand.Extensions.XAF.Xpo.dll
    Xpand.Persistent.Base.dll
    Xpand.XAF.Modules.CloneMemberValue.dll
    Xpand.XAF.Modules.CloneModelView.dll
    Xpand.XAF.Modules.HideToolBar.dll
    Xpand.XAF.Modules.PositionInListview.dll
    Xpand.XAF.Modules.ProgressBarViewItem.dll
    Xpand.XAF.Modules.Reactive.Logger.dll
    Xpand.XAF.Modules.RefreshView.dll
    Xpand.XAF.Modules.SequenceGenerator.dll
    Xpand.XAF.Modules.ViewItemValue.dll
    Xpand.xpo.dll

Also 
 	System.Configuration.ConfigurationManager
	System.Drawing.Common
	ConcurrentCollections
	0Harmony

and after all I get the following erroor:

Error CS0433The type 'ApplicationSettingsBase' exists in both 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by apobekiaris** [comment]
the exception simply says that there is a .net5 conficlt, only platformAgnostic/netStandard2.0 packages can installed in .net5

**Comment by neo-james** [comment]
Thanks for your reply,

First issue IMHO why all those dependencies for only adding navigation?

Can we look into modularity ? As I can't see why "Xpand.ExpressApp.Base.dll" depend on all those other extensions

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
