### ISSUE TITLE
Adding "eXpandLib" using nuget return error

### ISSUE THREAD

**Issue by neo-james** [eXpandFramework/eXpand#873]
trying to add package eXpandLib to Winforms project result in the following 

`

Attempting to gather dependency information for package 'eXpandLib.21.1.301' with respect to project 'XafTest.Win', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 1.07 min
Attempting to resolve dependencies for package 'eXpandLib.21.1.301' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'DevExpress 21.1 Local', 'Microsoft Visual Studio Offline Packages'.
Time Elapsed: 00:01:04.2016575
========== Finished ==========	

`

**Comment by apobekiaris** [comment]
please use the packagereference format instead of the packages.config

**Comment by faludigabor** [comment]
> trying to add package eXpandLib to Winforms project result in the following
> 
> `
> 
> Attempting to gather dependency information for package 'eXpandLib.21.1.301' with respect to project 'XafTest.Win', targeting '.NETFramework,Version=v4.7.2'
> Gathering dependency information took 1.07 min
> Attempting to resolve dependencies for package 'eXpandLib.21.1.301' with DependencyBehavior 'Lowest'
> Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'DevExpress 21.1 Local', 'Microsoft Visual Studio Offline Packages'.
> Time Elapsed: 00:01:04.2016575
> ========== Finished ==========
> 
> `

Have you got this resolved ? I have the same issue .
![image](https://user-images.githubusercontent.com/16480091/121768444-85f93c00-cb5e-11eb-92f8-e5508169a029.png)
tx,
gabor

**Comment by apobekiaris** [comment]
packages.config is not supported use packagereference format instead

**Comment by faludigabor** [comment]
thanks took me a while that I need to convert the packaging in visual studio :) but worked ! 
g

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
