### ISSUE TITLE
Xpand.Persistent.BaseImpl.JobScheduler classes missing after migrating from 20.2.503 to 21.1.401

### ISSUE THREAD

**Issue by AndreasMock1** [eXpandFramework/eXpand#875]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
After migrating eXpand from version 20.2.503 to 21.1.401 we are missing the Xpand.Persistent.BaseImpl.JobScheduler namespace classes we have used so far in job scheduling.
I can see that the sources have been removed from version 20.2.601.0 to 20.2.602.0 in commit 4dab2370723e4412dd1503ba4001842cdc8d8345, are the classes just moved to another namespace or are they being replaced by another implementation for the jobscheduler?

Thanks in advance for your support.

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
the old module is now removed as there are no tests and was build before 10+ years. The [hangfire](https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire)  is way better alternative
