### ISSUE TITLE
.net 5 is not supported

### ISSUE THREAD

**Issue by justineroncales** [eXpandFramework/eXpand#878]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
i tried to apply expand import. but it is not working on .net 5. is there anyways how can i use this library on my solution

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by justineroncales** [comment]
warning NU1701: Package 'eXpandLib 21.1.401' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
1>VERBOSE: dxVersion=21.1.3

**Comment by apobekiaris** [comment]
the eXpand* packages are not yet scaled, only the Xpand.XAF.Modules* packages can be used on .net5.0 currently.

**Comment by justineroncales** [comment]
Hi  sir,

Thanks for the confirmation.
May i kindly ask when will be the release support for .net 5.
Thanks so much

>

**Comment by apobekiaris** [comment]
cannot estimate exactly, but agnostic modules must be ported to .netstandard2.0 where possible and push what is not to platform modules. In addition platform modules must target additional to .net461 the .net5.0 framework.

**Comment by justineroncales** [comment]
Hi sir good day,

May i kindly ask how may i able to use import wizard on my application?
Is it the library i need or is it different?
i need is to import an excell file then save into BO.
thank you and god bless :)

[image: image.png]

**Comment by justineroncales** [comment]
[image: image.png]

**Comment by apobekiaris** [comment]
next release will offer additional net461, net5 support

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.500.0](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.500.0) includes commit that relate to this task:

* [.net5 support #878](https://github.com/eXpandFramework/eXpand.lab/commit/11785d0bd2ee0b7d5054102738ca77ff46c6ce06)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
Hi. @apobekiaris 
My first attemp to run an existing solution with 21.1.500 fails at startup with
`System.AggregateException
  HResult=0x80131500
  Mensaje = Se han producido uno o varios errores.
  Origen = mscorlib
  Seguimiento de la pila:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

  Esta excepción se generó originalmente en esta pila de llamadas:
    DevExpress.ExpressApp.Utils.CodeGeneration.CSCodeCompiler.RaiseCompilerException(string, System.CodeDom.Compiler.CompilerResults)
    DevExpress.ExpressApp.Model.Core.ModelAssemblyGeneratorArguments.CompileModelAssembly(bool)
    DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.GetFromRegistry(DevExpress.ExpressApp.Model.Core.ModelApplicationCreatorProperties)
    DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.Get.AnonymousMethod__1()
    System.Lazy<T>.CreateValue()
    System.Lazy<T>.LazyInitValue()
    DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.Get(DevExpress.ExpressApp.Model.Core.ModelApplicationCreatorProperties)
    DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.CreateCreatorInfo()
    DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.CreatorInfo.get()
    DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.GetNodeInfos(System.Type)
    ...
    [Pila de llamadas truncada]

Excepción interna 1:
CompilerErrorException: Cannot compile the generated code. Please inspect the generated code via this exception's SourceCode property. The following errors occurred: 
(102795, 14): El tipo 'System.Drawing.GraphicsUnit' está definido en un ensamblado al que no se hace referencia. Debe agregar una referencia al ensamblado 'System.Drawing.Common, Version=4.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
(102795, 14): 'ModelAppearanceRule' no implementa el miembro de interfaz 'Xpand.Persistent.Base.ModelAdapter.IModelAppearanceFont.Unit'. 'ModelAppearanceRule.Unit' no puede implementar 'Xpand.Persistent.Base.ModelAdapter.IModelAppearanceFont.Unit' porque no tiene el tipo de valor devuelto coincidente de 'System.Drawing.GraphicsUnit?'.

`

**Comment by vimarx** [comment]
I also added a package reference to system.drawing.common 5.0.2 explicitly....

**Comment by apobekiaris** [comment]
thnks for testing, wait for next minor please

**Comment by vimarx** [comment]
Ok, I forgot to mention the Target was 461

**Comment by vimarx** [comment]
the same exception with 21.1.500.1

`System.AggregateException
  HResult=0x80131500
  Mensaje = Se han producido uno o varios errores.
  Origen = mscorlib
  Seguimiento de la pila:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

  Esta excepción se generó originalmente en esta pila de llamadas:
    DevExpress.ExpressApp.Utils.CodeGeneration.CSCodeCompiler.RaiseCompilerException(string, System.CodeDom.Compiler.CompilerResults)
    DevExpress.ExpressApp.Model.Core.ModelAssemblyGeneratorArguments.CompileModelAssembly(bool)
    DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.GetFromRegistry(DevExpress.ExpressApp.Model.Core.ModelApplicationCreatorProperties)
    DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.Get.AnonymousMethod__1()
    System.Lazy<T>.CreateValue()
    System.Lazy<T>.LazyInitValue()
    DevExpress.ExpressApp.Model.Core.GlobalModelAssemblyRegistry.Get(DevExpress.ExpressApp.Model.Core.ModelApplicationCreatorProperties)
    DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.CreateCreatorInfo()
    DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.CreatorInfo.get()
    DevExpress.ExpressApp.Model.Core.ModelApplicationCreator.GetNodeInfos(System.Type)
    ...
    [Pila de llamadas truncada]

Excepción interna 1:
CompilerErrorException: Cannot compile the generated code. Please inspect the generated code via this exception's SourceCode property. The following errors occurred: 
(96630, 14): El tipo 'System.Drawing.GraphicsUnit' está definido en un ensamblado al que no se hace referencia. Debe agregar una referencia al ensamblado 'System.Drawing.Common, Version=4.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
(96630, 14): 'ModelAppearanceRule' no implementa el miembro de interfaz 'Xpand.Persistent.Base.ModelAdapter.IModelAppearanceFont.Unit'. 'ModelAppearanceRule.Unit' no puede implementar 'Xpand.Persistent.Base.ModelAdapter.IModelAppearanceFont.Unit' porque no tiene el tipo de valor devuelto coincidente de 'System.Drawing.GraphicsUnit?'.

`

**Comment by vimarx** [comment]
in my GAC
![image](https://user-images.githubusercontent.com/226800/129426442-a5a5ede2-66fe-41e8-bf48-622a296ed431.png)

**Comment by apobekiaris** [comment]
hmm how u test it? if you look at the source/latestcommit my fix was about to remove that `GraphicsUnit` type, so I cannot repro it anymore. Can you try to sample me somehow?

**Comment by apobekiaris** [comment]
I manage to repro it thnks

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.500.2](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.500.2) includes commit that relate to this task:

* [.net5 support #878 - System.Drawing.GraphicsUnit CompilerErrorException](https://github.com/eXpandFramework/eXpand.lab/commit/8f7c10749424982b7464ba83957dfc629afcaedd)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
Hi, that app works ok with 21.1.500.2, but another (more complex), fails with similar kind of exception

DevExpress.ExpressApp.Utils.CodeGeneration.CompilerErrorException
  HResult=0x80131500
  Mensaje = Cannot compile the generated code. Please inspect the generated code via this exception's SourceCode property. The following errors occurred: 
(114310, 14): El tipo 'System.Drawing.FontStyle' está definido en un ensamblado al que no se hace referencia. Debe agregar una referencia al ensamblado 'System.Drawing.Common, Version=4.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
(114310, 14): 'ModelAdditionalViewControlsRule' no implementa el miembro de interfaz 'Xpand.Persistent.Base.AdditionalViewControls.ISupportAppeareance.FontStyle'. 'ModelAdditionalViewControlsRule.FontStyle' no puede implementar 'Xpand.Persistent.Base.AdditionalViewControls.ISupportAppeareance.FontStyle' porque no tiene el tipo de valor devuelto coincidente de 'System.Drawing.FontStyle?'.

  Origen = DevExpress.ExpressApp.v21.1
  Seguimiento de la pila:
   at DevExpress.ExpressApp.Utils.CodeGeneration.CSCodeCompiler.RaiseCompilerException(String sourceCode, CompilerResults compilerResults) in DevExpress.ExpressApp\DevExpress.ExpressApp\Utils\CodeGeneration\CSCodeCompiler.cs:line 131

**Comment by vimarx** [comment]
Actual Solutions 
1 -> Winform -> net461
2 -> WebForm - > net461
3 -> Blazor -> net5
some common modules (agnostic) of these solutions are targeted net461 and some netstandard2.0

all these solutions are "working" with 21.1.500.2

**Comment by vimarx** [comment]
> Hi, that app works ok with 21.1.500.2, but another (more complex), fails with similar kind of exception
> 
> DevExpress.ExpressApp.Utils.CodeGeneration.CompilerErrorException
> HResult=0x80131500
> Mensaje = Cannot compile the generated code. Please inspect the generated code via this exception's SourceCode property. The following errors occurred:
> (114310, 14): El tipo 'System.Drawing.FontStyle' está definido en un ensamblado al que no se hace referencia. Debe agregar una referencia al ensamblado 'System.Drawing.Common, Version=4.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
> (114310, 14): 'ModelAdditionalViewControlsRule' no implementa el miembro de interfaz 'Xpand.Persistent.Base.AdditionalViewControls.ISupportAppeareance.FontStyle'. 'ModelAdditionalViewControlsRule.FontStyle' no puede implementar 'Xpand.Persistent.Base.AdditionalViewControls.ISupportAppeareance.FontStyle' porque no tiene el tipo de valor devuelto coincidente de 'System.Drawing.FontStyle?'.
> 
> Origen = DevExpress.ExpressApp.v21.1
> Seguimiento de la pila:
> at DevExpress.ExpressApp.Utils.CodeGeneration.CSCodeCompiler.RaiseCompilerException(String sourceCode, CompilerResults compilerResults) in DevExpress.ExpressApp\DevExpress.ExpressApp\Utils\CodeGeneration\CSCodeCompiler.cs:line 131

this issues appears starting Winform Project from solution

**Comment by apobekiaris** [comment]
agnostic packages for 21.500.2 target .net461 but now they are netstandard

**Comment by vimarx** [comment]
they are fine, but I understand there are two remaining issues

1) similar to ".net5 support #878 - System.Drawing.GraphicsUnit CompilerErrorException", it appears to be another issue with 'System.Drawing.FontStyle'  in AddicionalViewController ( I forgot to mention that I HAD to REMOVE this dependency to make it work)

2) #880 that is affecting startup debugging....

**Comment by apobekiaris** [comment]
yes of course I am working on them it not that east .net gets confused I am testing workarounds. Have't test the WebForsms yet thats why I asked

**Comment by vimarx** [comment]
thanks!, I've not released to production the WebForm (net461) solution yet, I will keep you informed

**Comment by vimarx** [comment]
I noticed that the fix is ready but the pipeline failed ... Could you retry it?

**Comment by apobekiaris** [comment]
working on this minor issue from yesterday as u can see

![image](https://user-images.githubusercontent.com/159464/130073633-63a68c89-9c49-4398-8c89-dbcccbf31ecd.png)

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.500.3](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.500.3) includes commit that relate to this task:

* [.net5 support #878 - System.Drawing.GraphicsUnit CompilerErrorException](https://github.com/eXpandFramework/eXpand.lab/commit/6c7731eaa90bcb84bb9076242469219f6fc0b1c4)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
looking forward for your feedback to myu tests I can run the packages for .net5 and .netframework. Do u suffer anyhow?

**Comment by justineroncales** [comment]
Hi,

Good day as of now i skip all the task regarding on this matter. noted on
everything. ill get back to you soonest once i applied thanks

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.501.2](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.501.2) includes commit that relate to this task:

* [add framework dependency to container packages #878](https://github.com/eXpandFramework/eXpand.lab/commit/511345068fc4ad1ac7290c77dc80573baf0a0ec3)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.600.0](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.600.0) includes commit that relate to this task:

* [add framework dependency to container packages #878](https://github.com/eXpandFramework/eXpand.lab/commit/b6eaefed8bbd557069f285b21c23b88dec7b16e9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
