### ISSUE TITLE
First try to build repository locally

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#881]
Hi, this is my first attempt to rebuild locally the lab repository

the rebuild option of vs fails  

'
1>Downloading runtime.native.System 4.3.1
1>Downloading System.Text.RegularExpressions 4.3.1
1>Something went wrong while downloading DevExpress.ExpressApp.TreeListEditors.Web 21.1.5
1>Message: The package DevExpress.ExpressApp.TreeListEditors.Web 21.1.5 can't be found in **C:\Program.** (The directory doesn't exist.)
1>Please check the feed definition in your paket.dependencies file.
'
Dx is installed in the default path, but paket restore is having some issues with the space in the path.

**Comment by apobekiaris** [comment]
paket.dependecies needs to modified to match your sources

here how azure does it

https://github.com/eXpandFramework/eXpand/blob/230ec8a0a8b5ada2b18aa7c1d26513047cd10a53/.github/Azure-pipeline.yml#L33

**Comment by apobekiaris** [comment]
so use your DXApiFeed instead

**Comment by apobekiaris** [comment]
also to clarify a bit more for all, if the build does not pass on azure it most problably won't work in your local machine although it worked on mine

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
