### ISSUE TITLE
Sequence Generator Postgresql - Error when using Postgresql - operator does not exist: bigint = character varying

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#887]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Error when using Postgresql - operator does not exist: bigint = character varying
According to the stack this seems to be a DX issue but still worth posting it here for information. 
So at this stage I guess there is nothing to do. 

in the module.cs I added the PostgreSqlConnectionProvider
`   Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.SupportedDataStoreTypes.Add(typeof(PostgreSqlConnectionProvider));
            RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorModule));`

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
Create a new record

[exception.txt](https://github.com/eXpandFramework/eXpand/files/7318305/exception.txt)

**Comment by apobekiaris** [comment]
the modules does not have dependecies to XPO providers. From your post I understand that XAF validation creates a non supported Postgresql query, so I guess modifying that validation rule or removing it should woraround the problem

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
