### ISSUE TITLE
small suggestion

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#895]
Hi, 
From time to time, I like to look at commits for seeing what is new / what is changing.
Today (and from some time ago), most of the commits are version stuff.
Is there any way/possibility of split commits? , so the real code changes are more isolated?
Thanks

**Comment by apobekiaris** [comment]
Unfortunately we are in a major upgrade time once more but i think the commits do represent the work roughly

![image](https://user-images.githubusercontent.com/159464/141530435-e173790c-6b2a-4d8f-8967-a497618615a3.png)

however when in lab I tend to rewrite history, meaning that i pushing several times on the latest commit until the tests pass and the docs are updated. If there is a specific problem that makes sense to keep detailed history like `891` I will create a seperate commit.

For example the latest commit `JobScheduler: ChainJobs tests #892` contains endless changes to all JobScheduler related packages, but they done to support ChainedJobs, makes no sense to start commiting every small idea or test that comes into my mind, many times these ideas are junk, in addition it takes a lot of time to do so.

**Comment by apobekiaris** [comment]
makes no sense to monitor any of the commits in the screenshot i posted, cause these are new packages, sure it makes sense to monitor them once you already use the package in your app for possible changes. But again the dev cost can skyrocket if you assign a percentage of your resources to beatify the commit history

**Comment by apobekiaris** [comment]
my guess is that you referr to this repository and not the reactive one. Yes there is only versioning stuff cause there is no other work done here. All the work is done in the Reactive repo as we are migrating constantly there.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
