### ISSUE TITLE
21.2.301 ReportV2 Initialisation Error

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#896]
Hi,

after migrating my project to 21.2.301 it doesn´t start with the error of a missing 
DevExpress.Persistent.BaseImpl

But the 
- DevExpress.Persistent.BaseImpl.Xpo.v21.2.dll
- DevExpress.Persistent.Base.v21.2.dll
are referenced in the project and in the local path (Copy local==true).

System.IO.FileNotFoundException
  HResult=0x80070002
  Nachricht = Please make sure DevExpress.Persistent.BaseImpl is referenced from your application project and has its Copy Local==true
  Quelle = Xpand.Persistent.Base
  Stapelüberwachung:
   bei Xpand.Persistent.Base.General.XpandModuleBase.GetDxBaseImplType(String typeName) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs: Zeile400
   bei Xpand.Persistent.Base.General.XpandModuleBase.LoadDxBaseImplType(String typeName) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs: Zeile409
   bei Xpand.ExpressApp.ReportsV2.Win.ReportsV2WinModule.Setup(XafApplication application) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ReportsV2.Win\WinModule.cs: Zeile14
   bei DevExpress.ExpressApp.XafApplication.ModuleList_ModuleAdded(Object sender, ModuleRegisteredEventArgs e)
   bei DevExpress.ExpressApp.ModuleList.SetupModule(ModuleBase module)
   bei DevExpress.ExpressApp.ModuleList.OnInsert(Int32 index, Object value)
   bei System.Collections.CollectionBase.System.Collections.IList.Add(Object value)
   bei DevExpress.ExpressApp.Utils.BindingListBase`1.Add(T item)
   bei DevExpress.ExpressApp.ModuleList.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   bei DevExpress.ExpressApp.ModuleList.EnsureModuleInList(Type moduleType, IList`1 moduleList, List`1 requiredModules)
   bei DevExpress.ExpressApp.ModuleList.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   bei DevExpress.ExpressApp.ModuleList.RefreshRequiredModules()
   bei DevExpress.ExpressApp.ModuleList.OnInitializeComplete()
   bei DevExpress.ExpressApp.Utils.BindingListBase`1.EndInit()
   bei DevExpress.ExpressApp.XafApplication.EndInit()
   bei iXISXRM.Win.iXISXRMWindowsFormsApplication.InitializeComponent() in C:\DevProjects\iXIS IF\iXISXRM.Win\WinApplication.Designer.cs: Zeile168
   bei iXISXRM.Win.iXISXRMWindowsFormsApplication..ctor() in C:\DevProjects\iXIS IF\iXISXRM.Win\WinApplication.cs: Zeile59
   bei iXISXRM.Win.Program.Main() in C:\DevProjects\iXIS IF\iXISXRM.Win\Program.cs: Zeile84

**Comment by apobekiaris** [comment]
Hi,

thanks I see the problem pushing a patch build

**Comment by apobekiaris** [comment]
eXpand.lab release [21.2.301.1](https://github.com/eXpandFramework/eXpand.lab/releases/21.2.301.1) includes commit that relate to this task:

* [Incorrect DevExpress.Persistent.BaseImpl dependency in XpandModuleBase #896](https://github.com/eXpandFramework/eXpand.lab/commit/1b6bb61bf82452e9093ee39eda0652b465bce32e)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi,

it works.
