### ISSUE TITLE
Xpand.ExpressApp.Security.Web not available in XAF Blazor

### ISSUE THREAD

**Issue by txt2203** [eXpandFramework/eXpand#899]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
I create XAF Blazor server. After adding Nuget eXpandSecurityWeb package to Module.Blazor, then adding RequiredModuleTypes raised error : 
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Security.Web.XpandSecurityWebModule));
=> Error: The type or namespace name 'Web' does not exist in the namespace 'Xpand.ExpressApp.Security' (are you missing an assembly reference?)

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
+ VS2019.
+ DevExpress 21.2.4.
+ eXpandWeb 21.2.401 Package.

𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
Searching Xpand source and I still see namespace Xpand.ExpressApp.Security.Web overthere ,also other Web packages for Web.
However, package : Xpand.ExpressApp.Security.Web.XpandSecurityWebModule not exists (namespace Web not exist).
𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
See attached
![XAF-mistakes](https://user-images.githubusercontent.com/55611923/149090662-4135d224-d1a8-41fb-b7db-bcbe8220353a.png)
.

**Comment by apobekiaris** [comment]
Security.Web and in general *.Web of this framework support only the Full .NetFramework

https://github.com/eXpandFramework/eXpand/blob/caeec3396188d30c3e75e5c020b7b8aa00332ad8/Xpand/Xpand.ExpressApp.Modules/Security.Web/Xpand.ExpressApp.Security.Web.csproj#L6

**Comment by apobekiaris** [comment]
*. Win and all packages of the RX repository are .NET5 compatible http://xaf.expandframework.com/

**Comment by txt2203** [comment]
Thanks. Do you have any plan to develop Security.Web in .NET5 and Blazor?

**Comment by apobekiaris** [comment]
not under this architecture as I mention all packages of http://xaf.expandframework.com/ already designed for Blazor. What I find it worthy from the *.Web of this framework it will packaged as standalone and published from the Reactive repository together with Unit/EasyTests and docs/videos
