### ISSUE TITLE
ReportDesigner: Detail Count at Design Time

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#902]
Hi Tolis,

Setting the value for "Detail Count at Design Time" throws an Error and the value is not taken. I sent it to Devexpress and they say I should give it to you. In a sample app without eXpandfamework it works.
![ReportDesigner](https://user-images.githubusercontent.com/43132306/151823048-fad03cef-d86d-44ba-a20b-ffe892731749.gif)

**Comment by apobekiaris** [comment]
is not there at runtime? is there a stack?

**Comment by CWolffIF** [comment]
It is at runtime when I use the designer.

There is no stack or errorlog. Here are some screenshots.

![Stacktrace2](https://user-images.githubusercontent.com/43132306/151827617-03153824-974f-4ab2-b328-5646efa965d6.png)
![error1](https://user-images.githubusercontent.com/43132306/151827623-6fef4475-55cf-4628-9e61-04c433316599.png)
![error2](https://user-images.githubusercontent.com/43132306/151827625-6ea97d5b-47cb-4259-bfbc-4e995f0abc13.png)
![stacktrace1](https://user-images.githubusercontent.com/43132306/151827628-41fcf8a5-f50a-4588-81e5-7aab2c9c6afd.png)

**Comment by apobekiaris** [comment]
not a clue, what about a sample?

**Comment by CWolffIF** [comment]
Wait, I check it first out with DevExpress....

**Comment by CWolffIF** [comment]
Hi,
Devexpress solved it (in 21.2.5).
But DashboardModule TopReturnedRecordsIn Designer #903 is still there.
