### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by fsrcapital** [eXpandFramework/eXpand#904]
I am attempting to use the ModelDifference module in a new project. I went to https://github.com/eXpandFramework/eXpand/wiki/Getting-Started and it says to get an installer. On the download page you end up on, there is only a nupkg and vsix file. The first page talks about running an installer and files being put into the GAC. Is the getting started document accurate or is there another way to get started that I cannot find anywhere on the page. 

I installed the VSIX file, but I don't have a new project template for eXpand so I am lost.

Thanks so much!

**Comment by apobekiaris** [comment]
there is no project template packages are on Nuget, this repo docs are not good I suggest you explore the work in the RX repository were docs are complete.

for installing all you require is to do as per video.

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules

**Comment by apobekiaris** [comment]
ModelDifference module has no docs expect to this old blod posts you can find in the first page of this repo.

**Comment by fsrcapital** [comment]
> there is no project template packages are on Nuget, this repo docs are not good I suggest you explore the work in the RX repository were docs are complete.
> 
> for installing all you require is to do as per video.
> 
> https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules

Thank you for the clarification!
