### ISSUE TITLE
Snap .net5

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#905]
Hi Tollis,

maybe you recognized the discussion at devexpress. The snap module is not ported to .net5. So we asked for to port is, because it is a main feature for our customers.

Snap is the right tool for End-Users (of our Applications) to design Text-Patterns, Templates (f.e. for eMails) or small Reports in XAF Application. The End User is familiar with Word Mailing capabilities. The power of snap is, that you have access to the whole Object Datastructure (this is very much better than the normal MailMerge Function of RTF Control). So our End Users in all projects build hundreds of Templates, Lettertemplates, eMailtemplates and on-the-fly Reports. This is a core feature and we have to deliver it.

The Report Module is to big for End-Users. It is a powerful tool, made for Administrators, us (Developers, Consultants) and maybe PowerUsers.

If Devexpress did not port it, do you think that there is a way to port it and maybe integrate it in expandFramework?

**Comment by apobekiaris** [comment]
do u target non windows ? I guess it should work even if in .net4

**Comment by apobekiaris** [comment]
snap is a large product even if I could port it I guess the support workload would be huge in addition I am not the owner and cannot take such desicion

**Comment by CWolffIF** [comment]
Hi Tolis,
thanx for your reply. I´m aware that you are not the product owner and I´m in discussion with devexpress. But if Devexpress closed down suppport, is there a way to continue the module in your opinion (under condition devexpress agreed)? We would place an order to convert it and you can help/teach us to maintain the module.

**Comment by apobekiaris** [comment]
I do not feel like discussing it in public especially without green light, you know my email feel free.
