### ISSUE TITLE
Updating model, error "The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception." is raised

### ISSUE THREAD

**Issue by Dade27** [eXpandFramework/eXpand#907]
Hi Tolis,
I am upgrading a XAF+eXpand win+web+xpo solution from 18.1.4 to 21.2.5 but I becoming crazy.
I decided to create a brand new XAF solution and add eXpandAgnostic nuget package to "Module" project, but I am not able to run successfully "Update model" on the project.
Error I have into updating VS output window is:

```
"------- Updating model differences: Project: C:\Users\david.desidera\source\repos\DXApplicationNETframe\DXApplicationNETframe.Module\DXApplicationNETframe.Module.csproj
Error:
Unable to create an instance of the "Xpand.XAF.Modules.ModelViewInheritance.ModelViewInheritanceModule" type.
Reason: "The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception."
Update failed"
```

I attached here my test solution: could you please help me to understand where I mistake?
Thank you in advance
With best regards
David Desiderà

[DXApplicationNETframe.zip](https://github.com/eXpandFramework/eXpand/files/8049942/DXApplicationNETframe.zip)

**Comment by apobekiaris** [comment]
looks interesting case, however not high priority, heads up that it might take a while

**Comment by Dade27** [comment]
I see... but what do you suggest for my case? 
Here below a few details.
- current released version (installed on customers' prod. environments) is based on DX18.1.4+Xpand18.1.4.9
- DevExpress project converter to 21.2.5 works fine
- I added manually all Xpand nupkg
- Right click on solution node "Update Module on all projects" command
- VS raises the error message in "Updating" output window

At the end of April I must release the never version: any suggestions are more then welcome!
Thanks
David

**Comment by apobekiaris** [comment]
lokos related to #908  so your only option is to recompile the framework and apply the same fix. Your can also go manual without the Update Model command, just open your models make a dummy change and save them, there should be an UnsuableNodes.on path xafml if problems

**Comment by Dade27** [comment]
Thanks a lot.  I will try and let you the result.

**Comment by apobekiaris** [comment]
works fine in my side 

```
------- Updating model differences: Project: C:\Work\issues\907\XpandApplication\XpandApplication\XpandApplication.Module\XpandApplication.Module.csproj
Update complete

------- Updating model differences: Project: C:\Work\issues\907\XpandApplication\XpandApplication\XpandApplication.Module.Web\XpandApplication.Module.Web.csproj
Update complete

------- Updating model differences: Project: C:\Work\issues\907\XpandApplication\XpandApplication\XpandApplication.Web\XpandApplication.Web.csproj
Update complete

------- Updating model differences: Project: C:\Work\issues\907\XpandApplication\XpandApplication\XpandApplication.Module.Win\XpandApplication.Module.Win.csproj
Update complete

------- Updating model differences: Project: C:\Work\issues\907\XpandApplication\XpandApplication\XpandApplication.Win\XpandApplication.Win.csproj
Update complete

```

1. I open the solution
2. run projectconverter as prompted for 21.2.6
3. Hit F5 and same exception thown however it clearly states about a missing dependecy to System.Text.Json 5. I install that package in the agnostic module and F5 again with success. Next I tried the `Update Model` command

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
