### ISSUE TITLE
How I got eXpand working on MacOS Visual Studio 2022 Preview.

### ISSUE THREAD

**Issue by dsikic** [eXpandFramework/eXpand#910]
𝗜𝘀 𝘆𝗼𝘂𝗿 𝗳𝗲𝗮𝘁𝘂𝗿𝗲 𝗿𝗲𝗾𝘂𝗲𝘀𝘁 𝗿𝗲𝗹𝗮𝘁𝗲𝗱 𝘁𝗼 𝗮 𝗽𝗿𝗼𝗯𝗹𝗲𝗺? 𝗣𝗹𝗲𝗮𝘀𝗲 𝗱𝗲𝘀𝗰𝗿𝗶𝗯𝗲.
I understand that very few people have thought about using VS on Mac, so this is quite niche. However, if you find yourself with an M1 (arm) based Mac or MacBook, you'll soon discover that running Visual Studio inside of parallels doesn't perform well. In fact Microsoft gives you a warning when the installer is running. 

Visual Studio for Mac is actually a decent experience when Developing XAF Blazor, but it breaks as soon as eXpand NuGet dependencies are introduced. Visual Studio will throw a build error saying it cannot find Powershell.exe and also that running powershell.exe, with a bunch of parameters failed.

To get around this issue you can install PWSH using the following guide. It's quick, just install brew, then use brew, then add to path.

[Installing PowerShell on macOS](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2)

Once this is done, I experimented with adding a shell alias for powershell.exe, but visual studio doesn't pick it up so that didn't yield any results.

However, once you have PWSH installed if you double click the error in Visual Studio for Mac it will take you to the *.targets file where the following command exists. 

`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="CopySymbols1" AfterTargets="AfterBuild">
        <Exec Command="Powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command &quot;&amp; { &amp;&apos;$(MSBuildThisFileDirectory)\CopySymbols.ps1&apos; &apos;$(Targetpath)&apos; &apos;$(Projectpath)&apos; } &quot; " LogStandardErrorAsError="True" ContinueOnError="False" />
    </Target>
</Project>`

Simply replace Powershell.exe with pwsh, and save the file. Then build solution again, and everything should work fine.

𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝘀𝗼𝗹𝘂𝘁𝗶𝗼𝗻 𝘆𝗼𝘂'𝗱 𝗹𝗶𝗸𝗲

I would like the existing scripts to detect whether they are on Windows, and if they're not, then default to pwsh instead of powershell.exe. Ideally they should remind the user to install pwsh using the link above, if that command also fails.

**Comment by dsikic** [comment]
@apobekiaris if you point me in the right direction, I'm happy to implement this myself in a pull request. Just not sure where the scripts are all stored.

**Comment by apobekiaris** [comment]
better idea is to disable the scripts once in MacOs cause they do actually nothing. The latest version already has VersionConverter.ps1 disabled

https://github.com/eXpandFramework/Reactive.XAF/blob/lab/tools/Xpand.VersionConverter/Xpand.VersionConverter.ps1#L17

VersionConverter support stopped as we got into this .NetFramework hell, meaning when .net5/.netcore was introduced.
CopySymbols copy the symbols from Nuget dir into path, howewver symbols are only working in windows, so tottally of no use.

YOu can add a returbn at the start of the script and test?

Happy to accept a PR if u can test detecting non Windows should be trivial as per c#

note pwsh is c# actually with a different syntax  so u could

```ps
[System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)
$IsWindows
```

or https://stackoverflow.com/questions/64893785/how-to-detect-linux-or-macos-or-windows-in-powershell

let me know if u require more help

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
