### ISSUE TITLE
Can the version converter be re enabled.

### ISSUE THREAD

**Issue by Johnka2** [eXpandFramework/eXpand#911]
We have an existing  project version 19.2.10 .net framework.
Can we enable version converter on latest reactive modules?
If not what is the last version of reactive modules that had version converter working.

**Comment by apobekiaris** [comment]
there are plans to reenable it however once there is a history that worths it, now is disabled cause of the switching to .NET5. What is the issue?

**Comment by apobekiaris** [comment]
ah i see i haven't read the full msg, in short you may attempt your self, it can work if u not want to support the universe. e.g. .NET5 compiled packages won't work. The versionconverter has minimum support for .NET5 currently

**Comment by Johnka2** [comment]
That's ok.
So how do I re enabled it for .net framework.

**Comment by apobekiaris** [comment]
uncommend the `return` line in VersionConverter.ps1 found ion your nuget folder, however I did not test my suggestion

**Comment by Johnka2** [comment]
Initial installation of nuget requires version 21.2.5.

**Comment by Johnka2** [comment]
May be I will compile the sources

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
