### ISSUE TITLE
World Creator sample request

### ISSUE THREAD

**Issue by Johnka2** [eXpandFramework/eXpand#915]
Is there any sample on world creator.
i have looked at existing documentation and only functionality is demonstrated but no 
info on how to set it up and existing demos are too old to run on current version.

using a sample from old expand demo "WorldCreatorTester.Win" v18.2.7 i get this error after upgrade to 21.2.6

Exception occurs while initializing the 'Xpand.ExpressApp.WorldCreator.WorldCreatorModule' module: Cannot handle the "Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentClassesModuleInfo" type. To address this error, add an appropriate Object Space to the AdditionalObjectSpaces collection (see http://docs.devexpress.com/eXpressAppFramework/DevExpress.ExpressApp.CompositeObjectSpace.AdditionalObjectSpaces).

   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModulesPatch(ApplicationModulesManager __instance)
   at DevExpress.ExpressApp.ApplicationModulesManager.SetupModules_Patch1(ApplicationModulesManager this)
   at DevExpress.ExpressApp.ApplicationModulesManager.LoadCore(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.Win.WinApplication.<>n__0(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass78_0.<SetupCore>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

is there any sample from current versions

**Comment by apobekiaris** [comment]
only packages from the xaf.expandframework.com are tested on each build, so no I do not have a sample but this does not look like an error. did u follow the suggestion?

**Comment by Johnka2** [comment]
yes followed the suggestion.
but application does not reach that far.
this happens at startup

**Comment by apobekiaris** [comment]
post your sample using nugets and latest version please

**Comment by Johnka2** [comment]
[wc.zip](https://github.com/eXpandFramework/eXpand/files/8237382/wc.zip)

**Comment by Johnka2** [comment]
this is the wc demo upgraded to 21,2.6

**Comment by Johnka2** [comment]
i have checked this and it works with dx 19.2.7
something changed in dx 21.2 that breaks it

**Comment by apobekiaris** [comment]
WC is like u run a 2nd Xaf app b4 the main app Xaf introodcued this exception as it seems in between need time to patch it. If you have the time to do it I can review your PR

**Comment by Siratigui** [comment]
you can register PersistentClassesModuleInfo inside your module constructor with the line below:

WorldCreatorTypeInfoSource.Instance.ForceRegisterEntity(typeof(Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentClassesModuleInfo));

**Comment by apobekiaris** [comment]
what this means? is it kind of fix ?

**Comment by Siratigui** [comment]
yes we faced the same error while ago.

**Comment by arnzuk** [comment]
Hi,

Do someone successfully started worldcreator? We have same error as Johnka2 with 21.2.601 version. Sirarigui suggestions does not help also.

**Comment by arnzuk** [comment]
Hi, apobekiaris,

Are you going to fix worldcreator? It does not work with 21.2 version

**Comment by apobekiaris** [comment]
PR are totally accepted however I cannot spend resources, to investigate possible patches unless there is a sponsorishp for the task.

**Comment by apobekiaris** [comment]
according to changes in #940 WC should be functional now

**Comment by apobekiaris** [comment]
```
WorldCreatorTypeInfoSource.Instance.ForceRegisterEntity(AppDomain.CurrentDomain.GetAssemblyType("Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentClassesModuleInfo"));
```

maybe this can also be included in the actuall WC module and not in your project mdules? If can someone test and confirm happy to add this line as well.



> WorldCreatorTypeInfoSource.Instance.ForceRegisterEntity(typeof(Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentClassesModuleInfo));


what I mean add in `WorldCreatorModule` build test and report back

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
