### ISSUE TITLE
Xpand.XAF.ModelEditor cannot work with VS 2022

### ISSUE THREAD

**Issue by garung1611** [eXpandFramework/eXpand#916]
I cannot find extension Xpand.XVSIX on Visual Studio Market using VS2022. Everything is fine with VS2019. When I pull project Xpand.XAF.ModelEditor to rebuild with VS2022, VS2022 throw error: Microsoft.Visualstudio.ExtensionManager not found. Is this extension compatible with VS2022?

**Comment by apobekiaris** [comment]
yes it is not ported PR is acceptable if u take the time to port it

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
