### ISSUE TITLE
Cannot set Email Recipients

### ISSUE THREAD

**Issue by garung1611** [eXpandFramework/eXpand#918]
I cannot create new Recipients in ReactiveModules.Email.Recipients using Model Editor. As I know, the property RecipientType get values from ReactiveModules.Email.RecipientTypes. I've already create a recipient type in ReactiveModules.Email.RecipientTypes. But when create Recipients, the popup for RecipientType field show no value
Recipients
![image](https://user-images.githubusercontent.com/69721339/160271820-1ec4d0f4-38d4-4ec9-a377-b1883ab082ee.png)

**Comment by apobekiaris** [comment]
until fixed possible workarounds is either code assigment or modify the xafml file. The lookup is only used with the ME

**Comment by apobekiaris** [comment]
The pre-release [4.212.8.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.212.8.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Email: Populate Recipients list when ME #918](https://github.com/eXpandFramework/Reactive.XAF/commit/0d8e0752129972ea7de24eaca90aea425da119cc)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Net461 v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft'>Xpand.XAF.Modules.Office.Cloud.Microsoft v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.212.8</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.212.8</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by garung1611** [comment]
> The pre-release [4.212.8.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.212.8.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch includes commits that relate to this task:
> 
> * [Email: Populate Recipients list when ME #918](https://github.com/eXpandFramework/Reactive.XAF/commit/0d8e0752129972ea7de24eaca90aea425da119cc)
> 
> To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
> 
> Released packages:
> Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).
> 
> If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.
> 
> Thanks a lot for your contribution.

Is this version ready available on nuget channel?

**Comment by apobekiaris** [comment]
exists on lab servers

no only in lab https://xpandnugetserver.azurewebsites.net/nuget

**Comment by garung1611** [comment]
Firstly I want to say sorry because after the first reading, I don't understand clearly this paragragh: **"Released packages:
Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/)**.". So sorry because I don't have much experience with nuget. I've checked on above link and see that
![image](https://user-images.githubusercontent.com/69721339/160282991-90f213cb-9ae0-47fe-bf63-26dda3f75d8b.png)
It said Date published is from 24/03/2022, but this commit "Email: Populate Recipients list when ME #918", you just updated today so is the version on https://xpandnugetserver.azurewebsites.net/nuget updated?

**Comment by apobekiaris** [comment]
add it in your package sources and u can consume lab packages as well

![image](https://user-images.githubusercontent.com/159464/160283969-1d37b559-769f-4659-a9cb-1a1afbecaf47.png)

**Comment by apobekiaris** [comment]
latest version os 
```
 get-xpandpackages -Source Lab -PackageType XAFModules

Id                                                Version   Source
--                                                -------   ------
Xpand.XAF.Modules.AutoCommit                      4.212.8.7 Lab
Xpand.XAF.Modules.Blazor                          4.212.8.7 Lab
Xpand.XAF.Modules.BulkObjectUpdate                4.212.8.7 Lab
Xpand.XAF.Modules.CloneMemberValue                4.212.8.7 Lab
Xpand.XAF.Modules.CloneModelView                  4.212.8.7 Lab
Xpand.XAF.Modules.Email                           4.212.8.7 Lab
Xpand.XAF.Modules.GridListEditor                  4.212.8.7 Lab
Xpand.XAF.Modules.HideToolBar                     4.212.8.7 Lab
Xpand.XAF.Modules.JobScheduler.Hangfire           4.212.8.7 Lab
Xpand.XAF.Modules.JobScheduler.Notification       4.212.8.7 Lab
Xpand.XAF.Modules.LookupCascade                   4.212.1.4 Lab
Xpand.XAF.Modules.MasterDetail                    4.212.8.7 Lab
Xpand.XAF.Modules.ModelMapper                     4.212.8.7 Lab
Xpand.XAF.Modules.ModelViewInheritance            4.212.8.7 Lab
Xpand.XAF.Modules.Office.Cloud.Google             4.212.8.7 Lab
Xpand.XAF.Modules.Office.Cloud.Google.Calendar    4.212.8.7 Lab
Xpand.XAF.Modules.Office.Cloud.Google.Tasks       4.212.8.7 Lab
Xpand.XAF.Modules.Office.Cloud.Microsoft          4.212.8.7 Lab
Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar 4.212.8.7 Lab
Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo     4.212.8.7 Lab
Xpand.XAF.Modules.Office.DocumentStyleManager     4.212.8.7 Lab
Xpand.XAF.Modules.OneView                         4.212.8.7 Lab
Xpand.XAF.Modules.PositionInListView              4.212.8.7 Lab
Xpand.XAF.Modules.ProgressBarViewItem             4.212.8.7 Lab
Xpand.XAF.Modules.RazorView                       4.212.8.7 Lab
Xpand.XAF.Modules.Reactive                        4.212.8.7 Lab
Xpand.XAF.Modules.Reactive.Logger                 4.212.8.7 Lab
Xpand.XAF.Modules.Reactive.Logger.Client.Win      4.212.8.7 Lab
Xpand.XAF.Modules.Reactive.Logger.Hub             4.212.8.7 Lab
Xpand.XAF.Modules.Reactive.Rest                   4.212.8.7 Lab
Xpand.XAF.Modules.RefreshView                     4.212.8.7 Lab
Xpand.XAF.Modules.SequenceGenerator               4.212.8.7 Lab
Xpand.XAF.Modules.SuppressConfirmation            4.212.8.7 Lab
Xpand.XAF.Modules.TenantManager                   4.212.8.7 Lab
Xpand.XAF.Modules.ViewEditMode                    4.212.8.7 Lab
Xpand.XAF.Modules.ViewItemValue                   4.212.8.7 Lab
Xpand.XAF.Modules.ViewWizard                      4.212.8.7 Lab
Xpand.XAF.Modules.Windows                         4.212.8.7 Lab
```

the message has a wrong version

**Comment by apobekiaris** [comment]
u always go for the latest version and if has revision it means is only available in lab, when in nuget.org there are no version revisions

**Comment by garung1611** [comment]
yes, i understand that point and already add before
![image](https://user-images.githubusercontent.com/69721339/160284142-84169f42-4a76-4b81-833b-9680398c047e.png)
from the image on my previous comment, you can see i've already choose your nuget channel
![image](https://user-images.githubusercontent.com/69721339/160284229-dddf96a2-2442-49ee-bc5d-7ef8712c3ed6.png)
But now, I've closed and reopened VS, I see the Date published  is 27/03/2022. Eveything seems to be ok now.

**Comment by garung1611** [comment]
> 

Thanks, I got it

**Comment by apobekiaris** [comment]
latest version is `4.212.8.7` not 4.212.8.6

**Comment by garung1611** [comment]
> latest version is `4.212.8.7` not 4.212.8.6

exactly

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
