### ISSUE TITLE
Some suggestions to improve expand framework

### ISSUE THREAD

**Issue by garung1611** [eXpandFramework/eXpand#919]
Based on expecting to improve expand framework, I have some suggestion as follow:
 1. From my newbie point of view, I think, If you want this useful framework to be more popular, you need to invest time to write more detail guide. It will be much much better for newbie like me. I know, from your point, guides are good enough. But you should consider from less experience guys.
 2. Intergrating some well known messaging API like Telegram, Skype, Signal, WhatsApp...
 3. Intergrating Signalr so instead of periodic pulling from clients, we can pushing new information from server to specific clients. Beside it, we can track online, offline state of users.
 4. Intergrating badges to Blazor, so from navigation or somewhere, we can easily identify how many new objects has been created...
 5. Make State Machine more generic, i means with specific transitions we can add more logic, for example: from State A to B, the app will show popup to ask users to add some more information, from state B to C, besides changing the state, the app also change some property according to specific logic...
 6. Import module for Blazor
 7. Sequence genegrator should be more generic. For example: document ID code has structure like this: Year code / Type code / document code / ID generator. 22/EX/IS/0001 (Ex: expand, IS: Issue), 21/RE/CD/001 (RE: Reactive.XAF, CD: Code)...

**Comment by apobekiaris** [comment]
>From my newbie point of view, I think, If you want this useful framework to be more popular, you need to invest time to write more detail guide. It will be much much better for newbie like me. I know, from your point, guides are good enough. But you should consider from less experience guys.

I always improve and this a framework meaning once u understadn one u apply it to all

>Intergrating some well known messaging API like Telegram, Skype, Signal, WhatsApp...

telegram is baking

>Intergrating Signalr so instead of periodic pulling from clients, we can pushing new information from server to specific clients. Beside it, we can track online, offline state of users.

I think this is Xaf job and not mine and there is already support for it

>Make State Machine more generic, i means with specific transitions we can add more logic, for example: from State A to B, the app will show popup to ask users to add some more information, from state B to C, besides changing the state, the app also change some property according to specific logic...

meaning? don't we have already chained hangfire jobs isn't this a transition

>Import module for Blazor

once some company has the need and pay for my efforts happy to do my best

**Comment by garung1611** [comment]
>always improve and this a framework meaning once u understadn one u apply it to all
>
just some suggestions with hoping that  expand framework will be better and more popular only
> I think this is Xaf job and not mine and there is already support for it
>
I think making Xaf works with Signalr is  Xaf job but they will not build some functionality like: integrating Signalr with User role structure so the app can track online, offline user, admin user can send some notification to specific user, or when some event (object created, object deleted, object change state...) happen, app can send notification to related user 
> meaning? don't we have already chained hangfire jobs isn't this a transition
>
for example: when I approve the document, I want to show message: "Document approved", when I decline one document, I want the app to show popup where I can type in the reason why I decline the document, or when i approve documents, i want sub document (document belongs to parent documents) to be approved to and besides state property, some other property like ApprovedDate need to be updated too. Up to now, I've to do that by create custom StateMachineController
> once some company has the need and pay for my efforts happy to do my best
>
hope to sell some apps so i can support you in the future
>Sequence genegrator should be more generic. For example: document ID code has structure like this: Year code / Type code / document code / ID generator. 22/EX/IS/0001 (Ex: expand, IS: Issue), 21/RE/CD/001 (RE: Reactive.XAF, CD: Code)...
>

>Intergrating badges to Blazor, so from navigation or somewhere, we can easily identify how many new objects has been created...
>
and what about this?

**Comment by apobekiaris** [comment]
>Sequence genegrator should be more generic. For example: document ID code has structure like this: Year code / Type code / document code / ID generator. 22/EX/IS/0001 (Ex: expand, IS: Issue), 21/RE/CD/001 (RE: Reactive.XAF, CD: Code)...

cannot answer this without spending considerable ammount in research /realization, however since with already have sub sequences my guess is with some extra BO properties u can achieve it

>Intergrating badges to Blazor, so from navigation or somewhere, we can easily identify how many new objects has been created...

no idea what u mean and how this is valueable to u

**Comment by apobekiaris** [comment]
>just some suggestions with hoping that expand framework will be better and more popular only

thnks for the feedback however this an old framework at least this repo and not designed properly, the rx repo however behaves like a unit making support easier and having tests/docs to improve quality. 

Of course docs need a lot more work so PR are always acceptabl;e from people that use the packages daily. Cause really I do not use them all and packages like SequenceGenerator not valueable in my apps, So I guess u are the expert on the package rather than me that I code it.

**Comment by garung1611** [comment]
>no idea what u mean and how this is valueable to u
>
not just for me, for all community who pay attention on your framework. I thinks badges (is the term exactly? sorry for my bad english, badges like this https://getbootstrap.com/docs/4.0/components/badge/) is very useful and it appear everywhere
from gmail, you can quickly got how many email unread
![image](https://user-images.githubusercontent.com/69721339/160321177-c358c633-813f-472d-bcb8-cd8ecabc1cbb.png)
to facebook, you can quickly got how many new notification or unread messages
![image](https://user-images.githubusercontent.com/69721339/160321266-f4dfc84e-cbdc-4525-a3a9-43a98e8fcdd4.png)
>Of course docs need a lot more work so PR are always acceptabl;e from people that use the packages daily. Cause really I do not use them all and packages like SequenceGenerator not valueable in my apps, So I guess u are the expert on the package rather than me that I code it.
>
hope to contribute to your framework in the future. My english and coding style is bad :(

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
