### ISSUE TITLE
Replacement for ISupportSequenceObject.Prefix in agnostic SequenceGenerator

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#921]
Hi,

I'm currently trying to migrate from the old eXpand SequenceGenerator to the 'new' Reactive.XAF SequenceGenerator module.
I am using the ISupportSequenceObject.Prefix property to generate unique sequences based on a property of the target entities. I wonder how to archive the same with the new SequenceGenerator implementation. There is a new SequenceStorageKeyName attribute, but it's lacking documentation and I don't know if this is what I should use.

Any help is appreciated!

**Comment by apobekiaris** [comment]
I am not sure either cause I presonally do not use the package and  for creating a sample it requires research time, 

I see a related test that might be of help https://github.com/eXpandFramework/Reactive.XAF/blob/16fda8ed431d6a11b5e119f03def866fe2a761d1/src/Tests/SequenceGenerator/SequenceGeneratorTests.cs#L200

maybe @CWolffIF or @isatahiri can help on this one?

**Comment by asmolarczyk** [comment]
Thank you,
I also found this test, but either I don't understand the impl or it is is not sufficient for my requirement:

In the test SequenceStorageKeyName is used to change the 'Name' field of the SequenceStorage object from CustomSquenceNameTestObject to CustomSequenceTypeName at compile time.
I don't know how to create multiple SequenceStorage objects for CustomSquenceNameTestObject based on a property.

Any help of @CWolffIF or @isatahiri is very appreciated

**Comment by krombipils** [comment]
Thank you,
I also found this test, but either I don't understand the impl or it is is not sufficient for my requirement:

In the test SequenceStorageKeyName is used to change the 'Name' field of the SequenceStorage object from CustomSquenceNameTestObject to CustomSequenceTypeName at compile time.
I don't know how to create multiple SequenceStorage objects for CustomSquenceNameTestObject based on a property.

Any help of @CWolffIF or @isatahiri is very appreciated
