### ISSUE TITLE
Blazor OData/MiddleTier: Decreased performance due to harmony Patch applied on every request

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#922]
This question/request is related to my [issue ](https://supportcenter.devexpress.com/ticket/details/t1078291) at DevExpress:

I'm currently evaluating performance of the new WebApi based MiddleTier and OData implementation. In the Azure Profiler I noticed quite a lot of time is spent in the harmony patch methods, e.g. in [ObjectSpaceProviderExtensions](https://github.com/eXpandFramework/Reactive.XAF/blob/master/src/Modules/Reactive/Services/ObjectSpaceProviderExtensions.cs).

The problem is that OnSetupComplete of the BlazorApplication is called for every http request to the odata/middletier service.
I wonder whether it is possible to apply the patches only once when using blazor?

**Comment by apobekiaris** [comment]
I guess u refer to this code

```cs
AppDomain.CurrentDomain.Patch(harmony => {
                        application.PatchSchemaUpdated(harmony);
                        application.PatchObjectSpaceCreated(harmony);
                    });
```

however both methods do not patch if alredy pathed

```cs
var methodBases = harmony.GetPatchedMethods().Select(m => m.Name);
            var name = $"{typeof(IObjectSpaceProvider).FullName}.{nameof(IObjectSpaceProvider.UpdateSchema)}";
            if (methodBases.All(s => s != name)) {
```

```cs
private static void PatchObjectSpaceCreated(this XafApplication application, Harmony harmony) {
            var name = nameof(IObjectSpaceProvider.CreateObjectSpace);
            if (harmony.GetPatchedMethods().Select(m => m.Name).All(s => s != name)) {
```

so where the time spent? in the `GetPatchedMethods` ??

**Comment by krombipils** [comment]
Sorry for the late reply.

You are right, in PatchObjectSpaceCreated and PatchSchemaUpdated you check for existing patches before calling harmony.Patch(...). But in [SecurityExtensions.PatchAuthentication](https://github.com/eXpandFramework/Reactive.XAF/blob/07c52fabd91388ab858200a6853ffef9c59a74dc/src/Modules/Reactive/Services/Security/SecurityExtensions.cs#L28) this check is missing.
I manually added the check and now the performance is way better:
 
    AppDomain.CurrentDomain.Patch(harmony =>
    {
        const string name = nameof(Authenticate);
        if (harmony.GetPatchedMethods().Select(m => m.Name).Any(s => s == name))
        {
            return;
        }

        if (Security.IsInstanceOf("DevExpress.ExpressApp.Security.SecurityStrategyBase"))
        {
            ...
        }
    });

Unfortunately it is quite hard to say what's going on (in the Profiler I only see that for my simple requests 99% of cpu time is spent in kernel), but harmony.Patch throws quite a lot of (first chance) ArgumentExceptions.
This seems to be the cause of the bad performance on Azure. I cannot reproduce this performance problem on a local machine, but I think adding the check is safe und consistent with your other patches.

What do you think? Thank you!

**Comment by apobekiaris** [comment]
I am not sure how and if Harmony repatching makes it slower but sure I can add an additional check. Please replay back if the performance improved

**Comment by apobekiaris** [comment]
>I manually added the check and now the performance is way better:

oh i missed it so its a go then, thnks for it!

**Comment by apobekiaris** [comment]
>application.WhenSetupComplete()

the patch is done after the setup meaning it only happends **once** on its request, wonering how many concurrent requests are u testing or what thoughts u can share on this.

ps: I will add the check as u already happy with it

**Comment by krombipils** [comment]
> the patch is done after the setup meaning it only happends **once** on its request,

You are right, but the new [backend-web-api-service](https://docs.devexpress.com/eXpressAppFramework/403394/backend-web-api-service) is stateless. So for every http get/post request a new XafApplication instance is created, modules are created, OnSetupCompleted is executed, OnLogged is executed and so on.

Therefore it is really important to do as little work as possible. E.g. in one of my own modules I checked some permissions in the OnLoggedOn event. This was fine in a XAF Win/Web app (because it was executed exactly once for a user sesssion). But in the backend-web-api-service this was a performance killer...

**Comment by apobekiaris** [comment]
i see many components start background requests e.g. Dashboard, sometimes it can hurt true, great this part is improved let move on.

**Comment by apobekiaris** [comment]
The pre-release [4.212.9.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.212.9.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Harmony delays fix #922](https://github.com/eXpandFramework/Reactive.XAF/commit/3dcca862e2d2c108460f7e652935329730796901)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Net461 v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft'>Xpand.XAF.Modules.Office.Cloud.Microsoft v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.212.9</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.212.9</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Just tried to test your fix in 4.212.9.7. Unfortunately it now throws a NullReferenceException in https://github.com/eXpandFramework/Reactive.XAF/blob/1da6367aee4190a07129ab4119ce3804c8fb25b5/src/Modules/Reactive/Services/AttributesExtensions.cs#L36

![grafik](https://user-images.githubusercontent.com/8317504/173526040-01420f2b-0fa1-4680-8386-8193db2b5bcc.png)

application.Model.ToReactiveModule<IModelReactiveModule>() returns null. Any idea what could be wrong?
Thank you!

**Comment by apobekiaris** [comment]
>. Any idea what could be wrong?

me that forgot to register this last minute addon stripped out of anothher project

**Comment by krombipils** [comment]
So I guess I have to what for new pre-release or is it possible to register it on my own?

**Comment by apobekiaris** [comment]
sorry i guesses u moniring the builds, I sent a build already but failed cause the previous one also tests failed although it managed to publish the packages. Long story short I am fixing it the fix source is in the lab already in case u needed now

**Comment by apobekiaris** [comment]
https://github.com/eXpandFramework/Reactive.XAF/commit/74e74e095bd3aebdf391c99e7fb78d27760197cc

**Comment by krombipils** [comment]
I think this can be closed now. Everything is working fine for me. Thank you!
