### ISSUE TITLE
Updating from 19.2.6 to current version

### ISSUE THREAD

**Issue by sergejoz** [eXpandFramework/eXpand#923]
Hello! I wanted to update from 19.2.6 to current version and wanna ask what is the easiest way to do it? As i can see you dont use pwsh line to update anymore? how can i install all nuget packages to replace old refs in a big project?
![image](https://user-images.githubusercontent.com/43649713/160606891-85dd9a83-1c18-4245-a26e-c398d74fae27.png)

**Comment by apobekiaris** [comment]
as per video

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules

**Comment by apobekiaris** [comment]
remove all existing deps first

**Comment by apobekiaris** [comment]
u wanna use the Xpand.ExpressApp container packages instead of the RX demoed in the video

@{Id=Xpand.XAF.Core.All; Version=4.212.8.8; Source=Lab}
@{Id=Xpand.XAF.Web.All; Version=4.212.8.8; Source=Lab}
@{Id=Xpand.XAF.Win.All; Version=4.212.8.8; Source=Lab}

**Comment by apobekiaris** [comment]
apologies I paste the RX containers the main container are

@{Id=eXpandAgnostic
@{Id=eXpandWin
@{Id=eXpandWed

**Comment by sergejoz** [comment]
Thank u for fast answer!

Tried to install a package to one of my modules and getting this:

Attempting to gather dependency information for package 'eXpandAgnostic.21.2.601' with respect to project 'VersionningModule', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 17.63 sec
Attempting to resolve dependencies for package 'eXpandAgnostic.21.2.601' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'Xpand', 'DevExpress 21.2 Local', 'Microsoft Visual Studio Offline Packages'.
Time Elapsed: 00:00:18.2257395
========== Finished ==========

**Comment by sergejoz** [comment]
I thought everythining is working but cant open Module or Module.Win model. Works fine in other modules. Didnt get any error, my VS just closes. Tried with clean project, get the same. Any suggestions?

**Comment by apobekiaris** [comment]
maybe try VS as Admin? to get more info

**Comment by sergejoz** [comment]
Already tried, nothing new
