### ISSUE TITLE
Xpand Model editor for net 5 (or net 6) project is asking for missing net core

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#924]
Hi, I had installed Vs2019 and vs2022  in a windows 11 machine. All is running fine, but when trying to use Model editor for a net core xaf module, it fails to start and ask for a missing net core instalation

![image](https://user-images.githubusercontent.com/226800/162057804-301d34e1-1615-4e7d-8620-7fab80e2c532.png)

reinstalled net 5 x86 sdk, net6 sdk x86, what else is needed?

**Comment by apobekiaris** [comment]
apologies i missed this case, the error comes from the .NET directly does not look Xpand related, and it will redirect u to the related download page. Assuming u download the runtime and install it i guess a restart might fix it? possibly .net enviromental vars are not initialized?

**Comment by apobekiaris** [comment]
I did not manage to repro it, however I migated the plugin solely for VS22, it is now published you can try it. *XVSIX64*

**Comment by vimarx** [comment]
> I did not manage to repro it, however I migated the plugin solely for VS22, it is now published you can try it. _XVSIX64_

Sorry, where is located?

**Comment by apobekiaris** [comment]
![image](https://user-images.githubusercontent.com/159464/168274401-729770bb-9b03-40ae-aca2-ed2ec7dc8457.png)

**Comment by txt2203** [comment]
I tried XVSIX64 for VS2022. This is some problems I found:
When  Xpand Model projects list window opened : 
+ Double click to a Module item => then Xpand Model Editor will open  with full items correctly. Close it normally.
+ Select Module item and press button "Configure" => A "Xpand Model Editor" open but not full items compared with Devexpress model editor or above case (this case same with one for VS2019). See picture. I think Xpand opened another App. Closing this window will reopen itself several times (and I have to close it by hand) before closing completely.
![Xpand-VS2022-0](https://user-images.githubusercontent.com/55611923/168276286-0414460f-e1e7-426b-92ba-456dba1ff15b.png)

**Comment by apobekiaris** [comment]
the model editor u get from the `Configure` action is for the XpandModelEditor and not for your apps, yes there is a bug once u use but in general u should not need to configure it.

I cannot tell aboiut your exception without exact repro steps or a sample, at my side works fine

**Comment by vimarx** [comment]
Can't download, cannot connect to remote server (I tried several times today)
![image](https://user-images.githubusercontent.com/226800/168373908-31a4a604-f24d-409b-9677-12bbe86a6373.png)

**Comment by vimarx** [comment]
HI, I managed to install it using Visual studio MarketPlace website.
Now Model Editor , starts, open briefly the model windows and dissapears 

from the attached log, I look at
`Type:       InvalidProjectFileException
	Message:    The imported project "C:\Program Files\dotnet\sdk\5.0.408\Microsoft\VisualStudio\v17.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.408\Microsoft\VisualStudio\v17.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.  C:\Repos\DesarrolloGit\F2011\PreSolicitud\PresolicitudW.Web\PresolicitudW.Web.vbproj
	Data:       0 entries
	Stack trace:`

in my PC there is no VisualStudio Folder inside C:\Program Files\dotnet\sdk\5.0.408\Microsoft, and the same for all the other Sdks I have installed.

What else can I try?

Thanks

[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/8691582/eXpressAppFramework.log)

**Comment by apobekiaris** [comment]
>Microsoft.WebApplication.targets

the editor support .NET5 projects and above

**Comment by vimarx** [comment]
but do not even start for mixed solutions?

**Comment by vimarx** [comment]
So there is no VS2022 upgrade for the net.framework model editor in vsix for vs2019 ??

**Comment by apobekiaris** [comment]
I am not sure what u mean, but i see no reason to support VS22 and VS19, we should go for VS22

**Comment by apobekiaris** [comment]
> connect to remote server

the ME editor is download from the Github RX repo. This is about Github connectivity, does it persist?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
