### ISSUE TITLE
Xpand.XAF.Modules.JobScheduler.Hangfire - context.JobId() desn't giving the persistent job id

### ISSUE THREAD

**Issue by dixboss** [eXpandFramework/eXpand#926]
context.JobId() doesn't give the persistent job id but a Hangfire.Server.PerformContext JobId in GUI.

**[JobProvider]
public async Task ImportTask(PerformContext context) {
var jobId = context.JobId(); // I'm getting a GUI ID
}**

**Comment by apobekiaris** [comment]
see 

>Use a Job descendant to pass job specific parameter

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire

**Comment by dixboss** [comment]
context.JobId() is giving a CS0012 error with IStorageConnection of  Hangfire.Core" Version="1.7.24"
I'm trying to get the Id by:

 var jobId = context.Connection.GetRecurringJobs().FirstOrDefault(id => id.LastJobState == "Processing")?.Id;

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
