### ISSUE TITLE
Namespace missing 

### ISSUE THREAD

**Issue by igortanaskoski** [eXpandFramework/eXpand#932]
Hi,
We suspect there is a bug in the Excelimporter.web module.
As you can see in the screenshot it seems there is no Web namespace in the eXpand.ExcelImporter.Web nuget package.

steps to recreate:
We created a new empty XAF solution( .Net core + Blazor + XPO + Standard Authentication) without modules.
Build this solution and then add the nuget package eXpand.ExcelImporter.Web in the {ProjectName}.Module.Blazor project. Again we did build the solution without problems.
After this we have added the required registration line RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Web.ExcelImporterWebModule)); in the BlazorModule.cs and as you can see from the screenshot there is a problem.

Is it something on our end or is the namespace really missing?
Thanks
![Screenshot 2022-05-07 175438](https://user-images.githubusercontent.com/48704545/167262051-94f64035-b2ee-48ba-ae03-18628041ff01.png)

**Comment by apobekiaris** [comment]
eXpand.ExcelImporter.Web is not ported to Blazor

**Comment by igortanaskoski** [comment]
thanks, now it makes sense .
