### ISSUE TITLE
Devexpress v22.1 & eXpand v22.1 

### ISSUE THREAD

**Issue by ugurozyildiz** [eXpandFramework/eXpand#935]
Hi, when will you release Devexpress v22.1 proper expand version ?

**Comment by krombipils** [comment]
I'm also very interested in a 22.1 (beta) release. I wonder whether VersionConverter (if re-enabled) could be used to test 22.1?! I tried it on my own (removing the 'return' as you [suggested](https://github.com/eXpandFramework/eXpand/issues/911#issuecomment-1053931084)) without success

**Comment by apobekiaris** [comment]
still in beta I am sorry, have endless more important tasks

**Comment by apobekiaris** [comment]
in any case just subribe to this repo and get notified when a compatible build is out

**Comment by ugurozyildiz** [comment]
Thanks for your support and feedback.

**Comment by apobekiaris** [comment]
need to update as I fall late here due to illness, but all rx tests except JobScheduler are now green at least locally. Next they must also pass on Azure, next is a production integration of my internal apps and finally an update of this repository. I still cannot estimate exatct times though most of the work looks complete

**Comment by ugurozyildiz** [comment]
Thank you very much for your support and efforts.

**Comment by apobekiaris** [comment]
fyi comaptible packages are now on lab server https://xpandnugetserver.azurewebsites.net/nuget

**Comment by dsikic** [comment]
Thanks!

Sent from my iPhone

On Jul 5, 2022, at 13:17, Apostolis Bekiaris ***@***.***> wrote:

﻿

fyi comaptible packages are now on lab server https://xpandnugetserver.azurewebsites.net/nuget<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxpandnugetserver.azurewebsites.net%2Fnuget&data=05%7C01%7C%7C1293e8d8262740b1fd0208da5eaa4d45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637926382772272648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=72QC4a%2Fmn%2FtKbq5LpSRc1cVgfbEFla5uEjfAgtZTNoQ%3D&reserved=0>

**Comment by ugurozyildiz** [comment]
Thank you very much for your work , "githup or nuget"  when can we download it from  ?

![image](https://user-images.githubusercontent.com/60185974/177479028-bfae0d82-f6c5-41a3-a101-079a10536e14.png)

![image](https://user-images.githubusercontent.com/60185974/177478822-f699264c-c6bc-4a03-9a2f-0f0468946d0f.png)

**Comment by apobekiaris** [comment]
1-2 days top I need to verify that at least my internal apps work with these packages while possibly get additional feedback from people try out the lab version

**Comment by apobekiaris** [comment]
nope it wasn't even .net5 remain net461 cause it has 3rd party dependecies e.g. OWIN that will never get updated

**Comment by krombipils** [comment]
22.1.300 is working fine for me. Thank you!

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
