### ISSUE TITLE
Error when I open the model of the module Win

### ISSUE THREAD

**Issue by GillesBrice** [eXpandFramework/eXpand#937]
Hello, after I update to 20.2.8, I have an error when I open the model of the module Win.

Here what the error say :

_One or more errors were encountered while loading the designer. The errors are listed below. Fixing some of the errors may require code or model changes.

Exception occurs while creating Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController
Unable to create an instance of the "Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController" type.
Reason: "Une exception a été levée par l'initialiseur de type pour 'Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController'."

à DevExpress.ExpressApp.Core.ControllersManager.CreateController(Type controllerType)
   à DevExpress.ExpressApp.Core.ControllersManager.RegisterControllerTypes(IEnumerable`1 controllerTypes)
   à DevExpress.ExpressApp.ApplicationModulesManager.RegisterControllerTypes()
   à DevExpress.ExpressApp.ApplicationModulesManager.LoadCore(ITypesInfo typesInfo)
   à DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   à DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance, Action initializeTypeInfoSources)
   à DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   à DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   à DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
----------InnerException----------
Unable to create an instance of the "Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController" type.
Reason: "Une exception a été levée par l'initialiseur de type pour 'Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController'."
----------StackTrace----------
   à DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   à DevExpress.ExpressApp.Controller.Create(Type controllerType)
   à DevExpress.ExpressApp.Core.ControllersManager.CreateController(Type controllerType)
----------InnerException----------
Une exception a été levée par l'initialiseur de type pour 'Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController'.
----------StackTrace----------
   à Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController..ctor()
   à Create_ChooseDatabaseAtLogonController()
   à DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
----------InnerException----------
Impossible de charger le fichier ou l'assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ou une de ses dépendances. Le fichier spécifié est introuvable.
----------StackTrace----------
   à Xpand.ExpressApp.Security.Controllers.ChooseDatabaseAtLogonController..cctor()_

Do you have a solution for me please ?

**Comment by GillesBrice** [comment]
Sorry it's not the 20.2.8, it's the 21.2.8.

**Comment by apobekiaris** [comment]
can u repro it on an empty solution with the latest version? 22.1.301 install the security package and run it, and if failed the same post it here for research

**Comment by apobekiaris** [comment]
>open the model 

I missed this part, so did you tried the Xpand Model Edditor is by far more reliable the VS designers

**Comment by GillesBrice** [comment]
Installing the 22.1.301 version, solve my issue.

Thank you for your time.
