### ISSUE TITLE
InvalidCastException in Xpand.Persistent.Base.dll

### ISSUE THREAD

**Issue by GillesBrice** [eXpandFramework/eXpand#938]
Hello,

I install the 22.1.3 and when I run my application I got this exception :

```
Exception levée : 'System.InvalidCastException' dans Xpand.Persistent.Base.dll
Une exception non gérée du type 'System.InvalidCastException' s'est produite dans Xpand.Persistent.Base.dll
Impossible d'effectuer un cast d'un objet de type 'DevExpress.ExpressApp.DC.IEntityStore[]' en type 'System.Collections.Generic.List`1[DevExpress.ExpressApp.DC.IEntityStore]'.
```

Do you have a solution please ?

**Comment by apobekiaris** [comment]
from the info you posted impossible to even guess, provide a sample solution or repro details

**Comment by GillesBrice** [comment]
I create a sample from my solution, it's in attachment.
When I run my application, I got the exception.

[Test.zip](https://github.com/eXpandFramework/eXpand/files/9093080/Test.zip)
.

**Comment by apobekiaris** [comment]
I can repro it will update this post once i know why

**Comment by apobekiaris** [comment]
i fixed the problem however your sample won't start cause the Security.RoleType is not assinged, I cannot spent time debugging your app. If you can modify your sample assinging a roletype which I guess you stript it out I can rerun it. Else wait for the build and test the fix

**Comment by apobekiaris** [comment]
eXpand.lab release [22.1.301.1](https://github.com/eXpandFramework/eXpand.lab/releases/22.1.301.1) includes commit that relate to this task:

* [22.1 breaking changes #938](https://github.com/eXpandFramework/eXpand.lab/commit/a168a5f16e1c88679d3e704ec0f7b2b31ca3c3e8)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by GillesBrice** [comment]
I works great now. Thank you very much for your time and reactivy.

**Comment by apobekiaris** [comment]
eXpand.lab release [22.1.302.1](https://github.com/eXpandFramework/eXpand.lab/releases/22.1.302.1) includes commit that relate to this task:

* [22.1 breaking changes #938](https://github.com/eXpandFramework/eXpand.lab/commit/6a551aaedaf72e5ddd3ac46a2440ccf282fdf4b0)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.400.0) includes commit that relate to this task:

* [22.1 breaking changes #938](https://github.com/eXpandFramework/eXpand.lab/commit/a1661fb442281a0ab8ed44dba30993b7e5d6edb6)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.
