### ISSUE TITLE
Exception while trying to open model editor in 22.1.302

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#939]
Excepción producida: 'System.MissingFieldException' en Fasterflect.dll
15.07.22 14:20:19.451	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Se han producido uno o varios errores.
	Data:       0 entries
	Stack trace:

   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Utils.Helpers.Retry.Do(Action action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(Boolean tryToUseCurrentTypesInfo, Action`1 action)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModelCore(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModel(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.OnCurrentObjectChanged()
   en DevExpress.ExpressApp.Editors.ViewItem.set_CurrentObject(Object value)
   en DevExpress.ExpressApp.ObjectView.InitializeItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.AddItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.LoadModelCore()
   en DevExpress.ExpressApp.View.LoadModel()
   en DevExpress.ExpressApp.View.SetModel(IModelView model)
   en Xpand.ExpressApp.ViewFactory.CreateDetailView(XafApplication xafApplication, String viewId, IObjectSpace objectSpace, Object obj, Boolean isRoot, Boolean enableDelayedObjectLoading)
   en Xpand.ExpressApp.SystemModule.XpandSystemModule.ApplicationOnDetailViewCreating(Object sender, DetailViewCreatingEventArgs args)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   en DevExpress.ExpressApp.XafApplication.PrepareDetailViewCreatingEventArgs(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading)
   en DevExpress.ExpressApp.XafApplication.CreateDetailViewCore(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Type objectType, Object objectKey, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       MissingFieldException
			Message:    No match for field with name objectSpaceProviders and flags Instance | NonPublic | Public | Static on type F.Win.FWindowsFormsApplication.
			Data:       0 entries
			Stack trace:

   en Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo)
   en Fasterflect.Emitter.MemberGetEmitter.CreateDelegate()
   en Fasterflect.Emitter.BaseEmitter.GetDelegate()
   en Fasterflect.FieldExtensions.DelegateForGetFieldValue(Type type, String name, Flags bindingFlags)
   en Fasterflect.FieldExtensions.GetFieldValue(Object obj, String name)
   en Xpand.Persistent.Base.General.ApplicationBuilder.Build()
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.<>c__DisplayClass12_0.<GetMasterModel>b__0()
   en Xpand.Utils.Helpers.Retry.<>c__DisplayClass0_0.<Do>b__0()
   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
			InnerException is null

================================================================================

**Comment by apobekiaris** [comment]
it looks like it is about ModelDifference package, can you test against an empty solution having installed only this package and upload your sample here. It will for sure speed up case resolution

**Comment by Siratigui** [comment]
#940

**Comment by Siratigui** [comment]
same issue here  #940

**Comment by apobekiaris** [comment]
same reply.

>it looks like it is about ModelDifference package, can you test against an empty solution having installed only this package and upload your sample here. It will for sure speed up case resolution

**Comment by Siratigui** [comment]
I wrote some suggestions here #940 you can have a look

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
