### ISSUE TITLE
Error XAF0017	Incompatible assemblies are referenced in the same project

### ISSUE THREAD

**Issue by txt2203** [eXpandFramework/eXpand#945]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
For standard XAF .NET 6, After adding Nuget Package Xpand.XAF.Core.All to project XXX.module, it show error after build : 
+ Error XAF0017	Incompatible assemblies are referenced in the same project: 'DevExpress.ExpressApp.Chart.Win.v22.1' and 'DevExpress.Blazor.v22.1'	XXX.Win	...\Visual Studio 2022\Projects\XXX\XXX.Win\CSC
+ Error XAF0017	Incompatible assemblies are referenced in the same project:  'DevExpress.ExpressApp.Office.Win.v22.1' and 'DevExpress.Blazor.v22.1' XXX.Win	...\Visual Studio 2022\Projects\XXX\XXX.E2E.Test\CSC

=> I could not find DevExpress.Blazor.v22.1 in Win project. Maybe it refer from source code of Xpand.XAF.Core.All ?
Thanks.

**Comment by apobekiaris** [comment]
if u want to try the lab packages, these is this commit in the lab servers https://github.com/eXpandFramework/Reactive.XAF/commit/5d5659f758234335616ead17d67ded0a8ae45205 nugts avaiable if the lab as well that is probably fixing the issue when the next release.

else you need to manually lower the severity of the DX analyzer by suppressing the warning

e.g. https://github.com/eXpandFramework/Reactive.XAF/search?q=XAF0017

note that the Xaf team wil decresase the severity from error to warning in the next release as well

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
