### ISSUE TITLE
Appearence rule in MasterDetail (detail object)

### ISSUE THREAD

**Issue by rodrigokiller** [eXpandFramework/eXpand#953]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
Hi. I would like to know if it is possible to use the appearance rule on an object that is a detail from a master-detail view. disabling an action. The appearance rule works when I do this on the child object:
```c#
[Appearance("Executando", TargetItems = "*", Criteria = "1=1", BackColor = "PaleTurquoise")]
```
but doesn't work when I do this on the child object:
```c#
[Appearance("ActionVisibility", AppearanceItemType = "Action", TargetItems = "Delete", Criteria = "1=1", Context = "Any", Enabled = false)]
```
I can provide a sample project if needed.

Thank you.

**Comment by apobekiaris** [comment]
This package lives in the category I am happy with it does and will not get much support with it. I already mentioned to you how it works and that is incomplete. Apparentky the way it binds the child frames has issues. The module was not developed for years, look its history.   If you have a simple case and not expect 100% Xaf working for childviews then it might be good to you.

**Comment by rodrigokiller** [comment]
> This package lives in the category I am happy with it does and will not get much support with it. I already mentioned to you how it works and that is incomplete. Apparentky the way it binds the child frames has issues. The module was not developed for years, look its history. If you have a simple case and not expect 100% Xaf working for childviews then it might be good to you.

I was only asking if there was something that I missed. Your response is vague. I am not reporting a bug, I was only asking if it was possible or not.

**Comment by apobekiaris** [comment]
apologies if I sound bad, however your question requies time for research how long you think? I can spent 1 min but I will answer similar, I can spent 1hr I could probably answer better. In any case my resources do not allow me to spent time for cases that I consider dead end like this module. 

I am working with Xaf from day one and I have tried to share with you my experience, which is that this module is not the way you will get the most out of Xaf, but you ignore me asking for more of my time. Happy to give it to you for something that will be of value to you. 

Thanks for the understanding.

**Comment by rodrigokiller** [comment]
> Thanks for the understanding.

Not a problem at all. I think I understand (sort of) what you are trying to tell me.
Have your time. I will also try to solve this with the source code that I have.
Maybe I will do a pull request (that you may or not accept). 
Thanks anyways

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
