### ISSUE TITLE
Unable to find package Xpand.Patcher with version (>= 3.0.5)

### ISSUE THREAD

**Issue by ramilcatalandomingo** [eXpandFramework/eXpand#954]
When installing the JobScheduler.Hangfire v4.221.8 package using the package manager from Visual Studio 2022, it looks for a version of Xpand.Patcher >= 3.0.5 from nuget that does not exist.  Therefore, the installation does not proceed.

**Comment by apobekiaris** [comment]
thnks was only published on lab server, I just push it on nuget

**Comment by ramilcatalandomingo** [comment]
I see it now. Thank you so much @apobekiaris.
