### ISSUE TITLE
JobScheduler.Notification namespace is missing

### ISSUE THREAD

**Issue by ramilcatalandomingo** [eXpandFramework/eXpand#955]
After installing the JobScheduler.Notification nuget package, I tried to register the module to my module agnostic project only to get an error indicating the namespace name 'Notification' does not exist.

![image](https://user-images.githubusercontent.com/31090302/194879097-90498a13-2efc-4fcb-b3cc-11ae1e2d1950.png)

**Comment by apobekiaris** [comment]
where did you got that namespace from the suggested once u install?

the correct namespace is `Xpand.XAF.Modules.JobScheduler.Hangfire.Notification`

**Comment by ramilcatalandomingo** [comment]
I got it from the readme.txt file.  I applied your correction and everything works now.  Thank you.

![image](https://user-images.githubusercontent.com/31090302/194880829-546e13d4-0be3-4daa-a78e-bd1c3dc7c88a.png)
