### ISSUE TITLE
Compile error after installing JobScheduler.Hangfire 4.221.8 from a fresh XAF Blazor project

### ISSUE THREAD

**Issue by ramilcatalandomingo** [eXpandFramework/eXpand#956]
Hello,

I created a fresh XAF Blazor project and then installed the JobScheduler Hangfire nuget package and added the required module but encountered a compilation error.  Please advise.  Thank you.

![image](https://user-images.githubusercontent.com/31090302/195244192-f90b3980-06a7-4c35-a444-06f80ac9a8a3.png)

**Comment by apobekiaris** [comment]
where is your sample?

**Comment by ramilcatalandomingo** [comment]
I have attached the sample project.

[DXApplication2.zip](https://github.com/eXpandFramework/eXpand/files/9761431/DXApplication2.zip)

**Comment by apobekiaris** [comment]
yes I can repro it, so I guess u need to wait for the next minor. I did not research it but if you in urge you may try removing the contents of the C:\Users\ramil\.nuget\packages\xpand.xaf.modules.jobscheduler.hangfire\4.221.8\build\Xpand.XAF.Modules.JobScheduler.Hangfire.ps1

**Comment by ramilcatalandomingo** [comment]
Hello. Your advice of removing the contents of the ps1 file did the trick.  Thank you very much and will await the next minor release.

**Comment by apobekiaris** [comment]
fyi the script tries to strongly sing the assemblies, native ME was throwing if the assemblies are not strongly singed

**Comment by ramilcatalandomingo** [comment]
Thanks @apobekiaris. I will look forward to the future fix.
