### ISSUE TITLE
ModelDifference Module Web Editor

### ISSUE THREAD

**Issue by Siratigui** [eXpandFramework/eXpand#958]
Hi Sir,

ModelDifference Web Module provides a plain xml editor. Is there any way to open ModelEditor from Web and the save the Xml to database ?

Thank you.

**Comment by apobekiaris** [comment]
you can use the ModelDifference.Win to open external apps models

**Comment by Siratigui** [comment]
for that I have to open a windows application I guess. is it possible to accomplish that without any windows intervention.

**Comment by apobekiaris** [comment]
I cannot follow you, how you imagine opening the `ModelEditor` which is a windows app
