### ISSUE TITLE
Drop suppport for Full .NET

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#961]
Starting next year all packages without a .NET6 target will be archived (e.g. WebForms) and all netstandard2.0 packages will be ported to .NET6

**Comment by vimarx** [comment]
I still have some webforms projects (supported by dx 22.2) but the new Xpand requirements don't let me upgrade to v22.2 because of this new base requirement of net 6.
Are there any ways to have NuGet packages with no further enhancements, but still compatible with net461/netstandard2.0?
Thanks.
 
Gustavo

**Comment by apobekiaris** [comment]
u need to support your own branch before 22.2, the scripts in the repo should be of help but in any case if you have questions on how to build let me know

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.400.0) includes commit that relate to this task:

* [22.2.300.0 Drop full framework support #961](https://github.com/eXpandFramework/eXpand.lab/commit/169f838eb66e00af099cfda7a1fca80d68409bda)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
