### ISSUE TITLE
unable to install Xpand.XAF.Core.All 4.221.11 - Xpand.Patcher 3.0.17 required - at nuget 3.0.14

### ISSUE THREAD

**Issue by yunits** [eXpandFramework/eXpand#962]
Hi,
I am unable to install Xpand.XAF.Core.All
it requires Xpand.Patcher Version 3.0.17 but the newest at nuget is 3.0.14

**Comment by apobekiaris** [comment]
I forget to push this package from the lab servers, now is published give it 5 min

**Comment by yunits** [comment]
wow thanks for this fast answer :D
