### ISSUE TITLE
Error loading Model.DesignedDiffs.xafml  after adding Expand.Xaf packages

### ISSUE THREAD

**Issue by MarkAlvinReyes** [eXpandFramework/eXpand#963]
I already upgraded my project to DevExpress version 22.1.6 but I have an error loading the Model.DesignedDiffs.xafml and model.xafml after adding the following packages (Xpand.Xaf.Modules.Reactive, Xpand.XAF.Modules.JobScheduler.Hangfire and Xpand.XAF.Modules.Blazor) to my MySampleHangfire.Blazor.Server and MySampleHangfire.Module project. See the attached screenshot. I also attach here my sample project.

The error occurred after adding the below code in the constructor of the BlazorModule.cs file.

RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Blazor.BlazorModule));
RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.Reactive.ReactiveModule));
RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.JobScheduler.Hangfire.JobSchedulerModule));

[MySampleHangfire.zip](https://github.com/eXpandFramework/eXpand/files/9989690/MySampleHangfire.zip)
![ErrorLoadingModel](https://user-images.githubusercontent.com/41627689/201328158-4b04d472-e6b5-49ec-8e24-6dd2c13931b5.png)

You can check the link below for the video recording I made to reproduce the issue.

https://supportcenter.devexpress.com/ticket/details/t1126554/how-to-add-model-assembly-job-source 
(Filename: ErrorExpandHangFire.mp4)

**Comment by apobekiaris** [comment]
thnks for the sample, I can repro the issue and will see to it. For now I was able to open ME by installing latest System.Interactive 6.0.1 to the Blazor.Server project and then restart VS.

**Comment by MarkAlvinReyes** [comment]
Thanks, apobekiaris! Please let me know when the fix for this will be available so that I can apply to my project.

**Comment by MarkAlvinReyes** [comment]
apobekiaris i tried to add the System.Interactive 6.0.1 to the Blazor.Server project  but there is an error, See the attached image.
![Error_Adding_System_Inteactive_V6_0_1](https://user-images.githubusercontent.com/41627689/201459286-214072e9-1cfd-4942-a4aa-bc9d9dd346d8.png)

**Comment by apobekiaris** [comment]
I do not think this error relates to eXpandFramework, it says the dir does not exist, so u probably uninstall DX. YOu can configure these dirs in your VS/Tools/Options/Nuget/Package Sources

**Comment by MarkAlvinReyes** [comment]
Thank you! issue was fixed after configuring the Nuget package sources. Just a follow-up question, how to create the objectspace in my class that has the JobProvider attribute? See the attached recording.  As you can see the value of the Application property is NULL so I was not able to create objectspace. It was NULL because the constructor that has the BlazorApplication parameter was not called.

https://user-images.githubusercontent.com/41627689/201474943-84fbfbca-1396-4aa0-bc97-f517e145bab9.mp4

**Comment by apobekiaris** [comment]
see the wiki for instructions on how to declare jobs

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire#details

**Comment by MarkAlvinReyes** [comment]
apobekiaris,

I have tried the code in your example but where i will get the ServiceProvider in the DailyTask method? See the attached screenshot.  Because when i try to use the ServiceProvider .RunWithStorageAsync is says that 
ServiceProvider does n
![RunWithStorageAsync_Error](https://user-images.githubusercontent.com/41627689/201517116-724570e8-ea5d-4469-8251-e078e0b6d42c.png)
![ServiceProvider](https://user-images.githubusercontent.com/41627689/201517117-14e2cea7-afb8-4041-97ba-a52597d0d850.png)
ot contain a definition for 'RunWithStorageAsync. What is the namespace of the ServiceProvider that you used in the sample code?
![ServiceProvider](https://user-images.githubusercontent.com/41627689/201517119-e1aed0a9-5de8-483a-a4f2-d047e1b129d1.png)
![RunWithStorageAsync_Error](https://user-images.githubusercontent.com/41627689/201517120-d366575f-bf3b-4aaf-b09f-9c2825ec43d6.png)

**Comment by apobekiaris** [comment]
the `ServiceProvider` is the `Provider` docs are wrong I will update them

**Comment by MarkAlvinReyes** [comment]
Same with this example from here:  https://www.youtube.com/watch?v=0LJ2bM1CfMg  the Application property is NULL so there is no way you can create an objectspace. See the attached video recording.  Even if I changed the property to Provider the value of this property is also NULL.

https://user-images.githubusercontent.com/41627689/201525075-748cf3af-3e59-4b43-808f-4b405ea812b3.mp4

**Comment by apobekiaris** [comment]
this video uses an old version it is not possible to inject the BlazorApplication, instead there is the IServiceProvider. There are several u can follow or also u can llok at the TestApplication

https://github.com/eXpandFramework/Reactive.XAF/blob/master/src/Tests/JobScheduler.Hangfire/TestJob.cs

https://github.com/eXpandFramework/Reactive.XAF/blob/master/src/Tests/EasyTests/TestApplication/TestApplication.Module.Blazor/JobScheduler/Job.cs

**Comment by apobekiaris** [comment]
I recommend you either use the distributed symbols to actually debug the package and see what's wrong or another option is to compile the source using the [quick ](https://github.com/eXpandFramework/Reactive.XAF/blob/master/QuickBuild.ps1) you can read more on how easy it is to own the code at https://github.com/eXpandFramework/eXpand/issues/943

as you can read after u build the source u can simply load the JobScheduler project in your solution or any other package and build. If you set a breakpoint it will break or u can even modify it. Sorry I cannot repeat myself again all the info you need to master this framework is on #943

**Comment by apobekiaris** [comment]
about 7

```cs
public static IObservable<JobState> JobState => JobStateSubject.AsObservable();
````

thats the declaration of JobState so it is static so feel free to use it any place and remember to dispose it along with the container the same u do with any IDisposabel class or events etc

**Comment by MarkAlvinReyes** [comment]
Where does the data in the Workers tab come from? Or how it was generated? Is there any code that I need to add in order to display the data in the Workers tab?

**Comment by apobekiaris** [comment]
without a sample and spending time to research why u cannot see the Worker is not possible to answer u. In any case the worker is created at JobSchedulerService.ApplyJobState which is called from the Hangfire filter and since u go into your job I assume it went there. I would check if the worker is on my DB or I would debug the package as I mentioned

**Comment by apobekiaris** [comment]
the package as all the packages work as is or there will be explicit instructions in the wiki. In this case no instruction so as it is

**Comment by apobekiaris** [comment]
did you run the TestApplication from the source code? does it work there?

**Comment by apobekiaris** [comment]
thnks I need time to review the testapplication apparently this is some kind of layout issue, data are there so they should be displayed unless the layout is broken. In the meantime feel free to open ME and play with the layout your self.

**Comment by MarkAlvinReyes** [comment]
And one thing apobekiaris, every time I run my application and there is a job that runs Minutely I always get this error. See the attached screenshot.

![DuplicateNameValidationError](https://user-images.githubusercontent.com/41627689/201941549-a10beaea-d82e-413f-bdae-4456a4168d62.png)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
