### ISSUE TITLE
Best way to create the default job in the database

### ISSUE THREAD

**Issue by MarkAlvinReyes** [eXpandFramework/eXpand#964]
Hi,

I'm using eXpand for my job automation, and one of the requirements is to create a default job that will execute every day. My question is where is the best location to add the code that will create the default job? Should I add the code in the BlazorModule or in the Startup?  By the way, I'm using Blazor application.

**Comment by apobekiaris** [comment]
Hangfire is a Blazor only package but really I do not understand your question what is a default job? is it the `Xpand.XAF.Modules.JobScheduler.Hangfire.BusinessObjects.Job` then since this is a Xaf BO it obeys eveyrthing you know about Xaf meaning that if you want to create initial data you can use a ModuleUpdater

**Comment by MarkAlvinReyes** [comment]
What I mean is I need to create initial data of the job in the database. For example, I want to have an initial job or default record in my database called DownloadSalesOrder that will run every day.

**Comment by apobekiaris** [comment]
> since this is a Xaf BO it obeys eveyrthing you know about Xaf meaning that if you want to create initial data you can use a ModuleUpdater

than that

**Comment by MarkAlvinReyes** [comment]
I see... Is it the right way if will add eXpand packages in both Blazor.Server and Module projects?

**Comment by apobekiaris** [comment]
think of a module **any** project even the server that contain a ModuleBase descenant

**Comment by apobekiaris** [comment]
sure u can add modules to both your server and your modules the server part is optional since it already has a dependecy to your modules

**Comment by MarkAlvinReyes** [comment]
@apobekiaris 

Is this the correct code to create job in the database through code using Xpand:

**Comment by apobekiaris** [comment]
I really cannot tell wihout details and testing myself, I can guess that you are in a moduleupdater just after u added the job but the services are not initialized at this point. A better way again without testing would be to trigger your job after login

**Comment by MarkAlvinReyes** [comment]
Yes, the code was added in the module updater. I can send you my sample project.  I also tried to run the job manually but it did not run. Here is my sample project. 

[HangfireJobAutomationSample.zip](https://github.com/eXpandFramework/eXpand/files/10038717/HangfireJobAutomationSample.zip)

**Comment by apobekiaris** [comment]
at the moment I am occupied and do not have the time to go through your sample, in the source there are a number of tests for various cases. Once I have the time to go through your other case I will have a look at your sample

**Comment by MarkAlvinReyes** [comment]
ok thank you @apobekiaris !

**Comment by apobekiaris** [comment]
>is there a way the Hangfire database objects automatically create in the database

my guess is that u speak about the db tables, so u have to realize that this is a Xaf package meaning it will automatically create the schema as per your db update strategy. That is it will create the tables when debugger is attached and after the creation of the first objectspace which by default happens on login. 

It is really a wrapper around the hangfire API it uses the Xaf BO objects e.g. Job state to display the views you need to trigger and manage your jobs

**Comment by apobekiaris** [comment]
so to be crystal clear the tables should be all created on login and when debugger is attached unrelated to hangfire

**Comment by apobekiaris** [comment]
if you speak about hangfire tables you need to consult with Hangfire docs, a good idea is to have those tables in a different db and create that with the sql scripts hangfire provides

**Comment by MarkAlvinReyes** [comment]
yes i'm talking about Hangfire tables. 

![HanfireTables](https://user-images.githubusercontent.com/41627689/202720063-dd6518bc-33e8-461a-81d0-3c5a7c50c407.png)

**Comment by apobekiaris** [comment]
xaf has nothing to do with them and never writes directly there

**Comment by MarkAlvinReyes** [comment]
here is the error when you call the job.trigger method if the hangfire tables are not yet initialized or created in the database.


![JobTriggerError](https://user-images.githubusercontent.com/41627689/202721647-909e6af3-4e9a-4d56-a047-d8975a2dc465.png)

**Comment by apobekiaris** [comment]
unrelated to this package see https://docs.hangfire.io/en/latest/configuration/using-sql-server.html

**Comment by MarkAlvinReyes** [comment]
ok. thank you @apobekiaris .

**Comment by apobekiaris** [comment]
in 22.2 UI and hangfire problems fixed

![image](https://user-images.githubusercontent.com/159464/208294016-b8a3d5a8-c102-4596-b848-4a333b976ff8.png)

**Comment by apobekiaris** [comment]
The pre-release [4.222.0.1](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.0.1) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Model generation issues with Blazor #964](https://github.com/eXpandFramework/Reactive.XAF/commit/2af655d9707dc8f3308f1eae5c52ef3674fdf612)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.222.0.1</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.222.0.1</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
