### ISSUE TITLE
eXpand support for DevExpress version 22.2 Beta

### ISSUE THREAD

**Issue by MarkAlvinReyes** [eXpandFramework/eXpand#965]
Hi!

I have a problem with eXpand packages when I tried to add it to the Blazor project that references the current beta release of DevExpress which is DevExpress 22.2.2 Beta. There is an error loading the Model.xafml of the Blazor project. See the attached screenshot. I think the packages only support DevExpress.ExpressApp.V22.1.6. I just want to ask when will you support or upgrade the eXpand packages to support the latest release of DevExpress?

![Model_xafml_Error](https://user-images.githubusercontent.com/41627689/205617832-5aacb10b-68c4-4e6e-a5a0-a6210767a26c.png)

Thanks....

**Comment by apobekiaris** [comment]
there is no comptibility with the beta version. We only support official releases so you have to wait a bit for using 22.2

**Comment by MarkAlvinReyes** [comment]
I see. Can I try to upgrade the source code of eXpand packages to support the current 22.2 beta version of DevExpress? Because I want to showcase in our demo the Job Automation that we did using the eXpand packages.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
