### ISSUE TITLE
Need help for build Xpand by myself

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#968]
Hi, when trying to build by myself using build.ps1  ( because of #961) , I found this problem

`
Restauración realizada correctamente.
Paket Restore C:\repos\expand\paket.dependencies
Paket version 7.1.5+e2fe7c693356a5e70a74cc01501f7dc5f8996695
Total time taken: 0 milliseconds
Paket failed with
-> paket.dependencies and paket.lock are out of sync in C:\repos\expand.
   Please run 'paket install' or 'paket update' to recompute the paket.lock file.
----------
Exception:
----------
ScriptHalted
ScriptHalted
En C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\System\Approve-LastExitCode.ps1: 14 Carácter: 13
+             throw
+             ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

-----------
StackTrace:
-----------
en Approve-LastExitCode<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\System\Approve-LastExitCode.ps1: línea 14
en Invoke-Script<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\System\Invoke-Script.ps1: línea 24
en <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\Nuget\Paket\Invoke-PaketRestore.ps1: línea 38
en Get-PaketDependenciesPath<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\Nuget\Paket\Get-PaketDependenciesPath.ps1: línea 31en Invoke-PaketRestore<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\Nuget\Paket\Invoke-PaketRestore.ps1: línea 21
en <ScriptBlock>, C:\repos\expand\support\build\Build.ps1: línea 107
en Invoke-Task, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-Task.ps1: línea 108
en Invoke-Task, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-Task.ps1: línea 131
en <ScriptBlock>, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-psake.ps1: línea 292
en ExecuteInBuildFileScope, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\private\ExecuteInBuildFileScope.ps1: línea 49
en Invoke-psake, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-psake.ps1: línea 256
en <ScriptBlock>, C:\repos\expand\support\build\go.ps1: línea 42
en <ScriptBlock>, C:\repos\expand\build.ps1: línea 3
en <ScriptBlock>, <sin archivo>: línea 1
Paket version 7.1.5+e2fe7c693356a5e70a74cc01501f7dc5f8996695
Resolving dependency graph...
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   C:\Program
   https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.win.all/index.json?semVerLevel=2.0.0
   https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Win.All'
   https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Win.All'
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   C:\Program
   https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.web.all/index.json?semVerLevel=2.0.0
   https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Web.All'
   https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Web.All'
Total time taken: 9 seconds
Paket failed with
-> Unable to retrieve package versions for 'DevExpress.ExpressApp.Win.All'
   -- CLOSED --
      Microsoft.Extensions.DependencyInjection.Abstractions == 6.0.0 (from C:\repos\expand\paket.dependencies)
      Microsoft.Extensions.DependencyInjection == 6.0.0 (from C:\repos\expand\paket.dependencies)
      Microsoft.Extensions.Hosting.Abstractions == 6.0.0 (from C:\repos\expand\paket.dependencies)
      Microsoft.Extensions.Options == 6.0.0 (from C:\repos\expand\paket.dependencies)
      System.Security.Cryptography.Xml == 6.0.0 (from C:\repos\expand\paket.dependencies)
      System.Data.OleDb == 6.0.0 (from C:\repos\expand\paket.dependencies)
      System.ComponentModel.Annotations == 5.0.0 (from C:\repos\expand\paket.dependencies)
      System.Reflection.Emit.Lightweight == 4.7.0 (from C:\repos\expand\paket.dependencies)
      JetBrains.Annotations 2021.3 (from C:\repos\expand\paket.dependencies)
   -- OPEN ----
      DevExpress.ExpressApp.Win.All 22.2.3 (from C:\repos\expand\paket.dependencies)
      DevExpress.ExpressApp.Web.All 22.2.3 (from C:\repos\expand\paket.dependencies)
      DevExpress.ExpressApp.Core.All 22.2.3 (from C:\repos\expand\paket.dependencies)
      DevExpress.ExpressApp.Security.Xpo 22.2.3 (from C:\repos\expand\paket.dependencies)
      DevExpress.Document.Processor 22.2.3 (from C:\repos\expand\paket.dependencies)
      DevExpress.ExpressApp.CodeAnalysis 22.2.3 (from C:\repos\expand\paket.dependencies)
      Newtonsoft.Json 13.0.1 (from C:\repos\expand\paket.dependencies)
      AutoMapper 10.1.1 (from C:\repos\expand\paket.dependencies)
      IIS.Microsoft.Web.Adminstration 8.5.9600.16384 (from C:\repos\expand\paket.dependencies)
      Unofficial.Microsoft.mshtml 7.0.3300 (from C:\repos\expand\paket.dependencies)
      Microsoft.IdentityModel.Protocols.OpenIdConnect 6.15 (from C:\repos\expand\paket.dependencies)
      System.Text.Json 6.0.6 (from C:\repos\expand\paket.dependencies)
      Microsoft.NETCore.Platforms 6.0.4 (from C:\repos\expand\paket.dependencies)
      System.Text.Encoding.CodePages 6.0 (from C:\repos\expand\paket.dependencies)
      System.CodeDom 6.0 (from C:\repos\expand\paket.dependencies)
      System.Configuration.ConfigurationManager 6.0 (from C:\repos\expand\paket.dependencies)
      System.Security.Permissions 6.0 (from C:\repos\expand\paket.dependencies)
      System.Drawing.Common 6.0 (from C:\repos\expand\paket.dependencies)
      System.Management 6.0 (from C:\repos\expand\paket.dependencies)
      System.Resources.Extensions 6.0 (from C:\repos\expand\paket.dependencies)
      System.Runtime.CompilerServices.Unsafe 6.0 (from C:\repos\expand\paket.dependencies)
      System.Collections.Immutable 6.0 (from C:\repos\expand\paket.dependencies)
      Microsoft.Bcl.AsyncInterfaces 6.0 (from C:\repos\expand\paket.dependencies)
      System.Text.Encodings.Web 6.0 (from C:\repos\expand\paket.dependencies)
      Microsoft.Win32.Registry 5.0 (from C:\repos\expand\paket.dependencies)
      System.Reactive 5.0 (from C:\repos\expand\paket.dependencies)
      system.interactive 5.0 (from C:\repos\expand\paket.dependencies)
      Xpand.XAF.Win.All 4.221.11 (from C:\repos\expand\paket.dependencies)
      Xpand.XAF.Web.All 4.221.11 (from C:\repos\expand\paket.dependencies)
      System.ServiceModel.NetTcp 4.9 (from C:\repos\expand\paket.dependencies)
      System.ServiceModel.Security 4.9 (from C:\repos\expand\paket.dependencies)
      System.ServiceModel.Http 4.9 (from C:\repos\expand\paket.dependencies)
      System.ServiceModel.Duplex 4.9 (from C:\repos\expand\paket.dependencies)
      System.Reflection.DispatchProxy 4.7.1 (from C:\repos\expand\paket.dependencies)
      Microsoft.CSharp 4.7 (from C:\repos\expand\paket.dependencies)
      System.Reflection.Emit 4.7 (from C:\repos\expand\paket.dependencies)
      System.Reflection.TypeExtensions 4.7 (from C:\repos\expand\paket.dependencies)
      WindowsBase 4.6.1055 (from C:\repos\expand\paket.dependencies)
      System.Threading.Tasks.Extensions 4.5.4 (from C:\repos\expand\paket.dependencies)
      System.Memory 4.5.4 (from C:\repos\expand\paket.dependencies)
      System.Buffers 4.5.1 (from C:\repos\expand\paket.dependencies)
      System.ValueTuple 4.5 (from C:\repos\expand\paket.dependencies)
      System.Runtime 4.3.1 (from C:\repos\expand\paket.dependencies)
      System.IO.Compression 4.3 (from C:\repos\expand\paket.dependencies)
      System.Xml.XDocument 4.3 (from C:\repos\expand\paket.dependencies)
      Fody 4.2.1 (from C:\repos\expand\paket.dependencies)
      Topshelf 4.2.1 (from C:\repos\expand\paket.dependencies)
      Enums.NET 4.0 (from C:\repos\expand\paket.dependencies)
      RazorEngine 3.10 (from C:\repos\expand\paket.dependencies)
      ExcelDataReader 3.6 (from C:\repos\expand\paket.dependencies)
      ExcelDataReader.DataSet 3.6 (from C:\repos\expand\paket.dependencies)
      Common.Logging 3.4.1 (from C:\repos\expand\paket.dependencies)
      Microsoft.AspNet.Razor 3.2.7 (from C:\repos\expand\paket.dependencies)
      DocumentFormat.OpenXml 2.11.3 (from C:\repos\expand\paket.dependencies)
      PropertyChanged.Fody 2.6.1 (from C:\repos\expand\paket.dependencies)
      AForge 2.2.5 (from C:\repos\expand\paket.dependencies)
      AForge.Imaging 2.2.5 (from C:\repos\expand\paket.dependencies)
      AForge.Math 2.2.5 (from C:\repos\expand\paket.dependencies)
      AForge.Video 2.2.5 (from C:\repos\expand\paket.dependencies)
      Microsoft.AspNetCore.WebUtilities 2.2 (from C:\repos\expand\paket.dependencies)
      Fasterflect.Xpand 2.0.7 (from C:\repos\expand\paket.dependencies)
      DotNetZip 1.16 (from C:\repos\expand\paket.dependencies)
      CommandLineParser 1.9.71 (from C:\repos\expand\paket.dependencies)
      SharpZipLib 1.3 (from C:\repos\expand\paket.dependencies)
      AppDomainToolkit 1.0.4.3 (from C:\repos\expand\paket.dependencies)
      InputSimulator 1.0.4 (from C:\repos\expand\paket.dependencies)
      Mono.Cecil 0.11.4 (from C:\repos\expand\paket.dependencies)
      System.Runtime.CompilerServices.Unsafe >= 6.0 (from Microsoft.Extensions.DependencyInjection 6.0)
      Microsoft.Bcl.AsyncInterfaces >= 6.0 (from Microsoft.Extensions.DependencyInjection.Abstractions 6.0)
      Microsoft.Extensions.Configuration.Abstractions >= 6.0 (from Microsoft.Extensions.Hosting.Abstractions 6.0)
      Microsoft.Extensions.FileProviders.Abstractions >= 6.0 (from Microsoft.Extensions.Hosting.Abstractions 6.0)
      System.Runtime.CompilerServices.Unsafe >= 6.0 (from Microsoft.Extensions.Hosting.Abstractions 6.0)
      Microsoft.Extensions.Primitives >= 6.0 (from Microsoft.Extensions.Options 6.0)
      System.Configuration.ConfigurationManager >= 6.0 (from System.Data.OleDb 6.0)
      System.Diagnostics.PerformanceCounter >= 6.0 (from System.Data.OleDb 6.0)
      System.Security.AccessControl >= 6.0 (from System.Security.Cryptography.Xml 6.0)
      System.Security.Cryptography.Pkcs >= 6.0 (from System.Security.Cryptography.Xml 6.0)
      Microsoft.Win32.Registry >= 5.0 (from System.Data.OleDb 6.0)
      System.Security.Principal.Windows >= 5.0 (from System.Data.OleDb 6.0)
      System.Reflection.Emit.ILGeneration >= 4.7 (from System.Reflection.Emit.Lightweight 4.7)
      System.Threading.Tasks.Extensions >= 4.5.4 (from Microsoft.Extensions.DependencyInjection.Abstractions 6.0)
      System.Memory >= 4.5.4 (from System.Security.Cryptography.Xml 6.0)
-> One or more errors occurred. (One or more errors occurred. (Could not find versions for package DevExpress.ExpressApp.Win.All on any of ["C:\Program"; "https://api.nuget.org/v3/index.json";
    "https://xpandnugetserver.azurewebsites.net/nuget"]. (Source 'C:\Program' yielded no results (Request 'C:\Program' finished with error)) (Source 'https://api.nuget.org/v3/index.json' yielded (0): [] (Request 'https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.win.all/index.json?semVerLevel=2.0.0' finished with: [])) (Source 'https://xpandnugetserver.azurewebsites.net/nuget' yielded (0): [] (Request 'https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Win.All'' finished with: []) (Request 'https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Win.All'' was cancelled (another one was faster)))))
-> One or more errors occurred. (Could not find versions for package DevExpress.ExpressApp.Win.All on any of ["C:\Program"; "https://api.nuget.org/v3/index.json";
    "https://xpandnugetserver.azurewebsites.net/nuget"]. (Source 'C:\Program' yielded no results (Request 'C:\Program' finished with error)) (Source 'https://api.nuget.org/v3/index.json' yielded (0): [] (Request 'https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.win.all/index.json?semVerLevel=2.0.0' finished with: [])) (Source 'https://xpandnugetserver.azurewebsites.net/nuget' yielded (0): [] (Request 'https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Win.All'' finished with: []) (Request 'https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Win.All'' was cancelled (another one was faster))))
-> Could not find versions for package DevExpress.ExpressApp.Win.All on any of ["C:\Program"; "https://api.nuget.org/v3/index.json";
    "https://xpandnugetserver.azurewebsites.net/nuget"]. (Source 'C:\Program' yielded no results (Request 'C:\Program' finished with error)) (Source 'https://api.nuget.org/v3/index.json' yielded (0): [] (Request 'https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.win.all/index.json?semVerLevel=2.0.0' finished with: [])) (Source 'https://xpandnugetserver.azurewebsites.net/nuget' yielded (0): [] (Request 'https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Win.All'' finished with: []) (Request 'https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Win.All'' was cancelled (another one was faster)))
        -  Source 'C:\Program' yielded no results (Request 'C:\Program' finished with error)
        -> Request 'C:\Program' finished with error
        -> Unhandled error in request to 'C:\Program' in NuGetRequestGetVersions.run
        -> The directory C:\Program doesn't exist.
           Please check the NuGet source feed definition in your paket.dependencies file.
        -  Source 'https://api.nuget.org/v3/index.json' yielded (0): [] (Request 'https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.win.all/index.json?semVerLevel=2.0.0' finished with: [])
        -> Request 'https://api.nuget.org/v3-flatcontainer/devexpress.expressapp.win.all/index.json?semVerLevel=2.0.0' finished with: []
        -  Source 'https://xpandnugetserver.azurewebsites.net/nuget' yielded (0): [] (Request 'https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Win.All'' finished with: []) (Request 'https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Win.All'' was cancelled (another one was faster))
                -  Request 'https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?semVerLevel=2.0.0&id='DevExpress.ExpressApp.Win.All'' finished with: []
                -  Request 'https://xpandnugetserver.azurewebsites.net/nuget/Packages?semVerLevel=2.0.0&$filter=Id eq 'DevExpress.ExpressApp.Win.All'' was cancelled (another one was faster)
----------
Exception:
----------
ScriptHalted
ScriptHalted
En C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\System\Approve-LastExitCode.ps1: 14 Carácter: 13
+             throw
+             ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

-----------
StackTrace:
-----------
en Approve-LastExitCode<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\System\Approve-LastExitCode.ps1: línea 14
en Invoke-Script<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\System\Invoke-Script.ps1: línea 24
en <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\Nuget\Paket\Invoke-PaketRestore.ps1: línea 42
en Get-PaketDependenciesPath<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\Nuget\Paket\Get-PaketDependenciesPath.ps1: línea 31en Invoke-PaketRestore<Process>, C:\Program Files\WindowsPowerShell\Modules\XpandPwsh\1.221.0.4\public\Nuget\Paket\Invoke-PaketRestore.ps1: línea 21
en <ScriptBlock>, C:\repos\expand\support\build\Build.ps1: línea 107
en Invoke-Task, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-Task.ps1: línea 108
en Invoke-Task, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-Task.ps1: línea 131
en <ScriptBlock>, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-psake.ps1: línea 292
en ExecuteInBuildFileScope, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\private\ExecuteInBuildFileScope.ps1: línea 49
en Invoke-psake, C:\Users\gmarzioni.VIMARX\Documents\WindowsPowerShell\Modules\psake\4.7.4\public\Invoke-psake.ps1: línea 256
en <ScriptBlock>, C:\repos\expand\support\build\go.ps1: línea 42
en <ScriptBlock>, C:\repos\expand\build.ps1: línea 3
en <ScriptBlock>, <sin archivo>: línea 1
Error: 22/12/2022 09:40:11:
 +             ~~~~~ [<<==>>] Exception: ScriptHaltedsh\1.221.0.4\public\System\Approve-LastExitCode.ps1: 14 Carácter: 13`

**Comment by apobekiaris** [comment]
first I want to clarify that building should be trivial while package generation not. Sure you can survive without packages, doing the dependecies manually as I guest you do not have many projects to support.

Now, you need to build both repos, the rx repo first instructions in [quickbuild] (https://github.com/eXpandFramework/Reactive.XAF/blob/master/QuickBuild.ps1) and then this repo.  The build.ps1 from  this repo I suggest you avoid it cause it is really for the CI/CD. I suggest the same for the Rx repo, u first update the dependencies in the paket.dependencies files in the root dir manually. Then you need to execute `invoke-paketinstall` (XpandPwsh) on the root to synch the lock file and then you can open the AllModules.sln and build it.

**Comment by apobekiaris** [comment]
if `paket` is too hard for u, it should be also possible to remove it completely and fallback to common nuget packages. This requires you remove all related imports from csproj and manually add all dependeccies listed in paket.references in the root of each project

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
