### ISSUE TITLE
is Xpand nuget source failing?

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#969]
My pipeline is failing in

https://xpandnugetserver.azurewebsites.net/nuget/FindPackagesById()?id=%27DevExpress.ExpressApp.Core.All%27&semVerLevel=2.0.0%27.

**Comment by apobekiaris** [comment]
yes for some reason, I am looking into it

**Comment by apobekiaris** [comment]
is is online now, let me know if anything plrease

**Comment by Kagandaj** [comment]
Is easy way to generate nuget packages for the rx repo

I built the rx repo(both tools and modules) for dx version 22.1.7 then called PackNuspec.ps1
this builds successfully.

however changing the version in common\assemblyinfo version breaks
the packing step.

**Comment by apobekiaris** [comment]
before you pack you have to create/synchronize etc with the `CreateNuspec.ps1`

**Comment by apobekiaris** [comment]
also, I guess u know that, XpandPwsh probably is used and should be installed

**Comment by Kagandaj** [comment]
Thanks,
Let me try that

**Comment by Kagandaj** [comment]
Worked Very Well
Thanks Very Much

**Comment by Kagandaj** [comment]
Hello,
Just have one follow up question.
How do I add targets to existing modules
For example I want to change bulk update module to netstandard

Build is successful and tests pass but create nuspec.ps1 fails

**Comment by apobekiaris** [comment]
i am not sure what is the problem I guess you not really asking how to change the targetframework

**Comment by apobekiaris** [comment]
>Build is successful and tests pass but create nuspec.ps1 fails

using VsCode with its powershell extension u should be able to set breakpoing see vars step info functions etc like full blown Visual studio does

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
