### ISSUE TITLE
Cannot open xpand modeleditor after project upgrade to 22.2.3

### ISSUE THREAD

**Issue by volokos** [eXpandFramework/eXpand#970]
Cannot open xpand modeleditor after project upgrade to 22.2.3.
I got error 'Multiple DevExpress versions found in \bin\debug' in rider

**Comment by apobekiaris** [comment]
delete all files from your bin and recompile

**Comment by volokos** [comment]
I deleted bin, obj folder, rebuild project and still have this problem.
B.T.W. i see that in \Roaming\Xpand.XAF.ModelEditor.Win\Xpand.XAF.ModelEditor.Win folder all devexpress dll is 22.1 version. Is this ok?

**Comment by apobekiaris** [comment]
for some reason ME did not upgrade it self this is done automatically by checking the contants of your C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\ to match the version of your project. So you cna try remoing all contents of C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\

if it persistnt you can also try configure the download sources. When ME opens the list of models there is a configure button whiche will allow u to se the ME download source Application/ModelEditor.

Also make sure your project does not reference by mistake any older version. You can look the DX versions on the bin after compile with ME run, there should be no older version there

**Comment by apobekiaris** [comment]
or you can add the files from the the online repo manually delete the C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\ contents and add them from https://github.com/eXpandFramework/Reactive.XAF/releases/download/untagged-72017c7c694c6db0c95f/Xpand.XAF.ModelEditor.WinDesktop.zip


![image](https://user-images.githubusercontent.com/159464/211524433-6c0614f9-5de8-4b98-8862-19880d63321d.png)

I use the lab versions locally but this shouldn't be the issues

**Comment by volokos** [comment]
So if i add content from  [https://github.com/eXpandFramework/Reactive.XAF/releases/download/4.222.1.1/Xpand.XAF.ModelEditor.WinDesktop.zip](url)
i'm getting error:

`System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\aleksandrs\AppData\Roaming\Xpand.XAF.ModelEditor.Win\\Xpand.XAF.ModelEditor.Win\Xpand.XAF.ModelEditor.Win.exe' with working directory 'C:\Program Files\JetBrains\JetBrains Rider 2022.1.2\jbr\bin'. The system cannot find the file specified. at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start(String fileName) at ModelEditor.XpandModelEditor.StartMEAsync() in C:\Work\Reactive.XAF\tools\Xpand.XAF.ModelEditor\IDE\XpandModelEditor.cs:line 34 at ReSharperPlugin.Xpand.XpandModelEditorAction.Execute(IDataContext context, DelegateExecute nextExecute) in C:\Work\Reactive.XAF\tools\Xpand.XAF.ModelEditor\IDE\Rider\src\dotnet\ReSharperPlugin.Xpand\XpandModelEditorAction.cs:line 34`

**Comment by volokos** [comment]
because there is Xpand.XAF.ModelEditor.WinDesktop.exe file

**Comment by apobekiaris** [comment]
hmm there is an issue on this 

https://github.com/eXpandFramework/eXpand/issues/966

**Comment by apobekiaris** [comment]
ME works with Rider 22.2.4 currently and not the latest Rider

**Comment by apobekiaris** [comment]
missuderstand sorry, there are two apps one acts as bootstrapper to load the second app. The first app the bootstrapper is XAF version agnostic and download the version dependent from the online repo.

**Comment by volokos** [comment]
In releases page of [repo](https://github.com/eXpandFramework/Reactive.XAF/releases) i see only platform dependent version of ModelEditor
![image](https://user-images.githubusercontent.com/11853791/211565092-cb97074c-31f8-4450-be30-1ec78e6f6426.png)

**Comment by apobekiaris** [comment]
when plugin starts it extracts and saves locally if not exists.

**Comment by apobekiaris** [comment]
attaching all contents of my C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\ in case u wanna try them as is

https://e1.pcloud.link/publink/show?code=XZqafmZTO8xGsYMD2V3DiahJAmjxpbijHyy

there are many versions i just let them in

**Comment by apobekiaris** [comment]
let me know so I can remove the link once u got it

**Comment by volokos** [comment]
Thanks, i will try

**Comment by volokos** [comment]
So, i'm getting this error on me loading now:
The SDK 'Microsoft.NET.Sdk' specified could not be found. C:\Projects\VolokosFramework\VolokosFramework.Win\VolokosFramework.Win.csproj

**Comment by apobekiaris** [comment]
do u use the new SDK format on your csproj file?

**Comment by volokos** [comment]
Project Sdk="Microsoft.NET.Sdk" in csproj
and in global.json
`{
  "sdk": {
    "version": "6.0.0",
    "rollForward": "latestMajor",
    "allowPrerelease": true
  }
}`

**Comment by apobekiaris** [comment]
>The SDK 'Microsoft.NET.Sdk' specified could not be found. C:\Projects\VolokosFramework\VolokosFramework.Win\VolokosFramework.Win.csproj

screenshot me how do u get this?

**Comment by apobekiaris** [comment]
can u also share the top 10 lines of your csproj?

**Comment by volokos** [comment]
`0.01.23 17:19:23.392	Window closing: 
10.01.23 17:19:23.393	Window closed: 
Xpand.XAF.ModelEditor.Win Error: 0 : 10.01.23 17:19:23.418	================================================================================
The error occurred:

	Type:       InvalidProjectFileException
	Message:    The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Projects\VolokosFramework\VolokosFramework.Win\VolokosFramework.Win.csproj
	Data:       0 entries
	Stack trace:

   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at Xpand.XAF.ModelEditor.Module.Win.MSBuildExtensions.<>c__DisplayClass1_0.<Projects>b__1(ProjectInSolution projectInSolution) in C:\Work\Reactive.XAF\tools\Xpand.XAF.ModelEditor\IDE\ModelEditor.Win\Xpand.XAF.ModelEditor.Module.Win\MSBuildExtensions.cs:line 23
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1361
	InnerException is null
`

**Comment by apobekiaris** [comment]
looks like MSBuild framework has some issues and wondered if u used the unsupport non SDK format it looks fine. Can you try it in a non exe project also can u try it in a empty project as produced from the Xaf solution wizard

**Comment by apobekiaris** [comment]
check Xpand ME version >22.2.4 not out yet

**Comment by apobekiaris** [comment]
The pre-release [4.222.2.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.2.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Fix ME issues #970 #979](https://github.com/eXpandFramework/Reactive.XAF/commit/e76faca72205f9d51c68b67dde77c49f2fc0c157)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.222.2</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
