### ISSUE TITLE
HyperLinkPropertyEditor

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#971]
Hi Tolis,

I´ve got 2 Problems. Both can be viewed in the detached sample. (VS2022, DevExpress 22.2.3)

1. if I try to use the HyperlinkPropertyEditor in a DetailView (only in DetailView) I got the error
Object reference not set to an instance of an object.

   at Xpand.ExpressApp.Win.PropertyEditors.HyperLinkPropertyEditor.CreateControlCore()
   at DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.controlItem_QueryControl(Object sender, QueryControlEventArgs e)
   at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseQueryControl()

2. If I try to open the Xpand ModelEditor  I got the error
"Multiple DevExpress versions found...."

[DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/10394122/DXApplication4.zip)
![Screenshot 2023-01-11 171548](https://user-images.githubusercontent.com/43132306/211858747-34465f4d-eaae-4b28-bef5-586a6ae38038.png)

**Comment by apobekiaris** [comment]
did you read https://github.com/eXpandFramework/eXpand/issues/970

**Comment by apobekiaris** [comment]
I guess you use VS there might be an issue there the plugin is not update long time now will test and update u how it works

**Comment by CWolffIF** [comment]
Can I work without the plugin?

**Comment by apobekiaris** [comment]
:) I liked the question, it really depends if you want you can always find ways to open a Xaf Model. For example the Xaf Standalone ME is what the plugin uses with the convenience of keyboard shortcut and the Model list. However since I guess you working one one solution you could create a command line script to open your models from a fixed path

**Comment by CWolffIF** [comment]
Open it in VS it always loads down the Version 4.212.9.4. with the error.
Do you have a sample how to open it in command line?

**Comment by volokos** [comment]
> Hi Tolis,
> 
> I´ve got 2 Problems. Both can be viewed in the detached sample. (VS2022, DevExpress 22.2.3)
> 
> 1. if I try to use the HyperlinkPropertyEditor in a DetailView (only in DetailView) I got the error
>    Object reference not set to an instance of an object.
>    at Xpand.ExpressApp.Win.PropertyEditors.HyperLinkPropertyEditor.CreateControlCore()
>    at DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
>    at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.controlItem_QueryControl(Object sender, QueryControlEventArgs e)
>    at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseQueryControl()
> 2. If I try to open the Xpand ModelEditor  I got the error
>    "Multiple DevExpress versions found...."
> 
> [DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/10394122/DXApplication4.zip) ![Screenshot 2023-01-11 171548](https://user-images.githubusercontent.com/43132306/211858747-34465f4d-eaae-4b28-bef5-586a6ae38038.png)

Yes, i cannot solve the problem with "Multiple DevExpress versions found...." already third day with rider plugin :(

**Comment by CWolffIF** [comment]
I managed to get the standalone ME.
Try to open my projct, I got the error:
![image](https://user-images.githubusercontent.com/43132306/212044038-4e5520f9-4044-4840-bec7-68cd873c70b6.png)

But the nuget reference is set and the file (System.Drawing.Common.dll vs 7.0.0.0) is in the debug.
Any Idea?

**Comment by apobekiaris** [comment]
my guess is it relates to whom uses .net7 and this is not the ME so is about your project

**Comment by apobekiaris** [comment]
I reviewed the case and I working on it, looks like we have a related bug in the source code as well so I need to release Xpand libs first

**Comment by CWolffIF** [comment]
Ok, good luck

**Comment by apobekiaris** [comment]
until I will manage to publish it you can try this one

https://e1.pcloud.link/publink/show?code=XZeq1mZlkmTiINqVb8bDx54KL3p6mDzRldk

**Comment by apobekiaris** [comment]
after the model view is open you use the `Configure` action on the bottom right and you Navigate to Application\ModelEditor and set the UsePrerelase attribute.

rember to clean up folders b4 running it

**Comment by CWolffIF** [comment]
Ok, it works with a simple project. Thanx.

In my project I get the error with the System.Drawing.Common.dll vs 7.0.0.0.. We use .net6. Any idea?

**Comment by apobekiaris** [comment]
sorry I misses your question, anyways what heppens if u add the file manually to the bin?


btw the pluin is now in the VS market place for direct download nothing changed from the posted version

**Comment by apobekiaris** [comment]
> We use .net6. Any idea?

some of your dependecies then must be targeting .net7 so it needs this version. the story is well know u remove them all one by one to find what to blame and if u need a second opinion feel free to post

**Comment by CWolffIF** [comment]
Hi,

the HyperlinkPropertyEditor throws an Error in CreateControlCore cause the _hyperlinkEdit.MaskBox in Null.

        protected override object CreateControlCore()
        {
            _hyperlinkEdit = new HyperLinkEdit();
            _hyperlinkEdit.MaskBox.Mask.MaskType = MaskType.RegEx;
            var maskProperties = _hyperlinkEdit.MaskBox.Mask;
            maskProperties.EditMask = UrlEmailMask;
            return _hyperlinkEdit;
        }

**Comment by CWolffIF** [comment]
OK I found it

System.DirectoryServices.AccountManagement 7.0.0 needs  System.Drawing.Common 7.0.0.
Both support .net6 and .net7, but it doesn´t work.

Setting both to 
System.DirectoryServices.AccountManagement 6.0.0 needs  System.Drawing.Common 6.0.0.
it works. Puh......

**Comment by apobekiaris** [comment]
> the HyperlinkPropertyEditor throws an Error in CreateControlCore cause the _hyperlinkEdit.MaskBox in Null.

does it work on any new solution? is it a side effect from your part?

**Comment by CWolffIF** [comment]
Yes, in a new sample
[DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/10456961/DXApplication4.zip)

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.400.0) includes commit that relate to this task:

* [HyperLinkPropertyEditor Maskbox exception #971](https://github.com/eXpandFramework/eXpand.lab/commit/7602c2fbc7fbf61c61df1e04b4347202ca7b7dd5)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
The pre-release [4.222.2.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.2.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [VS 22.2 XpandModelEd #970itor #971](https://github.com/eXpandFramework/Reactive.XAF/commit/104f885eb5bc344216ce01f28e4c91556ba28eac)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.222.2</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.222.2</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
