### ISSUE TITLE
XpandModelEditor not showing up

### ISSUE THREAD

**Issue by DaveFz** [eXpandFramework/eXpand#975]
Hello,

The Xpand ModelEditor is not showing up in Rider 2022.2.4 (DevExpress version: 22.1.6)
After clicking:
![image](https://user-images.githubusercontent.com/47706547/214838963-4689924f-3dd8-438a-9df7-a483e24e4826.png)
This shows up in the bottom right corner:
![image](https://user-images.githubusercontent.com/47706547/214839026-77e3c572-5d24-4125-9f87-47f571606ff0.png)
But unfortunately the popup window is not showing up.

It did show up like 2 times though but that's it :D

Thank you!

**Comment by DaveFz** [comment]
Okay I figured out that it was due to having VS2022 opened parallel to Rider.
But now the problem is, that the popup-window is showing up for 1 second and then instantly closes:
![image](https://user-images.githubusercontent.com/47706547/214840791-bdfb40ba-38c4-4c50-a1e9-26a960625895.png)

**Comment by apobekiaris** [comment]
usualy something wrong with the process try to kill the XpandModelEditor processes and try to use keyboard to control it

e.g. what i do is ctral+a bring up the Rider actions and type `Xpand`

**Comment by apobekiaris** [comment]
see also https://github.com/eXpandFramework/eXpand/issues/970

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
