### ISSUE TITLE
How to add targets framework

### ISSUE THREAD

**Issue by Muwanguzi124** [eXpandFramework/eXpand#976]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
How do I add a net48 targets  and build both Rx.Xaf and expand repos?
I can build locally both repos as they are.

**Comment by apobekiaris** [comment]
Use the last commit that includes net48 and selectively merge all  changes till now could be an answer.

**Comment by Muwanguzi124** [comment]
Ok. Works for the rx.xaf repo.
However last eXpand commit was net461

**Comment by apobekiaris** [comment]
>However last eXpand commit was net461

no idea what u mean by this

**Comment by apobekiaris** [comment]
you better describe your problem in detail rather than asking generic questions

**Comment by Muwanguzi124** [comment]
I would like to build nugets for .net 4.8 for [eXpand](https://github.com/eXpandFramework/eXpand)
 probably from [22.1.6](https://github.com/eXpandFramework/eXpand/releases/tag/22.1.602.0)

**Comment by apobekiaris** [comment]
assuming your projects are .net48 and u want to use the eXpand scripts to create them you check with the `CreateXpandNugets.ps1`

**Comment by apobekiaris** [comment]
But really why that hassle? the script is about eXpand and has a ton of shit unrelated to your case. Is there from before nuget becomes family

Alternatively u can generate your own p[ackages in a Directoty.Build like https://www.rubberduckdev.com/msbuild-nuget/

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
