### ISSUE TITLE
Xpand.VSIX-22.2.401.0

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#977]
Hi,

on my system VS2019 and VS2022 are installed.
if try to install the extension only VS2019 can be selected. How can I install the extension to VS2022 ?

**Comment by CWolffIF** [comment]
As a workaround I installed the 
XVSIX64.vsix
again you send me once. I can open the model.

**Comment by apobekiaris** [comment]
>on my system VS2019 and VS2022 are installed.

Unfortunately I do not use VS2019 years now, the plugin as well is not compatible with VS2019 years as well.

The plugin can be installed either from within VS/Extensions or u can download it manually from VS marketplace. It is the same XVSIX64.vsix.

https://marketplace.visualstudio.com/items?itemName=eXpandFramework.XVSIX64

**Comment by CWolffIF** [comment]
Thanks.
