### ISSUE TITLE
RoleModelDifferenceObject usage

### ISSUE THREAD

**Issue by Siratigui** [eXpandFramework/eXpand#983]
Hi, 

I created a **Role Model** and attached a role to it. I expected users under the attached role to use the model but it always autocreates a **User Model** at the first loggon.

Am I missing any parameter?
Thanks.

**Comment by apobekiaris** [comment]
>but it always autocreates a User Model at the first loggon

to me at least it is unclear what is the problem. Yes you always need a User Model since u logon as a user however the Role Differences are also respsected. Make sure you are not on some kind of overlap. I mean for e.g.g change your role model AllowEdit on a listview and logon and test the listview

**Comment by Siratigui** [comment]
Thank you for the reply. Now I get it.
