### ISSUE TITLE
Does Xpand support multiple databases in Blazor?

### ISSUE THREAD

**Issue by pjcunningham** [eXpandFramework/eXpand#984]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
Does Xpand support multiple databases in Blazor? If so how/where do I register the connections?

I'm using DevExpress example e4896, [Github code([e4896](https://github.com/DevExpress-Examples/XAF_how-to-connect-different-xpo-data-models-to-several-databases-within-a-single-application-e4896))] in researching the possibility of having two database connections in a Blazor app. One connection for a legacy database and then a second connection for a new database design.

e4896 actually uses three databases and works in itself, adding Xpand causes exception in Xpand on application startup

```csharp
   at Xpand.XAF.Modules.Reactive.Services.ObjectSpaceProviderExtensions.CreateObjectSpace(DevExpress.ExpressApp.IObjectSpaceProvider, DevExpress.ExpressApp.IObjectSpace)

```
See my `ConfigureServices` below. Xpand modules e.g. RefreshList works fine when the `NonPersistent` objectspace and `CommonModule` objectspace are added.

```csharp
public void ConfigureServices(IServiceCollection services) {
        services.AddSingleton(typeof(Microsoft.AspNetCore.SignalR.HubConnectionHandler<>), typeof(ProxyHubConnectionHandler<>));

        services.AddRazorPages();
        services.AddServerSideBlazor();
        services.AddHttpContextAccessor();
        services.AddScoped<CircuitHandler, CircuitHandlerProxy>();
        services.AddXaf(Configuration, builder => {
            builder.UseApplication<TwoXpoModelsForDifferentDatabasesBlazorApplication>();
            builder.Modules
                .AddConditionalAppearance()
                .AddValidation(options => {
                    options.AllowValidationDetailsAccess = false;
                })
                .Add<CommonModule.CommonModule>()
                .Add<ClassLibrary1.XafModule1>()
                .Add<ClassLibrary2.XafModule2>()
                .Add<TwoXpoModelsForDifferentDatabasesBlazorModule>();
            builder.ObjectSpaceProviders.AddNonPersistent();
            CommonModule.CommonModule.SetupObjectSpace(builder.ObjectSpaceProviders, Configuration);
            // ADDING second and/or third ObjectSpace provider causes exception in Xpand
            //ClassLibrary1.XafModule1.SetupObjectSpace(builder.ObjectSpaceProviders, Configuration);
            //ClassLibrary2.XafModule2.SetupObjectSpace(builder.ObjectSpaceProviders, Configuration);
            builder.Security
                .UseIntegratedMode(options => {
                    options.RoleType = typeof(PermissionPolicyRole);
                    // ApplicationUser descends from PermissionPolicyUser and supports the OAuth authentication. For more information, refer to the following topic: https://docs.devexpress.com/eXpressAppFramework/402197
                    // If your application uses PermissionPolicyUser or a custom user type, set the UserType property as follows:
                    options.UserType = typeof(CommonModule.BusinessObjects.ApplicationUser);
                    // ApplicationUserLoginInfo is only necessary for applications that use the ApplicationUser user type.
                    // If you use PermissionPolicyUser or a custom user type, comment out the following line:
                    options.UserLoginInfoType = typeof(CommonModule.BusinessObjects.ApplicationUserLoginInfo);
                    options.UseXpoPermissionsCaching();
                })
                .AddPasswordAuthentication(options => {
                    options.IsSupportChangePassword = true;
                });
        });
        services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(options => {
            options.LoginPath = "/LoginPage";
        });
    }
```

**Comment by apobekiaris** [comment]
>Does Xpand support multiple databases in Blazor? If so how/where do I register the connections?

shortly yes it is unrelated to eXpand but sure errors might exist and many as we do not have tests for it. In any case I can examine the RefreshLstView case after u post a sample

**Comment by pjcunningham** [comment]
Hello Apostolis,

Sorry, I forgot to post the sample project - see attached. The User's ListView has the Xpand refresh list functionality.

Lines 45 & 46 in `TwoXpoModelsForDifferentDatabases.Blazor.Server/startup.cs` have the commented out additional ObjectSpace providers.

[e4896+Xpand.NET.zip](https://github.com/eXpandFramework/eXpand/files/10785465/e4896%2BXpand.NET.zip)

Paul.

**Comment by apobekiaris** [comment]
on my side at least I get a stackoverflow on the PopulateAdditionalObjectSpaces implementation. I am not sure to the why but since this is a special case, I added an option to disable it.

```cs
ReactiveModule.PopulateAdditionalObjectSpaces = false;
```

**Comment by apobekiaris** [comment]
The pre-release [4.222.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.3.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Option to disable PopulateAdditionalObjectSpaces #984](https://github.com/eXpandFramework/Reactive.XAF/commit/705d4f7bd4b3250109a07667fe03f50468e3e2d6)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.222.3</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.222.3</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by pjcunningham** [comment]
Hello Apostolis,

Thanks for adding this. I'm try to test but I don't see this property in [4.222.3.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.3.0) ? I'm using your NugetServer.

![2023-03-09_12-47-15](https://user-images.githubusercontent.com/360727/224028222-0fd5b74f-faa7-4f47-bf1d-354fcbd5a5e8.jpg)

**Comment by apobekiaris** [comment]
it is a static property

```cs
ReactiveModule.PopulateAdditionalObjectSpaces = false;
```

**Comment by pjcunningham** [comment]
Ha ha - I'm an idiot!

**Comment by pjcunningham** [comment]
Still not seeing the static property. This is my decompiled source:

```csharp
#region Assembly Xpand.XAF.Modules.Reactive, Version=4.222.3.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958
// C:\Users\Paul\.nuget\packages\xpand.xaf.modules.reactive\4.222.3\lib\net6.0\Xpand.XAF.Modules.Reactive.dll
// Decompiled with ICSharpCode.Decompiler 7.1.0.6543
#endregion

using System;
using System.Reactive.Subjects;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.Model;
using DevExpress.ExpressApp.Model.Core;
using DevExpress.ExpressApp.SystemModule;
using Xpand.XAF.Modules.Reactive.Extensions;

namespace Xpand.XAF.Modules.Reactive
{
    public sealed class ReactiveModule : ReactiveModuleBase
    {
        private readonly Subject<ModelInterfaceExtenders> _extendingModelSubject = new Subject<ModelInterfaceExtenders>();

        private readonly Subject<ModelNodesGeneratorUpdaters> _generatorUpdaterSubject = new Subject<ModelNodesGeneratorUpdaters>();

        public static ReactiveTraceSource TraceSource { get; set; }

        internal IObservable<ModelInterfaceExtenders> ExtendingModel => _extendingModelSubject;

        static ReactiveModule()
        {
            TraceSource = new ReactiveTraceSource("ReactiveModule");
        }

        public ReactiveModule()
        {
            base.RequiredModuleTypes.Add(typeof(SystemModule));
        }

        public override void ExtendModelInterfaces(ModelInterfaceExtenders extenders)
        {
            base.ExtendModelInterfaces(extenders);
            _extendingModelSubject.OnNext(extenders);
            extenders.Add<IModelApplication, IModelApplicationReactiveModules>();
            extenders.Add<IModelReactiveModules, IModelReactiveModule>();
        }

        public IObservable<ModelNodesGeneratorUpdaters> WhenGeneratorUpdaters()
        {
            return _generatorUpdaterSubject;
        }

        public override void AddGeneratorUpdaters(ModelNodesGeneratorUpdaters updaters)
        {
            base.AddGeneratorUpdaters(updaters);
            _generatorUpdaterSubject.OnNext(updaters);
        }

        public override void Setup(ApplicationModulesManager moduleManager)
        {
            base.Setup(moduleManager);
            moduleManager.Connect().Subscribe(this);
        }
    }
```

**Comment by apobekiaris** [comment]
>4.222.3.0

looks like u decompile a public and not a lab version Revision>0

**Comment by apobekiaris** [comment]
hmm looking at it closer it looks we have some issue with the builds. THe notifications always refer to lab versions which should be a bit larger by revistion of the public version. Currently the lab is on 4.222..2 which is wrong but probably the source is included juding from the publication date. You can try it  no harm until I fix the versions

**Comment by apobekiaris** [comment]
latest version on lab is now fixed

```p1
PS C:\Box\AutoHotKey> Get-XpandPackages -Source Lab -PackageType XAFModules

Id                                                Version    Source
--                                                -------    ------
Xpand.XAF.Modules.AutoCommit                      4.222.3.1  Lab
Xpand.XAF.Modules.Blazor                          4.222.3.1  Lab
Xpand.XAF.Modules.BulkObjectUpdate                4.222.3.1  Lab
Xpand.XAF.Modules.CloneMemberValue                4.222.3.1  Lab
Xpand.XAF.Modules.CloneModelView                  4.222.3.1  Lab
Xpand.XAF.Modules.Email                           4.222.3.1  Lab
```

**Comment by pjcunningham** [comment]
Hello Apostolis,

That's fixed it, thanks!

```csharp
public void ConfigureServices(IServiceCollection services) {

    services.AddXaf(Configuration, builder =>
    {
        // stuff

        builder.Modules.Add<ReactiveModule>(options => {
            ReactiveModule.PopulateAdditionalObjectSpaces = false;
        });
        
        builder.Modules.Add<RefreshViewModule>();

        // more stuff

    });

}
```

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.400.0) includes commit that relate to this task:

* [Update rx packages #984](https://github.com/eXpandFramework/eXpand.lab/commit/e8881acdb371c4438a17af045ef2b4bfea095a75)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.
