### ISSUE TITLE
EF Core (Rather than XPO)

### ISSUE THREAD

**Issue by finchsimon** [eXpandFramework/eXpand#985]
I am wanting to use the JobScheduler that utilizes Hangfire and when I get my Blazor UI Project Setup it complains with 'No suitable constructor was found for entity type 'CronExpression'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'session' in 'CronExpression(Session session)'.

Does eXpand Support Entity Framework Core classes rather than Xpo and if not how can I get it to work with the DevExpress.Persistent.BaseImpl.EF.BaseObject?

**Comment by apobekiaris** [comment]
Short answer there are no interfaces you can possibly make it work as per https://supportcenter.devexpress.com/ticket/details/e4896/how-to-connect-different-data-models-to-several-databases-within-a-single-application

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
