### ISSUE TITLE
'powershell.exe' is not recognized as an internal or external command when Building in Docker

### ISSUE THREAD

**Issue by dexter-ss** [eXpandFramework/eXpand#987]
We're trying to build an app with Xpand.XAF.Modules.Blazor and Xpand.XAF.Modules.JobScheduler.Hangfire as dependencies. When trying to build it using Docker build, we get an error:

_C:\Users\ContainerUser\.nuget\packages\xpand.versionconverter\4.222.5\build\Xpand.VersionConverter.targets(4,9): error : 'powershell.exe' is not recognized as an internal or external command, [C:\src\********XAF.Blazor.Hangfire\*******XAF.Blazor.Hangfire.csproj]_

it works normally when building outside docker. Do you have any suggestion on how to workaround this or skip the file when building in Docker?

**Comment by apobekiaris** [comment]
your options apparently are two.

1. You remove the Xpand.VersionConverter.targets
2. Or you install powershell 

```
RUN apt-get update && \
    apt-get install -y powershell

```

**Comment by dexter-ss** [comment]
Thank you for your reply. We're able to resolve the issue bay changing the image from 6.0 to 6.0-windowsservercore-ltsc2019.
