### ISSUE TITLE
SequenceGenerator in combination with NonsecuredObjectSpace

### ISSUE THREAD

**Issue by yunits** [eXpandFramework/eXpand#988]
Hello Mr. Bekiaris, I have a small question:

When using your hangfire module, I have to create a new NonsecuredObjectSpace.

I also use your SequenceGenerator and it looks like there are no sequences generated, if creating Objects in NonsecuredObjectSpace.

How can I obtain next sequence?

**Comment by apobekiaris** [comment]
Without a sample I really cannot answer.

**Comment by yunits** [comment]
I found a workaround for myself but I guess it is not safe as it doesn't lock sequence table.

I created a sample. [DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/11128977/DXApplication1.zip)

Just run it, Create an Order and see that there is a sequence generated.
Then create a new Job "Import Orders", Trigger and see there are  no sequences generated.

**Comment by apobekiaris** [comment]
I did not really had the time to look at it, will do thnks

**Comment by apobekiaris** [comment]
your sample does not use a secured ObjectSpace in addition you use application.CreateNonSecuredObjectSpace(typeof(Order)) which it will create an updating objectspace and those are not monitor. use application.CreateObjectSpace(typeof(Order)) instead

**Comment by yunits** [comment]
my example was not fully correct. I forgot to include authentication with password I guess.

If using application.CreateObjectSpace(typeof(Order)) then authentication in code is needed, therefore I used NonSecuredObjectSpace.

Anyway, thanks for your response. I will authenticate in code.

**Comment by apobekiaris** [comment]
that's the reason I am asking repro samples to avoid missunderstanding and time spend in vain. Anyways post a better sample please

**Comment by apobekiaris** [comment]
in addition we have this test in the source

```cs
        [XpandTest]
        [TestCase(nameof(Platform.Win))]
        public void WhenObjectSpaceCreated(string platformName){
            var platform = GetPlatform(platformName);
            using var application = DefaultReactiveModule(platform).Application;
            using var exiTest = application.WhenObjectSpaceCreated().Test();

            application.CreateObjectSpace();
            application.CreateNonSecuredObjectSpace(typeof(R));
            

            exiTest.Items.Count.ShouldBe(2);
        }
```

it asserts that `WhenObjectSpaceCreated` which is used from the `SequenceGenerator` emit when `CreateNonSecuredObjectSpace`

**Comment by yunits** [comment]
Thanks, you already answered my question. NonSecuredObjectSpace can't be used with SequenceGenerator.

The fact that CreateObjectSpace has to be authenticated when using in a service is known. That has nothing to do with Xpand, therefore I won't bother you with that.
Similar question asked here for example: https://supportcenter.devexpress.com/ticket/details/t1159809/manually-authenticate-an-user-in-an-service

**Comment by apobekiaris** [comment]
> NonSecuredObjectSpace can't be used with SequenceGenerator.

I do not think this is correct assumption as per the unit test I posted

**Comment by yunits** [comment]
here you go with a new sample [DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/11284836/DXApplication4.zip)
I have created three jobs for testing purposes
1. using NonSecuredObjectSpace (will create Orders without Sequence)
2. using SecuredObjectSpace (nothing will happen)
3. using SecuredObjectSpace with authentication (will create Orders without Sequence)

**Comment by yunits** [comment]
@apobekiaris 
I used my existing sample to try to reproduce an issue. For that I just updated to 4.222.13.
https://github.com/eXpandFramework/eXpand/issues/988#issuecomment-1516045038

Sequences are generated but SequenceStorage stays at same value, for example 100.
Therefore, if you trigger a Job multiple times it would generate the following output
100
101
102
103..
and then
100
101
102
103..

**Comment by apobekiaris** [comment]
>if you trigger a Job multiple times it would generate the following output

elab

**Comment by yunits** [comment]
@apobekiaris I guess this comment is for you, right?

**Comment by apobekiaris** [comment]
I meant post details e.g. how do u trigger the job or anything is related to this case

**Comment by yunits** [comment]
@apobekiaris 
Create a Job "Import orders Secured".
Trigger.
Go to orders and see the sequences generated.
Trigger Job again.
[DXApplication4.zip](https://github.com/eXpandFramework/eXpand/files/11597551/DXApplication4.zip)

Go to orders and see the duplicate sequences, because sequence storage has not been incremented permanent.

**Comment by yunits** [comment]
is that what you need?

**Comment by apobekiaris** [comment]
looks so, but did not have the time to research it yet. I ll keep u posted

**Comment by expand** [comment]
The pre-release [4.222.11.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.11.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator in combination with NonsecuredObjectSpace #988](https://github.com/eXpandFramework/Reactive.XAF/commit/ef1c7dda61b6bf13d708256a8928ebf88853571f)
* [SequenceGenerator in combination with NonsecuredObjectSpace #988](https://github.com/eXpandFramework/Reactive.XAF/commit/51b28ee6649ce92464b6e75b254e367cec839eaa)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.222.13</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
