### ISSUE TITLE
JobScheduler.Notification: The type or namespace name 'Notification' does not exist 

### ISSUE THREAD

**Issue by qwertybba** [eXpandFramework/eXpand#991]
Hello;
After flowing the documents on how to install  **JobScheduler.Notification** module on **XAF Blazor 22.2.5**
`<PackageReference Include="Xpand.XAF.Modules.JobScheduler.Notification" Version="4.222.6" />`

I have added this line of code to register the module
` RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.JobScheduler.Notification.JobSchedulerNotificationModule));`

But then I got this error message

> The type or namespace name 'Notification' does not exist in the namespace 'Xpand.XAF.Modules.JobScheduler' (are you missing an assembly reference?)

I changed it to
`RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.JobScheduler.Hangfire.Notification.JobSchedulerNotificationModule));`
Is that correct or am I missing something?

**Comment by apobekiaris** [comment]
yes the docs are outdated a bit

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
