### ISSUE TITLE
New SVG for DashboardModule

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#993]
Hi Tolis,

can u use new SVG images for the Dashoard Module to get a fresher look?
Attached samples.

[Dashboard.zip](https://github.com/eXpandFramework/eXpand/files/11359495/Dashboard.zip)

**Comment by apobekiaris** [comment]
sure, can you detail me what is you want me to do not to miss something?

**Comment by CWolffIF** [comment]
Hi,
in the project are .png. Maybe you could replace them with the new .svg.

![image](https://user-images.githubusercontent.com/43132306/235355723-60dceb20-33bd-4a5a-8adb-c11c16ff2b89.png)

**Comment by CWolffIF** [comment]
Hi,
and is there a time planing to compile against 22.2.6? Cause there is a problem correction in devexpress that I need.

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.600.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.600.0) includes commit that relate to this task:

* [Replace images #993](https://github.com/eXpandFramework/eXpand.lab/commit/afde15f63e58be5598226b9ae8def692a20dd35d)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment]
Hi Tolis,

I tested it. Now the Dashboard group and the Dashboards itself has no Image.

![image](https://user-images.githubusercontent.com/43132306/236425928-043ae450-e0f7-48a7-b5d3-7b798ca7264d.png)

**Comment by CWolffIF** [comment]
I saved the images as embedded resources in my project and it works.....

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.601.1](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.601.1) includes commit that relate to this task:

* [Dashboard images are not embedded #993](https://github.com/eXpandFramework/eXpand.lab/commit/7fb7b0ddfed63f861bdd12164c9eb49ebc0109f9)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.
