### ISSUE TITLE
Adding a user interface for configuring and sending email

### ISSUE THREAD

**Issue by qwertybba** [eXpandFramework/eXpand#995]
Hello
This feature will allow Blazor users to easily set up their email accounts, choose recipients, compose messages, and send them with a click of a button. This feature would improve the user experience and functionality of the software.

 **I appreciate your hard work and dedication.**

**Comment by apobekiaris** [comment]
Your suggestion is not clear the Email module I guess you refer has events for that reason

**Comment by qwertybba** [comment]
> Your suggestion is not clear the Email module I guess you refer has events for that reason

I meant in the browser, not in the model editor

**Comment by apobekiaris** [comment]
so u want a UI to config? Is that what you meant? Really without clear instructions resulting in minimum resources spent I cannot help much. Unless you plan to sponsor an update of course or send your own PR

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
