### ISSUE TITLE
Xpand model editor don't open, because it is being used by another process.

### ISSUE THREAD

**Issue by DavisCacici** [eXpandFramework/eXpand#998]
Hi, I try open the plugin xpand model editor from Rider IDE, but I have the follow: 

The process cannot access the file 'C:\Users\davis.cacici\AppData\Roaming\Xpand.XAF.ModelEditor.Win\Xpand.XAF.ModelEditor.Win\Ready.txt' because it is being used by another process.

I searched this process, I didn't see anything

**Comment by apobekiaris** [comment]
kill the process manually and try again?

**Comment by DavisCacici** [comment]
Already tried

**Comment by apobekiaris** [comment]
I meant something like this

```ps1
Get-Process Xpand.XAF.ModelEditor.Win|kill
```

**Comment by DavisCacici** [comment]
I tried it, but I have same error

**Comment by DavisCacici** [comment]
I make it, also uninstall plugin and reinstall but nothing

**Comment by apobekiaris** [comment]
Does it happen with all solutions? what the version of ME in your roaming folder

**Comment by DavisCacici** [comment]
Yeah, it happen with all solutions, and roaming folder is on my account

**Comment by apobekiaris** [comment]
which is?

**Comment by DavisCacici** [comment]
2022.2.6.0

**Comment by apobekiaris** [comment]
also what folders do  have in C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop\

**Comment by DavisCacici** [comment]
Ok, I understand, version is 4.222.7.0. Do you ask it?

**Comment by apobekiaris** [comment]
looks the latest sorry I am out of suggestions currently and the case is not reproducible

**Comment by DavisCacici** [comment]
Ok, thanks for your help
