### ISSUE TITLE
.NET Framework version error.

### ISSUE THREAD

**Issue by WallnerRepo** [eXpandFramework/eXpand#999]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Error The package 'eXpandLib 22.2.602' could not be installed. You are trying to install this package in a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain assembly references or content files compatible with this framework. For more information, please contact the package author.
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
-I just installed clean Visual Studio 2022 Community Edition and Devexpress 22.2.6
-I tried to run it in a project with .NET Framework version 4.8, it doesnt worked, so i tried with 4.7.2 and with 4.6.2.
but it didn't work.
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
Install the modules.

Not sure if i misunderstand something or i am doing somesthing wrong. But i remember that i installed these modules in the past on other project and it was easy.

Thanks in advance.

**Comment by apobekiaris** [comment]
>'.NETFramework,Version=v4.6.2',

we only use .NET6 now .NET7 is not yet supported

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
